### ISSUE TITLE
Cleanup and move some of the oudated CWIKI pages elsewhere

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#10178]
**Description**

Move the documentation from the old pages in  CWiki to other places:

- [x] Committers' Guide [TODO: Move to dev] #10179 
- [x] Common Pitfalls [TODO: Move to Docs] #10180 
- [x] Community Guidelines [TODO: Move to CONTRIBUTING.rst] #10181 
- [x] Contributors' Guide [TODO: Move to CONTRIBUTING.rst] #10187 
- [ ] First time contributor's workshop [TODO: Move to airflow.apache.org/blogs] #10182 
- [x] Releasing Airflow [TODO: Move to dev] #10183 
- [x] Roles [TODO: Move to CONTRIBUTING.rst] #10184 
- [x] Scheduler Basics [TODO: Move to Docs] #10185 
- [x] Tips and Tricks for Oracle Shops [TODO: Move to Docs] #10186 
- [x] Announcement [TODO: Move to airflow.apache.org] #10196 
- [x] Add "Ecosystem" page  [ TODO: Add Ecostystem page to airflow.apache.org] #10274 

**Use case / motivation**

We decided to keep most of our in-progress work in Github Issues. Discussion about it [here](https://lists.apache.org/thread.html/rf3d9ed8b5cf8f39921b98ddac614500ed9f0ff2b0f56c96a9948e409%40%3Cdev.airflow.apache.org%3E)

**Context**

We are now cleaning and restructuring the docs to be more consistent. It's mostly based on who the "Readers" of the documentation are:

* [Airflow Docs](https://github.com/apache/airflow/tree/master/docs) - those are mostly the users of Airflow. People who either want to set up and manage Airflow or those who want to write Dags or develop custom operators/Hooks etc. 

* [Github Docs](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst) - Contributors and Committers. Basically, developers of Airflow

* [Airflow Site](https://airflow.apache.org) - mostly decision-makers, those who would like to understand whether Airflow is a good choice for them. Also, people who want to learn Airflow and decide whether they should become users or contributors or both. Basically this should be an index of "Everything Airflow" and a starting point for everything else.

* [CWiki](https://cwiki.apache.org/confluence/display/AIRFLOW/) - we keep it mostly for AIPs (Airflow Improvement Proposals). And the planning of the work we do for Airflow 2.0. But it's very likely - [discussion here] (https://lists.apache.org/thread.html/rf58348edc3ed4ad8dd167cdbeda0a2a5219a2ab1725d4e1b7e980d9a%40%3Cdev.airflow.apache.org%3E) - that we will get rid of it completely and move all the new AIPs to Github Issues. Possibly also future planning.

----------

Some of the outdated documentation was moved to [Archives](https://cwiki.apache.org/confluence/display/AIRFLOW/Archives) but some of the pages contain useful information that should simply be moved elsewhere.

**Comment by Angelvicks** [comment]
Hello, I am an Outreachy Applicant. Please can I work on this issue?

**Comment by Angelvicks** [comment]
Hello @potiuk ,please for the link to create a user at the confluence

**Comment by potiuk** [comment]
Just register new user when you get to cwiki.apache.org

**Comment by eladkal** [comment]
Closing as all items were completed / moved to dedicated issue
