### ISSUE TITLE
Testing status of the Providers released 2021.05.01

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#15623]
We are releasing new providers for Airflow with latest fixes - RCs released on 2021.05.01. 

This is a kind request for authors of the changes. It would be great if you could verify if the providers do what they are supposed to do :).

- [ ]  Amazon: @suiting-young @Tonkonozhenko @dstandish 
    https://pypi.org/project/apache-airflow-providers-amazon/1.4.0rc1/ 
- [ ] Apache Spark: @suiting-young @cadet354 
     https://pypi.org/project/apache-airflow-providers-apache-spark/1.0.3rc1/ 
- [x] Cncf.Kubernetes: @jedcunningham @kaxil @dimberman 
      https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/1.2.0rc1/
- [x] Docker: @jsemric @dimberman @akki 
      https://pypi.org/project/apache-airflow-providers-docker/1.2.0rc1/
- [ ] Elasticsearch: @millin  @suiting-young
      https://pypi.org/project/apache-airflow-providers-elasticsearch/1.0.4rc1/
- [x] Ftp: @CelastrinaLadon 
      https://pypi.org/project/apache-airflow-providers-ftp/1.1.0rc1/
- [x] Google: @kaxil @potiuk @pateash 
      https://pypi.org/project/apache-airflow-providers-google/3.0.0rc1/
- [x] JIRA:  @suiting-young
      https://pypi.org/project/apache-airflow-providers-jira/1.0.2rc1/
- [x]  Microsoft.azure: @suiting-young @potiuk
     https://pypi.org/project/apache-airflow-providers-microsoft-azure/2.0.0rc1/
- [ ]  Microsoft.mssql: @dstandish  
    https://pypi.org/project/apache-airflow-providers-microsoft-mssql/1.1.0rc1/
- [ ] Microsoft.winrm: @andrewgodwin 
    https://pypi.org/project/apache-airflow-providers-microsoft-winrm/1.2.0rc1/
- [x] Postgres: @zhzhang 
    https://pypi.org/project/apache-airflow-providers-postgres/1.0.2rc1/
- [x] Sftp: @pgaganon @CelastrinaLadon
    https://pypi.org/project/apache-airflow-providers-sftp/1.2.0rc1/
- [x] Snowflake: @mobuchowski 
    https://pypi.org/project/apache-airflow-providers-snowflake/1.3.0rc1/

No changes - just dependencies:
- [x] Apache Beam 

Please comment below if/when you test the RC with your changes.

**Comment by potiuk** [comment]
The voting for the RC packages should close by Wednesday 5th of May mid-day CEST. It would be great if majority of the changes/fixes is verified by then :).

Voting thread in the devlist:  https://lists.apache.org/thread.html/rb3fb597796a5b1bf83f97879e6783049dc8f2496b594bc5f3641eee3%40%3Cdev.airflow.apache.org%3E

**Comment by zhzhang** [comment]
I had another [PR](https://github.com/apache/airflow/pull/15412) on the postgres provider get merged just now, any chance it can be included in the RC?

**Comment by potiuk** [comment]
Unless this is really serious, I think I'd prefer to leave it for a follow-up ad-hoc release (1.0.3)? The mechanics of releasing providers works best if we release them in batches. From the bug description, I do not think the bug was critical (correct me if I am wrong?) so 1.0.2 will still be mostly working OK, so we can easily make a (very fast) 1.0.3 release right after?

**Comment by potiuk** [comment]
Looking forward to some testing :). Doing some testing  today myself.

**Comment by pateash** [comment]
@potiuk I have tested the changes for #15245

**Comment by jsemric** [comment]
tested the changes added by https://github.com/apache/airflow/pull/14642 involving docker provider

**Comment by mobuchowski** [comment]
Tested snowflake. Looks good.

**Comment by zhzhang** [comment]
Tested postgres changes against a Redshift cluster, looks good to me!

**Comment by jedcunningham** [comment]
Tested the `cncf.kubernetes` changes (except #15388) and had no issues.

**Comment by CelastrinaLadon** [comment]
SFTP and FTP Providers working well  All Green 😁

[image: image.png]

[image: image.png]

ในวันที่ พ. 5 พ.ค. 2021 เวลา 05:34 Jed Cunningham ***@***.***>
เขียนว่า:

**Comment by potiuk** [comment]
Cool! last chance to test some of the others :). Would be great to get Amzon, Spark, Elasticsearch, Micorosft ones also at least smoke-tested :)

**Comment by potiuk** [comment]
Thanks to all who tested their changes. I am closing this one - and proceeding with the release. The changes on the remaining providers look good from the inspection.
