### ISSUE TITLE
gitpodify Apache Airflow - online development workspace

### ISSUE THREAD

**Issue by j143** [apache/airflow#16480]
**Description**

Aims to create a online workspace for airflow project development with [gitpod.io ↗](https://gitpod.io)

<details>
  <summary> view image </summary>

![image](https://user-images.githubusercontent.com/53068787/122213622-c5a98600-cec6-11eb-8240-13e6b03e8566.png)

</details>

**Use case / motivation**

Beginner friendly and also to work well for regular devs. As my understanding develops
regarding this I would add further uses.

**Tasks:**
- [x] 1. Add basic feature https://github.com/apache/airflow/pull/19756
- [x] 2. Add pre-commit install
- [ ] 3. Add and configure environmental variables as mentioned here https://github.com/apache/airflow/pull/19756#issuecomment-976375218
- [ ] 4. Create url for failed builds do debug in gitpod as mentioned https://github.com/apache/airflow/pull/19756#issuecomment-976383139
- [x] 5. add a edit in gitpod badge for easy access 
![image](https://user-images.githubusercontent.com/53068787/143449645-e5a3bf83-28a9-4dc4-b18b-58b52ff343d8.png)

**Are you willing to submit a PR?**

Yes.

**Related Issues**

Mail discussion about a public development server and a related work for github workspaces

https://mail-archives.apache.org/mod_mbox/airflow-dev/202106.mbox/browser

**Comment by eladkal** [comment]
@j143 are you still working on this issue?

**Comment by j143** [comment]
Hi thanks for reminding me, @eladkal . Give me a week to figure out the remaining tasks.

**Comment by j143** [comment]
Thanks for the wait. The feature is complete, I guess.
