### ISSUE TITLE
Status of testing Providers that were prepared on September 04, 2021

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#18028]
I have a kind request for all the contributors to the latest provider packages release.
Could you help us to test the RC versions of the providers and let us know in the comment,
if the issue is addressed there.

## Providers that need testing

Those are providers that require testing as there were some substantial changes introduced:

### Provider [microsoft.psrp: 1.0.1rc2](https://pypi.org/project/apache-airflow-providers-microsoft-psrp/1.0.1rc2)
   - [ ] [Fix unexpected bug in exiting PSRPHook.client context manager (#18014)](https://github.com/apache/airflow/pull/18014): @malthe
### Provider [hashicorp: 2.1.0rc2](https://pypi.org/project/apache-airflow-providers-hashicorp/2.1.0rc2)
   - [x] [Fix instantiating Vault Secret Backend during configuration (#17935)](https://github.com/apache/airflow/pull/17935): @potiuk
   - [ ] [Invalidate Vault cached prop when not authenticated (#17387)](https://github.com/apache/airflow/pull/17387): @davlum
   - [ ] [Enable Connection creation from Vault parameters (#15013)](https://github.com/apache/airflow/pull/15013): @davlum
   - [x] [Adds secret backend and logging information to provider yaml (#17625)](https://github.com/apache/airflow/pull/17625): @potiuk

## Providers that do not need testing

Those are providers that were had changes that do not require testing (dependencies).

* Provider [celery: 2.1.0rc2](https://pypi.org/project/apache-airflow-providers-celery/2.1.0rc2)

<!--

NOTE TO RELEASE MANAGER:

Please move here the providers that have doc-only changes or for which changes are trivial and
you could asses that they are OK. In case

The providers are automatically installed on Airflow 2.1 and latest `main` during the CI, so we know they
are installable. Also all classes within the providers are imported during the CI run so we know all
providers can be imported.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
@nathadfield - I'd appreciate if you tested the Vailt #17935

**Comment by nathadfield** [comment]
@potiuk All seems good from a Vault perspective now.  No issues starting Airflow or retrieving values from Vault.

**Comment by potiuk** [comment]
Cool! Thanks!

**Comment by potiuk** [comment]
@malthe @davlum -> I'd appreciate quick tests there and we should be able to release those tomorrow I think :)

**Comment by potiuk** [comment]
Released !

**Comment by potiuk** [comment]
@nathadfield - thanks for the tests !
