### ISSUE TITLE
Status of testing Providers that were prepared on October 30, 2021

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#19328]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you help us to test the RC versions of the providers and let us know in the comment,
if the issue is addressed there.

## Providers that need testing

Those are providers that require testing as there were some substantial changes introduced:

### Provider [amazon: 2.4.0rc1](https://pypi.org/project/apache-airflow-providers-amazon/2.4.0rc1)
   - [ ] [MySQLToS3Operator add support for parquet format (#18755)](https://github.com/apache/airflow/pull/18755): @guotongfei
   - [x] [Add RedshiftSQLHook, RedshiftSQLOperator (#18447)](https://github.com/apache/airflow/pull/18447): @Brooke-white
   - [ ] [Remove extra postgres dependency from AWS Provider (#18844)](https://github.com/apache/airflow/pull/18844): @mariotaddeucci
   - [x] [Remove duplicated code on S3ToRedshiftOperator (#18671)](https://github.com/apache/airflow/pull/18671): @mariotaddeucci
   - [ ] [Fixing ses email backend (#18042)](https://github.com/apache/airflow/pull/18042): @ignaski
   - [ ] [Fixup string concatenations (#19099)](https://github.com/apache/airflow/pull/19099): @blag
   - [x] [Update S3PrefixSensor to support checking multiple prefixes within a bucket (#18807)](https://github.com/apache/airflow/pull/18807): @anaynayak
   - [x] [Move validation of templated input params to run after the context init (#19048)](https://github.com/apache/airflow/pull/19048): @eskarimov
### Provider [apache.hive: 2.0.3rc1](https://pypi.org/project/apache-airflow-providers-apache-hive/2.0.3rc1)
   - [x] [fix get_connections deprecation warn in hivemetastore hook (#18854)](https://github.com/apache/airflow/pull/18854): @Aakcht
### Provider [cncf.kubernetes: 2.1.0rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/2.1.0rc1)
   - [x] [Add more type hints to PodLauncher (#18928)](https://github.com/apache/airflow/pull/18928): @jameslamb
   - [x] [add more information to PodLauncher timeout error (#17953)](https://github.com/apache/airflow/pull/17953): @jameslamb
### Provider [docker: 2.3.0rc1](https://pypi.org/project/apache-airflow-providers-docker/2.3.0rc1)
   - [x] [Add support of placement in the DockerSwarmOperator (#18990)](https://github.com/apache/airflow/pull/18990): @enima2684
   - [ ] [Fixup string concatenations (#19099)](https://github.com/apache/airflow/pull/19099): @blag
   - [ ] [Remove the docker timeout workaround (#18872)](https://github.com/apache/airflow/pull/18872): @RyanSiu1995
   - [ ] [Move docker decorator example dag to docker provider (#18739)](https://github.com/apache/airflow/pull/18739): @ephraimbuddy
### Provider [elasticsearch: 2.1.0rc1](https://pypi.org/project/apache-airflow-providers-elasticsearch/2.1.0rc1)
   - [ ] [AIP 39: Documentation (#17552)](https://github.com/apache/airflow/pull/17552): @uranusjr
   - [ ] [Adds example showing the ES_hook (#17944)](https://github.com/apache/airflow/pull/17944): @frankcash
### Provider [facebook: 2.1.0rc1](https://pypi.org/project/apache-airflow-providers-facebook/2.1.0rc1)
   - [ ] [Align the default version with Facebook business SDK (#18883)](https://github.com/apache/airflow/pull/18883): @RyanSiu1995
### Provider [google: 6.1.0rc1](https://pypi.org/project/apache-airflow-providers-google/6.1.0rc1)
   - [ ] [Add value to &#34;namespaceId&#34; of query (#19163)](https://github.com/apache/airflow/pull/19163): @deedmitrij
   - [x] [Add pre-commit hook for common misspelling check in files (#18964)](https://github.com/apache/airflow/pull/18964): @ephraimbuddy
   - [ ] [Support query timeout as an argument in CassandraToGCSOperator (#18927)](https://github.com/apache/airflow/pull/18927): @xuan616
   - [x] [Update BigQueryCreateExternalTableOperator doc and parameters (#18676)](https://github.com/apache/airflow/pull/18676): @tnyz
   - [x] [Replacing non-attribute template_fields for BigQueryToMsSqlOperator (#19052)](https://github.com/apache/airflow/pull/19052): @josh-fell
   - [ ] [Upgrade the dataproc package to 3.0.0 and migrate from v1beta2 to v1 api (#18879)](https://github.com/apache/airflow/pull/18879): @lwyszomi
   - [x] [Use google cloud credentials when executing beam commands in subprocesses (#18992)](https://github.com/apache/airflow/pull/18992): @SamWheating
   - [x] [Replace default api_version of FacebookAdsReportToGcsOperator (#18996)](https://github.com/apache/airflow/pull/18996): @eladkal
   - [ ] [Dataflow Operators - use project and location from job in on_kill method. (#18699)](https://github.com/apache/airflow/pull/18699): @lwyszomi
   - [x] [Fix hard-coded /tmp directory in CloudSQL Hook (#19229)](https://github.com/apache/airflow/pull/19229): @potiuk
   - [ ] [Fix bug in Dataflow hook when no jobs are returned (#18981)](https://github.com/apache/airflow/pull/18981): @keze
   - [ ] [Fix BigQueryToMsSqlOperator documentation (#18995)](https://github.com/apache/airflow/pull/18995): @potatochip
   - [ ] [Move validation of templated input params to run after the context init (#19048)](https://github.com/apache/airflow/pull/19048): @eskarimov
   - [x] [Google provider catch invalid secret name (#18790)](https://github.com/apache/airflow/pull/18790): @raphaelauv
### Provider [jenkins: 2.0.3rc1](https://pypi.org/project/apache-airflow-providers-jenkins/2.0.3rc1)
   - [ ] [Remove distutils usages for Python 3.10 (#19064)](https://github.com/apache/airflow/pull/19064): @uranusjr
### Provider [microsoft.azure: 3.3.0rc1](https://pypi.org/project/apache-airflow-providers-microsoft-azure/3.3.0rc1)
   - [x] [update azure cosmos to latest version (#18695)](https://github.com/apache/airflow/pull/18695): @eladkal
   - [ ] [Added sas_token var to BlobServiceClient return. Updated tests (#19234)](https://github.com/apache/airflow/pull/19234): @ReadytoRocc
   - [x] [Add pre-commit hook for common misspelling check in files (#18964)](https://github.com/apache/airflow/pull/18964): @ephraimbuddy
   - [x] [Fix changelog for Azure Provider (#18736)](https://github.com/apache/airflow/pull/18736): @potiuk
   - [ ] [Expanding docs on client auth for AzureKeyVaultBackend (#18659)](https://github.com/apache/airflow/pull/18659): @alexbegg
   - [x] [Static start_date and default arg cleanup for Microsoft providers example DAGs (#19062)](https://github.com/apache/airflow/pull/19062): @josh-fell
### Provider [mongo: 2.2.0rc1](https://pypi.org/project/apache-airflow-providers-mongo/2.2.0rc1)
   - [x] [#19223 add mongo_db param to MongoSensor (#19276)](https://github.com/apache/airflow/pull/19276): @bhavaniravi
### Provider [pagerduty: 2.1.0rc1](https://pypi.org/project/apache-airflow-providers-pagerduty/2.1.0rc1)
   - [x] [Add standard hook fields to pagerdutyHook to make hook show up in UI (#18763)](https://github.com/apache/airflow/pull/18763): @GuidoTournois
   - [x] [Make a separate hook for interacting with the Pagerduty Events API (#18784)](https://github.com/apache/airflow/pull/18784): @GuidoTournois
### Provider [salesforce: 3.3.0rc1](https://pypi.org/project/apache-airflow-providers-salesforce/3.3.0rc1)
   - [x] [Add SalesforceApexRestOperator (#18819)](https://github.com/apache/airflow/pull/18819): @mariotaddeucci
### Provider [samba: 3.0.1rc1](https://pypi.org/project/apache-airflow-providers-samba/3.0.1rc1)
   - [x] [Handle leading slash in samba path (#18847)](https://github.com/apache/airflow/pull/18847): @fredthomsen
   - [x] [Open src and dst in binary for samba copy (#18752)](https://github.com/apache/airflow/pull/18752): @fredthomsen
### Provider [sftp: 2.2.0rc1](https://pypi.org/project/apache-airflow-providers-sftp/2.2.0rc1)
   - [ ] [SFTP hook to prefer the SSH paramiko key over the key file path (#18988)](https://github.com/apache/airflow/pull/18988): @30blay
### Provider [snowflake: 2.3.0rc1](https://pypi.org/project/apache-airflow-providers-snowflake/2.3.0rc1)
   - [x] [Add test_connection method for Snowflake Hook (#19041)](https://github.com/apache/airflow/pull/19041): @msumit
   - [ ] [Add region to Snowflake URI. (#18650)](https://github.com/apache/airflow/pull/18650): @dimberman
### Provider [ssh: 2.3.0rc1](https://pypi.org/project/apache-airflow-providers-ssh/2.3.0rc1)
   - [ ] [Refactor SSHOperator so a subclass can run many commands (#10874) (#17378)](https://github.com/apache/airflow/pull/17378): @baolsen
   - [ ] [update sshtunnel version (#18684)](https://github.com/apache/airflow/pull/18684): @eladkal
   - [x] [Correctly handle get_pty attribute if command passed as XComArg or template (#19323)](https://github.com/apache/airflow/pull/19323): @josh-fell
### Provider [tableau: 2.1.2rc1](https://pypi.org/project/apache-airflow-providers-tableau/2.1.2rc1)
   - [ ] [Remove distutils usages for Python 3.10 (#19064)](https://github.com/apache/airflow/pull/19064): @uranusjr
### Provider [trino: 2.0.2rc1](https://pypi.org/project/apache-airflow-providers-trino/2.0.2rc1)
   - [ ] [Properly handle verify parameter in TrinoHook (#18791)](https://github.com/apache/airflow/pull/18791): @danarwix

## Providers that do not need testing

Those are providers that were either doc-only or had changes that do not require testing.

* Provider [airbyte: 2.1.1rc1](https://pypi.org/project/apache-airflow-providers-airbyte/2.1.1rc1)
* Provider [alibaba: 1.0.0rc1](https://pypi.org/project/apache-airflow-providers-alibaba/1.0.0rc1)
* Provider [apache.drill: 1.0.1rc1](https://pypi.org/project/apache-airflow-providers-apache-drill/1.0.1rc1)
* Provider [apache.druid: 2.0.2rc1](https://pypi.org/project/apache-airflow-providers-apache-druid/2.0.2rc1)
* Provider [apache.kylin: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-apache-kylin/2.0.1rc1)
* Provider [apache.pig: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-apache-pig/2.0.1rc1)
* Provider [apache.pinot: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-apache-pinot/2.0.1rc1)
* Provider [apache.spark: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-apache-spark/2.0.1rc1)
* Provider [apache.sqoop: 2.0.2rc1](https://pypi.org/project/apache-airflow-providers-apache-sqoop/2.0.2rc1)
* Provider [celery: 2.1.0rc1](https://pypi.org/project/apache-airflow-providers-celery/2.1.0rc1)
* Provider [cloudant: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-cloudant/2.0.1rc1)
* Provider [datadog: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-datadog/2.0.1rc1)
* Provider [dingding: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-dingding/2.0.1rc1)
* Provider [discord: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-discord/2.0.1rc1)
* Provider [ftp: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-ftp/2.0.1rc1)
* Provider [grpc: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-grpc/2.0.1rc1)
* Provider [http: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-http/2.0.1rc1)
* Provider [imap: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-imap/2.0.1rc1)
* Provider [influxdb: 1.0.0rc1](https://pypi.org/project/apache-airflow-providers-influxdb/1.0.0rc1)
* Provider [jira: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-jira/2.0.1rc1)
* Provider [microsoft.mssql: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-microsoft-mssql/2.0.1rc1)
* Provider [microsoft.winrm: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-microsoft-winrm/2.0.1rc1)
* Provider [mysql: 2.1.1rc1](https://pypi.org/project/apache-airflow-providers-mysql/2.1.1rc1)
* Provider [odbc: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-odbc/2.0.1rc1)
* Provider [opsgenie: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-opsgenie/2.0.1rc1)
* Provider [oracle: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-oracle/2.0.1rc1)
* Provider [plexus: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-plexus/2.0.1rc1)
* Provider [presto: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-presto/2.0.1rc1)
* Provider [qubole: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-qubole/2.0.1rc1)
* Provider [redis: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-redis/2.0.1rc1)
* Provider [segment: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-segment/2.0.1rc1)
* Provider [sendgrid: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-sendgrid/2.0.1rc1)
* Provider [singularity: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-singularity/2.0.1rc1)
* Provider [telegram: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-telegram/2.0.1rc1)
* Provider [vertica: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-vertica/2.0.1rc1)
* Provider [zendesk: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-zendesk/2.0.1rc1)

Thanks to all who contributed to those provider's release

@sreenath-kamath @jarfgit @frankcash @deedmitrij @enima2684 @uranusjr @peter-volkov @mariotaddeucci @potatochip @malthe @msumit @dimberman @jameslamb @Brooke-white @GuidoTournois @minu7 @ashb @shadrus @ignaski @eladkal @ephraimbuddy @eskarimov @JavierLopezT @keze @josh-fell @raphaelauv @blag @Aakcht @guotongfei @SamWheating @danarwix 
@subkanthi @alexbegg @bhavaniravi @tnyz @Goodkat @fredthomsen @SayTen @kaxil @lwyszomi @ReadytoRocc @baolsen @30blay @nathadfield @xuan616 @RyanSiu1995

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by raphaelauv** [comment]
for **cncf.kubernetes: 2.1.0rc1** it's all good

 add more information to PodLauncher timeout error (#17953)  -> is working 
 
 ```
   File "/usr/local/lib/python3.9/site-packages/airflow/providers/cncf/kubernetes/operators/kubernetes_pod.py", line 374, in execute
    raise AirflowException(f'Pod Launching failed: {ex}')
airflow.exceptions.AirflowException: Pod Launching failed: Pod took longer than 120 seconds to start. Check the pod events in kubernetes to determine why.
[2021-10-30, 14:21:41 UTC] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-10-30, 14:21:41 UTC] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check

 ```
 
 Add more type hints to PodLauncher (#18928) > just typing , so OK

**Comment by codenamestif** [comment]
I think #18733 was released in 2.3.0

**Comment by raphaelauv** [comment]
for **google: 6.1.0rc1** 

Google provider catch invalid secret name (#18790) -> is working

```
[2021-10-30 14:56:31,254] {logging_mixin.py:104} INFO - Running <TaskInstance: a_nice_dag.also_run_this 2021-10-20T00:00:00+00:00 [running]> on host 0dbece050201
[2021-10-30 14:56:31,797] {secret_manager_client.py:100} ERROR - Google Cloud API Call Error (InvalidArgument): Invalid secret ID XXXXXXXXXXXXXX-variable-toto.tata.
                Only ASCII alphabets (a-Z), numbers (0-9), dashes (-), and underscores (_)
                are allowed in the secret ID.
                
[2021-10-30 14:56:31,858] {taskinstance.py:1300} INFO - Exporting the following env vars:
...
```

the error about secrets with a non valid char is now catch

**Comment by potiuk** [comment]
> I think #18733 was released in 2.3.0

Good spot @codenamestif ! It turned out that after last month's release of 2.3.0 as rc2 I set the "2.3.0" tag wrongly to rc1 - so the changes added between rc1 and rc2 were duplicated in the issue and changelog (and I missed that when I prepared it today). Those are the duplicated issues:

* ``Add AWS Fargate profile support (#18645)``
* ``Add emr cluster link (#18691)``
* ``AwsGlueJobOperator: add wait_for_completion to Glue job run (#18814)``
* ``AwsGlueJobOperator: add run_job_kwargs to Glue job run (#16796)``
* ``Add additional dependency for postgres extra for amazon provider (#18737)``
* ``Adds an s3 list prefixes operator (#17145)``
* ``ECSOperator: airflow exception on edge case when cloudwatch log stream is not found (#18733)``
* ``Amazon Athena Example (#18785)``
* ``Amazon SQS Example (#18760)``

I already corrected the tag, the issue and I will also correct the Changelog (and in docs those entries will be missing), but unless there are other, more serious changes that make it rc1, it will remain in the package README (and tecchnically those changes ARE in 2.4.0 as well as 2.3.0), In the future packages changelog will corrected.

Sorry everyone involved for spamming!

**Comment by potiuk** [comment]
> I think #18733 was released in 2.3.0

Good spot @codenamestif ! It turned out that after last month's release of 2.3.0 as rc2 I set the "2.3.0" tag wrongly to rc1 - so the changes added between rc1 and rc2 were duplicated in the issue and changelog (and I missed that when I prepared it today). Those are the duplicated issues:

* ``Add AWS Fargate profile support (#18645)``
* ``Add emr cluster link (#18691)``
* ``AwsGlueJobOperator: add wait_for_completion to Glue job run (#18814)``
* ``AwsGlueJobOperator: add run_job_kwargs to Glue job run (#16796)``
* ``Add additional dependency for postgres extra for amazon provider (#18737)``
* ``Adds an s3 list prefixes operator (#17145)``
* ``ECSOperator: airflow exception on edge case when cloudwatch log stream is not found (#18733)``
* ``Amazon Athena Example (#18785)``
* ``Amazon SQS Example (#18760)``

I already corrected the tag, the issue and I will also correct the Changelog (and in docs those entries will be missing), but unless there are other, more serious changes that make it rc1, it will remain in the package README (and tecchnically those changes ARE in 2.4.0 as well as 2.3.0), In the future packages changelog will corrected.

Sorry everyone involved for spamming!

**Comment by Aakcht** [comment]
Tested #18854 - all good.

#18331 is already present in 2.1.1 ( it was tested in #18638) , so I don't think `hdfs 2.1.1rc1` should be present here.

**Comment by JavierLopezT** [comment]
#17397 and #18764 were already tested in the last wave

**Comment by mariotaddeucci** [comment]
#18027 is already present in 2.3.0, tested in #18638
#18671 and #18819 are all good 
#18844 got errors using `RedshiftSQLHook ` when executing multiple commands into a prepared statement.  I'll fix it.

**Comment by enima2684** [comment]
#18990 tested and working

**Comment by enima2684** [comment]
#18872 I tested this PR and it is not working as expected.
The DockerSwarmOperator never returns and keep hanging.
I used for the test the following Job : 
```python
    task = DockerSwarmOperator(
        task_id="task",
        image="python:3.9",
        enable_logging=True,
        tty=True,
        command=["echo", "hello world !"]
    )
```

**Comment by potiuk** [comment]
> #18331 is already present in 2.1.1 ( it was tested in #18638) , so I don't think `hdfs 2.1.1rc1` should be present here.

Right - the issue generation script has a bug apparently in this case - hdfs is not being released. I Will fix it. Removed it from the issue.

**Comment by potiuk** [comment]
> #17397 and #18764 were already tested in the last wave

Correct - already removed (that was amazon's later release and wrong tag set - already corrected :)

**Comment by potiuk** [comment]
> #18844 got errors using `RedshiftSQLHook ` when executing multiple commands into a prepared statement. I'll fix it.
How serious / how much of a regression change is it @mariotadeucci ?

**Comment by Goodkat** [comment]
#17850 was already tested within 2.0.0rc2 release
#15016 (comment)

**Comment by potiuk** [comment]
| #18872 I tested this PR and it is not working as expected.

@RyanSiu1995  can you double check if you have the same problem ?

**Comment by potiuk** [comment]
> #17850 was already tested within 2.0.0rc2 release

Correct - exasol is not being released (same bug as with hdfs when generating issue only). I will fix it. Sorry for spam.

**Comment by potiuk** [comment]
I removed the few other providers which suffered from the same issue - sorry :(

**Comment by fredthomsen** [comment]
[#18847](https://github.com/apache/airflow/pull/18847) and [#18752](https://github.com/apache/airflow/pull/18752) for [samba: 3.0.1rc1](https://pypi.org/project/apache-airflow-providers-samba/3.0.1rc1) are both good.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by GuidoTournois** [comment]
I have validated that both changes for pagerduty work as intended!
-  Add standard hook fields to pagerdutyHook to make hook show up in UI (#18763)
- Make a separate hook for interacting with the Pagerduty Events API (#18784)

**Comment by Brooke-white** [comment]
#18447 tested and working

**Comment by anaynayak** [comment]
#18807 tested and verified both single + multiple s3 prefix matches.

**Comment by josh-fell** [comment]
Tested and verified #19052, #19062, and #19323. Thanks for organizing this release Jarek!

**Comment by tnyz** [comment]
tested #18676 and working

**Comment by potiuk** [comment]
Good progress so far :)!

**Comment by mariotaddeucci** [comment]
> > #18844 got errors using `RedshiftSQLHook ` when executing multiple commands into a prepared statement. I'll fix it.
> 
> How serious / how much of a regression change is it @mariotadeucci ?
@potiuk Happend on `S3ToRedshiftOperator` with specific configuration. By using "UPSERT" or "REPLACE" is generate an sql block with multiple queries. The `RedshiftSQLHook` don't support execute multiple queries in a single call of `execute`. To fix it just need to convert the single query string to a list of queries. Fix is available on PR #19358.

**Comment by eskarimov** [comment]
Tested #19048, works correctly :)

**Comment by bhavaniravi** [comment]
Tested #19276 MongoSensor picking up the new db param

**Comment by mik-laj** [comment]
> Provider facebook: 2.1.0rc1
> Align the default version with Facebook business SDK (#18883): @RyanSiu1995

It is a breaking change, so it should be in a new release.

> Provider google: 6.1.0rc1
>  Replace default api_version of FacebookAdsReportToGcsOperator (#18996): @eladkal

It is breaking change also.

> Provider microsoft.azure: 3.3.0rc1
> update azure cosmos to latest version (#18695): @eladkal

I am not sure here, but when we changed the minimum requirements of the google libraries, we always bumped the major version. Airflow is a thin layer between libraries and user, so breaking changes propagate to Airflow very easily.

**Comment by potiuk** [comment]
> > Provider facebook: 2.1.0rc1
> > Align the default version with Facebook business SDK (#18883): @RyanSiu1995
> 
> It is a breaking change, so it should be in a new release.
> 
> > Provider google: 6.1.0rc1
> >  Replace default api_version of FacebookAdsReportToGcsOperator (#18996): @eladkal
> 
> It is breaking change also.
> 
> > Provider microsoft.azure: 3.3.0rc1
> > update azure cosmos to latest version (#18695): @eladkal
> 
> I am not sure here, but when we changed the minimum requirements of the google libraries, we always bumped the major version. Airflow is a thin layer between libraries and user, so breaking changes propagate to Airflow very easily.
> 

Thanks @mik-laj I will take a look and decide

**Comment by SamWheating** [comment]
regarding https://github.com/apache/airflow/pull/18992

I've tested this change in our environment with the DataflowCreateJavaJobOperator. I haven't had a chance to set up test jobs for the other operators but based on the similarities in implementation I think that this fix should be applicable to all of them.

This PR introduced a change in behaviour, but I don't think it should be considered a breaking change as it is simply returning to the original / documented behaviour.

**Comment by potiuk** [comment]
> > > Provider facebook: 2.1.0rc1
> > > Provider google: 6.1.0rc1
> > > microsoft.azure 3.3.0rc1

Hey @mik-laj - thanks for raising your concenrs. i looked closer, and I do not see those changes as really "breaking" (or at least not really breaking enough and under our control to justify major version change (but I am open to hear to arguments if others disagree). 

## Facebook

Facebook API does not follow SemVer. AT ALL. 

They mostly introduce new features and bugfixes when they bump the version. More interestingly, they even CHANGE behaviour of old versions of APIs when this behaviour is working for quite some time in the new versions. 

Here are the changes to insights features we are using for example:

> Insights
> Applies to v9.0+. Will apply to all versions on May 9, 2021.
> IG User follower_count values now align more closely with their corresponding values displayed in the Instagram app. In > addition, follower_count now returns a maximum of 30 days of data instead of 2 years.

and:

> Ads Insights API
> Updated date_preset parameter
> Applies to v10.0+.

> The lifetime parameter (date_preset=lifetime) is disabled and replaced with date_preset=maximum, which can be used to retrieve a maximum of 37 months of data. The API will return an error when requests contain date ranges beyond the 37-month window.
> For v9.0 and lower, there will be no change in functionality until May 25, 2021. At that time, date_preset=maximum will be enabled and any lifetime calls will default to maximum and return only 37 months of data.

and:

> Deprecation of Store Visit Metrics
> Applies to 11.0+. Will apply to all versions on Sept. 6, 2021.

This means that the version 6.0 of "insights" we were using so far has anyway changed behaviour on Sep 6th this year to match the current 11+ behaviour :scream: 

So from what we see here, Facebook has chosen a "move fast break things" approach for their APIs. I assume Facebook users know it and I think the approach we took is a good one - we should not really try to keep compatibilty with version vN of Facebook, because even they don't do/recommend it (and we won't be able to actually do that because they can anyhow change the behaviour without us knowing it). So keeping the approach where by default API version is "latest" seems like a good approach and I do not see it really breaking anything. 

## Cosmos

> Provider microsoft.azure: 3.3.0rc1
> update azure cosmos to latest version (#18695): @eladkal

I looked at the changes again, and I do not see any breaking change. We indeed sometimes (but not always) bumped major versions for our providers when underlying libraries changed but only when they changed the Airflow API of that provider (format of data returned and similar). The sheer fact of library upgrading it's version does not automatically invalidates and forces bump to new version of all the applications and libraries using it. In this particular case, we simply adapted our implementation so that the API remained the same (the breaking change which affected us was simply throwing a different exception - in our case we caught it and returned None, and this behaviour remained so there is no reason to bump the major version here.

**Comment by potiuk** [comment]
Closing this one. As described in https://lists.apache.org/thread/6tzsq6xkm5r1q6pqtyq5yhvr5p1jqd13  I am releasing the wave now and we are removing the Amazon Provider from that release due to Redshift regression (and I will release fixed version soon). Thanks @mariotaddeucci for testing and spotting the problem (it was not obvious in the initial change and it's great you tested this case!) 

Thanks everyone who helped!
