### ISSUE TITLE
Status of testing Providers that were prepared on November 04, 2021

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#19414]
I have a kind request for all the contributors to the latest provider packages release.
Could you help us to test the RC versions of the providers and let us know in the comment,
if the issue is addressed there.

## Provider [amazon: 2.4.0rc2](https://pypi.org/project/apache-airflow-providers-amazon/2.4.0rc2)
   - [ ] [MySQLToS3Operator add support for parquet format (#18755)](https://github.com/apache/airflow/pull/18755): @guotongfei
   - [x] [Add RedshiftSQLHook, RedshiftSQLOperator (#18447)](https://github.com/apache/airflow/pull/18447): @Brooke-white
   - [x] [Remove extra postgres dependency from AWS Provider (#18844)](https://github.com/apache/airflow/pull/18844): @mariotaddeucci
   - [x] [Remove duplicated code on S3ToRedshiftOperator (#18671)](https://github.com/apache/airflow/pull/18671): @mariotaddeucci
   - [ ] [Fixing ses email backend (#18042)](https://github.com/apache/airflow/pull/18042): @ignaski
   - [ ] [Fixup string concatenations (#19099)](https://github.com/apache/airflow/pull/19099): @blag
   - [x] [Update S3PrefixSensor to support checking multiple prefixes within a bucket (#18807)](https://github.com/apache/airflow/pull/18807): @anaynayak
   - [x] [Move validation of templated input params to run after the context init (#19048)](https://github.com/apache/airflow/pull/19048): @eskarimov
   - [ ] [ fix SagemakerProcessingOperator ThrottlingException (#19195)](https://github.com/apache/airflow/pull/19195): @ChanglinZhou
   - [x] [Fix S3ToRedshiftOperator (#19358)](https://github.com/apache/airflow/pull/19358): @mariotaddeucci

Thanks to everyone involved in the PRs:
@eskarimov @blag @anaynayak @Brooke-white @mariotaddeucci @ignaski @ChanglinZhou @guotongfei

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
I marked those PRS that were already tested at https://github.com/apache/airflow/issues/19328 but feel free to re-test them  with RC2 just in case.

**Comment by mariotaddeucci** [comment]
#18671, #18844 and #19358 tested and worked as expected o/

**Comment by eladkal** [comment]
closing as provider was released
