### ISSUE TITLE
Status of testing of Apache Airflow 2.2.2rc1

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#19515]
### Status of testing of Apache Airflow 2.2.2rc1

We have a kind request for all the contributors to the latest [Apache Airflow RC 2.2.2rc1](https://pypi.org/project/apache-airflow/2.2.2rc1/).

Could you please help us to test the RC versions of Airflow?

Please let us know in the comment if the issue is addressed in the latest RC.

- [ ] [Add explicit session parameter in PoolSlotsAvailableDep (#18875)](https://github.com/apache/airflow/pull/18875): @avkirilishin
- [ ] [Use ``execution_date`` to check for existing ``DagRun`` for ``TriggerDagRunOperator`` (#18968)](https://github.com/apache/airflow/pull/18968): @gulshngill
- [x] [Fix Toggle Wrap on DAG code page (#19211)](https://github.com/apache/airflow/pull/19211): @PApostol @bartelemi
     Linked issues:
     - [Toggle Wrap on DAG code page is broken (#17047)](https://github.com/apache/airflow/issues/17047)
- [x] [Fix hard-coded /tmp dir in sqlite_default (#19255)](https://github.com/apache/airflow/pull/19255): @potiuk @aran3
     Linked issues:
     - [Removes hard-coding of /tmp filesystem cache (#19208)](https://github.com/apache/airflow/pull/19208)
     - [Fix hard-coded /tmp directory in CloudSQL Hook (#19229)](https://github.com/apache/airflow/pull/19229)
- [ ] [Fix task instance modal in gantt view (#19258)](https://github.com/apache/airflow/pull/19258): @robinedwards
     Linked issues:
     - [Task modal links are broken in the dag gantt view (#19252)](https://github.com/apache/airflow/issues/19252)
- [ ] [Fix hidden tooltip position (#19261)](https://github.com/apache/airflow/pull/19261): @mnojek @bbovenzi
     Linked issues:
     - [Tooltip element is not removed and overlays another clickable elements (#18732)](https://github.com/apache/airflow/issues/18732)
- [ ] [Fix serialization of Params with set data type (#19267)](https://github.com/apache/airflow/pull/19267): @dstandish
- [ ] [Fix MySQL db migration with default encoding/collation (#19268)](https://github.com/apache/airflow/pull/19268): @jedcunningham
- [ ] [Check next run exists before reading data interval (#19307)](https://github.com/apache/airflow/pull/19307): @uranusjr @ephraimbuddy @nicogelders
     Linked issues:
     - ["Not a valid timetable" when returning None from next_dagrun_info in a custom timetable (#19304)](https://github.com/apache/airflow/issues/19304)
     - [Fix catchup by limiting queued dagrun creation using max_active_runs (#18897)](https://github.com/apache/airflow/pull/18897)
- [ ] [Clarify dag-not-found error message (#19338)](https://github.com/apache/airflow/pull/19338): @dstandish
- [ ] [Task should fail immediately when pod is unprocessable (#19359)](https://github.com/apache/airflow/pull/19359): @dstandish
- [ ] [Fix message on "Mark as" confirmation page (#19363)](https://github.com/apache/airflow/pull/19363): @ashb
- [ ] [Only mark SchedulerJobs as failed, not any jobs (#19375)](https://github.com/apache/airflow/pull/19375): @jedcunningham @rodrigo-morais @sodafountain
     Linked issues:
     - [Re-deploy scheduler tasks failing with SIGTERM on K8s executor (#16881)](https://github.com/apache/airflow/issues/16881)
     - [State of this instance has been externally set to up_for_retry. Terminating instance. (#16573)](https://github.com/apache/airflow/issues/16573)
- [ ] [Check if job object is None before calling .is_alive() (#19380)](https://github.com/apache/airflow/pull/19380): @int3rlop3r
- [ ] [Fix downgrade for a DB Migration (#19390)](https://github.com/apache/airflow/pull/19390): @kaxil
- [ ] [Fix relativedelta schedule_interval serialization (#19418)](https://github.com/apache/airflow/pull/19418): @uranusjr @rcheatham-q
     Linked issues:
     - [A dag's schedule interval can no longer be an instance of dateutils.relativedelta (#19416)](https://github.com/apache/airflow/issues/19416)
- [ ] [Fix moving of dangling TaskInstance rows for SQL Server (#19425)](https://github.com/apache/airflow/pull/19425): @ashb
- [ ] [FAB still requires WTForms < 3.0 (#19466)](https://github.com/apache/airflow/pull/19466): @ashb

Thanks to all who contributed to the release (probably not a complete list!):
@potiuk @rodrigo-morais @mnojek @ephraimbuddy @int3rlop3r @malthe @robinedwards @sodafountain @john-jac @PApostol @uranusjr @dstandish @jedcunningham @nicogelders @axxe @rcheatham-q @bartelemi @ashb @kaxil @gavinBeam @avkirilishin @aran3 @gulshngill @raphaelauv @bbovenzi

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
#19255 works: 

```
root@df0e572d5245:/opt/airflow# airflow connections get sqlite_default
id | conn_id        | conn_type | description | host                                | schema | login | password | port | is_encrypted | is_extra_encrypted | extra_dejson | get_uri                                             
===+================+===========+=============+=====================================+========+=======+==========+======+==============+====================+==============+=====================================================
43 | sqlite_default | sqlite    | None        | /home/airflow/tmp/sqlite_default.db | None   | None  | None     | None | False        | False              | {}           | sqlite://%2Fhome%2Fairflow%2Ftmp%2Fsqlite_default.db
```

**Comment by PApostol** [comment]
#19211 works (see lines 6-7):

<img src="https://user-images.githubusercontent.com/50751110/141150255-7ab73feb-de99-4bdc-aad5-1820615a6683.png" width="700" height="550">

<img src="https://user-images.githubusercontent.com/50751110/141150270-ca286fb3-b9c2-44fa-85e6-743f52e034bd.png" width="700" height="550">

**Comment by potiuk** [comment]
Closing as we will have rc2.
