### ISSUE TITLE
Status of testing Providers that were prepared on November 30, 2021

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#19895]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you help us to test the RC versions of the providers and let us know in the comment,
if the issue is addressed there.

## Providers that need testing

Those are providers that require testing as there were some substantial changes introduced:

### Provider [amazon: 2.5.0rc1](https://pypi.org/project/apache-airflow-providers-amazon/2.5.0rc1)
   - [ ] [Adding support for using client_type API for interacting with EC2 and support for using filters (#9011)](https://github.com/apache/airflow/pull/9011): @VijayantSoni
   - [ ] [Do not check for S3 key before attempting download (#19504)](https://github.com/apache/airflow/pull/19504): @dstandish
   - [ ] [MySQLToS3Operator  actually allow writing parquet files to s3. (#19094)](https://github.com/apache/airflow/pull/19094): @guotongfei
   - [ ] [Amazon provider remove deprecation, second try (#19815)](https://github.com/apache/airflow/pull/19815): @uranusjr
   - [ ] [Catch AccessDeniedException in AWS Secrets Manager Backend (#19324)](https://github.com/apache/airflow/pull/19324): @john-jac
### Provider [apache.druid: 2.1.0rc1](https://pypi.org/project/apache-airflow-providers-apache-druid/2.1.0rc1)
   - [x] [Fix DruidOperator rendering problem (#19420)](https://github.com/apache/airflow/pull/19420): @humit0
   - [x] [Adding missing `max_ingestion_time` to DruidOperator docstring (#18693)](https://github.com/apache/airflow/pull/18693): @josh-fell
   - [ ] [Add guide for Apache Druid operators (#18527)](https://github.com/apache/airflow/pull/18527): @Jasonnor
### Provider [apache.hdfs: 2.2.0rc1](https://pypi.org/project/apache-airflow-providers-apache-hdfs/2.2.0rc1)
   - [x] [hdfs provider: fix HA support for webhdfs (#19711)](https://github.com/apache/airflow/pull/19711): @Aakcht
### Provider [apache.hive: 2.1.0rc1](https://pypi.org/project/apache-airflow-providers-apache-hive/2.1.0rc1)
   - [x] [hive provider: restore HA support for metastore (#19777)](https://github.com/apache/airflow/pull/19777): @Aakcht
### Provider [apache.spark: 2.0.2rc1](https://pypi.org/project/apache-airflow-providers-apache-spark/2.0.2rc1)
   - [ ] [fix bug of SparkSql Operator log  going to infinite loop. (#19449)](https://github.com/apache/airflow/pull/19449): @huage1994
### Provider [cncf.kubernetes: 2.2.0rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/2.2.0rc1)
   - [ ] [Added namespace as a template field in the KPO. (#19718)](https://github.com/apache/airflow/pull/19718): @ReadytoRocc
   - [ ] [Decouple name randomization from name kwarg (#19398)](https://github.com/apache/airflow/pull/19398): @ferruzzi
   - [x] [Checking event.status.container_statuses before filtering (#19713)](https://github.com/apache/airflow/pull/19713): @ulisesojeda
   - [ ] [Coalesce `extra` params to None in KubernetesHook (#19694)](https://github.com/apache/airflow/pull/19694): @dstandish
   - [ ] [Change to correct type in KubernetesPodOperator (#19459)](https://github.com/apache/airflow/pull/19459): @DorConnecteam
### Provider [databricks: 2.1.0rc1](https://pypi.org/project/apache-airflow-providers-databricks/2.1.0rc1)
   - [ ] [Databricks: add more methods to represent run state information (#19723)](https://github.com/apache/airflow/pull/19723): @alexott
   - [x] [Databricks - allow Azure SP authentication on other Azure clouds (#19722)](https://github.com/apache/airflow/pull/19722): @alexott
   - [x] [Databricks: allow to specify PAT in Password field (#19585)](https://github.com/apache/airflow/pull/19585): @alexott
   - [ ] [Databricks jobs 2.1 (#19544)](https://github.com/apache/airflow/pull/19544): @christophergrant
   - [x] [Update Databricks API from 2.0 to 2.1 (#19412)](https://github.com/apache/airflow/pull/19412): @Mokubyow
   - [x] [Authentication with AAD tokens in Databricks provider (#19335)](https://github.com/apache/airflow/pull/19335): @alexott
   - [ ] [Fixup string concatenations (#19099)](https://github.com/apache/airflow/pull/19099): @blag

The Databricks provider will be removed from this round due to https://github.com/apache/airflow/pull/20036.

### Provider [google: 6.2.0rc1](https://pypi.org/project/apache-airflow-providers-google/6.2.0rc1)
   - [x] [Added wait mechanizm to the DataprocJobSensor to avoid 509 errors when Job is not available (#19740)](https://github.com/apache/airflow/pull/19740): @lwyszomi
   - [ ] [Add support in GCP connection for reading key from Secret Manager (#19164)](https://github.com/apache/airflow/pull/19164): @keze
   - [ ] [Add dataproc metastore operators (#18945)](https://github.com/apache/airflow/pull/18945): @wojsamjan
   - [x] [Add support of `path` parameter for GCloud Storage Transfer Service operators (#17446)](https://github.com/apache/airflow/pull/17446): @eskarimov
   - [x] [Move `bucket_name` validation out of `__init__` in Google Marketing Platform operators (#19383)](https://github.com/apache/airflow/pull/19383): @josh-fell
   - [ ] [Create dataproc serverless spark batches operator (#19248)](https://github.com/apache/airflow/pull/19248): @MaksYermak
   - [ ] [updates pipeline_timeout CloudDataFusionStartPipelineOperator (#18773)](https://github.com/apache/airflow/pull/18773): @matsavage
   - [x] [Support impersonation_chain parameter in the GKEStartPodOperator (#19518)](https://github.com/apache/airflow/pull/19518): @lwyszomi
   - [ ] [Fix badly merged impersonation in GKEPodOperator (#19696)](https://github.com/apache/airflow/pull/19696): @potiuk
### Provider [influxdb: 1.1.0rc1](https://pypi.org/project/apache-airflow-providers-influxdb/1.1.0rc1)
   - [x] [Add influxdb operator (#19356)](https://github.com/apache/airflow/pull/19356): @subkanthi
### Provider [microsoft.azure: 3.4.0rc1](https://pypi.org/project/apache-airflow-providers-microsoft-azure/3.4.0rc1)
   - [x] [Remove unnecessary connection form customizations in Azure (#19595)](https://github.com/apache/airflow/pull/19595): @josh-fell
   - [x] [Update Azure modules to comply with AIP-21 (#19431)](https://github.com/apache/airflow/pull/19431): @josh-fell
   - [x] [Remove `host` from hidden fields in `WasbHook` (#19475)](https://github.com/apache/airflow/pull/19475): @josh-fell
   - [ ] [use DefaultAzureCredential if login not provided for Data Factory (#19079)](https://github.com/apache/airflow/pull/19079): @sdebruyn
   - [x] [Fix argument error in AzureContainerInstancesOperator (#19668)](https://github.com/apache/airflow/pull/19668): @chinwobble
### Provider [postgres: 2.4.0rc1](https://pypi.org/project/apache-airflow-providers-postgres/2.4.0rc1)
   - [x] [19489 - Pass client_encoding for postgres connections (#19827)](https://github.com/apache/airflow/pull/19827): @subkanthi
   - [ ] [Amazon provider remove deprecation, second try (#19815)](https://github.com/apache/airflow/pull/19815): @uranusjr
### Provider [salesforce: 3.4.0rc1](https://pypi.org/project/apache-airflow-providers-salesforce/3.4.0rc1)
   - [ ] [Do not require all extras for SalesforceHook (#19530)](https://github.com/apache/airflow/pull/19530): @alexbegg
### Provider [sftp: 2.3.0rc1](https://pypi.org/project/apache-airflow-providers-sftp/2.3.0rc1)
   - [ ] [Add test_connection method for sftp hook (#19609)](https://github.com/apache/airflow/pull/19609): @cmarteepants
### Provider [snowflake: 2.3.1rc1](https://pypi.org/project/apache-airflow-providers-snowflake/2.3.1rc1)
   - [x] [Remove duplicate get_connection in SnowflakeHook (#19543)](https://github.com/apache/airflow/pull/19543): @harryplumer

## Providers that do not need testing

We also had a number of providers that had documentation-only change (mostly around examples). Those need no testing.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by harryplumer** [comment]
snowflake 2.3.1rc1 looks good!

**Comment by eskarimov** [comment]
#17446 works as expected

**Comment by lwyszomi** [comment]
google 6.2.0rc1 works fine

**Comment by Aakcht** [comment]
#19711 and #19777 work as expected, so waiting for the release :)

**Comment by raphaelauv** [comment]
_Checking event.status.container_statuses before filtering (#19713)_ -> work

**Comment by chinwobble** [comment]
#19668 tested and working with `apache-airflow-providers-microsoft-azure==3.4.0rc1`

**Comment by josh-fell** [comment]
Verified #18693, #19431, #19475, #19595, and #19383

Thanks again @potiuk!

**Comment by potiuk** [comment]
Thanks for those who tested. Today is last day to do some testing  :)

**Comment by uranusjr** [comment]
cc @dimon222 for #19815

**Comment by alexott** [comment]
I have capacity to test only over the weekend...

**Comment by subkanthi** [comment]
Tested #19489

**Comment by potiuk** [comment]
@alexott  - good we need to more votes so still some time :)

**Comment by alexott** [comment]
Tested #19722, #19585, #19335, #19412.
Unfortunately there is a logical error in calculation of the expiration time that may lead to authentication error when executing long-running jobs, just submitted a very small PR to fix it: #20036 - it would be nice to include it into release

**Comment by potiuk** [comment]
> Tested #19722, #19585, #19335, #19412. Unfortunately there is a logical error in calculation of the expiration time that may lead to authentication error when executing long-running jobs, just submitted a very small PR to fix it: #20036 - it would be nice to include it into release

Thanks! 

I can remove it from the release and make ad-hoc rc2 for databricks only. This is how we deal with it when we find problems with a candidate provider.

**Comment by humit0** [comment]
Tested #19420

**Comment by potiuk** [comment]
Thanks everyone who helped. I am preparing Databricks relase separately now!
