### ISSUE TITLE
Status of testing Providers that were prepared on December 07, 2021

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#20097]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you help us to test the RC versions of the providers and let us know in the comment,
if the issue is addressed there.

## Providers that need testing

Those are providers that require testing as there were some substantial changes introduced:

### Provider [databricks: 2.1.0rc2](https://pypi.org/project/apache-airflow-providers-databricks/2.1.0rc2)
   - [x] [Databricks: add more methods to represent run state information (#19723)](https://github.com/apache/airflow/pull/19723): @alexott
   - [ ] [Databricks - allow Azure SP authentication on other Azure clouds (#19722)](https://github.com/apache/airflow/pull/19722): @alexott
   - [x] [Databricks: allow to specify PAT in Password field (#19585)](https://github.com/apache/airflow/pull/19585): @alexott
   - [x] [Databricks jobs 2.1 (#19544)](https://github.com/apache/airflow/pull/19544): @christophergrant
   - [ ] [Update Databricks API from 2.0 to 2.1 (#19412)](https://github.com/apache/airflow/pull/19412): @Mokubyow
   - [ ] [Authentication with AAD tokens in Databricks provider (#19335)](https://github.com/apache/airflow/pull/19335): @alexott
   - [ ] [Fixup string concatenations (#19099)](https://github.com/apache/airflow/pull/19099): @blag
   - [ ] [Databricks hook: fix expiration time check (#20036)](https://github.com/apache/airflow/pull/20036): @alexott

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by alexott** [comment]
Tested #19585, #19335, #19443, #19544 - looks good

P.S. #19443 is missing from the changelog

**Comment by potiuk** [comment]
> P.S. #19443 is missing from the changelog

Ah yeah. Good point -  I have mistakenly hidden it in the changelog - it is in the hidden section among refactoring (my bad) - see here - it is under "Below changes are excluded from the changelog":

https://raw.githubusercontent.com/apache/airflow/main/airflow/providers/databricks/CHANGELOG.rst

I will restore it in the documentation in https://airflow.apache.org/docs/apache-airflow-providers-databricks/stable/index.html - before publishing the docs (I can do it) - but I won't add it back (yet) in the PyPI package README (I can't - it's part of the package). But I will correct it in the CHANGELOG and when we release the next version (I see there are already some changes in progress :) . and it will appear back in the PyPI changelog when we release December wave.

**Comment by alexott** [comment]
Thank you Jarek

**Comment by kaxil** [comment]
-1 for Databricks provider. The change in https://github.com/apache/airflow/pull/19835 causes DB call in init (which was fixed in last version). @josh-fell  will have a PR in a bit to fix it

**Comment by potiuk** [comment]
Cancelling it then
