### ISSUE TITLE
Status of testing of Apache Airflow 2.2.3rc2

### ISSUE THREAD

**Issue by jedcunningham** [apache/airflow#20208]
We have a kind request for all the contributors to the latest [Apache Airflow RC 2.2.3rc2](https://pypi.org/project/apache-airflow/2.2.3rc2/).
                                                                                                                                                                                                                      Could you please help us to test the RC versions of Airflow?      

Please let us know in the comment if the issue is addressed in the latest RC.

- [ ] [Handle case of nonexistent file when preparing file path queue (#18998)](https://github.com/apache/airflow/pull/18998): @SamWheating
- [ ] [Simplify "invalid TI state" message (#19029)](https://github.com/apache/airflow/pull/19029): @dstandish
- [x] [Rename execution date in forms and tables (#19063)](https://github.com/apache/airflow/pull/19063): @bbovenzi
- [ ] [Fix: Add taskgroup tooltip to graph view (#19083)](https://github.com/apache/airflow/pull/19083): @bbovenzi @cb149
     Linked issues:
     - [TaskGroup tooltip missing actual tooltip and default_args issue (#19078)](https://github.com/apache/airflow/issues/19078)
- [x] [Do not create dagruns for DAGs with import errors  (#19367)](https://github.com/apache/airflow/pull/19367): @ephraimbuddy
- [x] [Fix log timezone in task log view (#19342) (#19401)](https://github.com/apache/airflow/pull/19401): @calfzhou @sartyukhov
     Linked issues:
     - [Webserver shows wrong datetime (timezone) in log (#19342)](https://github.com/apache/airflow/issues/19342)
- [x] [Fix field relabeling when switching between conn types (#19411)](https://github.com/apache/airflow/pull/19411): @josh-fell @cb149
     Linked issues:
     - [Relabeling in Connection form causes falsely named fields (UI only) (#19386)](https://github.com/apache/airflow/issues/19386)
- [x] [Do not crash with stacktrace when task instance is missing (#19478)](https://github.com/apache/airflow/pull/19478): @potiuk
     Linked issues:
     - ['NoneType' object has no attribute 'refresh_from_task'  Error when manually running task instance (#19477)](https://github.com/apache/airflow/issues/19477)
- [ ] [KubernetesExecutor should default to template image if used (#19484)](https://github.com/apache/airflow/pull/19484): @dstandish
- [x] [Fix task instance api cannot list task instances with None state (#19487)](https://github.com/apache/airflow/pull/19487): @ephraimbuddy
- [x] [Fix IntegrityError in `DagFileProcessor.manage_slas` (#19553)](https://github.com/apache/airflow/pull/19553): @ephraimbuddy
- [ ] [Cast macro datetime string inputs explicitly (#19592)](https://github.com/apache/airflow/pull/19592): @uranusjr @ShaharPotash1
     Linked issues:
     - [Cast to string in ds macro functions (#19249)](https://github.com/apache/airflow/pull/19249)
     - [next_ds changed to proxy and it cannot be used in ds_add macro function (#19241)](https://github.com/apache/airflow/issues/19241)
- [ ] [Declare data interval fields as serializable (#19616)](https://github.com/apache/airflow/pull/19616): @uranusjr @feluelle
     Linked issues:
     - [Fix PythonVirtualenvOperator not working with Airflow context (#9394)](https://github.com/apache/airflow/pull/9394)
- [x] [Fix log endpoint for same task (#19672)](https://github.com/apache/airflow/pull/19672): @humit0
- [ ] [Enable task run setting to be able reinitialise (#19845)](https://github.com/apache/airflow/pull/19845): @khalidmammadov
     Linked issues:
     - [Capture container logs and upload as artficats when failed (#19755)](https://github.com/apache/airflow/pull/19755)
- [x] [Workaround occasional deadlocks with MSSQL (#19856)](https://github.com/apache/airflow/pull/19856): @potiuk
- [ ] [Relax timetable clas validation (#19878)](https://github.com/apache/airflow/pull/19878): @uranusjr @covaliov
     Linked issues:
     - [Custom Timetable Import Error (#19869)](https://github.com/apache/airflow/issues/19869)
- [ ] [Context class handles deprecation (#19886)](https://github.com/apache/airflow/pull/19886): @uranusjr @jj-ookla
     Linked issues:
     - [[Airflow 2.2.2] execution_date Proxy object - str formatting error  (#19716)](https://github.com/apache/airflow/issues/19716)
     - [Custom deprecation proxy implementing __format__ (#19734)](https://github.com/apache/airflow/pull/19734)
- [ ] [Validate DagRun state is valid on assignment (#19898)](https://github.com/apache/airflow/pull/19898): @uranusjr @frapa-az
     Linked issues:
     - [DAGRun API endpoint returns status 500 for some run states (#19836)](https://github.com/apache/airflow/issues/19836)
- [x] [Fix labels used to find queued KubeExecutor pods (#19904)](https://github.com/apache/airflow/pull/19904): @jedcunningham
- [ ] [Fix possible reference to undeclared variable "return_code" (#19933)](https://github.com/apache/airflow/pull/19933): @PApostol
- [ ] [Fix db downgrades (#19994)](https://github.com/apache/airflow/pull/19994): @jedcunningham
- [ ] [Don't use CREATE TABLE AS SELECT ... with mySQL (#19999)](https://github.com/apache/airflow/pull/19999): @SamWheating
- [x] [Fix infinite recursion on redact log (#20039)](https://github.com/apache/airflow/pull/20039): @aresabalo @potiuk
     Linked issues:
     - [logging error  (#19816)](https://github.com/apache/airflow/issues/19816)
- [ ] [Lift off upper bound for MarkupSafe (#20113)](https://github.com/apache/airflow/pull/20113): @tsingh2k15
     Linked issues:
     - [removing upper bound for markupsafe (#19761)](https://github.com/apache/airflow/issues/19761)
- [ ] [fixing #19028 by moving chown to use sudo (#20114)](https://github.com/apache/airflow/pull/20114): @jgmarcel @plockaby @kevinbsilva
     Linked issues:
     - [PermissionError when `core:default_impersonation` is set (#19028)](https://github.com/apache/airflow/issues/19028)
     - [Applied permissions to self._error_file (#15947)](https://github.com/apache/airflow/pull/15947)
- [x] [Fix log link in gantt view (#20121)](https://github.com/apache/airflow/pull/20121): @jedcunningham
- [x] [Bump minimum required ``alembic`` version (#20153)](https://github.com/apache/airflow/pull/20153): @kaxil
- [x] [Log provider import warnings as debug (#20172)](https://github.com/apache/airflow/pull/20172): @potiuk @Aakcht
     Linked issues:
     - [Turn provider's import warnings into debug logs (#14903)](https://github.com/apache/airflow/pull/14903)
     - [Adds secret backend and logging information to provider yaml (#17625)](https://github.com/apache/airflow/pull/17625)
     - [Unnecessary warnings during airflow pods starts (#20159)](https://github.com/apache/airflow/issues/20159)
- [x] [Switch default version of Python to 3.7 (#18922)](https://github.com/apache/airflow/pull/18922): @potiuk
- [ ] [Move away from legacy importlib.resources API (#19091)](https://github.com/apache/airflow/pull/19091): @uranusjr
- [x] [Fix race condition when starting DagProcessorAgent (#19935)](https://github.com/apache/airflow/pull/19935): @potiuk
     Linked issues:
     - [Restore stability and unquarantine all test_scheduler_job tests (#19860)](https://github.com/apache/airflow/pull/19860)
     - [Reloading of Logging and ORM in Dag Processing can be disruptive in spawn mode (#19934)](https://github.com/apache/airflow/issues/19934)
- [x] [Move setgid as the first command executed in forked task runner (#20040)](https://github.com/apache/airflow/pull/20040): @potiuk
- [x] [Fix flaky on_kill (#20054)](https://github.com/apache/airflow/pull/20054): @potiuk
     Linked issues:
     - [Move setgid as the first command executed in forked task runner (#20040)](https://github.com/apache/airflow/pull/20040)
- [x] [Fix failing main. (#20094)](https://github.com/apache/airflow/pull/20094): @ephraimbuddy
- [x] [Lazy Jinja2 context (#20217)](https://github.com/apache/airflow/pull/20217): @uranusjr @jedcunningham
     Linked issues:
     - [Context deprecation warnings when they aren't used (#20213)](https://github.com/apache/airflow/issues/20213)
- [x] [Limit httpx to <0.20.0 (#20218)](https://github.com/apache/airflow/pull/20218): @potiuk
- [ ] [Exclude snowflake-sqlalchemy v1.2.5 (#20245)](https://github.com/apache/airflow/pull/20245): @mik-laj

Thanks to all who contributed to the release (probably not a complete list!):
@SamWheating @ephraimbuddy @jgmarcel @humit0 @sartyukhov @potiuk @calfzhou @josh-fell @frapa-az @kevinbsilva @uranusjr @feluelle @jedcunningham @cb149 @khalidmammadov @aresabalo @bbovenzi @dstandish @tsingh2k15 @kaxil @PApostol @ShaharPotash1 @Aakcht @jj-ookla @covaliov @plockaby @mik-laj

**Comment by jedcunningham** [comment]
I found an issue in #19886 and opened #20213 to address it. This will result in an RC2, but we can continue with RC1 testing in the meantime.

**Comment by Aakcht** [comment]
#20172 works as expected - no more provider import errors unless you set debug log level in the configuration.

**Comment by khalidmammadov** [comment]
FYI: just added this -> https://github.com/apache/airflow/issues/20225

**Comment by raphaelauv** [comment]
#20217 is working on rc2

**Comment by josh-fell** [comment]
Validated #19411. Thanks for organizing this release @jedcunningham!

**Comment by calfzhou** [comment]
#19342 #19401 is working as expected, log timezone in web view is now correct.

**Comment by humit0** [comment]
#19672 is working well.

**Comment by potiuk** [comment]
Tested #19478, #20039, #20172, #18922, #20218

Those are hard to test (but I checked they are part of the airflow sources released and our stable tests are proof they work): #19856, #19935, #20040, #20054

**Comment by jedcunningham** [comment]
Thanks everyone, 2.2.3 has been released.
