### ISSUE TITLE
Status of testing Providers that were prepared on December 11, 2021

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#20220]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you help us to test the RC versions of the providers and let us know in the comment,
if the issue is addressed there.

## Providers that need testing

Those are providers that require testing as there were some substantial changes introduced:

### Provider [databricks: 2.1.0rc3](https://pypi.org/project/apache-airflow-providers-databricks/2.1.0rc3)
   - [ ] [Databricks: add more methods to represent run state information (#19723)](https://github.com/apache/airflow/pull/19723): @alexott
   - [x] [Databricks - allow Azure SP authentication on other Azure clouds (#19722)](https://github.com/apache/airflow/pull/19722): @alexott
   - [x] [Databricks: allow to specify PAT in Password field (#19585)](https://github.com/apache/airflow/pull/19585): @alexott
   - [x] [Databricks jobs 2.1 (#19544)](https://github.com/apache/airflow/pull/19544): @christophergrant
   - [x] [Update Databricks API from 2.0 to 2.1 (#19412)](https://github.com/apache/airflow/pull/19412): @Mokubyow
   - [x] [Authentication with AAD tokens in Databricks provider (#19335)](https://github.com/apache/airflow/pull/19335): @alexott
   - [x] [Update Databricks operators to match latest version of API 2.0 (#19443)](https://github.com/apache/airflow/pull/19443): @alexott
   - [x] [Remove db call from `DatabricksHook.__init__()` (#20180)](https://github.com/apache/airflow/pull/20180): @josh-fell
   - [x] [Fixup string concatenations (#19099)](https://github.com/apache/airflow/pull/19099): @blag
   - [x] [Databricks hook: fix expiration time check (#20036)](https://github.com/apache/airflow/pull/20036): @alexott

## Providers that do not need testing

Those are providers that were either doc-only or had changes that do not require testing.
 

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by alexott** [comment]
Tested #19585, #19335 (also covers #19722 and #20036), #19443 (covering both `jar_tasks` and `pipeline_tasks`), #19544 (also covers #19412) - #20180 was covered by all of these tests

These specific changes looks good

**Comment by potiuk** [comment]
Cool! :)
