### ISSUE TITLE
Status of testing Providers that were prepared on December 31, 2021

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#20615]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 2.6.0rc1](https://pypi.org/project/apache-airflow-providers-amazon/2.6.0rc1)
   - [ ] [Add aws_conn_id to DynamoDBToS3Operator (#20363)](https://github.com/apache/airflow/pull/20363): @pingzh
   - [ ] [Add two operators in AWS Providers: RedshiftResumeClusterOperator and RedshiftPauseClusterOperator (#19665)](https://github.com/apache/airflow/pull/19665): @dbarrundiag
   - [ ] [Added function in AWSAthenaHook to get s3 output query results file URI  (#20124)](https://github.com/apache/airflow/pull/20124): @subkanthi
   - [ ] [Add sensor for AWS Batch (#19850) (#19885)](https://github.com/apache/airflow/pull/19885): @yeshbash
   - [ ] [Add state details to EMR container failure reason (#19579)](https://github.com/apache/airflow/pull/19579): @Swalloow
   - [x] [Add support to replace S3 file on MySqlToS3Operator (#20506)](https://github.com/apache/airflow/pull/20506): @mariotaddeucci
   - [ ] [Fix backwards compatibility issue in AWS provider&#39;s _get_credentials (#20463)](https://github.com/apache/airflow/pull/20463): @potiuk
   - [ ] [Fix deprecation messages after splitting redshift modules (#20366)](https://github.com/apache/airflow/pull/20366): @dstandish
   - [x] [ECSOperator: fix KeyError on missing exitCode (#20264)](https://github.com/apache/airflow/pull/20264): @ssatia
   - [ ] [Bug fix in AWS glue operator when specifying the WorkerType &amp; NumberOfWorkers (#19787)](https://github.com/apache/airflow/pull/19787): @Ritika-Singhal
   - [ ] [Organize Sagemaker classes in Amazon provider (#20370)](https://github.com/apache/airflow/pull/20370): @bhavaniravi
   - [ ] [20139 - move emr_container hook (#20375)](https://github.com/apache/airflow/pull/20375): @bhavaniravi
   - [ ] [Standardize AWS Athena naming (#20305)](https://github.com/apache/airflow/pull/20305): @ferruzzi
   - [ ] [Standardize AWS EKS naming (#20354)](https://github.com/apache/airflow/pull/20354): @ferruzzi
   - [ ] [Standardize AWS Glue naming (#20372)](https://github.com/apache/airflow/pull/20372): @ferruzzi
   - [ ] [Standardize Amazon SES naming (#20367)](https://github.com/apache/airflow/pull/20367): @ferruzzi
   - [ ] [Standardize AWS CloudFormation naming (#20357)](https://github.com/apache/airflow/pull/20357): @ferruzzi
   - [ ] [Standardize AWS Lambda naming (#20365)](https://github.com/apache/airflow/pull/20365): @ferruzzi
   - [ ] [Standardize AWS Kinesis/Firehose naming (#20362)](https://github.com/apache/airflow/pull/20362): @ferruzzi
   - [ ] [Standardize Amazon SNS naming (#20368)](https://github.com/apache/airflow/pull/20368): @ferruzzi
   - [ ] [Split redshift cluster and redshift sql (#20276)](https://github.com/apache/airflow/pull/20276): @dstandish
   - [ ] [20139 - organize aws emr operators (#20160)](https://github.com/apache/airflow/pull/20160): @bhavaniravi
   - [ ] [Standardize AWS DataSync naming (#20328)](https://github.com/apache/airflow/pull/20328): @ferruzzi
   - [ ] [Deprecate passing execution_date to XCom methods (#19825)](https://github.com/apache/airflow/pull/19825): @ashb
   - [ ] [#20139 - Move Dms operators and Sensors (#20156)](https://github.com/apache/airflow/pull/20156): @bhavaniravi
   - [ ] [Organise S3 Classes in Amazon Provider (#20167)](https://github.com/apache/airflow/pull/20167): @KennyRich
   - [ ] [20139 - organize aws step_function (#20158)](https://github.com/apache/airflow/pull/20158): @bhavaniravi
   - [ ] [Organize EC2 classes in Amazon provider (#20157)](https://github.com/apache/airflow/pull/20157): @eladkal
   - [ ] [Move to watchtower 2.0.1 - Fixes Watchtower crash when logging empty line  (#19907)](https://github.com/apache/airflow/pull/19907): @o-nikolas
   - [ ] [Fix mypy aws example dags (#20497)](https://github.com/apache/airflow/pull/20497): @subkanthi
   - [x] [Delete pods by default in KubernetesPodOperator (#20575)](https://github.com/apache/airflow/pull/20575): @dstandish
## Provider [apache.druid: 2.2.0rc1](https://pypi.org/project/apache-airflow-providers-apache-druid/2.2.0rc1)
   - [x] [Add timeout parameter to druid operator so it can be used in hook (#19984)](https://github.com/apache/airflow/pull/19984): @piotrkmita
## Provider [apache.spark: 2.0.3rc1](https://pypi.org/project/apache-airflow-providers-apache-spark/2.0.3rc1)
   - [x] [Ensure Spark driver response is valid before setting UNKNOWN status (#19978)](https://github.com/apache/airflow/pull/19978): @PApostol
## Provider [cncf.kubernetes: 3.0.0rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/3.0.0rc1)
   - [x] [Simplify ``KubernetesPodOperator`` (#19572)](https://github.com/apache/airflow/pull/19572): @dstandish
   - [x] [Delete pods by default in KubernetesPodOperator (#20575)](https://github.com/apache/airflow/pull/20575): @dstandish
   - [x] [Move pod_mutation_hook call from PodManager to KubernetesPodOperator (#20596)](https://github.com/apache/airflow/pull/20596): @dstandish
   - [x] [Rename ``PodLauncher`` to ``PodManager`` (#20576)](https://github.com/apache/airflow/pull/20576): @dstandish
   - [x] [Add config and context params to KubernetesHook (#19695)](https://github.com/apache/airflow/pull/19695): @dstandish
   - [x] [Implement dry_run for KubernetesPodOperator (#20573)](https://github.com/apache/airflow/pull/20573): @dstandish
   - [x] [Clarify docstring for `build_pod_request_obj` (#20574)](https://github.com/apache/airflow/pull/20574): @dstandish
   - [x] [Fix Volume/VolumeMount KPO DeprecationWarning (#19726)](https://github.com/apache/airflow/pull/19726): @dimon222
## Provider [databricks: 2.2.0rc1](https://pypi.org/project/apache-airflow-providers-databricks/2.2.0rc1)
   - [x] [Add `wait_for_termination` option for Databricks Operators (#20536)](https://github.com/apache/airflow/pull/20536): @eskarimov
   - [x] [Update connection object to cached_property in DatabricksHook (#20526)](https://github.com/apache/airflow/pull/20526): @josh-fell
   - [ ] [Remove `host` as an instance attr in `DatabricksHook` (#20540)](https://github.com/apache/airflow/pull/20540): @josh-fell
   - [x] [Databricks: fix verification of Azure Managed Identity (#20550)](https://github.com/apache/airflow/pull/20550): @alexott
## Provider [docker: 2.4.0rc1](https://pypi.org/project/apache-airflow-providers-docker/2.4.0rc1)
   - [ ] [Allow DockerOperator&#39;s image to be templated (#19997)](https://github.com/apache/airflow/pull/19997): @jedcunningham
## Provider [facebook: 2.2.0rc1](https://pypi.org/project/apache-airflow-providers-facebook/2.2.0rc1)
   - [x] [Providers facebook hook multiple account (#19377)](https://github.com/apache/airflow/pull/19377): @bugraoz93
## Provider [google: 6.3.0rc1](https://pypi.org/project/apache-airflow-providers-google/6.3.0rc1)
   - [ ] [Add optional location to bigquery data transfer service (#15088) (#20221)](https://github.com/apache/airflow/pull/20221): @bradleybonitatibus
   - [x] [Add Google Cloud Tasks how-to documentation (#20145)](https://github.com/apache/airflow/pull/20145): @kazanzhy
   - [x] [Added example DAG for MSSQL to Google Cloud Storage (GCS) (#19873)](https://github.com/apache/airflow/pull/19873): @Bowrna
   - [x] [Support regional GKE cluster (#18966)](https://github.com/apache/airflow/pull/18966): @mrkm4ntr
   - [x] [Delete pods by default in KubernetesPodOperator (#20575)](https://github.com/apache/airflow/pull/20575): @dstandish
   - [x] [Fixes for templates for PubSubCreateSubscriptionOperator (#20237)](https://github.com/apache/airflow/pull/20237): @kolban-google
   - [ ] [Fix missing get_backup method for Dataproc Metastore (#20326)](https://github.com/apache/airflow/pull/20326): @potiuk
   - [x] [Fixed the minor typo (#19924)](https://github.com/apache/airflow/pull/19924): @mai-nakagawa
   - [x] [Fix passing the gzip compression parameter on sftp_to_gcs (#20553)](https://github.com/apache/airflow/pull/20553): @qgallet
   - [ ] [switch to follow_redirects on httpx.get call in CloudSQL provider (#20239)](https://github.com/apache/airflow/pull/20239): @philipherrmann
   - [x] [avoid deprecation warnings in BigQuery transfer operators (#20502)](https://github.com/apache/airflow/pull/20502): @eladkal
   - [ ] [Change download_video parameter to resourceName (#20528)](https://github.com/apache/airflow/pull/20528): @mishc9
   - [x] [Fix various BigQuery to MSSQL/MySQL transfer issues (#20001)](https://github.com/apache/airflow/pull/20001): @jon-fearer
   - [ ] [Fix setting of project ID in provide_authorized_gcloud (#20428)](https://github.com/apache/airflow/pull/20428): @jobegrabber
   - [x] [Move source_objects datatype check out of GCSToBigQueryOperator.__init__ (#20347)](https://github.com/apache/airflow/pull/20347): @josh-fell
   - [ ] [Organise S3 Classes in Amazon Provider (#20167)](https://github.com/apache/airflow/pull/20167): @KennyRich
   - [ ] [Providers facebook hook multiple account (#19377)](https://github.com/apache/airflow/pull/19377): @bugraoz93
   - [x] [Remove deprecated method call (blob.download_as_string) (#20091)](https://github.com/apache/airflow/pull/20091): @kazanzhy
   - [ ] [Remove deprecated template_fields and add update tests (#19977) (#19991)](https://github.com/apache/airflow/pull/19991): @bradleybonitatibus
## Provider [http: 2.0.2rc1](https://pypi.org/project/apache-airflow-providers-http/2.0.2rc1)
   - [ ] [Un-ignore DeprecationWarning (#20322)](https://github.com/apache/airflow/pull/20322): @uranusjr
## Provider [imap: 2.1.0rc1](https://pypi.org/project/apache-airflow-providers-imap/2.1.0rc1)
   - [ ] [Allow setting port in IMAP Connection (#20440)](https://github.com/apache/airflow/pull/20440): @feluelle
## Provider [jenkins: 2.0.4rc1](https://pypi.org/project/apache-airflow-providers-jenkins/2.0.4rc1)
   - [x] [Clean up JenkinsJobTriggerOperator (#19019)](https://github.com/apache/airflow/pull/19019): @xinbinhuang
## Provider [microsoft.azure: 3.5.0rc1](https://pypi.org/project/apache-airflow-providers-microsoft-azure/3.5.0rc1)
   - [ ] [Azure: New sftp to wasb operator (#18877)](https://github.com/apache/airflow/pull/18877): @wolvery
   - [ ] [Removes InputRequired validation with azure extra (#20084)](https://github.com/apache/airflow/pull/20084): @potiuk
   - [x] [Add operator link to monitor Azure Data Factory pipeline runs (#20207)](https://github.com/apache/airflow/pull/20207): @josh-fell
## Provider [mongo: 2.3.0rc1](https://pypi.org/project/apache-airflow-providers-mongo/2.3.0rc1)
   - [ ] [Fix: pin pymongo &lt; 4.0.0 (#20511)](https://github.com/apache/airflow/pull/20511): @ckljohn
   - [x] [19223 - add mongo_db param to function doc string (#19280)](https://github.com/apache/airflow/pull/19280): @bhavaniravi
## Provider [neo4j: 2.1.0rc1](https://pypi.org/project/apache-airflow-providers-neo4j/2.1.0rc1)
   - [x] [Add template fields to neo4j operator (#20043)](https://github.com/apache/airflow/pull/20043): @subkanthi
## Provider [opsgenie: 3.0.0rc1](https://pypi.org/project/apache-airflow-providers-opsgenie/3.0.0rc1)
   - [ ] [Add `OpsgenieCloseAlertOperator` (#20488)](https://github.com/apache/airflow/pull/20488): @eladkal
   - [ ] [Organize Opsgenie provider classes (#20454)](https://github.com/apache/airflow/pull/20454): @eladkal
   - [x] [rewrite opsgenie alert hook with official python sdk, related issue #18641 (#20263)](https://github.com/apache/airflow/pull/20263): @pierrejeambrun
   - [ ] [Rename `OpsgenieAlertOperator` to `OpsgenieCreateAlertOperator` (#20514)](https://github.com/apache/airflow/pull/20514): @eladkal
## Provider [oracle: 2.1.0rc1](https://pypi.org/project/apache-airflow-providers-oracle/2.1.0rc1)
   - [ ] [Add method &#39;callproc&#39; on Oracle hook (#20072)](https://github.com/apache/airflow/pull/20072): @malthe
   - [ ] [The &#39;cx_Oracle&#39; driver does support autocommit (#20085)](https://github.com/apache/airflow/pull/20085): @malthe
## Provider [papermill: 2.2.0rc1](https://pypi.org/project/apache-airflow-providers-papermill/2.2.0rc1)
   - [ ] [Add support to specify kernel name in PapermillOperator (#20035)](https://github.com/apache/airflow/pull/20035): @minhthong582000
## Provider [sftp: 2.4.0rc1](https://pypi.org/project/apache-airflow-providers-sftp/2.4.0rc1)
   - [x] [Making SFTPHook&#39;s constructor consistent with its superclass SSHHook (#20164)](https://github.com/apache/airflow/pull/20164): @saveriogzz
## Provider [snowflake: 2.4.0rc1](https://pypi.org/project/apache-airflow-providers-snowflake/2.4.0rc1)
   - [ ] [Support insecure mode in SnowflakeHook (#20106)](https://github.com/apache/airflow/pull/20106): @mik-laj
   - [ ] [Remove unused code in SnowflakeHook (#20107)](https://github.com/apache/airflow/pull/20107): @mik-laj
   - [x] [Improvements for `SnowflakeHook.get_sqlalchemy_engine`  (#20509)](https://github.com/apache/airflow/pull/20509): @harishkrao
   - [ ] [Exclude snowflake-sqlalchemy v1.2.5 (#20245)](https://github.com/apache/airflow/pull/20245): @mik-laj
   - [ ] [Limit Snowflake connector to&lt; 2.7.2 (#20395)](https://github.com/apache/airflow/pull/20395): @potiuk
## Provider [tableau: 2.1.3rc1](https://pypi.org/project/apache-airflow-providers-tableau/2.1.3rc1)
   - [x] [Ensure Tableau connection is active to access wait_for_state (#20433)](https://github.com/apache/airflow/pull/20433): @ericpp
## Provider [yandex: 2.2.0rc1](https://pypi.org/project/apache-airflow-providers-yandex/2.2.0rc1)
   - [ ] [YandexCloud provider: Support new Yandex SDK features: log_group_id, user-agent, maven packages (#20103)](https://github.com/apache/airflow/pull/20103): @Piatachock

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by PApostol** [comment]
#19978 addresses the issue and works as expected.

**Comment by saveriogzz** [comment]
#20164 all good! ✅

**Comment by mariotaddeucci** [comment]
#20506 all good o/

**Comment by eskarimov** [comment]
#20536 tested, works as expected ✅

**Comment by bhavaniravi** [comment]
#19280 is a docstring update, no code changes

**Comment by alexott** [comment]
#20550 is verified, works as intended

**Comment by pierrejeambrun** [comment]
https://github.com/apache/airflow/pull/20263 tested, works correctly.

**Comment by piotrkmita** [comment]
#19984 tested. It's working as expected.

**Comment by harishkrao** [comment]
#20509 tested, working as expected.

**Comment by raphaelauv** [comment]
Simplify KubernetesPodOperator (#19572): 

I tried different scenario it work correctly

**Comment by jon-fearer** [comment]
#20001 Looks good

**Comment by kazanzhy** [comment]
#20145 is devoted to the documentation
#20091 tests also changed as well

Looks good

**Comment by dstandish** [comment]
> ` Simplify KubernetesPodOperator (#19572)`
> 
> I tried different scenario it work correctly

Thank you @raphaelauv

I tested too... "works on my machine" ;)

**Comment by mrkm4ntr** [comment]
#18966 works as expected.

**Comment by subkanthi** [comment]
checked and tested #20043

**Comment by dstandish** [comment]
i checked off all the PRs related to the KubernetesPodOperator. installed provider and run it through test dags.

**Comment by potiuk** [comment]
Wooho. Getting quite good test coverage :) ! one more day to go !

**Comment by qgallet** [comment]
#20553 works as expected !
#19924 and #20237 are doc fixes.

I believe #20575 can be marked as addressed on amazon and google provider since it's okay on kubernetes ;-)

**Comment by ericpp** [comment]
#20433 is working great for me now!

**Comment by bugraoz93** [comment]
[#19377](https://github.com/apache/airflow/pull/19377) works as expected for both cases!

**Comment by dimon222** [comment]
#19726 briefly tested, seems to work as intended and not raising any problems.

**Comment by potiuk** [comment]
Last chance to make some quick testing :)

**Comment by josh-fell** [comment]
#20207, #20526, #20540, and #20347 look good!

**Comment by Bowrna** [comment]
#19873 verified the example DAG

**Comment by potiuk** [comment]
Thanks everyone for helping to thest that wave. It's been released !

**Comment by potiuk** [comment]
Thanks everyone for helping to thest that wave. It's been released !

**Comment by ssatia** [comment]
#20264 works as expected. We had the unexpected occur again and it was handled correctly this time around 🙌

**Comment by Ritika-Singhal** [comment]
#19787 works as expected
