### ISSUE TITLE
Status of testing Providers that were prepared on January 08, 2022

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#20766]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [cncf.kubernetes: 3.0.1rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/3.0.1rc1)
   - [ ] [Update Kubernetes library version and backport pickle-fix for Loggers (#18797)](https://github.com/apache/airflow/pull/18797): @ashb
## Provider [sftp: 2.4.1rc1](https://pypi.org/project/apache-airflow-providers-sftp/2.4.1rc1)
   - [ ] [Bugfix: ``SFTPHook`` does not respect ``ssh_conn_id`` arg (#20756)](https://github.com/apache/airflow/pull/20756): @kaxil
   - [ ] [fix deprecation messages for SFTPHook (#20692)](https://github.com/apache/airflow/pull/20692): @eladkal

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by eladkal** [comment]
Closing as providers were released
