### ISSUE TITLE
Status of testing Providers that were prepared on February 09, 2022

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#21443]
I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 3.0.0rc2](https://pypi.org/project/apache-airflow-providers-amazon/3.0.0rc2)
   - [x] [Rename params to cloudformation_parameter in CloudFormation operators. (#20989)](https://github.com/apache/airflow/pull/20989): @potiuk
   - [ ] [[SQSSensor] Add opt-in to disable auto-delete messages (#21159)](https://github.com/apache/airflow/pull/21159): @LaPetiteSouris
   - [x] [Create a generic operator SqlToS3Operator and deprecate the MySqlToS3Operator.  (#20807)](https://github.com/apache/airflow/pull/20807): @mariotaddeucci
   - [ ] [Move some base_aws logging from info to debug level (#20858)](https://github.com/apache/airflow/pull/20858): @o-nikolas
   - [ ] [Adds support for optional kwargs in the EKS Operators (#20819)](https://github.com/apache/airflow/pull/20819): @ferruzzi
   - [ ] [AwsAthenaOperator: do not generate client_request_token if not provided (#20854)](https://github.com/apache/airflow/pull/20854): @XD-DENG
   - [x] [Add more SQL template fields renderers (#21237)](https://github.com/apache/airflow/pull/21237): @josh-fell
   - [x] [Add conditional `template_fields_renderers` check for new SQL lexers (#21403)](https://github.com/apache/airflow/pull/21403): @josh-fell
   - [ ] [fix: cloudwatch logs fetch logic (#20814)](https://github.com/apache/airflow/pull/20814): @ayushchauhan0811
   - [x] [Fix all Amazon Provider MyPy errors (#20935)](https://github.com/apache/airflow/pull/20935): @potiuk
   - [ ] [Bug fix in AWS glue operator related to num_of_dpus #19787 (#21353)](https://github.com/apache/airflow/pull/21353): @Ritika-Singhal
   - [x] [Fix safe type cast error in aws mysql_to_s3  (#21277)](https://github.com/apache/airflow/pull/21277): @SasanAhmadi
   - [x] [Alleviate import warning for `EmrClusterLink` in deprecated AWS module (#21195)](https://github.com/apache/airflow/pull/21195): @josh-fell
   - [ ] [Rename amazon EMR hook name (#20767)](https://github.com/apache/airflow/pull/20767): @vinitpayal
   - [ ] [Standardize AWS SQS classes names (#20732)](https://github.com/apache/airflow/pull/20732): @eladkal
   - [ ] [Standardize AWS Batch naming (#20369)](https://github.com/apache/airflow/pull/20369): @ferruzzi
   - [ ] [Standardize AWS Redshift naming (#20374)](https://github.com/apache/airflow/pull/20374): @ferruzzi
   - [ ] [Standardize DynamoDB naming (#20360)](https://github.com/apache/airflow/pull/20360): @ferruzzi
   - [ ] [Standardize AWS ECS naming (#20332)](https://github.com/apache/airflow/pull/20332): @ferruzzi
   - [x] [Refactor operator links to not create ad hoc TaskInstances (#21285)](https://github.com/apache/airflow/pull/21285): @josh-fell
   - [x] [eks_hook log level fatal -&gt; FATAL  (#21427)](https://github.com/apache/airflow/pull/21427): @frankcash
## Provider [apache.druid: 2.3.0rc2](https://pypi.org/project/apache-airflow-providers-apache-druid/2.3.0rc2)
   - [x] [Add more SQL template fields renderers (#21237)](https://github.com/apache/airflow/pull/21237): @josh-fell
## Provider [apache.hive: 2.2.0rc2](https://pypi.org/project/apache-airflow-providers-apache-hive/2.2.0rc2)
   - [x] [Add more SQL template fields renderers (#21237)](https://github.com/apache/airflow/pull/21237): @josh-fell
   - [x] [Add conditional `template_fields_renderers` check for new SQL lexers (#21403)](https://github.com/apache/airflow/pull/21403): @josh-fell
## Provider [apache.spark: 2.1.0rc2](https://pypi.org/project/apache-airflow-providers-apache-spark/2.1.0rc2)
   - [x] [Add more SQL template fields renderers (#21237)](https://github.com/apache/airflow/pull/21237): @josh-fell
   - [x] [Add optional features in providers. (#21074)](https://github.com/apache/airflow/pull/21074): @potiuk
## Provider [apache.sqoop: 2.1.0rc2](https://pypi.org/project/apache-airflow-providers-apache-sqoop/2.1.0rc2)
   - [x] [Add more SQL template fields renderers (#21237)](https://github.com/apache/airflow/pull/21237): @josh-fell
## Provider [cncf.kubernetes: 3.0.2rc2](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/3.0.2rc2)
   - [ ] [Add missed deprecations for cncf (#20031)](https://github.com/apache/airflow/pull/20031): @dimon222
## Provider [docker: 2.4.1rc2](https://pypi.org/project/apache-airflow-providers-docker/2.4.1rc2)
   - [x] [Fixes Docker xcom functionality (#21175)](https://github.com/apache/airflow/pull/21175): @ferruzzi
   - [x] [Fix docker behaviour with byte lines returned (#21429)](https://github.com/apache/airflow/pull/21429): @potiuk
## Provider [exasol: 2.1.0rc2](https://pypi.org/project/apache-airflow-providers-exasol/2.1.0rc2)
   - [x] [Add more SQL template fields renderers (#21237)](https://github.com/apache/airflow/pull/21237): @josh-fell
## Provider [google: 6.4.0rc2](https://pypi.org/project/apache-airflow-providers-google/6.4.0rc2)
   - [ ] [[Part 1]: Add hook for integrating with Google Calendar (#20542)](https://github.com/apache/airflow/pull/20542): @rsg17
   - [ ] [Add encoding parameter to `GCSToLocalFilesystemOperator` to fix #20901 (#20919)](https://github.com/apache/airflow/pull/20919): @danneaves-ee
   - [ ] [batch as templated field in DataprocCreateBatchOperator (#20905)](https://github.com/apache/airflow/pull/20905): @wsmolak
   - [x] [Make timeout Optional for wait_for_operation (#20981)](https://github.com/apache/airflow/pull/20981): @MaksYermak
   - [x] [Add more SQL template fields renderers (#21237)](https://github.com/apache/airflow/pull/21237): @josh-fell
   - [x] [Create CustomJob and Datasets operators for Vertex AI service (#21253)](https://github.com/apache/airflow/pull/21253): @MaksYermak
   - [ ] [Support to upload file to Google Shared Drive (#21319)](https://github.com/apache/airflow/pull/21319): @lihan
   - [x] [Cloudsql import links fix. (#21199)](https://github.com/apache/airflow/pull/21199): @subkanthi
   - [ ] [Fix BigQueryDataTransferServiceHook.get_transfer_run() request parameter (#21293)](https://github.com/apache/airflow/pull/21293): @zaimy
   - [ ] [:bug: (BigQueryHook) fix compatibility with sqlalchemy engine (#19508)](https://github.com/apache/airflow/pull/19508): @david30907d
   - [ ] [Refactor operator links to not create ad hoc TaskInstances (#21285)](https://github.com/apache/airflow/pull/21285): @josh-fell
## Provider [http: 2.0.3rc2](https://pypi.org/project/apache-airflow-providers-http/2.0.3rc2)
   - [ ] [Split out confusing path combination logic to separate method (#21247)](https://github.com/apache/airflow/pull/21247): @malthe
## Provider [imap: 2.2.0rc2](https://pypi.org/project/apache-airflow-providers-imap/2.2.0rc2)
   - [ ] [Add &#34;use_ssl&#34; option to IMAP connection (#20441)](https://github.com/apache/airflow/pull/20441): @feluelle
## Provider [jdbc: 2.1.0rc2](https://pypi.org/project/apache-airflow-providers-jdbc/2.1.0rc2)
   - [x] [Add more SQL template fields renderers (#21237)](https://github.com/apache/airflow/pull/21237): @josh-fell
   - [x] [Add optional features in providers. (#21074)](https://github.com/apache/airflow/pull/21074): @potiuk
## Provider [microsoft.azure: 3.6.0rc2](https://pypi.org/project/apache-airflow-providers-microsoft-azure/3.6.0rc2)
   - [x] [Add optional features in providers. (#21074)](https://github.com/apache/airflow/pull/21074): @potiuk
   - [ ] [Refactor operator links to not create ad hoc TaskInstances (#21285)](https://github.com/apache/airflow/pull/21285): @josh-fell
## Provider [microsoft.mssql: 2.1.0rc2](https://pypi.org/project/apache-airflow-providers-microsoft-mssql/2.1.0rc2)
   - [x] [Add more SQL template fields renderers (#21237)](https://github.com/apache/airflow/pull/21237): @josh-fell
   - [x] [Add conditional `template_fields_renderers` check for new SQL lexers (#21403)](https://github.com/apache/airflow/pull/21403): @josh-fell
## Provider [microsoft.psrp: 1.1.0rc2](https://pypi.org/project/apache-airflow-providers-microsoft-psrp/1.1.0rc2)
   - [ ] [PSRP improvements (#19806)](https://github.com/apache/airflow/pull/19806): @malthe
## Provider [mysql: 2.2.0rc2](https://pypi.org/project/apache-airflow-providers-mysql/2.2.0rc2)
   - [x] [Add more SQL template fields renderers (#21237)](https://github.com/apache/airflow/pull/21237): @josh-fell
   - [x] [Add conditional `template_fields_renderers` check for new SQL lexers (#21403)](https://github.com/apache/airflow/pull/21403): @josh-fell
   - [x] [Refactor vertica_to_mysql to make it more &#39;mypy&#39; friendly (#20618)](https://github.com/apache/airflow/pull/20618): @potiuk
## Provider [oracle: 2.2.0rc2](https://pypi.org/project/apache-airflow-providers-oracle/2.2.0rc2)
   - [x] [Add more SQL template fields renderers (#21237)](https://github.com/apache/airflow/pull/21237): @josh-fell
   - [ ] [[Oracle] Oracle Hook - automatically set current_schema when defined in Connection (#19084)](https://github.com/apache/airflow/pull/19084): @mehmax
   - [ ] [Fix handling of Oracle bindvars in stored procedure call when parameters are not provided (#20720)](https://github.com/apache/airflow/pull/20720): @malthe
## Provider [postgres: 3.0.0rc2](https://pypi.org/project/apache-airflow-providers-postgres/3.0.0rc2)
   - [x] [Replaces the usage of postgres:// with postgresql:// (#21205)](https://github.com/apache/airflow/pull/21205): @potiuk
   - [x] [Add more SQL template fields renderers (#21237)](https://github.com/apache/airflow/pull/21237): @josh-fell
   - [x] [Add conditional `template_fields_renderers` check for new SQL lexers (#21403)](https://github.com/apache/airflow/pull/21403): @josh-fell
## Provider [qubole: 2.1.0rc2](https://pypi.org/project/apache-airflow-providers-qubole/2.1.0rc2)
   - [x] [Add optional features in providers. (#21074)](https://github.com/apache/airflow/pull/21074): @potiuk
   - [ ] [Add Qubole how to documentation (#20058)](https://github.com/apache/airflow/pull/20058): @kazanzhy
## Provider [slack: 4.2.0rc2](https://pypi.org/project/apache-airflow-providers-slack/4.2.0rc2)
   - [ ] [Return slack api call response in slack_hook (#21107)](https://github.com/apache/airflow/pull/21107): @pingzh
   - [x] [Fix template_fields type to have MyPy friendly Sequence type (#20571)](https://github.com/apache/airflow/pull/20571): @potiuk
## Provider [snowflake: 2.5.0rc2](https://pypi.org/project/apache-airflow-providers-snowflake/2.5.0rc2)
   - [x] [Add more SQL template fields renderers (#21237)](https://github.com/apache/airflow/pull/21237): @josh-fell
   - [ ] [Fix #21096: Support boolean in extra__snowflake__insecure_mode (#21155)](https://github.com/apache/airflow/pull/21155): @mik-laj
## Provider [sqlite: 2.1.0rc2](https://pypi.org/project/apache-airflow-providers-sqlite/2.1.0rc2)
   - [x] [Add more SQL template fields renderers (#21237)](https://github.com/apache/airflow/pull/21237): @josh-fell
## Provider [ssh: 2.4.0rc2](https://pypi.org/project/apache-airflow-providers-ssh/2.4.0rc2)
   - [x] [Add a retry with wait interval for SSH operator (#14489)](https://github.com/apache/airflow/issues/14489): @Gaurang033
   - [x] [Add banner_timeout feature to SSH Hook/Operator (#21262)](https://github.com/apache/airflow/pull/21262): @potiuk
   - [x] [Add a retry with wait interval for SSH operator #14489 (#19981)](https://github.com/apache/airflow/pull/19981): @nshetty15
   - [x] [Delay the creation of ssh proxy until `get_conn()` (#20474)](https://github.com/apache/airflow/pull/20474): @derkuci
## Provider [tableau: 2.1.4rc2](https://pypi.org/project/apache-airflow-providers-tableau/2.1.4rc2)
   - [ ] [Squelch more deprecation warnings (#21003)](https://github.com/apache/airflow/pull/21003): @uranusjr
## Provider [vertica: 2.1.0rc2](https://pypi.org/project/apache-airflow-providers-vertica/2.1.0rc2)
   - [x] [Add more SQL template fields renderers (#21237)](https://github.com/apache/airflow/pull/21237): @josh-fell
## Provider [zendesk: 3.0.0rc2](https://pypi.org/project/apache-airflow-providers-zendesk/3.0.0rc2)
   - [x] [Switch from zdesk to zenpy in ZendeskHook (#21349)](https://github.com/apache/airflow/pull/21349): @pierrejeambrun

**Comment by david30907d** [comment]
sure, will test it on weekend

**Comment by frankcash** [comment]
I was able to verify https://github.com/apache/airflow/pull/21427 has been resolved in this RC

**Comment by dstandish** [comment]
@potiuk any reason elasticsearch not included?
there was this change: https://github.com/apache/airflow/pull/21261
too late i guess?

**Comment by potiuk** [comment]
> @potiuk any reason elasticsearch not included? there was this change: #21261 too late i guess?

AAAAH good eye @dstandish. Thanks! 

This one was actually a mistake of mine.  I classified as "doc-only" change in RC1 (the only change was that it had :rtype removed from the docs). That triggered a mistake when I released an RC2 - because I re-classified it the same (but there were your changes merged since). 

I will continue with the release and wil re-release it after this voting (I will also take a look if I had not made similar RC1-> RC2 mistake).

**Comment by dstandish** [comment]
really it's @jedcunningham's eyes that are due any credit

but thank you very much @potiuk

**Comment by pierrejeambrun** [comment]
Hi,

I tested all the methods for the new ZendeskHook, everything is working fine.

#21349 :heavy_check_mark:

**Comment by potiuk** [comment]
Cool. Loooking forward for more comments. We have time till ~ weekend (I will release on Sunday/Monday morning if I get enough votes)

**Comment by kazanzhy** [comment]
Changes in **Qubole** provider was in documentation (https://github.com/apache/airflow/pull/20058) and typing (https://github.com/apache/airflow/pull/21074).
There are no code changes, therefore I'm pretty sure everything is OK.

**Comment by derkuci** [comment]
#20474 has been running in our system without issues.

**Comment by eladkal** [comment]
@potiuk why the new GitHub provider is missing?
https://github.com/apache/airflow/pull/21076

**Comment by SasanAhmadi** [comment]
@potiuk, I checked #21277 has been resolved in this RC.

**Comment by MaksYermak** [comment]
@potiuk I´ve checked #20981 and #21253 it works fine

**Comment by nshetty15** [comment]
@potiuk   #19981 is working fine without issues.

**Comment by mehmax** [comment]
Hi @potiuk 
I tested https://github.com/apache/airflow/pull/19084 in our environment. In some cases the backwards compatibility is not sufficient.
Improvement see PR https://github.com/apache/airflow/pull/21524

**Comment by josh-fell** [comment]
#21195, #21285, and #21403 Look good

#21237 Looks good except for an inconsequential typo in the `template_fields_renderers` dict for `HiveOperator` in the Apache Hive provider. 

TIL that the logic which chooses the renderer will, cleverly, default to the template field name if it cannot find said template field in the `template_fields_renderers` dict. For `HiveOperator` the key in `template_fields_renderers` is "sql" when it should be "hql". Luckily "hql" is itself a renderer so there is no impact on the visual rendering in the UI. @potiuk I created #21525 to fix the typo.

**Comment by potiuk** [comment]
> I tested #19084 in our environment. In some cases the backwards compatibility is not sufficient.
> Improvement see PR #21524

Cool. Will release it with elasticsearch as RC3 then (the longest Provider release ever :) )

**Comment by potiuk** [comment]
Tested: 
* #21704 across the board
* #20989 - tested that it is nicely "non-backwards compatible" for params passed (i.e. complains about cloudformation_parameters missing).
 #21205 -> postgresql 

![image](https://user-images.githubusercontent.com/595491/153654788-d202b1b9-3dd1-4da9-a57a-a9d6d59d86bd.png)

* #21175 and #21429 with slightly modified example to @raphaelauv :) (Polish people would understand)
![image](https://user-images.githubusercontent.com/595491/153651731-16b9d7cd-e301-4604-8be9-3020eb957e70.png)

Both #14489 and #21262 with SSH (both banner timeout and retry present in the log): 

```
[2022-02-11, 19:23:10 UTC] {transport.py:1873} ERROR - Exception (client): Error reading SSH protocol banner
[2022-02-11, 19:23:10 UTC] {transport.py:1871} ERROR - Traceback (most recent call last):
[2022-02-11, 19:23:10 UTC] {transport.py:1871} ERROR -   File "/usr/local/lib/python3.7/site-packages/paramiko/transport.py", line 2270, in _check_banner
[2022-02-11, 19:23:10 UTC] {transport.py:1871} ERROR -     buf = self.packetizer.readline(timeout)
[2022-02-11, 19:23:10 UTC] {transport.py:1871} ERROR -   File "/usr/local/lib/python3.7/site-packages/paramiko/packet.py", line 380, in readline
[2022-02-11, 19:23:10 UTC] {transport.py:1871} ERROR -     buf += self._read_timeout(timeout)
[2022-02-11, 19:23:10 UTC] {transport.py:1871} ERROR -   File "/usr/local/lib/python3.7/site-packages/paramiko/packet.py", line 622, in _read_timeout
[2022-02-11, 19:23:10 UTC] {transport.py:1871} ERROR -     raise socket.timeout()
[2022-02-11, 19:23:10 UTC] {transport.py:1871} ERROR - socket.timeout
[2022-02-11, 19:23:10 UTC] {transport.py:1871} ERROR - 
[2022-02-11, 19:23:10 UTC] {transport.py:1871} ERROR - During handling of the above exception, another exception occurred:
[2022-02-11, 19:23:10 UTC] {transport.py:1871} ERROR - 
[2022-02-11, 19:23:10 UTC] {transport.py:1871} ERROR - Traceback (most recent call last):
[2022-02-11, 19:23:10 UTC] {transport.py:1871} ERROR -   File "/usr/local/lib/python3.7/site-packages/paramiko/transport.py", line 2093, in run
[2022-02-11, 19:23:10 UTC] {transport.py:1871} ERROR -     self._check_banner()
[2022-02-11, 19:23:10 UTC] {transport.py:1871} ERROR -   File "/usr/local/lib/python3.7/site-packages/paramiko/transport.py", line 2275, in _check_banner
[2022-02-11, 19:23:10 UTC] {transport.py:1871} ERROR -     "Error reading SSH protocol banner" + str(e)
[2022-02-11, 19:23:10 UTC] {transport.py:1871} ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
[2022-02-11, 19:23:10 UTC] {transport.py:1871} ERROR - 
[2022-02-11, 19:23:10 UTC] {ssh.py:314} INFO - Failed to connect. Sleeping before retry attempt 1
[2022-02-11, 19:23:14 UTC] {ssh.py:314} INFO - Failed to connect. Sleeping before retry attempt 2
```

**Comment by subkanthi** [comment]
#21199 is only a documentation change and I see the change in the tag.

**Comment by pateash** [comment]
> k int

@potiuk, **apache-airflow-providers-GitHub** tested and working as expected.

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/16856802/153725246-74e5bcb2-92ac-40dc-82f1-f97fd36bb320.png">

**Comment by pateash** [comment]
@potiuk @eladkal ,

**apache-airflow-provider-github v1.0.0rc2** working as expected, I have validated against **airflow v2.2.3**
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/16856802/153725314-99d9525d-3676-4140-8442-bca9e9418958.png">

**Comment by potiuk** [comment]
Cool!

**Comment by david30907d** [comment]
#19008 has a bug, my bad 😅 
already sent a PR and hope I can pass the CI https://github.com/apache/airflow/pull/21542

**Comment by potiuk** [comment]
> #19008 has a bug, my bad sweat_smile already sent a PR and hope I can pass the CI #21542

Ah . Cool that you checked. I will exclude trino from the release too and release those (and rc3 will include trino as well).

**Comment by potiuk** [comment]
> > Ah . Cool that you checked. I will exclude trino from the release too and release those (and rc3 will include trino as well).
> 
> I think @david30907d meant #19508 not #19008. its about google provider not trino

Yeah. I realized it when approved it :)

**Comment by potiuk** [comment]
Glad that you checked @eladkal :)

**Comment by david30907d** [comment]
Oh sorry i have fat-fingers 😅

**Comment by potiuk** [comment]
Thanks for testing. All providers except oracle, elasticsearch, google from that batch have been released. Proceeding with rc3 for the three.
