### ISSUE TITLE
Status of testing Providers that were prepared on February 14, 2022

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#21557]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [elasticsearch: 2.2.0rc3](https://pypi.org/project/apache-airflow-providers-elasticsearch/2.2.0rc3)
   - [ ] [Emit &#34;logs not found&#34; message when ES logs appear to be missing (#21261)](https://github.com/apache/airflow/pull/21261): @dstandish
   - [ ] [Use compat data interval shim in log handlers (#21289)](https://github.com/apache/airflow/pull/21289): @uranusjr
## Provider [google: 6.4.0rc3](https://pypi.org/project/apache-airflow-providers-google/6.4.0rc3)
   - [ ] [[Part 1]: Add hook for integrating with Google Calendar (#20542)](https://github.com/apache/airflow/pull/20542): @rsg17
   - [ ] [Add encoding parameter to `GCSToLocalFilesystemOperator` to fix #20901 (#20919)](https://github.com/apache/airflow/pull/20919): @danneaves-ee
   - [ ] [batch as templated field in DataprocCreateBatchOperator (#20905)](https://github.com/apache/airflow/pull/20905): @wsmolak
   - [x] [Make timeout Optional for wait_for_operation (#20981)](https://github.com/apache/airflow/pull/20981): @MaksYermak
   - [x] [Add more SQL template fields renderers (#21237)](https://github.com/apache/airflow/pull/21237): @josh-fell
   - [x] [Create CustomJob and Datasets operators for Vertex AI service (#21253)](https://github.com/apache/airflow/pull/21253): @MaksYermak
   - [ ] [Support to upload file to Google Shared Drive (#21319)](https://github.com/apache/airflow/pull/21319): @lihan
   - [x] [:pencil: (providers_google) add a location check (#19571)](https://github.com/apache/airflow/pull/19571): @david30907d
   - [ ] [Add support for BeamGoPipelineOperator (#20386)](https://github.com/apache/airflow/pull/20386): @pierrejeambrun
   - [x] [Google Cloud Composer opearators - with the deferrable option (#21251)](https://github.com/apache/airflow/pull/21251): @lwyszomi
   - [ ] [Enable asynchronous job submission in BigQuery Insert Job (#21385)](https://github.com/apache/airflow/pull/21385): @phanikumv
   - [x] [Optionally raise an error if source file does not exist in GCSToGCSOperator (#21391)](https://github.com/apache/airflow/pull/21391): @davidpr91
   - [x] [Cloudsql import links fix. (#21199)](https://github.com/apache/airflow/pull/21199): @subkanthi
   - [ ] [Fix BigQueryDataTransferServiceHook.get_transfer_run() request parameter (#21293)](https://github.com/apache/airflow/pull/21293): @zaimy
   - [x] [:bug: (BigQueryHook) fix compatibility with sqlalchemy engine (#19508)](https://github.com/apache/airflow/pull/19508): @david30907d
   - [x] [Refactor operator links to not create ad hoc TaskInstances (#21285)](https://github.com/apache/airflow/pull/21285): @josh-fell
## Provider [oracle: 2.2.0rc3](https://pypi.org/project/apache-airflow-providers-oracle/2.2.0rc3)
   - [x] [Add more SQL template fields renderers (#21237)](https://github.com/apache/airflow/pull/21237): @josh-fell
   - [x] [[Oracle] Oracle Hook - automatically set current_schema when defined in Connection (#19084)](https://github.com/apache/airflow/pull/19084): @mehmax
   - [x] [[Oracle] Oracle Improved backwards compatibility of change PR #19084 (#21524)](https://github.com/apache/airflow/pull/21524): @mehmax
   - [ ] [Fix handling of Oracle bindvars in stored procedure call when parameters are not provided (#20720)](https://github.com/apache/airflow/pull/20720): @malthe

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
I marked as tested those changes that were tested in RC2: in #21443 - but feel free to re-test them.

**Comment by david30907d** [comment]
@potiuk , I'd checked #19508 and #19570 and they worked fine ✔️

**Comment by lwyszomi** [comment]
I missed previous call, but checked the composer operators once again and all works good (#21251)

**Comment by josh-fell** [comment]
#21285 Looks good!

**Comment by potiuk** [comment]
We have one more day :)

**Comment by davidpr91** [comment]
#21391 works good!

**Comment by mehmax** [comment]
#19084 and #21524 works good!

**Comment by potiuk** [comment]
Thanks everyone for testing! Providers are released!
