### ISSUE TITLE
Status of testing Providers that were prepared on March 07, 2022

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#22063]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-amazon/3.1.0rc1)
   - [x] [Added AWS RDS sensors (#21231)](https://github.com/apache/airflow/pull/21231): @kazanzhy
   - [x] [Added AWS RDS operators (#20907)](https://github.com/apache/airflow/pull/20907): @kazanzhy
   - [ ] [Add RedshiftDataHook (#19137)](https://github.com/apache/airflow/pull/19137): @john-jac
   - [x] [Feature: Add invoke lambda function operator (#21686)](https://github.com/apache/airflow/pull/21686): @schirag1993
   - [ ] [Add JSON output on SqlToS3Operator (#21779)](https://github.com/apache/airflow/pull/21779): @mariotaddeucci
   - [x] [Implement a Sagemaker DeleteModelOperator and Delete model hook. (#21673)](https://github.com/apache/airflow/pull/21673): @hsrocks
   - [x] [Added Hook for Amazon RDS (#20642)](https://github.com/apache/airflow/pull/20642): @kazanzhy
   - [ ] [Added SNS example DAG and rst (#21475)](https://github.com/apache/airflow/pull/21475): @ferruzzi
   - [x] [retry on very specific eni provision failures (#22002)](https://github.com/apache/airflow/pull/22002): @zachliu
   - [x] [Configurable AWS Session Factory (#21778)](https://github.com/apache/airflow/pull/21778): @ac1997
   - [ ] [S3KeySensor to use S3Hook url parser (#21500)](https://github.com/apache/airflow/pull/21500): @dstandish
   - [x] [ECSOperator: Get log events after sleep to get all logs (#21574)](https://github.com/apache/airflow/pull/21574): @kanga333
   - [ ] [Use temporary file in GCSToS3Operator (#21295)](https://github.com/apache/airflow/pull/21295): @rafalh
   - [ ] [Fix the Type Hints in ``RedshiftSQLOperator`` (#21885)](https://github.com/apache/airflow/pull/21885): @kaxil
   - [ ] [Bug Fix - S3DeleteObjectsOperator will try and delete all keys (#21458)](https://github.com/apache/airflow/pull/21458): @njrs92
   - [ ] [Fix Amazon SES emailer signature (#21681)](https://github.com/apache/airflow/pull/21681): @potiuk
   - [ ] [Fix EcsOperatorError, so it can be loaded from a picklefile (#21441)](https://github.com/apache/airflow/pull/21441): @ngwallace
   - [x] [[doc] Improve s3 operator example by adding task upload_keys (#21422)](https://github.com/apache/airflow/pull/21422): @zhongjiajie
   - [ ] [Add docs and sample dags for AWS Batch Operator/Sensor (#22010)](https://github.com/apache/airflow/pull/22010): @o-nikolas
   - [x] [Cleanup RedshiftSQLOperator documentation (#21976)](https://github.com/apache/airflow/pull/21976): @vincbeck
   - [x] [Move S3ToRedshiftOperator documentation to transfer dir (#21975)](https://github.com/apache/airflow/pull/21975): @vincbeck
   - [x] [Rename &#39;S3&#39; hook name to &#39;Amazon S3&#39; (#21988)](https://github.com/apache/airflow/pull/21988): @TreyYi
   - [ ] [Update ECS sample DAG and Docs to new standards (#21828)](https://github.com/apache/airflow/pull/21828): @ferruzzi
   - [ ] [Update EKS sample DAGs and docs (#21523)](https://github.com/apache/airflow/pull/21523): @ferruzzi
## Provider [apache.beam: 3.2.0rc1](https://pypi.org/project/apache-airflow-providers-apache-beam/3.2.0rc1)
   - [ ] [Add support for BeamGoPipelineOperator (#20386)](https://github.com/apache/airflow/pull/20386): @pierrejeambrun
## Provider [apache.hdfs: 2.2.1rc1](https://pypi.org/project/apache-airflow-providers-apache-hdfs/2.2.1rc1)
   - [ ] [Add how-to guide for WebHDFS operators (#21393)](https://github.com/apache/airflow/pull/21393): @Melodie97
## Provider [apache.hive: 2.3.0rc1](https://pypi.org/project/apache-airflow-providers-apache-hive/2.3.0rc1)
   - [ ] [Set larger limit get_partitions_by_filter in HiveMetastoreHook (#21504)](https://github.com/apache/airflow/pull/21504): @pingzh
   - [ ] [Add Python 3.9 support to Hive (#21893)](https://github.com/apache/airflow/pull/21893): @potiuk
   - [x] [Fix key typo in `template_fields_renderers` for `HiveOperator` (#21525)](https://github.com/apache/airflow/pull/21525): @josh-fell
   - [ ] [add how-to guide for hive operator (#21590)](https://github.com/apache/airflow/pull/21590): @Melodie97
## Provider [apache.livy: 2.2.0rc1](https://pypi.org/project/apache-airflow-providers-apache-livy/2.2.0rc1)
   - [ ] [ Added retries to LivyHook #19384  (#21550)](https://github.com/apache/airflow/pull/21550): @utkarsharma2
   - [ ] [add how-to guide for livy operator (#21529)](https://github.com/apache/airflow/pull/21529): @Melodie97
## Provider [apache.spark: 2.1.1rc1](https://pypi.org/project/apache-airflow-providers-apache-spark/2.1.1rc1)
   - [x] [fix param rendering in docs of SparkSubmitHook (#21788)](https://github.com/apache/airflow/pull/21788): @eladkal
## Provider [cncf.kubernetes: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/3.1.0rc1)
   - [ ] [Add map_index label to mapped KubernetesPodOperator (#21916)](https://github.com/apache/airflow/pull/21916): @ashb
   - [ ] [Change KubePodOperator labels from exeuction_date to run_id (#21960)](https://github.com/apache/airflow/pull/21960): @ashb
   - [x] [Fix Kubernetes example with wrong operator casing (#21898)](https://github.com/apache/airflow/pull/21898): @potiuk
   - [x] [Remove types from KPO docstring (#21826)](https://github.com/apache/airflow/pull/21826): @jedcunningham
## Provider [databricks: 2.3.0rc1](https://pypi.org/project/apache-airflow-providers-databricks/2.3.0rc1)
   - [x] [Add-showing-runtime-error-feature-to-DatabricksSubmitRunOperator (#21709)](https://github.com/apache/airflow/pull/21709): @akifcakir
   - [x] [Databricks: add support for triggering jobs by name (#21663)](https://github.com/apache/airflow/pull/21663): @eskarimov
   - [ ] [Added template_ext = (&#39;.json&#39;) to databricks operators #18925 (#21530)](https://github.com/apache/airflow/pull/21530): @utkarsharma2
   - [x] [Databricks SQL operators (#21363)](https://github.com/apache/airflow/pull/21363): @alexott
   - [x] [Updated Databricks docs for correct jobs 2.1 API and links (#21494)](https://github.com/apache/airflow/pull/21494): @tfayyaz
## Provider [docker: 2.5.0rc1](https://pypi.org/project/apache-airflow-providers-docker/2.5.0rc1)
   - [x] [added docker network_mode options in documentation (#21986)](https://github.com/apache/airflow/pull/21986): @Bowrna
## Provider [elasticsearch: 3.0.0rc1](https://pypi.org/project/apache-airflow-providers-elasticsearch/3.0.0rc1)
   - [ ] [Change default log filename template to include map_index (#21495)](https://github.com/apache/airflow/pull/21495): @ashb
## Provider [ftp: 2.1.0rc1](https://pypi.org/project/apache-airflow-providers-ftp/2.1.0rc1)
   - [x] [[Feature] Updates FTPHook provider to have test_connection (#21997)](https://github.com/apache/airflow/pull/21997): @frankcash
## Provider [google: 6.5.0rc1](https://pypi.org/project/apache-airflow-providers-google/6.5.0rc1)
   - [x] [Add Looker PDT operators (#20882)](https://github.com/apache/airflow/pull/20882): @alekseiloginov
   - [x] [Add autodetect arg to external table creation in GCS-to-BQ operator (#21944)](https://github.com/apache/airflow/pull/21944): @shahkshitij15
   - [x] [Dataproc assets (#21756)](https://github.com/apache/airflow/pull/21756): @wojsamjan
   - [ ] [Create Auto ML operators for Vertex AI service (#21470)](https://github.com/apache/airflow/pull/21470): @MaksYermak
   - [ ] [[Part 2] Calendar to GCS Operator (#20769)](https://github.com/apache/airflow/pull/20769): @rsg17
   - [ ] [Make project_id argument optional in all dataproc operators (#21866)](https://github.com/apache/airflow/pull/21866): @rafalh
   - [ ] [Allow templates in more DataprocUpdateClusterOperator fields (#21865)](https://github.com/apache/airflow/pull/21865): @rafalh
   - [x] [Dataflow Assets (#21639)](https://github.com/apache/airflow/pull/21639): @lwyszomi
   - [ ] [Extract ClientInfo to module level (#21554)](https://github.com/apache/airflow/pull/21554): @pierrejeambrun
   - [x] [Datafusion assets (#21518)](https://github.com/apache/airflow/pull/21518): @wojsamjan
   - [x] [Dataproc metastore assets (#21267)](https://github.com/apache/airflow/pull/21267): @wojsamjan
   - [ ] [Normalize *_conn_id parameters in BigQuery sensors (#21430)](https://github.com/apache/airflow/pull/21430): @rafalh
   - [ ] [Fix bigquery_dts parameter docstring typo (#21786)](https://github.com/apache/airflow/pull/21786): @totogo
   - [x] [Fixed PostgresToGCSOperator fail on empty resultset for use_server_side_cursor=True (#21307)](https://github.com/apache/airflow/pull/21307): @kazanzhy
   - [ ] [Fix multi query scenario in bigquery example DAG (#21575)](https://github.com/apache/airflow/pull/21575): @phanikumv
   - [ ] [Unpin `google-cloud-memcache` (#21912)](https://github.com/apache/airflow/pull/21912): @kaxil
   - [ ] [Unpin ``pandas-gbq`` and remove unused code (#21915)](https://github.com/apache/airflow/pull/21915): @kaxil
   - [x] [Remove cursor methods calls from GCSToBigQueryOperator (#20119)](https://github.com/apache/airflow/pull/20119): @kazanzhy
## Provider [hashicorp: 2.1.2rc1](https://pypi.org/project/apache-airflow-providers-hashicorp/2.1.2rc1)
   - [ ] [Fix Vault default conn name (#20792)](https://github.com/apache/airflow/pull/20792): @ac1997
## Provider [http: 2.1.0rc1](https://pypi.org/project/apache-airflow-providers-http/2.1.0rc1)
   - [x] [Add &#39;method&#39; to attributes in HttpSensor (#21831)](https://github.com/apache/airflow/pull/21831): @h2cone
## Provider [microsoft.azure: 3.7.0rc1](https://pypi.org/project/apache-airflow-providers-microsoft-azure/3.7.0rc1)
   - [x] [Add `test_connection` method to `AzureDataFactoryHook` (#21924)](https://github.com/apache/airflow/pull/21924): @josh-fell  : Note: It won't work until #21330 is released.
   - [ ] [Add pre-commit check for docstring param types (#21398)](https://github.com/apache/airflow/pull/21398): @dstandish
   - [x] [Make container creation configurable when uploading files via WasbHook (#20510)](https://github.com/apache/airflow/pull/20510): @josh-fell
   - [ ] [(AzureCosmosDBHook) Update to latest Cosmos API (#21514)](https://github.com/apache/airflow/pull/21514): @BenGatewood
## Provider [mysql: 2.2.1rc1](https://pypi.org/project/apache-airflow-providers-mysql/2.2.1rc1)
   - [ ] [Make dbapi inherit get_uri from connection (#21764)](https://github.com/apache/airflow/pull/21764): @bolkedebruin
   - [x] [Task names should be consistent with variable names (drop vs create) in example dags (#21434)](https://github.com/apache/airflow/pull/21434): @vinooganesh
## Provider [oracle: 2.2.1rc1](https://pypi.org/project/apache-airflow-providers-oracle/2.2.1rc1)
   - [ ] [Fix oracle test connection (#21699)](https://github.com/apache/airflow/pull/21699): @hubert-pietron
## Provider [postgres: 4.0.0rc1](https://pypi.org/project/apache-airflow-providers-postgres/4.0.0rc1)
   - [ ] [Replaces the usage of postgres:// with postgresql:// (#21205)](https://github.com/apache/airflow/pull/21205): @potiuk
   - [x] [Add more SQL template fields renderers (#21237)](https://github.com/apache/airflow/pull/21237): @josh-fell
   - [x] [Add conditional `template_fields_renderers` check for new SQL lexers (#21403)](https://github.com/apache/airflow/pull/21403): @josh-fell
## Provider [presto: 2.1.0rc1](https://pypi.org/project/apache-airflow-providers-presto/2.1.0rc1)
   - [ ] [Add GCSToPrestoOperator (#21084)](https://github.com/apache/airflow/pull/21084): @rsg17
   - [ ] [Quick Update GCS Presto (#21855)](https://github.com/apache/airflow/pull/21855): @rsg17
   - [ ] [Replaced hql references to sql in TrinoHook and PrestoHook #21597 (#21630)](https://github.com/apache/airflow/pull/21630): @utkarsharma2
   - [x] [Fix K8S changelog to be PyPI-compatible (#20614)](https://github.com/apache/airflow/pull/20614): @potiuk
   - [x] [Fix MyPy Errors for Presto provider (#20244)](https://github.com/apache/airflow/pull/20244): @kazanzhy
## Provider [sftp: 2.5.0rc1](https://pypi.org/project/apache-airflow-providers-sftp/2.5.0rc1)
   - [x] [[Feature] Updates FTPHook provider to have test_connection (#21997)](https://github.com/apache/airflow/pull/21997): @frankcash
## Provider [trino: 2.1.0rc1](https://pypi.org/project/apache-airflow-providers-trino/2.1.0rc1)
   - [ ] [Add GCSToTrinoOperator (#21704)](https://github.com/apache/airflow/pull/21704): @rsg17
## Provider [zendesk: 3.0.1rc1](https://pypi.org/project/apache-airflow-providers-zendesk/3.0.1rc1)
   - [x] [Update Zendesk example DAG to use TaskFlow API (#21411)](https://github.com/apache/airflow/pull/21411): @josh-fell

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by vinooganesh** [comment]
#21434 looks good (docs change)

**Comment by kazanzhy** [comment]
#21307 - tested before PR
#20119 - seems OK
#20244 - OK

#20642 - In progress
#20907 - In progress
#21231 - In progress

**Comment by TreyYi** [comment]
#21988 Looks good (hook name change)

**Comment by zhongjiajie** [comment]
#21422  Looking good, and it just docs change BTW

**Comment by alexott** [comment]
Checked #21363 from the `main` branch, works. 
#21494 looks good. 

The rest for Databricks operator are also looks good from the source code perspective

**Comment by hsrocks** [comment]
#21673 Tested it. Worked fine

**Comment by h2cone** [comment]
#21831 Tested it, LGTM.

**Comment by akifcakir** [comment]
https://github.com/apache/airflow/pull/21709 tested it , works fine.

**Comment by potiuk** [comment]
Thanks for the tests so far :) . 

FYI. For those who struggle on how to test, here is a helpful guideline:

https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-by-contributors

I will add it to the issue template for next wave :)

**Comment by frankcash** [comment]
Confirmed https://github.com/apache/airflow/pull/21997 via the UI utility and running a task that calls `.test_connection()` for both FTP and SFTP hooks

**Comment by schirag1993** [comment]
Tested https://github.com/apache/airflow/pull/21686 - works as expected

**Comment by vincbeck** [comment]
#21975 is good too. Docs change only

**Comment by ac1997** [comment]
#21778 looks good. Thanks!

**Comment by vincbeck** [comment]
#19137 Found out some bugs while testing it. Will submit a PR soon

**Comment by alekseiloginov** [comment]
#20882 looks good, thanks!

**Comment by potiuk** [comment]
> #19137 Found out some bugs while testing it. Will submit a PR soon

Regression or some new stuff added has errors @vincbeck ?

**Comment by vincbeck** [comment]
> > #19137 Found out some bugs while testing it. Will submit a PR soon
> 
> Regression or some new stuff added has errors @vincbeck ?

New stuff

**Comment by potiuk** [comment]
> New stuff

Cool. Does not block AWS provider from releasing :) . We can release a new version right after.

**Comment by kanga333** [comment]
I tested #21574. It worked fine. LGTM!

**Comment by potiuk** [comment]
Cool. We have one more day and we are doing good with the new Providers. This one is great as will let us move to Python 3.10 finally :)

**Comment by eladkal** [comment]
@potiuk if we still can https://github.com/apache/airflow/pull/21788 should be skipped from change log.
I guess the skip log label isn't used for providers?

**Comment by potiuk** [comment]
> @potiuk if we still can #21788 should be skipped from change log. Its a change that doesn't require testing I guess the skip log label isn't used for providers?

Nope. It's not (and we might add it though I think with the coming towncrier changes we might not want to invest in it). 

We can always remove the changelog entry from the docs (but not from the package README),

**Comment by zachliu** [comment]
i tested https://github.com/apache/airflow/pull/22002. good news: the retry did kick in :rocket: 
however, i'd like to add `reraise: True` in the `default_kwargs` here https://github.com/apache/airflow/blob/a4d514bd7f7777e5bf03e9fa8e567f1c8774a74d/airflow/providers/amazon/aws/hooks/base_aws.py#L588-L594

otherwise we get a very vague exception when we exhaust all retries
```
tenacity.RetryError: RetryError[<Future at 0x7f143d69a9a0 state=finished raised Exception>]
```

**Comment by eskarimov** [comment]
Tested functionality introduced with #21663, works as expected.

**Comment by potiuk** [comment]
@kazanzhy the #22125 is also "new" stuff fix righ ? If so, we will release this RC tomorrow and i will run next Amazon provider release right after

**Comment by josh-fell** [comment]
#21525, #21237, #21403. and #21411 look good!

#21924 unfortunately won't work until #21330 is released (presumably in Airflow 2.3).

I should be able to get to testing #20510 later today.

@potiuk It's not part of this issue but when testing the new dbt Cloud provider a couple parameters in an operator that don't work quite as intended, but there is a workaround to get the same functionality with existing operator as written though. I can work on getting a fix in tonight but I was wondering if it would be possible to release an rc2 for dbt Cloud? Even though there is a workaround, it would be nice to have v1.0.0 work as expected out of the gate. WDYT?

**Comment by potiuk** [comment]
> @potiuk It's not part of this issue but when testing the new dbt Cloud provider a couple parameters in an operator don't work quite as intended, but there is a workaround to get the same functionality with existing operator as written though. I can work on getting a fix in tonight but I was wondering if it would be possible to release an rc2 for dbt Cloud? Even though there is a workaround, it would be nice to have v1.0.0 work as expected out of the gate. WDYT?

Sure. I can remove dbt from the list easily.

**Comment by potiuk** [comment]
> #21924 unfortunately won't work until #21330 is released (presumably in Airflow 2.3).

Too bad. Not critical though.

**Comment by shahkshitij15** [comment]
#21944 tested it, LGTM

**Comment by josh-fell** [comment]
> > @potiuk It's not part of this issue but when testing the new dbt Cloud provider a couple parameters in an operator don't work quite as intended, but there is a workaround to get the same functionality with existing operator as written though. I can work on getting a fix in tonight but I was wondering if it would be possible to release an rc2 for dbt Cloud? Even though there is a workaround, it would be nice to have v1.0.0 work as expected out of the gate. WDYT?
> 
> Sure. I can remove dbt from the list easily.

Thanks @potiuk!

**Comment by kazanzhy** [comment]
@potiuk 
Yes. #22125 fixes this new RDS functionality that is not covered by moto tests.

**Comment by zachliu** [comment]
@potiuk oh :hankey: there is a bug :sweat_smile: in https://github.com/apache/airflow/pull/22002
fix coming right up...https://github.com/apache/airflow/pull/22137

**Comment by josh-fell** [comment]
#20510 looks good too. Thanks for organizing the release as usual @potiuk

**Comment by lwyszomi** [comment]
#21756 #21639 #21518 and #21267 look good

**Comment by potiuk** [comment]
> @potiuk oh  there is a bug  in #22002

Right. Seems like Amazon accumulated enough fixes to skip it from the release and run RC2 :)

**Comment by Bowrna** [comment]
#21986 looks good, documentation changes only :)

**Comment by alexott** [comment]
if we'll do second set of releases, then it would be nice to get another release for databricks provider - to include #22076

**Comment by potiuk** [comment]
> if we'll do second set of releases, then it would be nice to get another release for databricks provider - to include #22076

I think unless we find some problems, I prefer to release only those that we have to as RC2. I thin this is not very far for the next month release :).

**Comment by jedcunningham** [comment]
Checked and the change from #21826 is in the release.

**Comment by potiuk** [comment]
Thanks everyone! I will proceed with releasing those and will release amazon/dbt RC2 shortly.
