### ISSUE TITLE
Status of testing of Apache Airflow Helm Chart 1.5.0rc2

### ISSUE THREAD

**Issue by ephraimbuddy** [apache/airflow#22096]
### Body

We have a kind request for all the contributors to the latest [Apache Airflow Helm Chart 1.5.0rc2](https://dist.apache.org/repos/dist/dev/airflow/helm-chart/1.5.0rc2).

Could you please help us to test the RC versions of the Airflow Helm Chart?

Please let us know in the comment if the issue is addressed in the latest RC.

- [ ] [AIRFLOW-20533: add airflow.cfg as volumeMounts on initContainer wait-… (#20609)](https://github.com/apache/airflow/pull/20609): @demetthyl
- [ ] [Helm Chart - support for priorityClassName (#20794)](https://github.com/apache/airflow/pull/20794): @YossiTamari @subkanthi
     Linked issues:
     - [Add priorityClassName support (#20632)](https://github.com/apache/airflow/issues/20632)
- [ ] [Speedup liveness probe for scheduler and triggerer (#20833)](https://github.com/apache/airflow/pull/20833): @dstandish
- [ ] [Add support for custom command and args in jobs (#20864)](https://github.com/apache/airflow/pull/20864): @jedcunningham
- [ ] [Fix liveness probe speedup for scheduler and triggerer (#21108)](https://github.com/apache/airflow/pull/21108): @dstandish
- [ ] [Grant pod log reader to triggerer serviceaccount (#21111)](https://github.com/apache/airflow/pull/21111): @dstandish
- [ ] [Helm: Fix elasticsearch URL in secret when username/password fields are empty, (#21222)](https://github.com/apache/airflow/pull/21222): @jedcunningham @subkanthi
     Linked issues:
     - [Elasticsearch connection user and password should be optional (#20560)](https://github.com/apache/airflow/issues/20560)
- [x] [Chart: Update git-sync to v3.4.0 (#21309)](https://github.com/apache/airflow/pull/21309): @dnskr
- [ ] [added envFrom statement to the flower deployment (#21401)](https://github.com/apache/airflow/pull/21401): @riccardo-salamanna
- [ ] [Fix annotations not getting added to cleanup pods (#21484)](https://github.com/apache/airflow/pull/21484): @jonstacks
     Linked issues:
     - [No way to supply custom annotations for cleanup cron job pods (#21469)](https://github.com/apache/airflow/issues/21469)
- [ ] [Remove default auth backend setting (#21640)](https://github.com/apache/airflow/pull/21640): @norm
- [x] [Chart: Default to Airflow 2.2.4 (#21745)](https://github.com/apache/airflow/pull/21745): @jedcunningham
- [x] [Change Redis image to bullseye (#21875)](https://github.com/apache/airflow/pull/21875): @vmalakhin @potiuk
     Linked issues:
     - [Docker image - Migrate to 3.x-slim-bullseye from 3.x-slim-buster  (#18190)](https://github.com/apache/airflow/issues/18190)
     - [Migrating to Bullseye images from Buster  (#18279)](https://github.com/apache/airflow/pull/18279)
- [ ] [Fix/21994 liveness probe (#22041)](https://github.com/apache/airflow/pull/22041): @Wilderone

Thanks to all who contributed to the release (probably not a complete list!):
@vmalakhin @norm @subkanthi @potiuk @dnskr @dstandish @riccardo-salamanna @YossiTamari @Wilderone @demetthyl @jonstacks @jedcunningham

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
Installed the chart verifed that:

* redis is based on bullseye now #21875
* checked that default image is 2.2.4 #21745 

```
root@airflow-redis-0:/data# cat /etc/*-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@airflow-redis-0:/data# 
```

![image](https://user-images.githubusercontent.com/595491/157310105-36cdf830-3dcb-4a4d-b061-56e96f4950c9.png)

**Comment by dnskr** [comment]
Verified that after git-sync upgrade to v3.4.0 it works as expected:

- [x] [Chart: Update git-sync to v3.4.0](https://github.com/apache/airflow/pull/21309)

**Comment by riccardo-salamanna** [comment]
Hi !
I tested the envFrom statement in the flower deployment
envFrom:
                                │
  - secretRef:
                                  │
      name: helm-test

and in the shell
***@***.***:/opt/airflow$ env | grep FRIENDS
FRIENDS=true

BR
Riccardo

**Comment by ephraimbuddy** [comment]
Thanks, everyone, 1.5.0 has been released
