### ISSUE TITLE
Migrate Amazon system tests to new design

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#22426]
There is a new design of system tests that was introduced by the [AIP-47](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-47+New+design+of+Airflow+System+Tests).

All current system tests need to be migrated, so they can be run in the CI process automatically before releases.

This is an aggregated issue for all system tests related to `Amazon` provider.

It is created to track progress of their migration.

List of paths to test files with corresponding number of tests inside:
- [x] tests/providers/amazon/aws/operators/test_ecs_system.py (1)
- [x] tests/providers/amazon/aws/operators/test_eks_system.py (4)
- [x] tests/providers/amazon/aws/operators/test_glacier_system.py (1)
- [x] tests/providers/amazon/aws/operators/test_s3_bucket_tagging_system.py (1)
- [x] tests/providers/amazon/aws/operators/test_emr_system.py (2)
- [x] tests/providers/amazon/aws/transfers/test_imap_attachment_to_s3_system.py (1)
- [x] tests/providers/amazon/aws/transfers/test_google_api_to_s3_system.py (2)
- [x] tests/providers/amazon/aws/transfers/test_s3_to_redshift_system.py (1)
- [x] tests/providers/amazon/aws/hooks/test_base_aws_system.py (1)

For anyone involved in working with this issue - please, make sure to also check if all example DAGs are migrated. The issue for them is stored separately. Search for `Migrate Amazon example DAGs to new design`
