### ISSUE TITLE
Migrate Docker example DAGs to new design

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#22444]
There is a new design of system tests that was introduced by the [AIP-47](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-47+New+design+of+Airflow+System+Tests).

All current example dags need to be migrated and converted into system tests, so they can be run in the CI process automatically before releases.

This is an aggregated issue for all example DAGs related to `Docker` provider. It is created to track progress of their migration.

List of paths to example DAGs:
- [x] airflow/providers/docker/example_dags/example_docker_swarm.py
- [x] airflow/providers/docker/example_dags/example_docker.py
- [x] airflow/providers/docker/example_dags/example_docker_copy_data.py

**Comment by Bowrna** [comment]
@potiuk Could I try this task?

**Comment by potiuk** [comment]
Sure :)

**Comment by Bowrna** [comment]
@potiuk There is an example tutorial in this example_dags folder for docker `airflow/providers/docker/example_dags/tutorial_taskflow_api_etl_docker_virtualenv.py` 
Do I have to migrate this example too?

**Comment by potiuk** [comment]
yeah.
