### ISSUE TITLE
Migrate Microsoft example DAGs to new design

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#22452]
There is a new design of system tests that was introduced by the [AIP-47](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-47+New+design+of+Airflow+System+Tests).

All current example dags need to be migrated and converted into system tests, so they can be run in the CI process automatically before releases.

This is an aggregated issue for all example DAGs related to `Microsoft` provider. It is created to track progress of their migration.

List of paths to example DAGs:
- [x] airflow/providers/microsoft/mssql/example_dags/example_mssql.py
- [x] airflow/providers/microsoft/azure/example_dags/example_azure_blob_to_gcs.py
- [x] airflow/providers/microsoft/azure/example_dags/example_azure_cosmosdb.py
- [x] airflow/providers/microsoft/azure/example_dags/example_fileshare.py
- [x] airflow/providers/microsoft/azure/example_dags/example_adls_delete.py
- [x] airflow/providers/microsoft/azure/example_dags/example_local_to_adls.py
- [x] airflow/providers/microsoft/azure/example_dags/example_azure_container_instances.py
- [x] airflow/providers/microsoft/azure/example_dags/example_local_to_wasb.py
- [x] airflow/providers/microsoft/azure/example_dags/example_sftp_to_wasb.py
- [x] airflow/providers/microsoft/azure/example_dags/example_adf_run_pipeline.py
- [x] airflow/providers/microsoft/winrm/example_dags/example_winrm.py

**Comment by chethanuk-plutoflume** [comment]
#24140

**Comment by chethanuk-plutoflume** [comment]
#24141
