### ISSUE TITLE
Rewrite Airflow CLI commands with Click

### ISSUE THREAD

**Issue by blag** [apache/airflow#22708]
Converting the Airflow CLI to use [Click](https://click.palletsprojects.com) and [rich-click](https://pypi.org/project/rich-click/) is a large task and will be much easier and quicker if other people pitch in.

I'm creating this issue to track volunteers and progress as we rewrite the Airflow CLI to use Click.

If you would like to help, you can do so by commenting below. I will try to update this list with the people who have volunteered to pitch in.

## Proposed Development Process ##

Once you drop a comment below, you can get to work converting a command. Please submit PRs against [my branch (`astronomer:convert-to-click-cli`)](https://github.com/astronomer/airflow/tree/convert-to-click-cli), that way we can review any changes separately from the apache/airflow review process and submit all of the conversions against `apache:airflow` in one go in PR #22613 (and I _think_ Git/GitHub will/should handle all of the attributions automatically).

I'd like to curtail the scope of this issue to just task management/assignments (and related issues). So if you run into an issue while coding, please drop your comment in #22613 and we can handle development issues there.

If you have any suggestions on how to improve this process, this would probably be a better place for it.

## Conversion Volunteers ##

* [x] celery - @hankehly
* [x] cheat_sheet - @hankehly
* [ ] config - @Bowrna
* [ ] connection - @Bowrna
* [ ] dag - @Bowrna
* [ ] dag_processor
* [x] db - @blag
* [x] info - @hankehly
* [x] jobs - @hankehly
* [ ] kerberos - @hankehly
* [ ] kubernetes - @hankehly
* [ ] legacy
* [ ] plugins - @hankehly
* [ ] pool - @hankehly
* [ ] provider
* [ ] role
* [ ] rotate_fernet_key
* [x] scheduler - @blag
* [x] standalone - @blag
* [x] sync_perm - @tirkarthi
* [ ] task
* [x] triggerer - @blag
* [ ] users - @blag
* [ ] variable - @Bowrna
* [x] version - @blag
* [x] webserver - @blag

### Committer

- [X] I acknowledge that I ~am a maintainer/committer of the Apache Airflow project~ have gotten permission from a maintainer/commiter of the Apache Airflow project to open this issue.

**Comment by tirkarthi** [comment]
sync-perm command PR : https://github.com/astronomer/airflow/pull/1485

**Comment by Bowrna** [comment]
I will choose `connection` first followed by `config`, `dag` in that order. will finish this first and pick up further :)

**Comment by hankehly** [comment]
@blag I will take `celery` and `cheat_sheet`

**Comment by Bowrna** [comment]
@blag I have picked up `variable` command too

**Comment by hankehly** [comment]
@blag I will take info and jobs

**Comment by hankehly** [comment]
@blag Hello, I'd like to continue contributing to this PR a few commands at a time. If someone could kindly take a look at / merge the PRs I submitted, I would gladly pick up another batch and continue working.

**Comment by blag** [comment]
Hey @hankehly, thank you for being so patient waiting for me to review and merge your PRs. I have merged all of your PRs that I'm aware of, please let me know if I've overlooked any. Thank you for your help so far, I really appreciate it!

**Comment by hankehly** [comment]
@blag Please assign the following to me
- kerberos
- kubernetes
- plugins
- pool

**Comment by blag** [comment]
From [this discussion](https://github.com/apache/airflow/pull/24591#pullrequestreview-1019268731), there is more groundwork and research necessary before we can evaluate rewriting the CLI with Click.
