### ISSUE TITLE
Status of testing Providers that were prepared on April 13, 2022

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#22983]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [databricks: 2.6.0rc2](https://pypi.org/project/apache-airflow-providers-databricks/2.6.0rc2)
   - [x] [More operators for Databricks Repos (#22422)](https://github.com/apache/airflow/pull/22422): @alexott
   - [x] [Add an UI link to Databricks Job Run (#22541)](https://github.com/apache/airflow/pull/22541): @alexott
   - [x] [Databricks SQL operators are now Python 3.10 compatible (#22886)](https://github.com/apache/airflow/pull/22886): @alexott
   - [x] [Correctly handle HTTP exception for Databricks Repos operations (#22885)](https://github.com/apache/airflow/pull/22885): @alexott
   - [x] [Refactor `DatabricksJobRunLink` to not create ad hoc TaskInstances (#22571)](https://github.com/apache/airflow/pull/22571): @josh-fell

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-by-contributors)

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by alexott** [comment]
I've retested all affected pieces, works correctly now

**Comment by potiuk** [comment]
Thanks @alexott !

**Comment by eladkal** [comment]
provider was released. closing issue
