### ISSUE TITLE
Status of testing Providers that were prepared on April 30, 2022

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#23375]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [cncf.kubernetes: 4.0.1rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/4.0.1rc1)
   - [x] [Add k8s container&#39;s error message in airflow exception (#22871)](https://github.com/apache/airflow/pull/22871): @karunpoudel
   - [ ] [KubernetesHook should try incluster first when not otherwise configured (#23126)](https://github.com/apache/airflow/pull/23126): @dstandish
   - [x] [KubernetesPodOperator should patch &#34;already checked&#34; always (#22734)](https://github.com/apache/airflow/pull/22734): @dstandish
   - [ ] [Delete old Spark Application in SparkKubernetesOperator (#21092)](https://github.com/apache/airflow/pull/21092): @theesen
   - [x] [Cleanup dup code now that k8s provider requires 2.3.0+ (#22845)](https://github.com/apache/airflow/pull/22845): @jedcunningham
   - [x] [Fix KubernetesPodOperator with KubernetesExecutor on 2.3.0 (#23371)](https://github.com/apache/airflow/pull/23371): @jedcunningham
   - [x] [Fix KPO to have hyphen instead of period (#22982)](https://github.com/apache/airflow/pull/22982): @dimon222
   - [x] [Fix new MyPy errors in main (#22884)](https://github.com/apache/airflow/pull/22884): @potiuk

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-by-contributors)

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by dimon222** [comment]
#22982 verified already - works

**Comment by jedcunningham** [comment]
Tested #23371 with KubernetesExecutor, CeleryExecutor, and `reattach_on_restart` True/False.
#22734 is also working.

**Comment by karunpoudel** [comment]
Verified #22871, it's working

**Comment by potiuk** [comment]
Cool. Thanks everyone. We just released it - earlier - to accompany 2.3.0 . Closing the issue :)
