### ISSUE TITLE
Status of testing of Apache Airflow Helm Chart 1.6.0rc2

### ISSUE THREAD

**Issue by jedcunningham** [apache/airflow#23599]
We have a kind request for all the contributors to the latest [Apache Airflow Helm Chart 1.6.0rc1](https://dist.apache.org/repos/dist/dev/airflow/helm-chart/1.6.0rc1).

Could you please help us to test the RC versions of Airflow?

Please let us know in the comment if the issue is addressed in the latest RC.

- [ ] [Add webserver PodDisruptionBudget (#21735)](https://github.com/apache/airflow/pull/21735): @mirobertod
- [ ] [Added support to override auth_type in auth_file in pgbouncer helm configuration (#21999)](https://github.com/apache/airflow/pull/21999): @freget @subkanthi
     Linked issues:
     - [Pgbouncer auth type cannot be configured (#19654)](https://github.com/apache/airflow/issues/19654)
- [ ] [Use jobs check command for liveness probe check in airflow 2 (#22143)](https://github.com/apache/airflow/pull/22143): @ephraimbuddy
- [ ] [Add securityContext config for Redis to helm chart (#22182)](https://github.com/apache/airflow/pull/22182): @dan-vaughan
- [ ] [allow migration jobs and init containers to be optional (#22195)](https://github.com/apache/airflow/pull/22195): @ajbosco
- [ ] [allow annotations on helm dag pvc (#22261)](https://github.com/apache/airflow/pull/22261): @ajbosco
- [ ] [Move the database configuration to a new section (#22284)](https://github.com/apache/airflow/pull/22284): @gitstart-airflow
- [ ] [enable optional subPath for dags volume mount (#22323)](https://github.com/apache/airflow/pull/22323): @ajbosco
- [ ] [Helm support local kubernetes executor (#22388)](https://github.com/apache/airflow/pull/22388): @subkanthi
- [ ] [Add `extraVolumeMounts` to flower (#22414)](https://github.com/apache/airflow/pull/22414): @jedcunningham
- [x] [Add support for topologySpreadConstraints to Helm Chart (#22712)](https://github.com/apache/airflow/pull/22712): @Swalloow
     Linked issues:
     - [Add support for topologySpreadConstraints to Helm Chart (#22652)](https://github.com/apache/airflow/issues/22652)
- [ ] [Chart: Update default airflow version to `2.3.0` (#23386)](https://github.com/apache/airflow/pull/23386): @ephraimbuddy
- [ ] [Support annotations on volumeClaimTemplates (#23433)](https://github.com/apache/airflow/pull/23433): @jedcunningham
- [ ] [Ensure the messages from migration job show up early (#23479)](https://github.com/apache/airflow/pull/23479): @ashb
- [ ] [Disable flower in chart by default (#23737)](https://github.com/apache/airflow/pull/23737): @jedcunningham

Thanks to all who contributed to the release (probably not a complete list!):
@ephraimbuddy @dan-vaughan @ajbosco @subkanthi @gitstart-airflow @mirobertod @ashb @potiuk @freget @jedcunningham @Swalloow

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by Swalloow** [comment]
Verified https://github.com/apache/airflow/pull/22712, it's working

**Comment by jedcunningham** [comment]
Helm Chart version 1.6.0 has been released. Thanks @Swalloow for testing your change 🎉
