### ISSUE TITLE
Add missing parameter documentation for `KubernetesHook` and `KubernetesPodOperator`

### ISSUE THREAD

**Issue by josh-fell** [apache/airflow#23955]
### Body

Currently the following modules are missing certain parameters in their docstrings. Because of this, these parameters are not captured in the [Python API docs for the Kubernetes provider](https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/_api/airflow/providers/cncf/kubernetes/index.html).

- [ ] KubernetesHook: `in_cluster`, `config_file`, `cluster_context`, `client_configuration`
- [ ] KubernetesPodOperator: `env_from`, `node_selectors`, `pod_runtime_info_envs`, `configmaps`

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by mariasumedre-3pg** [comment]
Hello! Can I pick this up?

**Comment by potiuk** [comment]
Sure
