### ISSUE TITLE
Status of testing of Apache Airflow 2.3.2rc1

### ISSUE THREAD

**Issue by ephraimbuddy** [apache/airflow#24024]
### Body

We have a kind request for all the contributors to the latest [Apache Airflow RC 2.3.2rc1](https://pypi.org/project/apache-airflow/2.3.2rc1/).

Could you please help us to test the RC versions of Airflow?

Please let us know in the comment if the issue is addressed in the latest RC.

- [ ] [Add is_mapped field to Task response. (#23319)](https://github.com/apache/airflow/pull/23319): @bbovenzi @tirkarthi
     Linked issues:
     - [Get DAG tasks in REST API does not include is_mapped (#23284)](https://github.com/apache/airflow/issues/23284)
- [ ] [Add cascade to `dag_tag` to `dag` foreignkey (#23444)](https://github.com/apache/airflow/pull/23444): @jrggggg @MatrixManAtYrService @ephraimbuddy
     Linked issues:
     - [UI shows Foreign Key Error when deleting a dag (#23206)](https://github.com/apache/airflow/issues/23206)
     - [airflow db clean - Dag cleanup won't run if dag is tagged (#23414)](https://github.com/apache/airflow/issues/23414)
- [ ] [Disallow calling expand with no arguments (#23463)](https://github.com/apache/airflow/pull/23463): @uranusjr @jedcunningham
     Linked issues:
     - [Empty `expand()` crashes the scheduler (#23435)](https://github.com/apache/airflow/issues/23435)
- [ ] [Exclude missing tasks from the gantt view (#23627)](https://github.com/apache/airflow/pull/23627): @joelossher
     Linked issues:
     - [Gantt Chart Broken After Deleting a Task (#23546)](https://github.com/apache/airflow/issues/23546)
- [ ] [Simplify flash message for _airflow_moved tables (#23635)](https://github.com/apache/airflow/pull/23635): @dstandish
- [ ] [Highlight task states by hovering on legend row (#23678)](https://github.com/apache/airflow/pull/23678): @pierrejeambrun
- [x] [Enable clicking on DAG owner in autocomplete dropdown (#23804)](https://github.com/apache/airflow/pull/23804): @ecodina @norm
     Linked issues:
     - [Airflow 2.3.0: can't filter by owner if selected from dropdown (#23670)](https://github.com/apache/airflow/issues/23670)
- [ ] [Mask sensitive values for not-yet-running TIs (#23807)](https://github.com/apache/airflow/pull/23807): @dstandish
- [x] [Fix UnboundLocalError when sql is empty list in DbApiHook (#23816)](https://github.com/apache/airflow/pull/23816): @kazanzhy
- [ ] [Add __wrapped__ property to _TaskDecorator (#23830)](https://github.com/apache/airflow/pull/23830): @snjypl
- [x] [Use '--subdir' argument value for standalone dag processor. (#23864)](https://github.com/apache/airflow/pull/23864): @mhenc
- [x] [DagFileProcessorManager: Start a new process group only if current process not a session leader (#23872)](https://github.com/apache/airflow/pull/23872): @Taragolis
     Linked issues:
     - [`dag-processor` failed to start in docker (#23871)](https://github.com/apache/airflow/issues/23871)
- [x] [Remove redundant register exit signals in `dag-processor` command (#23886)](https://github.com/apache/airflow/pull/23886): @Taragolis
- [ ] [Prevent UI from crashing if grid task instances are null (#23939)](https://github.com/apache/airflow/pull/23939): @bbovenzi
- [ ] [Fix and speed up grid view (#23947)](https://github.com/apache/airflow/pull/23947): @jedcunningham
- [ ] [Faster grid view (#23951)](https://github.com/apache/airflow/pull/23951): @jedcunningham
- [ ] [[23945] Icons in grid view for different dag types (#23970)](https://github.com/apache/airflow/pull/23970): @bbovenzi @dskoda1
     Linked issues:
     - [Add backfill icon to grid view dag runs (#23945)](https://github.com/apache/airflow/issues/23945)
- [x] [Remove pinning for xmltodict (#23992)](https://github.com/apache/airflow/pull/23992): @potiuk
     Linked issues:
     - [The xmltodict 0.13.0 breaks some emr tests (#23576)](https://github.com/apache/airflow/issues/23576)

Thanks to all who contributed to the release (probably not a complete list!):
@jrggggg @mhenc @kazanzhy @ecodina @joelossher @pierrejeambrun @dstandish @snjypl @Taragolis @uranusjr @ephraimbuddy @potiuk @jedcunningham @tirkarthi @MatrixManAtYrService @bbovenzi @norm @dskoda1

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by Taragolis** [comment]
Check in 4 different production images
- `apache/airflow:2.3.2rc1-python3.7`
- `apache/airflow:2.3.2rc1-python3.8`
- `apache/airflow:2.3.2rc1-python3.9`
- `apache/airflow:2.3.2rc1-python3.10`

#23872: Production image successfully starts with standalone dag-processor
#23886: No side effects during previous checks
#23864: Also check this one with two separate standalone dag processors with different --subdirs (first explicit set, another set by `AIRFLOW__CORE__DAGS_FOLDER`), working good.

**Comment by kazanzhy** [comment]
https://github.com/apache/airflow/pull/23816 seems OK

**Comment by potiuk** [comment]
Confirmed #23992 (limitation removed).
