### ISSUE TITLE
Status of testing Providers that were prepared on June 07, 2022

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#24289]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [alibaba: 2.0.0rc2](https://pypi.org/project/apache-airflow-providers-alibaba/2.0.0rc2)
- [x] [SSL Bucket, Light Logic Refactor and Docstring Update for Alibaba Provider (#23891)](https://github.com/apache/airflow/pull/23891): @koconder
- [ ] [Apply per-run log templates to log handlers (#24153)](https://github.com/apache/airflow/pull/24153): @uranusjr
## Provider [amazon: 4.0.0rc2](https://pypi.org/project/apache-airflow-providers-amazon/4.0.0rc2)
- [x] [Create `get_partition` and `create_partition` methods in `GlueCatalogHook`  (#23857)](https://github.com/apache/airflow/pull/23857): @gmcrocetti
- [ ] [Add support for associating  custom tags to job runs submitted via EmrContainerOperator (#23769)](https://github.com/apache/airflow/pull/23769): @skadyan
- [x] [Fix ``RedshiftCreateClusterOperator``  for single-node cluster type (#23839)](https://github.com/apache/airflow/pull/23839): @pankajastro
- [x] [fix: StepFunctionHook ignores explicit set `region_name` (#23976)](https://github.com/apache/airflow/pull/23976): @Taragolis
- [x] [Fix Amazon EKS example DAG raises warning during Imports (#23849)](https://github.com/apache/airflow/pull/23849): @Dark-Knight11
- [x] [Move string arg evals to `execute()` in `EksCreateClusterOperator` (#23877)](https://github.com/apache/airflow/pull/23877): @josh-fell
- [ ] [Fix: AwsGlueJobOperator - patches #24215 (#24308)](https://github.com/apache/airflow/pull/24308): @gmcrocetti
- [x] [Light Refactor and Clean-up AWS Provider (#23907)](https://github.com/apache/airflow/pull/23907): @koconder
- [x] [Update sample dag and doc for RDS (#23651)](https://github.com/apache/airflow/pull/23651): @vincbeck
- [x] [Reformat the whole AWS documentation (#23810)](https://github.com/apache/airflow/pull/23810): @vincbeck
- [x] [Replace &#34;absolute()&#34; with &#34;resolve()&#34; in pathlib objects (#23675)](https://github.com/apache/airflow/pull/23675): @potiuk
- [ ] [Apply per-run log templates to log handlers (#24153)](https://github.com/apache/airflow/pull/24153): @uranusjr
- [ ] [Refactor GlueJobHook `get_or_create_glue_job` method. (#24215)](https://github.com/apache/airflow/pull/24215): @gmcrocetti
- [ ] [Update the DMS Sample DAG and Docs (#23681)](https://github.com/apache/airflow/pull/23681): @ferruzzi
- [x] [Update doc and sample dag for Quicksight (#23653)](https://github.com/apache/airflow/pull/23653): @vincbeck
- [x] [Update doc and sample dag for EMR Containers (#24087)](https://github.com/apache/airflow/pull/24087): @vincbeck
- [x] [Add AWS project structure tests (re: AIP-47) (#23630)](https://github.com/apache/airflow/pull/23630): @o-nikolas
- [x] [Add doc and sample dag for GCSToS3Operator (#23730)](https://github.com/apache/airflow/pull/23730): @vincbeck
- [ ] [Remove old Athena Sample DAG (#24170)](https://github.com/apache/airflow/pull/24170): @ferruzzi
- [x] [Clean up f-strings in logging calls (#23597)](https://github.com/apache/airflow/pull/23597): @josh-fell
## Provider [apache.beam: 4.0.0rc2](https://pypi.org/project/apache-airflow-providers-apache-beam/4.0.0rc2)
- [ ] [Added missing project_id to the wait_for_job (#24020)](https://github.com/apache/airflow/pull/24020): @lwyszomi
- [ ] [Support impersonation service account parameter for Dataflow runner (#23961)](https://github.com/apache/airflow/pull/23961): @lwyszomi
- [x] [chore: Refactoring and Cleaning Apache Providers (#24219)](https://github.com/apache/airflow/pull/24219): @koconder
## Provider [apache.cassandra: 3.0.0rc2](https://pypi.org/project/apache-airflow-providers-apache-cassandra/3.0.0rc2)
- [x] [chore: Refactoring and Cleaning Apache Providers (#24219)](https://github.com/apache/airflow/pull/24219): @koconder
## Provider [apache.druid: 3.0.0rc2](https://pypi.org/project/apache-airflow-providers-apache-druid/3.0.0rc2)
- [x] [chore: Refactoring and Cleaning Apache Providers (#24219)](https://github.com/apache/airflow/pull/24219): @koconder
## Provider [apache.hdfs: 3.0.0rc2](https://pypi.org/project/apache-airflow-providers-apache-hdfs/3.0.0rc2)
- [x] [chore: Refactoring and Cleaning Apache Providers (#24219)](https://github.com/apache/airflow/pull/24219): @koconder
## Provider [apache.hive: 3.0.0rc2](https://pypi.org/project/apache-airflow-providers-apache-hive/3.0.0rc2)
- [x] [chore: Refactoring and Cleaning Apache Providers (#24219)](https://github.com/apache/airflow/pull/24219): @koconder
- [ ] [AIP-47 - Migrate hive DAGs to new design #22439 (#24204)](https://github.com/apache/airflow/pull/24204): @chethanuk-plutoflume
## Provider [apache.kylin: 3.0.0rc2](https://pypi.org/project/apache-airflow-providers-apache-kylin/3.0.0rc2)
- [ ] [AIP-47 - Migrate kylin DAGs to new design #22439 (#24205)](https://github.com/apache/airflow/pull/24205): @chethanuk-plutoflume
- [x] [chore: Refactoring and Cleaning Apache Providers (#24219)](https://github.com/apache/airflow/pull/24219): @koconder
## Provider [apache.pinot: 3.0.0rc2](https://pypi.org/project/apache-airflow-providers-apache-pinot/3.0.0rc2)
- [x] [chore: Refactoring and Cleaning Apache Providers (#24219)](https://github.com/apache/airflow/pull/24219): @koconder
## Provider [apache.spark: 3.0.0rc2](https://pypi.org/project/apache-airflow-providers-apache-spark/3.0.0rc2)
- [x] [Add typing for airflow/configuration.py (#23716)](https://github.com/apache/airflow/pull/23716): @potiuk
- [x] [Fix backwards-compatibility introduced by fixing mypy problems (#24230)](https://github.com/apache/airflow/pull/24230): @potiuk
- [ ] [AIP-47 - Migrate spark DAGs to new design #22439 (#24210)](https://github.com/apache/airflow/pull/24210): @chethanuk-plutoflume
- [x] [chore: Refactoring and Cleaning Apache Providers (#24219)](https://github.com/apache/airflow/pull/24219): @koconder
## Provider [cncf.kubernetes: 4.1.0rc2](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/4.1.0rc2)
- [ ] [Use KubernetesHook to create api client in KubernetesPodOperator (#20578)](https://github.com/apache/airflow/pull/20578): @dstandish
- [ ] [[FEATURE] KPO add optional K8S hook (#22086)](https://github.com/apache/airflow/pull/22086): @raphaelauv
- [ ] [Add param docs to KubernetesHook and KubernetesPodOperator (#23955) (#24054)](https://github.com/apache/airflow/pull/24054): @mariasumedre-3pg
- [ ] [Use &#34;remote&#34; pod when patching KPO pod as &#34;checked&#34; (#23676)](https://github.com/apache/airflow/pull/23676): @dstandish
- [ ] [Don&#39;t use the root logger in KPO _suppress function (#23835)](https://github.com/apache/airflow/pull/23835): @dstandish
- [ ] [Fix KubernetesPodOperator await_container_completion condition (#23883)](https://github.com/apache/airflow/pull/23883): @akakakakakaa
- [ ] [Migrate Cncf.Kubernetes example DAGs to new design #22441 (#24132)](https://github.com/apache/airflow/pull/24132): @chethanuk-plutoflume
- [x] [Clean up f-strings in logging calls (#23597)](https://github.com/apache/airflow/pull/23597): @josh-fell
## Provider [databricks: 3.0.0rc2](https://pypi.org/project/apache-airflow-providers-databricks/3.0.0rc2)
- [x] [Add Databricks Deferrable Operators (#19736)](https://github.com/apache/airflow/pull/19736): @eskarimov
- [ ] [Add git_source to DatabricksSubmitRunOperator (#23620)](https://github.com/apache/airflow/pull/23620): @akolar-db
- [x] [fix: DatabricksSubmitRunOperator and DatabricksRunNowOperator cannot define .json as template_ext (#23622) (#23641)](https://github.com/apache/airflow/pull/23641): @jonathansp
- [ ] [Fix UnboundLocalError when sql is empty list in DatabricksSqlHook (#23815)](https://github.com/apache/airflow/pull/23815): @kazanzhy
## Provider [dbt.cloud: 2.0.0rc2](https://pypi.org/project/apache-airflow-providers-dbt-cloud/2.0.0rc2)
- [ ] [Enable dbt Cloud provider to interact with single tenant instances (#24264)](https://github.com/apache/airflow/pull/24264): @epapineau
- [x] [Fix typo in dbt Cloud provider description (#23179)](https://github.com/apache/airflow/pull/23179): @josh-fell
- [x] [Fix new MyPy errors in main (#22884)](https://github.com/apache/airflow/pull/22884): @potiuk
## Provider [docker: 3.0.0rc2](https://pypi.org/project/apache-airflow-providers-docker/3.0.0rc2)
- [x] [Remove `xcom_push` from `DockerOperator` (#23981)](https://github.com/apache/airflow/pull/23981): @eladkal
- [x] [Migrate Docker example DAGs to new design  (#23167)](https://github.com/apache/airflow/pull/23167): @Bowrna
## Provider [elasticsearch: 4.0.0rc2](https://pypi.org/project/apache-airflow-providers-elasticsearch/4.0.0rc2)
- [ ] [Apply per-run log templates to log handlers (#24153)](https://github.com/apache/airflow/pull/24153): @uranusjr
## Provider [exasol: 3.0.0rc2](https://pypi.org/project/apache-airflow-providers-exasol/3.0.0rc2)
- [ ] [Fix UnboundLocalError when sql is empty list in ExasolHook (#23812)](https://github.com/apache/airflow/pull/23812): @kazanzhy
## Provider [github: 2.0.0rc2](https://pypi.org/project/apache-airflow-providers-github/2.0.0rc2)
- [x] [Remove `GithubOperator` use in  `GithubSensor.__init__()` (#24214)](https://github.com/apache/airflow/pull/24214): @josh-fell
## Provider [google: 8.0.0rc2](https://pypi.org/project/apache-airflow-providers-google/8.0.0rc2)
- [ ] [Add key_secret_project_id parameter which specifies a project with KeyFile (#23930)](https://github.com/apache/airflow/pull/23930): @MaksYermak
- [ ] [Added impersonation_chain for dataflow operators (#24046)](https://github.com/apache/airflow/pull/24046): @lwyszomi
- [x] [Add fields to CLOUD_SQL_EXPORT_VALIDATION. (#23724)](https://github.com/apache/airflow/pull/23724): @ishiis
- [ ] [Update credentials when using ADC in Compute Engine (#23773)](https://github.com/apache/airflow/pull/23773): @MaksYermak
- [x] [set color to operators in cloud_sql.py (#24000)](https://github.com/apache/airflow/pull/24000): @ishiis
- [ ] [Sql to gcs with exclude columns (#23695)](https://github.com/apache/airflow/pull/23695): @jaegwonseo
- [ ] [[Issue#22846] allow option to encode or not encode UUID when uploading from Cassandra to GCS (#23766)](https://github.com/apache/airflow/pull/23766): @fuxiao224
- [ ] [Workflows assets &amp; system tests migration (AIP-47) (#24105)](https://github.com/apache/airflow/pull/24105): @wojsamjan
- [ ] [Spanner assets &amp; system tests migration (AIP-47) (#23957)](https://github.com/apache/airflow/pull/23957): @wojsamjan
- [ ] [Speech To Text assets &amp; system tests migration (AIP-47) (#23643)](https://github.com/apache/airflow/pull/23643): @wojsamjan
- [ ] [Cloud SQL assets &amp; system tests migration (AIP-47) (#23583)](https://github.com/apache/airflow/pull/23583): @wojsamjan
- [ ] [Cloud Storage assets &amp; StorageLink update (#23865)](https://github.com/apache/airflow/pull/23865): @wojsamjan
- [x] [fix BigQueryInsertJobOperator (#24165)](https://github.com/apache/airflow/pull/24165): @raphaelauv
- [ ] [Fix the link to google workplace (#24080)](https://github.com/apache/airflow/pull/24080): @francois2metz
- [ ] [Fix DataprocJobBaseOperator not compatible with TaskGroups (#23791)](https://github.com/apache/airflow/pull/23791): @gmcrocetti
- [ ] [Remove hack from BigQuery DTS hook (#23887)](https://github.com/apache/airflow/pull/23887): @henriqueribeiro
- [ ] [Fix GCSToGCSOperator cannot copy a single file/folder without copying other files/folders with that prefix (#24039)](https://github.com/apache/airflow/pull/24039): @gitstart-airflow
- [ ] [Workaround job race bug on biguery to gcs transfer (#24330)](https://github.com/apache/airflow/pull/24330): @potiuk
- [ ] [Fix BigQuery system tests (#24013)](https://github.com/apache/airflow/pull/24013): @bhirsz
- [ ] [Ensure @contextmanager decorates generator func (#23103)](https://github.com/apache/airflow/pull/23103): @uranusjr
- [ ] [Migrate Dataproc to new system tests design (#22777)](https://github.com/apache/airflow/pull/22777): @bhirsz
- [ ] [AIP-47 - Migrate google leveldb DAGs to new design ##22447 (#24233)](https://github.com/apache/airflow/pull/24233): @chethanuk-plutoflume
- [ ] [Apply per-run log templates to log handlers (#24153)](https://github.com/apache/airflow/pull/24153): @uranusjr
## Provider [hashicorp: 3.0.0rc2](https://pypi.org/project/apache-airflow-providers-hashicorp/3.0.0rc2)
- [x] [Add explanatory note for contributors about updating Changelog (#24229)](https://github.com/apache/airflow/pull/24229): @potiuk
- [x] [Prepare provider documentation 2022.05.11 (#23631)](https://github.com/apache/airflow/pull/23631): @potiuk
- [ ] [pydocstyle D202 added (#24221)](https://github.com/apache/airflow/pull/24221): @Bowrna
- [x] [Prepare docs for May 2022 provider&#39;s release (#24231)](https://github.com/apache/airflow/pull/24231): @potiuk
## Provider [jdbc: 3.0.0rc2](https://pypi.org/project/apache-airflow-providers-jdbc/3.0.0rc2)
- [ ] [Handler parameter from JdbcOperator to JdbcHook.run (#23817)](https://github.com/apache/airflow/pull/23817): @kazanzhy
## Provider [jenkins: 3.0.0rc2](https://pypi.org/project/apache-airflow-providers-jenkins/3.0.0rc2)
- [x] [Bug Fix for `apache-airflow-providers-jenkins` `JenkinsJobTriggerOperator` (#22802)](https://github.com/apache/airflow/pull/22802): @SasanAhmadi
## Provider [microsoft.azure: 4.0.0rc2](https://pypi.org/project/apache-airflow-providers-microsoft-azure/4.0.0rc2)
- [ ] [Pass connection extra parameters to wasb BlobServiceClient (#24154)](https://github.com/apache/airflow/pull/24154): @tanelk
- [ ] [Apply per-run log templates to log handlers (#24153)](https://github.com/apache/airflow/pull/24153): @uranusjr
- [ ] [Migrate Microsoft example DAGs to new design #22452 - azure (#24141)](https://github.com/apache/airflow/pull/24141): @chethanuk-plutoflume
- [x] [Add typing to Azure Cosmos Client Hook (#23941)](https://github.com/apache/airflow/pull/23941): @potiuk
## Provider [oracle: 3.0.0rc2](https://pypi.org/project/apache-airflow-providers-oracle/3.0.0rc2)
- [ ] [Add `parameters` to templated fields in `OracleOperator` (#22857)](https://github.com/apache/airflow/pull/22857): @malthe
- [x] [Make numpy effectively an optional dependency for Oracle provider (#24272)](https://github.com/apache/airflow/pull/24272): @potiuk
## Provider [papermill: 3.0.0rc2](https://pypi.org/project/apache-airflow-providers-papermill/3.0.0rc2)
- [x] [Add support to specify language name in PapermillOperator (#23916)](https://github.com/apache/airflow/pull/23916): @nhojjohn
- [x] [Fix langauge override in papermill operator (#24301)](https://github.com/apache/airflow/pull/24301): @nhojjohn
## Provider [presto: 3.0.0rc2](https://pypi.org/project/apache-airflow-providers-presto/3.0.0rc2)
- [ ] [Add `PrestoToSlackOperator` (#23979)](https://github.com/apache/airflow/pull/23979): @eladkal
## Provider [qubole: 3.0.0rc2](https://pypi.org/project/apache-airflow-providers-qubole/3.0.0rc2)
- [x] [Add typing for airflow/configuration.py (#23716)](https://github.com/apache/airflow/pull/23716): @potiuk
- [x] [Fix backwards-compatibility introduced by fixing mypy problems (#24230)](https://github.com/apache/airflow/pull/24230): @potiuk
## Provider [sftp: 3.0.0rc2](https://pypi.org/project/apache-airflow-providers-sftp/3.0.0rc2)
- [x] [Adding fnmatch type regex to SFTPSensor (#24084)](https://github.com/apache/airflow/pull/24084): @alexkruc
## Provider [snowflake: 3.0.0rc2](https://pypi.org/project/apache-airflow-providers-snowflake/3.0.0rc2)
- [x] [Fix error when SnowflakeHook take empty list in `sql` param (#23767)](https://github.com/apache/airflow/pull/23767): @kazanzhy
## Provider [sqlite: 3.0.0rc2](https://pypi.org/project/apache-airflow-providers-sqlite/3.0.0rc2)
- [ ] [Fix ``SqliteHook`` compatibility with SQLAlchemy engine (#23790)](https://github.com/apache/airflow/pull/23790): @kaxil
## Provider [ssh: 3.0.0rc2](https://pypi.org/project/apache-airflow-providers-ssh/3.0.0rc2)
- [x] [Add disabled_algorithms as an extra parameter for SSH connections (#24090)](https://github.com/apache/airflow/pull/24090): @pauldalewilliams
- [x] [fixing SSHHook bug when using allow_host_key_change param (#24116)](https://github.com/apache/airflow/pull/24116): @alexkruc

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-by-contributors)

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by vincbeck** [comment]
All my changes are related to doc and/or sample dag. No testing needed

**Comment by potiuk** [comment]
Cool. Bulk-updated them as "tested" :D

**Comment by raphaelauv** [comment]
https://github.com/apache/airflow/pull/23981 work

**Comment by potiuk** [comment]
I also tested and updated all "my" changes

**Comment by potiuk** [comment]
One comment. I am releasing rc2 in a moment (@josh-fell found that our RELEASE notes (part of packages) contained Airflow 2.1+ so I am re-relesing all providers with that one change included (but feel free to continue the testing - the only difference will be those descriptions.

**Comment by ishiis** [comment]
#23724 #24000 is tested.

**Comment by Dark-Knight11** [comment]
#23849 contains only refactoring of code. No testing needed

**Comment by jonathansp** [comment]
I've tested #23622 and it works as expected.

**Comment by gilangardya** [comment]
I've tested #24165 (google, BigQueryInsertJobOperator) with `composer-2.0.15-airflow-2.2.5`, it works as expected.
These are the tests I did:

Job type | Statement | Details | 7.0.0 | 2022.5.18+composer | 8.0.0rc1
-- | -- | -- | -- | -- | --
COPY | N/A | Copy BigQuery Table | :x: | :x: | :white_check_mark:
EXTRACT | N/A | To CSV | :x: | :x: | :white_check_mark:
LOAD | N/A | From CSV | :x: | :x: | :white_check_mark:
QUERY | N/A | SELECT query | :white_check_mark: | :white_check_mark: | :white_check_mark:
QUERY | N/A | WRITE_TRUNCATE with partitioned table | :white_check_mark: | :white_check_mark: | :white_check_mark:
QUERY | DDL | CREATE TABLE AS SELECT | :white_check_mark: | :white_check_mark: | :white_check_mark:
QUERY | DML | INSERT | :white_check_mark: | :white_check_mark: | :white_check_mark:
QUERY | DML | MERGE | :white_check_mark: | :white_check_mark: | :white_check_mark:
QUERY | DCL | GRANT | :x: | :x: | :white_check_mark:
QUERY | Procedural | DECLARE | :x: | :x: | :white_check_mark:
QUERY | Debugging | ASSERT | :x: | :x: | :white_check_mark:
QUERY | Other | EXPORT DATA | :x: | :x: | :white_check_mark:
QUERY | Multi-statement | DECLARE + INSERT + MERGE | :x: | :x: | :white_check_mark:

**Comment by nhojjohn** [comment]
I checked https://github.com/apache/airflow/pull/23916 and noticed an problem with it.  Feel free to revert it or consider the following PR which fixes the issue https://github.com/apache/airflow/pull/24301

**Comment by SasanAhmadi** [comment]
I've tested [#22802](https://github.com/apache/airflow/pull/22802) and it is working as expected.

**Comment by potiuk** [comment]
> I checked #23916 and noticed an problem with it. Feel free to revert it or consider the following PR which fixes the issue #24301

Cool. I will look to it - I am going release rc2 so I will merge it before.

**Comment by potiuk** [comment]
> @potiuk do you know why k8s is a major?

As discussed on slack - mistake :). Will release minor as rc2.

**Comment by gmcrocetti** [comment]
1. https://github.com/apache/airflow/pull/23857 works;
2. https://github.com/apache/airflow/pull/24215 is broken but there's a patch fixing it: https://github.com/apache/airflow/pull/24308;
3. https://github.com/apache/airflow/pull/23791 I'm currently **unable** to test it. @eladkal, as the author would you be willing to test it ?

**Comment by alexkruc** [comment]
Verified the installation and that everything exists properly for my fixes:
* https://github.com/apache/airflow/pull/24084
* https://github.com/apache/airflow/pull/24116:

**Comment by potiuk** [comment]
Thanks @gmcrocetti - as I am releasing rc2 soon, I merged your fix :)

**Comment by kazanzhy** [comment]
https://github.com/apache/airflow/pull/23767 working as expected

**Comment by eskarimov** [comment]
Tested #19736 by executing `DatabricksRunNowDeferrableOperator` and `DatabricksSubmitRunDeferrableOperator`, both work as expected.

**Comment by o-nikolas** [comment]
My changes are testing related and not part of provider code shipped to customers. Though I verified those tests are still passing :+1:

**Comment by potiuk** [comment]
I  re-released the RC2 after few fixes (thanks to those who noticed them) and also corrected a number of documentation issues (that turned to be a bit more complex due to AIP-47 induced changes) - thanks @josh-fell and @deeptansh for raising the issues.

Announcement is about to be sent to the devlist. There is no real need to re-test the already tested changes (I left them checked) as the changes were minimal when it comes to code.

But the not-checked issues also need some ❤️  :).

Summary of changes in RC2:

* @dstandish - the "cncf.kubernetes' is now 4.1.0 not 5.0.0 (my mistake)
* @nhojjohn - your fix #24301 should be included in RC2 - worth double checking
* @deeptansh - the links to example dags in the docs should now be stable and correct
* A number of "system tests" (google and dbt) were moved while automating doc links - they were both missing "cloud" subdir (wich is needed for consistency
* Amazon and Google which are in progress with AIP-47 have two links (examples + legacy)
* I workarounded (proper fix will come)  a Google provider BigQuery extract job failure 

Have fun with testing (we release on Monday if all is good).

**Comment by josh-fell** [comment]
All of mine are 👍

**Comment by nhojjohn** [comment]
tested https://github.com/apache/airflow/pull/24301 on rc2 and works now.  Thanks!

**Comment by potiuk** [comment]
Looking forward for more testing till Monday :).

**Comment by koconder** [comment]
Tests looking good
