### ISSUE TITLE
Status of testing Providers that were prepared on June 15, 2022

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#24471]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [google: 8.1.0rc1](https://pypi.org/project/apache-airflow-providers-google/8.1.0rc1)
   - [x] [Update Oracle library to latest version (#24311)](https://github.com/apache/airflow/pull/24311): @lmeerwood
   - [x] [Expose SQL to GCS Metadata (#24382)](https://github.com/apache/airflow/pull/24382): @patricker
   - [x] [fix typo in google provider additional extras (#24431)](https://github.com/apache/airflow/pull/24431): @Taragolis
   - [x] [Use insert_job in the BigQueryToGCPOpertor and adjust links (#24416)](https://github.com/apache/airflow/pull/24416): @lwyszomi
## Provider [oracle: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-oracle/3.1.0rc1)
   - [x] [Update Oracle library to latest version (#24311)](https://github.com/apache/airflow/pull/24311): @lmeerwood

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-by-contributors)

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
cc: @lihan

**Comment by Taragolis** [comment]
https://github.com/apache/airflow/pull/24431 work as expected

```
❯ pip install "apache-airflow-providers-google[amazon,facebook]==8.1.0rc1"
Collecting apache-airflow-providers-google[amazon,facebook]==8.1.0rc1
...
Successfully installed Babel-2.10.2 Flask-Babel-2.0.0, ...

❯ pip list | grep airflow-providers
apache-airflow-providers-amazon    4.0.0
apache-airflow-providers-facebook  3.0.0
apache-airflow-providers-ftp       3.0.0
apache-airflow-providers-google    8.1.0rc1
apache-airflow-providers-http      3.0.0
apache-airflow-providers-imap      3.0.0
apache-airflow-providers-sqlite    3.0.0
```

**Comment by potiuk** [comment]
More testing if possible before tomorrow :)

**Comment by lmeerwood** [comment]
Hey @potiuk, Oracle seems to be working fine for me. I am able to perform almost all queries to my database just fine.

It's hard for me to give a valid test though as a) I'm currently in the middle of impletementing Airflow for my workspace and b) I don't have a google database so I can't test the oracle to google transfer.

**Comment by lwyszomi** [comment]
#24416 works as expected

**Comment by patricker** [comment]
#24382 works as expected (sorry for the delay!)

**Comment by potiuk** [comment]
Cool. About to release it... so .. just in time...
