### ISSUE TITLE
Status of testing of Apache Airflow 2.3.3rc1

### ISSUE THREAD

**Issue by ephraimbuddy** [apache/airflow#24806]
### Body

We have a kind request for all the contributors to the latest [Apache Airflow RC 2.3.3rc1](https://pypi.org/project/apache-airflow/2.3.3rc1/).

Could you please help us to test the RC versions of Airflow?

Please let us know in the comment if the issue is addressed in the latest RC.

- [ ] [Switch Markdown engine to markdown-it-py (#19702)](https://github.com/apache/airflow/pull/19702): @uranusjr @torbjornvatn
     Linked issues:
     - [Switch Markdown engine to markdown-it-py (#16435)](https://github.com/apache/airflow/issues/16435)
- [ ] [Parse error for task added to multiple groups (#23071)](https://github.com/apache/airflow/pull/23071): @wolfier @uranusjr
     Linked issues:
     - [Using TaskGroup without context manager (Graph view visual bug) (#14864)](https://github.com/apache/airflow/issues/14864)
- [ ] [Check bag DAG schedule_interval match tiemtable (#23113)](https://github.com/apache/airflow/pull/23113): @sdebruyn @uranusjr
     Linked issues:
     - [Show DAG parse error if 'timetable' and 'schedule_interval' are set together (#23087)](https://github.com/apache/airflow/issues/23087)
- [x] [Allow for LOGGING_LEVEL=DEBUG (#23360)](https://github.com/apache/airflow/pull/23360): @GApfel
- [ ] [Fix closing connection dbapi.get_pandas_df (#23452)](https://github.com/apache/airflow/pull/23452): @hubert-pietron @bauerfranz
     Linked issues:
     - [closing connection chunks in  DbApiHook.get_pandas_df (#22947)](https://github.com/apache/airflow/issues/22947)
- [ ] [Fix permission issue for dag that has dot in name (#23510)](https://github.com/apache/airflow/pull/23510): @ephraimbuddy
- [ ] [Fix mapped task immutability after clear (#23667)](https://github.com/apache/airflow/pull/23667): @ephraimbuddy
- [x] [Maintain grid view selection on filtering upstream (#23779)](https://github.com/apache/airflow/pull/23779): @bbovenzi
- [ ] [Add TaskInstance State 'REMOVED' to finished states and success states (#23797)](https://github.com/apache/airflow/pull/23797): @ephraimbuddy
- [ ] [Do not fail requeued TIs (#23846)](https://github.com/apache/airflow/pull/23846): @tanelk @malthe
     Linked issues:
     - [Race condition between Triggerer and Scheduler (#23824)](https://github.com/apache/airflow/issues/23824)
     - [Fix race condition between triggerer and scheduler (#21316)](https://github.com/apache/airflow/pull/21316)
- [ ] [Grid fix details button truncated and small UI tweaks (#23934)](https://github.com/apache/airflow/pull/23934): @pierrejeambrun
- [ ] [Replace `use_task_execution_date` with `use_task_logical_date` (#23983)](https://github.com/apache/airflow/pull/23983): @eladkal
- [ ] [Removing magic numbers from api_connecxion (#24050)](https://github.com/apache/airflow/pull/24050): @bernardocouto
- [ ] [Rename Permissions to Permission Pairs. (#24065)](https://github.com/apache/airflow/pull/24065): @jhtimmins @zachliu @gbonazzoli
     Linked issues:
     - [Random "duplicate key value violates unique constraint" errors when initializing the postgres database (#23512)](https://github.com/apache/airflow/issues/23512)
     - [Airflow 2.3.1 - gunicorn keeps removing and adding Permission menu access on Permissions to role Admin (#23926)](https://github.com/apache/airflow/issues/23926)
- [ ] [Reduce grid view API calls (#24083)](https://github.com/apache/airflow/pull/24083): @bbovenzi
- [ ] [Refactor `DagRun.verify_integrity` (#24114)](https://github.com/apache/airflow/pull/24114): @ephraimbuddy
- [ ] [Don't crash scheduler if exec config has old k8s objects (#24117)](https://github.com/apache/airflow/pull/24117): @dstandish @patryk126p
     Linked issues:
     - [Airflow 2.3 scheduler error: 'V1Container' object has no attribute '_startup_probe' (#23727)](https://github.com/apache/airflow/issues/23727)
- [x] [Fix useTasks crash on error (#24152)](https://github.com/apache/airflow/pull/24152): @bbovenzi
- [ ] [Apply per-run log templates to log handlers (#24153)](https://github.com/apache/airflow/pull/24153): @uranusjr
- [x] [Prevent dag dependencies page from crashing (#24166)](https://github.com/apache/airflow/pull/24166): @bbovenzi
- [ ] [Update 'rich' to latest version across the board. (#24186)](https://github.com/apache/airflow/pull/24186): @potiuk
- [ ] [Use `get_hostname` instead of `socket.getfqdn` (#24260)](https://github.com/apache/airflow/pull/24260): @jedcunningham
- [ ] [Optimize calendar view for cron scheduled DAGs (#24262)](https://github.com/apache/airflow/pull/24262): @jedcunningham @potiuk
     Linked issues:
     - [Calendar view is taking too long to load in airflow 2.3.0 (#23602)](https://github.com/apache/airflow/issues/23602)
- [ ] [Speed up grid_data endpoint by 10x (#24284)](https://github.com/apache/airflow/pull/24284): @ashb
- [x] [Check for run_id for grid task groups (#24327)](https://github.com/apache/airflow/pull/24327): @bbovenzi @jedcunningham
     Linked issues:
     - [Fix and speed up grid view (#23947)](https://github.com/apache/airflow/pull/23947)
     - [Grid data: do not load all mapped instances (#23813)](https://github.com/apache/airflow/pull/23813)
- [ ] [`TI.log_url` fix for `map_index` (#24335)](https://github.com/apache/airflow/pull/24335): @fritz-astronomer
     Linked issues:
     - [`TI.log_url` is incorrect with mapped tasks (#24328)](https://github.com/apache/airflow/issues/24328)
- [ ] [Add typescript (#24337)](https://github.com/apache/airflow/pull/24337): @bbovenzi
- [ ] [Add tests for the grid_data endpoint (#24375)](https://github.com/apache/airflow/pull/24375): @ashb
- [ ] [Fix links to sources for examples (#24386)](https://github.com/apache/airflow/pull/24386): @potiuk
- [ ] [Upgrade FAB to 4.1.1 (#24399)](https://github.com/apache/airflow/pull/24399): @potiuk
- [ ] [Fix flaky order of returned dag runs (#24405)](https://github.com/apache/airflow/pull/24405): @potiuk
- [ ] [Improve grid rendering performance with a custom tooltip (#24417)](https://github.com/apache/airflow/pull/24417): @bbovenzi
- [ ] [Upgrade to react 18 and chakra 2 (#24430)](https://github.com/apache/airflow/pull/24430): @bbovenzi
- [ ] [Remove framer-motion from custom tooltip (#24449)](https://github.com/apache/airflow/pull/24449): @bbovenzi
- [ ] [Return empty dict if Pod JSON encoding fails (#24478)](https://github.com/apache/airflow/pull/24478): @dstandish
- [ ] [Upgrade to webpack 5 (#24485)](https://github.com/apache/airflow/pull/24485): @bbovenzi
- [ ] [Add indexes for CASCADE deletes for task_instance (#24488)](https://github.com/apache/airflow/pull/24488): @dstandish @wolfier
     Linked issues:
     - [`airflow db clean task_instance` takes a long time (#24484)](https://github.com/apache/airflow/issues/24484)
- [ ] [Remove internet explorer support (#24495)](https://github.com/apache/airflow/pull/24495): @bbovenzi
- [x] [Fix toast messages (#24505)](https://github.com/apache/airflow/pull/24505): @bbovenzi
- [ ] [Fix deprecated log_id_template value (#24506)](https://github.com/apache/airflow/pull/24506): @jedcunningham
- [ ] [Migrate jsx files that affect run/task selection to tsx (#24509)](https://github.com/apache/airflow/pull/24509): @bbovenzi
- [ ] [Seed log_template table (#24511)](https://github.com/apache/airflow/pull/24511): @jedcunningham
- [ ] [Update flask-appbuilder authlib/oauth dependency (#24516)](https://github.com/apache/airflow/pull/24516): @potiuk
- [ ] [Get rid of TimedJSONWebSignatureSerializer (#24519)](https://github.com/apache/airflow/pull/24519): @potiuk
     Linked issues:
     - [Upgrade to FlaskAppBuilder 4.0.* (#22397)](https://github.com/apache/airflow/issues/22397)
- [x] [Do not calculate grid root instances (#24528)](https://github.com/apache/airflow/pull/24528): @bbovenzi
- [x] [Patch sql_alchemy_conn if old Postgres schemes used (#24569)](https://github.com/apache/airflow/pull/24569): @slyapustin @dstandish
     Linked issues:
     - [Patch sql_alchemy_conn if old postgres scheme used (#22333)](https://github.com/apache/airflow/pull/22333)
- [ ] [Fix migration 0080_2_0_2 - Replace null values before setting column not null (#24585)](https://github.com/apache/airflow/pull/24585): @ephraimbuddy @tm-drtina
     Linked issues:
     - [Support generating SQL script for upgrades (#20962)](https://github.com/apache/airflow/pull/20962)
     - [Migration changes column to NOT NULL without updating NULL data first (#24566)](https://github.com/apache/airflow/issues/24566)
- [ ] [Upgrade FAB to 4.1.2 (#24619)](https://github.com/apache/airflow/pull/24619): @potiuk
- [ ] [We now need at least Flask-WTF 0.15 (#24621)](https://github.com/apache/airflow/pull/24621): @ashb @potiuk
     Linked issues:
     - [Upgrade FAB to 4.1.1 (#24399)](https://github.com/apache/airflow/pull/24399)
- [ ] [Don't render child rows for closed groups (#24637)](https://github.com/apache/airflow/pull/24637): @bbovenzi
- [x] [Fix Grid vertical scrolling (#24684)](https://github.com/apache/airflow/pull/24684): @bbovenzi
- [x] [Debounce status highlighting in Grid view (#24710)](https://github.com/apache/airflow/pull/24710): @bbovenzi
- [x] [Address all yarn test warnings (#24722)](https://github.com/apache/airflow/pull/24722): @bbovenzi
- [ ] [Fix grid date ticks (#24738)](https://github.com/apache/airflow/pull/24738): @bbovenzi
     Linked issues:
     - [Fix Grid vertical scrolling (#24684)](https://github.com/apache/airflow/pull/24684)

Thanks to all who contributed to the release (probably not a complete list!):
@jhtimmins @GApfel @gbonazzoli @uranusjr @bauerfranz @sdebruyn @patryk126p @hubert-pietron @fritz-astronomer @eladkal @torbjornvatn @dstandish @slyapustin @ashb @tanelk @jedcunningham @zachliu @potiuk @bernardocouto @bbovenzi @ephraimbuddy @wolfier @malthe @pierrejeambrun @tm-drtina

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by GApfel** [comment]
Issue #23360 is addressed.

I used the lastest ([docker-compose.yml](https://github.com/apache/airflow/blob/main/docs/apache-airflow/start/docker-compose.yaml)) file, set the version to 2.3.3rc1, and added `AIRFLOW__LOGGING__LOGGING_LEVEL: 'DEBUG'` to the `x-airflow-common` section. The stack built successfully.

**Comment by slyapustin** [comment]
Issue #24569 is addressed.

I created a new branch for the [Airflow on Heroku](https://github.com/slyapustin/airflow-on-heroku/) deployment script with `Airflow==2.3.3rc1` and was able to deploy it without any issues.

**Comment by zachliu** [comment]
issue https://github.com/apache/airflow/issues/23512 was **partially** addressed by PR https://github.com/apache/airflow/pull/24065

see details here: https://github.com/apache/airflow/issues/23512#issuecomment-1156682542

**Comment by bbovenzi** [comment]
Can confirm:
#24327
#24166
#24505
#24684
#24722
#24710
#24637
#24152
#24528

#23779 also works, but a number of other buttons aren't keeping task selection. There is also a minor issue in #24738. I'll work on improvements. Very minor issues, I wouldn't consider them blocking at all.

**Comment by pierrejeambrun** [comment]
https://github.com/apache/airflow/pull/23934 is working as expected
