### ISSUE TITLE
Status of testing Providers that were prepared on July 13, 2022

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#25037]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [airbyte: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-airbyte/3.1.0rc1)
   - [ ] [`AirbyteHook` add cancel job option (#24593)](https://github.com/apache/airflow/pull/24593): @sivankumar86
## Provider [alibaba: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-alibaba/2.0.1rc1)
   - [x] [Update providers to use functools compat for ``cached_property`` (#24582)](https://github.com/apache/airflow/pull/24582): @josh-fell
## Provider [amazon: 4.1.0rc1](https://pypi.org/project/apache-airflow-providers-amazon/4.1.0rc1)
   - [x] [Add test_connection method to AWS hook (#24662)](https://github.com/apache/airflow/pull/24662): @Taragolis
   - [x] [Add AWS operators to create and delete RDS Database (#24099)](https://github.com/apache/airflow/pull/24099): @eskarimov
   - [ ] [Add batch option to `SqsSensor` (#24554)](https://github.com/apache/airflow/pull/24554): @LaPetiteSouris
   - [x] [Add AWS Batch &amp; AWS CloudWatch Extra Links (#24406)](https://github.com/apache/airflow/pull/24406): @Taragolis
   - [x] [Refactoring EmrClusterLink and add it for other AWS EMR Operators (#24294)](https://github.com/apache/airflow/pull/24294): @Taragolis
   - [x] [Move all SQL classes to common-sql provider (#24836)](https://github.com/apache/airflow/pull/24836): @potiuk
   - [x] [Amazon appflow (#24057)](https://github.com/apache/airflow/pull/24057): @igorborgest
   - [ ] [Make extra_args in S3Hook immutable between calls (#24527)](https://github.com/apache/airflow/pull/24527): @Taragolis
   - [ ] [Refactor and fix AWS secret manager invalid exception (#24898)](https://github.com/apache/airflow/pull/24898): @gitstart-airflow
   - [ ] [fix: RedshiftDataHook and RdsHook not use cached connection (#24387)](https://github.com/apache/airflow/pull/24387): @Taragolis
   - [x] [Fix links to sources for examples (#24386)](https://github.com/apache/airflow/pull/24386): @potiuk
   - [ ] [Fix S3KeySensor (#24378)](https://github.com/apache/airflow/pull/24378): @vincbeck
   - [x] [Fix: `emr_conn_id` should be optional in `EmrCreateJobFlowOperator` (#24306)](https://github.com/apache/airflow/pull/24306): @pankajastro
   - [x] [Update providers to use functools compat for ``cached_property`` (#24582)](https://github.com/apache/airflow/pull/24582): @josh-fell
## Provider [apache.drill: 2.1.0rc1](https://pypi.org/project/apache-airflow-providers-apache-drill/2.1.0rc1)
   - [x] [Move all SQL classes to common-sql provider (#24836)](https://github.com/apache/airflow/pull/24836): @potiuk
## Provider [apache.druid: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-apache-druid/3.1.0rc1)
   - [x] [Move all SQL classes to common-sql provider (#24836)](https://github.com/apache/airflow/pull/24836): @potiuk
## Provider [apache.hdfs: 3.0.1rc1](https://pypi.org/project/apache-airflow-providers-apache-hdfs/3.0.1rc1)
   - [ ] [`WebHDFSHook` Bugfix/optional port (#24550)](https://github.com/apache/airflow/pull/24550): @ankurbajaj9
## Provider [apache.hive: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-apache-hive/3.1.0rc1)
   - [x] [Move all SQL classes to common-sql provider (#24836)](https://github.com/apache/airflow/pull/24836): @potiuk
   - [ ] [fix connection extra parameter `auth_mechanism` in `HiveMetastoreHook` and `HiveServer2Hook` (#24713)](https://github.com/apache/airflow/pull/24713): @eladkal
## Provider [apache.pinot: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-apache-pinot/3.1.0rc1)
   - [x] [Move all SQL classes to common-sql provider (#24836)](https://github.com/apache/airflow/pull/24836): @potiuk
## Provider [asana: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-asana/2.0.1rc1)
   - [x] [Update providers to use functools compat for ``cached_property`` (#24582)](https://github.com/apache/airflow/pull/24582): @josh-fell
## Provider [cncf.kubernetes: 4.2.0rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/4.2.0rc1)
   - [ ] [Add `airflow_kpo_in_cluster` label to KPO pods (#24658)](https://github.com/apache/airflow/pull/24658): @jedcunningham
   - [ ] [Find Pod Before Cleanup In KubernetesPodOperator Execution (#22092)](https://github.com/apache/airflow/pull/22092): @michaelmicheal
   - [ ] [Revert &#34;Fix await_container_completion condition (#23883)&#34; (#24474)](https://github.com/apache/airflow/pull/24474): @jedcunningham
   - [x] [Update providers to use functools compat for ``cached_property`` (#24582)](https://github.com/apache/airflow/pull/24582): @josh-fell
## Provider [databricks: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-databricks/3.1.0rc1)
   - [ ] [Added databricks_conn_id as templated field (#24945)](https://github.com/apache/airflow/pull/24945): @skadyan
   - [x] [Add test_connection method to Databricks hook (#24617)](https://github.com/apache/airflow/pull/24617): @phanikumv
   - [x] [Move all SQL classes to common-sql provider (#24836)](https://github.com/apache/airflow/pull/24836): @potiuk
   - [x] [Update providers to use functools compat for ``cached_property`` (#24582)](https://github.com/apache/airflow/pull/24582): @josh-fell
## Provider [dbt.cloud: 2.0.1rc1](https://pypi.org/project/apache-airflow-providers-dbt-cloud/2.0.1rc1)
   - [x] [Update providers to use functools compat for ``cached_property`` (#24582)](https://github.com/apache/airflow/pull/24582): @josh-fell
## Provider [docker: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-docker/3.1.0rc1)
   - [ ] [Force-remove container after DockerOperator execution (#23160)](https://github.com/apache/airflow/pull/23160): @zengbotang
   - [x] [`DockerOperator` fix cli.logs giving character array instead of string (#24726)](https://github.com/apache/airflow/pull/24726): @pasalkarsachin1
## Provider [elasticsearch: 4.1.0rc1](https://pypi.org/project/apache-airflow-providers-elasticsearch/4.1.0rc1)
   - [x] [Adding ElasticserachPythonHook - ES Hook With The Python Client (#24895)](https://github.com/apache/airflow/pull/24895): @alexkruc
   - [x] [Move all SQL classes to common-sql provider (#24836)](https://github.com/apache/airflow/pull/24836): @potiuk
   - [ ] [Move fallible ti.task.dag assignment back inside try/except block (#24533) (#24592)](https://github.com/apache/airflow/pull/24592): @ejk43
## Provider [exasol: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-exasol/3.1.0rc1)
   - [x] [Move all SQL classes to common-sql provider (#24836)](https://github.com/apache/airflow/pull/24836): @potiuk
## Provider [facebook: 3.0.1rc1](https://pypi.org/project/apache-airflow-providers-facebook/3.0.1rc1)
   - [x] [Update providers to use functools compat for ``cached_property`` (#24582)](https://github.com/apache/airflow/pull/24582): @josh-fell
## Provider [ftp: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-ftp/3.1.0rc1)
   - [x] [Add blocksize arg for ftp hook (#24860)](https://github.com/apache/airflow/pull/24860): @kevgeo
## Provider [github: 2.1.0rc1](https://pypi.org/project/apache-airflow-providers-github/2.1.0rc1)
   - [x] [Add test connection functionality to `GithubHook` (#24903)](https://github.com/apache/airflow/pull/24903): @josh-fell
## Provider [google: 8.2.0rc1](https://pypi.org/project/apache-airflow-providers-google/8.2.0rc1)
   - [ ] [PubSub assets &amp; system tests migration (AIP-47) (#24867)](https://github.com/apache/airflow/pull/24867): @wojsamjan
   - [ ] [Add handling state of existing Dataproc batch (#24924)](https://github.com/apache/airflow/pull/24924): @danielvdende
   - [ ] [Add links for Google Kubernetes Engine operators (#24786)](https://github.com/apache/airflow/pull/24786): @MaksYermak
   - [x] [Add test_connection method to GoogleBaseHook (#24682)](https://github.com/apache/airflow/pull/24682): @phanikumv
   - [ ] [Add gcp_conn_id argument to GoogleDriveToLocalOperator (#24622)](https://github.com/apache/airflow/pull/24622): @aspain
   - [ ] [Add DeprecationWarning for column_transformations parameter in AutoML (#24467)](https://github.com/apache/airflow/pull/24467): @MaksYermak
   - [ ] [Modify BigQueryCreateExternalTableOperator to use updated hook function (#24363)](https://github.com/apache/airflow/pull/24363): @cswpy
   - [x] [Move all SQL classes to common-sql provider (#24836)](https://github.com/apache/airflow/pull/24836): @potiuk
   - [ ] [Datacatalog assets &amp; system tests migration (AIP-47) (#24600)](https://github.com/apache/airflow/pull/24600): @wojsamjan
   - [x] [Upgrade FAB to 4.1.1 (#24399)](https://github.com/apache/airflow/pull/24399): @potiuk
   - [ ] [GCSDeleteObjectsOperator empty prefix bug fix (#24353)](https://github.com/apache/airflow/pull/24353): @Lavedonio
   - [x] [perf(BigQuery): pass table_id as str type (#23141)](https://github.com/apache/airflow/pull/23141): @bryan824
   - [x] [Update providers to use functools compat for ``cached_property`` (#24582)](https://github.com/apache/airflow/pull/24582): @josh-fell
## Provider [hashicorp: 3.0.1rc1](https://pypi.org/project/apache-airflow-providers-hashicorp/3.0.1rc1)
   - [x] [Update providers to use functools compat for ``cached_property`` (#24582)](https://github.com/apache/airflow/pull/24582): @josh-fell
## Provider [http: 4.0.0rc1](https://pypi.org/project/apache-airflow-providers-http/4.0.0rc1)
   - [ ] [Add TCP_KEEPALIVE option to http provider (#24967)](https://github.com/apache/airflow/pull/24967): @potiuk
## Provider [jdbc: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-jdbc/3.1.0rc1)
   - [x] [Move all SQL classes to common-sql provider (#24836)](https://github.com/apache/airflow/pull/24836): @potiuk
## Provider [jira: 3.0.1rc1](https://pypi.org/project/apache-airflow-providers-jira/3.0.1rc1)
   - [ ] [Fix the error caused by passing unused context in JiraSensor.poke (#23352)](https://github.com/apache/airflow/pull/23352): @kianelbo
## Provider [microsoft.azure: 4.1.0rc1](https://pypi.org/project/apache-airflow-providers-microsoft-azure/4.1.0rc1)
   - [x] [Add `test_connection` method to AzureCosmosDBHook (#25018)](https://github.com/apache/airflow/pull/25018): @phanikumv
   - [x] [Add test_connection method to AzureFileShareHook (#24843)](https://github.com/apache/airflow/pull/24843): @phanikumv
   - [x] [Add test_connection method to Azure WasbHook (#24771)](https://github.com/apache/airflow/pull/24771): @phanikumv
   - [x] [Implement Azure service bus subscription (create, delete)Operators (#24625)](https://github.com/apache/airflow/pull/24625): @bharanidharan14
   - [x] [Implement Azure Service Bus Queue Operators (#24038)](https://github.com/apache/airflow/pull/24038): @bharanidharan14
   - [x] [Update providers to use functools compat for ``cached_property`` (#24582)](https://github.com/apache/airflow/pull/24582): @josh-fell
## Provider [microsoft.mssql: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-microsoft-mssql/3.1.0rc1)
   - [x] [Move all SQL classes to common-sql provider (#24836)](https://github.com/apache/airflow/pull/24836): @potiuk
## Provider [mysql: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-mysql/3.1.0rc1)
   - [x] [Move all SQL classes to common-sql provider (#24836)](https://github.com/apache/airflow/pull/24836): @potiuk
   - [ ] [Close the MySQL connections once operations are done. (#24508)](https://github.com/apache/airflow/pull/24508): @pavel-lexyr
## Provider [odbc: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-odbc/3.1.0rc1)
   - [x] [Move all SQL classes to common-sql provider (#24836)](https://github.com/apache/airflow/pull/24836): @potiuk
## Provider [oracle: 3.2.0rc1](https://pypi.org/project/apache-airflow-providers-oracle/3.2.0rc1)
   - [x] [Move all SQL classes to common-sql provider (#24836)](https://github.com/apache/airflow/pull/24836): @potiuk
## Provider [postgres: 5.1.0rc1](https://pypi.org/project/apache-airflow-providers-postgres/5.1.0rc1)
   - [x] [Move all SQL classes to common-sql provider (#24836)](https://github.com/apache/airflow/pull/24836): @potiuk
## Provider [presto: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-presto/3.1.0rc1)
   - [x] [Adding generic SqlToSlackOperator (#24663)](https://github.com/apache/airflow/pull/24663): @alexkruc
   - [x] [Move all SQL classes to common-sql provider (#24836)](https://github.com/apache/airflow/pull/24836): @potiuk
## Provider [qubole: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-qubole/3.1.0rc1)
   - [x] [Move all SQL classes to common-sql provider (#24836)](https://github.com/apache/airflow/pull/24836): @potiuk
## Provider [salesforce: 5.0.0rc1](https://pypi.org/project/apache-airflow-providers-salesforce/5.0.0rc1)
   - [ ] [Remove Tableau from Salesforce provider (#23747)](https://github.com/apache/airflow/pull/23747): @eladkal
   - [x] [Add support for Salesforce bulk api (#24473)](https://github.com/apache/airflow/pull/24473): @ishiis
   - [x] [Update providers to use functools compat for ``cached_property`` (#24582)](https://github.com/apache/airflow/pull/24582): @josh-fell

------------

## Provider [sftp: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-sftp/3.1.0rc1) !!! NOTE this one s removed for breaking changes that need 4.0.0 release.
   - [ ] [Convert sftp hook to use paramiko instead of pysftp (#24512)](https://github.com/apache/airflow/pull/24512): @pauldalewilliams
   - [ ] [Update `actual_file_to_check` with rendered `path` (#24451)](https://github.com/apache/airflow/pull/24451): @remem9527

------------

## Provider [slack: 5.1.0rc1](https://pypi.org/project/apache-airflow-providers-slack/5.1.0rc1)
   - [x] [Move all SQL classes to common-sql provider (#24836)](https://github.com/apache/airflow/pull/24836): @potiuk
   - [x] [Adding generic SqlToSlackOperator (#24663)](https://github.com/apache/airflow/pull/24663): @alexkruc
## Provider [snowflake: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-snowflake/3.1.0rc1)
   - [x] [Adding generic SqlToSlackOperator (#24663)](https://github.com/apache/airflow/pull/24663): @alexkruc
   - [x] [Move all SQL classes to common-sql provider (#24836)](https://github.com/apache/airflow/pull/24836): @potiuk
   - [ ] [Pattern parameter in S3ToSnowflakeOperator (#24571)](https://github.com/apache/airflow/pull/24571): @Taragolis
   - [ ] [S3ToSnowflakeOperator: escape single quote in s3_keys (#24607)](https://github.com/apache/airflow/pull/24607): @Taragolis
## Provider [sqlite: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-sqlite/3.1.0rc1)
   - [x] [Move all SQL classes to common-sql provider (#24836)](https://github.com/apache/airflow/pull/24836): @potiuk
## Provider [ssh: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-ssh/3.1.0rc1)
   - [ ] [Less verbose logging in ssh operator (#24915)](https://github.com/apache/airflow/pull/24915): @hsnprsd
   - [ ] [Convert sftp hook to use paramiko instead of pysftp (#24512)](https://github.com/apache/airflow/pull/24512): @pauldalewilliams
   - [x] [Update providers to use functools compat for ``cached_property`` (#24582)](https://github.com/apache/airflow/pull/24582): @josh-fell
## Provider [tableau: 3.0.1rc1](https://pypi.org/project/apache-airflow-providers-tableau/3.0.1rc1)
   - [ ] [Remove Tableau from Salesforce provider (#23747)](https://github.com/apache/airflow/pull/23747): @eladkal
## Provider [trino: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-trino/3.1.0rc1)
   - [x] [Move all SQL classes to common-sql provider (#24836)](https://github.com/apache/airflow/pull/24836): @potiuk
   - [x] [Add test_connection method to Trino hook (#24583)](https://github.com/apache/airflow/pull/24583): @phanikumv
   - [x] [Add on_kill() to kill Trino query if Airflow task is killed (#24559)](https://github.com/apache/airflow/pull/24559): @phanikumv
   - [x] [Add TrinoOperator (#24415)](https://github.com/apache/airflow/pull/24415): @phanikumv
## Provider [vertica: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-vertica/3.1.0rc1)
   - [x] [Move all SQL classes to common-sql provider (#24836)](https://github.com/apache/airflow/pull/24836): @potiuk

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-by-contributors)

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by pankajkoti** [comment]
I have a question regarding Provider [http: 4.0.0rc1](https://pypi.org/project/apache-airflow-providers-http/4.0.0rc1) and added it in the PR discussion here: https://github.com/apache/airflow/pull/24967#discussion_r920887030

**Comment by potiuk** [comment]
Thanks @pankajkoti - excellent point, I followed up with some extra comment/questions. I am happy to do either way (continue with self.hook removal, or restore it in RC2, and I think we should discuss what's best approach in general for deferred operators.

**Comment by phanikumv** [comment]
Tested the below PR with the respective rc images and they are working fine.

Add test_connection method to Databricks hook (#24617): @phanikumv
Add test_connection method to GoogleBaseHook (#24682): @phanikumv
Add test_connection method to AzureCosmosDBHook (#25018): @phanikumv
Add test_connection method to AzureFileShareHook (#24843): @phanikumv
Add test_connection method to Azure WasbHook (#24771): @phanikumv

**Comment by potiuk** [comment]
I tested all my changes - mostly they were about common-sql extraction and dependencies. They all looks good!

**Comment by phanikumv** [comment]
Completed testing the below PR and they are working fine.

Add test_connection method to Trino hook (#24583): @phanikumv
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/94376113/178978768-61af41d2-f26f-474a-8384-ebe56bc03026.png">

Add on_kill() to kill Trino query if Airflow task is killed (#24559): @phanikumv
Add TrinoOperator (#24415): @phanikumv

<img width="916" alt="image" src="https://user-images.githubusercontent.com/94376113/178978600-168a0ae0-8d72-4494-9270-60a6ef3e6ab0.png">

**Comment by igorborgest** [comment]
I can confirm that the [Amazon Appflow support](https://github.com/apache/airflow/pull/24057) is working as expected for `apache-airflow-providers-amazon==4.1.0rc1`.


![image](https://user-images.githubusercontent.com/2163472/178982018-1da3eaef-3128-499c-8c7b-c030b2862344.png)

**Comment by potiuk** [comment]
> It's a little difficult to test https://github.com/apache/airflow/pull/24582 since I don't have the means to test all of these providers in the wild, but I spot-checked the package files and +1

Indeed.

**Comment by ishiis** [comment]
#24473 is working as expected.

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/12693596/179033525-71d0504a-a872-4a5a-8118-2ad4ba0888cb.png">

**Comment by Taragolis** [comment]
Working as expected: #24662 #24406 #24294
Also check depreciation warnings from #24670 - not listed here but included in `apache-airflow-providers-amazon==4.1.0rc1`

**Comment by potiuk** [comment]
Yep #24670 has been removed from changelog as "not important" - we can re-add them later for the docs purpose see changelog with comments included https://raw.githubusercontent.com/apache/airflow/main/airflow/providers/amazon/CHANGELOG.rst)

**Comment by pauldalewilliams** [comment]
@potiuk Re #24512 does the fact that I removed deprecated parameters necessitate a major version bump for the SFTP provider?  See the second bullet point on my PR.

**Comment by kevgeo** [comment]
I have tested #24860, works great!

**Comment by pasalkarsachin1** [comment]
Looks okay to me https://github.com/apache/airflow/pull/24726

**Comment by potiuk** [comment]
> I see an issue with (#24550) <https://github.com/apache/airflow/pull/24550>.will try to raise a PR Regards Ankur Bajaj

How Serious? (BTW. it's no big problem we can remove it from the release and make rc2 right after - we are doing that with SFTP already).

**Comment by Fokko** [comment]
@potiuk would it be possible to include this patch into the RC2 as well? https://github.com/apache/airflow/pull/25099

**Comment by potiuk** [comment]
Sure. I will remove tabular from delivery too and add it to the list of rc2's

**Comment by alexott** [comment]
#24617 for Databricks has an issue because selected API is available only on AWS, and will fail on Azure/GCP...

More general question - is it possible to subscribe to all Databricks-related RPs?

**Comment by potiuk** [comment]
> #24617 for Databricks has an issue because selected API is available only on AWS, and will fail on Azure/GCP... 

Good check. That is not a regression, test_connection is a new method/functionality added and it partially works, so it's not a reason to cancel it. It can be adressed in the next release.

> More general question - is it possible to subscribe to all Databricks-related RPs?

We discussed it before, unfortunately CODEOWNER (which is a bad name BTW) only allows commiters to be marked as reviewer to part  of the repo, which is a bummer (because it's not a codeowner by any means is just assigning people to be reviewers which has nothing to do with either being committer or owner).

For now, the best you can do (and it should be pretty accurate) is to subscribe to all notifiction and write a custom filter - if you are using gmail (that's what I'd do at least). It's actually pretty accurate. All PRs/commit messages with databrics contain list of changed files so subscribing to anything with "providers/databricks" should do the job nicely and you can choose how it should be surfaced in your email (and you can archive/store non-matching emails from commts@github elsewhere).

 In the future (the mixed-governance was a pre-requisite to it) we plan to split providers to separate repos and then it will be much more flexible and you will be able to write more precise filters.

**Comment by ankurbajaj9** [comment]
> > I see an issue with (#24550) #24550.will try to raise a PR Regards Ankur Bajaj
> 
> How Serious? (BTW. it's no big problem we can remove it from the release and make rc2 right after - we are doing that with SFTP already).

Not serious at all. It seems the authentication is missing since the original code only. Nothing is breaking , it just needs additional lines to be able to work in my environment.

**Comment by potiuk** [comment]
> Not serious at all. It seems the authentication is missing since the original code only. Nothing is breaking , it just needs additional lines to be able to work in my environment.

Right. Then we can release it in next wave :)

**Comment by potiuk** [comment]
@Fokko - I actually released 1.0.0 (will be easier) and release 1.0.1 right after - 1.0.0 was the first release, no regression there.

**Comment by potiuk** [comment]
(both SFTP/Tabular will be rc1 then).

**Comment by potiuk** [comment]
Closing this one as providers are released. Thanks everyone. you rock!
