### ISSUE TITLE
Status of testing Providers that were prepared on July 17, 2022

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#25113]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [sftp: 4.0.0rc1](https://pypi.org/project/apache-airflow-providers-sftp/4.0.0rc1)
   - [x] [Convert sftp hook to use paramiko instead of pysftp (#24512)](https://github.com/apache/airflow/pull/24512): @pauldalewilliams
   - [x] [Update `actual_file_to_check` with rendered `path` (#24451)](https://github.com/apache/airflow/pull/24451): @remem9527
## Provider [tabular: 1.0.1rc1](https://pypi.org/project/apache-airflow-providers-tabular/1.0.1rc1)
   - [ ] [Set grant type of the Tabular hook (#25099)](https://github.com/apache/airflow/pull/25099): @Fokko

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-by-contributors)

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by pauldalewilliams** [comment]
I tested #24512 now and things seem to be working as expected on my end.  Thanks @potiuk!

**Comment by potiuk** [comment]
@Fokko  - wating for your input :)

**Comment by potiuk** [comment]
Released. I hope @Fokko  the 1.0.1 version is good :)
