### ISSUE TITLE
Status of testing Providers that were prepared on August 10, 2022

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#25634]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 5.0.0rc1](https://pypi.org/project/apache-airflow-providers-amazon/5.0.0rc1)
   - [ ] [Avoid requirement that AWS Secret Manager JSON values be urlencoded. (#25432)](https://github.com/apache/airflow/pull/25432): @dwreeves
   - [ ] [Remove Amazon deprecated modules (#25543)](https://github.com/apache/airflow/pull/25543): @vincbeck
   - [ ] [Resolve Amazon Hook&#39;s `region_name` and `config` in wrapper (#25336)](https://github.com/apache/airflow/pull/25336): @Taragolis
   - [ ] [Resolve and validate AWS Connection parameters in wrapper (#25256)](https://github.com/apache/airflow/pull/25256): @Taragolis
   - [ ] [Standardize AwsLambda (#25100)](https://github.com/apache/airflow/pull/25100): @eladkal
   - [ ] [Refactor monolithic ECS Operator into Operators, Sensors, and a Hook (#25413)](https://github.com/apache/airflow/pull/25413): @ferruzzi
   - [ ] [Remove deprecated modules from Amazon provider package (#25609)](https://github.com/apache/airflow/pull/25609): @vincbeck
   - [ ] [Add EMR Serverless Operators and Hooks (#25324)](https://github.com/apache/airflow/pull/25324): @syedahsn
   - [ ] [Hide unused fields for Amazon Web Services connection (#25416)](https://github.com/apache/airflow/pull/25416): @Taragolis
   - [ ] [Enable Auto-incrementing Transform job name in SageMakerTransformOperator (#25263)](https://github.com/apache/airflow/pull/25263): @celeriev
   - [ ] [Unify DbApiHook.run() method with the methods which override it (#23971)](https://github.com/apache/airflow/pull/23971): @kazanzhy
   - [ ] [SQSPublishOperator should allow sending messages to a FIFO Queue (#25171)](https://github.com/apache/airflow/pull/25171): @dbarrundiag
   - [ ] [Glue Job Driver logging (#25142)](https://github.com/apache/airflow/pull/25142): @ferruzzi
   - [ ] [Bump typing-extensions and mypy for ParamSpec (#25088)](https://github.com/apache/airflow/pull/25088): @uranusjr
   - [ ] [Fix S3Hook transfer config arguments validation (#25544)](https://github.com/apache/airflow/pull/25544): @Taragolis
   - [ ] [Fix BatchOperator links on wait_for_completion = True (#25228)](https://github.com/apache/airflow/pull/25228): @Taragolis
   - [ ] [SqlToS3Operator: change column type from object to str in dataframe (#25083)](https://github.com/apache/airflow/pull/25083): @pastanton
   - [ ] [Deprecate usage of `extra[host]` in AWS&#39;s connection (#25494)](https://github.com/apache/airflow/pull/25494): @gmcrocetti
   - [ ] [Get boto3.session.Session by appropriate method (#25569)](https://github.com/apache/airflow/pull/25569): @Taragolis
## Provider [apache.drill: 2.2.0rc1](https://pypi.org/project/apache-airflow-providers-apache-drill/2.2.0rc1)
   - [ ] [Unify DbApiHook.run() method with the methods which override it (#23971)](https://github.com/apache/airflow/pull/23971): @kazanzhy
## Provider [apache.druid: 3.2.0rc1](https://pypi.org/project/apache-airflow-providers-apache-druid/3.2.0rc1)
   - [ ] [Move all &#34;old&#34; SQL operators to common.sql providers (#25350)](https://github.com/apache/airflow/pull/25350): @potiuk
## Provider [apache.hdfs: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-apache-hdfs/3.1.0rc1)
   - [ ] [Adding Authentication to webhdfs sensor  (#25110)](https://github.com/apache/airflow/pull/25110): @ankurbajaj9
## Provider [apache.hive: 4.0.0rc1](https://pypi.org/project/apache-airflow-providers-apache-hive/4.0.0rc1)
   - [ ] [Deprecate hql parameters and synchronize DBApiHook method APIs (#25299)](https://github.com/apache/airflow/pull/25299): @potiuk
   - [ ] [Remove Smart Sensors (#25507)](https://github.com/apache/airflow/pull/25507): @ashb
## Provider [apache.livy: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-apache-livy/3.1.0rc1)
   - [ ] [Add auth_type to LivyHook (#25183)](https://github.com/apache/airflow/pull/25183): @bdsoha
## Provider [apache.pinot: 3.2.0rc1](https://pypi.org/project/apache-airflow-providers-apache-pinot/3.2.0rc1)
   - [ ] [Deprecate hql parameters and synchronize DBApiHook method APIs (#25299)](https://github.com/apache/airflow/pull/25299): @potiuk
   - [ ] [Unify DbApiHook.run() method with the methods which override it (#23971)](https://github.com/apache/airflow/pull/23971): @kazanzhy
## Provider [common.sql: 1.1.0rc1](https://pypi.org/project/apache-airflow-providers-common-sql/1.1.0rc1/)
   - [ ] [Fix fetch_all_handler & db-api tests for it (#25430)](https://github.com/apache/airflow/pull/25430): @FanatoniQ 
   - [ ] [Align Common SQL provider logo location (#25538)](https://github.com/apache/airflow/pull/25538): @josh-fell 
   - [ ] [Move all &#34;old&#34; SQL operators to common.sql providers (#25350)](https://github.com/apache/airflow/pull/25350): 
   - [ ] [Allow Legacy SqlSensor to use the common.sql providers (#25293)](https://github.com/apache/airflow/pull/25293): @potiuk
   - [ ] [Deprecate hql parameters and synchronize DBApiHook method APIs (#25299)](https://github.com/apache/airflow/pull/25299): @potiuk
   - [ ] [Unify DbApiHook.run() method with the methods which override it (#23971)](https://github.com/apache/airflow/pull/23971): @kazanzhy
   - [ ] [Common SQLCheckOperators Various Functionality Update (#25164)](https://github.com/apache/airflow/pull/25164): @denimalpaca
## Provider [cncf.kubernetes: 4.3.0rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/4.3.0rc1)
   - [ ] [Improve taskflow type hints with ParamSpec (#25173)](https://github.com/apache/airflow/pull/25173): @uranusjr
   - [ ] [Fix xcom_sidecar stuck problem (#24993)](https://github.com/apache/airflow/pull/24993): @MaksYermak
## Provider [databricks: 3.2.0rc1](https://pypi.org/project/apache-airflow-providers-databricks/3.2.0rc1)
   - [ ] [Databricks: update user-agent string (#25578)](https://github.com/apache/airflow/pull/25578): @alexott
   - [ ] [More improvements in the Databricks operators (#25260)](https://github.com/apache/airflow/pull/25260): @alexott
   - [ ] [Improved telemetry for Databricks provider (#25115)](https://github.com/apache/airflow/pull/25115): @alexott
   - [ ] [Unify DbApiHook.run() method with the methods which override it (#23971)](https://github.com/apache/airflow/pull/23971): @kazanzhy
   - [ ] [Databricks: fix test_connection implementation (#25114)](https://github.com/apache/airflow/pull/25114): @alexott
   - [ ] [Do not convert boolean values to string in deep_string_coerce function (#25394)](https://github.com/apache/airflow/pull/25394): @jgr-trackunit
   - [ ] [Correctly handle output of the failed tasks (#25427)](https://github.com/apache/airflow/pull/25427): @alexott
## Provider [dbt.cloud: 2.1.0rc1](https://pypi.org/project/apache-airflow-providers-dbt-cloud/2.1.0rc1)
   - [ ] [Improve taskflow type hints with ParamSpec (#25173)](https://github.com/apache/airflow/pull/25173): @uranusjr
## Provider [elasticsearch: 4.2.0rc1](https://pypi.org/project/apache-airflow-providers-elasticsearch/4.2.0rc1)
   - [ ] [Improve ElasticsearchTaskHandler (#21942)](https://github.com/apache/airflow/pull/21942): @millin
## Provider [exasol: 4.0.0rc1](https://pypi.org/project/apache-airflow-providers-exasol/4.0.0rc1)
   - [ ] [Deprecate hql parameters and synchronize DBApiHook method APIs (#25299)](https://github.com/apache/airflow/pull/25299): @potiuk
   - [ ] [Unify DbApiHook.run() method with the methods which override it (#23971)](https://github.com/apache/airflow/pull/23971): @kazanzhy
## Provider [google: 8.3.0rc1](https://pypi.org/project/apache-airflow-providers-google/8.3.0rc1)
   - [ ] [add description method in BigQueryCursor class (#25366)](https://github.com/apache/airflow/pull/25366): @sophiely
   - [ ] [Add project_id as a templated variable in two BQ operators (#24768)](https://github.com/apache/airflow/pull/24768): @leahecole
   - [ ] [Remove Amazon deprecated modules (#25543)](https://github.com/apache/airflow/pull/25543): @vincbeck
   - [ ] [Move all &#34;old&#34; SQL operators to common.sql providers (#25350)](https://github.com/apache/airflow/pull/25350): @potiuk
   - [ ] [Improve taskflow type hints with ParamSpec (#25173)](https://github.com/apache/airflow/pull/25173): @uranusjr
   - [ ] [Unify DbApiHook.run() method with the methods which override it (#23971)](https://github.com/apache/airflow/pull/23971): @kazanzhy
   - [ ] [Bump typing-extensions and mypy for ParamSpec (#25088)](https://github.com/apache/airflow/pull/25088): @uranusjr
   - [ ] [Deprecate hql parameters and synchronize DBApiHook method APIs (#25299)](https://github.com/apache/airflow/pull/25299): @potiuk
   - [ ] [New Operators for the Google Cloud Dataform service (#25587)](https://github.com/apache/airflow/pull/25587): @lwyszomi
   - [ ] [Fix an issue on document (#25614)](https://github.com/apache/airflow/pull/25614): @Corea
   - [ ] [Fix BigQueryInsertJobOperator cancel_on_kill (#25342)](https://github.com/apache/airflow/pull/25342): @lidalei
   - [ ] [Fix BaseSQLToGCSOperator approx_max_file_size_bytes (#25469)](https://github.com/apache/airflow/pull/25469): @dclandau
   - [ ] [Fix PostgresToGCSOperat bool dtype (#25475)](https://github.com/apache/airflow/pull/25475): @dclandau
   - [ ] [Fix Vertex AI Custom Job training issue (#25367)](https://github.com/apache/airflow/pull/25367): @MaksYermak
   - [ ] [Fix Flask Login user setting for Flask 2.2 and Flask-Login 0.6.2 (#25318)](https://github.com/apache/airflow/pull/25318): @potiuk
## Provider [hashicorp: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-hashicorp/3.1.0rc1)
   - [ ] [Use newer kubernetes authentication method in internal vault client (#25351)](https://github.com/apache/airflow/pull/25351): @pdebelak
## Provider [jdbc: 3.2.0rc1](https://pypi.org/project/apache-airflow-providers-jdbc/3.2.0rc1)
   - [ ] [Fixing JdbcOperator non-SELECT statement run (#25412)](https://github.com/apache/airflow/pull/25412): @kazanzhy
   - [ ] [Unify DbApiHook.run() method with the methods which override it (#23971)](https://github.com/apache/airflow/pull/23971): @kazanzhy
## Provider [microsoft.azure: 4.2.0rc1](https://pypi.org/project/apache-airflow-providers-microsoft-azure/4.2.0rc1)
   - [ ] [Add `test_connection` method to AzureContainerInstanceHook (#25362)](https://github.com/apache/airflow/pull/25362): @phanikumv
   - [ ] [Add test_connection to Azure Batch hook (#25235)](https://github.com/apache/airflow/pull/25235): @phanikumv
   - [ ] [Bump typing-extensions and mypy for ParamSpec (#25088)](https://github.com/apache/airflow/pull/25088): @uranusjr
   - [ ] [Implement Azure Service Bus (Update and Receive) Subscription Operator (#25029)](https://github.com/apache/airflow/pull/25029): @bharanidharan14
   - [ ] [Set default wasb Azure http logging level to warning; fixes #16224 (#18896)](https://github.com/apache/airflow/pull/18896): @havocbane
## Provider [microsoft.mssql: 3.2.0rc1](https://pypi.org/project/apache-airflow-providers-microsoft-mssql/3.2.0rc1)
   - [ ] [Unify DbApiHook.run() method with the methods which override it (#23971)](https://github.com/apache/airflow/pull/23971): @kazanzhy
   - [ ] [Fix MsSqlHook get_uri, adding pymssql driver to scheme (25092) (#25185)](https://github.com/apache/airflow/pull/25185): @FanatoniQ
## Provider [mysql: 3.2.0rc1](https://pypi.org/project/apache-airflow-providers-mysql/3.2.0rc1)
   - [ ] [Unify DbApiHook.run() method with the methods which override it (#23971)](https://github.com/apache/airflow/pull/23971): @kazanzhy
## Provider [neo4j: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-neo4j/3.1.0rc1)
   - [ ] [Add documentation for July 2022 Provider&#39;s release (#25030)](https://github.com/apache/airflow/pull/25030): @potiuk
   - [ ] [Unify DbApiHook.run() method with the methods which override it (#23971)](https://github.com/apache/airflow/pull/23971): @kazanzhy
## Provider [odbc: 3.1.1rc1](https://pypi.org/project/apache-airflow-providers-odbc/3.1.1rc1)
   - [ ] [Fix odbc hook sqlalchemy_scheme docstring (#25421)](https://github.com/apache/airflow/pull/25421): @FanatoniQ
## Provider [oracle: 3.3.0rc1](https://pypi.org/project/apache-airflow-providers-oracle/3.3.0rc1)
   - [ ] [Unify DbApiHook.run() method with the methods which override it (#23971)](https://github.com/apache/airflow/pull/23971): @kazanzhy
## Provider [postgres: 5.2.0rc1](https://pypi.org/project/apache-airflow-providers-postgres/5.2.0rc1)
   - [ ] [Use only public AwsHook&#39;s methods during IAM authorization (#25424)](https://github.com/apache/airflow/pull/25424): @Taragolis
   - [ ] [Unify DbApiHook.run() method with the methods which override it (#23971)](https://github.com/apache/airflow/pull/23971): @kazanzhy
## Provider [presto: 4.0.0rc1](https://pypi.org/project/apache-airflow-providers-presto/4.0.0rc1)
   - [ ] [Remove `PrestoToSlackOperator` (#25425)](https://github.com/apache/airflow/pull/25425): @eladkal
   - [ ] [Deprecate hql parameters and synchronize DBApiHook method APIs (#25299)](https://github.com/apache/airflow/pull/25299): @potiuk
   - [ ] [Unify DbApiHook.run() method with the methods which override it (#23971)](https://github.com/apache/airflow/pull/23971): @kazanzhy
## Provider [qubole: 3.2.0rc1](https://pypi.org/project/apache-airflow-providers-qubole/3.2.0rc1)
   - [ ] [Make extra link work in UI (#25500)](https://github.com/apache/airflow/pull/25500): @uranusjr
   - [ ] [Move all &#34;old&#34; SQL operators to common.sql providers (#25350)](https://github.com/apache/airflow/pull/25350): @potiuk
   - [ ] [Improve taskflow type hints with ParamSpec (#25173)](https://github.com/apache/airflow/pull/25173): @uranusjr
   - [ ] [Correctly render `results_parser_callable` parameter in Qubole operator docs (#25514)](https://github.com/apache/airflow/pull/25514): @josh-fell
## Provider [salesforce: 5.1.0rc1](https://pypi.org/project/apache-airflow-providers-salesforce/5.1.0rc1)
   - [ ] [Improve taskflow type hints with ParamSpec (#25173)](https://github.com/apache/airflow/pull/25173): @uranusjr
## Provider [snowflake: 3.2.0rc1](https://pypi.org/project/apache-airflow-providers-snowflake/3.2.0rc1)
   - [ ] [Move all &#34;old&#34; SQL operators to common.sql providers (#25350)](https://github.com/apache/airflow/pull/25350): @potiuk
   - [ ] [Unify DbApiHook.run() method with the methods which override it (#23971)](https://github.com/apache/airflow/pull/23971): @kazanzhy
## Provider [sqlite: 3.2.0rc1](https://pypi.org/project/apache-airflow-providers-sqlite/3.2.0rc1)
   - [ ] [Unify DbApiHook.run() method with the methods which override it (#23971)](https://github.com/apache/airflow/pull/23971): @kazanzhy
## Provider [trino: 4.0.0rc1](https://pypi.org/project/apache-airflow-providers-trino/4.0.0rc1)
   - [ ] [Deprecate hql parameters and synchronize DBApiHook method APIs (#25299)](https://github.com/apache/airflow/pull/25299): @potiuk
   - [ ] [Unify DbApiHook.run() method with the methods which override it (#23971)](https://github.com/apache/airflow/pull/23971): @kazanzhy
## Provider [vertica: 3.2.0rc1](https://pypi.org/project/apache-airflow-providers-vertica/3.2.0rc1)
   - [ ] [Optimize log when using VerticaOperator (#25566)](https://github.com/apache/airflow/pull/25566): @sudohainguyen
   - [ ] [Unify DbApiHook.run() method with the methods which override it (#23971)](https://github.com/apache/airflow/pull/23971): @kazanzhy
## Provider [yandex: 3.1.0rc1](https://pypi.org/project/apache-airflow-providers-yandex/3.1.0rc1)
   - [ ] [YandexCloud provider: Support new Yandex SDK features for DataProc (#25158)](https://github.com/apache/airflow/pull/25158): @Piatachock

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-by-contributors)

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
For some reason the automation did not include changes in comon.sql - I added it manually and fix it for the next run :)

**Comment by potiuk** [comment]
Canceling this one. New release comes shortly :). Apologies.
