### ISSUE TITLE
Status of testing of Apache Airflow 2.3.4rc1

### ISSUE THREAD

**Issue by ephraimbuddy** [apache/airflow#25846]
### Body

We have a kind request for all the contributors to the latest [Apache Airflow RC 2.3.4rc1](https://pypi.org/project/apache-airflow/2.3.4rc1/).

Could you please help us to test the RC versions of Airflow?

Please let us know in the comment if the issue is addressed in the latest RC.

- [ ] [Don't rely on current ORM structure for db clean command (#23574)](https://github.com/apache/airflow/pull/23574): @dstandish
- [ ] [clearer method name in scheduler_job.py (#23702)](https://github.com/apache/airflow/pull/23702): @RNHTTR
- [ ] [Clear next method when clearing TIs (#23929)](https://github.com/apache/airflow/pull/23929): @tanelk
- [ ] [Serialize pod_override to JSON before pickling executor_config (#24356)](https://github.com/apache/airflow/pull/24356): @dstandish
- [ ] [Send DAG timeout callbacks to processor outside of prohibit_commit (#24366)](https://github.com/apache/airflow/pull/24366): @tanelk
- [x] [Fix pid check (#24636)](https://github.com/apache/airflow/pull/24636): @iasoon @krcrouse @vinit-tribes
     Linked issues:
     - [Recorded pid<> does not match the current pid <> (#20992)](https://github.com/apache/airflow/issues/20992)
     - [Task processes killed with WARNING - Recorded pid does not match the current pid (#17507)](https://github.com/apache/airflow/issues/17507)
- [x] [TriggerDagRunOperator.operator_extra_links is attr (#24676)](https://github.com/apache/airflow/pull/24676): @uranusjr @consciencee
     Linked issues:
     - [Mapped TriggerDagRunOperator causes SerializationError due to operator_extra_links 'property' object is not iterable  (#24653)](https://github.com/apache/airflow/issues/24653)
- [ ] [Disable attrs state management on MappedOperator (#24772)](https://github.com/apache/airflow/pull/24772): @uranusjr @ashb
     Linked issues:
     - [AIP-45 breaks follow-on mini scheduler for mapped tasks (#23838)](https://github.com/apache/airflow/issues/23838)
- [ ] [Refactor DR.task_instance_scheduling_decisions (#24774)](https://github.com/apache/airflow/pull/24774): @uranusjr
- [x] [Add %z for %(asctime)s to fix timezone for logs on UI  (#24811)](https://github.com/apache/airflow/pull/24811): @rino0601 @freshlu11 @millin
     Linked issues:
     - [Revert "Add %z for %(asctime)s to fix timezone for logs on UI (#24373)" (#24810)](https://github.com/apache/airflow/pull/24810)
     - [Webserver shows wrong datetime (timezone) in log (#23796)](https://github.com/apache/airflow/issues/23796)
     - [Add %z for %(asctime)s to fix timezone for logs on UI (#24373)](https://github.com/apache/airflow/pull/24373)
     - [Improve ElasticsearchTaskHandler (#21942)](https://github.com/apache/airflow/pull/21942)
- [ ] [Bind log server on worker to IPv6 address (#24755) (#24846)](https://github.com/apache/airflow/pull/24846): @zartstrom
     Linked issues:
     - [Log server on celery worker does not work in IPv6-only setup (#24755)](https://github.com/apache/airflow/issues/24755)
- [x] [Upgrade FAB to 4.1.3 (#24884)](https://github.com/apache/airflow/pull/24884): @gmsantos
- [ ] [Fix zombie task handling with multiple schedulers (#24906)](https://github.com/apache/airflow/pull/24906): @jedcunningham
- [ ] [Fix tag link on dag detail page when setting base_url with url prefix (#24918)](https://github.com/apache/airflow/pull/24918): @xianghuzhao
- [ ] [Added exception catching to send default email if template file raises any exception (#24943)](https://github.com/apache/airflow/pull/24943): @ecodina
     Linked issues:
     - [Send default email if file "html_content_template" not found (#24919)](https://github.com/apache/airflow/issues/24919)
- [ ] [Extends resolve_xcom_backend function level documentation (#24965)](https://github.com/apache/airflow/pull/24965): @frankcash
- [x] [Limit astroid version to < 2.12 (#24982)](https://github.com/apache/airflow/pull/24982): @potiuk
- [ ] [Sort operator extra links (#24992)](https://github.com/apache/airflow/pull/24992): @hterik
- [ ] [set default task group in dag.add_task method (#25000)](https://github.com/apache/airflow/pull/25000): @rahulgoyal2987 @blcksrx
     Linked issues:
     - [Airflow doesn't set default task group while calling dag.add_tasks (#24996)](https://github.com/apache/airflow/issues/24996)
- [ ] [fix: change disable_verify_ssl behaviour (#25023)](https://github.com/apache/airflow/pull/25023): @wselfjes
- [ ] [No grid auto-refresh for backfill dag runs (#25042)](https://github.com/apache/airflow/pull/25042): @yingxuanwangxuan
     Linked issues:
     - [grid_data api keep refreshing  when backfill DAG runs (#24844)](https://github.com/apache/airflow/issues/24844)
- [ ] [airflow/www/package.json: Add name, version fields. (#25065)](https://github.com/apache/airflow/pull/25065): @tm-drtina @jsoo1
     Linked issues:
     - [Invalid `package.json` file in `airflow/www` (#25007)](https://github.com/apache/airflow/issues/25007)
- [ ] [Bump typing-extensions and mypy for ParamSpec (#25088)](https://github.com/apache/airflow/pull/25088): @uranusjr
- [x] [Fix invalidateQueries call (#25097)](https://github.com/apache/airflow/pull/25097): @pierrejeambrun
- [ ] [Stop SLA callbacks gazumping other callbacks and DOS'ing the DagProcessorManager queue (#25147)](https://github.com/apache/airflow/pull/25147): @argibbs
     Linked issues:
     - [Using SLAs causes DagFileProcessorManager timeouts and prevents deleted dags from being recreated (#15596)](https://github.com/apache/airflow/issues/15596)
- [x] [Move javascript compilation to host (#25169)](https://github.com/apache/airflow/pull/25169): @potiuk
- [ ] [Include missing mention of `external_executor_id` in docstring (#25197)](https://github.com/apache/airflow/pull/25197): @michaelosthege
- [ ] [Graph view: Update labels after expanding groups (#25217)](https://github.com/apache/airflow/pull/25217): @bbovenzi
- [ ] [Convert TimeSensorAsync target_time to utc on call time (#25221)](https://github.com/apache/airflow/pull/25221): @Gollum999 @gitstart-airflow
     Linked issues:
     - [TimeSensorAsync breaks if target_time is timezone-aware (#24736)](https://github.com/apache/airflow/issues/24736)
- [x] [Only load distribution of a name once (#25296)](https://github.com/apache/airflow/pull/25296): @rino0601 @uranusjr
     Linked issues:
     - [Version 2.3.3 breaks "Plugins as Python packages" feature (#25271)](https://github.com/apache/airflow/issues/25271)
- [x] [Add __repr__ to ParamsDict class (#25305)](https://github.com/apache/airflow/pull/25305): @hwooson12 @msumit
     Linked issues:
     - [ParamsDict represents the class object itself, not keys and values on Task Instance Details (#25295)](https://github.com/apache/airflow/issues/25295)
- [ ] [Don't mistakenly take a lock on DagRun via ti.refresh_from_fb (#25312)](https://github.com/apache/airflow/pull/25312): @ashb
- [ ] [BashOperator - resolve bash by absolute path (#25331)](https://github.com/apache/airflow/pull/25331): @MatrixManAtYrService
- [x] [Remove useless logging line (#25347)](https://github.com/apache/airflow/pull/25347): @Jorricks
- [ ] [Removed interfering force of index. (#25404)](https://github.com/apache/airflow/pull/25404): @dene14
- [ ] [Fix `airflow db reset` when dangling tables exist (#25441)](https://github.com/apache/airflow/pull/25441): @ashb
- [ ] [Fix Serialization error in TaskCallbackRequest (#25471)](https://github.com/apache/airflow/pull/25471): @ephraimbuddy
- [x] [Limit Flask to <2.3 in the wake of 2.2 breaking our tests (#25511)](https://github.com/apache/airflow/pull/25511): @potiuk
- [ ] [Fix reducing mapped length of a mapped task at runtime after a clear (#25531)](https://github.com/apache/airflow/pull/25531): @ephraimbuddy
- [ ] [Fix "This Session's transaction has been rolled back" (#25532)](https://github.com/apache/airflow/pull/25532): @ephraimbuddy
- [ ] [Allow wildcarded CORS origins (#25553)](https://github.com/apache/airflow/pull/25553): @Csaki95 @norm
     Linked issues:
     - [CORS access_control_allow_origin header never returned (#20110)](https://github.com/apache/airflow/issues/20110)
- [x] [Fix Grid task row scrollbar overlapping on Firefox (#25554)](https://github.com/apache/airflow/pull/25554): @pierrejeambrun
- [x] [Cache the custom secrets backend so the same instance gets re-used (#25556)](https://github.com/apache/airflow/pull/25556): @pdebelak
     Linked issues:
     - [Airflow doesn't re-use a secrets backend instance when loading configuration values (#25555)](https://github.com/apache/airflow/issues/25555)
- [x] [Move the old ./breeze script to scripts/tools/setup_breeze (#25584)](https://github.com/apache/airflow/pull/25584): @potiuk
- [ ] [Fix the errors raised when None is passed to template filters (#25593)](https://github.com/apache/airflow/pull/25593): @kianelbo @TamGB
     Linked issues:
     - [Macro prev_execution_date is always empty (#24678)](https://github.com/apache/airflow/issues/24678)
- [ ] [Fix mapped sensor with reschedule mode (#25594)](https://github.com/apache/airflow/pull/25594): @ephraimbuddy
- [ ] [Configurable umask to all deamonized processes. (#25664)](https://github.com/apache/airflow/pull/25664): @ashb
- [ ] [Adding mysql index hint to use index on task_instance.state in critical section query (#25673)](https://github.com/apache/airflow/pull/25673): @michaelmicheal
     Linked issues:
     - [MySQL Not Using Correct Index for Scheduler Critical Section Query (#25627)](https://github.com/apache/airflow/issues/25627)
- [x] [Bump cattrs version (#25689)](https://github.com/apache/airflow/pull/25689): @arminnajafi @tomsej
     Linked issues:
     - [Airflow pinning old version of attrs: apache-airflow (>=2.3.2,<3.0.0) requires attrs (>=20.0,<21.0) (#24421)](https://github.com/apache/airflow/issues/24421)
- [ ] [Two typing fixes (#25690)](https://github.com/apache/airflow/pull/25690): @uranusjr
- [x] [Remove depreciation warning when use default remote tasks logging handlers (#25764)](https://github.com/apache/airflow/pull/25764): @mschweder @uranusjr @Taragolis
     Linked issues:
     - [Apply per-run log templates to log handlers (#24153)](https://github.com/apache/airflow/pull/24153)
     - [DeprecationWarning: Passing filename_template to FileTaskHandler is deprecated and has no effect (#25743)](https://github.com/apache/airflow/issues/25743)
- [ ] [Rotate session id during login (#25771)](https://github.com/apache/airflow/pull/25771): @jedcunningham

Thanks to all who contributed to the release (probably not a complete list!):
@iasoon @xianghuzhao @gitstart-airflow @hterik @Gollum999 @rahulgoyal2987 @Jorricks @michaelosthege @jsoo1 @freshlu11 @dene14 @arminnajafi @potiuk @norm @hwooson12 @frankcash @bbovenzi @dstandish @tanelk @gmsantos @ephraimbuddy @kianelbo @uranusjr @consciencee @MatrixManAtYrService @mschweder @Csaki95 @millin @rino0601 @michaelmicheal @pdebelak @msumit @TamGB @blcksrx @pierrejeambrun @zartstrom @Taragolis @vinit-tribes @RNHTTR @yingxuanwangxuan @jedcunningham @ecodina @wselfjes @krcrouse @argibbs @ashb @tomsej @tm-drtina

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by Taragolis** [comment]
https://github.com/apache/airflow/pull/25764 Check on AWS S3 and AWS Cloudwatch handlers no warnings anymore

**Comment by tomsej** [comment]
https://github.com/apache/airflow/pull/25689 LGTM

**Comment by pierrejeambrun** [comment]
https://github.com/apache/airflow/pull/25554 working as expected :+1: 
https://github.com/apache/airflow/pull/25097 not much to test on this one.

**Comment by potiuk** [comment]
All good:

#24982 - correct limits
#25169 - assets are properly compiled in the package
#25511 -  flask correctly limited
#25584 - irrelevant

**Comment by Jorricks** [comment]
All good:

#25347 <https://github.com/apache/airflow/pull/25347> - Logging message is
no longer excessively present when you remove a task.

Op za 20 aug. 2022 om 16:18 schreef Jarek Potiuk ***@***.***>:

**Comment by rino0601** [comment]
#25296 working as expected 👍 2.3.4rc1 able to import Plugins as Python packages
#24811 working as expected 👍 2.3.4rc1  use ISO 8601 format in task log

**Comment by consciencee** [comment]
#24676 working as expected, no any serialization issues anymore

**Comment by hwooson12** [comment]
#25305 LGTM

**Comment by raphaelauv** [comment]
Global test look good
![Screenshot from 2022-08-22 08-42-35](https://user-images.githubusercontent.com/10202690/185855741-26d63362-a11a-4ce0-9714-5fb09f8a0abf.png)

**Comment by gmsantos** [comment]
#24884 LGTM

**Comment by pdebelak** [comment]
#25556 appears to be working as expected

**Comment by ephraimbuddy** [comment]
Airflow 2.3.4 is now released. Thank you all for testing this release candidate
