### ISSUE TITLE
Status of testing Providers that were prepared on September 05, 2022

### ISSUE THREAD

**Issue by ashb** [apache/airflow#26164]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 5.1.0rc1](https://pypi.org/project/apache-airflow-providers-amazon/5.1.0rc1)
   - [x] [Additional mask AWS Credentials (#26014)](https://github.com/apache/airflow/pull/26014): @Taragolis
   - [x] [Add RedshiftDeleteClusterSnapshotOperator (#25975)](https://github.com/apache/airflow/pull/25975): @pankajastro
   - [x] [Add redshift create cluster snapshot operator (#25857)](https://github.com/apache/airflow/pull/25857): @pankajastro
   - [x] [Add common-sql lower bound for common-sql (#25789)](https://github.com/apache/airflow/pull/25789): @potiuk
   - [ ] [Allow AWS Secrets Backends use AWS Connection capabilities (#25628)](https://github.com/apache/airflow/pull/25628): @Taragolis
   - [x] [Implement `EmrEksCreateClusterOperator` (#25816)](https://github.com/apache/airflow/pull/25816): @phanikumv
   - [ ] [Improve error handling/messaging around bucket exist check (#25805)](https://github.com/apache/airflow/pull/25805): @o-nikolas
   - [x] [Fix display aws connection info (#26025)](https://github.com/apache/airflow/pull/26025): @Taragolis
   - [x] [Fix `EcsBaseOperator` and `EcsBaseSensor` arguments (#25989)](https://github.com/apache/airflow/pull/25989): @Taragolis
   - [ ] [Fix RDS system test (#25839)](https://github.com/apache/airflow/pull/25839): @vincbeck
   - [x] [Avoid circular import problems when instantiating AWS SM backend (#25810)](https://github.com/apache/airflow/pull/25810): @Taragolis
   - [x] [Fix construction of Connection object in version Amazon provider 5.0.0rc3 (#25716)](https://github.com/apache/airflow/pull/25716): @dwreeves
## Provider [common.sql: 1.2.0rc1](https://pypi.org/project/apache-airflow-providers-common-sql/1.2.0rc1)
   - [ ] [Fix placeholders in `TrinoHook`, `PrestoHook`, `SqliteHook` (#25939)](https://github.com/apache/airflow/pull/25939): @alexandermalyga
   - [x] [Better error messsage for pre-common-sql providers (#26051)](https://github.com/apache/airflow/pull/26051): @potiuk
   - [x] [Fix (and test) SQLTableCheckOperator on postgresql (#25821)](https://github.com/apache/airflow/pull/25821): @ashb
   - [x] [Don&#39;t use Pandas for SQLTableCheckOperator (#25822)](https://github.com/apache/airflow/pull/25822): @ashb
   - [x] [Discard semicolon stripping in SQL hook (#25855)](https://github.com/apache/airflow/pull/25855): @kazanzhy
## Provider [postgres: 5.2.1rc1](https://pypi.org/project/apache-airflow-providers-postgres/5.2.1rc1)
   - [x] [Bump dep on common-sql to fix issue with SQLTableCheckOperator (#26143)](https://github.com/apache/airflow/pull/26143): @ashb
## Provider [presto: 4.0.1rc1](https://pypi.org/project/apache-airflow-providers-presto/4.0.1rc1)
   - [x] [Add common-sql lower bound for common-sql (#25789)](https://github.com/apache/airflow/pull/25789): @potiuk
   - [ ] [Fix placeholders in `TrinoHook`, `PrestoHook`, `SqliteHook` (#25939)](https://github.com/apache/airflow/pull/25939): @alexandermalyga
## Provider [sqlite: 3.2.1rc1](https://pypi.org/project/apache-airflow-providers-sqlite/3.2.1rc1)
   - [x] [Add common-sql lower bound for common-sql (#25789)](https://github.com/apache/airflow/pull/25789): @potiuk
   - [ ] [Fix placeholders in `TrinoHook`, `PrestoHook`, `SqliteHook` (#25939)](https://github.com/apache/airflow/pull/25939): @alexandermalyga
## Provider [trino: 4.0.1rc1](https://pypi.org/project/apache-airflow-providers-trino/4.0.1rc1)
   - [x] [Add common-sql lower bound for common-sql (#25789)](https://github.com/apache/airflow/pull/25789): @potiuk
   - [ ] [Fix placeholders in `TrinoHook`, `PrestoHook`, `SqliteHook` (#25939)](https://github.com/apache/airflow/pull/25939): @alexandermalyga

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-by-contributors)

All users involved in the PRs:
@pankajastro @potiuk @dwreeves @Taragolis @vincbeck @kazanzhy @ashb @phanikumv @o-nikolas @alexandermalyga

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by dwreeves** [comment]
My PR #25716 came about from testing for the Amazon provider package `5.0.0` and is a very simple 1-line change. (It was a PR for fixing a minor bug in `5.0.0rc3` from when I was testing that.) It does seem like it unfortunately made its way into the `5.0.0` release, hence why it's part of the `5.1.0` release cycle.

<img width="556" alt="image" src="https://user-images.githubusercontent.com/31971762/188485403-72ce9a83-d7ec-4c54-a13d-f3b4a2abdbc7.png">

Previous issue when my testing uncovered it: https://github.com/apache/airflow/issues/25640#issuecomment-1214247486

So I think you can ✔️ me?

**Comment by ashb** [comment]
@dwreeves thanks - the list was auto generated. Was your change in 5.0.0 of the provider do you know?

**Comment by Taragolis** [comment]
#25810 - No more circular import issue
#25989, #26014, #26025 - Work as expected

**Comment by eladkal** [comment]
> @dwreeves thanks - the list was auto generated. Was your change in 5.0.0 of the provider do you know?

I dont think it was.
Amazon provider 5.0.0 was releases on 14-Aug
https://github.com/apache/airflow/pull/25716 was merged on 15-Aug
The code with the amazon provider 5.0.0 tag doesnt have the changes in the PR:

https://github.com/apache/airflow/blob/5923788143e7871b56de5164b96a407b2fba75b8/airflow/providers/amazon/aws/secrets/secrets_manager.py#L200

**Comment by potiuk** [comment]
Common.sql lower-bounds are updated for those providers.

**Comment by kazanzhy** [comment]
Checked https://github.com/apache/airflow/pull/25855 with PostgresHook. Seems ok.

**Comment by dwreeves** [comment]
(Yeah sorry I wasn't clear with how I phrased that. "It made its way in" <-- "it" meaning the bug, not the fix for said bug.)

**Comment by potiuk** [comment]
> Tested #25816 , it is working good.

What an interesting set of colours. I wonder if they mean something :)

**Comment by pankajastro** [comment]
Worked as expected https://github.com/apache/airflow/pull/25857 and https://github.com/apache/airflow/pull/25975

**Comment by alexandermalyga** [comment]
Tested #25939 with Trino, Presto and SQLite hooks. The issue has been solved and it works like expected.

**Comment by ashb** [comment]
Releasing now.
