### ISSUE TITLE
Status of testing of Apache Airflow 2.4.2rc1

### ISSUE THREAD

**Issue by ephraimbuddy** [apache/airflow#27161]
### Body

We have a kind request for all the contributors to the latest [Apache Airflow RC 2.4.2rc1](https://pypi.org/project/apache-airflow/2.4.2rc1/).

Could you please help us to test the RC versions of Airflow?

Please let us know in the comment if the issue is addressed in the latest RC.

- [ ] [Retry on Airflow Schedule DAG Run DB Deadlock (#26347)](https://github.com/apache/airflow/pull/26347): @anthonyp97
- [x] [Bump FAB to 4.1.4 (#26393)](https://github.com/apache/airflow/pull/26393): @gmsantos
- [ ] [Revert "No grid auto-refresh for backfill dag runs (#25042)" (#26463)](https://github.com/apache/airflow/pull/26463): @yingxuanwangxuan @Gollum999
     Linked issues:
     - [grid_data api keep refreshing  when backfill DAG runs (#24844)](https://github.com/apache/airflow/issues/24844)
- [ ] [Fix version for a couple configurations (#26491)](https://github.com/apache/airflow/pull/26491): @jedcunningham
- [ ] [Fix airflow tasks run --local when dags_folder differs from that of processor (#26509)](https://github.com/apache/airflow/pull/26509): @dstandish
- [ ] [Simplify RTIF.delete_old_records() (#26667)](https://github.com/apache/airflow/pull/26667): @uranusjr @dstandish
     Linked issues:
     - [Resolve warning about renderedtifields query (#26548)](https://github.com/apache/airflow/issues/26548)
- [ ] [Remove TaskFail duplicates check (#26714)](https://github.com/apache/airflow/pull/26714): @dstandish
- [ ] [Fix non-hidden cumulative chart on duration view (#26716)](https://github.com/apache/airflow/pull/26716): @dstandish
- [ ] [Fix task duration cumulative chart (#26717)](https://github.com/apache/airflow/pull/26717): @dstandish
- [ ] [Handle mapped tasks in task duration chart (#26722)](https://github.com/apache/airflow/pull/26722): @dstandish
- [x] [Bump sphinx and sphinx-autoapi (#26743)](https://github.com/apache/airflow/pull/26743): @potiuk
- [ ] [Remove DAG parsing from StandardTaskRunner (#26750)](https://github.com/apache/airflow/pull/26750): @ephraimbuddy
- [ ] [Allow retrieving error message from data.detail (#26762)](https://github.com/apache/airflow/pull/26762): @pierrejeambrun
- [ ] [Add restarting state to TaskState Enum in REST API (#26776)](https://github.com/apache/airflow/pull/26776): @ephraimbuddy
- [ ] [Don't re-patch pods that are already controlled by current worker (#26778)](https://github.com/apache/airflow/pull/26778): @hterik
- [ ] [Ensure the log messages from operators during parsing go somewhere (#26779)](https://github.com/apache/airflow/pull/26779): @emredjan @ashb
     Linked issues:
     - ["Dependency already registered for DAG" warnings during runs in taskflow based tasks (#26599)](https://github.com/apache/airflow/issues/26599)
- [ ] [Add legend to datasets graph (#26781)](https://github.com/apache/airflow/pull/26781): @bbovenzi
- [ ] [demote Removed state in priority for displaying task summaries (#26789)](https://github.com/apache/airflow/pull/26789): @bbovenzi
- [ ] [Fix warning when using xcomarg dependencies (#26801)](https://github.com/apache/airflow/pull/26801): @ashb
- [ ] [Fix running debuggers inside `airflow tasks test` (#26806)](https://github.com/apache/airflow/pull/26806): @ashb
     Linked issues:
     - [pdb no longer works with airflow test command since 2.3.3 (#26802)](https://github.com/apache/airflow/issues/26802)
- [x] [Move user-facing string to template (#26815)](https://github.com/apache/airflow/pull/26815): @blag
- [x] [Add missing colors to state_color_mapping jinja global (#26822)](https://github.com/apache/airflow/pull/26822): @pierrejeambrun
- [ ] [Bump min version of jinja2 (#26866)](https://github.com/apache/airflow/pull/26866): @jedcunningham
- [ ] [Clean-ups around task-mapping code (#26879)](https://github.com/apache/airflow/pull/26879): @uranusjr
- [x] [Add separate error handler for 405(Method not allowed) errors (#26880)](https://github.com/apache/airflow/pull/26880): @PadmajaPeri @dakshin-k
     Linked issues:
     - [Airflow Webserver returns incorrect HTTP Error Response for custom REST API endpoints  (#26375)](https://github.com/apache/airflow/issues/26375)
- [ ] [Add missing AUTOINC/SERIAL for FAB tables (#26885)](https://github.com/apache/airflow/pull/26885): @ashb
- [ ] [Change dag audit log sort by date from asc to desc (#26895)](https://github.com/apache/airflow/pull/26895): @bbovenzi
- [ ] [Fix dataset-triggered next run modal links (#26897)](https://github.com/apache/airflow/pull/26897): @bbovenzi
- [x] [Fix auto refresh for graph view (#26926)](https://github.com/apache/airflow/pull/26926): @pierrejeambrun
- [ ] [Remove double collection of dags in `airflow dags reserialize`  (#27030)](https://github.com/apache/airflow/pull/27030): @ephraimbuddy
- [ ] [Filter dataset dependency data on webserver (#27046)](https://github.com/apache/airflow/pull/27046): @bbovenzi
- [ ] [Make tracebacks opt-in (#27059)](https://github.com/apache/airflow/pull/27059): @jedcunningham
- [ ] [Avoid 500 on dag redirect (#27064)](https://github.com/apache/airflow/pull/27064): @jedcunningham
- [ ] [Fix yarn warning from d3-color (#27139)](https://github.com/apache/airflow/pull/27139): @bbovenzi
- [ ] [Don't overwrite connection extra with invalid json (#27142)](https://github.com/apache/airflow/pull/27142): @jedcunningham
- [ ] [Simplify origin string cleaning (#27143)](https://github.com/apache/airflow/pull/27143): @jedcunningham

Thanks to all who contributed to the release (probably not a complete list!):
@dstandish @yingxuanwangxuan @gmsantos @hterik @blag @ashb @pierrejeambrun @uranusjr @bbovenzi @jedcunningham @anthonyp97 @dakshin-k @potiuk @PadmajaPeri @emredjan @ephraimbuddy @Gollum999

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by pierrejeambrun** [comment]
Hello all,

I tested #26822 and #26926.  Working as expected :+1:

To test #26762 we need an error from an `api_connexion` endpoint called from the `Grid` UI. (The toast should be properly displayed for ProblemException response). Unfortunately I wasn't able to test that. This is a really minor fix.

**Comment by raphaelauv** [comment]
2.4.2rc1 working well with "major" operators

![Screenshot from 2022-10-21 15-20-12](https://user-images.githubusercontent.com/10202690/197205571-f3251786-ce27-4172-b53d-e15293988dbf.png)

**Comment by gmsantos** [comment]
All good from #26393

[Airflow constraints](https://github.com/apache/airflow/blob/constraints-2-4/constraints-3.10.txt) were updated as expected.

**Comment by blag** [comment]
All good from #26815. :+1:

**Comment by dakshin-k** [comment]
#26880 looks good!

**Comment by ephraimbuddy** [comment]
Airflow 2.4.2 has been released! Thank you all for testing this release.
