### ISSUE TITLE
Status of testing of Apache Airflow 2.4.3rc1

### ISSUE THREAD

**Issue by ephraimbuddy** [apache/airflow#27618]
### Body

We have a kind request for all the contributors to the latest [Apache Airflow RC 2.4.3rc1](https://pypi.org/project/apache-airflow/2.4.3rc1/).

Could you please help us to test the RC versions of Airflow?

Please let us know in the comment if the issue is addressed in the latest RC.

- [ ] [Reduce log level for k8s TCP_KEEPALIVE etc warnings (#26981)](https://github.com/apache/airflow/pull/26981): @dstandish
- [ ] [set executor.job_id to BackfillJob.id for backfills (#27020)](https://github.com/apache/airflow/pull/27020): @RNHTTR
- [ ] [Fix some bug in web ui dags list page (auto-refresh & jump search null state) (#27141)](https://github.com/apache/airflow/pull/27141): @chenglongyan @talnagar @BobDu
     Linked issues:
     - [Support Is /not Null filter for value is None on webui (#26584)](https://github.com/apache/airflow/pull/26584)
     - [add auto refresh to dags home page (#22900)](https://github.com/apache/airflow/pull/22900)
- [ ] [Listener: Set task on sqlalchemy taskinstance object (#27167)](https://github.com/apache/airflow/pull/27167): @kaxil
- [x] [Make RotatingFilehandler used in DagProcessor non-caching (#27223)](https://github.com/apache/airflow/pull/27223): @potiuk @zachliu
     Linked issues:
     - [Log files are still being cached causing ever-growing memory usage when scheduler is running (#27065)](https://github.com/apache/airflow/issues/27065)
     - [Advises the kernel to not cache log files generated by Airflow (#18054)](https://github.com/apache/airflow/pull/18054)
- [ ] [Reduce extraneous task log requests (#27233)](https://github.com/apache/airflow/pull/27233): @hterik @bbovenzi
     Linked issues:
     - [Log-tab under grid view is automatically re-fetching completed logs every 3 sec. (#26912)](https://github.com/apache/airflow/issues/26912)
- [ ] [Fix python external template keys (#27256)](https://github.com/apache/airflow/pull/27256): @enisnazif
     Linked issues:
     - [ExternalPythonOperator: AttributeError: 'python_path' is configured as a template field but ExternalPythonOperator does not have this attribute. (#27232)](https://github.com/apache/airflow/issues/27232)
- [ ] [Add case insensitive constraint to username (#27266)](https://github.com/apache/airflow/pull/27266): @ephraimbuddy
- [x] [Fix IntegrityError during webserver startup (#27297)](https://github.com/apache/airflow/pull/27297): @ephraimbuddy
- [ ] [SLAMiss is nullable and not always given back when pulling task instances (#27423)](https://github.com/apache/airflow/pull/27423): @csm10495
- [ ] [Fix behavior of `_` when searching for DAGs (#27448)](https://github.com/apache/airflow/pull/27448): @jedcunningham
- [x] [Fix mini scheduler expansion of mapped task  (#27506)](https://github.com/apache/airflow/pull/27506): @ephraimbuddy
- [x] [Fix sqlalchemy primary key black-out error on DDRQ (#27538)](https://github.com/apache/airflow/pull/27538): @ephraimbuddy
- [ ] [Fix getting the dag/task ids from base executor (#27550)](https://github.com/apache/airflow/pull/27550): @potiuk @jordanjeremy
     Linked issues:
     - [Add parsing context to DAG Parsing  (#25161)](https://github.com/apache/airflow/pull/25161)
- [ ] [Bump loader-utils from 1.4.0 to 1.4.1 in /airflow/www (#27552)](https://github.com/apache/airflow/pull/27552): @dependabot[bot]
- [ ] [Replace FAB url filtering function with Airflows (#27576)](https://github.com/apache/airflow/pull/27576): @jedcunningham
- [ ] [Fix double logging with some task logging handler (#27591)](https://github.com/apache/airflow/pull/27591): @ashb

Thanks to all who contributed to the release (probably not a complete list!):
@ephraimbuddy @chenglongyan @potiuk @dstandish @ashb @bbovenzi @BobDu @jordanjeremy @zachliu @kaxil @dependabot[bot] @hterik @RNHTTR @jedcunningham @enisnazif @talnagar @csm10495

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
Checked #27223

**Comment by ephraimbuddy** [comment]
Thanks @potiuk for testing 👍
