### ISSUE TITLE
Status of testing Providers that were prepared on November 26, 2022

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#27939]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 6.2.0rc3](https://pypi.org/project/apache-airflow-providers-amazon/6.2.0rc3)
   - [ ] [Use Boto waiters instead of customer _await_status method for RDS Operators (#27410)](https://github.com/apache/airflow/pull/27410): @hankehly
   - [x] [Handle transient state errors in `RedshiftResumeClusterOperator` and `RedshiftPauseClusterOperator` (#27276)](https://github.com/apache/airflow/pull/27276): @syedahsn
   - [ ] [Add retry option in RedshiftDeleteClusterOperator to retry when an operation is running in the cluster (#27820)](https://github.com/apache/airflow/pull/27820): @vincbeck
   - [ ] [Correct job name matching in SagemakerProcessingOperator (#27634)](https://github.com/apache/airflow/pull/27634): @ferruzzi
## Provider [asana: 2.1.0rc3](https://pypi.org/project/apache-airflow-providers-asana/2.1.0rc3)
   - [x] [Move min airflow version to 2.3.0 for all providers (#27196)](https://github.com/apache/airflow/pull/27196): @potiuk
   - [ ] [Allow and prefer non-prefixed extra fields for AsanaHook (#27043)](https://github.com/apache/airflow/pull/27043): @dstandish
## Provider [common.sql: 1.3.1rc3](https://pypi.org/project/apache-airflow-providers-common-sql/1.3.1rc3)
   - [x] [Restore removed (but used) methods in common.sql (#27843)](https://github.com/apache/airflow/pull/27843): @potiuk
   - [ ] [Fix errors in Databricks SQL operator introduced when refactoring (#27854)](https://github.com/apache/airflow/pull/27854): @potiuk
   - [ ] [Fixing the behaviours of SQL Hooks and Operators finally (#27912)](https://github.com/apache/airflow/pull/27912): @potiuk
## Provider [databricks: 4.0.0rc3](https://pypi.org/project/apache-airflow-providers-databricks/4.0.0rc3)
   - [x] [Fix errors in Databricks SQL operator introduced when refactoring (#27854)](https://github.com/apache/airflow/pull/27854): @potiuk
   - [x] [Fix templating fields and do_xcom_push in DatabricksSQLOperator (#27868)](https://github.com/apache/airflow/pull/27868): @potiuk
   - [x] [Fixing the behaviours of SQL Hooks and Operators finally (#27912)](https://github.com/apache/airflow/pull/27912): @potiuk
## Provider [exasol: 4.1.1rc3](https://pypi.org/project/apache-airflow-providers-exasol/4.1.1rc3)
   - [x] [Fix errors in Databricks SQL operator introduced when refactoring (#27854)](https://github.com/apache/airflow/pull/27854): @potiuk
   - [ ] [Fixing the behaviours of SQL Hooks and Operators finally (#27912)](https://github.com/apache/airflow/pull/27912): @potiuk
## Provider [google: 8.6.0rc3](https://pypi.org/project/apache-airflow-providers-google/8.6.0rc3)
   - [x] [Persist DataprocLink for workflow operators regardless of job status (#26986)](https://github.com/apache/airflow/pull/26986): @vksunilk
   - [ ] [Deferrable mode for BigQueryToGCSOperator (#27683)](https://github.com/apache/airflow/pull/27683): @lwyszomi
   - [x] [Add Export Format to Template Fields in BigQueryToGCSOperator (#27910)](https://github.com/apache/airflow/pull/27910): @vksunilk
   - [ ] [Fix to read location parameter properly in BigQueryToBigQueryOperator (#27661)](https://github.com/apache/airflow/pull/27661): @VladaZakharova
## Provider [jdbc: 3.3.0rc3](https://pypi.org/project/apache-airflow-providers-jdbc/3.3.0rc3)
   - [x] [Move min airflow version to 2.3.0 for all providers (#27196)](https://github.com/apache/airflow/pull/27196): @potiuk
   - [ ] [Allow and prefer non-prefixed extra fields for JdbcHook (#27044)](https://github.com/apache/airflow/pull/27044): @dstandish
   - [x] [Add SQLExecuteQueryOperator (#25717)](https://github.com/apache/airflow/pull/25717): @kazanzhy
## Provider [mysql: 3.4.0rc3](https://pypi.org/project/apache-airflow-providers-mysql/3.4.0rc3)
   - [ ] [Allow SSL mode in MySQL provider (#27717)](https://github.com/apache/airflow/pull/27717): @Adityamalik123
## Provider [neo4j: 3.2.1rc3](https://pypi.org/project/apache-airflow-providers-neo4j/3.2.1rc3)
   - [x] [Fix typing problem revealed after recent Neo4J release (#27759)](https://github.com/apache/airflow/pull/27759): @potiuk
## Provider [presto: 4.2.0rc3](https://pypi.org/project/apache-airflow-providers-presto/4.2.0rc3)
   - [x] [Add _serialize_cell method to TrinoHook and PrestoHook (#27724)](https://github.com/apache/airflow/pull/27724): @alexandermalyga
## Provider [slack: 7.1.0rc3](https://pypi.org/project/apache-airflow-providers-slack/7.1.0rc3)
   - [x] [Implements SqlToSlackApiFileOperator (#26374)](https://github.com/apache/airflow/pull/26374): @Taragolis
## Provider [snowflake: 4.0.1rc3](https://pypi.org/project/apache-airflow-providers-snowflake/4.0.1rc3)
   - [x] [Fix errors in Databricks SQL operator introduced when refactoring (#27854)](https://github.com/apache/airflow/pull/27854): @potiuk
   - [ ] [Fixing the behaviours of SQL Hooks and Operators finally (#27912)](https://github.com/apache/airflow/pull/27912): @potiuk
## Provider [trino: 4.3.0rc3](https://pypi.org/project/apache-airflow-providers-trino/4.3.0rc3)
   - [x] [Add _serialize_cell method to TrinoHook and PrestoHook (#27724)](https://github.com/apache/airflow/pull/27724): @alexandermalyga
## Provider [yandex: 3.2.0rc3](https://pypi.org/project/apache-airflow-providers-yandex/3.2.0rc3)
   - [x] [Move min airflow version to 2.3.0 for all providers (#27196)](https://github.com/apache/airflow/pull/27196): @potiuk

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-by-contributors)

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
Hey everyone. The RC3 is there (email to devlist shortly) - I moved the status of testing from #27894.

I'd highly appreciate if the new comon.sql provider is tested with the various sql packages (and if someone could test it also with older versions of providers :)

**Comment by alexott** [comment]
Tested Databricks operator: normal queries, and writing files works as before. Thank you @potiuk for fixing it

**Comment by vksunilk** [comment]
Tested #26986 and #27910. Both are working fine.

**Comment by kazanzhy** [comment]
I tested https://github.com/apache/airflow/pull/25717 for Postgres and MySQL connections.
Works as expected 

![Screenshot from 2022-11-28 01-41-40](https://user-images.githubusercontent.com/10523218/204166092-d1d10b43-02e5-4c90-9e58-d94fcfe7dc8c.png)

**Comment by potiuk** [comment]
> I tested #25717 for Postgres and MySQL connections. Works as expected

Cool. Glad you are here. I hope all is good in the circumstances. And at the very least you might be happy with what the latest common.sql improvements with a miriad of tests are :)

**Comment by potiuk** [comment]
Thanks for testing. The RC3 wave is released now!
