### ISSUE TITLE
Status of testing Providers that were prepared on December 01, 2022

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#28036]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [exasol: 4.1.2rc1](https://pypi.org/project/apache-airflow-providers-exasol/4.1.2rc1)
   - [ ] [Update Exasol to common DBApiHook semantics and add tests (#28009)](https://github.com/apache/airflow/pull/28009): @potiuk
   - [ ] [Fix wrapping of run() method result of exasol and snoflake DB hooks (#27997)](https://github.com/apache/airflow/pull/27997): @potiuk
## Provider [snowflake: 4.0.2rc1](https://pypi.org/project/apache-airflow-providers-snowflake/4.0.2rc1)
   - [x] [Fix wrapping of run() method result of exasol and snoflake DB hooks (#27997)](https://github.com/apache/airflow/pull/27997): @potiuk
   - [x] [Make Snowflake Hook conform to semantics of DBApi (#28006)](https://github.com/apache/airflow/pull/28006): @potiuk
## Provider [zendesk: 4.2.0rc1](https://pypi.org/project/apache-airflow-providers-zendesk/4.2.0rc1)
   - [ ] [Add Zendesk connection type (#27984)](https://github.com/apache/airflow/pull/27984): @magdagultekin

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-by-contributors)

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
# 27997 #28006 checked by @park-peter https://github.com/apache/airflow/issues/27978#issuecomment-1334408599

**Comment by mag3141592** [comment]
#27976 resolved by 4.0.2rc1

**Comment by potiuk** [comment]
The release is OUT ! .... Enjoy everyone. It was a bit of a ride to get the common.sql refactoring and "commonalistation" and hopefuly it's behind us.
