### ISSUE TITLE
Status of testing Providers that were prepared on December 14, 2022

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#28349]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [apache.hive: 5.0.0rc1](https://pypi.org/project/apache-airflow-providers-apache-hive/5.0.0rc1)
   - [x] [Move hive_cli_params to hook parameters (#28101)](https://github.com/apache/airflow/pull/28101): @potiuk
   - [x] [Improve filtering for invalid schemas in Hive hook (#27808)](https://github.com/apache/airflow/pull/27808): @PApostol
## Provider [microsoft.azure: 5.0.1rc1](https://pypi.org/project/apache-airflow-providers-microsoft-azure/5.0.1rc1)
   - [x] [Make arguments &#39;offset&#39; and &#39;length&#39; not required (#28234)](https://github.com/apache/airflow/pull/28234): @malthe

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-by-contributors)

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by malthe** [comment]
We’ve tested the Azure log patch in our system, works great.

ons. 14. dec. 2022 kl. 00.46 skrev eladkal ***@***.***>:

**Comment by PApostol** [comment]
Tested #27808, seems to work fine!

**Comment by PApostol** [comment]
> Tested #28101 (mainly by inspection and verifying that it is part of the release) - @PApostol - is it possible, you check the hive provider with a "real" hive installation :) ?
I had a go with 5.0.0rc1 for a bit, didn't notice any issues!

**Comment by eladkal** [comment]
providers releases. thank you everyone for testing!
