### ISSUE TITLE
Status of testing Providers that were prepared on January 02, 2023

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#28679]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 7.0.0rc2](https://pypi.org/project/apache-airflow-providers-amazon/7.0.0rc2)
   - [x] [Make pandas dependency optional for Amazon Provider (#28505)](https://github.com/apache/airflow/pull/28505): @potiuk
   - [ ] [AWS Secrets Manager Backend - major update (#27920)](https://github.com/apache/airflow/pull/27920): @dwreeves
   - [ ] [Add execution role parameter to AddStepsOperator (#28484)](https://github.com/apache/airflow/pull/28484): @syedahsn
   - [x] [Add AWS SageMaker operator to register a model's version (#28024)](https://github.com/apache/airflow/pull/28024): @vandonr-amz
   - [ ] [Add link for EMR Steps Sensor logs (#28180)](https://github.com/apache/airflow/pull/28180): @syedahsn
   - [x] [Add Amazon Elastic Container Registry (ECR) Hook (#28279)](https://github.com/apache/airflow/pull/28279): @Taragolis
   - [ ] [EMR Notebook operator (#28312)](https://github.com/apache/airflow/pull/28312): @syedahsn
   - [ ] [Create Lambda create operator and sensor (#28241)](https://github.com/apache/airflow/pull/28241): @vincbeck
   - [ ] [Better support for Boto Waiters (#28236)](https://github.com/apache/airflow/pull/28236): @ferruzzi
   - [ ] [Amazon Provider Package user agent (#27823)](https://github.com/apache/airflow/pull/27823): @ferruzzi
   - [ ] [Allow waiter to be configured via EmrServerless Operators (#27784)](https://github.com/apache/airflow/pull/27784): @syedahsn
   - [x] [Add operators + sensor for aws sagemaker pipelines (#27786)](https://github.com/apache/airflow/pull/27786): @vandonr-amz
   - [x] [Update RdsHook docstrings to match code (#28108)](https://github.com/apache/airflow/pull/28108): @hankehly
   - [ ] [add some important log in aws athena hook (#27917)](https://github.com/apache/airflow/pull/27917): @BobDu
   - [ ] [Lambda hook: make runtime and handler optional (#27778)](https://github.com/apache/airflow/pull/27778): @vincbeck
   - [ ] [Fix EmrAddStepsOperature wait_for_completion parameter is not working (#28052)](https://github.com/apache/airflow/pull/28052): @2h-kim
   - [ ] [Correctly template Glue Jobs `create_job_kwargs` arg (#28403)](https://github.com/apache/airflow/pull/28403): @IAL32
   - [ ] [Fix template rendered bucket_key in S3KeySensor (#28340)](https://github.com/apache/airflow/pull/28340): @syun64
   - [ ] [Fix Type Error while using DynamoDBToS3Operator (#28158)](https://github.com/apache/airflow/pull/28158): @snjypl
   - [x] [AWSGlueJobHook updates job configuration if it exists (#27893)](https://github.com/apache/airflow/pull/27893): @romibuzi
   - [ ] [Fix GlueCrawlerOperature failure when using tags (#28005)](https://github.com/apache/airflow/pull/28005): @IAL32
   - [ ] [Fix S3KeySensor documentation (#28297)](https://github.com/apache/airflow/pull/28297): @IAL32
   - [x] [Improve docstring for `AwsLambdaInvokeFunctionOperator` (#28233)](https://github.com/apache/airflow/pull/28233): @eladkal
   - [x] [Remove outdated compat imports/code from providers (#28507)](https://github.com/apache/airflow/pull/28507): @Taragolis
   - [ ] [Amazon Provider Package release 7.0.0 - Add description of breaking changes (#28582)](https://github.com/apache/airflow/pull/28582): @dwreeves
   - [x] [[misc] Get rid of `pass` statement in conditions (#27775)](https://github.com/apache/airflow/pull/27775): @Taragolis
   - [x] [[misc] Replace XOR `^` conditions by `exactly_one` helper in providers (#27858)](https://github.com/apache/airflow/pull/27858): @Taragolis
## Provider [apache.hive: 5.1.0rc2](https://pypi.org/project/apache-airflow-providers-apache-hive/5.1.0rc2)
   - [x] [Move Hive macros to the provider (#28538)](https://github.com/apache/airflow/pull/28538): @potiuk
   - [x] [Make pandas dependency optional for Amazon Provider (#28505)](https://github.com/apache/airflow/pull/28505): @potiuk
## Provider [atlassian.jira: 2.0.0rc2](https://pypi.org/project/apache-airflow-providers-atlassian-jira/2.0.0rc2)
   - [ ] [Changing atlassian JIRA SDK to official atlassian-python-api SDK (#27633)](https://github.com/apache/airflow/pull/27633): @Adityamalik123
## Provider [cncf.kubernetes: 5.1.0rc2](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/5.1.0rc2)
   - [ ] [[Fixed] "Adding Flink on K8s Operator"  (#28512)](https://github.com/apache/airflow/pull/28512): @xinbinhuang
   - [ ] [Add volume-related nested template fields for KPO (#27719)](https://github.com/apache/airflow/pull/27719): @raphaelauv
   - [ ] [Allow longer pod names for k8s executor / KPO (#27736)](https://github.com/apache/airflow/pull/27736): @dstandish
   - [ ] [Use labels instead of pod name for pod log read in k8s exec (#28546)](https://github.com/apache/airflow/pull/28546): @dstandish
   - [ ] [Patch "checked" when pod not successful (#27845)](https://github.com/apache/airflow/pull/27845): @dstandish
   - [ ] [Keep pod name for k8s executor under 63 characters (#28237)](https://github.com/apache/airflow/pull/28237): @dstandish
   - [ ] [Remove outdated compat imports/code from providers (#28507)](https://github.com/apache/airflow/pull/28507): @Taragolis
   - [ ] [Restructure Docs  (#27235)](https://github.com/apache/airflow/pull/27235): @TohnJhomas
## Provider [common.sql: 1.3.2rc2](https://pypi.org/project/apache-airflow-providers-common-sql/1.3.2rc2)
   - [x] [Fix isort problems introduced by recent isort release (#28434)](https://github.com/apache/airflow/pull/28434): @potiuk
   - [ ] [Fix template rendering for Common SQL operators (#28202)](https://github.com/apache/airflow/pull/28202): @jon-evergreen
   - [ ] [Defer to hook setting for split_statements in SQLExecuteQueryOperator (#28635)](https://github.com/apache/airflow/pull/28635): @dstandish
   - [ ] [Clarify docstrings for updated DbApiHook (#27966)](https://github.com/apache/airflow/pull/27966): @dstandish
## Provider [docker: 3.4.0rc2](https://pypi.org/project/apache-airflow-providers-docker/3.4.0rc2)
   - [ ] [add hostname argument to DockerOperator (#27822)](https://github.com/apache/airflow/pull/27822): @skabbit
   - [x] [Move min airflow version down for Docker Provider to 2.3.0 (#28648)](https://github.com/apache/airflow/pull/28648): @potiuk
## Provider [elasticsearch: 4.3.2rc2](https://pypi.org/project/apache-airflow-providers-elasticsearch/4.3.2rc2)
   - [ ] [Support restricted index patterns in Elasticsearch log handler (#23888)](https://github.com/apache/airflow/pull/23888): @kouk
## Provider [ftp: 3.3.0rc2](https://pypi.org/project/apache-airflow-providers-ftp/3.3.0rc2)
   - [ ] [Add FTPSFileTransmitOperator (#28318)](https://github.com/apache/airflow/pull/28318): @RachitSharma2001
   - [ ] [Add `FTPFileTransmitOperator` (#26974)](https://github.com/apache/airflow/pull/26974): @RachitSharma2001
## Provider [google: 8.7.0rc2](https://pypi.org/project/apache-airflow-providers-google/8.7.0rc2)
   - [x] [Add table_resource to template fields for BigQueryCreateEmptyTableOperator (#28235)](https://github.com/apache/airflow/pull/28235): @jbandoro
   - [x] [Add retry param in GCSObjectExistenceSensor (#27943)](https://github.com/apache/airflow/pull/27943): @pankajastro
   - [ ] [Add preserveAsciiControlCharacters to src_fmt_configs (#27679)](https://github.com/apache/airflow/pull/27679): @thangnd197
   - [ ] [Add deferrable mode to CloudBuildCreateBuildOperator (#27783)](https://github.com/apache/airflow/pull/27783): @VladaZakharova
   - [x] [GCSToBigQueryOperator allows autodetect None and infers schema (#28564)](https://github.com/apache/airflow/pull/28564): @vchiapaikeo
   - [ ] [Improve memory usage in Dataproc deferrable operators (#28117)](https://github.com/apache/airflow/pull/28117): @lwyszomi
   - [x] [Push job_id in xcom for dataproc submit job op (#28639)](https://github.com/apache/airflow/pull/28639): @pankajastro
   - [ ] [Fix for issue with reading schema fields for JSON files in GCSToBigQueryOperator (#28284)](https://github.com/apache/airflow/pull/28284): @VladaZakharova
   - [x] [Fix GCSToBigQueryOperator not respecting schema_obj (#28444)](https://github.com/apache/airflow/pull/28444): @vchiapaikeo
   - [ ] [Fix GCSToGCSOperator copying list of objects without wildcard (#28111)](https://github.com/apache/airflow/pull/28111): @moiseenkov
   - [ ] [Fix: re-enable use of parameters in gcs_to_bq which had been disabled (#27961)](https://github.com/apache/airflow/pull/27961): @mdering
   - [x] [Set bigquery use_legacy_sql param in job config correctly (#28522)](https://github.com/apache/airflow/pull/28522): @pankajastro
   - [x] [Remove `pylint` messages control instructions (#28555)](https://github.com/apache/airflow/pull/28555): @Taragolis
   - [x] [Remove deprecated AIPlatformConsoleLink from google/provider.yaml (#28449)](https://github.com/apache/airflow/pull/28449): @vchiapaikeo
   - [ ] [Use object instead of array in config.yml for config template (#28417)](https://github.com/apache/airflow/pull/28417): @dstandish
   - [x] [[misc] Get rid of `pass` statement in conditions (#27775)](https://github.com/apache/airflow/pull/27775): @Taragolis
   - [ ] [Change log level to DEBUG when secret not found for google secret manager (#27856)](https://github.com/apache/airflow/pull/27856): @lwyszomi
   - [x] [[misc] Replace XOR `^` conditions by `exactly_one` helper in providers (#27858)](https://github.com/apache/airflow/pull/27858): @Taragolis
## Provider [imap: 3.1.1rc2](https://pypi.org/project/apache-airflow-providers-imap/3.1.1rc2)
   - [x] [[misc] Get rid of `pass` statement in conditions (#27775)](https://github.com/apache/airflow/pull/27775): @Taragolis
## Provider [microsoft.azure: 5.0.2rc2](https://pypi.org/project/apache-airflow-providers-microsoft-azure/5.0.2rc2)
   - [x] [Re-enable azure service bus on ARM as it now builds cleanly (#28442)](https://github.com/apache/airflow/pull/28442): @potiuk
## Provider [microsoft.mssql: 3.3.2rc2](https://pypi.org/project/apache-airflow-providers-microsoft-mssql/3.3.2rc2)
   - [ ] [Re-enable `pymsql` on ARM as it now builds cleanly (#28530)](https://github.com/apache/airflow/pull/28530): @Taragolis
## Provider [microsoft.winrm: 3.1.1rc2](https://pypi.org/project/apache-airflow-providers-microsoft-winrm/3.1.1rc2)
   - [ ] [Remove outdated compat imports/code from providers (#28507)](https://github.com/apache/airflow/pull/28507): @Taragolis
## Provider [oracle: 3.6.0rc2](https://pypi.org/project/apache-airflow-providers-oracle/3.6.0rc2)
   - [x] [XCOM push ORA error code in OracleStoredProcedure (#27319)](https://github.com/apache/airflow/pull/27319): @kolfild26
## Provider [postgres: 5.4.0rc2](https://pypi.org/project/apache-airflow-providers-postgres/5.4.0rc2)
   - [x] [Bring back psycopg2-binary as dependency instead of psycopg (#28316)](https://github.com/apache/airflow/pull/28316): @potiuk
## Provider [presto: 4.2.1rc2](https://pypi.org/project/apache-airflow-providers-presto/4.2.1rc2)
   - [ ] [Remove outdated compat imports/code from providers (#28507)](https://github.com/apache/airflow/pull/28507): @Taragolis
## Provider [salesforce: 5.3.0rc2](https://pypi.org/project/apache-airflow-providers-salesforce/5.3.0rc2)
   - [ ] [Add test_connection to SalesforceHook (#27921)](https://github.com/apache/airflow/pull/27921): @odaneau-astro
## Provider [sftp: 4.2.1rc2](https://pypi.org/project/apache-airflow-providers-sftp/4.2.1rc2)
   - [ ] [Update codespell and fix typos (#28568)](https://github.com/apache/airflow/pull/28568): @KarshVashi
   - [x] [[misc] Get rid of `pass` statement in conditions (#27775)](https://github.com/apache/airflow/pull/27775): @Taragolis
## Provider [slack: 7.1.1rc2](https://pypi.org/project/apache-airflow-providers-slack/7.1.1rc2)
   - [x] [[misc] Replace XOR `^` conditions by `exactly_one` helper in providers (#27858)](https://github.com/apache/airflow/pull/27858): @Taragolis
## Provider [ssh: 3.4.0rc2](https://pypi.org/project/apache-airflow-providers-ssh/3.4.0rc2)
   - [x] [Add .bash extension to SSHOperator (#28617)](https://github.com/apache/airflow/pull/28617): @stamixthereal
   - [ ] [Add test_connection method for SSHHook (#28184)](https://github.com/apache/airflow/pull/28184): @xjf729
   - [x] [SSH task exit code added to XCOM as 'ssh_exit' key (#27370)](https://github.com/apache/airflow/pull/27370): @kolfild26
   - [ ] [Remove outdated compat imports/code from providers (#28507)](https://github.com/apache/airflow/pull/28507): @Taragolis
   - [x] [[misc] Get rid of `pass` statement in conditions (#27775)](https://github.com/apache/airflow/pull/27775): @Taragolis
## Provider [telegram: 3.1.1rc2](https://pypi.org/project/apache-airflow-providers-telegram/3.1.1rc2)
   - [x] [Limit Telegram to < 20.0.0 (#28671)](https://github.com/apache/airflow/pull/28671): @potiuk
## Provider [trino: 4.3.1rc2](https://pypi.org/project/apache-airflow-providers-trino/4.3.1rc2)
   - [ ] [Remove outdated compat imports/code from providers (#28507)](https://github.com/apache/airflow/pull/28507): @Taragolis

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-by-contributors)

All users involved in the PRs:
@Taragolis @syedahsn @xinbinhuang @vchiapaikeo @ferruzzi @jon-evergreen @RachitSharma2001 @syun64 @snjypl @pankajastro @thangnd197 @dwreeves @eladkal @KarshVashi @BobDu @hankehly @xjf729 @Adityamalik123
@jbandoro @IAL32 @lwyszomi @moiseenkov @VladaZakharova @stamixthereal @vincbeck @2h-kim @kolfild26 @potiuk @raphaelauv @TohnJhomas @dstandish @vandonr-amz @romibuzi @mdering @skabbit @odaneau-astro 
@kouk

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by vandonr-amz** [comment]
✅ for me, as our CI ran the example DAGs sucessfully, which include the newly introduced operators/sensors.

**Comment by vchiapaikeo** [comment]
Reran our test dags and they both looked good:

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/9200263/210428435-323cbc58-c1d0-48b6-b5aa-bc3522f98ca8.png">

**Comment by hankehly** [comment]
#28108 is a document-only change (docs build successfully)

**Comment by stamixthereal** [comment]
#28617 also looks good on my local, anyway it is a small change

**Comment by potiuk** [comment]
All Good:

* The #28434 was just dev change 

* I checked all dependency changes in METADATA of wheel packages  (#28505, #28648, #28442, #28316 , #28671)

* Hive provider when installed provides the macros from the provider instead of the ones from Airflow (#28538):

I had no hive and connection defined, but it was correctly added and used by JINJA  and was clearly taken from hive provider, not airflow core:

```
  File "/opt/airflow/airflow/providers/apache/hive/macros/hive.py", line 49, in max_partition
    hive_hook = HiveMetastoreHook(metastore_conn_id=metastore_conn_id)
  File "/opt/airflow/airflow/providers/apache/hive/hooks/hive.py", line 485, in __init__
    self.conn = self.get_connection(metastore_conn_id)
  File "/opt/airflow/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/opt/airflow/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `metastore_default` isn't defined
```

Also it is visible in Airflow Webserver as Plugin when the new hive provider is installed (missing when installing hive provider 5.0.0):

<img width="2034" alt="Screenshot 2023-01-04 at 09 58 17" src="https://user-images.githubusercontent.com/595491/210519322-28410f1b-1637-439d-a6b3-d6e352ff777c.png">

**Comment by Taragolis** [comment]
#28555: This only affect CI and it pass

#28507, #27775,  #27858: Working fine

#28279: Check on AWS environment, work fine

#28505 - @potiuk I've found that  we try to import `numpy` before `pandas` we got ModuleNotFoundError raised instead of AirflowOptionalProviderFeatureException. `numpy` is a core dependency for `pandas` and it is not a dependency of airflow itself.  Check on slim image of airflow 2.3.4, 2.4.3 and 2.5.0. It is not critical - no raise any error during airflow services starts

https://github.com/apache/airflow/blob/8cb69bb05417075adebef19cd28b2409dbba3f33/airflow/providers/amazon/aws/transfers/sql_to_s3.py#L25-L32

```console

  File "/opt/airflow/dags/example_aws.py", line 5, in <module>
    from airflow.providers.amazon.aws.transfers.sql_to_s3 import SqlToS3Operator
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/amazon/aws/transfers/sql_to_s3.py", line 25, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

**Comment by eladkal** [comment]
>  I've found that we try to import numpy before pandas and in case of pandas not installed we more more likely get ModuleNotFoundError raised instead of AirflowOptionalProviderFeatureException

I don't think this is a concern...
This is a dependency of a dependency.
If you use library directly you should make sure you install it and not relay on another package to do that for you.

**Comment by potiuk** [comment]
> I don't think this is a concern...

Agree. It's just "less clear" exception in this case, not a blocker for sure. But I will add a fix for the next version.

**Comment by Taragolis** [comment]
> Agree. It's just "less clear" exception in this case, not a blocker for sure. But I will add a fix for the next version.

Yeah agree can do it later. This kind of import only critical if it optional part of Hooks, not a operators. We could just move it inside `try.. except` and suggest to install by extra `pip install apache-airflow-providers-amazon[pandas]`

**Comment by romibuzi** [comment]
https://github.com/apache/airflow/pull/27893 all good with a integration test:

<img width="1391" alt="image_2023-01-04_11 58 41" src="https://user-images.githubusercontent.com/2420675/210551818-72370b8a-af3a-49e4-a670-05b4d7e88187.png">

<img width="1408" alt="image_2023-01-04_11 59 08" src="https://user-images.githubusercontent.com/2420675/210551869-78348d38-9f9d-4f75-a50b-047b337ecb77.png">

**Comment by kolfild26** [comment]
Both #27319 and #27370 seem to be 🆗

**Comment by jbandoro** [comment]
Tested #28235 and it looks good, thanks!
