### ISSUE TITLE
Add missing connection types and documentation for community providers

### ISSUE THREAD

**Issue by Taragolis** [apache/airflow#28790]
### Body

Some of Hooks provide connection ability, however quite a few of them do not provide any documentation and/or connection type (missing in the UI). It would be nice if we add missing parts which might help Airflow users.

**Hooks Class Attributes reference**:
- `conn_type`: Unique connection type, should be also listed in providers.yaml
- `conn_name_attr`: Name of connection attribute, mainly uses for test connections
- `default_conn_name `: Name of default connection, it doesn't do anything if you do not set it directly to `conn_name_attr`, see as reference [SlackHook](https://github.com/apache/airflow/blob/faa32f23e824ec8dd00b296ce9d8bd239ac0437f/airflow/providers/slack/hooks/slack.py#L107-L115) 
- `hook_name`, connection name in dropdown list in the UI

**List of Providers and missing/inconsistent hooks class attributes or/and documentation**:

> [!NOTE]  
> If someone would like to work on one (or many) just let us know in comments or create PR with reference to this Issue.

[**alibaba**](https://airflow.apache.org/docs/apache-airflow-providers-alibaba/stable/index.html)
Mixin connections documentation [in the single page](https://airflow.apache.org/docs/apache-airflow-providers-alibaba/stable/connections/alibaba.html)
- [ ] [AnalyticDBSparkHook](https://airflow.apache.org/docs/apache-airflow-providers-alibaba/stable/_modules/airflow/providers/alibaba/cloud/hooks/analyticdb_spark.html#AnalyticDBSparkHook) (conn_type = "adb_spark", conn_name_attr = "alibabacloud_conn_id" this one **Inconsistent with actual hook attribute** "oss_conn_id", hook_name = "AnalyticDB Spark") https://github.com/apache/airflow/pull/51112
- [ ] [OSSHook](https://airflow.apache.org/docs/apache-airflow-providers-alibaba/stable/_modules/airflow/providers/alibaba/cloud/hooks/oss.html#OSSHook) (conn_type = "oss", conn_name_attr = "alibabacloud_conn_id" this one **Inconsistent with actual hook attribute** "oss_conn_id", hook_name = "OSS") https://github.com/apache/airflow/pull/51112

[**apache.druid**](https://airflow.apache.org/docs/apache-airflow-providers-apache-druid/stable/index.html)
- [ ] [DruidHook](https://airflow.apache.org/docs/apache-airflow-providers-apache-druid/stable/_modules/airflow/providers/apache/druid/hooks/druid.html#DruidHook) (Missing conn_type, conn_name_attr = "druid_ingest_conn_id"). 
   - [ ] Missing Conn Type/Names: https://github.com/apache/airflow/pull/33796 https://github.com/apache/airflow/pull/35244
   - [ ] Documentation
- [ ] [DruidDbApiHook](https://airflow.apache.org/docs/apache-airflow-providers-apache-druid/stable/_modules/airflow/providers/apache/druid/hooks/druid.html#DruidDbApiHook) (conn_type = "druid_broker", conn_name_attr = "druid_broker_conn_id", hook_name = "Druid Broker"). 
   - [ ] Documentation

[**apache.hdfs**](https://airflow.apache.org/docs/apache-airflow-providers-apache-hdfs/stable/index.html)
~Mixin connections documentation [in the single page](https://airflow.apache.org/docs/apache-airflow-providers-apache-hdfs/stable/connections.html#apache-hdfs-connection)~
- [x] ~[HDFSHook](https://airflow.apache.org/docs/apache-airflow-providers-apache-hdfs/stable/_modules/airflow/providers/apache/hdfs/hooks/hdfs.html#HDFSHook) (conn_type = "hdfs", conn_name_attr = "hdfs_conn_id", hook_name = "HDFS")~ Removed in 4.0.0
- [x] [WebHDFSHook](https://airflow.apache.org/docs/apache-airflow-providers-apache-hdfs/stable/_modules/airflow/providers/apache/hdfs/hooks/webhdfs.html#WebHDFSHook) (Missing conn_type, conn_name_attr = "webhdfs_conn_id") #36145

[**apache.kylin**](https://airflow.apache.org/docs/apache-airflow-providers-apache-kylin/stable/index.html)
- [x] [KylinHook](https://airflow.apache.org/docs/apache-airflow-providers-apache-kylin/stable/_modules/airflow/providers/apache/kylin/hooks/kylin.html#KylinHook) (Missing conn_type, conn_name_attr = "kylin_conn_id") #36413

[**apache.livy**](https://airflow.apache.org/docs/apache-airflow-providers-apache-livy/stable/index.html)
- [x] [LivyHook](https://airflow.apache.org/docs/apache-airflow-providers-apache-livy/stable/_modules/airflow/providers/apache/livy/hooks/livy.html#LivyHook) (conn_type = "livy", conn_name_attr = "livy_conn_id", hook_name = "Apache Livy") #36412

[**apache.pig**](https://airflow.apache.org/docs/apache-airflow-providers-apache-pig/stable/index.html)
- [ ] [PigCliHook](https://airflow.apache.org/docs/apache-airflow-providers-apache-pig/stable/_modules/airflow/providers/apache/pig/hooks/pig.html#PigCliHook) (conn_type = "pig_cli", conn_name_attr = "pig_cli_conn_id", hook_name = "Pig Client Wrapper")

[**apache.pinot**](https://airflow.apache.org/docs/apache-airflow-providers-apache-pinot/stable/index.html)
- [ ] [PinotAdminHook](https://airflow.apache.org/docs/apache-airflow-providers-apache-pinot/stable/_modules/airflow/providers/apache/pinot/hooks/pinot.html#PinotAdminHook) (conn_type = "pinot_admin", conn_name_attr = "conn_id", hook_name = "Pinot Admin"). 
   - [x] Missing Conn Type/Names: https://github.com/apache/airflow/pull/33601 (thanks @alexbegg)
   - [ ] Documentation
- [ ] [PinotDbApiHook](https://airflow.apache.org/docs/apache-airflow-providers-apache-pinot/stable/_modules/airflow/providers/apache/pinot/hooks/pinot.html#PinotDbApiHook) (conn_type = "pinot", conn_name_attr = "pinot_broker_conn_id", hook_name = "Pinot")
   - [x]  Missing Conn Type/Names: https://github.com/apache/airflow/pull/33601 (thanks @alexbegg)
   - [ ] Documentation

[**apache.spark**](https://airflow.apache.org/docs/apache-airflow-providers-apache-spark/stable/index.html)
Mixin connections documentation [in the single page](https://airflow.apache.org/docs/apache-airflow-providers-apache-spark/stable/connections/spark.html). 
- [x] [SparkSubmitHook](https://airflow.apache.org/docs/apache-airflow-providers-apache-spark/stable/_modules/airflow/providers/apache/spark/hooks/spark_submit.html#SparkSubmitHook) (conn_type = "spark", conn_name_attr = "conn_id", hook_name = "Spark") #36419
- [x] [SparkJDBCHook](https://airflow.apache.org/docs/apache-airflow-providers-apache-spark/stable/_modules/airflow/providers/apache/spark/hooks/spark_jdbc.html#SparkJDBCHook) (conn_type = "spark_jdbc", conn_name_attr = "spark_conn_id", hook_name = "Spark JDBC") #36419
- [x] [SparkSqlHook](https://airflow.apache.org/docs/apache-airflow-providers-apache-spark/stable/_modules/airflow/providers/apache/spark/hooks/spark_sql.html#SparkSqlHook) (conn_type = "spark_sql", conn_name_attr = "conn_id", hook_name = "Spark SQL") #36419

[**apache.sqoop**](https://airflow.apache.org/docs/apache-airflow-providers-apache-sqoop/stable/index.html)
- [x] ~[SqoopHook](https://airflow.apache.org/docs/apache-airflow-providers-apache-sqoop/stable/_modules/airflow/providers/apache/sqoop/hooks/sqoop.html#SqoopHook) (conn_type = "sqoop", conn_name_attr = "conn_id", hook_name = "Sqoop")~ Removed in https://github.com/apache/airflow/pull/36460

[**datadog**](https://airflow.apache.org/docs/apache-airflow-providers-datadog/stable/index.html)
- [x] [DatadogHook](https://airflow.apache.org/docs/apache-airflow-providers-datadog/stable/_modules/airflow/providers/datadog/hooks/datadog.html#DatadogHook) (Missing conn_type, conn_name_attr = "datadog_conn_id") https://github.com/apache/airflow/pull/30059

[**dingding**](https://airflow.apache.org/docs/apache-airflow-providers-dingding/stable/index.html)
- [ ] [DingdingHook](https://airflow.apache.org/docs/apache-airflow-providers-dingding/stable/_modules/airflow/providers/dingding/hooks/dingding.html#DingdingHook) (conn_type = "dingding", conn_name_attr = "dingding_conn_id", hook_name = "Dingding")

[**discord**](https://airflow.apache.org/docs/apache-airflow-providers-discord/stable/index.html)
Discord built in top of HTTP Connection with specific settings, which only described in docstring
- [x] [DiscordWebhookHook](https://airflow.apache.org/docs/apache-airflow-providers-discord/stable/_modules/airflow/providers/discord/hooks/discord_webhook.html#DiscordWebhookHook) (conn_type = "discord", conn_name_attr = "http_conn_id", hook_name = "Discord") https://github.com/apache/airflow/pull/36720

[**exasol**](https://airflow.apache.org/docs/apache-airflow-providers-exasol/stable/index.html)
- [ ] [ExasolHook](https://airflow.apache.org/docs/apache-airflow-providers-exasol/stable/_modules/airflow/providers/exasol/hooks/exasol.html#ExasolHook) (conn_type = "exasol", conn_name_attr = "exasol_conn_id", hook_name = "Exasol")

[**facebook**](https://airflow.apache.org/docs/apache-airflow-providers-facebook/stable/index.html)
- [ ] [FacebookAdsReportingHook](https://airflow.apache.org/docs/apache-airflow-providers-facebook/stable/_modules/airflow/providers/facebook/ads/hooks/ads.html#FacebookAdsReportingHook) (conn_type = "facebook_social", conn_name_attr = "facebook_conn_id", hook_name = "Facebook Ads"), https://github.com/apache/airflow/issues/25495

[**google**](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/index.html)
- [x] [GoogleAdsHook](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/_modules/airflow/providers/google/ads/hooks/ads.html#GoogleAdsHook) (Missing conn_type, conn_name_attr = "google_ads_conn_id") https://github.com/apache/airflow/pull/50755
- [ ] [LookerHook](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/_modules/airflow/providers/google/cloud/hooks/looker.html#LookerHook) (Missing conn_type, conn_name_attr = "looker_conn_id", **Note**: Connection Type has [documentation](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/connections/gcp_looker.html)) https://github.com/apache/airflow/pull/51058
- [x] [LevelDBHook](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/_modules/airflow/providers/google/leveldb/hooks/leveldb.html#LevelDBHook) (conn_type = "leveldb", conn_name_attr = "leveldb_conn_id", hook_name = "LevelDB") https://github.com/apache/airflow/pull/51058 https://github.com/apache/airflow/pull/51343
- [x] [BigQueryHook](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/_modules/airflow/providers/google/cloud/hooks/bigquery.html#BigQueryHook) (conn_type = "gcpbigquery", conn_name_attr = "gcp_conn_id", hook_name = "Google Bigquery"), https://github.com/apache/airflow/issues/29286#issuecomment-1412672082 https://github.com/apache/airflow/pull/38430

[**hashicorp**](https://airflow.apache.org/docs/apache-airflow-providers-hashicorp/stable/index.html)
- [x] [VaultHook](https://airflow.apache.org/docs/apache-airflow-providers-hashicorp/stable/_modules/airflow/providers/hashicorp/hooks/vault.html#VaultHook) (conn_type = "vault", conn_name_attr = "vault_conn_id", hook_name = "Hashicorp Vault") https://github.com/apache/airflow/pull/30057

[**cloudant**](https://airflow.apache.org/docs/apache-airflow-providers-cloudant/stable/index.html)
- [ ] [CloudantHook](https://airflow.apache.org/docs/apache-airflow-providers-cloudant/stable/_modules/airflow/providers/cloudant/hooks/cloudant.html#CloudantHook) (conn_type = "cloudant", conn_name_attr = "cloudant_conn_id", hook_name = "Cloudant")

[**atlassian.jira**](https://airflow.apache.org/docs/apache-airflow-providers-atlassian-jira/stable/index.html)
- [x] [JiraHook](https://airflow.apache.org/docs/apache-airflow-providers-atlassian-jira/stable/_modules/airflow/providers/atlassian/jira/hooks/jira.html#JiraHook) (conn_type = "jira", conn_name_attr = "jira_conn_id", hook_name = "JIRA") https://github.com/apache/airflow/pull/36458

[**microsoft.azure**](https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/stable/index.html)
- [ ] [AzureContainerInstanceHook](https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/stable/_modules/airflow/providers/microsoft/azure/hooks/container_instance.html#AzureContainerInstanceHook) (conn_type = "azure_container_instance", conn_name_attr = "azure_conn_id", hook_name = "Azure Container Instance")

[**microsoft.psrp**](https://airflow.apache.org/docs/apache-airflow-providers-microsoft-psrp/stable/index.html)
- [x] [PsrpHook](https://airflow.apache.org/docs/apache-airflow-providers-microsoft-psrp/stable/_modules/airflow/providers/microsoft/psrp/hooks/psrp.html#PsrpHook) (Missing conn_type, conn_name_attr = "psrp_conn_id") https://github.com/apache/airflow/pull/34766

[**microsoft.winrm**](https://airflow.apache.org/docs/apache-airflow-providers-microsoft-winrm/stable/index.html)
I'm not familiar with WinRM Protocol, but seems like it actually doesn't use SSH Connection, however connection attribute is `ssh_conn_id` which might confuse end users.
- [ ] [WinRMHook](https://airflow.apache.org/docs/apache-airflow-providers-microsoft-winrm/stable/_modules/airflow/providers/microsoft/winrm/hooks/winrm.html#WinRMHook) (Missing conn_type, conn_name_attr = "ssh_conn_id")

[**openfaas**](https://airflow.apache.org/docs/apache-airflow-providers-openfaas/stable/index.html)
- [ ] [OpenFaasHook](https://airflow.apache.org/docs/apache-airflow-providers-openfaas/stable/_modules/airflow/providers/openfaas/hooks/openfaas.html#OpenFaasHook) (Missing conn_type, conn_name_attr = "conn_id")

[**opsgenie**](https://airflow.apache.org/docs/apache-airflow-providers-opsgenie/stable/index.html)
- [x] [OpsgenieAlertHook](https://airflow.apache.org/docs/apache-airflow-providers-opsgenie/stable/_modules/airflow/providers/opsgenie/hooks/opsgenie.html#OpsgenieAlertHook) (conn_type = "opsgenie", conn_name_attr = "opsgenie_conn_id", hook_name = "Opsgenie") https://github.com/apache/airflow/pull/36519

[**pagerduty**](https://airflow.apache.org/docs/apache-airflow-providers-pagerduty/stable/index.html)
- [x] [PagerdutyHook](https://airflow.apache.org/docs/apache-airflow-providers-pagerduty/stable/_modules/airflow/providers/pagerduty/hooks/pagerduty.html#PagerdutyHook) (conn_type = "pagerduty", conn_name_attr = "pagerduty_conn_id", hook_name = "Pagerduty")
- [x] [PagerdutyEventsHook](https://airflow.apache.org/docs/apache-airflow-providers-pagerduty/stable/_modules/airflow/providers/pagerduty/hooks/pagerduty_events.html#PagerdutyEventsHook) (conn_type = "pagerduty_events", conn_name_attr = "pagerduty_events_conn_id", hook_name = "Pagerduty Events")

[**presto**](https://airflow.apache.org/docs/apache-airflow-providers-presto/stable/index.html)
- [x] [PrestoHook](https://airflow.apache.org/docs/apache-airflow-providers-presto/stable/_modules/airflow/providers/presto/hooks/presto.html#PrestoHook) (conn_type = "presto", conn_name_attr = "presto_conn_id", hook_name = "Presto") https://github.com/apache/airflow/pull/37536

~[**qubole**](https://airflow.apache.org/docs/apache-airflow-providers-qubole/stable/index.html)~
- ~[ ] [QuboleHook](https://airflow.apache.org/docs/apache-airflow-providers-qubole/stable/_modules/airflow/providers/qubole/hooks/qubole.html#QuboleHook) (conn_type = "qubole", conn_name_attr = "qubole_conn_id", hook_name = "Qubole")~ suspended provider

[**redis**](https://airflow.apache.org/docs/apache-airflow-providers-redis/stable/index.html)
- [x] [RedisHook](https://airflow.apache.org/docs/apache-airflow-providers-redis/stable/_modules/airflow/providers/redis/hooks/redis.html#RedisHook) (conn_type = "redis", conn_name_attr = "redis_conn_id", hook_name = "Redis") https://github.com/apache/airflow/pull/36581

[**samba**](https://airflow.apache.org/docs/apache-airflow-providers-samba/stable/index.html)
- [x] [SambaHook](https://airflow.apache.org/docs/apache-airflow-providers-samba/stable/_modules/airflow/providers/samba/hooks/samba.html#SambaHook) (conn_type = "samba", conn_name_attr = "samba_conn_id", hook_name = "Samba") https://github.com/apache/airflow/pull/36543

[**segment**](https://airflow.apache.org/docs/apache-airflow-providers-segment/stable/index.html)
- [ ] [SegmentHook](https://airflow.apache.org/docs/apache-airflow-providers-segment/stable/_modules/airflow/providers/segment/hooks/segment.html#SegmentHook) (conn_type = "segment", conn_name_attr = "segment_conn_id", hook_name = "Segment")

[**telegram**](https://airflow.apache.org/docs/apache-airflow-providers-telegram/stable/index.html)
- [x] [TelegramHook](https://airflow.apache.org/docs/apache-airflow-providers-telegram/stable/_modules/airflow/providers/telegram/hooks/telegram.html#TelegramHook) (Missing conn_type, conn_name_attr = "telegram_conn_id") https://github.com/apache/airflow/pull/37515

[**vertica**](https://airflow.apache.org/docs/apache-airflow-providers-vertica/stable/index.html)
- [ ] [VerticaHook](https://airflow.apache.org/docs/apache-airflow-providers-vertica/stable/_modules/airflow/providers/vertica/hooks/vertica.html#VerticaHook) (conn_type = "vertica", conn_name_attr = "vertica_conn_id", hook_name = "Vertica")

[**zendesk**](https://airflow.apache.org/docs/apache-airflow-providers-zendesk/stable/index.html)
- [x] [Zendesk](https://airflow.apache.org/docs/apache-airflow-providers-zendesk/stable/_modules/airflow/providers/zendesk/hooks/zendesk.html#ZendeskHook) (conn_type = "zendesk", conn_name_attr = "zendesk_conn_id", hook_name = "Zendesk") #36423

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by hussein-awala** [comment]
@Taragolis I just created #30057 to fix Vault connection and add missing doc, can you check it?

**Comment by shohamy7** [comment]
Hi @Taragolis 
Looks like WebHDFSHook has been resolved in #36145

**Comment by eladkal** [comment]
@jsjasonseba saw you contributed some features with Alibaba. Will you be able to assist with the Alibaba entries of this issue?
