### ISSUE TITLE
Status of testing Providers that were prepared on January 23, 2023

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#29103]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [apache.cassandra: 3.1.1rc1](https://pypi.org/project/apache-airflow-providers-apache-cassandra/3.1.1rc1)
   - [x] [Limit dnspython to < 2.3.0 until eventlet incompatibitliy is solved (#28962)](https://github.com/apache/airflow/pull/28962): @potiuk
   - [x] [Remove limit for dnspython after eventlet got fixed (#29004)](https://github.com/apache/airflow/pull/29004): @potiuk
## Provider [docker: 3.5.0rc1](https://pypi.org/project/apache-airflow-providers-docker/3.5.0rc1)
We prepare `3.5.0rc1` instead of `3.4.1rc2`
   - [x] [Add correct widgets in Docker Hook (#28700)](https://github.com/apache/airflow/pull/28700): @potiuk
   - [x] [make docker operators always use `DockerHook` for API calls (#28363)](https://github.com/apache/airflow/pull/28363): @Taragolis
   - [x] [Skip DockerOperator task when it returns a provided exit code (#28996)](https://github.com/apache/airflow/pull/28996): @hussein-awala
   - [x] [Fix label name for `reauth` field in Docker Connection (#28974)](https://github.com/apache/airflow/pull/28974): @Taragolis
## Provider [papermill: 3.1.1rc1](https://pypi.org/project/apache-airflow-providers-papermill/3.1.1rc1)
   - [x] [Fix rendering parameters in PapermillOperator (#28979)](https://github.com/apache/airflow/pull/28979): @Taragolis

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-by-contributors)

All users involved in the PRs:
@hussein-awala @Taragolis @potiuk

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by Taragolis** [comment]
@TPapajCin @marvinfretly @nicnguyen3103 could you also have a look PapermillOperator? 
```pip install apache-airflow-providers-papermill==3.1.1rc1```

**Comment by potiuk** [comment]
@eladkal I noticed unsual thing - that we do not have have the "sdist" in PyPI - only .whl ones. I think they are generated (they are present in SVN for verification) but not in PyPI. Just wanted to see if this is something of a problem with the release process /manual mistake ?

**Comment by hussein-awala** [comment]
#28996 tested and working as expected
```python
import pendulum

from airflow.providers.docker.operators.docker import DockerOperator
from airflow.models import DAG

default_args = {}


with DAG(
    dag_id='docker_operators',
    default_args=default_args,
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
    schedule=None
) as dag:
    docker1 = DockerOperator(
        task_id="alpine_should_success",
        image="alpine",
        container_name="docker1",
        command="echo 1",
        auto_remove="success",
        docker_url="unix://var/run/docker.sock",
        skip_exit_code=50,
    )

    docker2 = DockerOperator(
        task_id="alpine_should_skip",
        image="alpine",
        container_name="docker2",
        command='sh -c "exit 50"',
        auto_remove="success",
        docker_url="unix://var/run/docker.sock",
        skip_exit_code=50,
    )

    docker3 = DockerOperator(
        task_id="alpine_should_fail",
        image="alpine",
        container_name="docker3",
        command='sh -c "exit 50"',
        auto_remove="success",
        docker_url="unix://var/run/docker.sock",
    )

    docker4 = DockerOperator(
        task_id="python_should_skip",
        image="python",
        container_name="docker4",
        command="python -c 'print(1); exit(50)'",
        auto_remove="success",
        docker_url="unix://var/run/docker.sock",
        skip_exit_code=50,
    )

    docker5 = DockerOperator(
        task_id="python_should_fail",
        image="python",
        container_name="docker5",
        command="python -c 'print(1); exit(50)'",
        auto_remove="success",
        docker_url="unix://var/run/docker.sock",
    )
```
![image](https://user-images.githubusercontent.com/21311487/214136942-aae5edfe-1fe6-4714-8637-9dab26398468.png)

**Comment by Taragolis** [comment]
- https://github.com/apache/airflow/pull/28363 - work as expected with new implementation
- https://github.com/apache/airflow/pull/28979 - render templates (test in Airflow 2.3.4 and Airflow 2.5.1) and pass it to papermill library

**Comment by eladkal** [comment]
> @eladkal I noticed unsual thing - that we do not have have the "sdist" in PyPI - only .whl ones. I think they are generated (they are present in SVN for verification) but not in PyPI. Just wanted to see if this is something of a problem with the release process /manual mistake ?
> 
> See https://pypi.org/project/apache-airflow-providers-apache-cassandra/3.1.1rc1/#files for example


Thanks for noticing. Fixed

**Comment by eladkal** [comment]
Thank you everyone.
Providers are released
I invite everyone to help improve providers for the next release, a list of open bugs can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Akind%3Abug+label%3Aarea%3Aproviders).
