### ISSUE TITLE
Status of testing of Apache Airflow Helm Chart 1.8.0rc1 

### ISSUE THREAD

**Issue by jedcunningham** [apache/airflow#29273]
We have a kind request for all the contributors to the latest [Apache Airflow Helm Chart 1.8.0rc1](https://dist.apache.org/repos/dist/dev/airflow/helm-chart/1.8.0rc1).

Could you please help us to test the RC versions of the Apache Airflow Helm Chart?

Please let us know in the comment if the issue is addressed in the latest RC.

- [x] [Add nodePort declaration to chart/values.schema.json (#26945)](https://github.com/apache/airflow/pull/26945): @joseph-max-coalfire
     Linked issues:
     - [Add NodePort Option to the values schema (#26812)](https://github.com/apache/airflow/issues/26812)
- [x] [Make custom env vars optional for job templates (#27148)](https://github.com/apache/airflow/pull/27148): @richardbadman @tseruga
     Linked issues:
     - [[Helm Chart] Decouple custom_airflow_environment from all pods and jobs (#26045)](https://github.com/apache/airflow/issues/26045)
- [x] [Add workeer log-groomer-sidecar enable option in helm chart (#27178)](https://github.com/apache/airflow/pull/27178): @BobDu @jedcunningham
     Linked issues:
     - [Adds support for custom command and args (#16153)](https://github.com/apache/airflow/pull/16153)
- [x] [Chart: Default airflow version to 2.4.2 (#27230)](https://github.com/apache/airflow/pull/27230): @ephraimbuddy
- [x] [Add webserverConfigConfigMapName (#27419)](https://github.com/apache/airflow/pull/27419): @JulesTriomphe
- [ ] [ExtraVolumeMounts in sidecars and initContainers (#27420)](https://github.com/apache/airflow/pull/27420): @JulesTriomphe
- [x] [allow pgbouncer replicas to be configurable (#27439)](https://github.com/apache/airflow/pull/27439): @pgvishnuram
- [x] [[BUMP] helm chart - redis 7 (#27443)](https://github.com/apache/airflow/pull/27443): @raphaelauv
- [x] [Chart: add hostaliases to pod template file (#27544)](https://github.com/apache/airflow/pull/27544): @Aakcht
- [x] [Chart: Decrease default gitSync wait (#27625)](https://github.com/apache/airflow/pull/27625): @jedcunningham
- [x] [Chart: Update default airflow version to 2.4.3 (#27668)](https://github.com/apache/airflow/pull/27668): @ephraimbuddy
- [x] [Correct repo example for cloning via ssh - comments in helm chart (#27671)](https://github.com/apache/airflow/pull/27671): @schudoku @morkot
     Linked issues:
     - [helm chart - mounting-dags-from-a-private-github-repo-using-git-sync-sidecar (#21970)](https://github.com/apache/airflow/issues/21970)
- [x] [Replace helm chart icon (#27704)](https://github.com/apache/airflow/pull/27704): @ronahk
- [x] [Chart: add airflow_local_settings to all airflow containers (#27779)](https://github.com/apache/airflow/pull/27779): @rauljmz @Aakcht @venkatnpedada
     Linked issues:
     - [Not able to use custom logging with airflow helm chart (#27498)](https://github.com/apache/airflow/issues/27498)
     - [Cannot reference airflow_local_settings in config settings (#25637)](https://github.com/apache/airflow/issues/25637)
- [x] [Add global volume & volumeMounts to the chart (#27781)](https://github.com/apache/airflow/pull/27781): @csp33
     Linked issues:
     - [Allow global volume & volumeMounts in Helm chart (#27687)](https://github.com/apache/airflow/issues/27687)
- [x] [git-sync 3.6.3 (#27848)](https://github.com/apache/airflow/pull/27848): @danielhoherd
- [x] [Enhance chart to allow over-riding command-line args to statsd exporter (#28041)](https://github.com/apache/airflow/pull/28041): @rob-1126
- [x] [Chart: Default airflow version to 2.5.0 (#28074)](https://github.com/apache/airflow/pull/28074): @ephraimbuddy
- [ ] [Fix helm chart NOTES.txt to show correct URL (#28264)](https://github.com/apache/airflow/pull/28264): @okue
- [ ] [Remove checks for 1.19 api checks (#28461)](https://github.com/apache/airflow/pull/28461): @potiuk @Jmdaming
     Linked issues:
     - [Wrong apiVersion Detected During Ingress Creation (#22657)](https://github.com/apache/airflow/issues/22657)
- [x] [Add missing annotations on deployments [#28604] (#28688)](https://github.com/apache/airflow/pull/28688): @sudeepgupta90
     Linked issues:
     - [Missing annotations on Deployments (#28604)](https://github.com/apache/airflow/issues/28604)
- [x] [Add worker service account for LocalKubernetesExecutor (#28813)](https://github.com/apache/airflow/pull/28813): @Chen-Oliver
- [x] [Fix helm chart create scheduler service to  serve task logs for LocalKubernetesExecutor (#28828)](https://github.com/apache/airflow/pull/28828): @snjypl
- [x] [Fix incorrect comments in worker-kedaautoscaler.yaml (#28858)](https://github.com/apache/airflow/pull/28858): @EricGao888
- [x] [Chart: add doc note about podtemplate images (#29032)](https://github.com/apache/airflow/pull/29032): @Aakcht
- [ ] [Upgrade bitnami/postgresql helm depenency from 10.5.3 to 12.1.9 (#29071)](https://github.com/apache/airflow/pull/29071): @snjypl
- [x] [Update Airflow version to 2.5.1 (#29074)](https://github.com/apache/airflow/pull/29074): @pierrejeambrun
- [ ] [Fix PgBouncer after postgres subchart upgrade (#29207)](https://github.com/apache/airflow/pull/29207): @snjypl @jedcunningham
     Linked issues:
     - [Upgrade bitnami/postgresql helm depenency from 10.5.3 to 12.1.9 (#29071)](https://github.com/apache/airflow/pull/29071)

Thanks to all who contributed to the release (probably not a complete list!):
@richardbadman @ronahk @pgvishnuram @sudeepgupta90 @Jmdaming @joseph-max-coalfire @Aakcht @tseruga @JulesTriomphe @morkot @rauljmz @pierrejeambrun @csp33 @raphaelauv @rob-1126 @jedcunningham @okue @venkatnpedada @Chen-Oliver @schudoku @EricGao888 @danielhoherd @BobDu @snjypl @potiuk @ephraimbuddy

**Comment by danielhoherd** [comment]
I have validated https://github.com/apache/airflow/pull/27848 which was easy to validate. It was just a version bump.

**Comment by Aakcht** [comment]
Checked #27544 , #27779 and #29032 - all good.

**Comment by sudeepgupta90** [comment]
Checked #28604 <https://github.com/apache/airflow/issues/28604> - all good

**Comment by pgvishnuram** [comment]
Checked #27439 works as expected

**Comment by JulesTriomphe** [comment]
I have spotted multiple issues:

- There is a missing prefixing `-` [here](https://github.com/apache/airflow/blob/helm-chart/1.8.0rc1/chart/templates/jobs/migrate-database-job.yaml#L111) to cleanly render the volume mounts for the migrate-database-job, same [here](https://github.com/apache/airflow/blob/helm-chart/1.8.0rc1/chart/templates/dag-processor/dag-processor-deployment.yaml#L155) for the dag-processor, [here](https://github.com/apache/airflow/blob/helm-chart/1.8.0rc1/chart/templates/scheduler/scheduler-deployment.yaml#L145), [here](https://github.com/apache/airflow/blob/helm-chart/1.8.0rc1/chart/templates/scheduler/scheduler-deployment.yaml#L224) and [here](https://github.com/apache/airflow/blob/helm-chart/1.8.0rc1/chart/templates/scheduler/scheduler-deployment.yaml#L253) for the scheduler, [here](https://github.com/apache/airflow/blob/helm-chart/1.8.0rc1/chart/templates/triggerer/triggerer-deployment.yaml#L125) and [here](https://github.com/apache/airflow/blob/helm-chart/1.8.0rc1/chart/templates/triggerer/triggerer-deployment.yaml#L164) for the triggerer, [here](https://github.com/apache/airflow/blob/helm-chart/1.8.0rc1/chart/templates/webserver/webserver-deployment.yaml#L137) and [here](https://github.com/apache/airflow/blob/helm-chart/1.8.0rc1/chart/templates/webserver/webserver-deployment.yaml#L193) for the webserver, [here](https://github.com/apache/airflow/blob/helm-chart/1.8.0rc1/chart/templates/workers/worker-deployment.yaml#L155), [here](https://github.com/apache/airflow/blob/helm-chart/1.8.0rc1/chart/templates/workers/worker-deployment.yaml#L212), [here](https://github.com/apache/airflow/blob/helm-chart/1.8.0rc1/chart/templates/workers/worker-deployment.yaml#L274) and [here](https://github.com/apache/airflow/blob/helm-chart/1.8.0rc1/chart/templates/workers/worker-deployment.yaml#L306) for the workers
- Globally defined volumes are missing in the [pod-template-file](https://github.com/apache/airflow/blob/helm-chart/1.8.0rc1/chart/files/pod-template-file.kubernetes-helm-yaml) which will make pod spawning fail on clusters where readOnlyRootFilesystem is True and a volume for airflow home has been set globally. Workaround would be to set that volume in each system's extraVolumes and extraVolumeMounts but that would greatly reduce the functionality of global volumes and volume mounts.
- There is a missing trailing `-` [here](https://github.com/apache/airflow/blob/helm-chart/1.8.0rc1/chart/templates/_helpers.yaml#L431) to cleanly render the "airflow_dags_mount"
- There is a missing prefixing `-` [here](https://github.com/apache/airflow/blob/helm-chart/1.8.0rc1/chart/templates/webserver/webserver-service.yaml#L45) to cleanly render webserver service ports, and I didn't manage to clean the rendering of the fields themselves (name aligned with the dash). The current state looks like this:
```yaml
ports:

    - 
      name: airflow-ui
      port: 8080
```

I will try adding the missing globally defined volumes to the pod template file, deploy and then open a PR to correct this and another for the rendering issues.

**Comment by richardbadman** [comment]
Checked [#27148](https://github.com/apache/airflow/pull/27148), works as expected

**Comment by ronahk** [comment]
Checked #27704 <https://github.com/apache/airflow/pull/27704> works as
expected.

**Comment by rob-1126** [comment]
Checked [#28041](https://github.com/apache/airflow/pull/28041) - works as expected.

**Comment by jedcunningham** [comment]
@JulesTriomphe, thanks for testing this out! Since the issue you found isn't a regression from 1.7.0, it'll end up going in the next helm chart release instead of blocking this one.

**Comment by joseph-max-coalfire** [comment]
Tested #26945 -- looks good, working as intended 💯

**Comment by JulesTriomphe** [comment]
@jedcunningham are you planning to release a patch version sometime soon to include these bug fixes ?

**Comment by JulesTriomphe** [comment]
Checked #27419, works as expected

**Comment by jedcunningham** [comment]
@JulesTriomphe, I fully intend to do releases more quickly than we have in the past. So "sometime soon" meaning in the next month, yes, in the next week or so, no.

**Comment by morkot** [comment]
#27671 has been checked. Changes are there, as expected. You can tick that one off.

**Comment by JulesTriomphe** [comment]
Very cool, thanks for the clarification @jedcunningham !

**Comment by csp33** [comment]
Guess we can confirm that #27230, #27668, #28074 and #29074 are working✌🏻
![image](https://user-images.githubusercontent.com/28935464/216542517-f131b4af-158b-44d6-b36e-7be71ead3357.png)

**Comment by csp33** [comment]
#27178 works as expected

**Comment by csp33** [comment]
#27443 is also OK

**Comment by csp33** [comment]
All good in #27625

**Comment by csp33** [comment]
#28813 looks good

**Comment by BobDu** [comment]
#27178 is ok!

**Comment by jedcunningham** [comment]
Awesome, thanks @csp33! (I'd intended to remove all those core Airflow version bumps but missed it!)

**Comment by jedcunningham** [comment]
1.8.0 is out! Thanks everyone for taking the time to test the RC!
