### ISSUE TITLE
Status of testing Providers that were prepared on February 08, 2023

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#29424]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 7.2.0rc1](https://pypi.org/project/apache-airflow-providers-amazon/7.2.0rc1)
   - [x] [Add option to wait for completion on the EmrCreateJobFlowOperator (#28827)](https://github.com/apache/airflow/pull/28827): @BasPH
   - [ ] [Add transfer operator S3 to (generic) SQL (#29085)](https://github.com/apache/airflow/pull/29085): @maggesssss
   - [ ] [add retries to stop_pipeline on conflict (#29077)](https://github.com/apache/airflow/pull/29077): @vandonr-amz
   - [ ] [Add log for AWS Glue Job Console URL (#28925)](https://github.com/apache/airflow/pull/28925): @IAL32
   - [ ] [Enable trigger logging in webserver (#27758)](https://github.com/apache/airflow/pull/27758): @dstandish
   - [ ] [fix: type annotation for `num_of_dpus` in GlueJobHook (#29176)](https://github.com/apache/airflow/pull/29176): @wonhyeongseo
   - [x] [Fix typo in DataSyncHook boto3 methods for create location in NFS and EFS (#28948)](https://github.com/apache/airflow/pull/28948): @Taragolis
   - [x] [Decrypt SecureString value obtained by SsmHook (#29142)](https://github.com/apache/airflow/pull/29142): @Taragolis
   - [ ] [log the observed status in redshift sensor (#29274)](https://github.com/apache/airflow/pull/29274): @vandonr-amz
   - [x] [Use thin/passthrough hook instead of one-liner hook method (#29252)](https://github.com/apache/airflow/pull/29252): @o-nikolas
   - [ ] [Move imports in AWS SqlToS3Operator transfer to callable function (#29045)](https://github.com/apache/airflow/pull/29045): @joarobles
   - [ ] [introduce base class for EKS sensors (#29053)](https://github.com/apache/airflow/pull/29053): @vandonr-amz
   - [ ] [introduce a method to convert dictionaries to boto-style key-value lists (#28816)](https://github.com/apache/airflow/pull/28816): @vandonr-amz
   - [ ] [Update provide_bucket_name() decorator to handle new conn_type (#28706)](https://github.com/apache/airflow/pull/28706): @RachitSharma2001
   - [ ] [uniformize getting hook through cached property in aws sensors (#29001)](https://github.com/apache/airflow/pull/29001): @vandonr-amz
   - [x] [Use boto3 intersphinx inventory in documentation/docstrings. (#28945)](https://github.com/apache/airflow/pull/28945): @Taragolis
## Provider [apache.beam: 4.2.0rc1](https://pypi.org/project/apache-airflow-providers-apache-beam/4.2.0rc1)
   - [x] [Add support for running a Beam Go pipeline with an executable binary (#28764)](https://github.com/apache/airflow/pull/28764): @johannaojeling
   - [ ] [Deprecate `delegate_to` param in GCP operators and update docs (#29088)](https://github.com/apache/airflow/pull/29088): @shahar1
## Provider [apache.hive: 5.1.2rc1](https://pypi.org/project/apache-airflow-providers-apache-hive/5.1.2rc1)
   - [x] [Fixed MyPy errors introduced by new mysql-connector-python (#28995)](https://github.com/apache/airflow/pull/28995): @potiuk
## Provider [arangodb: 2.1.1rc1](https://pypi.org/project/apache-airflow-providers-arangodb/2.1.1rc1)
   - [x] [Fix ArangoDB static checks (#28820)](https://github.com/apache/airflow/pull/28820): Not require testing
## Provider [cncf.kubernetes: 5.2.0rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/5.2.0rc1)
   - [ ] [Add deferrable mode to KubernetesPodOperator (#29017)](https://github.com/apache/airflow/pull/29017): @VladaZakharova
   - [x] [Allow setting the name for the base container within K8s Pod Operator (#28808)](https://github.com/apache/airflow/pull/28808): @csm10495
   - [ ] [Patch only single label when marking KPO checked (#29279)](https://github.com/apache/airflow/pull/29279): @jedcunningham
## Provider [dbt.cloud: 3.0.0rc1](https://pypi.org/project/apache-airflow-providers-dbt-cloud/3.0.0rc1)
   - [x] [Drop Connection.schema use in DbtCloudHook (#29166)](https://github.com/apache/airflow/pull/29166): @josh-fell
   - [x] [Allow downloading of dbt Cloud artifacts to non-existent paths (#29048)](https://github.com/apache/airflow/pull/29048): @josh-fell
   - [x] [Add deferrable mode to `DbtCloudRunJobOperator` (#29014)](https://github.com/apache/airflow/pull/29014): @phanikumv
   - [x] [Provide more context for `trigger_reason` in DbtCloudRunJobOperator (#28994)](https://github.com/apache/airflow/pull/28994): @josh-fell
## Provider [elasticsearch: 4.4.0rc1](https://pypi.org/project/apache-airflow-providers-elasticsearch/4.4.0rc1)
   - [ ] [Enable trigger logging in webserver (#27758)](https://github.com/apache/airflow/pull/27758): @dstandish
## Provider [ftp: 3.3.1rc1](https://pypi.org/project/apache-airflow-providers-ftp/3.3.1rc1)
   - [ ] [FTP operator has logic in __init__ (#29073)](https://github.com/apache/airflow/pull/29073): @snjypl
## Provider [google: 8.9.0rc1](https://pypi.org/project/apache-airflow-providers-google/8.9.0rc1)
   - [x] [Add deferrable capability to existing DataprocDeleteClusterOperator (#29349)](https://github.com/apache/airflow/pull/29349): @pankajkoti
   - [ ] [Add deferrable mode to dataflow operators (#27776)](https://github.com/apache/airflow/pull/27776): @MrGeorgeOwl
   - [ ] [Add deferrable mode to DataprocCreateBatchOperator (#28457)](https://github.com/apache/airflow/pull/28457): @bkossakowska
   - [ ] [Add deferrable mode to DataprocCreateClusterOperator and (#28529)](https://github.com/apache/airflow/pull/28529): @bkossakowska
   - [ ] [Add deferrable mode to MLEngineStartTrainingJobOperator (#27405)](https://github.com/apache/airflow/pull/27405): @VladaZakharova
   - [ ] [Add deferrable mode to DataFusionStartPipelineOperator (#28690)](https://github.com/apache/airflow/pull/28690): @VladaZakharova
   - [ ] [Add deferrable mode for Big Query Transfer operator (#27833)](https://github.com/apache/airflow/pull/27833): @MrGeorgeOwl
   - [x] [Add support for write_on_empty in BaseSQLToGCSOperator (#28959)](https://github.com/apache/airflow/pull/28959): @vchiapaikeo
   - [ ] [Add DataprocCancelOperationOperator (#28456)](https://github.com/apache/airflow/pull/28456): @bkossakowska
   - [ ] [Enable trigger logging in webserver (#27758)](https://github.com/apache/airflow/pull/27758): @dstandish
   - [ ] [Auto ML assets (#25466)](https://github.com/apache/airflow/pull/25466): @MaksYermak
   - [ ] [Fix GoogleDriveHook writing files to trashed folders on upload v2 (#29119)](https://github.com/apache/airflow/pull/29119): @vchiapaikeo
   - [x] [fix Google provider CHANGELOG.rst (#29122)](https://github.com/apache/airflow/pull/29122): Not require testing
   - [x] [fix Google provider CHANGELOG.rst (#29114)](https://github.com/apache/airflow/pull/29114): Not require testing
   - [ ] [Keyfile dict can be dict not str (#29135)](https://github.com/apache/airflow/pull/29135): @dstandish
   - [ ] [GCSTaskHandler may use remote log conn id (#29117)](https://github.com/apache/airflow/pull/29117): @dstandish
   - [ ] [Deprecate `delegate_to` param in GCP operators and update docs (#29088)](https://github.com/apache/airflow/pull/29088): @shahar1
## Provider [microsoft.azure: 5.2.0rc1](https://pypi.org/project/apache-airflow-providers-microsoft-azure/5.2.0rc1)
   - [ ] [Enable trigger logging in webserver (#27758)](https://github.com/apache/airflow/pull/27758): @dstandish
   - [x] [Fix params rendering in AzureSynapseHook Python API docs (#29041)](https://github.com/apache/airflow/pull/29041): @josh-fell
   - [ ] [Deprecate `delegate_to` param in GCP operators and update docs (#29088)](https://github.com/apache/airflow/pull/29088): @shahar1
## Provider [mysql: 4.0.1rc1](https://pypi.org/project/apache-airflow-providers-mysql/4.0.1rc1)
   - [ ] [Fixed MyPy errors introduced by new mysql-connector-python (#28995)](https://github.com/apache/airflow/pull/28995): @potiuk
## Provider [presto: 4.2.2rc1](https://pypi.org/project/apache-airflow-providers-presto/4.2.2rc1)
   - [ ] [Deprecate `delegate_to` param in GCP operators and update docs (#29088)](https://github.com/apache/airflow/pull/29088): @shahar1
## Provider [sftp: 4.2.2rc1](https://pypi.org/project/apache-airflow-providers-sftp/4.2.2rc1)
   - [ ] [Fix SFTP operator's template fields processing (#29068)](https://github.com/apache/airflow/pull/29068): @potiuk
   - [ ] [FTP operator has logic in __init__ (#29073)](https://github.com/apache/airflow/pull/29073): @snjypl
## Provider [snowflake: 4.0.3rc1](https://pypi.org/project/apache-airflow-providers-snowflake/4.0.3rc1)
   - [ ] [Provide the missing connection id for the parent classes of snowflake operators (#29211)](https://github.com/apache/airflow/pull/29211): @hussein-awala
   - [ ] [Snowflake Provider Package - hide host from UI (#29208)](https://github.com/apache/airflow/pull/29208): @dwreeves
## Provider [tableau: 4.1.0rc1](https://pypi.org/project/apache-airflow-providers-tableau/4.1.0rc1)
   - [x] [(#29353) feat: TableauOperator.template_fields = find, match_with (#29360)](https://github.com/apache/airflow/pull/29360): @seunggabi
## Provider [trino: 4.3.2rc1](https://pypi.org/project/apache-airflow-providers-trino/4.3.2rc1)
   - [ ] [Deprecate `delegate_to` param in GCP operators and update docs (#29088)](https://github.com/apache/airflow/pull/29088): @shahar1

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-by-contributors)

**Contributors are also encouraged to cast vote in the [mailing list thread](https://lists.apache.org/thread/yg0gz8g5r38gcpnr9301f6sj2km3qlgc).**

All users involved in the PRs:
@BasPH @VladaZakharova @bkossakowska @pankajkoti @phanikumv @MaksYermak @RachitSharma2001 @vandonr-amz @IAL32 @raphaelauv @Taragolis @dwreeves @potiuk @snjypl @dstandish @vchiapaikeo @eladkal @shahar1 
@jedcunningham @csm10495 @josh-fell @joarobles @johannaojeling @o-nikolas @wonhyeongseo @seunggabi @MrGeorgeOwl @hussein-awala @maggesssss

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by pankajkoti** [comment]
Thanks @eladkal . I tested my PR https://github.com/apache/airflow/pull/29349 and it works fine.

**Comment by seunggabi** [comment]
Thanks @eladkal .
I tested a minute ago.

> https://github.com/apache/airflow/pull/29360: @seunggabi
> https://pypi.org/project/apache-airflow-providers-tableau/4.1.0rc1/

It was works.
```
from airflow.providers.tableau.operators.tableau import TableauOperator

...

task_refresh_workbook_blocking = TableauOperator(
    resource="workbooks",
    method="refresh",
    match_with="{{ params.match_with }}",
    find="{{ params.find }}",
    blocking_refresh=True,
    task_id="refresh_tableau_workbook_blocking",
    dag=dag,
)
```

<img width="548" alt="스크린샷 2023-02-10 오전 12 11 31" src="https://user-images.githubusercontent.com/8468371/217852501-b9cc32e1-f3b0-448a-878b-1ed53c3fb4d7.png">

**Comment by johannaojeling** [comment]
#28764 is tested with the Beam RC and works as expected

**Comment by csm10495** [comment]
#28808 still seems legit

**Comment by vchiapaikeo** [comment]
https://github.com/apache/airflow/pull/28959 looks good

`write_on_empty=False (default)`
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/9200263/217911454-ce12ad5d-c11c-43a5-9f9b-b987f61d5706.png">

`write_on_empty=True`
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/9200263/217911094-43aac6ac-01d9-4b79-ab97-0b0fef583f0e.png">

**Comment by o-nikolas** [comment]
I added code to kill the process while running to test the emr `on_kill` changes, and the cleanup code ran successfully (and I confirmed the resource was deleted in my AWS account):

```
INFO  [airflow.task.operators] Job flow with id j-1ADYKTIV4THO5 created
INFO  [airflow.task.operators] SLEEPING NOW, KILL THE PROCESS TO TEST ON_KILL
INFO  [airflow.task.operators] TRYING TO KILL MYSELF
ERROR [airflow.task] Received SIGTERM. Terminating subprocesses.
INFO  [airflow.task.operators] Terminating job flow j-1ADYKTIV4THO5
```

**Comment by josh-fell** [comment]
Thanks for organizing @eladkal! 

All of the dbt Cloud changes look good as well as the Python API docs change in #29041.

**Comment by eladkal** [comment]
Thank you everyone.
Providers are released
I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
