### ISSUE TITLE
Status of testing Providers that were prepared on February 18, 2023

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#29607]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 7.2.1rc1](https://pypi.org/project/apache-airflow-providers-amazon/7.2.1rc1)
   - [x] [Explicitly handle exceptions raised by config parsing in AWS provider (#29587)](https://github.com/apache/airflow/pull/29587): @potiuk
   - [x] [Fix docstring for EcsRunTaskOperator region_name -> region (#29562)](https://github.com/apache/airflow/pull/29562): No testing required
## Provider [apache.beam: 4.3.0rc1](https://pypi.org/project/apache-airflow-providers-apache-beam/4.3.0rc1)
   - [ ] [Get rid of state in Apache Beam provider hook (#29503)](https://github.com/apache/airflow/pull/29503): @dannikay
## Provider [apache.hive: 5.1.3rc1](https://pypi.org/project/apache-airflow-providers-apache-hive/5.1.3rc1)
   - [x] [Validate Hive Beeline parameters (#29502)](https://github.com/apache/airflow/pull/29502): @potiuk
## Provider [apache.sqoop: 3.1.1rc1](https://pypi.org/project/apache-airflow-providers-apache-sqoop/3.1.1rc1)
   - [x] [Move libjars parameter in Sqoop Hook to Hook parameter (#29500)](https://github.com/apache/airflow/pull/29500): @potiuk
## Provider [cncf.kubernetes: 5.2.1rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/5.2.1rc1)
   - [x] [Fix @task.kubernetes to receive input and send output (#28942)](https://github.com/apache/airflow/pull/28942): @vchiapaikeo
## Provider [docker: 3.5.1rc1](https://pypi.org/project/apache-airflow-providers-docker/3.5.1rc1)
   - [ ] [fix template_fields in the decorator `task.docker` (#29586)](https://github.com/apache/airflow/pull/29586): @jeffery9876
## Provider [google: 8.10.0rc1](https://pypi.org/project/apache-airflow-providers-google/8.10.0rc1)
   - [ ] [Add defer mode to GKECreateClusterOperator and GKEDeleteClusterOperator (#28406)](https://github.com/apache/airflow/pull/28406): @MrGeorgeOwl
   - [x] [Move cloud_sql_binary_path from connection to Hook (#29499)](https://github.com/apache/airflow/pull/29499): @potiuk
   - [x] [Check that cloud sql provider version is valid (#29497)](https://github.com/apache/airflow/pull/29497): @potiuk
   - [ ] [`GoogleDriveHook`: Add folder_id param to upload_file (#29477)](https://github.com/apache/airflow/pull/29477): @shahar1
        Linked issues:
     - [Google provider doesn't let uploading file to a shared drive (#29552)](https://github.com/apache/airflow/issues/29552) @aru-trackunit
   - [ ] [Add documentation for BigQuery transfer operators (#29466)](https://github.com/apache/airflow/pull/29466): @shahar1
## Provider [http: 4.2.0rc1](https://pypi.org/project/apache-airflow-providers-http/4.2.0rc1)
   - [ ] [Add HttpHookAsync for deferrable implementation (#29038)](https://github.com/apache/airflow/pull/29038): @sunank200
## Provider [microsoft.azure: 5.2.1rc1](https://pypi.org/project/apache-airflow-providers-microsoft-azure/5.2.1rc1)
   - [x] [Handle deleting more than 256 blobs using `WasbHook.delete_file()` (#29565)](https://github.com/apache/airflow/pull/29565): @josh-fell
## Provider [sftp: 4.2.3rc1](https://pypi.org/project/apache-airflow-providers-sftp/4.2.3rc1)
   - [ ] [Fix sftp sensor with pattern (#29467)](https://github.com/apache/airflow/pull/29467): @BenediktRamsauer
## Provider [snowflake: 4.0.4rc1](https://pypi.org/project/apache-airflow-providers-snowflake/4.0.4rc1)
   - [ ] [Fix SQL syntax for files parameter in CopyFromExternalStageToSnowflakeOperator (#29437)](https://github.com/apache/airflow/pull/29437): @bnix

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-by-contributors)

All users involved in the PRs:
@potiuk @vchiapaikeo @bnix @shahar1 @jeffery9876 @BenediktRamsauer @MrGeorgeOwl @deanmorin @josh-fell @dannikay @sunank200

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by eladkal** [comment]
Contributors are also encouraged to cast vote in the [mailing list thread](https://lists.apache.org/thread/9nc26lo9xoywntfgbpxk3z0rdn8wrq2d).

**Comment by potiuk** [comment]
Checked: #29587, #29502, #29500, #29499 , #29497. All are good.

**Comment by josh-fell** [comment]
#29565 looks good.

Thanks for organizing @eladkal!

**Comment by aru-trackunit** [comment]
#29552 Tested and it works. 
From my perspective there are 2 issues.
- proper documentation on how to use `drive_folder` and `folder_id` arguments together (as they can be confusing)
- log doesn't print the exact path where the file will be located. (I believe log shouldn't print the path, or print it correctly, is it worth making X amount of calls and go up the folder tree, since google returns only parent directory.

I am happy to address (in this or next release) them just let me know your thoughts

**Comment by eladkal** [comment]
> #29552 Tested and it works. From my perspective there are 2 issues.
> 
> * proper documentation on how to use `drive_folder` and `folder_id` arguments together (as they can be confusing)
> * log doesn't print the exact path where the file will be located. (I believe log shouldn't print the path, or print it correctly, is it worth making X amount of calls and go up the folder tree, since google returns only parent directory.
> 
> I am happy to address (in this or next release) them just let me know your thoughts

Feel free to raise PR to adress this since these are not regressions it will not block this release.

**Comment by vchiapaikeo** [comment]
https://github.com/apache/airflow/pull/28942 still looks good. 

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/9200263/220392003-9ee1fda4-0167-497e-8531-cbd0363530fb.png">

Thanks Elad!

**Comment by eladkal** [comment]
Thank you everyone.
Providers are released
I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).

**Comment by BenediktRamsauer** [comment]
I'm a bit late to the party, but #29467 is tested on [sftp: 4.2.4](https://pypi.org/project/apache-airflow-providers-sftp/4.2.4/) and is working.

Thank you for the work.
