### ISSUE TITLE
Add Triggers to provider information

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#29918]
### Body

We do not have triggers information exposed in provider info but some Providerst already expose some (for example cncf.kubernetes). 

What needs to be done:

- [x] add triggers to provider.yaml schema https://github.com/apache/airflow/pull/29950
- [x] add triggers to provider_info schema https://github.com/apache/airflow/pull/33654
- [x] expose triggers via Providers Manager https://github.com/apache/airflow/pull/31278
- [x] add CLI triggers command to `airflow providers`  https://github.com/apache/airflow/pull/31278
- [x] add automated exposure of triggers in the docs
- [x] check trigge classes are present in provider.yaml in unit tests

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
cc: @eladkal

**Comment by Bowrna** [comment]
hi @potiuk I don't see trigger information as part of `providers.yaml` for `cncf.kubernetes` file too. Am i looking at the wrong place?

https://github.com/apache/airflow/blob/main/airflow/providers/cncf/kubernetes/provider.yaml#L76-L112

**Comment by potiuk** [comment]
Yep. That's the point. We don't have them there and we need to add them :)

**Comment by Bowrna** [comment]
I don't think I understood the changes in provider_info_schema
do you mean the below file? what changes has to go into this file to support triggers?
https://github.com/apache/airflow/blob/main/airflow/provider_info.schema.json#L1-L10

**Comment by potiuk** [comment]
Those Schemas (JSON schemas) define what is the allowed content of the provider.yaml  (provider.yaml.schema.json) and what kind of information can be exposed via provider_info entrypoint in the provider packages (provier_info.schema.json). Both need to be updated to add optional "triggerer" information.

**Comment by Bowrna** [comment]
the `provider_info.schema.json` file doesn't contain information about hooks, sensors, transfers, or operators as such. Does it have to contain `triggers` information alone? 
could you explain to me why `triggers` alone have to be included? @potiuk

**Comment by potiuk** [comment]
We expose the information there also for connections and other things:


```
    "connection-types": {
      "type": "array",
      "description": "Map of connection types mapped to hook class names.",
      "items": {
        "type": "object",
        "properties": {
          "connection-type": {
            "description": "Type of connection defined by the provider",
            "type": "string"
          },
          "hook-class-name": {
            "description": "Hook class name that implements the connection type",
            "type": "string"
          }
        }
      },
      "required": ["connection-type", "hook-class-name"]
    },
    "extra-links": {
      "type": "array",
      "description": "Operator class names that provide extra link functionality",
      "items": {
        "type": "string"
      }
    },
   ...
```

This is what I call "core extensions" - i.e. the ways how providers are adding implementation  of capabilities that Airflow exposes as public interface. It is nicely summarized here (this page is automatically generated based on the provider.yaml information, but also it is exposed for runtime query via CLI (`airflow providers` subcommands such as `hooks`, `auth` etc.) 

This information is automatically discovered via ProvidersManager based on the information exposed via "get_provider_info" entrypoint (Providers Manager automatically queries the installed providers to get that information and it uses "provider_info.schema" to know how to query (simply get_provider_info returns a dict that conforms to the schema which is selected subset of information in provider.yaml.



https://airflow.apache.org/docs/apache-airflow-providers/core-extensions/index.html


This is in order to be able to actively "query" the providers and figure out in automated way wha

**Comment by eladkal** [comment]
@Bowrna are you working on any of the other sub tasks listed in the issue?

**Comment by Bowrna** [comment]
I will pick one more task from this list and start working on it before today @eladkal

**Comment by Bowrna** [comment]
can expect delay at my side ( for a week) as i am relocating home. sorry @eladkal i thought i could find time in between and check this, but i am wrong.

**Comment by pankajastro** [comment]
I think we can mark the below task as done PR https://github.com/apache/airflow/pull/30822
> expose triggers via Providers Manager
 add CLI triggers command to airflow providers

**Comment by potiuk** [comment]
Marked :)

**Comment by potiuk** [comment]
` check trigge classes are present in provider.yaml in unit tests`  -> that is already there.

**Comment by subhramit** [comment]
Hi, I took a dig at finishing this in https://github.com/apache/airflow/pull/71975. Would appreciate any feedback!
