### ISSUE TITLE
Status of testing Providers that were prepared on March 07, 2023

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#29948]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [hashicorp: 3.3.0rc2](https://pypi.org/project/apache-airflow-providers-hashicorp/3.3.0rc2)
   - [x] [Support multiple mount points in Vault backend secret (#29734)](https://github.com/apache/airflow/pull/29734): @hussein-awala
   - [x] [Fix empty paths in Vault secrets backend (#29908)](https://github.com/apache/airflow/pull/29908): @hussein-awala

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-by-contributors)

All users involved in the PRs:
@hussein-awala

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by hussein-awala** [comment]
I tested #29734  and #29908 and they work as expected :tada:

**Comment by aru-trackunit** [comment]
@eladkal Did this pull request got forgotten? https://github.com/apache/airflow/pull/29694
Please let me know if I should do something about it to make it visible.

**Comment by potiuk** [comment]
> @eladkal Did this pull request got forgotten? #29694 Please let me know if I should do something about it to make it visible.

Only Hashicorp ad-hoc release was released then. plese be patient, google changes will be released in  the next wave
