### ISSUE TITLE
Status of testing Providers that were prepared on April 09, 2023

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#30553]
I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 7.4.1rc1](https://pypi.org/project/apache-airflow-providers-amazon/7.4.1rc1)
   - [x] [Fix `RedshiftResumeClusterOperator` deferrable implementation (#30370)](https://github.com/apache/airflow/pull/30370): @phanikumv
   - [x] [add more info to quicksight errors (#30466)](https://github.com/apache/airflow/pull/30466): @vandonr-amz
   - [ ] [Add s3_bucket to template fields in S3 to SFTP operator (#30472)](https://github.com/apache/airflow/pull/30472): @happilyeverafter95
   - [x] [Add s3_bucket to template fields in SFTP to S3 operator (#30444)](https://github.com/apache/airflow/pull/30444): @potiuk
## Provider [cncf.kubernetes: 6.0.0rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/6.0.0rc1)
   - [x] [Use default connection id for KubernetesPodOperator (#28848)](https://github.com/apache/airflow/pull/28848): @lwyszomi
   - [ ] [Set limits for XCOM pod (#28125)](https://github.com/apache/airflow/pull/28125): @dolfinus
   - [x] [Add mechanism to suspend providers (#30422)](https://github.com/apache/airflow/pull/30422): @potiuk
## Provider [google: 9.0.0rc1](https://pypi.org/project/apache-airflow-providers-google/9.0.0rc1)
   - [x] [Update DV360 operators to use API v2 (#30326)](https://github.com/apache/airflow/pull/30326): @lwyszomi
   - [x] [Fix dynamic imports in google ads vendored in library (#30544)](https://github.com/apache/airflow/pull/30544): @potiuk
   - [ ] [Add deferrable mode to GKEStartPodOperator (#29266)](https://github.com/apache/airflow/pull/29266): @VladaZakharova
   - [x] [BigQueryHook list_rows/get_datasets_list can return iterator (#30543)](https://github.com/apache/airflow/pull/30543): @vchiapaikeo
   - [x] [Fix cloud build async credentials (#30441)](https://github.com/apache/airflow/pull/30441): @tnk-ysk
## Provider [microsoft.azure: 5.3.1rc1](https://pypi.org/project/apache-airflow-providers-microsoft-azure/5.3.1rc1)
   - [x] [Fix AzureDataFactoryPipelineRunLink UI link generation (#30514)](https://github.com/apache/airflow/pull/30514): @hussein-awala
## Provider [smtp: 1.0.1rc1](https://pypi.org/project/apache-airflow-providers-smtp/1.0.1rc1)
   - [x] [`EmailOperator`: fix wrong assignment of `from_email` (#30524)](https://github.com/apache/airflow/pull/30524): @vanducng
   - [x] [Accept None for `EmailOperator.from_email` to load it from smtp connection (#30533)](https://github.com/apache/airflow/pull/30533): @hussein-awala

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-by-contributors)

All users involved in the PRs:
@happilyeverafter95 @dolfinus @VladaZakharova @phanikumv @potiuk @tnk-ysk @hussein-awala @vandonr-amz @vanducng @vchiapaikeo @lwyszomi

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by vanducng** [comment]
Confirm #30524 bug already got fixed in [smtp: 1.0.1rc1](https://pypi.org/project/apache-airflow-providers-smtp/1.0.1rc1). Thanks.

**Comment by vandonr-amz** [comment]
👍

**Comment by vanducng** [comment]
[google: 9.0.0rc1](https://pypi.org/project/apache-airflow-providers-google/9.0.0rc1) also works well with our google ads and dv360 task.

**Comment by vchiapaikeo** [comment]
https://github.com/apache/airflow/pull/30543 also still looks fine. Thank you, Elad!

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/9200263/230792277-9a9968c0-1d9e-4ba2-b3b7-98553f8f6a98.png">

**Comment by potiuk** [comment]
> [google: 9.0.0rc1](https://pypi.org/project/apache-airflow-providers-google/9.0.0rc1) also works well with our google ads and dv360 task.

🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by potiuk** [comment]
Tested mine. All works.

**Comment by raphaelauv** [comment]
```
https://github.com/apache/airflow/pull/28848
```
work

**Comment by hussein-awala** [comment]
- https://github.com/apache/airflow/pull/30533 -> works as expected
- https://github.com/apache/airflow/pull/30514 -> it works with the connections created via the Airflow CLI (as I did when I tested the PR before), but not directly with the connections created from the UI, I created #30556 to describe and fix the problem, and #30557 to clean the Azure provider code. Since we can create the connection from the CLI or the environment variables, and even we can edit the UI connection manually once it is created, no need to block the release and create a new one, we can add the fix (and maybe the full clean) to the next release.

**Comment by tnk-ysk** [comment]
I tested https://github.com/apache/airflow/pull/30441, it works as expected

**Comment by eladkal** [comment]
> https://github.com/apache/airflow/pull/30514 -> it works with the connections created via the Airflow CLI (as I did when I tested the PR before), but not directly with the connections created from the UI, I created https://github.com/apache/airflow/pull/30556 to describe and fix the problem, and https://github.com/apache/airflow/issues/30557 to clean the Azure provider code. Since we can create the connection from the CLI or the environment variables, and even we can edit the UI connection manually once it is created, no need to block the release and create a new one, we can add the fix (and maybe the full clean) to the next release.

since this is the only fix in the release for azure I tend to drop azure from this wave. I think it's preferred to cut RC2 after the fixes are ready

**Comment by potiuk** [comment]
> since this is the only fix in the release for azure I tend to drop azure from this wave. I think it's preferred to cut RC2 after the fixes are ready

We could also apply what we agreed about - shorter voting period for RC2+
* https://github.com/apache/airflow/pull/30037/files

We could potentially merge the change now, prepare RC2 for azure only and release them all together when voting period ends. Might be good time to try this method to see if there is anything to fix in our process to follow this route.

**Comment by potiuk** [comment]
We will need an RC2 for google provider too - (found by @cgadam - fix in #30564).

**Comment by utkarsharma2** [comment]
Works well with AstroSDk.

**Comment by phanikumv** [comment]
#30370 works well.

```
2023-04-10, 14:00:26 UTC] {standard_task_runner.py:55} INFO - Started process 3123 to run task
[2023-04-10, 14:00:26 UTC] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'example_async_redshift_cluster_management', 'resume_redshift_cluster', 'manual__2023-04-10T13:55:51.894401+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/example_redshift_cluster_management.py', '--cfg-path', '/tmp/tmpsyc34091']
[2023-04-10, 14:00:26 UTC] {standard_task_runner.py:83} INFO - Job 10: Subtask resume_redshift_cluster
[2023-04-10, 14:00:26 UTC] {task_command.py:389} INFO - Running <TaskInstance: example_async_redshift_cluster_management.resume_redshift_cluster manual__2023-04-10T13:55:51.894401+00:00 [running]> on host 101451e0c77b
[2023-04-10, 14:00:26 UTC] {redshift_cluster.py:472} INFO - resume_redshift_cluster completed successfully.
[2023-04-10, 14:00:26 UTC] {redshift_cluster.py:473} INFO - Resumed cluster successfully
```

**Comment by eladkal** [comment]
Thank you everyone.
The `google` and `microsoft.azure` providers are excluded from the release and RC2 will be cut for them shortly.
other providers are released.
I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
