### ISSUE TITLE
Status of testing Providers that were prepared on April 21, 2023

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#30803]
I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 8.0.0rc1](https://pypi.org/project/apache-airflow-providers-amazon/8.0.0rc1)
   - [ ] [Remove deprecated "delegate_to" from GCP operators and hooks (#30748)](https://github.com/apache/airflow/pull/30748): @shahar1
   - [ ] [take advantage of upcoming major version release to remove deprecated things (#30755)](https://github.com/apache/airflow/pull/30755): @vandonr-amz
   - [ ] [add a stop operator to emr serverless (#30720)](https://github.com/apache/airflow/pull/30720): @vandonr-amz
   - [ ] [SqlToS3Operator - Add feature to partition SQL table (#30460)](https://github.com/apache/airflow/pull/30460): @utkarsharma2
   - [x] [New AWS sensor — DynamoDBValueSensor (#28338)](https://github.com/apache/airflow/pull/28338): @mrichman
   - [x] [Fixed logging issue in `DynamoDBValueSensor` (#30703)](https://github.com/apache/airflow/pull/30703): @mrichman
   - [ ] [DynamoDBHook - waiter_path() to consider `resource_type` or `client_type` (#30595)](https://github.com/apache/airflow/pull/30595): @utkarsharma2
   - [ ] [Add ability to override waiter delay in EcsRunTaskOperator (#30586)](https://github.com/apache/airflow/pull/30586): @vincbeck
   - [ ] [Add support in AWS Batch Operator for multinode jobs (#29522)](https://github.com/apache/airflow/pull/29522): @vandonr-amz
   - [ ] [AWS logs. Exit fast when 3 consecutive responses are returned from AWS Cloudwatch logs (#30756)](https://github.com/apache/airflow/pull/30756): @vincbeck
   - [ ] [Remove @poke_mode_only from EmrStepSensor (#30774)](https://github.com/apache/airflow/pull/30774): @vincbeck
   - [x] [Organize Amazon provider docs index (#30541)](https://github.com/apache/airflow/pull/30541): @eladkal
   - [ ] [Remove duplicate param docstring in EksPodOperator (#30634)](https://github.com/apache/airflow/pull/30634): @jlaneve
## Provider [apache.beam: 5.0.0rc1](https://pypi.org/project/apache-airflow-providers-apache-beam/5.0.0rc1)
   - [ ] [Remove deprecated "delegate_to" from GCP operators and hooks (#30748)](https://github.com/apache/airflow/pull/30748): @shahar1
   - [x] [Add mechanism to suspend providers (#30422)](https://github.com/apache/airflow/pull/30422): @potiuk
## Provider [apache.kafka: 1.0.0rc1](https://pypi.org/project/apache-airflow-providers-apache-kafka/1.0.0rc1/)
   - [x] [Add provider for Apache Kafka (#30175)](https://github.com/apache/airflow/pull/30175): @dylanbstorey
## Provider [cncf.kubernetes: 6.1.0rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/6.1.0rc1)
   - [x] [Add multiple exit code handling in skip logic for `DockerOperator` and `KubernetesPodOperator` (#30769)](https://github.com/apache/airflow/pull/30769): @eladkal
   - [x] [Skip KubernetesPodOperator task when it returns a provided exit code (#29000)](https://github.com/apache/airflow/pull/29000): @hussein-awala
## Provider [databricks: 4.1.0rc1](https://pypi.org/project/apache-airflow-providers-databricks/4.1.0rc1)
   - [ ] [Add delete inactive run functionality to databricks provider (#30646)](https://github.com/apache/airflow/pull/30646): @phanikumv
   - [x] [Databricks SQL sensor (#30477)](https://github.com/apache/airflow/pull/30477): @harishkesavarao
## Provider [dbt.cloud: 3.1.1rc1](https://pypi.org/project/apache-airflow-providers-dbt-cloud/3.1.1rc1)
   - [ ] [Merge DbtCloudJobRunAsyncSensor logic to DbtCloudJobRunSensor (#30227)](https://github.com/apache/airflow/pull/30227): @Lee-W
   - [ ] [Move typing imports behind TYPE_CHECKING in DbtCloudHook (#29989)](https://github.com/apache/airflow/pull/29989): @josh-fell
## Provider [docker: 3.6.0rc1](https://pypi.org/project/apache-airflow-providers-docker/3.6.0rc1)
   - [x] [Add multiple exit code handling in skip logic for `DockerOperator` and `KubernetesPodOperator` (#30769)](https://github.com/apache/airflow/pull/30769): @eladkal
   - [ ] [In `DockerOperator`, adding an attribute `tls_verify` to choose whether to validate certificate (#30309) (#30310)](https://github.com/apache/airflow/pull/30310): @oboki
   - [x] [Deprecate `skip_exit_code` in `DockerOperator` and `KubernetesPodOperator` (#30733)](https://github.com/apache/airflow/pull/30733): @eladkal
## Provider [google: 10.0.0rc1](https://pypi.org/project/apache-airflow-providers-google/10.0.0rc1)
   - [ ] [Remove deprecated "delegate_to" from GCP operators and hooks (#30748)](https://github.com/apache/airflow/pull/30748): @shahar1
   - [ ] [Update Google Campaign Manager360 operators to use API v4 (#30598)](https://github.com/apache/airflow/pull/30598): @VladaZakharova
   - [ ] [Update DataprocCreateCluster operator to use 'label' parameter properly (#30741)](https://github.com/apache/airflow/pull/30741): @VladaZakharova
   - [x] [BigQueryGetDataOperator should use project_id (#30651)](https://github.com/apache/airflow/pull/30651): @ying-w
   - [ ] [Display Video 360 cleanup v1 API usage (#30577)](https://github.com/apache/airflow/pull/30577): @lwyszomi
## Provider [microsoft.azure: 6.0.0rc1](https://pypi.org/project/apache-airflow-providers-microsoft-azure/6.0.0rc1)
   - [ ] [Remove deprecated "delegate_to" from GCP operators and hooks (#30748)](https://github.com/apache/airflow/pull/30748): @shahar1
   - [ ] [Add deferrable mode to `WasbBlobSensor` (#30488)](https://github.com/apache/airflow/pull/30488): @phanikumv
## Provider [mysql: 5.0.0rc1](https://pypi.org/project/apache-airflow-providers-mysql/5.0.0rc1)
   - [ ] [Remove mysql-connector-python (#30487)](https://github.com/apache/airflow/pull/30487): @moiseenkov
## Provider [presto: 5.0.0rc1](https://pypi.org/project/apache-airflow-providers-presto/5.0.0rc1)
   - [ ] [Remove deprecated "delegate_to" from GCP operators and hooks (#30748)](https://github.com/apache/airflow/pull/30748): @shahar1
   - [x] [Add mechanism to suspend providers (#30422)](https://github.com/apache/airflow/pull/30422): @potiuk
## Provider [snowflake: 4.0.5rc1](https://pypi.org/project/apache-airflow-providers-snowflake/4.0.5rc1)
   - [x] [Update documentation for snowflake provider 4.0 breaking change (#30020)](https://github.com/apache/airflow/pull/30020): @potiuk
## Provider [sqlite: 3.3.2rc1](https://pypi.org/project/apache-airflow-providers-sqlite/3.3.2rc1)
   - [ ] [Use connection URI in SqliteHook (#28721)](https://github.com/apache/airflow/pull/28721): @feluelle
## Provider [trino: 5.0.0rc1](https://pypi.org/project/apache-airflow-providers-trino/5.0.0rc1)
   - [ ] [Remove deprecated "delegate_to" from GCP operators and hooks (#30748)](https://github.com/apache/airflow/pull/30748): @shahar1
   - [x] [Add mechanism to suspend providers (#30422)](https://github.com/apache/airflow/pull/30422): @potiuk

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-by-contributors)

All users involved in the PRs:
@feluelle @ying-w @vandonr-amz @eladkal @mrichman @hussein-awala @lwyszomi @utkarsharma2 @jlaneve @josh-fell @vincbeck @shahar1 @Lee-W @harishkesavarao @oboki @phanikumv @moiseenkov @potiuk 
@VladaZakharova @dylanbstorey 

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
Looked at my changes - they were doc or "cI" only.

**Comment by vandonr-amz** [comment]
System tests revealed that RdsCreateDbSnapshotOperator had a bad default value for `aws_conn_id` (something that was hidden under a deprecation warning before). I don't know what percentage of users rely on the default value for this, but it should be fixed before we package this I think.
There is a PR for that: #30804

**Comment by eladkal** [comment]
amazon 8.0.0rc1 will be excluded from the release and will cut rc2 due to https://github.com/apache/airflow/pull/30806
this will happen after I release the other providers.
Please continue to test rc1 as usual.

**Comment by vandonr-amz** [comment]
ok then if https://github.com/apache/airflow/pull/30806 gets integrated in rc2, ignore my comment above.

**Comment by dylanbstorey** [comment]
Test DAGs worked as expected for apache.kafka 1.0.0rc1.

**Comment by harishkesavarao** [comment]
Test DAG ran successfully with `databricks: 4.1.0rc1`.

**Comment by ying-w** [comment]
I tested my change locally and it works

**Comment by mrichman** [comment]
Tested my changes successfully:

https://github.com/apache/airflow/pull/28338
https://github.com/apache/airflow/pull/30703
