### ISSUE TITLE
Status of testing of Apache Airflow 2.6.1rc3

### ISSUE THREAD

**Issue by ephraimbuddy** [apache/airflow#31202]
### Body

We are kindly requesting that contributors to [Apache Airflow RC 2.6.1rc1](https://pypi.org/project/apache-airflow/2.6.1rc1/) help test the RC.

Please let us know by commenting if the issue is addressed in the latest RC.

- [ ] [Prevent DagRun's `start_date` from reset (#30124) (#30125)](https://github.com/apache/airflow/pull/30125): @dimonchik-suvorov
     Linked issues:
     - [DagRun's start_date updated when user clears task of the running Dagrun (#30124)](https://github.com/apache/airflow/issues/30124)
- [ ] [Reenable clear on TaskInstanceModelView for role User (#30415)](https://github.com/apache/airflow/pull/30415): @eejbyfeldt
- [x] [Table for affected tasks in grid actions (#30633)](https://github.com/apache/airflow/pull/30633): @pierrejeambrun 
- [ ] [Fix backfill KeyError when try_number out of sync (#30653)](https://github.com/apache/airflow/pull/30653): @ephraimbuddy @sarvothaman @huozhanfeng @awbush
     Linked issues:
     - [[Bug] Backfill job fails to run when there are tasks run into rescheduling state. (#17305)](https://github.com/apache/airflow/pull/17305)
     - [Backfill crashes with "KeyError: TaskInstanceKey" when task has retries (#13322)](https://github.com/apache/airflow/issues/13322)
     - [Add unittest for #17305 (#18806)](https://github.com/apache/airflow/pull/18806)
- [ ] [Fix problem with displaying graph (#30765)](https://github.com/apache/airflow/pull/30765): @meujin
- [x] [Fix mappedStates case (#30916)](https://github.com/apache/airflow/pull/30916): @bbovenzi
- [x] [Improve task group UI in new graph (#30918)](https://github.com/apache/airflow/pull/30918): @bbovenzi
- [x] [Remove print from dag trigger command (#30921)](https://github.com/apache/airflow/pull/30921): @pankajastro
- [x] [Include node height/width in center-on-task logic (#30924)](https://github.com/apache/airflow/pull/30924): @bbovenzi
- [x] [Fix `order_by` request in list DAG rest api (#30926)](https://github.com/apache/airflow/pull/30926): @pankajastro
- [ ] [Use the Task Group explicitly passed to 'partial' if any (#30933)](https://github.com/apache/airflow/pull/30933): @LuizArmesto
     Linked issues:
     - [Tasks created using "dynamic task mapping" ignore the Task Group passed as argument (#30932)](https://github.com/apache/airflow/issues/30932)
- [ ] [Add support for dynamic tasks with template fields that contain `pandas.DataFrame` (#30943)](https://github.com/apache/airflow/pull/30943): @tatiana
- [x] [Upgrade PIP to 23.1.2 (#30964)](https://github.com/apache/airflow/pull/30964): @potiuk
- [ ] [Update incorrect config values (#30969)](https://github.com/apache/airflow/pull/30969): @ephraimbuddy
- [ ] [Fix Pool schema OpenAPI spec (#30973)](https://github.com/apache/airflow/pull/30973): @pierrejeambrun
- [x] [Fix output for `airflow providers get` command (#30978)](https://github.com/apache/airflow/pull/30978): @pankajastro
- [x] [Fix unable to remove DagRun and TaskInstance with note (#30987)](https://github.com/apache/airflow/pull/30987): @herlambang
     Linked issues:
     - [Unable to remove DagRun and TaskInstance with note (#30984)](https://github.com/apache/airflow/issues/30984)
- [x] [Fix missing models in API documentation. (#31021)](https://github.com/apache/airflow/pull/31021): @potiuk
     Linked issues:
     - [Add Public Interface description to Airflow documentation (#28300)](https://github.com/apache/airflow/pull/28300)
- [ ] [Move TaskInstanceKey to a separate file to fix circular import from kubernetes_helper_functions.py (#31033)](https://github.com/apache/airflow/pull/31033): @LipuFei
     Linked issues:
     - [DB migration job fails with circular import (#30988)](https://github.com/apache/airflow/issues/30988)
- [ ] [Fix issue in pre-importing modules in zipfile (#31061)](https://github.com/apache/airflow/pull/31061): @ephraimbuddy
- [ ] [Update provider to apache-hive suffix. (#31068)](https://github.com/apache/airflow/pull/31068): @davidshur
     Linked issues:
     - [[BUG] apache.hive extra is referencing incorrect provider name (#31067)](https://github.com/apache/airflow/issues/31067)
- [x] [Fix template error when iterating None value and fix params documentation (#31078)](https://github.com/apache/airflow/pull/31078): @herlambang @Limess
     Linked issues:
     - [Exception when manually triggering dags via UI with `params` defined. (#31014)](https://github.com/apache/airflow/issues/31014)
- [ ] [Fix Spacing for DagBag.dagbag_report()'s Output (#31095)](https://github.com/apache/airflow/pull/31095): @mtsadler-branch
- [ ] [fix MappedTaskGroup import in taskinstance (#31100)](https://github.com/apache/airflow/pull/31100): @JCoder01
- [ ] [Ensure that we check worker for served logs if no local or remote logs found (#31101)](https://github.com/apache/airflow/pull/31101): @dstandish @juraa14 @zachliu
     Linked issues:
     - [Logs no longer shown after task completed CeleryExecutor (#31059)](https://github.com/apache/airflow/issues/31059)
     - [Incorrect logic when reading from local log files (#30997)](https://github.com/apache/airflow/issues/30997)
- [ ] [Move interleave_timestamp_parser config to section logging (#31102)](https://github.com/apache/airflow/pull/31102): @dstandish
- [x] [Fix unmasked env var on task detail view (#31125)](https://github.com/apache/airflow/pull/31125): @herlambang @chriscmorgan
     Linked issues:
     - [Connection password values appearing unmasked in the "Task Instance Details" -> "Environment" field (#30089)](https://github.com/apache/airflow/issues/30089)
- [ ] [Remove worrying log message about redaction caused by OpenLineage plugin (#31149)](https://github.com/apache/airflow/pull/31149): @ashb
- [ ] [Ensure the KPO runs pod mutation hooks correctly (#31173)](https://github.com/apache/airflow/pull/31173): @jedcunningham
- [ ] [Fix section name reference for api_client_retry_configuration (#31174)](https://github.com/apache/airflow/pull/31174): @dstandish
- [ ] [Fix timestamp parse failure for k8s executor pod tailing (#31175)](https://github.com/apache/airflow/pull/31175): @dstandish
- [ ] [Make sure that DAG processor job row has filed value in `job_type` column (#31182)](https://github.com/apache/airflow/pull/31182): @AmFlint
- [x] [Fix calculation of health check threshold for SchedulerJob (#31277)](https://github.com/apache/airflow/pull/31277): @potiuk 

Thanks to all who contributed to the release (probably not a complete list!):
@pierrejeambrun @LipuFei @pankajastro @JCoder01 @davidshur @zachliu @meujin @LuizArmesto @Limess @AmFlint @juraa14 @jedcunningham @tatiana @bbovenzi @huozhanfeng @herlambang @sarvothaman @chriscmorgan @potiuk @eejbyfeldt @dstandish @awbush @mtsadler-branch @dimonchik-suvorov @ashb @ephraimbuddy

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by LipuFei** [comment]
Hi @ephraimbuddy , I've just tested https://github.com/apache/airflow/pull/31033, but the DB job still fails due to another circular import. I found a fix for this. Can I directly make a new PR or should I also raise an issue for this?

**Comment by herlambang** [comment]
**UAT Test Result v2.6.1rc1**

**Dashboard Footer:**  
Version: v2.6.1  
Git Version: .release:06e3aa3e40948efcb53e9320b78d6b33b875ad12  

**Fix unable to remove DagRun and TaskInstance with note (#30987)** ✅ 

- open page `/dagrun/list/`
- edit 1 dag run, fill note field and save
- delete dag run previously edited
- dag run deleted
- open page `/taskinstance/list/`
- edit 1 task, fill note field and save
- delete task instance previously edited
- task instance deleted


**Fix template error when iterating None value and fix params documentation (#31078)** ✅ 

- Create dag with params
```python
"array_param": Param(
    None,
    type=["null", "array"],
),
```
- Click dag's play button, select `Trigger DAG w/ config`
- Page loaded without error
- Form field `array_param` shown with empty textbox
- `Generated Configuration JSON` shows
```json
{
    "array_param": null
}
```

**Fix unmasked env var on task detail view (#31125)** ✅ 

- Create variable with name contains `secret`
- Set environment variable with secret variable in an operator
```python
run_this = BashOperator(
    task_id="masked_envvar",
    bash_command="echo 1",
    env={
        "ENVVAR_NAME": "{{ var.value.secret_service }}"
    },
)
```
- Run the dag and open task instance detail page
- Task Attributes `env` is masked
```
env	{'ENVVAR_NAME': '***'}
```

**Comment by ephraimbuddy** [comment]
> Hi @ephraimbuddy , I've just tested #31033, but the DB job still fails due to another circular import. I found a fix for this. Can I directly make a new PR or should I also raise an issue for this?
> 
> **UPDATE:** I've created a PR to fix this #31204 **UPDATE 2:** #31204 was merged.

Thanks @LipuFei . I have created rc2 with your fix. Verify and let me know how it goes

**Comment by potiuk** [comment]
Checked PIP/docs to see if missing models are fixed  - looks good

**Comment by LipuFei** [comment]
> > Hi @ephraimbuddy , I've just tested #31033, but the DB job still fails due to another circular import. I found a fix for this. Can I directly make a new PR or should I also raise an issue for this?
> > **UPDATE:** I've created a PR to fix this #31204 **UPDATE 2:** #31204 was merged.
> 
> Thanks @LipuFei . I have created rc2 with your fix. Verify and let me know how it goes

Checked https://github.com/apache/airflow/pull/31033 and https://github.com/apache/airflow/pull/31204 with `2.6.1rc2`. Looks good! The migration job can run successfully.

Thanks! @ephraimbuddy

**Comment by potiuk** [comment]
Tested the https://github.com/apache/airflow/pull/31277 behaviour. Works as expected now:

1) started airflow
2) both jobs check and UI show it as live
3) kill scheduler FORECEFULLY (i.e. with -9)
4) still alive
5s 
5) still alive
10s
6) still alive
....

7)
35 seconds:

> The scheduler does not appear to be running. Last heartbeat was received 35 s ago.

Everything as expected

**Comment by pankajastro** [comment]
Tested https://github.com/apache/airflow/pull/30921 https://github.com/apache/airflow/pull/30926 https://github.com/apache/airflow/pull/30978 looks good. thanks!

**Comment by ephraimbuddy** [comment]
2.6.1 has been released. Thank you all for testing this release candidate.
