### ISSUE TITLE
Status of testing Providers that were prepared on May 19, 2023

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#31322]
I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 8.1.0rc2](https://pypi.org/project/apache-airflow-providers-amazon/8.1.0rc2)
   - [x] [DynamoDBToS3Operator - Add a feature to export the table to a point in time. (#31142)](https://github.com/apache/airflow/pull/31142): @utkarsharma2
   - [x] [Add deferrable param in SageMakerTransformOperator (#31063)](https://github.com/apache/airflow/pull/31063): @pankajkoti
   - [x] [Add deferrable param in SageMakerTrainingOperator (#31042)](https://github.com/apache/airflow/pull/31042): @pankajkoti
   - [x] [Add deferrable param in SageMakerProcessingOperator (#31062)](https://github.com/apache/airflow/pull/31062): @pankajkoti
   - [ ] [Add IAM authentication to Amazon Redshift Connection by AWS Connection (#28187)](https://github.com/apache/airflow/pull/28187): @IAL32
   - [x] [`StepFunctionStartExecutionOperator`: get logs in case of failure (#31072)](https://github.com/apache/airflow/pull/31072): @eladkal
   - [x] [Add on_kill to EMR Serverless Job Operator (#31169)](https://github.com/apache/airflow/pull/31169): @dacort
   - [ ] [Add Deferrable Mode for EC2StateSensor (#31130)](https://github.com/apache/airflow/pull/31130): @syedahsn
   - [ ] [Loop through paginated response to check for cluster id (#29732)](https://github.com/apache/airflow/pull/29732): @nsAstro
   - [ ] [Add template field to S3ToRedshiftOperator (#30781)](https://github.com/apache/airflow/pull/30781): @alextgu
   - [x] [Add extras links to some more EMR Operators and Sensors (#31032)](https://github.com/apache/airflow/pull/31032): @ferruzzi
   - [ ] [Add retries to S3 delete_bucket (#31192)](https://github.com/apache/airflow/pull/31192): @ferruzzi
   - [x] [Add tags param in RedshiftCreateClusterSnapshotOperator (#31006)](https://github.com/apache/airflow/pull/31006): @pankajastro
   - [ ] [improve/fix glue job logs printing (#30886)](https://github.com/apache/airflow/pull/30886): @vandonr-amz
   - [x] [Import aiobotocore only if deferrable is true (#31094)](https://github.com/apache/airflow/pull/31094): @pankajastro
   - [ ] [Update return types of `get_key` methods on `S3Hook` (#30923)](https://github.com/apache/airflow/pull/30923): @jonshea
   - [x] [Support `shareIdentifier` in BatchOperator (#30829)](https://github.com/apache/airflow/pull/30829): @phanikumv
   - [ ] [BaseAWS - Override client when resource_type is user to get custom waiters (#30897)](https://github.com/apache/airflow/pull/30897): @utkarsharma2
   - [x] [Add future-compatible mongo Hook typing (#31289)](https://github.com/apache/airflow/pull/31289): @potiuk
   - [ ] [Handle temporary credentials when resource_type is used to get custom waiters (#31333)](https://github.com/apache/airflow/pull/31333): @vincbeck
## Provider [apache.beam: 5.1.0rc2](https://pypi.org/project/apache-airflow-providers-apache-beam/5.1.0rc2)
   - [ ] [Update SDKs for google provider package (#30067)](https://github.com/apache/airflow/pull/30067): @lwyszomi
## Provider [apache.hdfs: 4.0.0rc2](https://pypi.org/project/apache-airflow-providers-apache-hdfs/4.0.0rc2)
   - [x] [Remove snakebite-py3 based HDFS hooks and sensors (#31262)](https://github.com/apache/airflow/pull/31262): @potiuk
## Provider [apache.hive: 6.1.0rc2](https://pypi.org/project/apache-airflow-providers-apache-hive/6.1.0rc2)
   - [ ] [Update return types of `get_key` methods on `S3Hook` (#30923)](https://github.com/apache/airflow/pull/30923): @jonshea
## Provider [apache.pinot: 4.1.0rc2](https://pypi.org/project/apache-airflow-providers-apache-pinot/4.1.0rc2)
   - [ ] [Add guide for Apache Pinot operators (#28653)](https://github.com/apache/airflow/pull/28653): @shahar1
## Provider [cncf.kubernetes: 7.0.0rc2](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/7.0.0rc2)
   - [ ] [Remove deprecated features from KubernetesHook (#31402)](https://github.com/apache/airflow/pull/31402): @dstandish
   - [ ] [K8s hook should still work with missing default conn (#31187)](https://github.com/apache/airflow/pull/31187): @dstandish
   - [ ] [Add protocol to define methods relied upon by KubernetesPodOperator (#31298)](https://github.com/apache/airflow/pull/31298): @dstandish
   - [ ] [fix kubernetes task decorator pickle error (#31110)](https://github.com/apache/airflow/pull/31110): @JCoder01
   - [ ] [Empty xcom result file log message more specific (#31228)](https://github.com/apache/airflow/pull/31228): @dstandish
   - [ ] [Add options to KubernetesPodOperator (#30992)](https://github.com/apache/airflow/pull/30992): @RachitSharma2001
   - [ ] [add missing read for K8S config file from conn in deferred `KubernetesPodOperator`  (#29498)](https://github.com/apache/airflow/pull/29498): @hussein-awala
## Provider [common.sql: 1.5.0rc2](https://pypi.org/project/apache-airflow-providers-common-sql/1.5.0rc2)
   - [ ] [Add conditional output processing in SQL operators (#31136)](https://github.com/apache/airflow/pull/31136): @potiuk
   - [ ] [Remove noisy log from SQL table check (#31037)](https://github.com/apache/airflow/pull/31037): @jon-evergreen
## Provider [databricks: 4.2.0rc2](https://pypi.org/project/apache-airflow-providers-databricks/4.2.0rc2)
   - [ ] [Add conditional output processing in SQL operators (#31136)](https://github.com/apache/airflow/pull/31136): @potiuk
   - [ ] [Add cancel all runs functionality to Databricks hook (#31038)](https://github.com/apache/airflow/pull/31038): @phanikumv
   - [x] [Add retry param in databrics async operator (#30744)](https://github.com/apache/airflow/pull/30744): @pankajastro
   - [ ] [Add repair job functionality to databricks hook (#30786)](https://github.com/apache/airflow/pull/30786): @phanikumv
   - [x] [Add `DatabricksPartitionSensor` (#30980)](https://github.com/apache/airflow/pull/30980): @harishkesavarao
   - [x] [Deprecate Databricks Deferrable Operator (#30761)](https://github.com/apache/airflow/pull/30761): @pankajastro
## Provider [dbt.cloud: 3.2.0rc2](https://pypi.org/project/apache-airflow-providers-dbt-cloud/3.2.0rc2)
   - [x] [Optimize deferrable mode execution in `DbtCloudJobRunSensor` (#30968)](https://github.com/apache/airflow/pull/30968): @phanikumv
   - [ ] [Optimize deferrable execution mode for `DbtCloudRunJobOperator` (#31188)](https://github.com/apache/airflow/pull/31188): @phanikumv
## Provider [elasticsearch: 4.5.0rc2](https://pypi.org/project/apache-airflow-providers-elasticsearch/4.5.0rc2)
   - [x] [Upper-bind elasticearch integration (#31255)](https://github.com/apache/airflow/pull/31255): @potiuk
## Provider [google: 10.1.0rc2](https://pypi.org/project/apache-airflow-providers-google/10.1.0rc2)
   - [ ] [Add deferrable mode to DataprocInstantiateInlineWorkflowTemplateOperator (#30878)](https://github.com/apache/airflow/pull/30878): @bkossakowska
   - [x] [Add deferrable mode to `GCSObjectUpdateSensor` (#30579)](https://github.com/apache/airflow/pull/30579): @phanikumv
   - [ ] [Add protocol to define methods relied upon by KubernetesPodOperator (#31298)](https://github.com/apache/airflow/pull/31298): @dstandish
   - [ ] [Add BigQueryToPostgresOperator (#30658)](https://github.com/apache/airflow/pull/30658): @jbbqqf
   - [ ] [`DataflowTemplatedJobStartOperator` fix overwriting of location with default value, when a region is provided. (#31082)](https://github.com/apache/airflow/pull/31082): @VVildVVolf
   - [x] [Optimize deferrable mode execution in `GCSObjectsWithPrefixExistenceSensor` (#30939)](https://github.com/apache/airflow/pull/30939): @phanikumv
   - [x] [Add deferrable mode to `GCSObjectsWithPrefixExistenceSensor` (#30618)](https://github.com/apache/airflow/pull/30618): @phanikumv
   - [x] [Refactor GCS list hook to support multiple prefixes (#30815)](https://github.com/apache/airflow/pull/30815): @shahar1
   - [x] [Fix removed delegate_to parameter in deferrable GCS sensor (#30810)](https://github.com/apache/airflow/pull/30810): @potiuk
   - [ ] [Add `use_legacy_sql` param to `BigQueryGetDataOperator` (#31190)](https://github.com/apache/airflow/pull/31190): @shahar1
   - [ ] [Add `as_dict` param to `BigQueryGetDataOperator` (#30887)](https://github.com/apache/airflow/pull/30887): @shahar1
   - [ ] [Add flag apply_gcs_prefix to S3ToGCSOperator (#31127)](https://github.com/apache/airflow/pull/31127): @moiseenkov
   - [x] [Add `priority` parameter to BigQueryHook (#30655)](https://github.com/apache/airflow/pull/30655): @ying-w
   - [ ] [implement gcs_schema_object for BigQueryCreateExternalTableOperator (#30961)](https://github.com/apache/airflow/pull/30961): @attilaszombati
   - [ ] [Optimize deferrable mode execution in bigquery sensors (#30946)](https://github.com/apache/airflow/pull/30946): @phanikumv
   - [x] [Optimize deferrable mode execution in `GCSObjectUpdateSensor` (#30920)](https://github.com/apache/airflow/pull/30920): @phanikumv
   - [ ] [Optimize deferrable mode in `GCSObjectExistenceSensor` (#30901)](https://github.com/apache/airflow/pull/30901): @phanikumv
   - [ ] [`CreateBatchPredictionJobOperator` Add batch_size param for Vertex AI BatchPredictionJob objects (#31118)](https://github.com/apache/airflow/pull/31118): @VVildVVolf
   - [ ] [GKEPodHook needs to have all methods KPO calls (#31266)](https://github.com/apache/airflow/pull/31266): @dstandish
   - [x] [Add CloudBuild build id log (#30516)](https://github.com/apache/airflow/pull/30516): @tnk-ysk
   - [x] [Switch default Google ads to v13 (#31382)](https://github.com/apache/airflow/pull/31382): @ahidalgob
   - [x] [Switch to google ads v13 (#31369)](https://github.com/apache/airflow/pull/31369): @potiuk
   - [x] [Update SDKs for google provider package (#30067)](https://github.com/apache/airflow/pull/30067): @lwyszomi
## Provider [microsoft.azure: 6.1.0rc2](https://pypi.org/project/apache-airflow-providers-microsoft-azure/6.1.0rc2)
   - [x] [Add deferrable mode to `WasbPrefixSensor` (#30252)](https://github.com/apache/airflow/pull/30252): @phanikumv
   - [ ] [Optimize deferrable execution mode `AzureDataFactoryPipelineRunStatusSensor` (#30983)](https://github.com/apache/airflow/pull/30983): @phanikumv
   - [ ] [Optimize deferrable execution for `AzureDataFactoryRunPipelineOperator` (#31214)](https://github.com/apache/airflow/pull/31214): @phanikumv
## Provider [mongo: 3.2.0rc2](https://pypi.org/project/apache-airflow-providers-mongo/3.2.0rc2)
   - [ ] [Remove the upper version bound on pymongo (#31189)](https://github.com/apache/airflow/pull/31189): @jonshea
   - [x] [Add future-compatible mongo Hook typing (#31289)](https://github.com/apache/airflow/pull/31289): @potiuk
## Provider [neo4j: 3.3.0rc2](https://pypi.org/project/apache-airflow-providers-neo4j/3.3.0rc2)
   - [ ] [Removed Mandatory Encryption in Neo4jHook (#30418)](https://github.com/apache/airflow/pull/30418): @eldar-eln-bigabid
## Provider [oracle: 3.7.0rc2](https://pypi.org/project/apache-airflow-providers-oracle/3.7.0rc2)
   - [ ] [Add docs for Oracle operators (#30979)](https://github.com/apache/airflow/pull/30979): @vchiapaikeo
   - [x] [Fix deprecated import in Oracle example (#31166)](https://github.com/apache/airflow/pull/31166): @potiuk
## Provider [pagerduty: 3.2.0rc2](https://pypi.org/project/apache-airflow-providers-pagerduty/3.2.0rc2)
   - [ ] [Add test_connection method to PagerdutyHook (#31344)](https://github.com/apache/airflow/pull/31344): @utkarsharma2
   - [ ] [Add test_connection method to PagerdutyEventsHook (#31346)](https://github.com/apache/airflow/pull/31346): @utkarsharma2
   - [ ] [Add Change event V2 API support for pagerduty (#31222)](https://github.com/apache/airflow/pull/31222): @utkarsharma2
   - [ ] [Fixed typo in PagerdutyEventsHook (#31209)](https://github.com/apache/airflow/pull/31209): @utkarsharma2
## Provider [redis: 3.2.0rc2](https://pypi.org/project/apache-airflow-providers-redis/3.2.0rc2)
   - [ ] [Upgrade redis (#31279)](https://github.com/apache/airflow/pull/31279): @Owen-CH-Leung
## Provider [slack: 7.3.0rc2](https://pypi.org/project/apache-airflow-providers-slack/7.3.0rc2)
   - [x] [Add Documentation for notification feature extension (#29191)](https://github.com/apache/airflow/pull/29191): @ephraimbuddy
   - [x] [Standardize Slack Notifier (#31244)](https://github.com/apache/airflow/pull/31244): @eladkal

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-by-contributors)

All users involved in the PRs:
@ying-w @alextgu @RachitSharma2001 @hussein-awala @jonshea @vincbeck @dacort @VVildVVolf @pankajastro @shahar1 @potiuk @vandonr-amz @ferruzzi @eladkal @utkarsharma2 @harishkesavarao @bkossakowska 
@dstandish @jon-evergreen @tnk-ysk @IAL32 @nsAstro @Owen-CH-Leung @eldar-eln-bigabid @ephraimbuddy @moiseenkov @jbbqqf @attilaszombati @ahidalgob @vchiapaikeo @JCoder01 @syedahsn @pankajkoti @lwyszomi 
@phanikumv

**Comment by shahar1** [comment]
> ## Provider [apache.pinot: 4.1.0rc1](https://pypi.org/project/apache-airflow-providers-apache-pinot/4.1.0rc1)
> * [X]  [Add guide for Apache Pinot operators (#28653)](https://github.com/apache/airflow/pull/28653):

> ## Provider [google: 10.1.0rc1](https://pypi.org/project/apache-airflow-providers-google/10.1.0rc1)
> * [X]  [Refactor GCS list hook to support multiple prefixes (#30815)](https://github.com/apache/airflow/pull/30815):
> * [ ]  [Add `use_legacy_sql` param to `BigQueryGetDataOperator` (#31190)](https://github.com/apache/airflow/pull/31190): There's a problem with the deferrable mode regarding the project's ID, I'll try to take care of it soon.
> * [X]  [Add `as_dict` param to `BigQueryGetDataOperator` (#30887)](https://github.com/apache/airflow/pull/30887):

**Comment by raphaelauv** [comment]
Provider [cncf.kubernetes: 6.2.0rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/6.2.0rc1)
:heavy_check_mark:  https://github.com/apache/airflow/pull/29498: @hussein-awala

**Comment by harishkesavarao** [comment]
## Provider [databricks: 4.2.0rc1](https://pypi.org/project/apache-airflow-providers-databricks/4.2.0rc1)

- [x] #30980

**Comment by ying-w** [comment]
Confirmed https://github.com/apache/airflow/pull/30655 by verifying priority on ui when running the following dag

```py
from pendulum import datetime
from airflow.providers.common.sql.operators.sql import SQLExecuteQueryOperator
from airflow.decorators import task, dag

default_args = {
    "owner": "example",
    "retries": 0,
}

@dag(
    description="tmp",
    start_date=datetime(2021, 1, 1),
    schedule=None,
)
def testing():
    SQLExecuteQueryOperator(
        task_id="test",
        conn_id="bigquery",
        sql="SELECT 2",
        hook_params={
            "use_legacy_sql": False,
            "location": "us",
            "priority": "BATCH",  # this is the new part
            "api_resource_configs": {"query": {"useQueryCache": False}},
        },
    )

testing()
```

**Comment by phanikumv** [comment]
https://github.com/apache/airflow/pull/30829: works good. Tested it by passing a shareIdentifier while submitting the Batch job

```
[2023-05-17, 08:57:54 UTC] {batch_client.py:328} INFO - AWS Batch job (733b153e-fda5-4f3c-a29b-95eb8c22a6d4) check status (RUNNABLE) in ['RUNNING', 'SUCCEEDED', 'FAILED']
[2023-05-17, 08:57:54 UTC] {batch_client.py:343} INFO - AWS Batch job (733b153e-fda5-4f3c-a29b-95eb8c22a6d4) status check (7 of 4200) in the next 7.67 seconds
[2023-05-17, 08:58:03 UTC] {batch_client.py:328} INFO - AWS Batch job (733b153e-fda5-4f3c-a29b-95eb8c22a6d4) check status (STARTING) in ['RUNNING', 'SUCCEEDED', 'FAILED']
[2023-05-17, 08:58:03 UTC] {batch_client.py:343} INFO - AWS Batch job (733b153e-fda5-4f3c-a29b-95eb8c22a6d4) status check (8 of 4200) in the next 8.68 seconds
[2023-05-17, 08:58:12 UTC] {batch_client.py:328} INFO - AWS Batch job (733b153e-fda5-4f3c-a29b-95eb8c22a6d4) check status (SUCCEEDED) in ['RUNNING', 'SUCCEEDED', 'FAILED']
[2023-05-17, 08:58:21 UTC] {batch_client.py:328} INFO - AWS Batch job (733b153e-fda5-4f3c-a29b-95eb8c22a6d4) check status (SUCCEEDED) in ['SUCCEEDED', 'FAILED']
[2023-05-17, 08:58:21 UTC] {batch_client.py:269} INFO - AWS Batch job (733b153e-fda5-4f3c-a29b-95eb8c22a6d4) has completed
[2023-05-17, 08:58:21 UTC] {batch.py:310} INFO - AWS Batch job (733b153e-fda5-4f3c-a29b-95eb8c22a6d4) CloudWatch Events details found. Links to logs:
[2023-05-17, 08:58:21 UTC] {batch.py:313} INFO - 
[2023-05-17, 08:58:21 UTC] {batch_client.py:245} INFO - AWS Batch job (733b153e-fda5-4f3c-a29b-95eb8c22a6d4) succeeded: {'jobArn': 'arn:aws:batch:us-east-2:396807896376:job/733b153e-fda5-4f3c-a29b-95eb8c22a6d4', 'jobName': 'test_***_job', 'jobId': '733b153e-fda5-4f3c-a29b-95eb8c22a6d4', 'jobQueue': 'arn:aws:batch:us-east-2:396807896376:job-queue/providers_team_job_queue', 'status': 'SUCCEEDED', 'shareIdentifier': 'providers', 'schedulingPriority': 1, 'attempts': [{'container': {'containerInstanceArn': 'arn:aws:ecs:us-east-2:396807896376:container-instance/AWSBatch-providers_team_compute_env-0f056134-f57a-3a1f-9cbb-8d84bdd0f935/bcefcb90921e460085877d330bc5f495', 'taskArn': 'arn:aws:ecs:us-east-2:396807896376:task/AWSBatch-providers_team_compute_env-0f056134-f57a-3a1f-9cbb-8d84bdd0f935/0c4cdbb8cbfa4605aa1ad82e28384f87', 'exitCode': 0, 'logStreamName': 'providers_team_job_defn/default/0c4cdbb8cbfa4605aa1ad82e28384f87', 'networkInterfaces': []}, 'startedAt': 1684313885354, 'stoppedAt': 1684313885432, 'statusReason': 'Essential container in task exited'}], 'statusReason': 'Essential container in task exited', 'createdAt': 1684313824707, 'startedAt': 1684313885354, 'stoppedAt': 1684313885432, 'dependsOn': [], 'jobDefinition': 'arn:aws:batch:us-east-2:396807896376:job-definition/providers_team_job_defn:2', 'parameters': {}, 'container': {'image': 'public.ecr.aws/amazonlinux/amazonlinux:latest', 'command': ['echo', 'hello world'], 'volumes': [], 'environment': [], 'mountPoints': [], 'ulimits': [], 'exitCode': 0, 'containerInstanceArn': 'arn:aws:ecs:us-east-2:396807896376:container-instance/AWSBatch-providers_team_compute_env-0f056134-f57a-3a1f-9cbb-8d84bdd0f935/bcefcb90921e460085877d330bc5f495', 'taskArn': 'arn:aws:ecs:us-east-2:396807896376:task/AWSBatch-providers_team_compute_env-0f056134-f57a-3a1f-9cbb-8d84bdd0f935/0c4cdbb8cbfa4605aa1ad82e28384f87', 'logStreamName': 'providers_team_job_defn/default/0c4cdbb8cbfa4605aa1ad82e28384f87', 'networkInterfaces': [], 'resourceRequirements': [{'value': '1', 'type': 'VCPU'}, {'value': '2048', 'type': 'MEMORY'}], 'secrets': []}, 'tags': {}, 'propagateTags': False, 'platformCapabilities': ['EC2'], 'eksAttempts': []}
[2023-05-17, 08:58:21 UTC] {batch.py:329} INFO - AWS Batch job (733b153e-fda5-4f3c-a29b-95eb8c22a6d4) succeeded
```

**Comment by tnk-ysk** [comment]
I tested #30516, it works as expected

**Comment by phanikumv** [comment]
https://github.com/apache/airflow/pull/30968 works as expected


```
[2023-05-17, 10:13:51 UTC] {dbt.py:488} INFO - Getting the status of job run 151181329.
[2023-05-17, 10:13:51 UTC] {base.py:73} INFO - Using connection ID 'dbt_test_conn' for task execution.
[2023-05-17, 10:13:52 UTC] {dbt.py:493} INFO - Current status of job run 151181329: SUCCESS
[2023-05-17, 10:13:52 UTC] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=example_dbt_cloud, task_id=job_run_sensor_async, execution_date=20230517T101254, start_date=20230517T101351, end_date=20230517T101352
[2023-05-17, 10:13:52 UTC] {local_task_job_runner.py:225} INFO - Task exited with return code 0

```

**Comment by pankajkoti** [comment]
Confirmed https://github.com/apache/airflow/pull/31063, https://github.com/apache/airflow/pull/31042, and https://github.com/apache/airflow/pull/31062 (all of them are for Provider [amazon: 8.1.0rc1](https://pypi.org/project/apache-airflow-providers-amazon/8.1.0rc1)) are included in the RC and they ran fine on my example DAG. Thank you for the efforts!

**Comment by utkarsharma2** [comment]
Tested -  DynamoDBToS3Operator - Add a feature to export the table to a
point in time. (#31142) <https://github.com/apache/airflow/pull/31142>
With below dag:

from datetime import datetime

from airflow import DAG
from airflow.providers.amazon.aws.transfers.dynamodb_to_s3 import
DynamoDBToS3Operator

with DAG(
    dag_id='example_export_dynamodb',
    schedule_interval=None,
    start_date=datetime(2021, 1, 1),
    tags=['example'],
    catchup=False,
) as dag:
    dynamodb_to_s3_operator = DynamoDBToS3Operator(
        task_id="dynamodb_to_s3",
        dynamodb_table_name="test",
        s3_bucket_name="tmp9",
        file_size=4000,
        export_time=datetime.now(),
        s3_key_prefix="test1"
    )

Thanks,
Utkarsh Sharma

**Comment by JCoder01** [comment]
https://github.com/apache/airflow/pull/31110 works as expected

**Comment by vandonr-amz** [comment]
👍  for me

**Comment by eladkal** [comment]
Issue template has been updated for RC2

**Comment by hussein-awala** [comment]
Should we create a major release for google provider? #30067 worth it. @eladkal WDYT?

**Comment by eladkal** [comment]
> Should we create a major release for google provider? #30067 worth it. @eladkal WDYT?

I didnt see breaking changes on that PR. Can you specify which change?
Depended packages breaking changes are not considered breaking change for Airflow.

**Comment by potiuk** [comment]
> > Should we create a major release for google provider? #30067 worth it. @eladkal WDYT?
> 
> I didnt see breaking changes on that PR. Can you specify which change? Depended packages breaking changes are not considered breaking change for Airflow. We do major release when Airflow breaks the schema/signature of functions/classes/imports.

That's right. We even documented it: https://github.com/apache/airflow#semantic-versioning

> Changing limits for versions of Airflow dependencies is not a breaking change on its own.

If there were no breaking changes in OUR API in providers, deps upgrade are not breaking. This is quite common approach - for example `apache-beam` uses the same. The version that enabled the upgrade was 2.47.0, a minor upgrade from previous 2.46.0 - and they bumped some of the same deps we did (pyarrow, protobuf to name the most important ones).

**Comment by potiuk** [comment]
Everything Looks good:
* no more circular import problems (I checked it in similar way as is done in our CI now: https://github.com/apache/airflow/pull/31385 - but I did it also for Airflow 2.5 and 2.6.1 (not only 2.4 and main).
* All providers now have `__version__` defined at their top-level
* I also checked that this version of preinstalled providers cannot be used for airflow < 2.4. When you try to import those you get this nice exception:

![image](https://github.com/apache/airflow/assets/595491/ea487f72-bee0-4019-a2aa-d2abdcd223c4)

All looks good!

**Comment by pankajastro** [comment]
https://github.com/apache/airflow/pull/31006  https://github.com/apache/airflow/pull/31094 https://github.com/apache/airflow/pull/30744 https://github.com/apache/airflow/pull/30761 looks good. thank you!

**Comment by Lee-W** [comment]
I tested the following DAG

```python
    create_job_flow = EmrCreateJobFlowOperator(
        task_id="create_job_flow",
        job_flow_overrides=JOB_FLOW_OVERRIDES,
        aws_conn_id=AWS_CONN_ID,
    )
```

but encountered the following issue 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/providers/amazon/aws/operators/emr.py", line 695, in execute
    log_uri=get_log_uri(emr_client=self._emr_hook.conn, job_flow_id=self._job_flow_id),
  File "/usr/local/lib/python3.10/site-packages/airflow/providers/amazon/aws/links/emr.py", line 61, in get_log_uri
    log_uri = S3Hook.parse_s3_url(response["Cluster"]["LogUri"])
KeyError: 'LogUri'
```

**Comment by potiuk** [comment]
Looks like might be caused by https://github.com/apache/airflow/pull/31032 (cc: @ferruzzi )

**Comment by phanikumv** [comment]
I tested and found a bug in `WasbPrefixSensor` while testing microsoft.azure rc, fix is available in this PR https://github.com/apache/airflow/pull/31411 . Would it be okay to include it as well

**Comment by eladkal** [comment]
Thank you everyone.
Providers are released
I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).



Note: we decided to release amazon and microsoft.azure providers despite the bug reports, reasons are explained in the [mailing list thread](https://lists.apache.org/thread/0njo8nd4mzgk96qzg9sc73jxgocw22b4).
