### ISSUE TITLE
Add Notifiers to provider information

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#31443]
### Body

Similar to https://github.com/apache/airflow/issues/29918

We have notifiers exposed in provider info but no mechanism to expose them.

- [x] add notifications to provider.yaml schema (verify that all current notifiers in code base presented in  provider.yaml) https://github.com/apache/airflow/pull/31576
- [x] add notifications to provider_info schema 
- [x] expose notifications via Providers Manager
- [x] add CLI notifications command to airflow providers  https://github.com/apache/airflow/pull/33116
- [x] add automated exposure of notifications in the docs (needs to be exposed at [list of notifiers in airflow docs ](https://airflow.apache.org/docs/apache-airflow-providers/core-extensions/notifications.html) and as part of the provider index)
- [x] check notifications classes are present in provider.yaml in unit tests https://github.com/apache/airflow/pull/33640

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by omidroshani** [comment]
I'm interested in collaborating on it. Could you please let me know if I can work on this issue?

**Comment by potiuk** [comment]
> I'm interested in collaborating on it. Could you please let me know if I can work on this issue?

Feel free.

**Comment by devlp121** [comment]
I'd like to collaborate on this issue.

**Comment by potiuk** [comment]
Assigned you both. Check with @omidroshani what's the status please.

**Comment by potiuk** [comment]
CC: @eladkal - also checked "add notifications to provider_info schema. It is already there.
