### ISSUE TITLE
Status of testing Providers that were prepared on May 24, 2023

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#31495]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [common.sql: 1.5.1rc1](https://pypi.org/project/apache-airflow-providers-common-sql/1.5.1rc1)
   - [x] [Bring back min-airflow-version for preinstalled providers (#31469)](https://github.com/apache/airflow/pull/31469): @potiuk
## Provider [ftp: 3.4.1rc1](https://pypi.org/project/apache-airflow-providers-ftp/3.4.1rc1)
   - [x] [Bring back min-airflow-version for preinstalled providers (#31469)](https://github.com/apache/airflow/pull/31469): @potiuk
## Provider [google: 10.1.1rc1](https://pypi.org/project/apache-airflow-providers-google/10.1.1rc1)
   - [x] [Fix accessing a GKE cluster through the private endpoint in `GKEStartPodOperator` (#31391)](https://github.com/apache/airflow/pull/31391): @hussein-awala
   - [ ] [Fix `BigQueryGetDataOperator`'s query job bugs in deferrable mode (#31433)](https://github.com/apache/airflow/pull/31433): @shahar1
## Provider [http: 4.4.1rc1](https://pypi.org/project/apache-airflow-providers-http/4.4.1rc1)
   - [x] [Bring back min-airflow-version for preinstalled providers (#31469)](https://github.com/apache/airflow/pull/31469): @potiuk
## Provider [imap: 3.2.1rc1](https://pypi.org/project/apache-airflow-providers-imap/3.2.1rc1)
   - [x] [Bring back min-airflow-version for preinstalled providers (#31469)](https://github.com/apache/airflow/pull/31469): @potiuk
## Provider [microsoft.azure: 6.1.1rc1](https://pypi.org/project/apache-airflow-providers-microsoft-azure/6.1.1rc1)
   - [x] [Fix deferrable mode execution in `WasbPrefixSensor` (#31411)](https://github.com/apache/airflow/pull/31411): @phanikumv
   - [x] [Optimize deferred mode execution for wasb sensors (#31009)](https://github.com/apache/airflow/pull/31009): @phanikumv
## Provider [sqlite: 3.4.1rc1](https://pypi.org/project/apache-airflow-providers-sqlite/3.4.1rc1)
   - [x] [Bring back min-airflow-version for preinstalled providers (#31469)](https://github.com/apache/airflow/pull/31469): @potiuk

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-by-contributors)

All users involved in the PRs:
@shahar1 @phanikumv @potiuk @hussein-awala

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by phanikumv** [comment]
#31411 and #31009 work as expected

```
[2023-05-24, 17:03:44 UTC] {standard_task_runner.py:85} INFO - Job 33: Subtask wasb_blob_sensor
[2023-05-24, 17:03:44 UTC] {task_command.py:410} INFO - Running <TaskInstance: example_wasb_sensors.wasb_blob_sensor manual__2023-05-24T17:03:32.020763+00:00 [running]> on host 4a8ddc38546d
[2023-05-24, 17:03:44 UTC] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_wasb_sensors' AIRFLOW_CTX_TASK_ID='wasb_blob_sensor' AIRFLOW_CTX_EXECUTION_DATE='2023-05-24T17:03:32.020763+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-24T17:03:32.020763+00:00'
[2023-05-24, 17:03:44 UTC] {wasb.py:70} INFO - Poking for blob: example_azure_test_file.txt
 in wasb://test-container-providers
[2023-05-24, 17:03:44 UTC] {base.py:73} INFO - Using connection ID 'wasb_default' for task execution.
[2023-05-24, 17:03:45 UTC] {base.py:255} INFO - Success criteria met. Exiting.
[2023-05-24, 17:03:45 UTC] {taskinstance.py:1345} INFO - Marking task as SUCCESS
```

```
[2023-05-24, 17:03:48 UTC] {task_command.py:410} INFO - Running <TaskInstance: example_wasb_sensors.wasb_prefix_sensor manual__2023-05-24T17:03:32.020763+00:00 [running]> on host 4a8ddc38546d
[2023-05-24, 17:03:48 UTC] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_wasb_sensors' AIRFLOW_CTX_TASK_ID='wasb_prefix_sensor' AIRFLOW_CTX_EXECUTION_DATE='2023-05-24T17:03:32.020763+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-24T17:03:32.020763+00:00'
[2023-05-24, 17:03:48 UTC] {wasb.py:165} INFO - Poking for prefix: example_az in wasb://test-container-providers
[2023-05-24, 17:03:48 UTC] {base.py:73} INFO - Using connection ID 'wasb_default' for task execution.
[2023-05-24, 17:03:49 UTC] {base.py:255} INFO - Success criteria met. Exiting.
```

**Comment by eladkal** [comment]
Thank you everyone.
Providers are released
I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
