### ISSUE TITLE
Status of testing of Apache Airflow 2.6.2rc2

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#31867]
### Body

We are kindly requesting that contributors to [Apache Airflow RC 2.6.2rc2](https://pypi.org/project/apache-airflow/2.6.2rc2/) help test the RC.

Please let us know by commenting if the issue is addressed in the latest RC.

- [x] [Add Python 3.11 support (#27264)](https://github.com/apache/airflow/pull/27264): @potiuk
- [x] [Add fullname to owner on logging (#30185)](https://github.com/apache/airflow/pull/30185): @arjunanan6
     Linked issues:
     - [Audit Log is unclear when using Azure AD login (#29662)](https://github.com/apache/airflow/issues/29662)
- [x] [Fix DAG.access_control can't sync when clean access_control (#30340)](https://github.com/apache/airflow/pull/30340): @huymq1710
- [ ] [Save scheduler execution time during search for queued dag_runs (#30699)](https://github.com/apache/airflow/pull/30699): @AutomationDev85
- [ ] [Save scheduler execution time by checking if DAG has interval or timetable (#30706)](https://github.com/apache/airflow/pull/30706): @AutomationDev85
- [x] [Fix ExternalTaskSensor to work correctly with task groups (#30742)](https://github.com/apache/airflow/pull/30742): @dzhigimont
- [x] [Add instructions on how to avoid accidental airflow upgrade/downgrade (#30813)](https://github.com/apache/airflow/pull/30813): @potiuk
- [ ] [Add broad-strokes 'security model' (#30843)](https://github.com/apache/airflow/pull/30843): @raboof
- [ ] [Executor events are not always "exited" here (#30859)](https://github.com/apache/airflow/pull/30859): @dstandish
- [ ] [Include rediss to the list of supported URL schemes (#31028)](https://github.com/apache/airflow/pull/31028): @vlazuka
- [x] [Validate connection IDs (#31140)](https://github.com/apache/airflow/pull/31140): @BasPH @mattusifer
     Linked issues:
     - [Restrict allowed characters in connection ids (#29836)](https://github.com/apache/airflow/issues/29836)
- [x] [Add description on how we handle security issues in Airflow (#30960) (#31160)](https://github.com/apache/airflow/pull/31160): @potiuk
- [x] [Added spinner activity while the logs load (#31165)](https://github.com/apache/airflow/pull/31165): @Adaverse
- [ ] [Use only one line for tmp dir log (#31170)](https://github.com/apache/airflow/pull/31170): @dstandish
- [ ] [Don't present an undefined execution date (#31196)](https://github.com/apache/airflow/pull/31196): @evanmiller
- [ ] [Upgrade FAB to 4.3.1 (#31203)](https://github.com/apache/airflow/pull/31203): @VVildVVolf
- [ ] [Fix `url_for_asset` fallback and 404 on DAG Audit Log (#31233)](https://github.com/apache/airflow/pull/31233): @jedcunningham
- [ ] [Fix Kubernetes executor set wrong task status (#31274)](https://github.com/apache/airflow/pull/31274): @pankajastro
- [ ] [Make connection id validation consistent across interface (#31282)](https://github.com/apache/airflow/pull/31282): @pankajastro
- [ ] [Make BaseJobRunner a generic on the job class (#31287)](https://github.com/apache/airflow/pull/31287): @uranusjr
- [x] [Added metavar and choices to --state flag in airflow dags list-jobs CLI for suggesting valid state arguments. (#31308)](https://github.com/apache/airflow/pull/31308): @jgarte @rohan472000
     Linked issues:
     - [airflow dags list-jobs missing state metavar and choices keyword arguments (#31303)](https://github.com/apache/airflow/issues/31303)
- [x] [Use keyword paramaters for migration methods for mssql (#31309)](https://github.com/apache/airflow/pull/31309): @potiuk @uranusjr @dstandish
     Linked issues:
     - [Always pass named type_ arg to drop_constraint (#31306)](https://github.com/apache/airflow/pull/31306)
     - [Fix bad drop_constraint call in migrations (#31302)](https://github.com/apache/airflow/pull/31302)
- [x] [Rephrase comment in setup.py (#31312)](https://github.com/apache/airflow/pull/31312): @potiuk @pankajkoti
     Linked issues:
     - [Use keyword paramaters for migration methods for mssql (#31309)](https://github.com/apache/airflow/pull/31309)
- [x] [Convert dask upper-binding into exclusion (#31329)](https://github.com/apache/airflow/pull/31329): @potiuk
- [x] [Add an example for `sql_alchemy_connect_args` conf (#31332)](https://github.com/apache/airflow/pull/31332): @hussein-awala
- [x] [Fix Scheduler crash when clear a previous run of a normal task that is now a mapped task. (#31352)](https://github.com/apache/airflow/pull/31352): @tirkarthi
     Linked issues:
     - [Changing task from unmapped to mapped task with task instance note and task reschedule (#31351)](https://github.com/apache/airflow/issues/31351)
- [ ] [Skip auto-document things with :meta private: (#31380)](https://github.com/apache/airflow/pull/31380): @uranusjr
- [x] [Fix dropdown default and adjust tutorial to use 42 as default for proof (#31400)](https://github.com/apache/airflow/pull/31400): @jens-scheffler-bosch
     Linked issues:
     - [Trigger UI Form Dropdowns with enums do not set default correct (#31399)](https://github.com/apache/airflow/issues/31399)
- [ ] [Fix error handling when pre-importing modules in DAGs (#31401)](https://github.com/apache/airflow/pull/31401): @vandonr-amz @jedcunningham
     Linked issues:
     - [preload airflow imports before dag parsing to save time (#30495)](https://github.com/apache/airflow/pull/30495)
- [ ] [Fix `max_active_tis_per_dagrun` for Dynamic Task Mapping (#31406)](https://github.com/apache/airflow/pull/31406): @mdembiczak
- [x] [Fix min_backoff calculation in base sensor when exponential_backoff is on (#31412)](https://github.com/apache/airflow/pull/31412): @hussein-awala @AVMusorin
     Linked issues:
     - [ZeroDivisionError in BaseSensorOperator with `exponential_backoff=True` and `poke_interval=1`  (#31409)](https://github.com/apache/airflow/issues/31409)
- [x] [Cascade update of taskinstance to TaskMap table (#31445)](https://github.com/apache/airflow/pull/31445): @ephraimbuddy
- [x] [Wording the next and last run DAG columns better (#31467)](https://github.com/apache/airflow/pull/31467): @wolfier @amoghrajesh
     Linked issues:
     - [The `Next Run` column name and tooltip is misleading (#31365)](https://github.com/apache/airflow/issues/31365)
- [x] [Use kube_client over default CoreV1Api for deleting pods (#31477)](https://github.com/apache/airflow/pull/31477): @luos-fc
     Linked issues:
     - [cleanup-pod CLI command fails due to incorrect host (#31476)](https://github.com/apache/airflow/issues/31476)
- [x] [Fix table formatting in docker build documentation (#31472)](https://github.com/apache/airflow/pull/31472): @potiuk
- [ ] [Fix typing in external task triggers (#31490)](https://github.com/apache/airflow/pull/31490): @uranusjr
- [x] [Remove dependency already registered for this task warning (#31502)](https://github.com/apache/airflow/pull/31502): @ephraimbuddy
- [x] [Include triggerer health status in Airflow /health endpoint (#31529)](https://github.com/apache/airflow/pull/31529): @pankajkoti @jedcunningham
     Linked issues:
     - [`/health` endpoint missed when adding triggerer health status reporting (#31522)](https://github.com/apache/airflow/issues/31522)
- [x] [fix airflow users delete CLI command (#31539)](https://github.com/apache/airflow/pull/31539): @hussein-awala @casper-voltgoed
     Linked issues:
     - [Unable to delete user via CI (#31509)](https://github.com/apache/airflow/issues/31509)
- [x] [Add the missing `map_index` to the xcom key when skipping downstream tasks (#31541)](https://github.com/apache/airflow/pull/31541): @hussein-awala @luederm
     Linked issues:
     - [Short circuit task in expanded task group fails when it returns false (#31526)](https://github.com/apache/airflow/issues/31526)
- [x] [Fix sorting of tags (#31553)](https://github.com/apache/airflow/pull/31553): @arjunanan6
     Linked issues:
     - [Tag filter doesn't sort tags alphabetically (#31547)](https://github.com/apache/airflow/issues/31547)
- [ ] [Remove found_descendents param from get_flat_relative_ids (#31559)](https://github.com/apache/airflow/pull/31559): @dstandish
- [x] [Resolving issue where Grid won't un-collapse when Details is collapsed (#31561)](https://github.com/apache/airflow/pull/31561): @Adaverse
- [x] [Add TriggererStatus to OpenAPI spec (#31579)](https://github.com/apache/airflow/pull/31579): @pierrejeambrun
- [ ] [Testing connection - clearing old alert box when testing connection (#31606)](https://github.com/apache/airflow/pull/31606): @utkarsharma2
- [x] [Fix overriding `default_args` in nested task groups (#31608)](https://github.com/apache/airflow/pull/31608): @hussein-awala @hyeong10
     Linked issues:
     - [Override default_args between Nested TaskGroups (#31604)](https://github.com/apache/airflow/issues/31604)
- [x] [fixing broken links in openapi/v1.yaml (#31619)](https://github.com/apache/airflow/pull/31619): @Adaverse
- [ ] [Replace unicodecsv with standard csv library (#31693)](https://github.com/apache/airflow/pull/31693): @dstandish
- [x] [Add severity rating explanation to our Security Policy (#31702)](https://github.com/apache/airflow/pull/31702): @potiuk
- [x] [Add back accidentally removed `create_session` in utils/db.py (#31705)](https://github.com/apache/airflow/pull/31705): @ephraimbuddy
- [ ] [Control permissibility of driver config in extra from airflow.cfg (#31754)](https://github.com/apache/airflow/pull/31754): @dstandish
- [x] [Fix failing get_safe_url tests for latest Python 3.8 and 3.9 (#31766)](https://github.com/apache/airflow/pull/31766): @potiuk
- [x] [Fix typing for POST user endpoint (#31767)](https://github.com/apache/airflow/pull/31767): @ephraimbuddy
- [x] [Fix wrong override for nested group default args (#31776)](https://github.com/apache/airflow/pull/31776): @hussein-awala
     Linked issues:
     - [Fix overriding `default_args` in nested task groups (#31608)](https://github.com/apache/airflow/pull/31608)
- [ ] [Mark `[secrets] backend_kwargs` as a sensitive config (#31788)](https://github.com/apache/airflow/pull/31788): @jedcunningham
- [x] [Bring back unicodecsv as depenendency of Airflow (#31814)](https://github.com/apache/airflow/pull/31814): @potiuk @dstandish
     Linked issues:
     - [Replace unicodecsv with standard csv library (#31693)](https://github.com/apache/airflow/pull/31693)
- [ ] [Use single source of truth for sensitive config items (#31820)](https://github.com/apache/airflow/pull/31820): @dstandish
- [x] [Fix selective checks skipping provider tests in non main branch (#31821)](https://github.com/apache/airflow/pull/31821): @potiuk
- [x] [Only run builds on "push" events for v* test branch (#31825)](https://github.com/apache/airflow/pull/31825): @potiuk
- [x] [Skip instalation of provider sdist packages when provider tests skipped (#31827)](https://github.com/apache/airflow/pull/31827): @potiuk
- [x] [Check that breeze image builds quickly only on main branch (#31828)](https://github.com/apache/airflow/pull/31828): @potiuk

Thanks to all who contributed to the release (probably not a complete list!):
@vlazuka @tirkarthi @rohan472000 @huymq1710 @arjunanan6 @utkarsharma2 @hussein-awala @uranusjr @pankajkoti @raboof @wolfier @BasPH @mdembiczak @jgarte @luederm @pankajastro @dzhigimont @vandonr-amz @hyeong10 @mattusifer @dstandish @AVMusorin @luos-fc @potiuk @amoghrajesh @Adaverse @pierrejeambrun @AutomationDev85 @VVildVVolf @jens-scheffler-bosch @casper-voltgoed @ephraimbuddy @evanmiller @jedcunningham

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by Adaverse** [comment]
Checked #31165,  #31561 and #31619. Looks good!

**Comment by pankajkoti** [comment]
https://github.com/apache/airflow/pull/31312 and https://github.com/apache/airflow/pull/31529 look good. Thank you for including these!

**Comment by jens-scheffler-bosch** [comment]
Double checked PR #31400 for Issue #31399 and on source level the fix is contained. Thanks for including!

**Comment by amoghrajesh** [comment]
https://github.com/apache/airflow/pull/31467 looks good 👍🏽

**Comment by utkarsharma2** [comment]
#31606 <https://github.com/apache/airflow/pull/31606>Works as expected.

Thanks,
Utkarsh Sharma

**Comment by rohan472000** [comment]
#31308 LGTM👍.

**Comment by potiuk** [comment]
Most of my changes were docs/metadata. I checked all of them and marked. There is one thing I found that was either missed or overwritten when cherry-picking

https://github.com/apache/airflow/pull/31472 - but this is a small documentation formatting fix and we can cherry-pick it later or separately maybe and release documentation separately.

All the rest looks good.

**Comment by arjunanan6** [comment]
#31553 and #30185 looks fine.

**Comment by huymq1710** [comment]
#30340 look good. Thank you!

**Comment by pankajastro** [comment]
https://github.com/apache/airflow/pull/31274 and https://github.com/apache/airflow/pull/31282 looks good. thank you!

**Comment by hussein-awala** [comment]
I tested my changes which are listed in this issue and #29762 which is not listed, they are all present in the RC1 and work as expected.

**Comment by pierrejeambrun** [comment]
@hussein-awala `type:doc-only` and `changelog:skip` labels are skipped from the testing issue right now. (Maybe we should update that?)

https://github.com/apache/airflow/blob/main/dev/prepare_release_issue.py#L297

**Comment by pierrejeambrun** [comment]
https://github.com/apache/airflow/pull/31579 Working as expected

**Comment by potiuk** [comment]
All good - including doc changes.

**Comment by luos-fc** [comment]
#31477 working as expected

**Comment by vatsrahul1001** [comment]
Test below, looks good

1. https://github.com/apache/airflow/pull/30742
2. https://github.com/apache/airflow/pull/31140
3. https://github.com/apache/airflow/pull/31352
4. https://github.com/apache/airflow/pull/31445

**Comment by eladkal** [comment]
Airflow 2.6.2 has been released.
Thanks to all contributors for helping test this release
