### ISSUE TITLE
Switch Airlfow base images to use debian Bookworm

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#31941]
### Body

Debian on 10th of June 2023 released `bookworm`  (Debian 12) which is the new stable version that is going to get 5 years of support. Currently we use `bullseye` - previous stable version (soon to be named oldstable).

Here is bookworm info on Debian's site

* https://www.debian.org/News/2023/20230610

Also Python images started to be published in bookworm version as of today (15th of June).

https://hub.docker.com/_/python/tags?page=1&name=bookworm

We should make an attempt and eventualy switch to `bookworm` so that one of the future major relaseses  in the future is based on bookworm as default so that we can phase out boo. When we switched from buster to debian this was a stage proeces and we should likely repeat that.

Here are the steps that need to be done:

- [ ] Have a way to switch between bullseye and bookworm in `breeze` and our Dockerfiles (make our prod and CI images build)
- [ ] Have a way to switch between bullseye and bookworm in CI (via label)
- [ ] Make our CI tests failed in bookworm
- [ ] Run continuously single bookworm-based job in CI in `canary` builds
- [ ] publish prod images for bookworm in parallel to bullseye (so that users can choose which one they should use) 
- [ ] swap primary OS bookworm <> bullseye to run most tests on bookworm
- [ ] swap default image to be bookworm in a selected minor version of airflow
- [ ] stop building and publishing bullseye images (and run tests)  at another minor release - leaving only possibilty to run bullseye if the user want to build custom image
- [ ] drop support for bullseye from images and custom images at another minor release

This will be a long process and we likely cannot even start it yet. There are a number of dependencies of ours that will likely not work in the bookworm version for at least 4-6 months. This will likely be the first time where we will be "check" the first box from the list above.

Also Debian Bullseye is suported by regular Debian support till July 2024 at least (maybe even until 2026) and will be taken over by LTS, so there is no particular reason to move there (for now). This might change as support for bullseye will get dropped by some of the dependencies of ours (likely not sooneer than 2024/2025) so we might simply not have an incentive to switch to Bookworm till then.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by marzoli** [comment]
Up please!

**Comment by Taragolis** [comment]
@marzoli just for a record [Oracle MySQL repo (x86_64)](https://www.mysql.com/support/supportedplatforms/database.html) only provided for Debian 11

**Comment by raphaelauv** [comment]
https://github.com/apache/airflow/pull/35376#event-10870071411

@potiuk we can close this issue

**Comment by potiuk** [comment]
Thanks @raphaelauv !
