### ISSUE TITLE
Status of testing of Apache Airflow 2.6.3rc1

### ISSUE THREAD

**Issue by ephraimbuddy** [apache/airflow#32432]
### Body

We are kindly requesting that contributors to [Apache Airflow RC 2.6.3rc1](https://pypi.org/project/apache-airflow/2.6.3rc1/) help test the RC.

Please let us know by commenting if the issue is addressed in the latest RC.

- [ ] [Fix airflow module version check when using ExternalPythonOperator and debug logging level (#30367)](https://github.com/apache/airflow/pull/30367): @mathbou
- [ ] [fix issue: DAG's on_failure_callback is not invoked when task failed during testing dag. (#30965)](https://github.com/apache/airflow/pull/30965): @mis98zb
- [ ] [This fixes an issue were a database session got stuck (#31128)](https://github.com/apache/airflow/pull/31128): @stijndehaes
- [x] [fix connection uri parsing when the host includes a scheme (#31465)](https://github.com/apache/airflow/pull/31465): @hussein-awala @amoghrajesh @Scope0910
     Linked issues:
     - [Add capability in Airflow connections to validate host (#31460)](https://github.com/apache/airflow/issues/31460)
     - [Spark Connection with k8s in URL not mapped correctly  (#21638)](https://github.com/apache/airflow/issues/21638)
- [ ] [feat(jobs/triggerer_job_runner): add triggerer canceled log (#31757)](https://github.com/apache/airflow/pull/31757): @dstandish @Lee-W
     Linked issues:
     - [Add a log message when a trigger is canceled for timeout (#31720)](https://github.com/apache/airflow/issues/31720)
     - [Add a log message when a trigger is canceled for timeout (#31720)](https://github.com/apache/airflow/issues/31720)
- [x] [Add a check for trailing slash in webserver base_url (#31833)](https://github.com/apache/airflow/pull/31833): @hussein-awala @PaleNeutron
     Linked issues:
     - [redirect to same url after set base_url (#31726)](https://github.com/apache/airflow/issues/31726)
- [x] [Add release management command that generates SBOM information (#31835)](https://github.com/apache/airflow/pull/31835): @potiuk
- [ ] [Decode old-style nested Xcom value (#31866)](https://github.com/apache/airflow/pull/31866): @utkarsharma2
- [ ] [Fix `operator_extra_links` property serialization in mapped tasks (#31904)](https://github.com/apache/airflow/pull/31904): @hussein-awala @harrisonharris-di
     Linked issues:
     - [MappedOperator doesn't allow `operator_extra_links` instance property (#31902)](https://github.com/apache/airflow/issues/31902)
- [ ] [bump: kind 0.20.0 (#31922)](https://github.com/apache/airflow/pull/31922): @raphaelauv
- [x] [Add command to generate requirements that are needed by a provider (#31943)](https://github.com/apache/airflow/pull/31943): @potiuk
- [x] [Fix number param html type in trigger template (#31946)](https://github.com/apache/airflow/pull/31946): @hussein-awala @mikelius2b
     Linked issues:
     - [UI: New trigger DAG with config form doesn’t allow valid floats and empty strings (#31930)](https://github.com/apache/airflow/issues/31930)
- [ ] [Fix task.sensor annotation in type stub (#31954)](https://github.com/apache/airflow/pull/31954): @uranusjr
- [x] [Fix masking nested variable fields (#31964)](https://github.com/apache/airflow/pull/31964): @hussein-awala @NikitasB
     Linked issues:
     - [KubernetesPodOperator doesn't mask variables in Rendered Template that are used as arguments  (#31873)](https://github.com/apache/airflow/issues/31873)
- [x] [Fix copy artifacts to svn command (#31975)](https://github.com/apache/airflow/pull/31975): @ephraimbuddy
- [x] [Fix number param html type in trigger template (#31980)](https://github.com/apache/airflow/pull/31980): @hussein-awala @mikelius2b
     Linked issues:
     - [Fix number param html type in trigger template (#31946)](https://github.com/apache/airflow/pull/31946)
     - [UI: New trigger DAG with config form doesn’t allow valid floats and empty strings (#31930)](https://github.com/apache/airflow/issues/31930)
- [ ] [Catch the exception that triggerer initialization failed (#31999)](https://github.com/apache/airflow/pull/31999): @Lee-W
- [x] [Fix ExternalTaskSensor when there is not task group TIs for the current execution date (#32009)](https://github.com/apache/airflow/pull/32009): @hussein-awala @dzhigimont @jgmarcel
     Linked issues:
     - [Fix ExternalTaskSensor to work correctly with task groups (#30742)](https://github.com/apache/airflow/pull/30742)
     - [ZeroDivisionError while poking ExternalTaskSensor (#32007)](https://github.com/apache/airflow/issues/32007)
- [x] [Flash an error msg instead of failure in `rendered-templates` when map index is not found (#32011)](https://github.com/apache/airflow/pull/32011): @hussein-awala @raphaelauv
     Linked issues:
     - [webserver - MAPPED tasks - rendered-templates page FAIL (#32005)](https://github.com/apache/airflow/issues/32005)
- [ ] [Check for DAG ID in query param from url as well as kwargs (#32014)](https://github.com/apache/airflow/pull/32014): @o-nikolas
- [ ] [Return None if an XComArg fails to resolve in a multiple_outputs Task (#32027)](https://github.com/apache/airflow/pull/32027): @ephraimbuddy
- [ ] [Fix hashing of dag_dependencies in serialized dag (#32037)](https://github.com/apache/airflow/pull/32037): @dstandish
- [ ] [Render list items in rendered fields view (#32042)](https://github.com/apache/airflow/pull/32042): @cvaliente
- [x] [Use re2 for matching untrusted regex (#32060)](https://github.com/apache/airflow/pull/32060): @pierrejeambrun
- [x] [Add pkgconf to system dependencies for the CI/prod image (#32075)](https://github.com/apache/airflow/pull/32075): @potiuk
- [x] [Remove casting of forward_credentials for shell and start-airflow breeze (#32087)](https://github.com/apache/airflow/pull/32087): @potiuk
- [ ] [Handle partially updated trigger/task_instance data in triggerr jobs (#32092)](https://github.com/apache/airflow/pull/32092): @tomrutter
     Linked issues:
     - [Triggerer intermittent failure when running many triggerers (#32091)](https://github.com/apache/airflow/issues/32091)
- [x] [Exit asset compilation fork in start-airflow after it completed (#32114)](https://github.com/apache/airflow/pull/32114): @potiuk
- [x] [Avoid permission error when asset compilation exists before killing it (#32116)](https://github.com/apache/airflow/pull/32116): @potiuk
     Linked issues:
     - [Exit asset compilation fork in start-airflow after it completed (#32114)](https://github.com/apache/airflow/pull/32114)
- [x] [Add release management command to retreive provider version metadata (#32119)](https://github.com/apache/airflow/pull/32119): @potiuk
- [x] [Fix triggerers alive check and add a new conf for triggerer heartbeat rate (#32123)](https://github.com/apache/airflow/pull/32123): @hussein-awala @tirkarthi
     Linked issues:
     - [Multiple Triggerer processes keeps reassigning triggers to each other when job_heartbeat_sec is higher than 30 seconds. (#32121)](https://github.com/apache/airflow/issues/32121)
- [x] [Add airflow to docs packages if only docs/apache-airflow/* files changed (#32149)](https://github.com/apache/airflow/pull/32149): @potiuk
- [ ] [Use mapIndex to display extra links per mapped task. (#32154)](https://github.com/apache/airflow/pull/32154): @tirkarthi
     Linked issues:
     - [Support extra link per mapped task in grid view (#32153)](https://github.com/apache/airflow/issues/32153)
- [x] [Update git-sync description in Helm Chart documentation (#32181)](https://github.com/apache/airflow/pull/32181): @potiuk
- [x] [Add libeos_dev on ARM runtime PROD image (#32200)](https://github.com/apache/airflow/pull/32200): @potiuk
     Linked issues:
     - [Add libgeos-dev to dev dependencies in CI image (#31437)](https://github.com/apache/airflow/pull/31437)
- [ ] [fix bugged singleton implementation (#32218)](https://github.com/apache/airflow/pull/32218): @mobuchowski
- [x] [Remove executor_class from Job - fixing backfil for custom executors (#32219)](https://github.com/apache/airflow/pull/32219): @potiuk
- [ ] [add mobuchowski to committers breeze variable (#32228)](https://github.com/apache/airflow/pull/32228): @mobuchowski
- [ ] [Add phanikumv to committers (#32229)](https://github.com/apache/airflow/pull/32229): @phanikumv
- [x] [Fix behaviour of LazyDictWithCache when import fails (#32248)](https://github.com/apache/airflow/pull/32248): @potiuk @dimberman
     Linked issues:
     - [Add a Docker Taskflow decorator (#15330)](https://github.com/apache/airflow/pull/15330)
- [x] [Add apache-airflow-providers to filter in selective checks if needed (#32284)](https://github.com/apache/airflow/pull/32284): @potiuk
     Linked issues:
     - [Update references to restructured documentation from airflow core (#32282)](https://github.com/apache/airflow/pull/32282)
     - [Separate out advanced logging configuration (#32131)](https://github.com/apache/airflow/pull/32131)
- [ ] [Sanitize `DagRun.run_id` and allow flexibility (#32293)](https://github.com/apache/airflow/pull/32293): @ephraimbuddy
- [x] [Replace re with re2 (#32303)](https://github.com/apache/airflow/pull/32303): @pierrejeambrun
- [x] [Fix Pydantic 2 pickiness about model definition (#32307)](https://github.com/apache/airflow/pull/32307): @Iceazy @potiuk
     Linked issues:
     - [= instead of : in type hints - failing Pydantic 2 (#32301)](https://github.com/apache/airflow/issues/32301)
- [x] [Hide sensitive values from extra in connection edit form (#32309)](https://github.com/apache/airflow/pull/32309): @potiuk
- [x] [Limit Pydantic to < 2.0.0 until we solve 2.0.0 incompatibilities (#32312)](https://github.com/apache/airflow/pull/32312): @potiuk
     Linked issues:
     - [Pydantic 2.0.0 support for Airflow (#32311)](https://github.com/apache/airflow/issues/32311)
- [ ] [Retry transactions on occasional deadlocks for rendered fields (#32341)](https://github.com/apache/airflow/pull/32341): @vizeit @potiuk @amagr
     Linked issues:
     - [Retry deadlocked transactions on deleting old rendered task fields (#18616)](https://github.com/apache/airflow/pull/18616)
     - [K8 executor throws MySQL DB error 'Deadlock found when trying to get lock; try restarting transaction' (#32294)](https://github.com/apache/airflow/issues/32294)
     - [Deadlock when airflow try to update 'k8s_pod_yaml' in 'rendered_task_instance_fields' table (#29687)](https://github.com/apache/airflow/issues/29687)
- [ ] [Fix try_number shown in the `task?task_id=&dag_id=&execution_date=` (#32361)](https://github.com/apache/airflow/pull/32361): @aamster @Adaverse
     Linked issues:
     - [Try number is incorrect (#32290)](https://github.com/apache/airflow/issues/32290)
- [ ] [Use WebEncoder to encode DagRun.conf in DagRun's list view (#32385)](https://github.com/apache/airflow/pull/32385): @hussein-awala @tatiana @xuganyu96 @ReadytoRocc
     Linked issues:
     - [Make the DAG Run UI view more reliable by removing the column `config` (#32288)](https://github.com/apache/airflow/pull/32288)
     - [Fix dag run conf encoding with non-JSON serializable values (#28777)](https://github.com/apache/airflow/pull/28777)
     - [DAG Run List UI Breaks when a non-JSON serializable value is added to dag_run.conf (#28772)](https://github.com/apache/airflow/issues/28772)
     - [Unable to show DAG Runs in the UI if webserver fails to parse a  DAG Run `config` (#32287)](https://github.com/apache/airflow/issues/32287)
- [x] [Add information on ARM MySQL support in Docker images (#32401)](https://github.com/apache/airflow/pull/32401): @Taragolis @potiuk
     Linked issues:
     - [Use MariaDB client binaries in arm64 image for support MySQL backend (#29519)](https://github.com/apache/airflow/pull/29519)
- [x] [Fix failing main due to new release of jsonschema (#32405)](https://github.com/apache/airflow/pull/32405): @eladkal
- [x] [Limit click until we fix mypy issues (#32413)](https://github.com/apache/airflow/pull/32413): @potiuk
     Linked issues:
     - [Click 8.1.4 breaks mypy typing checks (#32412)](https://github.com/apache/airflow/issues/32412)

Thanks to all who contributed to the release (probably not a complete list!):
@PaleNeutron @Iceazy @stijndehaes @ReadytoRocc @tomrutter @raphaelauv @mathbou @Scope0910 @mis98zb @dstandish @pierrejeambrun @cvaliente @o-nikolas @dzhigimont @ephraimbuddy @Taragolis @NikitasB @Lee-W @amoghrajesh @phanikumv @jgmarcel @eladkal @potiuk @tirkarthi @Adaverse @harrisonharris-di @hussein-awala @amagr @utkarsharma2 @vizeit @dimberman @mikelius2b @tatiana @aamster @xuganyu96 @mobuchowski @uranusjr

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
Checked all mine. most of them were dev-only.
Specifically checked #32309 -> works as expected

**Comment by xuganyu96** [comment]
#32385 looks good. Thank you!

**Comment by amoghrajesh** [comment]
Tested out https://github.com/apache/airflow/pull/31465 by trying a couple of connections. Looks good 👍🏽

**Comment by utkarsharma2** [comment]
Tested #31866 <https://github.com/apache/airflow/pull/31866> with old Xcom
values, working as expected.

**Comment by Adaverse** [comment]
Tested #32361 works as expected.

**Comment by vatsrahul1001** [comment]
Verified #32123, one observation, it seems there is a need to update the unreleased [documentation](http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airfalow/latest/authoring-and-scheduling/deferring.html#high-availability) to reflect the new dynamically calculated threshold instead of the hardcoded 30-second time.
![image (1)](https://github.com/apache/airflow/assets/43964496/aa1e8e00-2bdc-4be2-84fb-8a17a168cd00)

**Comment by hussein-awala** [comment]
@vatsrahul1001 I created #32454 to fix the doc, however I don't think we need to create a new RC for this small problem, and if I am not mistaken, there is a way to create a manual Airflow documentation release (cc: @potiuk)

**Comment by vatsrahul1001** [comment]
Verified [#32361]https://github.com/apache/airflow/pull/32361, [#31866](https://github.com/apache/airflow/pull/31866) from my end as well

**Comment by potiuk** [comment]
Yes. We can cherry-pick #32454 and rebuild the docs after release. No problems with that.

**Comment by hussein-awala** [comment]
I've tested my changes (except #32385), they work as expected

**Comment by tomrutter** [comment]
Happy with #32092 <https://github.com/apache/airflow/pull/32092> too.
Thanks for including this in the release!

**Comment by pierrejeambrun** [comment]
Not easy to test https://github.com/apache/airflow/pull/32060 and https://github.com/apache/airflow/pull/32303, but seems to work as expected.

**Comment by ephraimbuddy** [comment]
Apache Airflow 2.6.3 has been released. Thank you all for testing this release!
