### ISSUE TITLE
Implement `breeze publish-docs` command

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#32491]
### Body

We need a small improvement for our docs publishing process.

We currently have those two scripts:

* [x] docs/publish_docs.py https://github.com/apache/airflow/blob/main/docs/publish_docs.py in airflow repo
* [ ] post-docs/ in airflow-site https://github.com/apache/airflow-site/blob/main/post-docs/add-back-references.py

We have currently the steps that are describing how to publish the documentation in our release documentation:

* https://github.com/apache/airflow/blob/main/dev/README_RELEASE_AIRFLOW.md
* https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md
* https://github.com/apache/airflow/blob/main/dev/README_RELEASE_HELM_CHART.md

This is the "Publish documentation"  chapter

They currently consists of few steps:

1) checking out the main in "airflow-sites"
2) setting the AIRFLOW_SITE_DIRECTORY env variable to the checked out repo
3) building docs (with `breeze build-docs`) 
4) Running publish_docs.py scripts in docs that copies the generated docs to "AIRFLOW_SITE_DIRECTORY" 
5) **I just added those** running post-docs post-processing for back references
6) Commiting the changes and pushing them to airflow-site

(there are few variants of those depends what docs you are building).

The problem with that is that it requires several venvs to setup independently (and they might sometimes miss stuff) and those commands are distributed across repositories. 

The goal of the change is to replace publish + post-docs with single, new breeze command - similarly as we have "build-docs" now.

I imagine this command should be similar to:

```
breeze publish-docs --airflow-site-directory DIRECTORY --package-filter .... and the rest of other arguments that publish_docs.py has 
```

This command should copy the files and run post-processing on back-references (depending which package documentation we publish).

Then the process of publish docs should like:

1) checking out the main in "airflow-sites"
2) setting the AIRFLOW_SITE_DIRECTORY env variable to the checked out repo
3) building docs (with `breeze build-docs`) 
4) publishing docs (with `breeze publish-docs`) 
5) Commiting the changes and pushing them to airflow-site

The benefits:

* no separate venvs to manage (all done in breeze's env) - automatically manged
* nicer integration in our dev/CI environment
* all code for publishing docs in one place - in breeze

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by amoghrajesh** [comment]
Amazing issue. Liked the whole idea of it. 
I will be working on this :)

**Comment by amoghrajesh** [comment]
However, I dont think we should retire the `build-docs` command. Sometimes it can only be used for testing, without copying or having the intention to publish it.
WDYT? @potiuk

**Comment by potiuk** [comment]
`build-docs` MUST stay. the `publish-docs` should be separate step from buiding docs

**Comment by potiuk** [comment]
Those are two distinct commands:

* `build-docs` builds them in `docs/_build` of checked out "apache/airflow" repo
* `publish-docs` should take the docs built by `build-doc` in "apache/airflow/" repo and copy them to "airflow-site" folder checked out elsewhere

**Comment by amoghrajesh** [comment]
Makes sense. We do not want to retire the build-docs AT all.

**Comment by amoghrajesh** [comment]
@potiuk instead of doing the whole task in one shot, imo it is better if we do it step by step. First PR in this series is here: https://github.com/apache/airflow/pull/32495

**Comment by potiuk** [comment]
> @potiuk instead of doing the whole task in one shot, imo it is better if we do it step by step. First PR in this series is here: #32495

Well. Breeze will not work with importing the "docs" folder from elsewhere, so at the very least the code must be copied to "breeze".

**Comment by amoghrajesh** [comment]
Makes sense. I suspected this portion. Making the changes accordingly

**Comment by potiuk** [comment]
OK. the first part (publish-docs) Merged with #32495. Now time to also move `post-docs` to breeze, following the same patterns @amoghrajesh :).

I thought a bit and I think we want to have a separate command for that ("add-back-references"?) because sometimes we might want to post-process the documentation without actually publishing new docs.

**Comment by amoghrajesh** [comment]
Yes of course.

We should have another command under release-management called 'process-published-docs' or so that does that post docs stuff on the docs published.

These two should be run in conjunction to achieve the final results.

Wdyt?

**Comment by potiuk** [comment]
yep.

**Comment by potiuk** [comment]
Also see my https://github.com/apache/airflow/pull/32556 where I re-organized other release commands to be consistent and nicer groupped (and documented - I realized few of them were hidden as I found out while reviewing your changes )

**Comment by amoghrajesh** [comment]
@potiuk should we close this issue and open a new one to track the `add-back-references`? I think that would be more convenient.

**Comment by potiuk** [comment]
We often have several PRs for the same "task" this is pretty expected and has no bad effects - we hav check-boxes in the issue when we track what's left and the last PR has "Fixes: #issue" - this is far less of an overhead than having to create new issues

**Comment by amoghrajesh** [comment]
Thanks for informing me that. I'll adhere to that

**Comment by amoghrajesh** [comment]
@potiuk do you see anything more pending on this task? I think we have completed it here :)

Might want to ask all the users to rebase their PRs

**Comment by potiuk** [comment]
No need to ask. All seems good.
