### ISSUE TITLE
Status of testing Providers that were prepared on July 12, 2023

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#32568]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 8.3.1rc1](https://pypi.org/project/apache-airflow-providers-amazon/8.3.1rc1)
   - [ ] [Append region info to S3ToRedshitOperator if present (#32328)](https://github.com/apache/airflow/pull/32328): @richardbadman
## Provider [cncf.kubernetes: 7.3.0rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/7.3.0rc1)
   - [x] [Logging from all containers in KubernetesOperatorPod (#31663)](https://github.com/apache/airflow/pull/31663): @amoghrajesh
   - [ ] [Fix async KPO by waiting pod termination in `execute_complete` before cleanup (#32467)](https://github.com/apache/airflow/pull/32467): @hussein-awala
## Provider [google: 10.4.0rc1](https://pypi.org/project/apache-airflow-providers-google/10.4.0rc1)
   - [ ] [Bugfix GCSToGCSOperator when copy files to folder without wildcard (#32486)](https://github.com/apache/airflow/pull/32486): @moiseenkov
   - [ ] [Fix `cache_control` parameter of upload function in `GCSHook`  (#32440)](https://github.com/apache/airflow/pull/32440): @shahar1
   - [x] [Fix BigQuery transfer operators to respect project_id arguments (#32232)](https://github.com/apache/airflow/pull/32232): @avinashpandeshwar
   - [ ] [Fix the gcp_gcs_delete_objects operator delete whole bucket on processing empty list of objects (#32383)](https://github.com/apache/airflow/pull/32383): @yupbank
   - [x] [Fix endless loop of defer in google cloud_build (#32387)](https://github.com/apache/airflow/pull/32387): @tnk-ysk
   - [ ] [Bugfix GCSToGCSOperator when copy an object without wildcard and exact_match=True (#32376)](https://github.com/apache/airflow/pull/32376): @moiseenkov
   - [x] [Allow a destination folder to be provided (#31885)](https://github.com/apache/airflow/pull/31885): @stiak
   - [ ] [Moves `AzureBlobStorageToGCSOperator` from Azure to Google provider (#32306)](https://github.com/apache/airflow/pull/32306): @Adaverse
   - [ ] [Give better link to job configuration docs in BigQueryInsertJobOperator (#31736)](https://github.com/apache/airflow/pull/31736): @rafalh
## Provider [http: 4.5.0rc1](https://pypi.org/project/apache-airflow-providers-http/4.5.0rc1)
   - [x] [Add deferrable mode to SimpleHttpOperator (#32448)](https://github.com/apache/airflow/pull/32448): @tnk-ysk
   - [ ] [Fix headers passed into HttpAsyncHook (#32409)](https://github.com/apache/airflow/pull/32409): @sumeshpremraj
## Provider [microsoft.azure: 6.2.1rc1](https://pypi.org/project/apache-airflow-providers-microsoft-azure/6.2.1rc1)
   - [x] [Fix breaking change when Active Directory ID is used as host in WASB (#32560)](https://github.com/apache/airflow/pull/32560): @ephraimbuddy
   - [x] [Fix get_blobs_list_async method to return BlobProperties (#32545)](https://github.com/apache/airflow/pull/32545): @potiuk
   - [x] [Moves `AzureBlobStorageToGCSOperator` from Azure to Google provider (#32306)](https://github.com/apache/airflow/pull/32306): @Adaverse

## Provider [sftp: 4.4.0rc1](https://pypi.org/project/apache-airflow-providers-sftp/4.4.0rc1)
   - [x] [Adds sftp_sensor decorator (#32457)](https://github.com/apache/airflow/pull/32457): @Adaverse
## Provider [snowflake: 4.3.1rc1](https://pypi.org/project/apache-airflow-providers-snowflake/4.3.1rc1)
   - [ ] [Fix an issue that crashes Airflow Webserver when passed invalid private key path to Snowflake (#32016)](https://github.com/apache/airflow/pull/32016): @bjankie1

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-by-contributors)

All users involved in the PRs:
@stiak @shahar1 @sumeshpremraj @rafalh @Adaverse @richardbadman @moiseenkov @ephraimbuddy @amoghrajesh @yupbank @bjankie1 @potiuk @hussein-awala @tnk-ysk @avinashpandeshwar

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by stiak** [comment]
I've tested my PR (https://github.com/apache/airflow/pull/31885) with the release candidate and was able to copy files into a folder by ID.

**Comment by Lee-W** [comment]
I've tested the following providers with our example DAGs without encountering errors.

* apache-airflow-providers-amazon
* apache-airflow-providers-cncf-kubernetes
* apache-airflow-providers-google
* apache-airflow-providers-http
* apache-airflow-providers-microsoft-azure
* apache-airflow-providers-sftp
* apache-airflow-providers-snowflake

**Comment by amoghrajesh** [comment]
Tested the provider: apache-airflow-providers-cncf-kubernetes successfully without any error.

**Comment by tnk-ysk** [comment]
I tested #32387, #32448. it works as expected

**Comment by vatsrahul1001** [comment]
Verified #32560

**Comment by Adaverse** [comment]
Ran example dags for #32457 #32306 works as expected. Thanks.

**Comment by avinashpandeshwar-sharechat** [comment]
Verified https://github.com/apache/airflow/pull/32232

**Comment by potiuk** [comment]
#32545 works

**Comment by eladkal** [comment]
Thank you everyone.
Providers are released
I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
