### ISSUE TITLE
Status of testing Providers that were prepared on July 17, 2023

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#32640]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [elasticsearch: 5.0.0rc3](https://pypi.org/project/apache-airflow-providers-elasticsearch/5.0.0rc3)
   - [x] [Deprecate the 2 non-official elasticsearch libraries (#31920)](https://github.com/apache/airflow/pull/31920): @Owen-CH-Leung
   - [x] [Update type hint for ElasticsearchTaskHandler.es_read to reflect integer usage (#32509)](https://github.com/apache/airflow/pull/32509): @cushionbadak
   - [x] [Fix Failing ES Remote Logging (#32438)](https://github.com/apache/airflow/pull/32438): @Owen-CH-Leung

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-by-contributors)

All users involved in the PRs:
@cushionbadak @Owen-CH-Leung

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by Owen-CH-Leung** [comment]
Tested the RC for ES remote logging and can confirm that the PR fixes the remote logging issue that were discovere =) Should be good to go

**Comment by eladkal** [comment]
Thank you everyone.
elasticsearch provider is released
I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
