### ISSUE TITLE
Status of testing Providers that were prepared on August 05, 2023

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#33132]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 8.5.0rc1](https://pypi.org/project/apache-airflow-providers-amazon/8.5.0rc1)
   - [x] [openlineage, sagemaker: add OpenLineage support for SageMaker's Processing, Transform and Training operators (#31816)](https://github.com/apache/airflow/pull/31816): @mobuchowski
   - [ ] [Add Amazon EventBridge PutRule hook and operator (#32869)](https://github.com/apache/airflow/pull/32869): @mahammi
   - [ ] [Add GCS Requester Pays bucket support to GCSToS3Operator (#32760)](https://github.com/apache/airflow/pull/32760): @hankehly
   - [x] [Check google provider version in GCSToS3Operator before provide match_glob param (#32925)](https://github.com/apache/airflow/pull/32925): @hussein-awala
   - [x] [FIX: set longer default `waiter_max_attempts` for deferred BatchJobOperator (#33045)](https://github.com/apache/airflow/pull/33045): @rishi-kulkarni
   - [x] [openlineage, sagemaker: add missing OpenLineage type signature (#33114)](https://github.com/apache/airflow/pull/33114): @mobuchowski
   - [x] [Add S3Bucket for mypy (#33028)](https://github.com/apache/airflow/pull/33028): @kimdwkimdw
## Provider [apache.drill: 2.4.3rc1](https://pypi.org/project/apache-airflow-providers-apache-drill/2.4.3rc1)
   - [x] [Validate database URL passed to create_engine of Drill hook's connection (#33074)](https://github.com/apache/airflow/pull/33074): @pankajkoti
## Provider [apache.hive: 6.1.4rc1](https://pypi.org/project/apache-airflow-providers-apache-hive/6.1.4rc1)
   - [x] [Bring back mysql-connector-python as required dependency (#32989)](https://github.com/apache/airflow/pull/32989): @potiuk
## Provider [apache.spark: 4.1.3rc1](https://pypi.org/project/apache-airflow-providers-apache-spark/4.1.3rc1)
   - [x] [Validate conn_prefix in extra field for Spark JDBC hook (#32946)](https://github.com/apache/airflow/pull/32946): @pankajkoti
## Provider [apache.sqoop: 4.0.0rc1](https://pypi.org/project/apache-airflow-providers-apache-sqoop/4.0.0rc1)
   - [x] [Validate SqoopHook connection string and disable extra options from public hook methods (#33039)](https://github.com/apache/airflow/pull/33039): @pankajkoti
   - [x] [Validate connection host field for Sqoop connection (#32968)](https://github.com/apache/airflow/pull/32968): @pankajkoti
   - [x] [Remove spurious headers for provider changelogs (#32373)](https://github.com/apache/airflow/pull/32373): @potiuk
   - [x] [Improve provider documentation and README structure (#32125)](https://github.com/apache/airflow/pull/32125): @potiuk
## Provider [asana: 2.2.2rc1](https://pypi.org/project/apache-airflow-providers-asana/2.2.2rc1)
   - [x] [Limit Asana Python client until provider is adapted to 4.* version (#32995)](https://github.com/apache/airflow/pull/32995): @potiuk
## Provider [celery: 3.3.1rc1](https://pypi.org/project/apache-airflow-providers-celery/3.3.1rc1)
   - [x] [Add documentation generation for CLI commands from executors (#33081)](https://github.com/apache/airflow/pull/33081): @potiuk
   - [ ] [Get rid of Python2 numeric relics (#33050)](https://github.com/apache/airflow/pull/33050): @eumiro
## Provider [cncf.kubernetes: 7.4.1rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/7.4.1rc1)
   - [x] [Fix waiting the base container when reading the logs of other containers (#33127)](https://github.com/apache/airflow/pull/33127): @hussein-awala
   - [ ] [Fix: Configurable Docker image of `xcom_sidecar` (#32858)](https://github.com/apache/airflow/pull/32858): @pegasas
   - [x] [Fix KPO sub classes default container_logs (#33090)](https://github.com/apache/airflow/pull/33090): @hussein-awala
   - [x] [Consider custom pod labels on pod finding process on KubernetesPodOperator (#33057)](https://github.com/apache/airflow/pull/33057): @okayhooni
   - [x] [Add documentation generation for CLI commands from executors (#33081)](https://github.com/apache/airflow/pull/33081): @potiuk
## Provider [common.sql: 1.6.2rc1](https://pypi.org/project/apache-airflow-providers-common-sql/1.6.2rc1)
   - [x] [Make `SQLExecuteQueryOperator` signature consistent with other SQL operators (#32974)](https://github.com/apache/airflow/pull/32974): @potiuk
   - [ ] [Get rid of Python2 numeric relics (#33050)](https://github.com/apache/airflow/pull/33050): @eumiro
## Provider [docker: 3.7.2rc1](https://pypi.org/project/apache-airflow-providers-docker/3.7.2rc1)
   - [ ] [Get rid of Python2 numeric relics (#33050)](https://github.com/apache/airflow/pull/33050): @eumiro
## Provider [ftp: 3.5.0rc1](https://pypi.org/project/apache-airflow-providers-ftp/3.5.0rc1)
   - [x] [openlineage, ftp: add OpenLineage support for FTPFileTransferOperator (#31354)](https://github.com/apache/airflow/pull/31354): @mobuchowski
## Provider [google: 10.6.0rc1](https://pypi.org/project/apache-airflow-providers-google/10.6.0rc1)
   - [x] [openlineage, bigquery: add openlineage method support for BigQueryInsertJobOperator (#31293)](https://github.com/apache/airflow/pull/31293): @mobuchowski
   - [ ] [Add GCS Requester Pays bucket support to GCSToS3Operator (#32760)](https://github.com/apache/airflow/pull/32760): @hankehly
   - [x] [Add system test and docs for CloudDataTransferServiceGCSToGCSOperator (#32960)](https://github.com/apache/airflow/pull/32960): @moiseenkov
   - [ ] [Fix names of resources in Datafusion system tests (#32855)](https://github.com/apache/airflow/pull/32855): @VladaZakharova
   - [x] [Fix system test for MetastoreHivePartitionSensor (#32861)](https://github.com/apache/airflow/pull/32861): @moiseenkov
## Provider [imap: 3.3.0rc1](https://pypi.org/project/apache-airflow-providers-imap/3.3.0rc1)
   - [x] [Allows to choose SSL context for IMAP provider (#33108)](https://github.com/apache/airflow/pull/33108): @potiuk
   - [x] [Add possibility to use `ssl_context` extra for SMTP and IMAP connections (#33112)](https://github.com/apache/airflow/pull/33112): @potiuk
## Provider [microsoft.azure: 6.2.3rc1](https://pypi.org/project/apache-airflow-providers-microsoft-azure/6.2.3rc1)
   - [x] [Refactor account_url use in WasbHook (#32980)](https://github.com/apache/airflow/pull/32980): @ephraimbuddy
## Provider [mysql: 5.2.1rc1](https://pypi.org/project/apache-airflow-providers-mysql/5.2.1rc1)
   - [x] [Bring back mysql-connector-python as required dependency (#32989)](https://github.com/apache/airflow/pull/32989): @potiuk
## Provider [openlineage: 1.0.1rc1](https://pypi.org/project/apache-airflow-providers-openlineage/1.0.1rc1)
   - [x] [openlineage: disable running listener if not configured (#33120)](https://github.com/apache/airflow/pull/33120): @mobuchowski
   - [ ] [openlineage: don't use database as fallback when no schema parsed. (#32959)](https://github.com/apache/airflow/pull/32959): @JDarDagran
   - [x] [openlineage, bigquery: add openlineage method support for BigQueryInsertJobOperator (#31293)](https://github.com/apache/airflow/pull/31293): @mobuchowski
   - [x] [Move openlineage configuration to provider (#33124)](https://github.com/apache/airflow/pull/33124): @potiuk
## Provider [redis: 3.3.1rc1](https://pypi.org/project/apache-airflow-providers-redis/3.3.1rc1)
   - [x] #33138
## Provider [smtp: 1.3.0rc1](https://pypi.org/project/apache-airflow-providers-smtp/1.3.0rc1)
   - [x] [Add possibility to use `ssl_context` extra for SMTP and IMAP connections (#33112)](https://github.com/apache/airflow/pull/33112): @potiuk
   - [x] [Allows to choose SSL context for SMTP provider (#33075)](https://github.com/apache/airflow/pull/33075): @potiuk
## Provider [snowflake: 4.4.1rc1](https://pypi.org/project/apache-airflow-providers-snowflake/4.4.1rc1)
   - [x] [Fix connection parameters of `SnowflakeValueCheckOperator` (#32605)](https://github.com/apache/airflow/pull/32605): @frodo2000

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-by-contributors)

All users involved in the PRs:
@pankajkoti @moiseenkov @okayhooni @hankehly @frodo2000 @VladaZakharova @hussein-awala @mahammi @mobuchowski @kimdwkimdw @ephraimbuddy @potiuk @eumiro @pegasas @rishi-kulkarni @JDarDagran

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by rishi-kulkarni** [comment]
I can confirm that #33045 makes them default timeout sufficiently long.

**Comment by hankehly** [comment]
#32760 works on main branch (provider versions seem to match above).

Could someone please tell me how to install specific provider versions in a breeze environment? I am having some trouble following the directions in https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#provider-packages

**Comment by potiuk** [comment]
> #32760 works on main branch (provider versions seem to match above).
> 
> Could someone please tell me how to install specific provider versions in a breeze environment? I am having some trouble following the directions in https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#provider-packages

See the link posted in the issue at the top [Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-by-contributors)

There are very precise instructions.

**Comment by potiuk** [comment]
Checked all my changes - they all look good - except redis. I found out that the fix caused multiple "subscribe" calls for the sensor, so would likely cause problems. We should remove redis from the list, the fix for rc2 is coming.

**Comment by eladkal** [comment]
google and redis provider will be excluded from RC1 and will have rc2

PR to be included in RC2 of redis:
https://github.com/apache/airflow/pull/33139

PR to be included in RC2 of google:
https://github.com/apache/airflow/pull/33148

**Comment by mobuchowski** [comment]
Tested mine changes, they look good.

**Comment by hussein-awala** [comment]
Tested my changes, they are included and they work as expected

**Comment by kimdwkimdw** [comment]
Tested my changes with https://pypi.org/project/apache-airflow-providers-amazon/8.5.0rc1/

**Comment by okayhooni** [comment]
Tested my minor changes worked well
https://github.com/apache/airflow/pull/33057

**Comment by ephraimbuddy** [comment]
Tested my refactor on azure https://github.com/apache/airflow/pull/32980

**Comment by moiseenkov** [comment]
#32960 and #32861 work as expected
```
apache-airflow-providers-google==10.6.0rc1
apache-airflow-providers-celery==3.3.1rc1
apache-airflow-providers-amazon==8.5.0rc1
apache-airflow-providers-cncf-kubernetes==7.4.1rc1
```

**Comment by frodo2000** [comment]
#32605 <https://github.com/apache/airflow/pull/32605>  work as expected

apache-airflow-providers-snowflake==4.4.1rc1


pon., 7 sie 2023 o 10:27 max ***@***.***> napisał(a):

**Comment by pankajkoti** [comment]
Tested https://github.com/apache/airflow/pull/33074, https://github.com/apache/airflow/pull/32946, https://github.com/apache/airflow/pull/33039, https://github.com/apache/airflow/pull/32968

Verified they are included in the RCs, ran tests and verified they work as expected.

**Comment by eladkal** [comment]
Thank you everyone.
Providers are released

google and redis providers are excluded, I will cut RC2 shortly

I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
