### ISSUE TITLE
Status of testing Providers that were prepared on August 08, 2023

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#33193]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [google: 10.6.0rc2](https://pypi.org/project/apache-airflow-providers-google/10.6.0rc2)
   - [x] [openlineage, bigquery: add openlineage method support for BigQueryInsertJobOperator (#31293)](https://github.com/apache/airflow/pull/31293): @mobuchowski
   - [ ] [Add GCS Requester Pays bucket support to GCSToS3Operator (#32760)](https://github.com/apache/airflow/pull/32760): @hankehly
   - [x] [Add system test and docs for CloudDataTransferServiceGCSToGCSOperator (#32960)](https://github.com/apache/airflow/pull/32960): @moiseenkov
   - [x] [Add a new parameter to SQL operators to specify conn id field (#30784)](https://github.com/apache/airflow/pull/30784): @hussein-awala
   - [ ] [Fix names of resources in Datafusion system tests (#32855)](https://github.com/apache/airflow/pull/32855): @VladaZakharova
   - [x] [Fix system test for MetastoreHivePartitionSensor (#32861)](https://github.com/apache/airflow/pull/32861): @moiseenkov
   - [ ] [Implement new way of checking 409 error for Datafusion pipeline (#33173)](https://github.com/apache/airflow/pull/33173): @VladaZakharova
## Provider [redis: 3.3.1rc2](https://pypi.org/project/apache-airflow-providers-redis/3.3.1rc2)
   - [x] [Move redis subscribe to poke() method in Redis Sensor (#32984)](https://github.com/apache/airflow/pull/32984): @potiuk
   - [x] [Fix oversubsription of Redis pubsub sensor (#33139)](https://github.com/apache/airflow/pull/33139): @potiuk

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

All users involved in the PRs:
@hussein-awala @mobuchowski @VladaZakharova @moiseenkov @hankehly @potiuk

Previous RC1 track: https://github.com/apache/airflow/issues/33132

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by eladkal** [comment]
Items that were reported as tested in RC1 are also marked as tested in RC2 but feel free to test again

**Comment by Lee-W** [comment]
May I know if we're going to include https://github.com/apache/airflow/pull/33148 in this release? Thanks!

**Comment by moiseenkov** [comment]
Rechecked #32960 and #32861, they are working fine.

**Comment by eladkal** [comment]
> May I know if we're going to include #33148 in this release? Thanks!

It is included. Please check RC2 and let us know if resolved

**Comment by potiuk** [comment]
Checked the redis changes. They were already tested during integration tests we have, the code I added is there.

**Comment by hussein-awala** [comment]
I tested my change, it is useless without releasing the new version of common sql, but I took the opportunity to make sure that there is no breaking change with the old version of common sql.

**Comment by eladkal** [comment]
Thank you everyone.
Redis providers is released
Google provider has been removed from the release and RC3 is expected shortly.
I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
