### ISSUE TITLE
Status of testing Providers that were prepared on August 09, 2023

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#33257]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [google: 10.6.0rc3](https://pypi.org/project/apache-airflow-providers-google/10.6.0rc3)
   - [x] [openlineage, bigquery: add openlineage method support for BigQueryInsertJobOperator (#31293)](https://github.com/apache/airflow/pull/31293): @mobuchowski
   - [x] [Add GCS Requester Pays bucket support to GCSToS3Operator (#32760)](https://github.com/apache/airflow/pull/32760): @hankehly
   - [x] [Add system test and docs for CloudDataTransferServiceGCSToGCSOperator (#32960)](https://github.com/apache/airflow/pull/32960): @moiseenkov
   - [x] [Add a new parameter to SQL operators to specify conn id field (#30784)](https://github.com/apache/airflow/pull/30784): @hussein-awala
   - [x] [Fix names of resources in Datafusion system tests (#32855)](https://github.com/apache/airflow/pull/32855): @VladaZakharova
   - [x] [Fix system test for MetastoreHivePartitionSensor (#32861)](https://github.com/apache/airflow/pull/32861): @moiseenkov
   - [x] [Implement new way of checking 409 error for Datafusion pipeline (#33173)](https://github.com/apache/airflow/pull/33173): @VladaZakharova
   - [x] [make `sql` a cached property in `BigQueryInsertJobOperator` (#33218)](https://github.com/apache/airflow/pull/33218): @mobuchowski
   - [x] [add deprecation warning to DATAPROC_JOB_LOG_LINK (#33189)](https://github.com/apache/airflow/pull/33189): @Lee-W

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

All users involved in the PRs:
@mobuchowski @hankehly @VladaZakharova @Lee-W @moiseenkov @hussein-awala

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by eladkal** [comment]
Items that were reported as tested in [RC2](https://github.com/apache/airflow/issues/33193) are also marked as tested in RC3 but feel free to test again

**Comment by Lee-W** [comment]
Tested with our example dags and everything works as expected. Thanks!

**Comment by eladkal** [comment]
Thank you everyone.
Google provider is released
I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
