### ISSUE TITLE
Status of testing Providers that were prepared on August 29, 2023

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#33875]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [cncf.kubernetes: 7.5.0rc2](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/7.5.0rc2)
   - [x] [Add istio test, use curl /quitquitquit to exit sidecar, and some othe… (#33306)](https://github.com/apache/airflow/pull/33306): @Owen-CH-Leung
   - [x] [Add `active_deadline_seconds` parameter to `KubernetesPodOperator` (#33379)](https://github.com/apache/airflow/pull/33379): @amoghrajesh
   - [x] [Make cluster_context templated in KubernetesPodOperator (#33604)](https://github.com/apache/airflow/pull/33604): @mati-o
   - [x] [Fix KubernetesPodOperator duplicating logs when interrupted (#33500)](https://github.com/apache/airflow/pull/33500): @fdemiane
   - [x] [Fix 2.7.0 db migration job errors (#33652)](https://github.com/apache/airflow/pull/33652): @LipuFei
   - [ ] [Inspect container state rather than last_state when deciding whether to skip (#33702)](https://github.com/apache/airflow/pull/33702): @SamWheating
   - [x] [Fix kill istio proxy logic (#33779)](https://github.com/apache/airflow/pull/33779): @Owen-CH-Leung
   - [x] [Introducing class constant to make worker pod log lines configurable (#33378)](https://github.com/apache/airflow/pull/33378): @amoghrajesh
   - [x] [Adding typing for KPO SCC objects (#33381)](https://github.com/apache/airflow/pull/33381): @amoghrajesh
   - [x] [Refactor: Improve detection of duplicates and list sorting (#33675)](https://github.com/apache/airflow/pull/33675): @eumiro
   - [x] [Refactor Sqlalchemy queries to 2.0 style (Part 7) (#32883)](https://github.com/apache/airflow/pull/32883): @phanikumv
   - [x] [Always use Literal from typing_extensions (#33794)](https://github.com/apache/airflow/pull/33794): @Taragolis
   - [x] [Use literal dict instead of calling dict() in providers (#33761)](https://github.com/apache/airflow/pull/33761): @hussein-awala
   - [x] [Improve modules import in cncf.kubernetes provider by move some of them into a type-checking block (#33781)](https://github.com/apache/airflow/pull/33781): @hussein-awala
## Provider [microsoft.azure: 6.3.0rc2](https://pypi.org/project/apache-airflow-providers-microsoft-azure/6.3.0rc2)
   - [x] [Add AzureBatchOperator example (#33716)](https://github.com/apache/airflow/pull/33716): @Lee-W
   - [x] [feat(providers/microsoft): add DefaultAzureCredential support to AzureContainerInstanceHook (#33467)](https://github.com/apache/airflow/pull/33467): @Lee-W
   - [x] [Add DefaultAzureCredential auth for ADX service (#33627)](https://github.com/apache/airflow/pull/33627): @pankajastro
   - [x] [feat(providers/microsoft): add DefaultAzureCredential to data_lake (#33433)](https://github.com/apache/airflow/pull/33433): @Lee-W
   - [x] [feat(providers/azure): allow passing fully_qualified_namespace and credential to initialize Azure Service Bus Client (#33493)](https://github.com/apache/airflow/pull/33493): @Lee-W
   - [x] [feat(providers/microsoft): add DefaultAzureCredential support to cosmos (#33436)](https://github.com/apache/airflow/pull/33436): @Lee-W
   - [x] [ feat(providers/microsoft): add DefaultAzureCredential support to AzureBatchHook (#33469)](https://github.com/apache/airflow/pull/33469): @Lee-W
   - [x] [Fix updating account url for WasbHook (#33457)](https://github.com/apache/airflow/pull/33457): @ephraimbuddy
   - [x] [Fix Azure Batch Hook instantation (#33731)](https://github.com/apache/airflow/pull/33731): @potiuk
   - [x] [Truncate Wasb storage account name if it's more than 24 characters (#33851)](https://github.com/apache/airflow/pull/33851): @ephraimbuddy
   - [x] [Remove duplicated message commit in Azure MessageHook (#33776)](https://github.com/apache/airflow/pull/33776): @hussein-awala
   - [x] [fix(providers/azure): remove json.dumps when querying AzureCosmosDBHook (#33653)](https://github.com/apache/airflow/pull/33653): @Lee-W
   - [x] [Bump azure-kusto-data>=4.1.0 (#33598)](https://github.com/apache/airflow/pull/33598): @pankajastro
   - [x] [Set logging level to WARNING (#33314)](https://github.com/apache/airflow/pull/33314): @arjunanan6
   - [x] [Bump azure-mgmt-containerinstance>=7.0.0,<9.0.0 (#33696)](https://github.com/apache/airflow/pull/33696): @pankajastro
   - [x] [Improve modules import in Airflow providers by some of them into a type-checking block (#33754)](https://github.com/apache/airflow/pull/33754): @hussein-awala
   - [x] [Use a single  statement with multiple contexts instead of nested  statements in providers (#33768)](https://github.com/apache/airflow/pull/33768): @hussein-awala
   - [x] [remove unnecessary map and rewrite it using list in providers (#33763)](https://github.com/apache/airflow/pull/33763): @hussein-awala
   - [x] [Optimise Airflow DB backend usage in Azure Provider (#33750)](https://github.com/apache/airflow/pull/33750): @Taragolis

All users involved in the PRs:
@amoghrajesh @eumiro @fdemiane @LipuFei @mati-o @potiuk @SamWheating @phanikumv @pankajastro @arjunanan6 @Owen-CH-Leung @ephraimbuddy @Taragolis @Lee-W @hussein-awala

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by Lee-W** [comment]
Verified https://github.com/apache/airflow/pull/33716, https://github.com/apache/airflow/pull/33467, https://github.com/apache/airflow/pull/33433, https://github.com/apache/airflow/pull/33493, https://github.com/apache/airflow/pull/33469, https://github.com/apache/airflow/pull/33436, https://github.com/apache/airflow/pull/33653

**Comment by LipuFei** [comment]
Verified #33652

**Comment by fdemiane** [comment]
Verified #33500

**Comment by pankajastro** [comment]
https://github.com/apache/airflow/pull/33627, https://github.com/apache/airflow/pull/33598 and https://github.com/apache/airflow/pull/33696 looks good

**Comment by Owen-CH-Leung** [comment]
Verified #33306 , #33779 . Works as expected

**Comment by amoghrajesh** [comment]
Verified #33378 #33379 #33381, no regressions from the last time. They work as expected.

**Comment by potiuk** [comment]
Checked #33731. all good.

**Comment by arjunanan6** [comment]
Check #33314 and it's working as expected.

**Comment by hussein-awala** [comment]
Checked my changes, all looks good.

**Comment by mati-o** [comment]
Checked #33604, works as expected 🚀

**Comment by eladkal** [comment]
Thank you everyone.
Providers are released
I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
