### ISSUE TITLE
Status of testing Providers that were prepared on September 12, 2023

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#34302]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [dbt.cloud: 3.3.0rc2](https://pypi.org/project/apache-airflow-providers-dbt-cloud/3.3.0rc2)
   - [x] [openlineage, dbt: add OpenLineage support for DBT Cloud (#33959)](https://github.com/apache/airflow/pull/33959): @JDarDagran
   - [ ] [respect soft_fail argument when exception is raised for dbt sensors (#34164)](https://github.com/apache/airflow/pull/34164): @Lee-W
   - [ ] [dbt, openlineage: set run_id after defer, do not log error if operator has no run_id set (#34270)](https://github.com/apache/airflow/pull/34270): @mobuchowski
   - [x] [Remove some useless try/except from providers code (#33967)](https://github.com/apache/airflow/pull/33967): @hussein-awala
   - [x] [Use a single  statement with multiple contexts instead of nested  statements in providers (#33768)](https://github.com/apache/airflow/pull/33768): @hussein-awala

All users involved in the PRs:
@JDarDagran @mobuchowski @Lee-W @hussein-awala

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
Checked the packages (no changes or mine this time ) - looks good.

**Comment by hussein-awala** [comment]
Checked my changes, they are present in the RC.

**Comment by hussein-awala** [comment]
I created #34322 to remove the useless print which we cannot filter by controlling the logging level, but IMHO it is not a blocker for the RC, it could be released in the next wave.

**Comment by eladkal** [comment]
Thank you everyone.
Providers are released
I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
