### ISSUE TITLE
Status of testing of Apache Airflow Helm Chart 1.11.0rc2

### ISSUE THREAD

**Issue by jedcunningham** [apache/airflow#34660]
We are kindly requesting that contributors to [Apache Airflow Helm Chart 1.11.0rc1](https://dist.apache.org/repos/dist/dev/airflow/helm-chart/1.11.0rc1) help test the RC.

Please let us know by commenting if the issue is addressed in the latest RC.

- [x] [Defining priorityClasses for airflow services and workers (#31615)](https://github.com/apache/airflow/pull/31615): @amoghrajesh
- [ ] [Runtime class name (#31868)](https://github.com/apache/airflow/pull/31868): @Francesko90
- [x] [Chart: template dagprocessor waitformigrations extraVolumeMounts (#32100)](https://github.com/apache/airflow/pull/32100): @nirroz93 @Aakcht
     Linked issues:
     - [Template extra volumes in helm chart (#30773)](https://github.com/apache/airflow/pull/30773)
     - [Chart: add custom volumemounts to dag processor waitForMigrations init container (#30990)](https://github.com/apache/airflow/pull/30990)
- [x] [Support KEDA scaling for triggerer in the helm chart (#32302)](https://github.com/apache/airflow/pull/32302): @hussein-awala
- [ ] [Adds support for custom query in workers KEDA trigger (#32308)](https://github.com/apache/airflow/pull/32308): @hussein-awala
- [ ] [Chart: add support for container lifecycle hooks (#32349)](https://github.com/apache/airflow/pull/32349): @rzjfr
- [ ] [Move CeleryExecutor to the celery provider (#32526)](https://github.com/apache/airflow/pull/32526): @potiuk
- [x] [Add an option to use a direct DB connection in KEDA when pgbouncer is enabled (#32608)](https://github.com/apache/airflow/pull/32608): @hussein-awala @brokenjacobs
     Linked issues:
     - [When using KEDA and pgbouncer together, KEDA logs repeated prepared statement errors (#32590)](https://github.com/apache/airflow/issues/32590)
- [ ] [Fix chart named template comments (#32681)](https://github.com/apache/airflow/pull/32681): @jedcunningham
- [ ] [fix: remove K8S 1.23 support (#32899)](https://github.com/apache/airflow/pull/32899): @raphaelauv
- [x] [Replace `common.tplvalues.render` by `tpl` in ingress template files (#33384)](https://github.com/apache/airflow/pull/33384): @kimminw00 @hussein-awala
     Linked issues:
     - [Allow templating webserver ingress hostnames (#33142)](https://github.com/apache/airflow/pull/33142)
- [x] [Remove unnecessary loops used to load env from helm values (#33506)](https://github.com/apache/airflow/pull/33506): @hussein-awala
- [ ] [Fix chart schema defaults (#33518)](https://github.com/apache/airflow/pull/33518): @jedcunningham
- [x] [Ability to inject extra containers into pgbouncer (#33686)](https://github.com/apache/airflow/pull/33686): @amoghrajesh
- [x] [Chart: Update postgres subchart (#33747)](https://github.com/apache/airflow/pull/33747): @jedcunningham
- [x] [Chart: update gitsync (#33748)](https://github.com/apache/airflow/pull/33748): @jedcunningham
- [x] [Chart:  Add scheduler name to PODs templates (#33843)](https://github.com/apache/airflow/pull/33843): @wolvery
- [ ] [Add airflow db migrate command to migrateDatabaseJob (#34178)](https://github.com/apache/airflow/pull/34178): @kimminw00
- [ ] [Chart: Default airflow version to 2.7.1 (#34186)](https://github.com/apache/airflow/pull/34186): @ephraimbuddy
- [ ] [Add containerSecurityContext for cleanup cronjob (#34351)](https://github.com/apache/airflow/pull/34351): @kimminw00
     Linked issues:
     - [securityContext value for the cleanup container is not set properly (#34298)](https://github.com/apache/airflow/issues/34298)
- [x] [Add note for ingress on 31066 news fragment (#34354)](https://github.com/apache/airflow/pull/34354): @fgalind1
- [ ] [Remove unnecessary `or` function in template files (#34415)](https://github.com/apache/airflow/pull/34415): @kimminw00
- [ ] [Chart: Fix `runtimeClassName` for KE (#34631)](https://github.com/apache/airflow/pull/34631): @jedcunningham @Francesko90
     Linked issues:
     - [Runtime class name (#31868)](https://github.com/apache/airflow/pull/31868)
- [x] [Chart: Only create pod template file when using KE (#34633)](https://github.com/apache/airflow/pull/34633): @amoghrajesh @jedcunningham
     Linked issues:
     - [Adding startupProbe to airflow services charts (#33107)](https://github.com/apache/airflow/pull/33107)

Thanks to all who contributed to the release (probably not a complete list!):
@hussein-awala @jedcunningham @nirroz93 @raphaelauv @Aakcht @brokenjacobs @ephraimbuddy @amoghrajesh @Francesko90 @fgalind1 @potiuk @kimminw00 @rzjfr @wolvery

**Comment by rzjfr** [comment]
https://github.com/apache/airflow/pull/32349 unfortunately has an issue, I opened https://github.com/apache/airflow/pull/34677 to address that.

**Comment by Aakcht** [comment]
#32100 looks good.

**Comment by hussein-awala** [comment]
Tested my changes, all looks good!

**Comment by wolvery** [comment]
#33843 working properly!

**Comment by amoghrajesh** [comment]
Tested my changes https://github.com/apache/airflow/pull/31615 and https://github.com/apache/airflow/pull/33686. Both the PRs work as expected.

**Comment by fgalind1** [comment]
#34354 just a documentation change, all good. previous PR to support new naming convention working good 👍

**Comment by jedcunningham** [comment]
1.11.0 is (almost) out! Thanks everyone for taking the time to test the RC!

**Comment by kimminw00** [comment]
I tested #34178, #34351 and #34415. All the PRs works as expected!

**Comment by Francesko90** [comment]
Tested #31868 and #34631. Works fine

**Comment by brokenjacobs** [comment]
https://github.com/apache/airflow/issues/32590 uses the wrong port to connect to postgres, it defaults to port 6543 (the port provisioned for pgbouncer) instead of port 5433. Sorry I was out when this ask came in :(

**Comment by hussein-awala** [comment]
> #32590 uses the wrong port to connect to postgres, it defaults to port 6543 (the port provisioned for pgbouncer) instead of port 5433. Sorry I was out when this ask came in :(

I will check it

**Comment by brokenjacobs** [comment]
@hussein-awala please see https://github.com/apache/airflow/issues/34740
