### ISSUE TITLE
Status of testing Providers that were prepared on October 13, 2023

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#34930]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [alibaba: 2.6.0rc1](https://pypi.org/project/apache-airflow-providers-alibaba/2.6.0rc1)
   - [x] [Consolidate hook management in AnalyticDBSparkSensor (#34435)](https://github.com/apache/airflow/pull/34435): @hussein-awala
   - [x] [Consolidate hook management in AnalyticDBSparkBaseOperator (#34434)](https://github.com/apache/airflow/pull/34434): @hussein-awala
   - [x] [Deprecate get_hook in OSSKeySensor and use hook instead (#34426)](https://github.com/apache/airflow/pull/34426): @hussein-awala
## Provider [amazon: 8.8.0rc1](https://pypi.org/project/apache-airflow-providers-amazon/8.8.0rc1)
   - [x] [Implements `AwsBaseOperator` and `AwsBaseSensor` (#34784)](https://github.com/apache/airflow/pull/34784): @Taragolis
   - [x] [Extend hooks arguments into `AwsBaseWaiterTrigger` (#34884)](https://github.com/apache/airflow/pull/34884): @Taragolis
   - [x] [Allow setup `endpoint_url` per-service in AWS Connection (#34593)](https://github.com/apache/airflow/pull/34593): @Taragolis
   - [x] [Include AWS Lambda execution logs to task logs (#34692)](https://github.com/apache/airflow/pull/34692): @Taragolis
   - [ ] [respect soft_fail argument when exception is raised for amazon sensors (#34134)](https://github.com/apache/airflow/pull/34134): @Lee-W
   - [ ] [do not fail operator if we cannot find logs (#34570)](https://github.com/apache/airflow/pull/34570): @vandonr-amz
   - [x] [Respect 'soft_fail' argument when running BatchSensors (#34592)](https://github.com/apache/airflow/pull/34592): @utkarsharma2
   - [x] [Respect 'soft_fail' argument when running SqsSensor (#34569)](https://github.com/apache/airflow/pull/34569): @utkarsharma2
   - [x] [Respect 'soft_fail' argument when running EcsBaseSensor (#34596)](https://github.com/apache/airflow/pull/34596): @utkarsharma2
   - [x] [Respect 'soft_fail' argument when running SageMakerBaseSensor (#34565)](https://github.com/apache/airflow/pull/34565): @utkarsharma2
   - [x] [Respect soft_fail parameter in S3KeysUnchangedSensor and S3KeySensor (#34550)](https://github.com/apache/airflow/pull/34550): @utkarsharma2
   - [x] [Respect soft_fail parameter in LambdaFunctionStateSensor (#34551)](https://github.com/apache/airflow/pull/34551): @utkarsharma2
   - [x] [Respect soft_fail parameter in AthenaSensor (#34553)](https://github.com/apache/airflow/pull/34553): @utkarsharma2
   - [x] [Respect soft_fail parameter in QuickSightSensor (#34555)](https://github.com/apache/airflow/pull/34555): @utkarsharma2
   - [x] [Respect soft_fail parameter in GlacierJobOperationSensor (#34557)](https://github.com/apache/airflow/pull/34557): @utkarsharma2
   - [x] [Respect soft_fail parameter in Glue*Sensor (#34559)](https://github.com/apache/airflow/pull/34559): @utkarsharma2
   - [x] [Respect soft_fail parameter in StepFunctionExecutionSensor (#34560)](https://github.com/apache/airflow/pull/34560): @utkarsharma2
   - [x] [Refactor consolidate import from io in providers (#34378)](https://github.com/apache/airflow/pull/34378): @eumiro
   - [ ] [Upgrade watchtower to 3.0.1 (#25019) (#34747)](https://github.com/apache/airflow/pull/34747): @cBiscuitSurprise
   - [x] [Refactor import from collections (#34406)](https://github.com/apache/airflow/pull/34406): @eumiro
   - [x] [Clarify Amazon Lambda invocation and sensing (#34653)](https://github.com/apache/airflow/pull/34653): @Taragolis
   - [x] [Refactor multiple equals to contains in providers (#34441)](https://github.com/apache/airflow/pull/34441): @eumiro
   - [x] [Rename "bucket" to "gcs_bucket" in GCSToS3Operator (#33031)](https://github.com/apache/airflow/pull/33031): @hankehly
   - [x] [Remove duplicate `asgiref` dependency in Amazon Provider (#34580)](https://github.com/apache/airflow/pull/34580): @Taragolis
   - [x] [Update operator_extra_links property (#34506)](https://github.com/apache/airflow/pull/34506): @asherkhb
   - [ ] [sagemaker.py spell error:  tranform change to  transform (#34445)](https://github.com/apache/airflow/pull/34445): @yanfangli85
   - [x] [Use `airflow.exceptions.AirflowException` in providers (#34511)](https://github.com/apache/airflow/pull/34511): @Taragolis
   - [x] [Use AirflowProviderDeprecationWarning in the deprecated decorator in Amazon provider (#34488)](https://github.com/apache/airflow/pull/34488): @hussein-awala
   - [ ] [Use `AirflowProviderDeprecrationWarning` in EMR Operators (#34453)](https://github.com/apache/airflow/pull/34453): @frankcash
   - [x] [Deprecate get_hook in DataSyncOperator and use hook instead (#34427)](https://github.com/apache/airflow/pull/34427): @hussein-awala
## Provider [apache.beam: 5.3.0rc1](https://pypi.org/project/apache-airflow-providers-apache-beam/5.3.0rc1)
   - [x] [Use `airflow.exceptions.AirflowException` in providers (#34511)](https://github.com/apache/airflow/pull/34511): @Taragolis
## Provider [apache.druid: 3.6.0rc1](https://pypi.org/project/apache-airflow-providers-apache-druid/3.6.0rc1)
   - [x] [Allow passing context to DruidDbApiHook (#34603)](https://github.com/apache/airflow/pull/34603): @saulius
## Provider [apache.flink: 1.2.0rc1](https://pypi.org/project/apache-airflow-providers-apache-flink/1.2.0rc1)
   - [ ] [respect soft_fail argument when exception is raised for flink sensors (#34476)](https://github.com/apache/airflow/pull/34476): @Lee-W
## Provider [apache.hdfs: 4.2.0rc1](https://pypi.org/project/apache-airflow-providers-apache-hdfs/4.2.0rc1)
   - [x] [Use `airflow.exceptions.AirflowException` in providers (#34511)](https://github.com/apache/airflow/pull/34511): @Taragolis
## Provider [apache.hive: 6.2.0rc1](https://pypi.org/project/apache-airflow-providers-apache-hive/6.2.0rc1)
   - [x] [Consolidate hook management in HiveOperator (#34430)](https://github.com/apache/airflow/pull/34430): @hussein-awala
## Provider [apache.kafka: 1.2.0rc1](https://pypi.org/project/apache-airflow-providers-apache-kafka/1.2.0rc1)
   - [x] [Fix typos (double words and it's/its) (#33623)](https://github.com/apache/airflow/pull/33623): @eumiro
   - [x] [Fixes the Kafka provider's max message limit error (#32926) (#33321)](https://github.com/apache/airflow/pull/33321): @aritra24
   - [x] [Use `airflow.exceptions.AirflowException` in providers (#34511)](https://github.com/apache/airflow/pull/34511): @Taragolis
## Provider [apache.livy: 3.6.0rc1](https://pypi.org/project/apache-airflow-providers-apache-livy/3.6.0rc1)
   - [x] [Consolidate hook management in LivyOperator (#34431)](https://github.com/apache/airflow/pull/34431): @hussein-awala
## Provider [arangodb: 2.3.0rc1](https://pypi.org/project/apache-airflow-providers-arangodb/2.3.0rc1)
   - [x] [Use `airflow.exceptions.AirflowException` in providers (#34511)](https://github.com/apache/airflow/pull/34511): @Taragolis
## Provider [celery: 3.4.0rc1](https://pypi.org/project/apache-airflow-providers-celery/3.4.0rc1)
   - [ ] [respect soft_fail argument when exception is raised for celery sensors (#34474)](https://github.com/apache/airflow/pull/34474): @Lee-W
## Provider [cncf.kubernetes: 7.7.0rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/7.7.0rc1)
   - [x] [Fix parsing KubernetesPodOperator multiline logs (#34412)](https://github.com/apache/airflow/pull/34412): @hussein-awala
   - [ ] [Fix KubernetesPodTrigger startup timeout (#34579)](https://github.com/apache/airflow/pull/34579): @dzhigimont
   - [x] [Fix Pod not being removed after istio-sidecar is removed  (#34500)](https://github.com/apache/airflow/pull/34500): @Owen-CH-Leung
   - [ ] [Remove duplicated logs by reusing PodLogsConsumer (#34127)](https://github.com/apache/airflow/pull/34127): @dkim010
   - [ ] [warn level for deprecated set to stacklevel 2 (#34530)](https://github.com/apache/airflow/pull/34530): @daxmahoney
   - [x] [Use `airflow.exceptions.AirflowException` in providers (#34511)](https://github.com/apache/airflow/pull/34511): @Taragolis
## Provider [common.sql: 1.8.0rc1](https://pypi.org/project/apache-airflow-providers-common-sql/1.8.0rc1)
   - [ ] [respect soft_fail argument when exception is raised for sql sensors (#34199)](https://github.com/apache/airflow/pull/34199): @Lee-W
   - [x] [Use `airflow.exceptions.AirflowException` in providers (#34511)](https://github.com/apache/airflow/pull/34511): @Taragolis
## Provider [databricks: 4.6.0rc1](https://pypi.org/project/apache-airflow-providers-databricks/4.6.0rc1)
   - [x] [DatabricksHook ClusterState (#34643)](https://github.com/apache/airflow/pull/34643): @Seokyun-Ha
   - [x] [Respect soft_fail parameter in DatabricksSqlSensor (#34544)](https://github.com/apache/airflow/pull/34544): @utkarsharma2
   - [x] [Respect 'soft_fail' argument when running DatabricksPartitionSensor (#34517)](https://github.com/apache/airflow/pull/34517): @utkarsharma2
   - [x] [Decode response in f-string (#34518)](https://github.com/apache/airflow/pull/34518): @Taragolis
   - [x] [Use aiohttp.BasicAuth instead of HTTPBasicAuth for aiohttp session in databricks hook (#34590)](https://github.com/apache/airflow/pull/34590): @hussein-awala
   - [x] [Update `list_jobs` function in `DatabricksHook` to token-based pagination  (#33472)](https://github.com/apache/airflow/pull/33472): @oleksiidav
## Provider [datadog: 3.4.0rc1](https://pypi.org/project/apache-airflow-providers-datadog/3.4.0rc1)
   - [ ] [respect soft_fail argument when exception is raised for datadog sensors (#34472)](https://github.com/apache/airflow/pull/34472): @Lee-W
## Provider [dbt.cloud: 3.4.0rc1](https://pypi.org/project/apache-airflow-providers-dbt-cloud/3.4.0rc1)
   - [x] [Remove useless print from dbt operator (#34322)](https://github.com/apache/airflow/pull/34322): @hussein-awala
## Provider [docker: 3.8.0rc1](https://pypi.org/project/apache-airflow-providers-docker/3.8.0rc1)
   - [ ] [expose ulimits host_config-option (#34284)](https://github.com/apache/airflow/pull/34284): @kahlstrm
   - [x] [Deprecate get_hook method in DockerOperator (#34432)](https://github.com/apache/airflow/pull/34432): @hussein-awala
## Provider [elasticsearch: 5.1.0rc1](https://pypi.org/project/apache-airflow-providers-elasticsearch/5.1.0rc1)
   - [ ] [Remove unused argument metadata from es_read and make clearly private (#34790)](https://github.com/apache/airflow/pull/34790): @dstandish
   - [ ] [Improve intelligibility of end_of_log determination (#34788)](https://github.com/apache/airflow/pull/34788): @dstandish
   - [x] [Replace try/except/pass by contextlib.suppress in ElasticSearch provider (#34251)](https://github.com/apache/airflow/pull/34251): @hussein-awala
## Provider [github: 2.4.0rc1](https://pypi.org/project/apache-airflow-providers-github/2.4.0rc1)
   - [x] [Use `airflow.exceptions.AirflowException` in providers (#34511)](https://github.com/apache/airflow/pull/34511): @Taragolis
## Provider [google: 10.10.0rc1](https://pypi.org/project/apache-airflow-providers-google/10.10.0rc1)
   - [ ] [improvement: introduce proejct_id in BigQueryIntervalCheckOperator (#34573)](https://github.com/apache/airflow/pull/34573): @Zhenye-Na
   - [ ] [respect soft_fail argument when exception is raised for google sensors (#34501)](https://github.com/apache/airflow/pull/34501): @Lee-W
   - [x] [Fix GCSToGoogleDriveOperator and gdrive system tests (#34545)](https://github.com/apache/airflow/pull/34545): @moiseenkov
   - [ ] [Fix LookerHook serialize missing 1 argument error (#34678)](https://github.com/apache/airflow/pull/34678): @cjonesy
   - [ ] [Fix Dataform system tests (#34329)](https://github.com/apache/airflow/pull/34329): @bkossakowska
   - [x] [Refactor DataFusionInstanceLink usage (#34514)](https://github.com/apache/airflow/pull/34514): @moiseenkov
   - [x] [Use `airflow.models.dag.DAG` in Google Provider examples (#34614)](https://github.com/apache/airflow/pull/34614): @Taragolis
   - [x] [Deprecate Life Sciences Operator and Hook (#34549)](https://github.com/apache/airflow/pull/34549): @fdemiane
   - [x] [Use `airflow.exceptions.AirflowException` in providers (#34511)](https://github.com/apache/airflow/pull/34511): @Taragolis
## Provider [http: 4.6.0rc1](https://pypi.org/project/apache-airflow-providers-http/4.6.0rc1)
   - [ ] [respect soft_fail argument when exception is raised for http sensors (#34391)](https://github.com/apache/airflow/pull/34391): @Lee-W
## Provider [jenkins: 3.4.0rc1](https://pypi.org/project/apache-airflow-providers-jenkins/3.4.0rc1)
   - [ ] [respect soft_fail argument when exception is raised for jenkins sensors (#34475)](https://github.com/apache/airflow/pull/34475): @Lee-W
   - [x] [Consolidate hook management in JenkinsJobTriggerOperator (#34433)](https://github.com/apache/airflow/pull/34433): @hussein-awala
## Provider [microsoft.azure: 8.0.0rc1](https://pypi.org/project/apache-airflow-providers-microsoft-azure/8.0.0rc1)
   - [ ] [Bump azure-mgmt-containerinstance (#34738)](https://github.com/apache/airflow/pull/34738): @pankajastro
   - [x] [Upgrade azure-mgmt-datafactory in microsift azure provider (#34040)](https://github.com/apache/airflow/pull/34040): @pankajastro
   - [x] [Add subnet_ids param in AzureContainerInstancesOperator (#34850)](https://github.com/apache/airflow/pull/34850): @pankajastro
   - [x] [allow providing credentials through keyword argument in AzureKeyVaultBackend (#34706)](https://github.com/apache/airflow/pull/34706): @Lee-W
   - [ ] [Name params while invoking ClientSecretCredential (#34732)](https://github.com/apache/airflow/pull/34732): @irajankumar
   - [x] [respect soft_fail argument when exception is raised for microsoft-azure sensors (#34494)](https://github.com/apache/airflow/pull/34494): @Lee-W
   - [x] [Error handling for when Azure container log cannot be read in properly. (#34627)](https://github.com/apache/airflow/pull/34627): @krisfur
   - [x] [Fix hardcoded container name in remote logging option for Azure Blob Storage (#32779)](https://github.com/apache/airflow/pull/32779): @Adaverse
   - [x] [Consolidate hook management in AzureBatchOperator (#34437)](https://github.com/apache/airflow/pull/34437): @hussein-awala
   - [x] [Consolidate hook management in AzureDataExplorerQueryOperator (#34436)](https://github.com/apache/airflow/pull/34436): @hussein-awala
## Provider [openlineage: 1.1.1rc1](https://pypi.org/project/apache-airflow-providers-openlineage/1.1.1rc1)
   - [x] [openlineage: adjust log levels (#34801)](https://github.com/apache/airflow/pull/34801): @JDarDagran
## Provider [papermill: 3.4.0rc1](https://pypi.org/project/apache-airflow-providers-papermill/3.4.0rc1)
   - [x] [Remove Airflow 2.3 compat from `PapermillOperator` (#34675)](https://github.com/apache/airflow/pull/34675): @Taragolis
## Provider [postgres: 5.7.0rc1](https://pypi.org/project/apache-airflow-providers-postgres/5.7.0rc1)
   - [x] [Add `get_ui_field_behaviour()` method to PostgresHook (#34811)](https://github.com/apache/airflow/pull/34811): @pubudu91
## Provider [presto: 5.2.0rc1](https://pypi.org/project/apache-airflow-providers-presto/5.2.0rc1)
   - [x] [Use `airflow.exceptions.AirflowException` in providers (#34511)](https://github.com/apache/airflow/pull/34511): @Taragolis
## Provider [samba: 4.3.0rc1](https://pypi.org/project/apache-airflow-providers-samba/4.3.0rc1)
   - [x] [Feature: Add Google Cloud Storage to Samba operator (#34369)](https://github.com/apache/airflow/pull/34369): @ealebed
## Provider [slack: 8.2.0rc1](https://pypi.org/project/apache-airflow-providers-slack/8.2.0rc1)
   - [x] [Slack: use default_conn_name by default (#34548)](https://github.com/apache/airflow/pull/34548): @Khrol
## Provider [snowflake: 5.1.0rc1](https://pypi.org/project/apache-airflow-providers-snowflake/5.1.0rc1)
   - [x] [Decode response in f-string (#34518)](https://github.com/apache/airflow/pull/34518): @Taragolis
   - [x] [Use `airflow.exceptions.AirflowException` in providers (#34511)](https://github.com/apache/airflow/pull/34511): @Taragolis
## Provider [trino: 5.4.0rc1](https://pypi.org/project/apache-airflow-providers-trino/5.4.0rc1)
   - [x] [Use `airflow.exceptions.AirflowException` in providers (#34511)](https://github.com/apache/airflow/pull/34511): @Taragolis

All users involved in the PRs:
@Zhenye-Na @pubudu91 @pankajastro @krisfur @Taragolis @kahlstrm @Khrol @moiseenkov @utkarsharma2 @saulius @irajankumar @ealebed @eumiro @hussein-awala @cjonesy @dstandish @daxmahoney @Seokyun-Ha 
@oleksiidav @aritra24 @cBiscuitSurprise @dkim010 @frankcash @hankehly @asherkhb @bkossakowska @Lee-W @Owen-CH-Leung @fdemiane @vandonr-amz @JDarDagran @dzhigimont @Adaverse @yanfangli85

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by Lee-W** [comment]
Tested with our examples DAGs with only one expected fail due to azure provider breaking change.

**Comment by ealebed** [comment]
**apache-airflow-providers-samba==4.3.0rc1** has been tested with our examples DAGs (on staging Airflow and test Google Cloud Composer environments)

**Comment by pubudu91** [comment]
Tested the postgres provider 5.7.0rc1 locally. The fix done is available in it.

**Comment by Owen-CH-Leung** [comment]
checked `apache-airflow-providers-cncf-kubernetes==7.7.0rc1`. The fix is working as expected.

**Comment by utkarsharma2** [comment]
Checked my changes, and they seem to be working fine.

Thanks,
Utkarsh Sharma

**Comment by hankehly** [comment]
#33031 is working on amazon-8.8.0rc1 😄 
Here are the commands I used to setup my environment / run my checks if it helps anyone.
```shell
breeze
pip install apache-airflow-providers-amazon==8.8.0rc1
pip list | grep amazon  # check version

# Run unit tests
pytest tests/providers/amazon/aws/transfers/test_gcs_to_s3.py

# Run system tests
export AWS_ACCESS_KEY_ID=***
export AWS_SECRET_ACCESS_KEY=***
export AWS_DEFAULT_REGION=***
export GOOGLE_APPLICATION_CREDENTIALS=/path/to/credentials.json
export GCP_PROJECT_ID=***
pytest --system amazon tests/system/providers/amazon/aws/example_gcs_to_s3.py
```

**Comment by Adaverse** [comment]
Tested #32779, it works as expected.

**Comment by aritra24** [comment]
Tested out #32926, works as expected

**Comment by saulius** [comment]
Tested https://github.com/apache/airflow/pull/34603 in dev environment, works as expected.

**Comment by JDarDagran** [comment]
https://github.com/apache/airflow/pull/34801 tested, works as expected

**Comment by Taragolis** [comment]
- https://github.com/apache/airflow/pull/34511: I've checked that packages in this release doesn't use lazy import AirflowException anymore
- https://github.com/apache/airflow/pull/34675: Check that operator doesn't have any serialization problem, as well as parameters templates after the changes
- https://github.com/apache/airflow/pull/34692: works as expected
- https://github.com/apache/airflow/pull/34593: works as expected, test on couple services include STS
- https://github.com/apache/airflow/pull/34784: No side effect found, this classes don't use right now
- https://github.com/apache/airflow/pull/34884: Couldn't found side effect in existed triggers, additional parameters doesn't provided from community Operators yet
- https://github.com/apache/airflow/pull/34580: Amazon Provider package's metadata contain `asgiref` as dependency only once

---

- https://github.com/apache/airflow/pull/34614: System test/examples only
- https://github.com/apache/airflow/pull/34653: Doc only

---

- https://github.com/apache/airflow/pull/34518: Hard to check because I do not have access to any Databriks or Snowflake environment, should not be a problem since this code executed only on Hooks/Operator's fatal error

**Comment by oleksiidav** [comment]
I trust the test coverage of #33472 since the changes are pretty trivial. Let's ship it 💪

**Comment by asherkhb** [comment]
Confirming Amazon 8.8.0rc1 resolves the issues related to my changes 👍

**Comment by Khrol** [comment]
> [slack: 8.2.0rc1](https://pypi.org/project/apache-airflow-providers-slack/8.2.0rc1)

Tested locally. LGTM.

**Comment by Seokyun-Ha** [comment]
I Checked https://github.com/apache/airflow/pull/34643 works as expected!

Sorry for late response 🙏

**Comment by krisfur** [comment]
All good with #34627 (apologies for the very late response, holidays)
