### ISSUE TITLE
Status of testing Providers that were prepared on October 18, 2023

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#35030]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 8.9.0rc1](https://pypi.org/project/apache-airflow-providers-amazon/8.9.0rc1)
   - [x] [Glue DataBrew operator (#34807)](https://github.com/apache/airflow/pull/34807): @ellisms
   - [x] [Add `check_interval` and `max_attempts` as parameter of `DynamoDBToS3Operator` (#34972)](https://github.com/apache/airflow/pull/34972): @vincbeck
   - [x] [Sets EcsRunTaskOperator default waiter duration to 70 days (#34928)](https://github.com/apache/airflow/pull/34928): @123MwanjeMike
## Provider [celery: 3.4.1rc1](https://pypi.org/project/apache-airflow-providers-celery/3.4.1rc1)
   - [ ] [Fix _SECRET and _CMD broker configuration (#34782)](https://github.com/apache/airflow/pull/34782): @JonnyWaffles
   - [x] [Remove sensitive information from Celery executor warning (#34954)](https://github.com/apache/airflow/pull/34954): @hussein-awala
## Provider [google: 10.10.1rc1](https://pypi.org/project/apache-airflow-providers-google/10.10.1rc1)
   - [ ] [Add links between documentation related to Google Cloud Storage (#34994)](https://github.com/apache/airflow/pull/34994): @PeWu
   - [ ] [Migrate legacy version of AI Platform Prediction to VertexAI (#34922)](https://github.com/apache/airflow/pull/34922): @VladaZakharova
   - [ ] [Cancel workflow in on_kill in DataprocInstantiate{Inline}WorkflowTemplateOperator (#34957)](https://github.com/apache/airflow/pull/34957): @michalsosn
## Provider [opensearch: 1.0.0rc1](https://pypi.org/project/apache-airflow-providers-opensearch/1.0.0rc1)
   - [x] [`Add Open Search Provider` (#34705)](https://github.com/apache/airflow/pull/34705): @cjames23
## Provider [postgres: 5.7.1rc1](https://pypi.org/project/apache-airflow-providers-postgres/5.7.1rc1)
   - [x] [`PostgresOperator` should not overwrite `SQLExecuteQueryOperator.template_fields` (#34969)](https://github.com/apache/airflow/pull/34969): @Taragolis

All users involved in the PRs:
@ellisms @Taragolis @VladaZakharova @123MwanjeMike @hussein-awala @vincbeck @PeWu @michalsosn @JonnyWaffles @cjames23

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by vincbeck** [comment]
AWS system tests are using #34972 and it is working fine

**Comment by Taragolis** [comment]
https://github.com/apache/airflow/pull/34969 - check, works fine

**Comment by ellisms** [comment]
#34807 works fine

**Comment by hussein-awala** [comment]
#34954 works as expected!

**Comment by cjames23** [comment]
#34705 works as expected

**Comment by Lee-W** [comment]
Tested apache-airflow-providers-amazon==8.9.0rc1 and apache-airflow-providers-google==10.10.1rc1. Both of them works as expected.

**Comment by 123MwanjeMike** [comment]
#34972 works fine

**Comment by eladkal** [comment]
Thank you everyone.
Providers are released
I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
