### ISSUE TITLE
Support Native Kubernetes sidecars in our Chart

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#35154]
### Body

The 1.28 version of K8S introduce "naative sidecars" https://kubernetes.io/blog/2023/08/25/native-sidecar-containers/ which  - with implementation of [KEP-753](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/753-sidecar-containers/README.md) finally solve the long standing problem of sidecar lifetime management, where exiting the main container would not stop the POD where sidecar container is still running.  We could likely also use some more features of sidecars.

Implementing some of our sidecars (for example kerberos, but also other sidecars that we currently use) would sovle the problems of side-car containers not being killed when main container shuts down, allowing to have better self-maintained k8s deployment.

It would be great to review our helm chart and apply the new sidecar pattern (for k8s >= 1.28). 

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by amoghrajesh** [comment]
@potiuk @eladkal I will self assign this to myself. I plan to start working on this soon as part of a follow up to https://github.com/apache/airflow/pull/35146

**Comment by potiuk** [comment]
Cool!

**Comment by Miretpl** [comment]
Hi @amoghrajesh, are you working on it? If not, I could take it

**Comment by kaxil** [comment]
Feel free to take it @Miretpl

**Comment by Miretpl** [comment]
Init containers in the 1.19.0 Helm Chart version:

- [x] `wait-for-airflow-migrations` - which do not exist in containers, so we don't change it
- [ ] `git-sync-container` - will be changed
   - dag-processor-deployment.yaml
   - scheduler-deployment.yaml
   - triggerer-deployment.yaml
   - webserver-deployment.yaml
   - worker-deployment.yaml
   - pod-template-file - uses only init
- [x] `volume-permissions` - which do not exist in containers, so we don't change them
- [ ] `kerberos-init` (`worker-kerberos` in containers) - will be changed
   - worker-deployment.yaml
   - pod-template-file

Both `git-sync-container` and `kerberos`-related containers lack `startupProbe`, which is useful with native sidecars, so I will take care of this first.

**Comment by potiuk** [comment]
@Miretpl We are unassigning you from this issue as part of our updated [assignment policy](https://github.com/apache/airflow/blob/main/contributing-docs/04_how_to_contribute.rst#contribute-code-changes).

This is not meant to discourage your contribution — quite the opposite! You are still very welcome to work on this issue and submit a PR for it. Simply comment that you are working on it and open a PR when ready.

We found that formal assignments were not working well, as they often prevented others from contributing when the assignee was not actively working on the issue.

**Comment by aaron-y-chen** [comment]
Hi @Miretpl, do you mind if I work on the remaining parts?

**Comment by Miretpl** [comment]
Hi @aaron-y-chen feel free to do that. Just some notes:
1. `git-sync` will be removed in Helm Chart 2.0, so working on it is rather unnecessary
2. If I remember correctly, I was thinking about how to make Kerberos one in a nice way. By "nice way" I mean you need to have a `startupProbe` set up for it, and I wanted to do something a bit different from just checking the keytab file (but maybe that is good enough at the beginning 🤔). So first it would be good to have a probe for it, and after that make a change for usage of native sidecars
