### ISSUE TITLE
Status of testing Providers that were prepared on October 28, 2023

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#35240]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 8.10.0rc1](https://pypi.org/project/apache-airflow-providers-amazon/8.10.0rc1)
   - [ ] [AWS ECS Executor (#34381)](https://github.com/apache/airflow/pull/34381): @o-nikolas
   - [x] [AIP-58: Add Airflow ObjectStore (AFS) (#34729)](https://github.com/apache/airflow/pull/34729): @bolkedebruin
   - [x] [Add http to s3 operator (#35176)](https://github.com/apache/airflow/pull/35176): @simonprydden
   - [x] [Enable encryption in S3 download_files() hook. (#35037)](https://github.com/apache/airflow/pull/35037): @ferruzzi
   - [x] [Use base aws classes in Amazon AppFlow Operators (#35082)](https://github.com/apache/airflow/pull/35082): @Taragolis
   - [x] [Use base aws classes in Amazon Athena Operators/Sensors/Triggers (#35133)](https://github.com/apache/airflow/pull/35133): @Taragolis
   - [x] [Use base classes for AWS Lambda Operators/Sensors (#34890)](https://github.com/apache/airflow/pull/34890): @Taragolis
   - [x] [Use base aws classes in Amazon S3 Glacier Operators/Sensors (#35108)](https://github.com/apache/airflow/pull/35108): @Taragolis
   - [x] [Expose catalog parameter in `AthenaOpeartor` (#35103)](https://github.com/apache/airflow/pull/35103): @eladkal
## Provider [apache.spark: 4.3.0rc1](https://pypi.org/project/apache-airflow-providers-apache-spark/4.3.0rc1)
   - [ ] [Add use_krb5ccache option to SparkSubmitHook (#34386)](https://github.com/apache/airflow/pull/34386): @zeotuan
## Provider [cncf.kubernetes: 7.8.0rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/7.8.0rc1)
   - [ ] [Added to the rendering of KubernetesOperator V1VolumeMount, sub_path (#35129)](https://github.com/apache/airflow/pull/35129): @mescanne
   - [x] [feat: add hostAliases to pod spec in KubernetesPodOperator (#35063)](https://github.com/apache/airflow/pull/35063): @imurchie
   - [ ] [Replace blocking IO with async IO in AsyncKubernetesHook (#35162)](https://github.com/apache/airflow/pull/35162): @functicons
   - [ ] [Consolidate the warning stacklevel in KubernetesPodTrigger (#35079)](https://github.com/apache/airflow/pull/35079): @anukrati1507
## Provider [common.io: 1.0.0rc1](https://pypi.org/project/apache-airflow-providers-common-io/1.0.0rc1)
   - [x] [AIP-58: Add Airflow ObjectStore (AFS) (#34729)](https://github.com/apache/airflow/pull/34729): @bolkedebruin
## Provider [databricks: 4.7.0rc1](https://pypi.org/project/apache-airflow-providers-databricks/4.7.0rc1)
   - [ ] [Add operator to create jobs in Databricks (#35156)](https://github.com/apache/airflow/pull/35156): @tatiana
## Provider [google: 10.11.0rc1](https://pypi.org/project/apache-airflow-providers-google/10.11.0rc1)
   - [x] [AIP-58: Add Airflow ObjectStore (AFS) (#34729)](https://github.com/apache/airflow/pull/34729): @bolkedebruin
   - [x] [Make Dataprep system test self-sufficient (#34880)](https://github.com/apache/airflow/pull/34880): @moiseenkov
   - [x] [Added `overrides` parameter to CloudRunExecuteJobOperator (#34874)](https://github.com/apache/airflow/pull/34874): @ChloeSheasby
## Provider [microsoft.azure: 8.1.0rc1](https://pypi.org/project/apache-airflow-providers-microsoft-azure/8.1.0rc1)
   - [ ] [AIP-58: Add Airflow ObjectStore (AFS) (#34729)](https://github.com/apache/airflow/pull/34729): @bolkedebruin
## Provider [mongo: 3.4.0rc1](https://pypi.org/project/apache-airflow-providers-mongo/3.4.0rc1)
   - [ ] [Add distinct function to MongoHook in apache-airflow-providers-mongo (#34466)](https://github.com/apache/airflow/pull/34466): @octaviolage
## Provider [openlineage: 1.2.0rc1](https://pypi.org/project/apache-airflow-providers-openlineage/1.2.0rc1)
   - [ ] [openlineage, common.sql: send column lineage from SQL operators. (#34843)](https://github.com/apache/airflow/pull/34843): @JDarDagran
## Provider [presto: 5.2.1rc1](https://pypi.org/project/apache-airflow-providers-presto/5.2.1rc1)
   - [x] [Bump min version of presto client to bring better dbapi compatibility (#35132)](https://github.com/apache/airflow/pull/35132): @potiuk
## Provider [slack: 8.3.0rc1](https://pypi.org/project/apache-airflow-providers-slack/8.3.0rc1)
   - [x] [Pass additional arguments from Slack's Operators/Notifiers to Hooks (#35039)](https://github.com/apache/airflow/pull/35039): @Taragolis
## Provider [smtp: 1.4.1rc1](https://pypi.org/project/apache-airflow-providers-smtp/1.4.1rc1)
   - [ ] [Make `cc` and `bcc` templated fields in EmailOperator (#35235)](https://github.com/apache/airflow/pull/35235): @Joffreybvn
## Provider [ssh: 3.8.1rc1](https://pypi.org/project/apache-airflow-providers-ssh/3.8.1rc1)
   - [ ] [Consolidate stacklevel in ssh operator warning (#35151)](https://github.com/apache/airflow/pull/35151): @shubhamraj-git

All users involved in the PRs:
@bolkedebruin @mescanne @shubhamraj-git @octaviolage @potiuk @zeotuan @moiseenkov @o-nikolas @ChloeSheasby @ferruzzi @Joffreybvn @anukrati1507 @eladkal @JDarDagran @Taragolis @tatiana @imurchie 
@functicons @simonprydden

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by simonprydden** [comment]
#35137 HttpToS3Operator tested and working as expected

**Comment by potiuk** [comment]
Min version for presto is nicely bumped :) #35132

**Comment by bolkedebruin** [comment]
I have tested, S3 particularly, for #34729. However, this only becomes relevant for Airflow 2.8 - integrations until that time won't be active / work.

**Comment by eladkal** [comment]
> I have tested, S3 particularly, for #34729. However, this only becomes relevant for Airflow 2.8 - integrations until that time won't be active / work.

Yes this is expected

**Comment by Taragolis** [comment]
- https://github.com/apache/airflow/pull/35039 : test different combination and it looks good
- https://github.com/apache/airflow/pull/35082, https://github.com/apache/airflow/pull/35133, https://github.com/apache/airflow/pull/34890, https://github.com/apache/airflow/pull/35108 : I've primary test Lambda and Athena Operators/Sensors, hardly possible to test all combination but I wan't to believe that unit tests cover other cases and Appflow and Glacier oeprators

**Comment by Taragolis** [comment]
In addition test https://github.com/apache/airflow/pull/35037, looks fine

**Comment by moiseenkov** [comment]
#34880 works as expected

**Comment by bolkedebruin** [comment]
I'm adding a small fix to `get_fs` for s3 to allow anonymous access. You might want to include this.

**Comment by imurchie** [comment]
Kubernetes `host_aliases` (https://github.com/apache/airflow/pull/35063) works as expected.

**Comment by eladkal** [comment]
> I'm adding a small fix to `get_fs` for s3 to allow anonymous access. You might want to include this.

This doesn't call for RC2 because the feature is useable only with Airflow>=2.8.0 thus there is no regression in Amazon provider

**Comment by ChloeSheasby** [comment]
I believe that #34874 is working as expected, but this is my first time as a contributor, so if someone else could also test it, I would really appreciate that!

**Comment by eladkal** [comment]
Thank you everyone.
Providers are released
I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
