### ISSUE TITLE
Status of testing Providers that were prepared on November 12, 2023

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#35592]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [discord: 3.4.1rc2](https://pypi.org/project/apache-airflow-providers-discord/3.4.1rc2)
   - [x] [Add pagination to `HttpOperator` and make it more modular (#34669)](https://github.com/apache/airflow/pull/34669): @Joffreybvn
## Provider [http: 4.7.0rc2](https://pypi.org/project/apache-airflow-providers-http/4.7.0rc2)
   - [x] [Add pagination to `HttpOperator` and make it more modular (#34669)](https://github.com/apache/airflow/pull/34669): @Joffreybvn
   - [ ] [json data for async PUTs fixed (#35405)](https://github.com/apache/airflow/pull/35405): @andrew9691
   - [x] [Fix: Paginate on lastest Response (#35560)](https://github.com/apache/airflow/pull/35560): @Joffreybvn

All users involved in the PRs:
@andrew9691 @Joffreybvn

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by Joffreybvn** [comment]
Discord and Http provider are working like a charm ! (tested #35560 and #34669)
Thanks !
