### ISSUE TITLE
Status of testing Providers that were prepared on December 08, 2023

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#36117]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 8.13.0rc1](https://pypi.org/project/apache-airflow-providers-amazon/8.13.0rc1)
   - [x] [Support IAM authentication for Redshift serverless (#35897)](https://github.com/apache/airflow/pull/35897): @hussein-awala
   - [ ] [Implement `is_authorized_variable` in AWS auth manager (#35804)](https://github.com/apache/airflow/pull/35804): @vincbeck
   - [ ] [Enhance DynamoDBValueSensor to support any attribute value in list (#35831)](https://github.com/apache/airflow/pull/35831): @flolas
   - [ ] [Fix handling of single quotes in `RedshiftToS3Operator` (#35986)](https://github.com/apache/airflow/pull/35986): @vincbeck
   - [x] [Fix a bug in get_iam_token for Redshift Serverless (#36001)](https://github.com/apache/airflow/pull/36001): @hussein-awala
   - [ ] [Fix reraise outside of try block in `AthenaHook.get_output_location` (#36008)](https://github.com/apache/airflow/pull/36008): @Taragolis
   - [x] [Fix a bug with accessing hooks in EKS trigger (#35989)](https://github.com/apache/airflow/pull/35989): @hussein-awala
   - [x] [Fix a bug in method name used in GlacierToGCSOperator (#35978)](https://github.com/apache/airflow/pull/35978): @hussein-awala
   - [x] [Fix EC2Hook get_instance for client_type api (#35960)](https://github.com/apache/airflow/pull/35960): @hussein-awala
   - [x] [Avoid creating the hook in the EmrServerlessCancelJobsTrigger init (#35992)](https://github.com/apache/airflow/pull/35992): @hussein-awala
   - [x] [Stop getting message from event after migrating EmrContainerTrigger to AwsBaseWaiterTrigger (#35892)](https://github.com/apache/airflow/pull/35892): @hussein-awala
   - [ ] [Fix for EksCreateClusterOperator deferrable mode (#36079)](https://github.com/apache/airflow/pull/36079): @syedahsn
   - [ ] [Update `boto3` and `botocore` versions notes (#36073)](https://github.com/apache/airflow/pull/36073): @Taragolis
   - [x] [Improve typing hints for `only_client_type` decorator (#35997)](https://github.com/apache/airflow/pull/35997): @hussein-awala
   - [x] [Refactor some methods in EmrContainerHook (#35999)](https://github.com/apache/airflow/pull/35999): @hussein-awala
   - [x] [Refactor `get_output_location` method in AthenaHook (#35996)](https://github.com/apache/airflow/pull/35996): @hussein-awala
   - [x] [Move RDS hook to a cached property in RDS trigger (#35990)](https://github.com/apache/airflow/pull/35990): @hussein-awala
   - [x] [Replace default empty dict value by None in AzureBlobStorageToS3Operator (#35977)](https://github.com/apache/airflow/pull/35977): @hussein-awala
   - [x] [Refacto CloudwatchTaskHandler set_context method (#35975)](https://github.com/apache/airflow/pull/35975): @hussein-awala
   - [x] [Use S3 hook instead of AwsGenericHook in AWS S3 FS (#35973)](https://github.com/apache/airflow/pull/35973): @hussein-awala
   - [ ] [AWS auth manager: implement all `is_authorized_*` methods (but `is_authorized_dag`) (#35928)](https://github.com/apache/airflow/pull/35928): @vincbeck
   - [x] [Remove setting a non-existing object param and use local var instead in S3Hook (#35950)](https://github.com/apache/airflow/pull/35950): @hussein-awala
## Provider [cncf.kubernetes: 7.11.0rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/7.11.0rc1)
   - [ ] [fix: KPO typing env_vars (#36048)](https://github.com/apache/airflow/pull/36048): @raphaelauv
   - [x] [Stop converting state to TaskInstanceState when it's None (#35891)](https://github.com/apache/airflow/pull/35891): @hussein-awala
   - [ ] [Feature pass dictionary configuration in application_file in SparkKubernetesOperator (#35848)](https://github.com/apache/airflow/pull/35848): @romsharon98
## Provider [docker: 3.9.0rc1](https://pypi.org/project/apache-airflow-providers-docker/3.9.0rc1)
   - [x] [Fix `enable_logging=True` not working in `DockerSwarmOperator` (#35677)](https://github.com/apache/airflow/pull/35677): @stavdav143
## Provider [elasticsearch: 5.3.0rc1](https://pypi.org/project/apache-airflow-providers-elasticsearch/5.3.0rc1)
   - [x] [Cleanup code for elasticsearch<8 (#35707)](https://github.com/apache/airflow/pull/35707): @eladkal
## Provider [google: 10.13.0rc1](https://pypi.org/project/apache-airflow-providers-google/10.13.0rc1)
   - [x] [GCP Secrets Backend Impersonation (#36072)](https://github.com/apache/airflow/pull/36072): @nathadfield
   - [ ] [Add OpenLineage support to GCS operators (#35838)](https://github.com/apache/airflow/pull/35838): @kacpermuda
   - [ ] [Add support for service account impersonation with computeEngineSSHHook (google provider) and IAP tunnel (#35136)](https://github.com/apache/airflow/pull/35136): @ginolegigot
   - [ ] [Fix DataprocSubmitJobOperator to retrieve failed job error message (#36053)](https://github.com/apache/airflow/pull/36053): @VladaZakharova
   - [ ] [Fix CloudRunExecuteJobOperator in deferrable mode (#36012)](https://github.com/apache/airflow/pull/36012): @VladaZakharova
   - [ ] [Fix gcs listing - ensure blobs are loaded (#34919)](https://github.com/apache/airflow/pull/34919): @atrbgithub
   - [x] [allow multiple elements in impersonation chain (#35694)](https://github.com/apache/airflow/pull/35694): @melugoyal
   - [ ] [Deprecate `CloudComposerEnvironmentSensor` in favor of `CloudComposerCreateEnvironmentOperator` with defer mode (#35775)](https://github.com/apache/airflow/pull/35775): @VladaZakharova
## Provider [http: 4.8.0rc1](https://pypi.org/project/apache-airflow-providers-http/4.8.0rc1)
   - [ ] [Fix HttpOperator pagination with `str` data (#35782)](https://github.com/apache/airflow/pull/35782): @Joffreybvn
## Provider [jdbc: 4.2.0rc1](https://pypi.org/project/apache-airflow-providers-jdbc/4.2.0rc1)
   - [ ] [Add documentation about "providers.jdbc" in provider.yaml (#35580)](https://github.com/apache/airflow/pull/35580): @pankajkoti
## Provider [microsoft.azure: 8.4.0rc1](https://pypi.org/project/apache-airflow-providers-microsoft-azure/8.4.0rc1)
   - [ ] [Fix reraise outside of try block in `AzureSynapsePipelineRunLink.get_fields_from_url` (#36009)](https://github.com/apache/airflow/pull/36009): @Taragolis
   - [ ] [Do not catch too broad exception in `WasbHook.delete_container` (#36034)](https://github.com/apache/airflow/pull/36034): @Taragolis
## Provider [microsoft.mssql: 3.6.0rc1](https://pypi.org/project/apache-airflow-providers-microsoft-mssql/3.6.0rc1)
   - [ ] [Remove workaround for pymssql failing compilation with new Cython (#35924)](https://github.com/apache/airflow/pull/35924): @potiuk
## Provider [openai: 1.1.0rc1](https://pypi.org/project/apache-airflow-providers-openai/1.1.0rc1)
   - [x] [Bump up openai version to >=1.0 & use get_conn (#36014)](https://github.com/apache/airflow/pull/36014): @pankajkoti
## Provider [openlineage: 1.3.0rc1](https://pypi.org/project/apache-airflow-providers-openlineage/1.3.0rc1)
   - [ ] [OpenLineage: Add parent_run_id for COMPLETE and FAIL events (#36067)](https://github.com/apache/airflow/pull/36067): @kacpermuda
   - [ ] [openlineage: add basic metrics to stats collector. (#35368)](https://github.com/apache/airflow/pull/35368): @JDarDagran
   - [ ] [Repair different run_id for OpenLineage START and FAIL events. (#36051)](https://github.com/apache/airflow/pull/36051): @kacpermuda
   - [ ] [openlineage: add ClassVar to Airflow facets. (#36084)](https://github.com/apache/airflow/pull/36084): @JDarDagran
## Provider [trino: 5.5.0rc1](https://pypi.org/project/apache-airflow-providers-trino/5.5.0rc1)
   - [ ] [Feature/trino provider timezone (#35963)](https://github.com/apache/airflow/pull/35963): @romsharon98
## Provider [weaviate: 1.1.0rc1](https://pypi.org/project/apache-airflow-providers-weaviate/1.1.0rc1)
   - [ ] [Add object methods in weaviate hook (#35934)](https://github.com/apache/airflow/pull/35934): @ephraimbuddy
   - [ ] [Add a cache for weaviate client (#35983)](https://github.com/apache/airflow/pull/35983): @ephraimbuddy
   - [ ] [Add more ways to connect to weaviate (#35864)](https://github.com/apache/airflow/pull/35864): @ephraimbuddy

All users involved in the PRs:
@Taragolis @vincbeck @romsharon98 @syedahsn @kacpermuda @raphaelauv @melugoyal @ginolegigot @atrbgithub @flolas @JDarDagran @nathadfield @potiuk @ephraimbuddy @Joffreybvn @pankajkoti @hussein-awala
@VladaZakharova @stavdav143 @eladkal

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by melugoyal** [comment]
#35694 working as expected

**Comment by eladkal** [comment]
Docker provider will be excluded from rc1

**Comment by hussein-awala** [comment]
I tested my change on the Kubernetes executor, and most of the changes in the Amazon provider, all work as expected.

**Comment by pankajastro** [comment]
As @atrbgithub has mentioned above https://github.com/apache/airflow/pull/34919 is breaking an existing DAG. so we might need to exclude Google provider

**Comment by eladkal** [comment]
> so we might need to exclude Google provider

Yes. Google provider will also have RC2

**Comment by potiuk** [comment]
Tested mssql - all looks good.

One more thing I noticed - the removed `daskexecutor` has not been prepared.  We have this in the release process, so it's easy to miss:

```
NOTE! When you want to release a provider marked for removal (needed in order to prepare last release of the provider), package for the provider will not be prepared when you prepare documentation for all providers - you have to specifically use the provider name in a separate command. For example to prepare documentation for removed.provider provider marked for removal you need to run separately this command:

breeze release-management prepare-provider-packages --package-format both removed.provider
```

But maybye we will change it in the future - we have more removed providers coming. So possibly we shoudl automatically add removed providers to the list of providers prepared (both for documentation and package building - so that we do not have to remember to prepare them. That was probably bad idea to not add them in the first place.

@eladkal -> I guess we should include rc2 (even if there was no rc1) for `daskexecutor`.

**Comment by potiuk** [comment]
One small update - as @pankajastro noticed in https://github.com/apache/airflow/pull/32319#discussion_r1421437350 - there is a case where we are not handling properly the fact that `handler` can return either list of rows or rows - in both ODBC and DAtabricks oviders, so IMHO they should also be moved to RC2 (cc: @Joffreybvn )

**Comment by potiuk** [comment]
Fix to the process to automatically generate removed providers here: https://github.com/apache/airflow/pull/36160

**Comment by Joffreybvn** [comment]
Fix for https://github.com/apache/airflow/pull/32319#discussion_r1421437350 is here -> #36161

**Comment by nathadfield** [comment]
#36072 has been tested and working as expected.

**Comment by eladkal** [comment]
Thank you everyone.
Providers are released (excluding Google, ODBC, Databricks, Docker which we will have RC2 soon)
I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
