### ISSUE TITLE
Status of testing Providers that were prepared on December 12, 2023

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#36194]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [databricks: 5.1.0rc2](https://pypi.org/project/apache-airflow-providers-databricks/5.1.0rc2)
   - [ ] [Fix: Implement support for `fetchone()` in the ODBCHook and the Databricks SQL Hook (#36161)](https://github.com/apache/airflow/pull/36161): @Joffreybvn
## Provider [docker: 3.9.0rc2](https://pypi.org/project/apache-airflow-providers-docker/3.9.0rc2)
   - [x] [Fix `enable_logging=True` not working in `DockerSwarmOperator` (#35677)](https://github.com/apache/airflow/pull/35677): @stavdav143
   - [x] [Fix broken log streaming from #35677 (#36127)](https://github.com/apache/airflow/pull/36127): @stavdav143
   - [x] [Follow BaseHook connection fields method signature in providers hooks (#36086)](https://github.com/apache/airflow/pull/36086): @Taragolis
## Provider [google: 10.13.0rc2](https://pypi.org/project/apache-airflow-providers-google/10.13.0rc2)
   - [x] [GCP Secrets Backend Impersonation (#36072)](https://github.com/apache/airflow/pull/36072): @nathadfield
   - [ ] [Add OpenLineage support to GCS operators (#35838)](https://github.com/apache/airflow/pull/35838): @kacpermuda
   - [ ] [Add support for service account impersonation with computeEngineSSHHook (google provider) and IAP tunnel (#35136)](https://github.com/apache/airflow/pull/35136): @ginolegigot
   - [ ] [Added Datascan Profiling (#35696)](https://github.com/apache/airflow/pull/35696): @shourya116
   - [x] [Add overrides to template fields of Google Cloud Run Jobs Execute Operator (#36133)](https://github.com/apache/airflow/pull/36133): @guillaumeblaquiere
   - [ ] [Fix DataprocSubmitJobOperator to retrieve failed job error message (#36053)](https://github.com/apache/airflow/pull/36053): @VladaZakharova
   - [ ] [Fix CloudRunExecuteJobOperator in deferrable mode (#36012)](https://github.com/apache/airflow/pull/36012): @VladaZakharova
   - [ ] [Fix gcs listing - ensure blobs are loaded (#34919)](https://github.com/apache/airflow/pull/34919): @atrbgithub
   - [x] [allow multiple elements in impersonation chain (#35694)](https://github.com/apache/airflow/pull/35694): @melugoyal
   - [ ] [Change retry type for Google Clients to async ones where needed (#36141)](https://github.com/apache/airflow/pull/36141): @potiuk
   - [ ] [Deprecate `CloudComposerEnvironmentSensor` in favor of `CloudComposerCreateEnvironmentOperator` with defer mode (#35775)](https://github.com/apache/airflow/pull/35775): @VladaZakharova
   - [ ] [Follow BaseHook connection fields method signature in providers hooks (#36086)](https://github.com/apache/airflow/pull/36086): @Taragolis
   - [ ] [Allow storage options to be passed (#35820)](https://github.com/apache/airflow/pull/35820): @bolkedebruin
## Provider [odbc: 4.3.0rc2](https://pypi.org/project/apache-airflow-providers-odbc/4.3.0rc2)
   - [ ] [Fix: Implement support for `fetchone()` in the ODBCHook and the Databricks SQL Hook (#36161)](https://github.com/apache/airflow/pull/36161): @Joffreybvn

All users involved in the PRs:
@kacpermuda @nathadfield @potiuk @Joffreybvn @atrbgithub @bolkedebruin @VladaZakharova @Taragolis @eladkal @guillaumeblaquiere @ginolegigot @stavdav143 @melugoyal @shourya116

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by Lee-W** [comment]
I think we still have an issue on google-provider. I just sent https://github.com/apache/airflow/pull/36202 for addressing it

**Comment by potiuk** [comment]
Yep. Both Google and Databricks will be removed and we will have RC3 for them.

**Comment by guillaumeblaquiere** [comment]
Just validated #36133

**Comment by potiuk** [comment]
Fix to databricks discussed in https://github.com/apache/airflow/pull/36205

**Comment by stavdav143** [comment]
Docker Operator and changes

- [Fixenable_logging=Truenot working ***@***.***(https://github.com/stavdav143)
- [Fix broken log streaming from #35677 ***@***.***(https://github.com/stavdav143)

look fine.

[(#36086](https://github.com/apache/airflow/pull/36086), [#36017)](https://github.com/apache/airflow/pull/36017) can be tested by someone who knows better
Jarek Potiuk ***@***.***> schrieb am Mittwoch, 13. Dezember 2023 um 14:55:

**Comment by potiuk** [comment]
Thanks everyone. The providers except Google and Databricks have been released. We will shortly get RC3 release for them (and also the two removed sqoop and plexus providers).
