### ISSUE TITLE
Status of testing Providers that were prepared on December 28, 2023

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#36467]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [alibaba: 2.7.1rc1](https://pypi.org/project/apache-airflow-providers-alibaba/2.7.1rc1)
   - [x] [Clean OSS task handler code after bumping min Airflow version to 2.6.0 (#36420)](https://github.com/apache/airflow/pull/36420): @hussein-awala
## Provider [amazon: 8.15.0rc1](https://pypi.org/project/apache-airflow-providers-amazon/8.15.0rc1)
   - [x] [Add Amazon Athena query results extra link (#36447)](https://github.com/apache/airflow/pull/36447): @Taragolis
   - [x] [remove event['message'] call in EmrContainerOperator.execute_complete|as the key message no longer exists (#36417)](https://github.com/apache/airflow/pull/36417): @Lee-W
   - [x] [handle tzinfo in S3Hook.is_keys_unchanged_async (#36363)](https://github.com/apache/airflow/pull/36363): @Lee-W
   - [ ] [Use base aws classes in Amazon ECS Operators/Sensors/Triggers (#36393)](https://github.com/apache/airflow/pull/36393): @jayceslesar
## Provider [apache.hdfs: 4.3.2rc1](https://pypi.org/project/apache-airflow-providers-apache-hdfs/4.3.2rc1)
   - [x] [Remove _read method from hdfs task handler after bumping min airflow version to 2.6 (#36425)](https://github.com/apache/airflow/pull/36425): @hussein-awala
   - [x] [Consolidate loading delete_local_logs conf in hdfs task handler (#36422)](https://github.com/apache/airflow/pull/36422): @hussein-awala
## Provider [apache.kylin: 3.5.0rc1](https://pypi.org/project/apache-airflow-providers-apache-kylin/3.5.0rc1)
   - [x] [Add apache kylin conn type and kylin connection docs (#36413)](https://github.com/apache/airflow/pull/36413): @shohamy7
## Provider [cncf.kubernetes: 7.13.0rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/7.13.0rc1)
   - [ ] [Allow changing of `config_file` in `KubernetesResourceBaseOperator` (#36397)](https://github.com/apache/airflow/pull/36397): @romsharon98
   - [x] [Add reminder about update stub file in case of change KubernetesPodOperator's arguments (#36434)](https://github.com/apache/airflow/pull/36434): @Taragolis
   - [ ] [Fix AirflowSkipException message raised by KubernetesPodOperator (#36355)](https://github.com/apache/airflow/pull/36355): @dolfinus
   - [x] [Remove deprecated input parameters in the k8s pod operator (#36433)](https://github.com/apache/airflow/pull/36433): @dirrao
   - [x] [Delete get_python_source from Kubernetes decorator after bumping min airflow version to 2.6.0 (#36426)](https://github.com/apache/airflow/pull/36426): @hussein-awala
   - [x] [Remove duplicated methods in K8S pod operator module and import them from helper function (#36427)](https://github.com/apache/airflow/pull/36427): @hussein-awala
## Provider [elasticsearch: 5.3.1rc1](https://pypi.org/project/apache-airflow-providers-elasticsearch/5.3.1rc1)
   - [x] [Remove getattr in es task handler when airflow min version bumped to 2.6 (#36431)](https://github.com/apache/airflow/pull/36431): @dirrao
## Provider [google: 10.13.1rc1](https://pypi.org/project/apache-airflow-providers-google/10.13.1rc1)
   - [ ] [Remove backcompat code for stackdriver (#36442)](https://github.com/apache/airflow/pull/36442): @potiuk
   - [x] [Remove unused `_parse_version` function (#36450)](https://github.com/apache/airflow/pull/36450): @Taragolis
   - [ ] [Remove remaining Airflow 2.5 backcompat code from GCS Task Handler  (#36457)](https://github.com/apache/airflow/pull/36457): @potiuk
## Provider [microsoft.azure: 8.5.1rc1](https://pypi.org/project/apache-airflow-providers-microsoft-azure/8.5.1rc1)
   - [x] [Remove unused `_parse_version` function (#36450)](https://github.com/apache/airflow/pull/36450): @Taragolis
   - [x] [Clean WASB task handler code after bumping min Airflow version to 2.6.0 (#36421)](https://github.com/apache/airflow/pull/36421): @hussein-awala
## Provider [weaviate: 1.3.0rc1](https://pypi.org/project/apache-airflow-providers-weaviate/1.3.0rc1)
   - [ ] [Add WeaviateDocumentIngestOperator (#36402)](https://github.com/apache/airflow/pull/36402): @utkarsharma2
   - [ ] [Add 'uuid_column', 'tenant' params to WeaviateIngestOperator (#36387)](https://github.com/apache/airflow/pull/36387): @utkarsharma2
   - [ ] [Add create_or_replace_document_objects method to weaviate provider (#36177)](https://github.com/apache/airflow/pull/36177): @utkarsharma2
   - [ ] [Remove 'insertion_errors' as required argument for weaviate's hook 'batch_data' method (#36435)](https://github.com/apache/airflow/pull/36435): @utkarsharma2
## Provider [zendesk: 4.6.0rc1](https://pypi.org/project/apache-airflow-providers-zendesk/4.6.0rc1)
   - [x] [Add docs about zendesk connection and creating dedicated connection form (#36423)](https://github.com/apache/airflow/pull/36423): @shohamy7

All users involved in the PRs:
@romsharon98 @jayceslesar @dolfinus @Lee-W @utkarsharma2 @potiuk @shohamy7 @Taragolis @hussein-awala @dirrao

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by Taragolis** [comment]
Check my changes:
- https://github.com/apache/airflow/pull/36447 : Works as expected
- https://github.com/apache/airflow/pull/36434 : Internal changes:  comments added
- https://github.com/apache/airflow/pull/36450: Internal changes: no side effects found

**Comment by Lee-W** [comment]
Tested our example DAGs with the following providers without encountering issues

* apache-airflow-providers-amazon==8.15.0rc1
* apache-airflow-providers-cncf-kubernetes==7.13.0rc1
* apache-airflow-providers-google==10.13.1rc1
* apache-airflow-providers-microsoft-azure==8.5.1rc1

**Comment by Lee-W** [comment]
https://github.com/apache/airflow/pull/36417 and https://github.com/apache/airflow/pull/36363 also verified

**Comment by dirrao** [comment]
I have verified the following #36433 and #36431. They looks good to me.

**Comment by shohamy7** [comment]
Verified #36423 and #36413, looks good

**Comment by hussein-awala** [comment]
I checked my changes, and all looks good!

**Comment by potiuk** [comment]
Thank you everyone. Providers are released (except Waeviate that will have ad-hoc release shortly).

I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
