### ISSUE TITLE
Status of testing Providers that were prepared on December 31, 2023

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#36511]
I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [weaviate: 1.3.0rc2](https://pypi.org/project/apache-airflow-providers-weaviate/1.3.0rc2)
   - [x] [Add WeaviateDocumentIngestOperator (#36402)](https://github.com/apache/airflow/pull/36402): @utkarsharma2
   - [x] [Add 'uuid_column', 'tenant' params to WeaviateIngestOperator (#36387)](https://github.com/apache/airflow/pull/36387): @utkarsharma2
   - [x] [Add create_or_replace_document_objects method to weaviate provider (#36177)](https://github.com/apache/airflow/pull/36177): @utkarsharma2
   - [x] [Remove 'insertion_errors' as required argument for weaviate's hook 'batch_data' method (#36435)](https://github.com/apache/airflow/pull/36435): @utkarsharma2
   - [x] [Handle  list like input objects in weavaite's 'create_or_replace_document_objects' hook method (#36475)](https://github.com/apache/airflow/pull/36475): @utkarsharma2

All users involved in the PRs:
@utkarsharma2

**Comment by utkarsharma2** [comment]
Thanks @potiuk for the ad-hoc release and yes, It's all working as expected. :)

**Comment by potiuk** [comment]
Thanks @utkarsharma2 !. Providers are released.

I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
