### ISSUE TITLE
Status of testing Providers that were prepared on January 07, 2024

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#36644]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 8.16.0rc1](https://pypi.org/project/apache-airflow-providers-amazon/8.16.0rc1)
   - [x] [Add AWS Step Functions links (#36599)](https://github.com/apache/airflow/pull/36599): @Taragolis
   - [x] [openlineage, aws: add OpenLineage support for Redshift SQL. (#35794)](https://github.com/apache/airflow/pull/35794): @JDarDagran
   - [x] [Fix assignment of template field in `__init__` in `AwsToAwsBaseOperator` (#36604)](https://github.com/apache/airflow/pull/36604): @romsharon98
   - [x] [Fix assignment of template field in `__init__` in `DataSyncOperator` (#36605)](https://github.com/apache/airflow/pull/36605): @romsharon98
   - [x] [Check redshift cluster state before deferring to triggerer (#36416)](https://github.com/apache/airflow/pull/36416): @Lee-W
   - [x] [Use base aws classes in Amazon SQS Operators/Sensors/Triggers (#36613)](https://github.com/apache/airflow/pull/36613): @Taragolis
   - [x] [Use base aws classes in Amazon SNS Operators (#36615)](https://github.com/apache/airflow/pull/36615): @Taragolis
   - [x] [Use base aws classes in AWS Step Functions Operators/Sensors/Triggers (#36468)](https://github.com/apache/airflow/pull/36468): @Taragolis
## Provider [apache.hive: 6.4.1rc1](https://pypi.org/project/apache-airflow-providers-apache-hive/6.4.1rc1)
   - [x] [Fix assignment of template field in `__init__` in `hive_to_samba.py` (#36486)](https://github.com/apache/airflow/pull/36486): @romsharon98
## Provider [apache.livy: 3.7.1rc1](https://pypi.org/project/apache-airflow-providers-apache-livy/3.7.1rc1)
   - [x] [prevent templated field logic checks in operators `__init__` in livy operator  (#36490)](https://github.com/apache/airflow/pull/36490): @romsharon98
## Provider [apache.spark: 4.7.0rc1](https://pypi.org/project/apache-airflow-providers-apache-spark/4.7.0rc1)
   - [x] [change spark connection form and add spark connections docs (#36419)](https://github.com/apache/airflow/pull/36419): @shohamy7
## Provider [atlassian.jira: 2.5.0rc1](https://pypi.org/project/apache-airflow-providers-atlassian-jira/2.5.0rc1)
   - [x] [Add jira connection docs and UI form (#36458)](https://github.com/apache/airflow/pull/36458): @shohamy7
## Provider [common.io: 1.2.0rc1](https://pypi.org/project/apache-airflow-providers-common-io/1.2.0rc1)
   - [ ] [Add support for openlineage to AFS and common.io (#36410)](https://github.com/apache/airflow/pull/36410): @bolkedebruin
## Provider [mysql: 5.5.1rc1](https://pypi.org/project/apache-airflow-providers-mysql/5.5.1rc1)
   - [x] [Sanitize filenames in MySQLHook (#33328)](https://github.com/apache/airflow/pull/33328): @PApostol
## Provider [openlineage: 1.4.0rc1](https://pypi.org/project/apache-airflow-providers-openlineage/1.4.0rc1)
   - [ ] [openlineage, aws: add OpenLineage support for Redshift SQL. (#35794)](https://github.com/apache/airflow/pull/35794): @JDarDagran
## Provider [opsgenie: 5.5.0rc1](https://pypi.org/project/apache-airflow-providers-opsgenie/5.5.0rc1)
   - [x] [Add docs for opsgenie connection (#36519)](https://github.com/apache/airflow/pull/36519): @shohamy7
## Provider [pagerduty: 3.6.0rc1](https://pypi.org/project/apache-airflow-providers-pagerduty/3.6.0rc1)
   - [x] [Add docs on pagerduty connection (#36636)](https://github.com/apache/airflow/pull/36636): @shohamy7
## Provider [redis: 3.6.0rc1](https://pypi.org/project/apache-airflow-providers-redis/3.6.0rc1)
   - [x] [Add docs to redis connection (#36581)](https://github.com/apache/airflow/pull/36581): @shohamy7
   - [x] [Add username authenticating to the Redis hook (#36562)](https://github.com/apache/airflow/pull/36562): @shohamy7
   - [x] [Fix misconfiguration of redis client with ssl (#36561)](https://github.com/apache/airflow/pull/36561): @shohamy7
## Provider [samba: 4.5.0rc1](https://pypi.org/project/apache-airflow-providers-samba/4.5.0rc1)
   - [x] [Add docs and user-friendly connection form for Samba connection (#36543)](https://github.com/apache/airflow/pull/36543): @shohamy7

All users involved in the PRs:
@bolkedebruin @shohamy7 @Taragolis @romsharon98 @Lee-W @JDarDagran @PApostol

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by Lee-W** [comment]
We've tested with the following providers with our example DAGs without encountering issues.

* apache-airflow-providers-amazon==8.16.0rc1 (this includes https://github.com/apache/airflow/pull/36416)
* apache-airflow-providers-apache-hive==6.4.1rc1
* apache-airflow-providers-apache-livy==3.7.1rc1

**Comment by vatsrahul1001** [comment]
Re-tested providers mentioned by @Lee-W also verified apache-airflow-providers-mysql==5.5.1rc1. LGTM

**Comment by shohamy7** [comment]
I've checked my changes, all looks good

**Comment by eladkal** [comment]
Thank you everyone. Providers are released.

I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
