### ISSUE TITLE
Status of testing Providers that were prepared on January 26, 2024

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#36948]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [airbyte: 3.6.0rc2](https://pypi.org/project/apache-airflow-providers-airbyte/3.6.0rc2)
   - [ ] [Add deferrable functionality to the AirbyteJobSensor and AirbyteTriggerSyncOperator (#36780)](https://github.com/apache/airflow/pull/36780): @chrishronek
## Provider [alibaba: 2.7.2rc2](https://pypi.org/project/apache-airflow-providers-alibaba/2.7.2rc2)
   - [ ] [Fix assignment of template field in `__init__` in `analyticdb_spark.py` (#36911)](https://github.com/apache/airflow/pull/36911): @romsharon98
## Provider [amazon: 8.17.0rc2](https://pypi.org/project/apache-airflow-providers-amazon/8.17.0rc2)
   - [ ] [add deferrable mode to RedshiftDataOperator (#36586)](https://github.com/apache/airflow/pull/36586): @Lee-W
   - [x] [Adds support for capacity providers to ECS Executor (#36722)](https://github.com/apache/airflow/pull/36722): @ferruzzi
   - [ ] [add use_regex argument for allowing S3KeySensor to check s3 keys with regular expression (#36578)](https://github.com/apache/airflow/pull/36578): @Lee-W
   - [ ] [add deferrable mode to RedshiftClusterSensor (#36550)](https://github.com/apache/airflow/pull/36550): @Lee-W
   - [ ] [Implement AthenaSQLHook (#36171)](https://github.com/apache/airflow/pull/36171): @flolas
   - [ ] [Create CLI commands for AWS auth manager to create Amazon Verified Permissions related resources (#36799)](https://github.com/apache/airflow/pull/36799): @vincbeck
   - [ ] [Implement `is_authorized_dag` in AWS auth manager (#36619)](https://github.com/apache/airflow/pull/36619): @vincbeck
   - [x] [Fix stacklevel in warnings.warn into the providers (#36831)](https://github.com/apache/airflow/pull/36831): @Taragolis
   - [ ] [EC2 CreateInstance: terminate instances in on_kill (#36828)](https://github.com/apache/airflow/pull/36828): @AchimGaedkeLynker
   - [x] [Fallback to default value if `[aws] cloudwatch_task_handler_json_serializer` not set (#36851)](https://github.com/apache/airflow/pull/36851): @Taragolis
   - [x] [Raise AirflowOptionalProviderfeature exception for AVP command (#36824)](https://github.com/apache/airflow/pull/36824): @potiuk
   - [ ] [check transform job status before deferring SageMakerTransformOperator (#36680)](https://github.com/apache/airflow/pull/36680): @Lee-W
   - [ ] [check ProcessingJobStatus status before deferring SageMakerProcessingOperator (#36658)](https://github.com/apache/airflow/pull/36658): @Lee-W
   - [ ] [check job_status before BatchOperator execute in deferrable mode (#36523)](https://github.com/apache/airflow/pull/36523): @Lee-W
   - [x] [Update the redshift hostname check to avoid possible bugs (#36703)](https://github.com/apache/airflow/pull/36703): @hussein-awala
   - [ ] [Refresh credentials in `AwsEcsExecutor` (#36179)](https://github.com/apache/airflow/pull/36179): @syedahsn
   - [ ] [Fix on docstring for apply_wildcard parameter in S3ListOperator (#36679)](https://github.com/apache/airflow/pull/36679): @sasidharan-rathinam
   - [x] [Use base aws classes in AWS DMS Operators/Sensors (#36772)](https://github.com/apache/airflow/pull/36772): @Taragolis
   - [x] [Use base aws classes in AWS Redshift Data API Operators (#36764)](https://github.com/apache/airflow/pull/36764): @Taragolis
   - [x] [Use base aws classes in Amazon EventBridge Operators (#36765)](https://github.com/apache/airflow/pull/36765): @Taragolis
   - [x] [Use base aws classes in Amazon QuickSight Operators/Sensors (#36776)](https://github.com/apache/airflow/pull/36776): @Taragolis
   - [x] [Use base aws classes in AWS Datasync Operators (#36766)](https://github.com/apache/airflow/pull/36766): @Taragolis
   - [x] [Use base aws classes in Amazon DynamoDB Sensors (#36770)](https://github.com/apache/airflow/pull/36770): @Taragolis
   - [x] [Use base aws classes in AWS CloudFormation Operators/Sensors (#36771)](https://github.com/apache/airflow/pull/36771): @Taragolis
   - [x] [Set min pandas dependency to 1.2.5 for all providers and airflow (#36698)](https://github.com/apache/airflow/pull/36698): @potiuk
   - [x] [Bump min version of amazon-provider related dependencies (#36660)](https://github.com/apache/airflow/pull/36660): @potiuk
## Provider [apache.beam: 5.6.0rc2](https://pypi.org/project/apache-airflow-providers-apache-beam/5.6.0rc2)
   - [x] [Get rid of pyarrow-hotfix for CVE-2023-47248 (#36697)](https://github.com/apache/airflow/pull/36697): @potiuk
## Provider [apache.druid: 3.8.0rc2](https://pypi.org/project/apache-airflow-providers-apache-druid/3.8.0rc2)
   - [ ] [Provide the logger_name param in providers hooks in order to override the logger name (#36675)](https://github.com/apache/airflow/pull/36675): @hussein-awala
   - [x] [Fix successful Apache Druid task submissions reported as failed (#36813)](https://github.com/apache/airflow/pull/36813): @listik
## Provider [apache.hive: 6.4.2rc1](https://pypi.org/project/apache-airflow-providers-apache-hive/6.4.2rc1)
   - [ ] [Fix assignment of template field in `__init__` in `hive-stats` (#36905)](https://github.com/apache/airflow/pull/36905): @romsharon98
   - [x] [Set min pandas dependency to 1.2.5 for all providers and airflow (#36698)](https://github.com/apache/airflow/pull/36698): @potiuk
## Provider [apache.spark: 4.7.1rc1](https://pypi.org/project/apache-airflow-providers-apache-spark/4.7.1rc1)
   - [x] [Bump min version for grpcio-status in spark provider (#36662)](https://github.com/apache/airflow/pull/36662): @potiuk
## Provider [atlassian.jira: 2.5.1rc1](https://pypi.org/project/apache-airflow-providers-atlassian-jira/2.5.1rc1)
   - [x] [Use lax `atlassian-python-api` limitation (#36841)](https://github.com/apache/airflow/pull/36841): @Taragolis
   - [x] [Limit `atlassian-python-api` to <3.41.6 (#36815)](https://github.com/apache/airflow/pull/36815): @Taragolis
## Provider [celery: 3.5.2rc2](https://pypi.org/project/apache-airflow-providers-celery/3.5.2rc2)
   - [x] [Fix stacklevel in warnings.warn into the providers (#36831)](https://github.com/apache/airflow/pull/36831): @Taragolis
## Provider [cncf.kubernetes: 7.14.0rc2](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/7.14.0rc2)
   - [ ] [Add SparkKubernetesOperator crd implementation (#22253)](https://github.com/apache/airflow/pull/22253): @hamedhsn
   - [x] [Template field support for configmaps in the KubernetesPodOperator (#36922)](https://github.com/apache/airflow/pull/36922): @vizeit
   - [x] [Create a generic callbacks class for KubernetesPodOperator (#35714)](https://github.com/apache/airflow/pull/35714): @hussein-awala
   - [ ] [avoid retrying after KubernetesPodOperator has been marked as failed (#36749)](https://github.com/apache/airflow/pull/36749): @Lee-W
   - [x] [Fix stacklevel in warnings.warn into the providers (#36831)](https://github.com/apache/airflow/pull/36831): @Taragolis
   - [ ] [Increase tenacity wait in read_pod_logs (#36955)](https://github.com/apache/airflow/pull/36955): @o-nikolas
   - [x] [Fix dynamic configmaps as environment variable in `KubernetesPodOperator` (#37001)](https://github.com/apache/airflow/pull/37001): @vizeit
   - [x] [Change field type for kube_config in kubernetes cluster connection (#36752)](https://github.com/apache/airflow/pull/36752): @arjunanan6
   - [ ] [Changing wording in docstring for CNCF provider (#36547)](https://github.com/apache/airflow/pull/36547): @amoghrajesh
   - [ ] [Add support of Pendulum 3 (#36281)](https://github.com/apache/airflow/pull/36281): @Taragolis
## Provider [cohere: 1.1.2rc1](https://pypi.org/project/apache-airflow-providers-cohere/1.1.2rc1)
   - [x] [Bump Cohere min version to limit backtracking on upgrade (#36666)](https://github.com/apache/airflow/pull/36666): @potiuk
## Provider [common.sql: 1.10.1rc1](https://pypi.org/project/apache-airflow-providers-common-sql/1.10.1rc1)
   - [x] [Set min pandas dependency to 1.2.5 for all providers and airflow (#36698)](https://github.com/apache/airflow/pull/36698): @potiuk
## Provider [databricks: 6.1.0rc2](https://pypi.org/project/apache-airflow-providers-databricks/6.1.0rc2)
   - [ ] [[FEAT] adds repair run functionality for databricks (#36601)](https://github.com/apache/airflow/pull/36601): @gaurav7261
   - [x] [Fix databricks_sql hook query failing on empty result for return_tuple (#36827)](https://github.com/apache/airflow/pull/36827): @potiuk
   - [ ] [Rename columns to valid namedtuple attributes + ensure Row.fields are retrieved as tuple (#36949)](https://github.com/apache/airflow/pull/36949): @Joffreybvn
   - [ ] [check status before DatabricksSubmitRunOperator & DatabricksSubmitRunOperator executes in deferrable mode (#36862)](https://github.com/apache/airflow/pull/36862): @vatsrahul1001
## Provider [dbt.cloud: 3.6.0rc2](https://pypi.org/project/apache-airflow-providers-dbt-cloud/3.6.0rc2)
   - [ ] [OpenLineage: Add dag_id when generating run_id for task instance. (#36659)](https://github.com/apache/airflow/pull/36659): @kacpermuda
   - [x] [Fix stacklevel in warnings.warn into the providers (#36831)](https://github.com/apache/airflow/pull/36831): @Taragolis
## Provider [discord: 3.6.0rc2](https://pypi.org/project/apache-airflow-providers-discord/3.6.0rc2)
   - [ ] [Add docs for discord webhook connection (#36720)](https://github.com/apache/airflow/pull/36720): @shohamy7
## Provider [elasticsearch: 5.3.2rc1](https://pypi.org/project/apache-airflow-providers-elasticsearch/5.3.2rc1)
   - [x] [Fix stacklevel in warnings.warn into the providers (#36831)](https://github.com/apache/airflow/pull/36831): @Taragolis
## Provider [exasol: 4.4.2rc2](https://pypi.org/project/apache-airflow-providers-exasol/4.4.2rc2)
   - [x] [Set min pandas dependency to 1.2.5 for all providers and airflow (#36698)](https://github.com/apache/airflow/pull/36698): @potiuk
## Provider [google: 10.14.0rc2](https://pypi.org/project/apache-airflow-providers-google/10.14.0rc2)
   - [ ] [Add templated fields to `BigQueryToSqlBaseOperator` from `BigQueryToPostgresOperator` (#36663)](https://github.com/apache/airflow/pull/36663): @romsharon98
   - [ ] [Added Check for Cancel Workflow Invocation and added new Query Workflow Invocation operator (#36351)](https://github.com/apache/airflow/pull/36351): @varuntwr
   - [ ] [Implement Google Analytics Admin (GA4) operators (#36276)](https://github.com/apache/airflow/pull/36276): @moiseenkov
   - [ ] [Add operator to collect diagnostic tarball for Dataproc cluster (#36899)](https://github.com/apache/airflow/pull/36899): @flacode
   - [ ] [Add scopes into a GCP token (#36974)](https://github.com/apache/airflow/pull/36974): @moiseenkov
   - [ ] [feat: full support for google credentials in gcloud-aio clients (#36849)](https://github.com/apache/airflow/pull/36849): @m1racoli
   - [ ] [Fix assignment of template field in `__init__` in `auto_ml.py` (#36934)](https://github.com/apache/airflow/pull/36934): @romsharon98
   - [x] [fix: respect connection ID and impersonation in GKEStartPodOperator (#36861)](https://github.com/apache/airflow/pull/36861): @m1racoli
   - [x] [Fix stacklevel in warnings.warn into the providers (#36831)](https://github.com/apache/airflow/pull/36831): @Taragolis
   - [x] [Fix deprecations into the GCP Dataproc links (#36834)](https://github.com/apache/airflow/pull/36834): @Taragolis
   - [ ] [Fix assignment of template field in `__init__` in `SFTPToGCSOperator ` (#36603)](https://github.com/apache/airflow/pull/36603): @romsharon98
   - [x] [Check cluster state before defer Dataproc operators to trigger (#36892)](https://github.com/apache/airflow/pull/36892): @Lee-W
   - [ ] [prevent templated field logic checks in operators `__init__` in dataproc (#36489)](https://github.com/apache/airflow/pull/36489): @romsharon98
   - [ ] [Preserve ASCII control characters directly through the BigQuery load API (#36533)](https://github.com/apache/airflow/pull/36533): @romsharon98
   - [ ] [Change default `parquet_row_group_size` in `BaseSQLToGCSOperator` (#36817)](https://github.com/apache/airflow/pull/36817): @renzepost
   - [ ] [Fix google operators handling of impersonation chain (#36903)](https://github.com/apache/airflow/pull/36903): @m1racoli
   - [x] [style(providers/google): improve BigQueryInsertJobOperator type hinting (#36894)](https://github.com/apache/airflow/pull/36894): @Lee-W
   - [ ] [Deprecate AutoMLTrainModelOperator for Vision and Video (#36473)](https://github.com/apache/airflow/pull/36473): @VladaZakharova
   - [ ] [Remove backward compatibility check for KubernetesPodOperator module (#36724)](https://github.com/apache/airflow/pull/36724): @hussein-awala
   - [ ] [Remove backward compatibility check for KubernetesPodTrigger module from google provider (#36721)](https://github.com/apache/airflow/pull/36721): @hussein-awala
   - [x] [Set min pandas dependency to 1.2.5 for all providers and airflow (#36698)](https://github.com/apache/airflow/pull/36698): @potiuk
   - [ ] [prevent templated field logic checks in operators `__init__` in `BigQueryToPostgresOperator` operator (#36491)](https://github.com/apache/airflow/pull/36491): @romsharon98
   - [x] [reword GoogleBaseHookAsync as GoogleBaseAsyncHook in docstring (#36946)](https://github.com/apache/airflow/pull/36946): @Lee-W
## Provider [hashicorp: 3.6.2rc1](https://pypi.org/project/apache-airflow-providers-hashicorp/3.6.2rc1)
   - [ ] [Explicitly passing `raise_on_deleted_version=True` to `read_secret_version` in Hashicorp operator (#36532)](https://github.com/apache/airflow/pull/36532): @romsharon98
## Provider [http: 4.9.0rc2](https://pypi.org/project/apache-airflow-providers-http/4.9.0rc2)
   - [ ] [Allow default requests parameters like proxy to be defined in extra options field of a Airflow HTTP Connection (#36733)](https://github.com/apache/airflow/pull/36733): @dabla
   - [ ] [Add deferrable implementation in HTTPSensor (#36904)](https://github.com/apache/airflow/pull/36904): @vatsrahul1001
   - [x] [Fix stacklevel in warnings.warn into the providers (#36831)](https://github.com/apache/airflow/pull/36831): @Taragolis
## Provider [mongo: 3.6.0rc2](https://pypi.org/project/apache-airflow-providers-mongo/3.6.0rc2)
   - [x] [Switch to `mongo_conn_id` argument into the MongoHook constructor (#36896)](https://github.com/apache/airflow/pull/36896): @Taragolis
## Provider [mysql: 5.5.2rc2](https://pypi.org/project/apache-airflow-providers-mysql/5.5.2rc2)
   - [x] [Bump min version of mysql-connector-python (#36668)](https://github.com/apache/airflow/pull/36668): @potiuk
## Provider [odbc: 4.4.1rc2](https://pypi.org/project/apache-airflow-providers-odbc/4.4.1rc2)
   - [ ] [Fix ODBC Hook sql select return empty table (#36709)](https://github.com/apache/airflow/pull/36709): @roel-w
   - [ ] [Rename columns to valid namedtuple attributes + ensure Row.fields are retrieved as tuple (#36949)](https://github.com/apache/airflow/pull/36949): @Joffreybvn
## Provider [openlineage: 1.5.0rc2](https://pypi.org/project/apache-airflow-providers-openlineage/1.5.0rc2)
   - [ ] [OpenLineage: Add dag_id when generating run_id for task instance. (#36659)](https://github.com/apache/airflow/pull/36659): @kacpermuda
   - [ ] [Prepare docs 2nd wave of Providers January 2024 (#36945)](https://github.com/apache/airflow/pull/36945): @eladkal
## Provider [pagerduty: 3.6.1rc1](https://pypi.org/project/apache-airflow-providers-pagerduty/3.6.1rc1)
   - [x] [Fix stacklevel in warnings.warn into the providers (#36831)](https://github.com/apache/airflow/pull/36831): @Taragolis
   - [ ] [Revert "Provide the logger_name param in providers hooks in order to override the logger name (#36675)" (#37015)](https://github.com/apache/airflow/pull/37015): @Taragolis
   - [ ] [Prepare docs 2nd wave of Providers January 2024 (#36945)](https://github.com/apache/airflow/pull/36945): @eladkal
   - [ ] [Provide the logger_name param in providers hooks in order to override the logger name (#36675)](https://github.com/apache/airflow/pull/36675): @hussein-awala
## Provider [papermill: 3.6.1rc2](https://pypi.org/project/apache-airflow-providers-papermill/3.6.1rc2)
   - [ ] [Fix assignment of template field in `__init__` in `papermill.py` (#36530)](https://github.com/apache/airflow/pull/36530): @romsharon98
   - [x] [Bump min provider version for papermill (#36669)](https://github.com/apache/airflow/pull/36669): @potiuk
## Provider [pinecone: 1.1.2rc1](https://pypi.org/project/apache-airflow-providers-pinecone/1.1.2rc1)
   - [x] [Limit `pinecone-client` to <3.0 (#36818)](https://github.com/apache/airflow/pull/36818): @Taragolis
## Provider [presto: 5.4.1rc2](https://pypi.org/project/apache-airflow-providers-presto/5.4.1rc2)
   - [x] [Set min pandas dependency to 1.2.5 for all providers and airflow (#36698)](https://github.com/apache/airflow/pull/36698): @potiuk
## Provider [salesforce: 5.6.2rc1](https://pypi.org/project/apache-airflow-providers-salesforce/5.6.2rc1)
   - [ ] [Set min pandas dependency to 1.2.5 for all providers and airflow (#36698)](https://github.com/apache/airflow/pull/36698): @potiuk
## Provider [slack: 8.6.0rc2](https://pypi.org/project/apache-airflow-providers-slack/8.6.0rc2)
   - [x] [Optionally use `client.files_upload_v2` in Slack Provider (#36757)](https://github.com/apache/airflow/pull/36757): @Taragolis
   - [x] [Fix stacklevel in warnings.warn into the providers (#36831)](https://github.com/apache/airflow/pull/36831): @Taragolis
## Provider [snowflake: 5.3.0rc2](https://pypi.org/project/apache-airflow-providers-snowflake/5.3.0rc2)
   - [ ] [Add openlineage support for CopyFromExternalStageToSnowflakeOperator (#36535)](https://github.com/apache/airflow/pull/36535): @kacpermuda
   - [x] [Fix stacklevel in warnings.warn into the providers (#36831)](https://github.com/apache/airflow/pull/36831): @Taragolis
   - [ ] [check query status before SnowflakeSqlApiOperator execute in deferrable mode (#36850)](https://github.com/apache/airflow/pull/36850): @vatsrahul1001
## Provider [tableau: 4.4.1rc1](https://pypi.org/project/apache-airflow-providers-tableau/4.4.1rc1)
   - [x] [Fix stacklevel in warnings.warn into the providers (#36831)](https://github.com/apache/airflow/pull/36831): @Taragolis
## Provider [telegram: 4.3.1rc1](https://pypi.org/project/apache-airflow-providers-telegram/4.3.1rc1)
   - [x] [Bump min telegram-bot version (#36670)](https://github.com/apache/airflow/pull/36670): @potiuk
## Provider [trino: 5.6.1rc2](https://pypi.org/project/apache-airflow-providers-trino/5.6.1rc2)
   - [x] [Set min pandas dependency to 1.2.5 for all providers and airflow (#36698)](https://github.com/apache/airflow/pull/36698): @potiuk
## Provider [weaviate: 1.3.1rc2](https://pypi.org/project/apache-airflow-providers-weaviate/1.3.1rc2)
   - [x] [Fix stacklevel in warnings.warn into the providers (#36831)](https://github.com/apache/airflow/pull/36831): @Taragolis
   - [ ] [Fix assignment of template field in `__init__` in weaviate (#36908)](https://github.com/apache/airflow/pull/36908): @romsharon98
## Provider [yandex: 3.8.0rc2](https://pypi.org/project/apache-airflow-providers-yandex/3.8.0rc2)
   - [ ] [feat: add Yandex Cloud Lockbox secrets backend (#36449)](https://github.com/apache/airflow/pull/36449): @ImpressionableRaccoon
   - [x] [Fix stacklevel in warnings.warn into the providers (#36831)](https://github.com/apache/airflow/pull/36831): @Taragolis

All users involved in the PRs:
@romsharon98 @kacpermuda @dabla @renzepost @vizeit @varuntwr @AchimGaedkeLynker @hamedhsn @Taragolis @Lee-W @ferruzzi @sasidharan-rathinam @hussein-awala @chrishronek @syedahsn @vatsrahul1001 @arjunanan

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by m1racoli** [comment]
Tested https://github.com/apache/airflow/pull/36861 and impersonation chain is now properly passed.

**Comment by arjunanan6** [comment]
Test #36752  and it works as expected.

**Comment by Lee-W** [comment]
Verified https://github.com/apache/airflow/pull/36892, https://github.com/apache/airflow/pull/36946 and https://github.com/apache/airflow/pull/36894. will continue work on the rest

**Comment by potiuk** [comment]
All my changes work ! :tada:

**Comment by Taragolis** [comment]
Validate changes in 
- https://github.com/apache/airflow/pull/36831
- https://github.com/apache/airflow/pull/36834
- https://github.com/apache/airflow/pull/36818
- https://github.com/apache/airflow/pull/36841
- https://github.com/apache/airflow/pull/36815
- https://github.com/apache/airflow/pull/36896


I plan to check later other my changes

**Comment by romsharon98** [comment]
Validate changes in:
https://github.com/apache/airflow/pull/36911
https://github.com/apache/airflow/pull/36905
https://github.com/apache/airflow/pull/36663
https://github.com/apache/airflow/pull/36934
https://github.com/apache/airflow/pull/36603
https://github.com/apache/airflow/pull/36489
https://github.com/apache/airflow/pull/36533
https://github.com/apache/airflow/pull/36491
https://github.com/apache/airflow/pull/36532
https://github.com/apache/airflow/pull/36530
https://github.com/apache/airflow/pull/36908

**Comment by VladaZakharova** [comment]
Hi!
#36473 works as well, thank you :)

**Comment by moiseenkov** [comment]
#36276 works as expected

**Comment by AchimGaedkeLynker** [comment]
https://github.com/apache/airflow/pull/36828 works as expected

**Comment by Lee-W** [comment]
Tested https://github.com/apache/airflow/pull/36586, https://github.com/apache/airflow/pull/36578, https://github.com/apache/airflow/pull/36550, https://github.com/apache/airflow/pull/36680, https://github.com/apache/airflow/pull/36658

**Comment by renzepost** [comment]
#36817 works as expected

**Comment by hussein-awala** [comment]
Tested my changes, they look good.

**Comment by vizeit** [comment]
#36922 tested. It is working for configmaps mounted as volume but not for configmaps mounted as environment variable. I was troubleshooting the issue and it appears that I will need to make ‘env_from’ templated not ‘configmaps’ attribute. Any inputs from k8 operator experts? Also please let me know how do I proceed with the fix, a new issue or just open new PR with the fix?

**Comment by vizeit** [comment]
> #36922 tested. It is working for configmaps mounted as volume but not for configmaps mounted as environment variable. I was troubleshooting the issue and it appears that I will need to make ‘env_from’ templated not ‘configmaps’ attribute. Any inputs from k8 operator experts? Also please let me know how do I proceed with the fix, a new issue or just open new PR with the fix?

Opened #37001 with the fix and unit tested

**Comment by potiuk** [comment]
> Opened https://github.com/apache/airflow/pull/37001 with the fix and unit tested

Cool. Yep. that's ok. In Airlfow `PR` is the `unit of work` - not issue, issue is mostly advisory and can be missing or there can be several PRs referring to the same issue, some of the PRs being incomplete. I understand that this is is a new feature, so it is not a regression?

**Comment by flolas** [comment]
Tested https://github.com/apache/airflow/issues/36948#:~:text=Implement%20AthenaSQLHook%20(%2336171).
Work as expected.

Env: Amazon MWAA [v2.7.2](https://pypi.python.org/pypi/apache-airflow/2.7.2) Instance.

Steps:
(1) Started a fresh MWAA instance

(2) Added to requirements [amazon: 8.17.0rc1](https://pypi.org/project/apache-airflow-providers-amazon/8.17.0rc1), also bump constrains:
```bash
apache-airflow-providers-amazon==8.17.0rc1
boto3==1.33.0
botocore==1.33.0
s3transfer==0.8.0
redshift_connector==2.0.918
```
(3) Created connection `athena_default` with extras
```json
{
  "work_group": "primary",
  "region_name": "us-east-1"
}
```
(4) Created connection `athena_assumed_role` with extras
```json
{
  "work_group": "primary",
  "region_name": "us-east-1",
  "role_arn": "arn:aws:iam::xxxxxxxxx:role/athena-access"
}
```
(5) Test  DAG
```python
create_sql_table1 = SQLExecuteQueryOperator(
            task_id="create_sql_table",
            conn_id='athena_default',
            sql='SELECT 1;SELECT 2;SELECT 3;SELECT 4',
            split_statements=True,
            dag=dag,
        )
create_sql_table2 = SQLExecuteQueryOperator(
            task_id="create_sql_table",
            conn_id='athena_assumed_role',
            sql='SELECT 1;SELECT 2;SELECT 3;SELECT 4',
            split_statements=True,
            dag=dag,
        )
create_sql_table1 >> create_sql_table2
```

**Comment by vizeit** [comment]
> > Opened #37001 with the fix and unit tested
> 
> Cool. Yep. that's ok. In Airlfow `PR` is the `unit of work` - not issue, issue is mostly advisory and can be missing or there can be several PRs referring to the same issue, some of the PRs being incomplete. I understand that this is is a new feature, so it is not a regression?

Yes, this is a new feature

**Comment by eladkal** [comment]
> Yes, this is a new feature

So I will not issue RC2 as this release has many new features that we shouldnt hold. The fix will be released in the next wave

**Comment by Taragolis** [comment]
- https://github.com/apache/airflow/pull/36675 raise an error in Airflow versions where `logger_name` not implemented in  `LoggingMixin` class constructor yet

Error which raised on Airflow 2.6.3

```console
[2024-01-25, 08:29:34 UTC] Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/slack/operators/slack.py", line 258, in execute
    self._method_resolver(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/slack/operators/slack.py", line 254, in _method_resolver
    return self.hook.send_file
  File "/usr/local/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/slack/operators/slack.py", line 82, in hook
    return SlackHook(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/slack/hooks/slack.py", line 117, in __init__
    super().__init__(logger_name=extra_client_args.pop("logger_name", None))
TypeError: LoggingMixin.__init__() got an unexpected keyword argument 'logger_name'
```

I guess this affects only providers which explicitly propagate, something like `super().__init__(logger_name=kwargs.pop("logger_name", None))`:
- [mongo: 3.6.0rc1](https://pypi.org/project/apache-airflow-providers-mongo/3.6.0rc1)
- [segment: 3.5.0rc1](https://pypi.org/project/apache-airflow-providers-segment/3.5.0rc1)
- [slack: 8.6.0rc1](https://pypi.org/project/apache-airflow-providers-slack/8.6.0rc1)
- [common.sql: 1.11.0rc1](https://pypi.org/project/apache-airflow-providers-common-sql/1.11.0rc1)

cc: @eladkal @hussein-awala

**Comment by Taragolis** [comment]
- https://github.com/apache/airflow/pull/36851: Check that cloudwatch remote logger now fallback to the default value even if it not explicitly set, and in Airflow versions before configurations started loads from the providers
- https://github.com/apache/airflow/pull/36757: Work with both file delivery methods

Do simple test for migration AWS operators/sensors/triggerers to base classes. Works fine, however for most the classes I've check only the instantiating objects  
- https://github.com/apache/airflow/pull/36772
- https://github.com/apache/airflow/pull/36764
- https://github.com/apache/airflow/pull/36765
- https://github.com/apache/airflow/pull/36776
- https://github.com/apache/airflow/pull/36766
- https://github.com/apache/airflow/pull/36770
- https://github.com/apache/airflow/pull/36771

**Comment by potiuk** [comment]
> I guess this affects only providers which explicitly propagate, something like super().__init__(logger_name=kwargs.pop("logger_name", None)):

[mongo: 3.6.0rc1](https://pypi.org/project/apache-airflow-providers-mongo/3.6.0rc1)
[segment: 3.5.0rc1](https://pypi.org/project/apache-airflow-providers-segment/3.5.0rc1)
[slack: 8.6.0rc1](https://pypi.org/project/apache-airflow-providers-slack/8.6.0rc1)
[common.sql: 1.11.0rc1](https://pypi.org/project/apache-airflow-providers-common-sql/1.11.0rc1)

Yes. Looks like the #34964 that introduced the logger_name had a hidden back-compatibility issue and we simply can't pass loggger_name for airflow < 2.8.0 . I guess we should remove these providers and only pass logger_name from our providers conditionally  (and add pre-commit for that).

Smth like:

```python
if packaging.version.parse(packaging.version.parse(airflow_version).base_version) < packaging.version.parse(
    "2.8.0"
):
    super().__init__()
else:
     super().__init__(logger_name=kwargs.pop("logger_name", None))
```

**Comment by Taragolis** [comment]
Or it might be something like that for avoid parsing version

```python
extra_kwargs = {}
if logger_name := kwargs.pop("logger_name", None):
    extra_kwargs["logger_name"] = logger_name
super().__init__(**extra_kwargs)
```

**Comment by potiuk** [comment]
The first approach  - the difference in the first case is that you can use same DAG / Operator for different Airlfow versions. The second one depends on how you use it - so for example you would not be able to have operator with logger_name that will work both pre- and post- 2.8.0  (unless you do version check in the operator)

**Comment by Taragolis** [comment]
My proposed fix it is just for avoid provide `logger_name` implicitly even if it not defined. If we would like to check version than we need to make fixes in all providers. 

In general usage users can't use/define attributes which not available into the BaseOperator / BaseHook for particular version. 
For example users can't define `schedule="@once"` and expect that it should work into the Airflow 2.3. The same here if user define `logger_name`  in Airflow < 2.8 then well it just won't work because feature only available in Airflow 2.8.

**Comment by potiuk** [comment]
> My proposed fix it is just for avoid provide logger_name implicitly even if it not defined. If we would like to check version than we need to make fixes in all providers.

I understand - but the thing is that our Hooks are mostly used internally by Operators and both Hooks and opertors are relased in providers, so there is a risk that someone will add an Operator that will initialize Hook with logger_name (which might be then exposed by or even hard-coded in the operator) . By implementing a protection against it in Hook, we allow such change to happen without waiting for min-airflow >= 2.8.0.

In other words - our code in Airflow that uses hooks - will not be able to use the `logger_name` in any way if we do it the way you proposed. We will not be able to release an Operator which will adds the option of specifying it - you will only be able to specify the `logger_name" directly in the DAG code were Hooks are used directly or when users would like to develop custom operators and they are **100% sure** the operator will be used in airflow 2.8.0+. Maybe that's what we want to do, but I think it is limiting. So for example if someone develops custom provider, that might use (say) common.sql  DBApiHook. They will have to add "apache-airflow>=2.8.0" if their Operator will pass "logger_name" to the hook.

The first proposal will work in all cases. It will only propagate logger_name to Base Hook in Airflow 2.8.0 - and will set no limitations on the users of the Hook to **know** they are run in Airflow 2.8.0 environment. You might just write custom operator (or we can implement it in our operators) to specify logger_name and it will work, regardless of what "airflow version" the operator is installed at. So in the above example - if somoene would like to create their own provider and use "DBApiHook" they will be able to create an operator that will use it it and pass "logger_name" = "mylogger" to it (and they will not have to add `apache-airlfow>= 2.8.0` in their provider.

**Comment by Taragolis** [comment]
Then we need to add this fix into the all providers affected by https://github.com/apache/airflow/pull/36675 (all?) or revert it for now. Depend on what is faster. In any cases we need to prepare rc2 for all providers I guess

**Comment by potiuk** [comment]
@eladkal asked me to take over from here as he is flying tonight. I thought a bit about it and agree with @Taragolis that reverting #36675 is the best way to approach this - including re-releasing RC2 with accelerated voting (and implementing better support for logger_name) for the next wave.

**Comment by vizeit** [comment]
@potiuk would re-releasing RC2 include cncf.Kubernetes provider? @eladkal said in his last comment for my PR #37001 that he will not release rc2 but include it in the next wave. With this recent change of rc2 re-releasing, would that be possible to reconsider and include #37001 in this re-releasing or not possible? I have been trying to get it approved by the listed reviewers but no luck so far. Please advise

**Comment by potiuk** [comment]
> @potiuk would re-releasing RC2 include cncf.Kubernetes provider? @eladkal said in his last comment for my PR #37001 that he will not release rc2 but include it in the next wave. With this recent change of rc2 re-releasing, would that be possible to reconsider and include #37001 in this re-releasing or not possible? I have been trying to get it approved by the listed reviewers but no luck so far. Please advise

Yep. Included it.

**Comment by vizeit** [comment]
> > @potiuk would re-releasing RC2 include cncf.Kubernetes provider? @eladkal said in his last comment for my PR #37001 that he will not release rc2 but include it in the next wave. With this recent change of rc2 re-releasing, would that be possible to reconsider and include #37001 in this re-releasing or not possible? I have been trying to get it approved by the listed reviewers but no luck so far. Please advise
> 
> Yep. Included it.

Thanka a lot!

**Comment by potiuk** [comment]
Hey Everyone - the issue is updated with new RC candidates and I am calling for another vote in a moment. Let's continue testing here!

**Comment by potiuk** [comment]
I kept the status from previous tests BTW

**Comment by listik** [comment]
#36813 tested and working ✅

**Comment by potiuk** [comment]
Thank you everyone. Providers are released!

I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
