### ISSUE TITLE
Status of testing Providers that were prepared on January 30, 2024

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#37102]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [microsoft.azure: 9.0.0rc1](https://pypi.org/project/apache-airflow-providers-microsoft-azure/9.0.0rc1)
   - [x] [Fix WasbPrefixSensor arg inconsistency between sync and async mode (#36806)](https://github.com/apache/airflow/pull/36806): @Lee-W
   - [x] [add WasbPrefixSensorTrigger params breaking change to azure provider changelog (#36940)](https://github.com/apache/airflow/pull/36940): @Lee-W
   - [x] [Fix failed tasks are not detected in `AzureBatchHook` (#36785)](https://github.com/apache/airflow/pull/36785): @ArvidMartensRenson
   - [x] [Fix assignment of template field in `__init__` in `container_instances.py` (#36529)](https://github.com/apache/airflow/pull/36529): @romsharon98
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
   - [x] [Fix stacklevel in warnings.warn into the providers (#36831)](https://github.com/apache/airflow/pull/36831): @Taragolis

All users involved in the PRs:
@kacpermuda @ArvidMartensRenson @romsharon98 @Lee-W @Taragolis

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by Taragolis** [comment]
I've check my change and could confirm that it work as desired

**Comment by Lee-W** [comment]
I've checked my changes, and they work as expected.

**Comment by ArvidMartensRenson** [comment]
I can confirm that my changes work as expected.

**Comment by kacpermuda** [comment]
My changes also work as expected.

**Comment by romsharon98** [comment]
Checked my changes, looks good.

**Comment by eladkal** [comment]
Thank you everyone. Providers are released.

I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
