### ISSUE TITLE
Status of testing of Apache Airflow Helm Chart 1.12.0rc1

### ISSUE THREAD

**Issue by jedcunningham** [apache/airflow#37259]
We are kindly requesting that contributors to [Apache Airflow Helm Chart 1.12.0rc1](https://dist.apache.org/repos/dist/dev/airflow/helm-chart/1.12.0rc1) help test the RC.

Please let us know by commenting if the issue is addressed in the latest RC.

- [ ] [Upgrade pre-commits (#35033)](https://github.com/apache/airflow/pull/35033): @potiuk
- [ ] [Pick config statsd host from chart helpers (#35679)](https://github.com/apache/airflow/pull/35679): @siryur
     Linked issues:
     - [Airflow metrics config on the Helm Chart mismatch when `fullnameOveride` is provided (#35678)](https://github.com/apache/airflow/issues/35678)
- [ ] [Fix git-sync-init resources indent (#35824)](https://github.com/apache/airflow/pull/35824): @romsharon98
- [ ] [feat: support mysql backend as keda trigger (#36167)](https://github.com/apache/airflow/pull/36167): @claneys
     Linked issues:
     - [Also support mysql Keda trigger in scaledObject (#36166)](https://github.com/apache/airflow/issues/36166)
- [ ] [Enable native HPA for Airflow Workers (#36174)](https://github.com/apache/airflow/pull/36174): @pemiranda-clgx
- [ ] [Rebuild pgbouncer and pgbouncer-exporter images with newer versions (#36898)](https://github.com/apache/airflow/pull/36898): @potiuk
- [ ] [Chart: Default airflow version to 2.8.1 (#36907)](https://github.com/apache/airflow/pull/36907): @ephraimbuddy
- [ ] [Chart: update newsfragment pr number (#36913)](https://github.com/apache/airflow/pull/36913): @jedcunningham
- [ ] [Chart: Add warning about changing/adding metrics mappings (#36960)](https://github.com/apache/airflow/pull/36960): @jedcunningham
- [ ] [Added ability to enable/disable scheduler and webserver  (#36991)](https://github.com/apache/airflow/pull/36991): @kajanajustin

Thanks to all who contributed to the release (probably not a complete list!):
@jedcunningham @potiuk @kajanajustin @siryur @romsharon98 @ephraimbuddy @claneys @pemiranda-clgx @frankgrimes97 @shohamy7

**Comment by jedcunningham** [comment]
1.12.0 has been released!
