### ISSUE TITLE
Status of testing Providers that were prepared on February 12, 2024

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#37358]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 8.18.0rc1](https://pypi.org/project/apache-airflow-providers-amazon/8.18.0rc1)
   - [ ] [ECS Executor - Add backoff on failed task retry (#37109)](https://github.com/apache/airflow/pull/37109): @ferruzzi
   - [ ] [SqlToS3Operator: feat/ add max_rows_per_file parameter (#37055)](https://github.com/apache/airflow/pull/37055): @selimchergui
   - [x] [Adding Amazon Neptune Hook and Operators (#37000)](https://github.com/apache/airflow/pull/37000): @ellisms
   - [ ] [Fix `log_query` to format SQL statement correctly in `AthenaOperator` (#36962)](https://github.com/apache/airflow/pull/36962): @ferruzzi
   - [x] [check sagemaker training job status before deferring SageMakerTrainingOperator (#36685)](https://github.com/apache/airflow/pull/36685): @Lee-W
   - [ ] [Merge all ECS executor configs following recursive python dict update (#37137)](https://github.com/apache/airflow/pull/37137): @o-nikolas
   - [ ] [Update default value for `BatchSensor` (#37234)](https://github.com/apache/airflow/pull/37234): @vincbeck
   - [x] [Remove info log from amazon provider-> S3 Hook -> download_file (#37211)](https://github.com/apache/airflow/pull/37211): @rawwar
   - [ ] [feature: S3ToRedshiftOperator templating aws_conn_id (#37195)](https://github.com/apache/airflow/pull/37195): @raphaelauv
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
## Provider [apache.beam: 5.6.1rc1](https://pypi.org/project/apache-airflow-providers-apache-beam/5.6.1rc1)
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
## Provider [apache.drill: 2.6.1rc1](https://pypi.org/project/apache-airflow-providers-apache-drill/2.6.1rc1)
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
## Provider [apache.druid: 3.8.1rc1](https://pypi.org/project/apache-airflow-providers-apache-druid/3.8.1rc1)
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
## Provider [apache.hive: 7.0.0rc1](https://pypi.org/project/apache-airflow-providers-apache-hive/7.0.0rc1)
   - [ ] [ Simplify hive client connection (#37043)](https://github.com/apache/airflow/pull/37043): @romsharon98
   - [x] [Fix pyhive hive_pure_sasl extra name (#37323)](https://github.com/apache/airflow/pull/37323): @hussein-awala
## Provider [apache.livy: 3.7.2rc1](https://pypi.org/project/apache-airflow-providers-apache-livy/3.7.2rc1)
   - [x] [Bump aiohttp min version to avoid CVE-2024-23829 and CVE-2024-23334 (#37110)](https://github.com/apache/airflow/pull/37110): @hussein-awala
## Provider [apprise: 1.2.2rc1](https://pypi.org/project/apache-airflow-providers-apprise/1.2.2rc1)
   - [x] [Simplified configuration parsing in Apprise Connection (#37202)](https://github.com/apache/airflow/pull/37202): @infohash
## Provider [celery: 3.6.0rc1](https://pypi.org/project/apache-airflow-providers-celery/3.6.0rc1)
   - [x] [Add `task_acks_late` configuration to Celery Executor (#37066)](https://github.com/apache/airflow/pull/37066): @ninsbl
   - [ ] [prevent celery command autoscale misconfig (#36576)](https://github.com/apache/airflow/pull/36576): @Bowrna
## Provider [cncf.kubernetes: 8.0.0rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/8.0.0rc1)
   - [ ] [The task is stuck in a queued state forever in case of pod launch errors  (#36882)](https://github.com/apache/airflow/pull/36882): @dirrao
   - [ ] [Modify KPO to log container log periodically  (#37279)](https://github.com/apache/airflow/pull/37279): @pankajastro
   - [x] [Fix occasional attr-undefined for the python_kubernetes_script (#37318)](https://github.com/apache/airflow/pull/37318): @potiuk
   - [ ] [Fix hanging KPO on deferrable task with do_xcom_push (#37300)](https://github.com/apache/airflow/pull/37300): @vchiapaikeo
   - [x] [Fix rendering `SparkKubernetesOperator.template_body` (#37271)](https://github.com/apache/airflow/pull/37271): @Taragolis
   - [ ] [Fix assignment of template field in `__init__` in `KubernetesPodOperator` (#37010)](https://github.com/apache/airflow/pull/37010): @romsharon98
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
   - [ ] [Kubernetes version bump (#37040)](https://github.com/apache/airflow/pull/37040): @dirrao
## Provider [common.io: 1.3.0rc1](https://pypi.org/project/apache-airflow-providers-common-io/1.3.0rc1)
   - [ ] [AIP-58: Add object storage backend for xcom (#37058)](https://github.com/apache/airflow/pull/37058): @bolkedebruin
## Provider [common.sql: 1.11.0rc2](https://pypi.org/project/apache-airflow-providers-common-sql/1.11.0rc2)
   - [ ] [Enhancement: Performance enhancement for insert_rows method DbApiHook with fast executemany + SAP Hana support (#37246)](https://github.com/apache/airflow/pull/37246): @dabla
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
## Provider [databricks: 6.2.0rc1](https://pypi.org/project/apache-airflow-providers-databricks/6.2.0rc1)
   - [x] [Update DatabricksSqlOperator to work with namedtuple (#37025)](https://github.com/apache/airflow/pull/37025): @SuperBo
   - [x] [Bump aiohttp min version to avoid CVE-2024-23829 and CVE-2024-23334 (#37110)](https://github.com/apache/airflow/pull/37110): @hussein-awala
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
   - [x] [Get rid of pytest-httpx as dependency (#37334)](https://github.com/apache/airflow/pull/37334): @potiuk
## Provider [dbt.cloud: 3.6.1rc1](https://pypi.org/project/apache-airflow-providers-dbt-cloud/3.6.1rc1)
   - [x] [Bump aiohttp min version to avoid CVE-2024-23829 and CVE-2024-23334 (#37110)](https://github.com/apache/airflow/pull/37110): @hussein-awala
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
## Provider [elasticsearch: 5.3.3rc1](https://pypi.org/project/apache-airflow-providers-elasticsearch/5.3.3rc1)
   - [x] [Avoid `pendulum.from_timestamp` usage (#37160)](https://github.com/apache/airflow/pull/37160): @Taragolis
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
## Provider [google: 10.15.0rc1](https://pypi.org/project/apache-airflow-providers-google/10.15.0rc1)
   - [ ] [add service_file support to GKEPodAsyncHook (#37081)](https://github.com/apache/airflow/pull/37081): @Lee-W
   - [ ] [Update GCP Dataproc ClusterGenerator to support GPU params (#37036)](https://github.com/apache/airflow/pull/37036): @dmedora
   - [x] [Create DataprocStartClusterOperator and DataprocStopClusterOperator (#36996)](https://github.com/apache/airflow/pull/36996): @molcay
   - [x] [Implement deferrable mode for CreateHyperparameterTuningJobOperator (#36594)](https://github.com/apache/airflow/pull/36594): @moiseenkov
   - [ ] [Enable '_enable_tcp_keepalive' functionality for GKEPodHook (#36999)](https://github.com/apache/airflow/pull/36999): @MaksYermak
   - [ ] [fix how GKEPodAsyncHook.service_file_as_context is used (#37306)](https://github.com/apache/airflow/pull/37306): @Lee-W
   - [x] [Fix metadata override for ComputeEngineSSHHook (#37192)](https://github.com/apache/airflow/pull/37192): @molcay
   - [ ] [Fix assignment of template field in `__init__` in `custom_job` (#36789)](https://github.com/apache/airflow/pull/36789): @romsharon98
   - [ ] [Fix location requirement in DataflowTemplatedJobStartOperator (#37069)](https://github.com/apache/airflow/pull/37069): @shardbread
   - [ ] [Fix assignment of template field in `__init__` in `CloudDataTransferServiceCreateJobOperator` (#36909)](https://github.com/apache/airflow/pull/36909): @romsharon98
   - [x] [Fixed the hardcoded default namespace value for GCP Data Fusion links. (#35379)](https://github.com/apache/airflow/pull/35379): @synsh
   - [x] [Do not ignore the internal_ip_only if set to false in Dataproc cluster config (#37014)](https://github.com/apache/airflow/pull/37014): @ahzaz
   - [x] [Revert protection against back-compatibilty issue with google-core-api (#37111)](https://github.com/apache/airflow/pull/37111): @potiuk
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
## Provider [hashicorp: 3.6.3rc1](https://pypi.org/project/apache-airflow-providers-hashicorp/3.6.3rc1)
   - [x] [feat(hashicorp): Add `VAULT_TOKEN` support (#37337)](https://github.com/apache/airflow/pull/37337): @V0lantis
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
## Provider [http: 4.9.1rc1](https://pypi.org/project/apache-airflow-providers-http/4.9.1rc1)
   - [x] [Bump aiohttp min version to avoid CVE-2024-23829 and CVE-2024-23334 (#37110)](https://github.com/apache/airflow/pull/37110): @hussein-awala
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
   - [x] [Get rid of pytest-httpx as dependency (#37334)](https://github.com/apache/airflow/pull/37334): @potiuk
## Provider [influxdb: 2.4.1rc1](https://pypi.org/project/apache-airflow-providers-influxdb/2.4.1rc1)
   - [x] [Get rid of pytest-httpx as dependency (#37334)](https://github.com/apache/airflow/pull/37334): @potiuk
## Provider [jdbc: 4.2.2rc1](https://pypi.org/project/apache-airflow-providers-jdbc/4.2.2rc1)
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
## Provider [microsoft.mssql: 3.6.1rc1](https://pypi.org/project/apache-airflow-providers-microsoft-mssql/3.6.1rc1)
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
## Provider [mongo: 4.0.0rc1](https://pypi.org/project/apache-airflow-providers-mongo/4.0.0rc1)
   - [x] [Adding certificate validation for ssl in mongo hook (#37214)](https://github.com/apache/airflow/pull/37214): @amoghrajesh
   - [x] [Change `MongoHook.conn_name_attr` to `mongo_conn_id` (#37104)](https://github.com/apache/airflow/pull/37104): @Taragolis
   - [ ] [Change docs type in insert_many to list of dicts (#37230)](https://github.com/apache/airflow/pull/37230): @MezentsevIlya
## Provider [mysql: 5.5.3rc1](https://pypi.org/project/apache-airflow-providers-mysql/5.5.3rc1)
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
## Provider [oracle: 3.9.2rc1](https://pypi.org/project/apache-airflow-providers-oracle/3.9.2rc1)
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
## Provider [pagerduty: 3.6.2rc1](https://pypi.org/project/apache-airflow-providers-pagerduty/3.6.2rc1)
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
## Provider [postgres: 5.10.1rc1](https://pypi.org/project/apache-airflow-providers-postgres/5.10.1rc1)
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
## Provider [qdrant: 1.0.0rc1](https://pypi.org/project/apache-airflow-providers-qdrant/1.0.0rc1)
   - [x] [Add Qdrant Provider (#36805)](https://github.com/apache/airflow/pull/36805): @Anush008
## Provider [sftp: 4.9.0rc1](https://pypi.org/project/apache-airflow-providers-sftp/4.9.0rc1)
   - [x] [Add deferrable param in SFTPSensor (#37117)](https://github.com/apache/airflow/pull/37117): @utkarsharma2
## Provider [slack: 8.6.1rc1](https://pypi.org/project/apache-airflow-providers-slack/8.6.1rc1)
   - [x] [Remove the remaining references to use the token bypassing the Connection in the Slack provider. (#37112)](https://github.com/apache/airflow/pull/37112): @Taragolis
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
## Provider [snowflake: 5.3.1rc1](https://pypi.org/project/apache-airflow-providers-snowflake/5.3.1rc1)
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
## Provider [sqlite: 3.7.1rc1](https://pypi.org/project/apache-airflow-providers-sqlite/3.7.1rc1)
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
## Provider [ssh: 3.10.1rc1](https://pypi.org/project/apache-airflow-providers-ssh/3.10.1rc1)
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
## Provider [tableau: 4.4.2rc1](https://pypi.org/project/apache-airflow-providers-tableau/4.4.2rc1)
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
## Provider [trino: 5.6.2rc1](https://pypi.org/project/apache-airflow-providers-trino/5.6.2rc1)
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
## Provider [vertica: 3.7.1rc1](https://pypi.org/project/apache-airflow-providers-vertica/3.7.1rc1)
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
## Provider [weaviate: 1.3.2rc1](https://pypi.org/project/apache-airflow-providers-weaviate/1.3.2rc1)
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
## Provider [yandex: 3.9.0rc1](https://pypi.org/project/apache-airflow-providers-yandex/3.9.0rc1)
   - [x] [Add secrets-backends section into the Yandex provider yaml definition (#37065)](https://github.com/apache/airflow/pull/37065): @Taragolis
   - [ ] [fix: using endpoint from connection if not specified (#37076)](https://github.com/apache/airflow/pull/37076): @ImpressionableRaccoon

All users involved in the PRs:
@ellisms @moiseenkov @synsh @Anush008 @infohash @shardbread @raphaelauv @hussein-awala @molcay @pankajastro @selimchergui @dabla @rawwar @SuperBo @ninsbl @V0lantis @kacpermuda @ahzaz @dirrao

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by eladkal** [comment]
> @potiuk , @eladkal , hi, Could we please include #37282 into the release?

If PR missed cut off time there is no option to add it. It will have to wait for next release / RC2 if we will have one.

**Comment by pankajkoti** [comment]
Observing an issue with [common.sql: 1.11.0rc2](https://pypi.org/project/apache-airflow-providers-common-sql/1.11.0rc2)

Posted a [question](https://github.com/apache/airflow/pull/37246#discussion_r1486120101) on the PR

**Comment by potiuk** [comment]
> Observing an issue with [common.sql: 1.11.0rc2](https://pypi.org/project/apache-airflow-providers-common-sql/1.11.0rc2)
> 
> Posted a [question](https://github.com/apache/airflow/pull/37246#discussion_r1486120101) on the PR

Nice catch @pankajkoti

**Comment by pankajkoti** [comment]
> Nice catch @pankajkoti

Actually, it was the (Astronomer) Providers RC automation test suite that reported this failure :) 
Thank you @potiuk for providing the fix PR https://github.com/apache/airflow/pull/37359 so quick. Appreciate it 🙏🏽

**Comment by infohash** [comment]
* gh-37202 is working with Provider [apprise: 1.2.2rc1](https://pypi.org/project/apache-airflow-providers-apprise/1.2.2rc1)

**Comment by vchiapaikeo** [comment]
https://github.com/apache/airflow/pull/37300 looks good. Also, @Lee-W , thank you for that fix to GKE providers.

However, I have deferrable tasks that should be completing that are not completing due to https://github.com/apache/airflow/pull/37279. Will comment on the PR there.

**Comment by pankajastro** [comment]
> However, I have deferrable tasks that should be completing that are not completing due to https://github.com/apache/airflow/pull/37279. Will comment on the PR there. cc @pankajastro @pankajkoti

Thanks for testing it. please share the DAG and other details if possible.

**Comment by ninsbl** [comment]
Hmm... I am struggeling to build a recent version of Airflow with `celery 3.6.0rc1`. The issue seems unrelated to the changes in the provider. I tried to build a container with 2.9.0 but there FAB provider seems to be missing / not installable...

**Comment by potiuk** [comment]
> Hmm... I am struggeling to build a recent version of Airflow with `celery 3.6.0rc1`. The issue seems unrelated to the changes in the provider. I tried to build a container with 2.9.0 but there FAB provider seems to be missing / not installable...

Yes. FAB provider and Airflow 2.9.0 are not yet usable to install. We might want to change that and release FAB provider in the next wave

**Comment by potiuk** [comment]
Added https://github.com/apache/airflow/pull/37362 to make the provider "ready" (we will need to do it when we come closer to 2.9.0 release.

**Comment by ellisms** [comment]
#37000 is good.

**Comment by kacpermuda** [comment]
I tested a random sample of changes from #36876 and it works OK. The PR simply changed the warnings.warn to decorator.

**Comment by amoghrajesh** [comment]
Tried out https://github.com/apache/airflow/pull/37214 using some sample DAGs in breeze environment. Looks good 👍🏽

**Comment by rawwar** [comment]
Tried out #37211 

amazon provider - 8.17.0:
![image](https://github.com/apache/airflow/assets/20266953/f96c054b-a6fe-4021-a0e5-ecfa5a76c23b)

amazon provider - 8.18.0rc1:
![image](https://github.com/apache/airflow/assets/20266953/f727596c-51d6-4c88-a06f-9a74e408a2a9)


Log is no longer printed. hence, working as expected.

**Comment by V0lantis** [comment]
Tried out #37337 <https://github.com/apache/airflow/pull/37337>, works like
a charm.

Provider apache-airflow-providers-hashicorp==3.6.3rc1

**Comment by hussein-awala** [comment]
Tested #37110 and #37323 and they both work as expected.

**Comment by o-nikolas** [comment]
While testing #37137 I encountered an unexpected behaviour with the ECS executor not retrying on failures. I don't think it was caused by this change, it's a separate regression I believe. However, this executor is still experimental so I'm not sure it should block this release.
CC @ferruzzi @syedahsn @shubham22

**Comment by potiuk** [comment]
Checked all my changes. LGTM.

**Comment by Lee-W** [comment]
https://github.com/apache/airflow/pull/36685 doesn't work as expected. It stucks somehow. Will take a deeper look these days.

https://github.com/apache/airflow/pull/37306 and https://github.com/apache/airflow/pull/37081 works fine without [cncf.kubernetes: 8.0.0rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/8.0.0rc1) Looks like https://github.com/apache/airflow/pull/37279#issuecomment-1938782796 is the root cause

**Comment by Anush008** [comment]
> Provider [qdrant: 1.0.0rc1](https://pypi.org/project/apache-airflow-providers-qdrant/1.0.0rc1)
 https://github.com/apache/airflow/pull/36805
 
Tested the DAGs. Works.

**Comment by Anush008** [comment]
> Provider [qdrant: 1.0.0rc1](https://pypi.org/project/apache-airflow-providers-qdrant/1.0.0rc1)
 https://github.com/apache/airflow/pull/36805
 
Tested DAGs. Works.

**Comment by eladkal** [comment]
Providers `amazon`, `cncf.kubernetes` and `common.sql` will be excluded from RC1.

**Comment by Taragolis** [comment]
> However it raises error with xcom enabled when serializing named tuple to json.

Serializing named tuple should be add into the core first, e.g. it might be added by https://github.com/apache/airflow/pull/37168

**Comment by Taragolis** [comment]
Checked all my changes, looking good

**Comment by ahzaz** [comment]
#37014 works as expected.

**Comment by pankajkoti** [comment]
#37117 works as expected

**Comment by utkarsharma2** [comment]
Tested Add deferrable param in SFTPSensor (#37117)
<https://github.com/apache/airflow/pull/37117> and Fix metadata override
for ComputeEngineSSHHook (#37192)
<https://github.com/apache/airflow/pull/37192>: @molcay
<https://github.com/molcay> works as expected.

Thanks,
Utkarsh Sharma

**Comment by raphaelauv** [comment]
` Fix hanging KPO on deferrable task with do_xcom_push (#37300): @vchiapaikeo`
 
 work :+1:

**Comment by pankajastro** [comment]
> However, I have deferrable tasks that should be completing that are not completing due to #37279. Will comment on the PR there. cc @pankajastro @pankajkoti
> 
> Link to comment: [#37279 (comment)](https://github.com/apache/airflow/pull/37279#issuecomment-1938757838)

Hey @vchiapaikeo would it be possible for you to test https://github.com/apache/airflow/pull/37363 with your use case?

**Comment by eladkal** [comment]
> However, this executor is still experimental so I'm not sure it should block this release.

Since we are having RC2 for amazon provider there is time to fix it if you can raise a PR?

**Comment by ninsbl** [comment]
#37066 Seems to work fine. The environment variable is acknowledged in the airflow config and long running tasks have been finnishing successfull with Celery 3.6.0rc1.

**Comment by Lee-W** [comment]
> #36685 doesn't work as expected. It stucks somehow. Will take a deeper look these days.
> 
> #37306 and #37081 works fine without [cncf.kubernetes: 8.0.0rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/8.0.0rc1) Looks like [#37279 (comment)](https://github.com/apache/airflow/pull/37279#issuecomment-1938782796) is the root cause

I tested #36685 a few more times today. The issue can no longer be reproduced.

**Comment by eladkal** [comment]
Thank you everyone. Providers are released.

Providers: `amazon`, `common.sql`, `cncf.kubernetes` were excluded from this release.

I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
