### ISSUE TITLE
Status of testing Providers that were prepared on February 17, 2024

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#37504]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 8.18.0rc2](https://pypi.org/project/apache-airflow-providers-amazon/8.18.0rc2)
   - [ ] [ECS Executor - Add backoff on failed task retry (#37109)](https://github.com/apache/airflow/pull/37109): @ferruzzi
   - [ ] [SqlToS3Operator: feat/ add max_rows_per_file parameter (#37055)](https://github.com/apache/airflow/pull/37055): @selimchergui
   - [x] [Adding Amazon Neptune Hook and Operators (#37000)](https://github.com/apache/airflow/pull/37000): @ellisms
   - [ ] [Add retry configuration in `EmrContainerOperator` (#37426)](https://github.com/apache/airflow/pull/37426): @vincbeck
   - [ ] [Create CLI commands for AWS auth manager to create AWS Identity Center related resources (#37407)](https://github.com/apache/airflow/pull/37407): @vincbeck
   - [x] [Add extra operator links for EMR Serverless (#34225)](https://github.com/apache/airflow/pull/34225): @dacort
   - [ ] [Fix `log_query` to format SQL statement correctly in `AthenaOperator` (#36962)](https://github.com/apache/airflow/pull/36962): @ferruzzi
   - [x] [check sagemaker training job status before deferring SageMakerTrainingOperator (#36685)](https://github.com/apache/airflow/pull/36685): @Lee-W
   - [ ] [Merge all ECS executor configs following recursive python dict update (#37137)](https://github.com/apache/airflow/pull/37137): @o-nikolas
   - [ ] [Update default value for `BatchSensor` (#37234)](https://github.com/apache/airflow/pull/37234): @vincbeck
   - [x] [Remove info log from amazon provider-> S3 Hook -> download_file (#37211)](https://github.com/apache/airflow/pull/37211): @rawwar
   - [ ] [feature: S3ToRedshiftOperator templating aws_conn_id (#37195)](https://github.com/apache/airflow/pull/37195): @raphaelauv
   - [ ] [Updates to ECS Executor Docs (#37125)](https://github.com/apache/airflow/pull/37125): @o-nikolas
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
   - [x] [Replace usage of `datetime.utcnow` and `datetime.utcfromtimestamp` in providers (#37138)](https://github.com/apache/airflow/pull/37138): @Taragolis
   - [x] [add type annotations to Amazon provider "execute_coplete" methods (#36330)](https://github.com/apache/airflow/pull/36330): @Lee-W
## Provider [cncf.kubernetes: 8.0.0rc2](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/8.0.0rc2)
   - [ ] [The task is stuck in a queued state forever in case of pod launch errors  (#36882)](https://github.com/apache/airflow/pull/36882): @dirrao
   - [ ] [Modify KPO to log container log periodically  (#37279)](https://github.com/apache/airflow/pull/37279): @pankajastro
   - [ ] [Create GKEStartJobOperator and KubernetesJobOperator (#36847)](https://github.com/apache/airflow/pull/36847): @MaksYermak
   - [x] [Fix occasional attr-undefined for the python_kubernetes_script (#37318)](https://github.com/apache/airflow/pull/37318): @potiuk
   - [x] [Fix hanging KPO on deferrable task with do_xcom_push (#37300)](https://github.com/apache/airflow/pull/37300): @vchiapaikeo
   - [x] [Fix rendering `SparkKubernetesOperator.template_body` (#37271)](https://github.com/apache/airflow/pull/37271): @Taragolis
   - [x] [Fix assignment of template field in `__init__` in `KubernetesPodOperator` (#37010)](https://github.com/apache/airflow/pull/37010): @romsharon98
   - [x] [KPO Maintain backward compatibility for execute_complete and trigger run method (#37454)](https://github.com/apache/airflow/pull/37454): @pankajastro
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
   - [ ] [Add GKEStartKueueInsideClusterOperator to support Kueue inside clusters (#37072)](https://github.com/apache/airflow/pull/37072): @VladaZakharova
   - [ ] [Convert Kubernetes ApiException status code to string to ensure it's correctly checked (#37405)](https://github.com/apache/airflow/pull/37405): @hussein-awala
   - [ ] [KPO Maintain backward compatibility for execute_complete and trigger run method (#37363)](https://github.com/apache/airflow/pull/37363): @pankajastro
## Provider [common.sql: 1.11.0rc3](https://pypi.org/project/apache-airflow-providers-common-sql/1.11.0rc3)
   - [ ] [Enhancement: Performance enhancement for insert_rows method DbApiHook with fast executemany + SAP Hana support (#37246)](https://github.com/apache/airflow/pull/37246): @dabla
   - [x] [Fix SQLThresholdCheckOperator error on falsey vals (#37150)](https://github.com/apache/airflow/pull/37150): @Don-Burns
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
   - [x] [Add more-itertools as dependency of common-sql (#37359)](https://github.com/apache/airflow/pull/37359): @potiuk

All users involved in the PRs:
@ellisms @potiuk @vincbeck @rawwar @MaksYermak @Don-Burns @Lee-W @kacpermuda @Taragolis @dacort @vchiapaikeo @romsharon98 @hussein-awala @ferruzzi @raphaelauv @dirrao @pankajastro @dabla @VladaZakharova

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by eladkal** [comment]
I marked all items that were tested in RC1 https://github.com/apache/airflow/issues/37358 as tested here too but feel free to retest them.

**Comment by vchiapaikeo** [comment]
Thanks so much @eladkal, @potiuk, and @pankajastro for getting this fixed and prepped so quickly. https://github.com/apache/airflow/pull/37300 still looks good. 

I found a subtle bug with the trigger_reentry refactor, but I don't think it should block the release by any means. Sorry for missing this in testing earlier! I put out a PR for it here: https://github.com/apache/airflow/pull/37508

**Comment by Lee-W** [comment]
Tested both providers with our example DAGs without encountering an error. Verified https://github.com/apache/airflow/pull/36330

**Comment by dacort** [comment]
Confirmed #34225

**Comment by potiuk** [comment]
Checked #37359 -> all good.

**Comment by Taragolis** [comment]
Checked: https://github.com/apache/airflow/pull/37138

**Comment by Don-Burns** [comment]
Checked: #37150: Working as intended.

**Comment by eladkal** [comment]
provider cncf.kubernetes will be excluded from this release due to bug found

**Comment by eladkal** [comment]
Thank you everyone. Providers are released.
`cncf.kubernetes` is excluded and RC3 will follow shortly.

I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
