### ISSUE TITLE
Status of testing Providers that were prepared on February 19, 2024

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#37534]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [cncf.kubernetes: 8.0.0rc3](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/8.0.0rc3)
   - [ ] [The task is stuck in a queued state forever in case of pod launch errors  (#36882)](https://github.com/apache/airflow/pull/36882): @dirrao
   - [x] [Modify KPO to log container log periodically  (#37279)](https://github.com/apache/airflow/pull/37279): @pankajastro
   - [x] [Create GKEStartJobOperator and KubernetesJobOperator (#36847)](https://github.com/apache/airflow/pull/36847): @MaksYermak
   - [x] [Fix occasional attr-undefined for the python_kubernetes_script (#37318)](https://github.com/apache/airflow/pull/37318): @potiuk
   - [x] [Fix hanging KPO on deferrable task with do_xcom_push (#37300)](https://github.com/apache/airflow/pull/37300): @vchiapaikeo
   - [x] [Fix rendering `SparkKubernetesOperator.template_body` (#37271)](https://github.com/apache/airflow/pull/37271): @Taragolis
   - [x] [Fix assignment of template field in `__init__` in `KubernetesPodOperator` (#37010)](https://github.com/apache/airflow/pull/37010): @romsharon98
   - [x] [KPO Maintain backward compatibility for execute_complete and trigger run method (#37454)](https://github.com/apache/airflow/pull/37454): @pankajastro
   - [x] [Fix KPO task hanging when pod fails to start within specified timeout (#37514)](https://github.com/apache/airflow/pull/37514): @pankajkoti
   - [x] [Fix KeyError when KPO exits too soon (#37508)](https://github.com/apache/airflow/pull/37508): @vchiapaikeo
   - [x] [Standardize deprecations in providers [part1] (#36876)](https://github.com/apache/airflow/pull/36876): @kacpermuda
   - [ ] [Kubernetes version bump (#37040)](https://github.com/apache/airflow/pull/37040): @dirrao
   - [x] [Add GKEStartKueueInsideClusterOperator to support Kueue inside clusters (#37072)](https://github.com/apache/airflow/pull/37072): @VladaZakharova
   - [ ] [Convert Kubernetes ApiException status code to string to ensure it's correctly checked (#37405)](https://github.com/apache/airflow/pull/37405): @hussein-awala
   - [x] [KPO Maintain backward compatibility for execute_complete and trigger run method (#37363)](https://github.com/apache/airflow/pull/37363): @pankajastro

All users involved in the PRs:
@MaksYermak @pankajkoti @Taragolis @potiuk @kacpermuda @VladaZakharova @hussein-awala @romsharon98 @vchiapaikeo @dirrao @pankajastro

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by eladkal** [comment]
I marked all items that were tested in RC2 https://github.com/apache/airflow/issues/37504 as tested here too but feel free to retest them.

**Comment by pankajastro** [comment]
Tested my changes. looking good. Thanks for the RC's

**Comment by vchiapaikeo** [comment]
https://github.com/apache/airflow/pull/37508 looks good. Thank you! 🙇

**Comment by raphaelauv** [comment]
logging_interval is at None by default in the 8.0.0 is that voluntary ?

would be more friendly for users that we have this , wdyt  ( I was surprise to not see logs anymore in airflow for my pod ) ?

```python
if get_logs:
    if logging_interval is None:
        logging_interval = 10
```

**Comment by pankajastro** [comment]
> I was surprise to not see logs anymore in airflow for my pod

That should not be the case. If the logging interval is none then you will see logs at the end of a task execution.

**Comment by raphaelauv** [comment]
sorry I was not explicit 

I was surprise to not see logs anymore in airflow for my pod during the run of the pod cause I have the option get_logs at true

**Comment by pankajkoti** [comment]
@raphaelauv I believe `get_logs` was only meant to fetch logs at the end of the pod completion and so is also the case now. 

I guess what you mean is the missing logs in trigger showing that the container is not yet finished and that the trigger is polling with sleep that we were seeing earlier. I have created a PR to show those logs https://github.com/apache/airflow/pull/37546.

The good point now is that with setting logging_interval, we now would also be able to periodically fetch logs from the pod itself to show what's happening inside the pod.
I understand we now have less logs at the moment by default, however, I am unsure if we should call for cancelling the RC for these missing informative logs. WDYT?

**Comment by vchiapaikeo** [comment]
Agree with @pankajkoti that this was also the behavior previously. For deferrable tasks, logs were fetched and sent at the end (on pod completion) to the task. New commits included in this RC now allow us to modify this behavior and fetch logs periodically.

If deferrable is set to false, the behavior of get_logs is synchronous and logs will be streamed to the task.

**Comment by raphaelauv** [comment]
in 7.1.4 with only `get_logs =true `

it fetch the logs regularly when the pod is running 

in 8.0.0rc3 with only `get_logs =true`

it fetch the logs only at the end

---
users will be surprise

**Comment by pankajkoti** [comment]
Yes, I agree there will be no informative logs in RC3 from the triggerer saying the container is still running.

However, the trigger logs are independent of get_logs (even if we set it to False  we will see the same diff between 7.1.4 and 8.0.0RC3). 

In the case of deferrable mode, with 7.1.4, get_logs is relevant only for fetching logs from within the pod and at the end of pod completion. It is not relevant while the pod is still running. While the pod is still running, we get logs from trigger saying the container is still running and it's going to sleep. This is independent of get_logs.

**Comment by pankajastro** [comment]
@raphaelauv I'm a bit confused now. Sorry!. Do you mean container log is not visible regularly or the log statement something like "container is still running/pending" when trigger loop is running.
 
- We has been just `logging_interval`  in this RC and it is None by default.
- Container logs was not available earlier regularly
- Logging statement like "container is still running/pending" when trigger trigger is running should not have anything to do with param `get_logs`

**Comment by raphaelauv** [comment]
"Container logs was not available earlier regularly"

That's wrong, the kpo with get_logs , get the container logs regularly

**Comment by pankajkoti** [comment]
> "Container logs was not available earlier regularly"
> 
> That's wrong, the kpo with get_logs , get the container logs regularly

@raphaelauv It was not possible to get logs from within the container previously in `deferrable` mode while the **pod was still running**. They only appear after the pod completes it's execution. I think we're not on the same page when we say "container logs"

with 8.0.0RC3 you might want to try below example task in your DAG
```
create_k8s_pod = KubernetesPodOperator(
        task_id="create_k8s_pod",
        namespace=namespace,
        in_cluster=in_cluster,
        config_file=config_file,
        name="k8s_test_pod",
        deferrable=True,
        logging_interval=10,
        # startup_timeout_seconds=60,
        image="ubuntu",
        cmds=[
            "bash",
            "-cx",
            (
                "i=0; "
                "while [ $i -ne 150 ]; "
                "do i=$(($i+1)); "
                "echo $i; "
                "sleep 1; "
                "done; "
                "mkdir -p /airflow/xcom/; "
                'echo \'{"message": "good afternoon!"}\' > /airflow/xcom/return.json'
            ),
        ],
        do_xcom_push=True,
    )
```

and you can try to run the same task without the `logging_interval` parameter with 7.14.0 (as 7.14.0 did not have this param).

You will observe that you won't see logs from the echo command above periodically in 7.14.0 while the pod is running. You will only see them at the end.

**Comment by raphaelauv** [comment]
I'm not speaking about the deferrable mode

**Comment by pankajkoti** [comment]
> I'm not speaking about the deferrable mode

Okay, :). The `logging_interval` param that you pointed at [earlier](https://github.com/apache/airflow/issues/37534#issuecomment-1952355153) that has been introduced only gets used for deferrable mode. It does not concern synchronous/non-deferrable mode. 

And I checked both 7.14.0 and 8.0.0RC3 for synchronous (non-deferrable mode) and I do not see any diff, I can see that 8.0.0RC3 is able to show pogs logs when the pod is still running

<img width="977" alt="Screenshot 2024-02-20 at 12 55 29 AM" src="https://github.com/apache/airflow/assets/10206082/81082d49-9cd1-4af0-83ac-fc2954948b2b">

<img width="917" alt="Screenshot 2024-02-20 at 12 55 46 AM" src="https://github.com/apache/airflow/assets/10206082/1ccea7b1-013e-49db-a4b9-35eb803209a0">

**Comment by pankajastro** [comment]
Still not sure, `logging_interval` is a new param in 8.0.0rc and it should not impact the sync version of the operator.
here code for the sync kpo
https://github.com/apache/airflow/blame/main/airflow/providers/cncf/kubernetes/operators/pod.py#L572-L637

@raphaelauv would you like to share some example DAG logs

**Comment by raphaelauv** [comment]
@pankajastro you are correct I mixed the settings between asyn and non async when I checked the RC.

**Comment by eladkal** [comment]
@raphaelauv @pankajastro @pankajkoti If i get it right the resolution we are good to go with release?

**Comment by pankajkoti** [comment]
> @raphaelauv @pankajastro @pankajkoti If i get it right the resolution we are good to go with release?

@eladkal IMO, yes, we're good to go with release.

**Comment by pankajastro** [comment]
@eladkal yes, we are good to go with the release. Thanks!

**Comment by VladaZakharova** [comment]
Hi ! 
#36847 and  #37072 work as expected, thank you :)

**Comment by eladkal** [comment]
Thank you everyone. Providers are released.

I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
