### ISSUE TITLE
Decouple SMTP Provider settings from the Airflow Core

### ISSUE THREAD

**Issue by Taragolis** [apache/airflow#37703]
### Body

By mistake we add coupling between SMTP provider and core in https://github.com/apache/airflow/pull/36226.
Discussion for the reference: https://github.com/apache/airflow/pull/37701#discussion_r1502499164

**Provider Changes**
- [x] Move configurations into the provider configurations and get this settings from there

**Airflow Core Changes**
- [x] ~Deprecate~ Remove `SMTP_DEFAULT_TEMPLATED_SUBJECT` and `SMTP_DEFAULT_TEMPLATED_HTML_CONTENT_PATH` into the [`airflow/settings.py`](https://github.com/apache/airflow/blob/70348deaf76e07ba3e9ba5d9f50c584091852ae8/airflow/settings.py#L624-L634)
  ~- E.g. on access raise a deprecation warning with suggestion to upgrade to the new version of the SMTP Provider~
  ~- E.g. on set from [`airflow_local_settings.py`](https://github.com/apache/airflow/blob/70348deaf76e07ba3e9ba5d9f50c584091852ae8/airflow/settings.py#L474) raise a deprecation warning with suggestion to upgrade to the new version of the SMTP Provider and use configurations instead~

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by Taragolis** [comment]
Not really. This one about remove unnecessary settings options from the SMPT Provider, which add accidentally into the SmtpNotifier and Airflow 2.8.1

**Comment by Taragolis** [comment]
So there is no such attributes into the `settings.py` into the Airflow 2.8.1 and 2.8.2
- https://github.com/apache/airflow/blob/2.8.1/airflow/settings.py
- https://github.com/apache/airflow/blob/2.8.2/airflow/settings.py

So we might just fix it into the provider, and remove it from the core until we release 2.9

**Comment by vchiapaikeo** [comment]
Oh nice! If we can just remove those configs, that would make things a lot easier. I was thinking of swapping them over to provider configuration w/ something like this:

https://github.com/apache/airflow/pull/37711

**Comment by potiuk** [comment]
We just discussed it in release management channel - we will just remove the settings altogether (and yes replace with config) - we will also yank 1.6.0 (likely) and release 1.7.0 and also switch constraints for Airfrlow 2.8.1 and 2.8.2 to use smtp 1.5.0

**Comment by potiuk** [comment]
You can join `#release-management` channel on Slack for that one @vchiapaikeo :)

**Comment by vchiapaikeo** [comment]
Awesome, sounds good. Sorry about all the hassle here. Will get to fixing up that PR tonight!

**Comment by potiuk** [comment]
Well. We did not do a good job on preventing it during review, so don't put all the blame on you :)
