### ISSUE TITLE
Status of testing of Apache Airflow Helm Chart 1.13.0rc1

### ISSUE THREAD

**Issue by jedcunningham** [apache/airflow#37844]
We are kindly requesting that contributors to [Apache Airflow Helm Chart 1.13.0rc1](https://dist.apache.org/repos/dist/dev/airflow/helm-chart/1.13.0rc1) help test the RC.

Please let us know by commenting if the issue is addressed in the latest RC.

- [ ] [remove duplicate ports key in webserver-service.yaml (#37356)](https://github.com/apache/airflow/pull/37356): @Ahmad-RW
     Linked issues:
     - [mapping key "ports" already defined at line 23 - Regression introduced in 681d2ba  (#37353)](https://github.com/apache/airflow/issues/37353)
- [ ] [Possibility to set labels specific to the migrateDatabaseJob objects and pods (#37490)](https://github.com/apache/airflow/pull/37490): @cylabr
- [x] [Chart: Update comment about metrics mapping options (#37496)](https://github.com/apache/airflow/pull/37496): @jedcunningham
- [ ] [Flower K8s Probe config (#37528)](https://github.com/apache/airflow/pull/37528): @Seokyun-Ha
- [ ] [add airflow_home to loggrommersidecar (#37588)](https://github.com/apache/airflow/pull/37588): @romsharon98
- [x] [Chart: Default airflow version to 2.8.2 (#37704)](https://github.com/apache/airflow/pull/37704): @ephraimbuddy

Thanks to all who contributed to the release (probably not a complete list!):
@tata2000 @cylabr @Seokyun-Ha @jedcunningham @tatyana-arenburg-armis @Ahmad-RW @romsharon98 @ephraimbuddy

**Comment by potiuk** [comment]
I run a few basic test s- look s good. Default version of Airlfow was 2.8.2 and I was able to run some DAGs with default settings

**Comment by atul-ram** [comment]
Hi team,
i tried using this version, via helmrelease . it give below error :( .
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"helm.toolkit.fluxcd.io/v2beta1","kind":"HelmRelease","metadata":{"annotations":{},"name":"demo","namespace":"demo"},"spec":{"chart":{"spec":{"chart":"odpt-airflow","interval":"1m","sourceRef":{"kind":"HelmRepository","name":"helm-releases","namespace":"demo"},"version":"1.13.0"}},"install":{"disableWait":true},"interval":"5m","upgrade":{"disableWait":true},"values":{"config":{"core":{"colored_console_log":"True"},"logging":{"colored_console_log":"True"},"metrics":{"statsd_prefix":"demo"},"scheduler":{"statsd_prefix":"demo"}},"defaultAirflowRepository":"example.com.com:18445/apache/airflow","extraEnv":"- name: AIRFLOW__CORE__LOAD_EXAMPLES\n  value: 'True'\n","images":{"gitSync":{"pullPolicy":"IfNotPresent","repository":"example.com.com:18445/git-sync/git-sync","tag":"v4.1.0"},"pgbouncer":{"pullPolicy":"IfNotPresent","repository":"example.com.com:18445/apache/airflow","tag":"airflow-pgbouncer-2024.01.19-1.21.0"},"pgbouncerExporter":{"pullPolicy":"IfNotPresent","repository":"example.com.com:18445/apache/airflow","tag":"airflow-pgbouncer-exporter-2024.01.19-0.16.0"},"redis":{"pullPolicy":"IfNotPresent","repository":"example.com.com:18445/redis","tag":"7-bookworm"},"statsd":{"repository":"example.com.com:18445/prometheus/statsd-exporter"}},"ingress":{"enabled":true,"web":{"enabled":true,"hosts":[{"name":"arfw02-p-01-aks.nl.eu.abnamro.com","tls":{"enabled":true,"secretName":"ingress-tls-csi"}}],"ingressClassName":"nginx","path":"/","pathType":"Prefix"}},"logs":{"persistence":{"enabled":false}},"networkPolicies":{"enabled":false},"postgresql":{"enabled":true,"global":{"imageRegistry":"example.com.com:18445"},"primary":{"persistence":{"enabled":false}}},"redis":{"persistence":{"enabled":false}},"statsd":{"args":["--statsd.mapping-config=/etc/statsd-exporter/mappings.yml","--log.level=debug"],"enabled":true},"triggerer":{"persistence":{"enabled":false}},"webserver":{"extraVolumeMounts":[{"mountPath":"/mnt/secrets-store","name":"secret-store","readOnly":true}],"extraVolumes":[{"csi":{"driver":"secrets-store.csi.k8s.io","readOnly":true,"volumeAttributes":{"secretProviderClass":"ingress-tls-csi"}},"name":"secret-store"}]},"workers":{"persistence":{"enabled":false}}}}}
  creationTimestamp: "2024-03-04T06:13:42Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  name: demo
  namespace: demo
  resourceVersion: "10661457"
  uid: 7116a790-9e83-4717-829c-9e869aa1bde9
spec:
  chart:
    spec:
      chart: odpt-airflow
      interval: 1m
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: helm-releases
        namespace: demo
      version: 1.13.0
  install:
    disableWait: true
  interval: 5m
  upgrade:
    disableWait: true
  values:
    config:
      core:
        colored_console_log: "True"
      logging:
        colored_console_log: "True"
      metrics:
        statsd_prefix: demo
      scheduler:
        statsd_prefix: demo
    defaultAirflowRepository: example.com.com:18445/apache/airflow
    extraEnv: |
      - name: AIRFLOW__CORE__LOAD_EXAMPLES
        value: 'True'
    images:
      gitSync:
        pullPolicy: IfNotPresent
        repository: example.com.com:18445/git-sync/git-sync
        tag: v4.1.0
      pgbouncer:
        pullPolicy: IfNotPresent
        repository: example.com.com:18445/apache/airflow
        tag: airflow-pgbouncer-2024.01.19-1.21.0
      pgbouncerExporter:
        pullPolicy: IfNotPresent
        repository: example.com.com:18445/apache/airflow
        tag: airflow-pgbouncer-exporter-2024.01.19-0.16.0
      redis:
        pullPolicy: IfNotPresent
        repository: example.com.com:18445/redis
        tag: 7-bookworm
      statsd:
        repository: example.com.com:18445/prometheus/statsd-exporter
    ingress:
      enabled: true
      web:
        enabled: true
        hosts:
        - name: arfw02-p-01-aks.nl.eu.abnamro.com
          tls:
            enabled: true
            secretName: ingress-tls-csi
        ingressClassName: nginx
        path: /
        pathType: Prefix
    logs:
      persistence:
        enabled: false
    networkPolicies:
      enabled: false
    postgresql:
      enabled: true
      global:
        imageRegistry: example.com.com:18445
      primary:
        persistence:
          enabled: false
    redis:
      persistence:
        enabled: false
    statsd:
      args:
      - --statsd.mapping-config=/etc/statsd-exporter/mappings.yml
      - --log.level=debug
      enabled: true
    triggerer:
      persistence:
        enabled: false
    webserver:
      extraVolumeMounts:
      - mountPath: /mnt/secrets-store
        name: secret-store
        readOnly: true
      extraVolumes:
      - csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: ingress-tls-csi
        name: secret-store
    workers:
      persistence:
        enabled: false
status:
  conditions:
  - lastTransitionTime: "2024-03-04T06:16:14Z"
    message: |-
      Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
        line 45: mapping key "cluster-autoscaler.kubernetes.io/safe-to-evict" already defined at line 44
    reason: InstallFailed
    status: "False"
    type: Ready
  - lastTransitionTime: "2024-03-04T06:16:14Z"
    message: |+
      Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
        line 45: mapping key "cluster-autoscaler.kubernetes.io/safe-to-evict" already defined at line 44

      Last Helm logs:

    reason: InstallFailed
    status: "False"
    type: Released
  failures: 1
  helmChart: demo/demo-demo
  installFailures: 1
  lastAttemptedRevision: 1.13.0
  lastAttemptedValuesChecksum: 12366aa69b4709f4d42670010ab779449337fee3
  lastReleaseRevision: 1
  observedGeneration: 1
```

**Comment by eh-john** [comment]
I was able to install the chart from ArgoCD which was not possible on 1.12.0 so I would say #37402 is working as intended and fixes #37399 (although it's not on your list).

**Comment by jedcunningham** [comment]
Thanks @eh-john and @potiuk for testing. 1.13.0 is being released now 🥳
