### ISSUE TITLE
Fix wrong assertion methods in tests

### ISSUE THREAD

**Issue by Taragolis** [apache/airflow#37897]
### Body

During the https://github.com/apache/airflow/pull/37874 we starts to check invalid usage of `unittest.mock.Mock` methods, e.g.
usage of `assert <mocked_object>.called_once` which always evaluated as True instead of correct one `<mocked_object>.assert_called_once()`.

Unfortunetly not all tests are worked after changes: 
- regression
- changes in code base not reflected in tests
- comparison with new objects which do not implements `__eq__`
- etc.

All assert which are do not pass [PGH005](https://docs.astral.sh/ruff/rules/invalid-mock-access/#invalid-mock-access-pgh005) rule has `# noqa: PGH005 (fixme: WHAT HAPPEN IF CHANGE TO METHOD)`, this should be resolved. 

There is no single rule how it should be done, because it might involve to fix in Airflow codebase rather than in tests. 

## Provider [amazon](https://github.com/apache/airflow/tree/main/airflow/providers/amazon)
- [x] [`tests/providers/amazon/aws/operators/test_eks.py`](https://github.com/apache/airflow/blob/main/tests/providers/amazon/aws/operators/test_eks.py) (total: 1)

## Provider [microsoft.azure](https://github.com/apache/airflow/tree/main/airflow/providers/microsoft/azure)
- [x] [`tests/providers/microsoft/azure/hooks/test_data_lake.py`](https://github.com/apache/airflow/blob/main/tests/providers/microsoft/azure/hooks/test_data_lake.py) (total: 1)
- [x] [`tests/providers/microsoft/azure/hooks/test_cosmos.py`](https://github.com/apache/airflow/blob/main/tests/providers/microsoft/azure/hooks/test_cosmos.py) (total: 1)
- [x] [`tests/providers/microsoft/azure/hooks/test_adx.py`](https://github.com/apache/airflow/blob/main/tests/providers/microsoft/azure/hooks/test_adx.py)  (total: 7)
- [x] [`tests/providers/microsoft/azure/hooks/test_data_factory.py`](https://github.com/apache/airflow/blob/main/tests/providers/microsoft/azure/hooks/test_data_factory.py)  (total: 1)
- [x] [`tests/providers/microsoft/azure/hooks/test_synapse.py`](https://github.com/apache/airflow/blob/main/tests/providers/microsoft/azure/hooks/test_synapse.py) (total: 1)
- [x] [`tests/providers/microsoft/azure/hooks/test_wasb.py`](https://github.com/apache/airflow/blob/main/tests/providers/microsoft/azure/hooks/test_wasb.py) (total: 1)

## Provider [celery](https://github.com/apache/airflow/tree/main/airflow/providers/celery)
- [x] [`tests/providers/celery/executors/test_celery_executor.py`](https://github.com/apache/airflow/blob/main/tests/providers/celery/executors/test_celery_executor.py) (total: 1)

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
Assigned you.

**Comment by alizademhdi** [comment]
Hi @potiuk, I'm interested in doing the rest of the tasks. Can you assign it to me?

**Comment by alizademhdi** [comment]
I think all of this tasks fixed in #36755 and #38025. So you can close this issue :)

**Comment by potiuk** [comment]
Yep. Python 3.12 caught all of them.
