### ISSUE TITLE
Status of testing Providers that were prepared on March 04, 2024

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#37890]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 8.19.0rc1](https://pypi.org/project/apache-airflow-providers-amazon/8.19.0rc1)
   - [ ] [Implement `filter_permitted_menu_items` in AWS auth manager (#37627)](https://github.com/apache/airflow/pull/37627): @vincbeck
   - [ ] [Implement `batch_is_authorized_*` APIs in AWS auth manager (#37430)](https://github.com/apache/airflow/pull/37430): @vincbeck
   - [ ] [Fix init checks for aws `eks` (#37674)](https://github.com/apache/airflow/pull/37674): @okirialbert
   - [ ] [init checks for aws gcs_to_s3 (#37662)](https://github.com/apache/airflow/pull/37662): @okirialbert
   - [x] [Use named loggers instead of root logger (#37801)](https://github.com/apache/airflow/pull/37801): @Taragolis
   - [x] [Avoid non-recommended usage of logging (#37792)](https://github.com/apache/airflow/pull/37792): @Taragolis
   - [ ] [Unify aws_conn_id type to always be str | None (#37768)](https://github.com/apache/airflow/pull/37768): @eejbyfeldt
   - [x] [Limit `pandas` to `<2.2` (#37748)](https://github.com/apache/airflow/pull/37748): @Taragolis
   - [ ] [Implement AIP-60 Dataset URI formats (#37005)](https://github.com/apache/airflow/pull/37005): @uranusjr
   - [x] [Bump min versions of openapi validators (#37691)](https://github.com/apache/airflow/pull/37691): @potiuk
   - [ ] [Update action names in AWS auth manager (#37572)](https://github.com/apache/airflow/pull/37572): @vincbeck
## Provider [apache.beam: 5.6.2rc1](https://pypi.org/project/apache-airflow-providers-apache-beam/5.6.2rc1)
   - [x] [Add Python 3.12 exclusions in providers/pyproject.toml (#37404)](https://github.com/apache/airflow/pull/37404): @potiuk
## Provider [apache.druid: 3.9.0rc1](https://pypi.org/project/apache-airflow-providers-apache-druid/3.9.0rc1)
   - [ ] [Adding optional SSL verification for druid operator (#37629)](https://github.com/apache/airflow/pull/37629): @danielbe11
   - [ ] [Modify ssl verification in druid operator (#37673)](https://github.com/apache/airflow/pull/37673): @danielbe11
## Provider [apache.hdfs: 4.3.3rc1](https://pypi.org/project/apache-airflow-providers-apache-hdfs/4.3.3rc1)
   - [x] [Turn Pydantic into an optional dependency (#37320)](https://github.com/apache/airflow/pull/37320): @potiuk
## Provider [apache.hive: 7.0.1rc1](https://pypi.org/project/apache-airflow-providers-apache-hive/7.0.1rc1)
   - [x] [Remove references from the code to Jira Issues (#37807)](https://github.com/apache/airflow/pull/37807): @Taragolis
   - [ ] [Unify aws_conn_id type to always be str | None (#37768)](https://github.com/apache/airflow/pull/37768): @eejbyfeldt
   - [x] [Limit `pandas` to `<2.2` (#37748)](https://github.com/apache/airflow/pull/37748): @Taragolis
## Provider [apache.livy: 3.7.3rc1](https://pypi.org/project/apache-airflow-providers-apache-livy/3.7.3rc1)
   - [x] [Fix rendering `LivyOperator.spark_params` (#37361)](https://github.com/apache/airflow/pull/37361): @Taragolis
## Provider [apache.pinot: 4.3.1rc1](https://pypi.org/project/apache-airflow-providers-apache-pinot/4.3.1rc1)
   - [x] [Bump lower-limit for pinotdb (#37690)](https://github.com/apache/airflow/pull/37690): @potiuk
## Provider [celery: 3.6.1rc1](https://pypi.org/project/apache-airflow-providers-celery/3.6.1rc1)
   - [x] [Remove pid arg from celery option to fix duplicate pid issue, Move celery command to provider package (#36794)](https://github.com/apache/airflow/pull/36794): @pavansharma36
   - [ ] [Change AirflowTaskTimeout to inherit BaseException (#35653)](https://github.com/apache/airflow/pull/35653): @hterik
   - [ ] [Migrate executor docs to respective providers (#37728)](https://github.com/apache/airflow/pull/37728): @RNHTTR
## Provider [cncf.kubernetes: 8.0.1rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/8.0.1rc1)
   - [ ] [Immediately fail the task in case of worker pod having a fatal container state (#37670)](https://github.com/apache/airflow/pull/37670): @dirrao
   - [ ] [Skip pod cleanup in case of pod creation failed (#37671)](https://github.com/apache/airflow/pull/37671): @dirrao
   - [x] [Avoid non-recommended usage of logging (#37792)](https://github.com/apache/airflow/pull/37792): @Taragolis
   - [ ] [Migrate executor docs to respective providers (#37728)](https://github.com/apache/airflow/pull/37728): @RNHTTR
## Provider [common.sql: 1.11.1rc1](https://pypi.org/project/apache-airflow-providers-common-sql/1.11.1rc1)
   - [x] [Make `executemany` keyword arguments only in `DbApiHook.insert_rows` (#37840)](https://github.com/apache/airflow/pull/37840): @Taragolis
   - [x] [Limit `pandas` to `<2.2` (#37748)](https://github.com/apache/airflow/pull/37748): @Taragolis
## Provider [dbt.cloud: 3.7.0rc1](https://pypi.org/project/apache-airflow-providers-dbt-cloud/3.7.0rc1)
   - [ ] [add reuse_existing_run for allowing DbtCloudRunJobOperator to reuse existing run (#37474)](https://github.com/apache/airflow/pull/37474): @Lee-W
## Provider [docker: 3.9.2rc1](https://pypi.org/project/apache-airflow-providers-docker/3.9.2rc1)
   - [x] [Fix construct `docker.TLSConfig` for `docker>=7` (#37481)](https://github.com/apache/airflow/pull/37481): @Taragolis
## Provider [exasol: 4.4.3rc1](https://pypi.org/project/apache-airflow-providers-exasol/4.4.3rc1)
   - [x] [Limit `pandas` to `<2.2` (#37748)](https://github.com/apache/airflow/pull/37748): @Taragolis
## Provider [google: 10.16.0rc1](https://pypi.org/project/apache-airflow-providers-google/10.16.0rc1)
   - [ ] [`CloudRunExecuteJobOperator`: Add project_id to hook.get_job calls (#37201)](https://github.com/apache/airflow/pull/37201): @freyrsae
   - [ ] [Add developer token as authentication method to GoogleAdsHook (#37417)](https://github.com/apache/airflow/pull/37417): @LeonGraveland
   - [ ] [Add GKEStartKueueInsideClusterOperator to support Kueue inside clusters (#37072)](https://github.com/apache/airflow/pull/37072): @VladaZakharova
   - [x] [Support location for BigQueryInsertJobOperator in deferrable mode (#37282)](https://github.com/apache/airflow/pull/37282): @moiseenkov
   - [x] [Add support for impersonation chain to GKEStartPodOperator in deferrable mode (#37486)](https://github.com/apache/airflow/pull/37486): @m1racoli
   - [ ] [Create GKEStartJobOperator and KubernetesJobOperator (#36847)](https://github.com/apache/airflow/pull/36847): @MaksYermak
   - [x] [Fix invalid deprecation of `DataFusionPipelineLinkHelper` (#37755)](https://github.com/apache/airflow/pull/37755): @Taragolis
   - [ ] [fix templated field assignment `google/cloud/operators/compute.py` (#37659)](https://github.com/apache/airflow/pull/37659): @romsharon98
   - [ ] [Fix `bigquery_to_mysql` init checks (#37653)](https://github.com/apache/airflow/pull/37653): @okirialbert
   - [x] [Fix Async GCSObjectsWithPrefixExistenceSensor xcom push (#37634)](https://github.com/apache/airflow/pull/37634): @pankajastro
   - [ ] [Fix GCSSynchronizeBucketsOperator timeout error (#37237)](https://github.com/apache/airflow/pull/37237): @kevgeo
   - [ ] [fix: Signature of "insert_rows" incompatible with supertype "DbApiHook" (#37391)](https://github.com/apache/airflow/pull/37391): @rawwar
   - [ ] [fix: use offset-naive datetime in _CredentialsToken (#37539)](https://github.com/apache/airflow/pull/37539): @m1racoli
   - [ ] [Use hook.wait_for_operation in DataprocInstantiateInlineWorkflowTemplateOperator (#37145)](https://github.com/apache/airflow/pull/37145): @edin-tapad
   - [ ] [Fix typo on DataflowStartFlexTemplateOperator documentation (#37595)](https://github.com/apache/airflow/pull/37595): @sarafonseca-123
   - [x] [Make `executemany` keyword arguments only in `DbApiHook.insert_rows` (#37840)](https://github.com/apache/airflow/pull/37840): @Taragolis
   - [ ] [Unify aws_conn_id type to always be str | None (#37768)](https://github.com/apache/airflow/pull/37768): @eejbyfeldt
   - [x] [Limit `pandas` to `<2.2` (#37748)](https://github.com/apache/airflow/pull/37748): @Taragolis
   - [x] [Remove broken deprecated fallback into the Google provider operators (#37740)](https://github.com/apache/airflow/pull/37740): @Taragolis
   - [ ] [Implement AIP-60 Dataset URI formats (#37005)](https://github.com/apache/airflow/pull/37005): @uranusjr
   - [ ] [resolve template fields init checks for `bigquery` (#37586)](https://github.com/apache/airflow/pull/37586): @okirialbert
   - [ ] [Update docs for the DataprocCreateBatchOperator (#37562)](https://github.com/apache/airflow/pull/37562): @molcay
   - [x] [Replace usage of `datetime.utcnow` and `datetime.utcfromtimestamp` in providers (#37138)](https://github.com/apache/airflow/pull/37138): @Taragolis
## Provider [hashicorp: 3.6.4rc1](https://pypi.org/project/apache-airflow-providers-hashicorp/3.6.4rc1)
   - [ ] [Fix unexpected keyword argument 'secret_path' in secrets.kv.v2 (#37626)](https://github.com/apache/airflow/pull/37626): @tungbq
## Provider [http: 4.10.0rc1](https://pypi.org/project/apache-airflow-providers-http/4.10.0rc1)
   - [ ] [Change the URL building in HttpHookAsync to match the behavior of HttpHook (#37696)](https://github.com/apache/airflow/pull/37696): @alejorodriguez96
   - [x] [Return back removed public HttpHook's method (#37738)](https://github.com/apache/airflow/pull/37738): @Taragolis
## Provider [microsoft.azure: 9.0.1rc1](https://pypi.org/project/apache-airflow-providers-microsoft-azure/9.0.1rc1)
   - [x] [fix: Pass proxies config when using ClientSecretCredential in AzureDataLakeStorageV2Hook (#37103)](https://github.com/apache/airflow/pull/37103): @dabla
## Provider [microsoft.psrp: 2.6.0rc2](https://pypi.org/project/apache-airflow-providers-microsoft-psrp/2.6.0rc2)
   - [x] [Add PSRP connection type (#34766)](https://github.com/apache/airflow/pull/34766): @arjunanan6
## Provider [mysql: 5.5.4rc1](https://pypi.org/project/apache-airflow-providers-mysql/5.5.4rc1)
   - [ ] [Unify aws_conn_id type to always be str | None (#37768)](https://github.com/apache/airflow/pull/37768): @eejbyfeldt
   - [ ] [Implement AIP-60 Dataset URI formats (#37005)](https://github.com/apache/airflow/pull/37005): @uranusjr
## Provider [openlineage: 1.6.0rc1](https://pypi.org/project/apache-airflow-providers-openlineage/1.6.0rc1)
   - [x] [[OpenLineage] feat: Add metrics for event_size and extraction time (#37797)](https://github.com/apache/airflow/pull/37797): @kacpermuda
   - [x] [[OpenLineage] feat: Add OpenLineage support for File and User Airflow's lineage entity (#37744)](https://github.com/apache/airflow/pull/37744): @kacpermuda
   - [x] [[OpenLineage] Add support for JobTypeJobFacet properties. (#37255)](https://github.com/apache/airflow/pull/37255): @mattiabertorello
   - [x] [[OpenLineage] chore: Update comments and logging in OpenLineage ExtractorManager (#37622)](https://github.com/apache/airflow/pull/37622): @kacpermuda
   - [x] [[OpenLineage] Check for disabled operators in DefaultExtractor.extract_on_complete (#37392)](https://github.com/apache/airflow/pull/37392): @kacpermuda
   - [x] [[OpenLineage] docs: Update whole OpenLineage Provider docs. (#37620)](https://github.com/apache/airflow/pull/37620): @kacpermuda
## Provider [opensearch: 1.1.2rc1](https://pypi.org/project/apache-airflow-providers-opensearch/1.1.2rc1)
   - [x] [Fix "Exception statement has no effect" (#37722)](https://github.com/apache/airflow/pull/37722): @Taragolis
## Provider [postgres: 5.10.2rc1](https://pypi.org/project/apache-airflow-providers-postgres/5.10.2rc1)
   - [ ] [Implement AIP-60 Dataset URI formats (#37005)](https://github.com/apache/airflow/pull/37005): @uranusjr
## Provider [presto: 5.4.2rc1](https://pypi.org/project/apache-airflow-providers-presto/5.4.2rc1)
   - [x] [Limit `pandas` to `<2.2` (#37748)](https://github.com/apache/airflow/pull/37748): @Taragolis
## Provider [salesforce: 5.6.3rc1](https://pypi.org/project/apache-airflow-providers-salesforce/5.6.3rc1)
   - [x] [Limit `pandas` to `<2.2` (#37748)](https://github.com/apache/airflow/pull/37748): @Taragolis
## Provider [smtp: 1.6.1rc1](https://pypi.org/project/apache-airflow-providers-smtp/1.6.1rc1)
   - [x] [Fix backwards compatibility for SMTP provider (#37701)](https://github.com/apache/airflow/pull/37701): @potiuk
   - [x] [Deprecate smtp configs in airflow settings / local_settings (#37711)](https://github.com/apache/airflow/pull/37711): @vchiapaikeo
## Provider [telegram: 4.4.0rc2](https://pypi.org/project/apache-airflow-providers-telegram/4.4.0rc2)
   - [ ] [Add telegram connection with documnetation (#37515)](https://github.com/apache/airflow/pull/37515): @romsharon98
## Provider [trino: 5.6.3rc1](https://pypi.org/project/apache-airflow-providers-trino/5.6.3rc1)
   - [x] [Limit `pandas` to `<2.2` (#37748)](https://github.com/apache/airflow/pull/37748): @Taragolis
   - [ ] [Implement AIP-60 Dataset URI formats (#37005)](https://github.com/apache/airflow/pull/37005): @uranusjr
## Provider [weaviate: 1.3.3rc1](https://pypi.org/project/apache-airflow-providers-weaviate/1.3.3rc1)
   - [x] [Limit `pandas` to `<2.2` (#37748)](https://github.com/apache/airflow/pull/37748): @Taragolis

All users involved in the PRs:
@vincbeck @VladaZakharova @pankajastro @dabla @m1racoli @RNHTTR @danielbe11 @Taragolis @pavansharma36 @kacpermuda @moiseenkov @dirrao @kevgeo @okirialbert @eejbyfeldt @mattiabertorello @MaksYermak @hter

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by moiseenkov** [comment]
hi,
#37282 works as expected

**Comment by kacpermuda** [comment]
All the PR's for the `Provider openlineage: 1.6.0rc1` works as expected.

**Comment by Taragolis** [comment]
I've check my changes, most of them pretty simple.

- https://github.com/apache/airflow/pull/37138 in google Provider changes should be fixed by https://github.com/apache/airflow/pull/37539, cc: @m1racoli
- https://github.com/apache/airflow/pull/37361: I've checked that it rendered correctly, it would be nice if @LudvigLundberg have a time to look on changes as original reporter of the issue

**Comment by LudvigLundberg** [comment]
> I've check my changes, most of them pretty simple.
> 
> * [Replace usage of `datetime.utcnow` and `datetime.utcfromtimestamp` in providers #37138](https://github.com/apache/airflow/pull/37138) in google Provider changes should be fixed by [fix: use offset-naive datetime in _CredentialsToken #37539](https://github.com/apache/airflow/pull/37539), cc: @m1racoli
> * [Fix rendering `LivyOperator.spark_params` #37361](https://github.com/apache/airflow/pull/37361): I've checked that it rendered correctly, it would be nice if @LudvigLundberg have a time to look on changes as original reporter of the issue

Can confirm that the changes in #37361 have solved the issue I was experiencing! Big thanks for fixing it!

**Comment by vchiapaikeo** [comment]
https://github.com/apache/airflow/pull/37711 looks good.

Huge thank you to everyone that helped resolve this mini fire last week (Jarek, Andrey, Elad 🙇 )

**Comment by arjunanan6** [comment]
#34766 works as expected. :)

**Comment by m1racoli** [comment]
I can confirm #37486.

Although I had to manually require `apache-airflow-providers-cncf-kubernetes>=8.0.0` for my DAG to parse. Before that I had version 7.14.0 installed and getting

```
Broken DAG: [/usr/local/airflow/dags/test_gke.py] Traceback (most recent call last):
  File "/usr/local/airflow/dags/test_gke.py", line 3, in <module>
    from airflow.providers.google.cloud.operators.kubernetes_engine import GKEStartPodOperator, OnFinishAction
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/google/cloud/operators/kubernetes_engine.py", line 35, in <module>
    from airflow.providers.cncf.kubernetes.operators.job import KubernetesJobOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.job'
```

I assume this is because of #36847. Are we missing a requirement for `apache-airflow-providers-cncf-kubernetes>=8.0.0` in the google provider's dependencies?

**Comment by moiseenkov** [comment]
> I assume this is because of #36847. Are we missing a requirement for `apache-airflow-providers-cncf-kubernetes>=8.0.0` in the google provider's dependencies?

@m1racoli , yes you're right.
@eladkal , can we please exclude google from this release for now, merge the fix #37899 and release google afterwards with RC2?

**Comment by potiuk** [comment]
All my changes are there :)

**Comment by pavansharma36** [comment]
Verified #36794

**Comment by eladkal** [comment]
@moiseenkov I don't think this qualify for RC2. It's not a regression and there is a simple fix (bump k8s provider if not using latest). Also the RC1 contains many features and fixes that not worth delaying.
We can always improve the mechanism and have better error message for next release.

**Comment by moiseenkov** [comment]
> @moiseenkov I don't think this qualify for RC2. It's not a regression and there is a simple fix (bump k8s provider if not using latest). Also the RC1 contains many features and fixes that not worth delaying.
> We can always improve the mechanism and have better error message for next release.

I totally agree. We will adjust error messages in the google provider package for the next release and will follow this convention from now. Thank you!

**Comment by eladkal** [comment]
Thank you everyone. Providers are released.

I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).

**Comment by dabla** [comment]
Maybe a bit late but I tested [#37103](https://github.com/apache/airflow/pull/37103) and I can confirm it works :)

**Comment by potiuk** [comment]
Never too late for good news :)
