### ISSUE TITLE
Status of testing of Apache Airflow 2.8.3rc1

### ISSUE THREAD

**Issue by ephraimbuddy** [apache/airflow#37982]
### Body

We are kindly requesting that contributors to [Apache Airflow RC 2.8.3rc1](https://pypi.org/project/apache-airflow/2.8.3rc1/) help test the RC.

Please let us know by commenting if the issue is addressed in the latest RC.

- [ ] [Set parsing context dag_id in dag test command (#37606)](https://github.com/apache/airflow/pull/37606): @SamWheating
- [x] [Remove gosu binary from our images (#37677)](https://github.com/apache/airflow/pull/37677): @potiuk
- [x] [Properly include airflow_pre_installed_providers.txt artifact (#37679)](https://github.com/apache/airflow/pull/37679): @potiuk
- [ ] [Improve code coverage for TriggerRuleDep (#37680)](https://github.com/apache/airflow/pull/37680): @stevenschaerer @ephraimbuddy
     Linked issues:
     - [Improve Code Coverage for Airflow (#35127)](https://github.com/apache/airflow/issues/35127)
- [x] [Bump min versions of openapi validators (#37691)](https://github.com/apache/airflow/pull/37691): @potiuk
     Linked issues:
     - [Use `uv` as packaging tool used in CI builds (#37683)](https://github.com/apache/airflow/pull/37683)
- [x] [The SMTP provider is now preinstalled when installing Airflow (#37713)](https://github.com/apache/airflow/pull/37713): @vchiapaikeo @potiuk
     Linked issues:
     - [Modify SmtpNotifier to accept template with defaults (#36226)](https://github.com/apache/airflow/pull/36226)
     - [Fix backwards compatibility for SMTP provider (#37701)](https://github.com/apache/airflow/pull/37701)
- [x] [Add smtp provider to prod_image_installed_providers.txt (#37739)](https://github.com/apache/airflow/pull/37739): @drajguru @potiuk
     Linked issues:
     - [Fix backwards compatibility for SMTP provider (#37701)](https://github.com/apache/airflow/pull/37701)
     - [Wrap AIRFLOW_HOME env var lookup in Path (#37733)](https://github.com/apache/airflow/pull/37733)
- [x] [Fix external_executor_id being overwritten (#37784)](https://github.com/apache/airflow/pull/37784): @ferruzzi
- [ ] [`MappedOperator` setter methods (#37828)](https://github.com/apache/airflow/pull/37828): @nathadfield
     Linked issues:
     - [Cluster policies on mapped tasks cause broken DAGs (#37013)](https://github.com/apache/airflow/issues/37013)
- [x] [Fix mypy checks failing in new types-docutils (#37858)](https://github.com/apache/airflow/pull/37858): @potiuk
- [x] [Additional type-ignore after types-docutils (#37859)](https://github.com/apache/airflow/pull/37859): @potiuk
- [ ] [Add "MENU" permission in auth manager (#37881)](https://github.com/apache/airflow/pull/37881): @vincbeck
- [ ] [Update build and install dependencies. (#37910)](https://github.com/apache/airflow/pull/37910): @potiuk

Thanks to all who contributed to the release (probably not a complete list!):
@vincbeck @SamWheating @drajguru @potiuk @ferruzzi @stevenschaerer @vchiapaikeo @nathadfield @ephraimbuddy

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
Checked all my changes. Look s good.

**Comment by nathadfield** [comment]
#37828 is all good from me.

**Comment by vincbeck** [comment]
Checked my change and it works as expected

**Comment by stevenschaerer** [comment]
#37680 added tests to increasee code coverage so there is nothing to check.
