### ISSUE TITLE
Fix remaining `PT012` pytest checks: `pytest-raises-with-multiple-statements`

### ISSUE THREAD

**Issue by Taragolis** [apache/airflow#38270]
### Body

Follow-up task for https://github.com/apache/airflow/pull/38219

We enable this rule for avoid accidentally misses some asserts into the `pytest.raises()` blocks

### Easy way to find all linting problem into the module
1. Remove corresponding line to particular module into the [`pyproject.toml`](https://github.com/apache/airflow/blob/main/pyproject.toml#L1490) in [tool.ruff.lint.per-file-ignores]
2. Run ruff via [pre-commit](https://github.com/apache/airflow/blob/main/contributing-docs/08_static_code_checks.rst#pre-commit-hooks) hook 
3. [Run tests locally](https://github.com/apache/airflow/blob/main/contributing-docs/testing/unit_tests.rst#running-unit-tests)

```console
❯ pre-commit run ruff --all-files

Run 'ruff' for extremely fast Python linting.............................Failed
- hook id: ruff
- exit code: 1

tests/providers/amazon/aws/hooks/test_base_aws.py:1126:5: PT012 `pytest.raises()` block should contain a single simple statement
tests/providers/amazon/aws/hooks/test_datasync.py:410:9: PT012 `pytest.raises()` block should contain a single simple statement
tests/providers/amazon/aws/hooks/test_eks.py:792:13: PT012 `pytest.raises()` block should contain a single simple statement
tests/providers/amazon/aws/hooks/test_redshift_data.py:80:9: PT012 `pytest.raises()` block should contain a single simple statement
tests/providers/amazon/aws/hooks/test_s3.py:495:9: PT012 `pytest.raises()` block should contain a single simple statement
tests/providers/amazon/aws/operators/test_emr_serverless.py:435:9: PT012 `pytest.raises()` block should contain a single simple statement
tests/providers/amazon/aws/operators/test_redshift_data.py:300:9: PT012 `pytest.raises()` block should contain a single simple statement
Found 7 errors.
tests/providers/amazon/aws/sensors/test_glacier.py:91:9: PT012 `pytest.raises()` block should contain a single simple statement
tests/providers/amazon/aws/sensors/test_glue.py:129:9: PT012 `pytest.raises()` block should contain a single simple statement
tests/providers/amazon/aws/sensors/test_lambda_function.py:100:9: PT012 `pytest.raises()` block should contain a single simple statement
tests/providers/amazon/aws/system/utils/test_helpers.py:88:9: PT012 `pytest.raises()` block should contain a single simple statement
tests/providers/amazon/aws/system/utils/test_helpers.py:125:13: PT012 `pytest.raises()` block should contain a single simple statement
tests/providers/amazon/aws/transfers/test_redshift_to_s3.py:377:9: PT012 `pytest.raises()` block should contain a single simple statement
tests/providers/amazon/aws/triggers/test_ecs.py:55:9: PT012 `pytest.raises()` block should contain a single simple statement
tests/providers/amazon/aws/triggers/test_ecs.py:74:9: PT012 `pytest.raises()` block should contain a single simple statement
tests/providers/amazon/aws/waiters/test_neptune.py:56:9: PT012 `pytest.raises()` block should contain a single simple statement
tests/providers/amazon/aws/waiters/test_neptune.py:77:9: PT012 `pytest.raises()` block should contain a single simple statement
Found 10 errors.
```

> [!TIP]
> Feel free to ask a suggestion/helps in slack channels `#contributors` or `#new-contributors`

> [!NOTE]
> There is no problem to mark specific case which cannot be easily resolved by add `# noqa: PT012  reason why it should be skiped from check`

> [!WARNING]
> There is a chance to found a regression into the Providers Code Base, so better fix it separately of other changes. E.g fix regression in code base and adopt the test by the separate PR

# Regular Unit Tests

## Provider [amazon](https://github.com/apache/airflow/tree/main/airflow/providers/amazon)
- [x] `tests/providers/amazon/aws/hooks/test_base_aws.py`
- [x] `tests/providers/amazon/aws/hooks/test_datasync.py`
- [x] `tests/providers/amazon/aws/hooks/test_eks.py`
- [x] `tests/providers/amazon/aws/hooks/test_redshift_data.py`
- [x] `tests/providers/amazon/aws/hooks/test_s3.py`
- [x] `tests/providers/amazon/aws/operators/test_emr_serverless.py`
- [x] `tests/providers/amazon/aws/operators/test_redshift_data.py`
- [x] `tests/providers/amazon/aws/sensors/test_glacier.py`
- [x] `tests/providers/amazon/aws/sensors/test_glue.py`
- [x] `tests/providers/amazon/aws/sensors/test_lambda_function.py`
- [x] `tests/providers/amazon/aws/system/utils/test_helpers.py`
- [x] `tests/providers/amazon/aws/transfers/test_redshift_to_s3.py`
- [x] `tests/providers/amazon/aws/triggers/test_ecs.py`
- [x] `tests/providers/amazon/aws/waiters/test_neptune.py`

## Provider [apache.beam](https://github.com/apache/airflow/tree/main/airflow/providers/apache/beam)
- [x] `tests/providers/apache/beam/hooks/test_beam.py`

## Provider [apache.hive](https://github.com/apache/airflow/tree/main/airflow/providers/apache/hive)
- [x] `tests/providers/apache/hive/hooks/test_hive.py`
- [x] `tests/providers/apache/hive/sensors/test_named_hive_partition.py`

## Provider [apache.spark](https://github.com/apache/airflow/tree/main/airflow/providers/apache/spark)
- [x] `tests/providers/apache/spark/hooks/test_spark_sql.py`

## Provider [celery](https://github.com/apache/airflow/tree/main/airflow/providers/celery)
- [x] `tests/providers/celery/sensors/test_celery_queue.py`

## Provider [cncf.kubernetes](https://github.com/apache/airflow/tree/main/airflow/providers/cncf/kubernetes)
- [x] `tests/providers/cncf/kubernetes/executors/test_kubernetes_executor.py`
- [x] `tests/providers/cncf/kubernetes/hooks/test_kubernetes.py`
- [x] `tests/providers/cncf/kubernetes/operators/test_pod.py`
- [x] `tests/providers/cncf/kubernetes/utils/test_k8s_resource_iterator.py`
- [x] `tests/providers/cncf/kubernetes/utils/test_pod_manager.py`

## Provider [common.sql](https://github.com/apache/airflow/tree/main/airflow/providers/common/sql)
- [x] `tests/providers/common/sql/operators/test_sql.py`

## Provider [databricks](https://github.com/apache/airflow/tree/main/airflow/providers/databricks)
- [x] `tests/providers/databricks/hooks/test_databricks.py`
- [x] `tests/providers/databricks/operators/test_databricks.py`
- [x] `tests/providers/databricks/operators/test_databricks_repos.py`
- [x] `tests/providers/databricks/sensors/test_databricks_partition.py`

## Provider [datadog](https://github.com/apache/airflow/tree/main/airflow/providers/datadog)
- [x] `tests/providers/datadog/sensors/test_datadog.py`

## Provider [dbt](https://github.com/apache/airflow/tree/main/airflow/providers/dbt)
- [x] `tests/providers/dbt/cloud/operators/test_dbt.py`

## Provider [fab](https://github.com/apache/airflow/tree/main/airflow/providers/fab)
- [x] `tests/providers/fab/auth_manager/cli_commands/test_user_command.py`

## Provider [ftp](https://github.com/apache/airflow/tree/main/airflow/providers/ftp)
- [x] `tests/providers/ftp/operators/test_ftp.py`

## Provider [google](https://github.com/apache/airflow/tree/main/airflow/providers/google)
- [x] `tests/providers/google/cloud/hooks/test_bigquery.py`
- [x] `tests/providers/google/cloud/hooks/test_cloud_storage_transfer_service.py`
- [x] `tests/providers/google/cloud/hooks/test_dataflow.py`
- [x] `tests/providers/google/cloud/hooks/test_dataprep.py`
- [x] `tests/providers/google/cloud/hooks/test_kubernetes_engine.py`
- [x] `tests/providers/google/cloud/hooks/test_pubsub.py`
- [x] `tests/providers/google/cloud/operators/test_bigtable.py`
- [x] `tests/providers/google/cloud/operators/test_cloud_sql.py`
- [x] `tests/providers/google/cloud/operators/test_cloud_storage_transfer_service.py`
- [x] `tests/providers/google/cloud/operators/test_compute.py`
- [x] `tests/providers/google/cloud/operators/test_datafusion.py`
- [x] `tests/providers/google/cloud/operators/test_dataproc.py`
- [x] `tests/providers/google/cloud/operators/test_functions.py`
- [x] `tests/providers/google/cloud/operators/test_kubernetes_engine.py`
- [x] `tests/providers/google/cloud/operators/test_mlengine.py`
- [x] `tests/providers/google/cloud/operators/test_spanner.py`
- [x] `tests/providers/google/cloud/sensors/test_datafusion.py`
- [x] `tests/providers/google/cloud/sensors/test_dataproc.py`
- [x] `tests/providers/google/cloud/sensors/test_gcs.py`
- [x] `tests/providers/google/cloud/sensors/test_pubsub.py`
- [x] `tests/providers/google/cloud/transfers/test_gcs_to_bigquery.py`
- [x] `tests/providers/google/cloud/utils/test_credentials_provider.py`
- [x] `tests/providers/google/common/hooks/test_base_google.py`

## Provider [jenkins](https://github.com/apache/airflow/tree/main/airflow/providers/jenkins)
- [x] `tests/providers/jenkins/sensors/test_jenkins.py`

## Provider [microsoft.azure](https://github.com/apache/airflow/tree/main/airflow/providers/microsoft/azure)
- [x] `tests/providers/microsoft/azure/hooks/test_data_factory.py`
- [x] `tests/providers/microsoft/azure/hooks/test_wasb.py`

## Provider [microsoft.psrp](https://github.com/apache/airflow/tree/main/airflow/providers/microsoft/psrp)
- [x] `tests/providers/microsoft/psrp/hooks/test_psrp.py`

## Provider [openai](https://github.com/apache/airflow/tree/main/airflow/providers/openai)
- [x] `tests/providers/openai/operators/test_openai.py`

## Provider [oracle](https://github.com/apache/airflow/tree/main/airflow/providers/oracle)
- [x] `tests/providers/oracle/hooks/test_oracle.py`

## Provider [papermill](https://github.com/apache/airflow/tree/main/airflow/providers/papermill)
- [x] `tests/providers/papermill/operators/test_papermill.py`

## Provider [sftp](https://github.com/apache/airflow/tree/main/airflow/providers/sftp)
- [x] `tests/providers/sftp/hooks/test_sftp.py`
- [x] `tests/providers/sftp/operators/test_sftp.py`
- [x] `tests/providers/sftp/sensors/test_sftp.py`
- [x] `tests/providers/sftp/triggers/test_sftp.py`

## Provider [ssh](https://github.com/apache/airflow/tree/main/airflow/providers/ssh)
- [x] `tests/providers/ssh/hooks/test_ssh.py`
- [x] `tests/providers/ssh/operators/test_ssh.py`

## Provider [telegram](https://github.com/apache/airflow/tree/main/airflow/providers/telegram)
- [x] `tests/providers/telegram/hooks/test_telegram.py`
- [x] `tests/providers/telegram/operators/test_telegram.py`

# K8S Tests
For more detail have a look [Kubernetes tests](https://github.com/apache/airflow/blob/main/contributing-docs/testing/k8s_tests.rst) into the contributors documentation

https://github.com/apache/airflow/blob/5a612dac4a6ebdf44d73d5d23fed5419e2519eb1/pyproject.toml#L1406

- [x] `kubernetes_tests/test_kubernetes_pod_operator.py`

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by shahar1** [comment]
And we're done :)
Good job everyone!

**Comment by potiuk** [comment]
Cool!
