### ISSUE TITLE
Status of testing of Apache Airflow 2.8.4rc1

### ISSUE THREAD

**Issue by jedcunningham** [apache/airflow#38334]
We are kindly requesting that contributors to [Apache Airflow RC 2.8.4rc1](https://pypi.org/project/apache-airflow/2.8.4rc1/) help test the RC.

Please let us know by commenting if the issue is addressed in the latest RC.

- [x] [Fix few typos in image documentation (#37714)](https://github.com/apache/airflow/pull/37714): @potiuk
- [x] [Limit `pandas` to `<2.2` (#37748)](https://github.com/apache/airflow/pull/37748): @Taragolis @aa-matthias
     Linked issues:
     - [SQLAlchemy / Pandas incompatibility (#37742)](https://github.com/apache/airflow/issues/37742)
- [x] [Fix hash caching in `ObjectStoragePath` (#37769)](https://github.com/apache/airflow/pull/37769): @Taragolis
- [ ] [Add padding to prevent grid horizontal scroll overlapping tasks (#37942)](https://github.com/apache/airflow/pull/37942): @bbovenzi
- [x] [Fix a bug where scheduler heartrate parameter were not used (#37992)](https://github.com/apache/airflow/pull/37992): @kosteev @potiuk
     Linked issues:
     - [Scheduler uses [scheduler]job_heartbeat_sec property for heartbeats instead of [scheduler]scheduler_heartbeat_sec (#37971)](https://github.com/apache/airflow/issues/37971)
     - [Decouple "job runner" from BaseJob ORM model (#30255)](https://github.com/apache/airflow/pull/30255)
- [x] [Workaround optional typing error detected by new typing-docutils (#38012)](https://github.com/apache/airflow/pull/38012): @potiuk
- [x] [Update documentation about recent image changes (#38085)](https://github.com/apache/airflow/pull/38085): @potiuk
- [x] [Limit importlib_resources as it breaks pytest_rewrites (#38095)](https://github.com/apache/airflow/pull/38095): @potiuk
- [x] [Fix task instances list link (#38096)](https://github.com/apache/airflow/pull/38096): @bbovenzi
- [ ] [Fix incorrect serialisation of the FixedTimezone (#38139)](https://github.com/apache/airflow/pull/38139): @millin
- [x] [Fix excessive permission changing for log task handler (#38164)](https://github.com/apache/airflow/pull/38164): @BretaGlac @potiuk
     Linked issues:
     - [Airflow changes permissions of home directory (#38137)](https://github.com/apache/airflow/issues/38137)
- [ ] [bump croniter to fix an issue with 29 Feb cron expressions (#38198)](https://github.com/apache/airflow/pull/38198): @lanhhv84 @hussein-awala
     Linked issues:
     - [DAGs scheduled on February 29th are not executed. (#38174)](https://github.com/apache/airflow/issues/38174)
- [ ] [Minor fixup on docker-stack changelog (#38293)](https://github.com/apache/airflow/pull/38293): @jedcunningham
- [x] [Lift the limit on importlib_resources library (#38294)](https://github.com/apache/airflow/pull/38294): @potiuk

Thanks to all who contributed to the release (probably not a complete list!):
@kosteev @BretaGlac @jedcunningham @bbovenzi @Taragolis @hussein-awala @potiuk @millin @lanhhv84 @aa-matthias

**Comment by Taragolis** [comment]
- #37748: Check Apache Airflow extras and Docker Images looks fine
- https://github.com/apache/airflow/pull/37769: Works as expected

**Comment by potiuk** [comment]
Tested / verified all my changes. Particularly tested well the propagation of permissions (#38164) and the scheduler heartrate change (#37992) - in various scenarios and those fixes are working as expected.
