### ISSUE TITLE
Status of testing of Apache Airflow Helm Chart 1.13.1rc1

### ISSUE THREAD

**Issue by jedcunningham** [apache/airflow#38382]
We are kindly requesting that contributors to [Apache Airflow Helm Chart 1.13.1rc1](https://dist.apache.org/repos/dist/dev/airflow/helm-chart/1.13.1rc1) help test the RC.

Please let us know by commenting if the issue is addressed in the latest RC.

- [x] [Chart: Fix cluster-wide RBAC naming clash when using multiple multiNamespace releases with the same name (#37197)](https://github.com/apache/airflow/pull/37197): @mewa
     Linked issues:
     - [Chart: Fix cluster-wide RBAC naming clash when using multiple multiNamespace releases with the same name (#31613)](https://github.com/apache/airflow/pull/31613)
- [ ] [Don't overwrite .Values.airflowPodAnnotations (#37917)](https://github.com/apache/airflow/pull/37917): @brokenjacobs
- [ ] [Chart: Default airflow version to 2.8.3 (#38036)](https://github.com/apache/airflow/pull/38036): @ephraimbuddy

Thanks to all who contributed to the release (probably not a complete list!):
@ephraimbuddy @brokenjacobs @mewa

**Comment by brokenjacobs** [comment]
ok actually got the message this time! I'm testing this in a bit.

**Comment by brokenjacobs** [comment]
quay.io outage causing issues with the statsd container:
![image](https://github.com/apache/airflow/assets/3159463/562b91ea-2813-435e-80fb-396f489c00f2)
```
  Warning  Failed     15s                 kubelet                                Failed to pull image "quay.io/prometheus/statsd-exporter:v0.26.0": failed to pull and unpack image "quay.io/prometheus/statsd-exporter:v0.26.0": failed to copy: httpReadSeeker: failed open: unexpected status code https://quay.io/v2/prometheus/statsd-exporter/blobs/sha256:4f76ba478baf84e4e9091fe66b1e53b70d9f1dfa1bd0ce24fcd4aec18e0b3929: 502 Bad Gateway
```

**Comment by brokenjacobs** [comment]
LGTM!, keda bypass of pgbouncer is working as well.

**Comment by jedcunningham** [comment]
Thanks @brokenjacobs for testing. Release in progress 🍺

**Comment by mewa** [comment]
Looks good :+1:
