### ISSUE TITLE
Status of testing Providers that were prepared on April 10, 2024

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#38904]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [airbyte: 3.7.0rc1](https://pypi.org/project/apache-airflow-providers-airbyte/3.7.0rc1)
   - [ ] [Ensure Airbyte Provider is Compatible with Cloud and Config APIs (#37943)](https://github.com/apache/airflow/pull/37943): @chrishronek
     Linked issues:
       - [ ] [Linked Issue #35011](https://github.com/apache/airflow/issues/35011): @vytautasnord
   - [x] [fix: try002 for provider airbyte (#38786)](https://github.com/apache/airflow/pull/38786): @dondaum
     Linked issues:
       - [x] [Linked Issue #38761](https://github.com/apache/airflow/issues/38761): @Taragolis
   - [x] [add "return" statement to "yield" within a while loop in airbyte triggers (#38390)](https://github.com/apache/airflow/pull/38390): @Lee-W
## Provider [alibaba: 2.7.3rc1](https://pypi.org/project/apache-airflow-providers-alibaba/2.7.3rc1)
   - [ ] [Avoid use of `assert` outside of the tests (#37718)](https://github.com/apache/airflow/pull/37718): @Taragolis
## Provider [amazon: 8.20.0rc1](https://pypi.org/project/apache-airflow-providers-amazon/8.20.0rc1)
   - [ ] [AWS Batch Executor (#37618)](https://github.com/apache/airflow/pull/37618): @syedahsn
   - [ ] [Add fallback `region_name` value to AWS Executors (#38704)](https://github.com/apache/airflow/pull/38704): @Taragolis
   - [ ] [Introduce Amazon Bedrock service (#38602)](https://github.com/apache/airflow/pull/38602): @ferruzzi
   - [ ] [Amazon Bedrock - Model Customization Jobs (#38693)](https://github.com/apache/airflow/pull/38693): @ferruzzi
   - [ ] [ECS Executor - add support to adopt orphaned tasks. (#37786)](https://github.com/apache/airflow/pull/37786): @ferruzzi
     Linked issues:
       - [ ] [Linked Issue #35491](https://github.com/apache/airflow/issues/35491): @o-nikolas
   - [ ] [Update AWS auth manager CLI command to not disable AVP schema validation (#38301)](https://github.com/apache/airflow/pull/38301): @vincbeck
   - [x] [Reduce s3hook memory usage (#37886)](https://github.com/apache/airflow/pull/37886): @ellisms
     Linked issues:
       - [x] [Linked Issue #35449](https://github.com/apache/airflow/issues/35449): @Taragolis
   - [ ] [Add check in AWS auth manager to check if the Amazon Verified Permissions schema is up to date (#38333)](https://github.com/apache/airflow/pull/38333): @vincbeck
   - [x] [fix: EmrServerlessStartJobOperator not serializing DAGs correctly whe… (#38022)](https://github.com/apache/airflow/pull/38022): @jliu0812
     Linked issues:
       - [x] [Linked Issue #38005](https://github.com/apache/airflow/issues/38005): @jliu0812
   - [x] [add "return" statement to "yield" within a while loop in amazon triggers (#38396)](https://github.com/apache/airflow/pull/38396): @Lee-W
   - [ ] [Fix set deprecated amazon operators arguments in `MappedOperator` (#38346)](https://github.com/apache/airflow/pull/38346): @Taragolis
   - [ ] [`ECSExecutor` API Retry bug fix (#38118)](https://github.com/apache/airflow/pull/38118): @syedahsn
   - [ ] [Fix `region` argument in `MappedOperator` based on `AwsBaseOperator` / `AwsBaseSensor` (#38178)](https://github.com/apache/airflow/pull/38178): @Taragolis
   - [ ] [ECS Executor retry task bug fix (#37979)](https://github.com/apache/airflow/pull/37979): @syedahsn
   - [ ] [Fix init checks for aws redshift to s3 operator (#37861)](https://github.com/apache/airflow/pull/37861): @okirialbert
     Linked issues:
       - [ ] [Linked Issue #36484](https://github.com/apache/airflow/issues/36484): @shahar1
   - [ ] [Make the method `BaseAuthManager.is_authorized_custom_view` abstract (#37915)](https://github.com/apache/airflow/pull/37915): @vincbeck
   - [ ] [Replace "Role" by "Group" in AWS auth manager (#38078)](https://github.com/apache/airflow/pull/38078): @vincbeck
   - [ ] [Avoid use of `assert` outside of the tests (#37718)](https://github.com/apache/airflow/pull/37718): @Taragolis
   - [ ] [Use AwsLogsHook when fetching Glue job logs (#38010)](https://github.com/apache/airflow/pull/38010): @VincentChantreau
   - [ ] [Implement `filter_permitted_dag_ids` in AWS auth manager (#37666)](https://github.com/apache/airflow/pull/37666): @vincbeck
   - [ ] [AWS auth manager CLI: persist the policy store description when doing updates (#37946)](https://github.com/apache/airflow/pull/37946): @vincbeck
   - [ ] [Change f-string to formatting into the logging messages for Batch Executor (#37929)](https://github.com/apache/airflow/pull/37929): @Taragolis
## Provider [apache.beam: 5.6.3rc1](https://pypi.org/project/apache-airflow-providers-apache-beam/5.6.3rc1)
   - [x] [Fix skip Apache Beam pipeline options if value is set to false (#38496)](https://github.com/apache/airflow/pull/38496): @dondaum
     Linked issues:
       - [x] [Linked Issue #38457](https://github.com/apache/airflow/issues/38457): @gblazq
   - [x] [Fix side-effect of default options in Beam Operators (#37916)](https://github.com/apache/airflow/pull/37916): @potiuk
   - [ ] [Avoid to use subprocess in asyncio loop (#38292)](https://github.com/apache/airflow/pull/38292): @Taragolis
   - [ ] [Avoid change attributes into the constructor in Apache Beam operators (#37934)](https://github.com/apache/airflow/pull/37934): @Taragolis
## Provider [apache.cassandra: 3.4.2rc1](https://pypi.org/project/apache-airflow-providers-apache-cassandra/3.4.2rc1)
   - [x] [Re-enable cassandra for Python 3.12 after the driver got libev support (#38314)](https://github.com/apache/airflow/pull/38314): @potiuk
## Provider [apache.hive: 8.0.0rc1](https://pypi.org/project/apache-airflow-providers-apache-hive/8.0.0rc1)
   - [x] [Setting use_beeline by default for hive cli connection (#38763)](https://github.com/apache/airflow/pull/38763): @amoghrajesh
   - [x] [Removing deprecated code in hive provider (#38859)](https://github.com/apache/airflow/pull/38859): @amoghrajesh
   - [x] [Adding support to hive hook for high availability Hive installations (#38651)](https://github.com/apache/airflow/pull/38651): @amoghrajesh
   - [x] [Fix TRY002 for apache hive provider (#38781)](https://github.com/apache/airflow/pull/38781): @amoghrajesh
   - [ ] [Fix deprecated apache.hive operators arguments in `MappedOperator` (#38351)](https://github.com/apache/airflow/pull/38351): @Taragolis
## Provider [apache.spark: 4.7.2rc1](https://pypi.org/project/apache-airflow-providers-apache-spark/4.7.2rc1)
   - [ ] [Rename `SparkSubmitOperator`/`SparkJDBCOperator` fields' names to comply with templated fields validation (#38051)](https://github.com/apache/airflow/pull/38051): @shahar1
     Linked issues:
       - [ ] [Linked Issue #36484](https://github.com/apache/airflow/issues/36484): @shahar1
   - [ ] [Rename `SparkSqlOperator`'s field to comply with templated fields' validation (#38045)](https://github.com/apache/airflow/pull/38045): @shahar1
     Linked issues:
       - [ ] [Linked Issue #36484](https://github.com/apache/airflow/issues/36484): @shahar1
## Provider [celery: 3.6.2rc1](https://pypi.org/project/apache-airflow-providers-celery/3.6.2rc1)
   - [ ] [Ensure __exit__ is called in decorator context managers (#38383)](https://github.com/apache/airflow/pull/38383): @dstandish
     Linked issues:
       - [ ] [Linked Issue #36800](https://github.com/apache/airflow/pull/36800): @joaopamaral
   - [ ] [Don't dispose sqlalchemy engine when using internal api (std task runner) (#38562)](https://github.com/apache/airflow/pull/38562): @dstandish
   - [x] [Use celery worker CLI from Airflow package for Airflow < 2.8.0 (#38879)](https://github.com/apache/airflow/pull/38879): @potiuk
     Linked issues:
       - [x] [Linked Issue #34945](https://github.com/apache/airflow/pull/34945): @Bisk1
       - [x] [Linked Issue #36794](https://github.com/apache/airflow/pull/36794): @pavansharma36
   - [ ] [Allow to use redis>=5 (#38385)](https://github.com/apache/airflow/pull/38385): @Taragolis
   - [ ] [Re-raise of AirflowOptionalProviderFeatureException should be direct (#38555)](https://github.com/apache/airflow/pull/38555): @dstandish
## Provider [cncf.kubernetes: 8.1.0rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/8.1.0rc1)
   - [ ] [KPO Add follow log in termination step (#38081)](https://github.com/apache/airflow/pull/38081): @pankajastro
   - [ ] [Add GKECreateCustomResourceOperator and GKEDeleteCustomResourceOperator operators (#37616)](https://github.com/apache/airflow/pull/37616): @MaksYermak
   - [x] [Implement deferrable mode for KubernetesJobOperator (#38251)](https://github.com/apache/airflow/pull/38251): @moiseenkov
   - [ ] [Create KubernetesPatchJobOperator operator (#38146)](https://github.com/apache/airflow/pull/38146): @MaksYermak
   - [x] [Implement delete_on_status parameter for KubernetesDeleteJobOperator (#38458)](https://github.com/apache/airflow/pull/38458): @moiseenkov
   - [x] [Implement deferrable mode for GKEStartJobOperator (#38454)](https://github.com/apache/airflow/pull/38454): @moiseenkov
   - [ ] [Use startup_check_interval_seconds instead of poll_interval to check pod while startup (#38075)](https://github.com/apache/airflow/pull/38075): @pankajastro
   - [x] [Implement wait_until_job_complete parameter for KubernetesJobOperator (#37998)](https://github.com/apache/airflow/pull/37998): @moiseenkov
   - [x] [Use SIGINT signal number instead of signal name (#37905)](https://github.com/apache/airflow/pull/37905): @pdebelak
     Linked issues:
       - [x] [Linked Issue #37903](https://github.com/apache/airflow/issues/37903): @pdebelak
   - [x] [Fix spark operator log retrieval from driver (#38106)](https://github.com/apache/airflow/pull/38106): @sudohainguyen
     Linked issues:
       - [x] [Linked Issue #37681](https://github.com/apache/airflow/issues/37681): @thispejo
   - [x] [Fix dynamic allocation specs handling for custom launcher (#38223)](https://github.com/apache/airflow/pull/38223): @sudohainguyen
   - [ ] [Fix case if `SparkKubernetesOperator.application_file` is templated file (#38035)](https://github.com/apache/airflow/pull/38035): @Taragolis
     Linked issues:
       - [ ] [Linked Issue #38017](https://github.com/apache/airflow/issues/38017): @gbloisi-openaire
   - [ ] [fix: reduce irrelevant error logs for pod events. (#37944)](https://github.com/apache/airflow/pull/37944): @sudiptob2
     Linked issues:
       - [ ] [Linked Issue #36077](https://github.com/apache/airflow/issues/36077): @ketozhang
   - [ ] [Add GKEListJobsOperator and GKEDescribeJobOperator (#37598)](https://github.com/apache/airflow/pull/37598): @VladaZakharova
   - [ ] [removed usage of deprecated function  for naming the pod in provider k8s pod.py (#38638)](https://github.com/apache/airflow/pull/38638): @idantepper
   - [ ] [Create DeleteKubernetesJobOperator and GKEDeleteJobOperator operators (#37793)](https://github.com/apache/airflow/pull/37793): @MaksYermak
   - [x] [Refactor GKE hooks (#38404)](https://github.com/apache/airflow/pull/38404): @moiseenkov
## Provider [cohere: 1.1.3rc1](https://pypi.org/project/apache-airflow-providers-cohere/1.1.3rc1)
   - [ ] [Limit `cohere` to <5 (#38348)](https://github.com/apache/airflow/pull/38348): @Taragolis
## Provider [common.io: 1.3.1rc1](https://pypi.org/project/apache-airflow-providers-common-io/1.3.1rc1)
   - [ ] [Improve XComObjectStoreBackend implementation (#38608)](https://github.com/apache/airflow/pull/38608): @uranusjr
   - [ ] [Rename to XComObjectStorageBackend (#38607)](https://github.com/apache/airflow/pull/38607): @uranusjr
     Linked issues:
       - [ ] [Linked Issue #38142](https://github.com/apache/airflow/pull/38142): @pankajastro
   - [ ] [Turn common.io xcom exception into OptionalProviderFeatureException (#38543)](https://github.com/apache/airflow/pull/38543): @potiuk
   - [ ] [Update ObjectStoragePath for universal_pathlib>=v0.2.2 (#37930)](https://github.com/apache/airflow/pull/37930): @bolkedebruin
## Provider [common.sql: 1.12.0rc1](https://pypi.org/project/apache-airflow-providers-common-sql/1.12.0rc1)
   - [ ] [Add hook_params to template_fields for BaseSQLOperator-related Operators (#38724)](https://github.com/apache/airflow/pull/38724): @odaneau-astro
   - [ ] [Make `placeholder` of DbApiHook configurable in UI (#38528)](https://github.com/apache/airflow/pull/38528): @dabla
     Linked issues:
       - [ ] [Linked Issue #36000](https://github.com/apache/airflow/pull/36000): @jarnedemunter1
   - [ ] [Undeprecating `DBApiHookForTests._make_common_data_structure` (#38573)](https://github.com/apache/airflow/pull/38573): @Taragolis
## Provider [databricks: 6.3.0rc1](https://pypi.org/project/apache-airflow-providers-databricks/6.3.0rc1)
   - [x] [Add cancel_previous_run to DatabricksRunNowOperator (#38702)](https://github.com/apache/airflow/pull/38702): @SubhamSinghal
   - [ ] [add repair_run support to DatabricksRunNowOperator in deferrable mode (#38619)](https://github.com/apache/airflow/pull/38619): @Lee-W
     Linked issues:
       - [ ] [Linked Issue #38619](https://github.com/apache/airflow/pull/38619): @Lee-W
   - [x] [Update ACL during job reset (#38741)](https://github.com/apache/airflow/pull/38741): @SubhamSinghal
   - [x] [remove redundant else block in DatabricksExecutionTrigger (#38397)](https://github.com/apache/airflow/pull/38397): @Lee-W
   - [ ] [Rename `DatabricksSqlOperator`'s fields' names to comply with templated fields validation (#38052)](https://github.com/apache/airflow/pull/38052): @shahar1
     Linked issues:
       - [ ] [Linked Issue #36484](https://github.com/apache/airflow/issues/36484): @shahar1
## Provider [dbt.cloud: 3.7.1rc1](https://pypi.org/project/apache-airflow-providers-dbt-cloud/3.7.1rc1)
   - [x] [[OpenLineage] fix: disabled_for_operators now stops whole event emission  (#38033)](https://github.com/apache/airflow/pull/38033): @kacpermuda
   - [x] [add "return" statement to "yield" within a while loop in dbt triggers (#38395)](https://github.com/apache/airflow/pull/38395): @Lee-W
## Provider [docker: 3.10.0rc2](https://pypi.org/project/apache-airflow-providers-docker/3.10.0rc2)
   - [ ] [Support multiple Docker hosts in `docker_url` attribute. (#38466)](https://github.com/apache/airflow/pull/38466): @oboki
   - [ ] [Fix deprecated `DockerOperator` operator arguments in `MappedOperator` (#38379)](https://github.com/apache/airflow/pull/38379): @Taragolis
   - [ ] [Remove redundant usage of `importlib_metadata` for distribution versions (#38368)](https://github.com/apache/airflow/pull/38368): @Taragolis
   - [ ] [DockerOperator: use DOCKER_HOST as default for docker_url (#38387)](https://github.com/apache/airflow/pull/38387): @maresb
## Provider [elasticsearch: 5.3.4rc1](https://pypi.org/project/apache-airflow-providers-elasticsearch/5.3.4rc1)
   - [ ] [Add missing attrs / correct bad attrs on TaskInstancePydantic (#37854)](https://github.com/apache/airflow/pull/37854): @dstandish
## Provider [fab: 1.0.3rc1](https://pypi.org/project/apache-airflow-providers-fab/1.0.3rc1)
   - [ ] [Rename `allowed_filter_attrs` to `allowed_sort_attrs` (#38626)](https://github.com/apache/airflow/pull/38626): @jedcunningham
   - [x] [Fix azure authentication when no email is set (#38872)](https://github.com/apache/airflow/pull/38872): @gschuurman
## Provider [ftp: 3.8.0rc2](https://pypi.org/project/apache-airflow-providers-ftp/3.8.0rc2)
   - [x] [Add ssl context for verification of certs in FTPS hook (#38266)](https://github.com/apache/airflow/pull/38266): @amoghrajesh
## Provider [google: 10.17.0rc1](https://pypi.org/project/apache-airflow-providers-google/10.17.0rc1)
   - [ ] [Add `impersonation_scopes` to BigQuery (#38169)](https://github.com/apache/airflow/pull/38169): @ying-w
   - [x] [Deferrable mode for RunPipelineJobOperator (#37969)](https://github.com/apache/airflow/pull/37969): @e-galan
   - [ ] [Add GKECreateCustomResourceOperator and GKEDeleteCustomResourceOperator operators (#37616)](https://github.com/apache/airflow/pull/37616): @MaksYermak
   - [ ] [Add VertexAI Language Model and Multimodal Model Operators for Google Cloud Generative AI use (#37721)](https://github.com/apache/airflow/pull/37721): @CYarros10
   - [ ] [Add GKEListJobsOperator and GKEDescribeJobOperator (#37598)](https://github.com/apache/airflow/pull/37598): @VladaZakharova
   - [ ] [Create GKEStartKueueJobOperator operator (#37477)](https://github.com/apache/airflow/pull/37477): @MaksYermak
   - [ ] [Create DeleteKubernetesJobOperator and GKEDeleteJobOperator operators (#37793)](https://github.com/apache/airflow/pull/37793): @MaksYermak
   - [ ] [Update GCS hook to get crc32c hash for CMEK-protected objects (#38191)](https://github.com/apache/airflow/pull/38191): @shahar1
     Linked issues:
       - [ ] [Linked Issue #34980](https://github.com/apache/airflow/issues/34980): @dmedora
       - [ ] [Linked Issue #34982](https://github.com/apache/airflow/pull/34982): @dmedora
   - [x] [Set job labels for traceability in BigQuery jobs (#37736)](https://github.com/apache/airflow/pull/37736): @stiak
   - [x] [Deferrable mode for CreateBatchPredictionJobOperator (#37818)](https://github.com/apache/airflow/pull/37818): @moiseenkov
   - [ ] [Fix BigQuery connection and add docs (#38430)](https://github.com/apache/airflow/pull/38430): @shahar1
     Linked issues:
       - [ ] [Linked Issue #28790](https://github.com/apache/airflow/issues/28790): @Taragolis
   - [ ] [fix(google,log): Avoid log name overriding (#38071)](https://github.com/apache/airflow/pull/38071): @AlexisBRENON
   - [ ] [Fix credentials error for S3ToGCSOperator trigger (#37518)](https://github.com/apache/airflow/pull/37518): @korolkevich
     Linked issues:
       - [ ] [Linked Issue #37331](https://github.com/apache/airflow/issues/37331): @aviramst
   - [ ] [Fix `parent_model` parameter in GCP Vertex AI AutoML and Custom Job operators (#38417)](https://github.com/apache/airflow/pull/38417): @shahar1
     Linked issues:
       - [ ] [Linked Issue #37400](https://github.com/apache/airflow/issues/37400): @devinmnorris
   - [x] [add "return" statement to "yield" within a while loop in google triggers (#38394)](https://github.com/apache/airflow/pull/38394): @Lee-W
   - [ ] [Fix cursor unique name surpasses Postgres identifier limit in `PostgresToGCSOperator` (#38040)](https://github.com/apache/airflow/pull/38040): @dybolo
     Linked issues:
       - [ ] [Linked Issue #37654](https://github.com/apache/airflow/issues/37654): @obarisk
   - [ ] [Fix GCS Anonymous user issue because none token (#38102)](https://github.com/apache/airflow/pull/38102): @pankajastro
   - [ ] [Fix BigQueryTablePartitionExistenceTrigger partition query (#37655)](https://github.com/apache/airflow/pull/37655): @Silviu-Surcica
   - [x] [Add google-cloud-bigquery as explicit google-provider dependency (#38753)](https://github.com/apache/airflow/pull/38753): @potiuk
   - [ ] [Avoid to use `functools.lru_cache` in class methods in `google` provider (#38652)](https://github.com/apache/airflow/pull/38652): @Taragolis
   - [x] [Refactor GKE hooks (#38404)](https://github.com/apache/airflow/pull/38404): @moiseenkov
   - [ ] [Remove unused loop variable from airflow package (#38308)](https://github.com/apache/airflow/pull/38308): @hussein-awala
   - [ ] [templated fields logic checks for cloud_storage_transfer_service (#37519)](https://github.com/apache/airflow/pull/37519): @okirialbert
   - [ ] [Rename `MLEngine` operators' fields' names to comply with templated fields validation (#38053)](https://github.com/apache/airflow/pull/38053): @shahar1
     Linked issues:
       - [ ] [Linked Issue #36484](https://github.com/apache/airflow/issues/36484): @shahar1
   - [ ] [Rename Vertex AI AutoML operators fields' names to comply with templated fields validation (#38049)](https://github.com/apache/airflow/pull/38049): @shahar1
     Linked issues:
       - [ ] [Linked Issue #36484](https://github.com/apache/airflow/issues/36484): @shahar1
   - [ ] [Rename `DeleteCustomTrainingJobOperator`'s fields' names to comply with templated fields validation (#38048)](https://github.com/apache/airflow/pull/38048): @shahar1
     Linked issues:
       - [ ] [Linked Issue #36484](https://github.com/apache/airflow/issues/36484): @shahar1
   - [ ] [Restore delegate_to for Google Transfer Operators retrieving from Google Cloud. (#37925)](https://github.com/apache/airflow/pull/37925): @emery-finkelstein
     Linked issues:
       - [ ] [Linked Issue #29088](https://github.com/apache/airflow/pull/29088): @shahar1
       - [ ] [Linked Issue #30748](https://github.com/apache/airflow/pull/30748): @shahar1
   - [x] [Deprecate sync parameter for CreateHyperparameterTuningJobOperator (#37938)](https://github.com/apache/airflow/pull/37938): @moiseenkov
   - [ ] [Upgrade google-ads version (#37787)](https://github.com/apache/airflow/pull/37787): @molcay
## Provider [http: 4.10.1rc1](https://pypi.org/project/apache-airflow-providers-http/4.10.1rc1)
   - [x] [add "return" statement to "yield" within a while loop in http triggers (#38392)](https://github.com/apache/airflow/pull/38392): @Lee-W
   - [ ] [Consolidate HttpOperator http request between sync and async mode (#37293)](https://github.com/apache/airflow/pull/37293): @hussein-awala
     Linked issues:
       - [ ] [Linked Issue #37291](https://github.com/apache/airflow/issues/37291): @dlesco
## Provider [microsoft.azure: 10.0.0rc1](https://pypi.org/project/apache-airflow-providers-microsoft-azure/10.0.0rc1)
   - [ ] [Feature/refactor azure synapse pipeline class (#38723)](https://github.com/apache/airflow/pull/38723): @romsharon98
   - [ ] [Add `ADLSCreateObjectOperator` (#37821)](https://github.com/apache/airflow/pull/37821): @dabla
   - [x] [add "return" statement to "yield" within a while loop in azure triggers (#38393)](https://github.com/apache/airflow/pull/38393): @Lee-W
   - [ ] [fix cosmos hook static checks by making providing partition_key mandatory (#38199)](https://github.com/apache/airflow/pull/38199): @hussein-awala
     Linked issues:
       - [ ] [Linked Issue #38196](https://github.com/apache/airflow/issues/38196): @Taragolis
   - [ ] [refactor: Refactored __new__ magic method of BaseOperatorMeta to avoid bad mixing classic and decorated operators (#37937)](https://github.com/apache/airflow/pull/37937): @dabla
   - [ ] [update to latest service bus library (#38384)](https://github.com/apache/airflow/pull/38384): @swathipil
     Linked issues:
       - [ ] [Linked Issue #31168](https://github.com/apache/airflow/pull/31168): @kashifkhan
   - [ ] [Limit azure-cosmos<4.6.0 (#38175)](https://github.com/apache/airflow/pull/38175): @eladkal
## Provider [microsoft.psrp: 2.6.1rc1](https://pypi.org/project/apache-airflow-providers-microsoft-psrp/2.6.1rc1)
   - [ ] [Avoid use of `assert` outside of the tests (#37718)](https://github.com/apache/airflow/pull/37718): @Taragolis
## Provider [odbc: 4.5.0rc1](https://pypi.org/project/apache-airflow-providers-odbc/4.5.0rc1)
   - [x] [Make `placeholder` of DbApiHook configurable in UI (#38528)](https://github.com/apache/airflow/pull/38528): @dabla
     Linked issues:
       - [x] [Linked Issue #36000](https://github.com/apache/airflow/pull/36000): @jarnedemunter1
## Provider [openlineage: 1.7.0rc1](https://pypi.org/project/apache-airflow-providers-openlineage/1.7.0rc1)
   - [ ] [Add lineage_job_namespace and lineage_job_name OpenLineage macros (#38829)](https://github.com/apache/airflow/pull/38829): @dolfinus
   - [ ] [openlineage: add `opt-in` option (#37725)](https://github.com/apache/airflow/pull/37725): @JDarDagran
   - [x] [[OpenLineage] Remove redundant operator information from facets (#38264)](https://github.com/apache/airflow/pull/38264): @kacpermuda
   - [x] [[OpenLineage] fix: disabled_for_operators now stops whole event emission  (#38033)](https://github.com/apache/airflow/pull/38033): @kacpermuda
   - [x] [[OpenLineage] fix: Add fallbacks when retrieving Airflow configuration to avoid errors being raised (#37994)](https://github.com/apache/airflow/pull/37994): @kacpermuda
   - [x] [[OpenLineage] fix: Fix parent id macro and remove unused utils (#37877)](https://github.com/apache/airflow/pull/37877): @kacpermuda
   - [ ] [Avoid use of `assert` outside of the tests (#37718)](https://github.com/apache/airflow/pull/37718): @Taragolis
   - [ ] [Add missing attrs / correct bad attrs on TaskInstancePydantic (#37854)](https://github.com/apache/airflow/pull/37854): @dstandish
## Provider [papermill: 3.6.2rc1](https://pypi.org/project/apache-airflow-providers-papermill/3.6.2rc1)
   - [x] [Turn Pydantic into an optional dependency (#37320)](https://github.com/apache/airflow/pull/37320): @potiuk
## Provider [redis: 3.6.1rc1](https://pypi.org/project/apache-airflow-providers-redis/3.6.1rc1)
   - [ ] [Allow to use redis>=5 (#38385)](https://github.com/apache/airflow/pull/38385): @Taragolis
## Provider [samba: 4.6.0rc2](https://pypi.org/project/apache-airflow-providers-samba/4.6.0rc2)
   - [ ] [Allow specification of buffer length for GCS to Samba (#38373)](https://github.com/apache/airflow/pull/38373): @collinmcnulty
## Provider [sftp: 4.9.1rc1](https://pypi.org/project/apache-airflow-providers-sftp/4.9.1rc1)
   - [x] [add "return" statement to "yield" within a while loop in sftp triggers (#38391)](https://github.com/apache/airflow/pull/38391): @Lee-W
   - [x] [Close open connections for deferrable SFTPSensor (#38881)](https://github.com/apache/airflow/pull/38881): @pankajkoti
## Provider [slack: 8.6.2rc1](https://pypi.org/project/apache-airflow-providers-slack/8.6.2rc1)
   - [ ] [Fix set deprecated slack operators arguments in `MappedOperator` (#38345)](https://github.com/apache/airflow/pull/38345): @Taragolis
   - [ ] [Update SqlToSlackApiFileOperator with new param to check empty output (#38079)](https://github.com/apache/airflow/pull/38079): @andyguwc
## Provider [snowflake: 5.4.0rc1](https://pypi.org/project/apache-airflow-providers-snowflake/5.4.0rc1)
   - [ ] [feat: update SnowflakeSqlApiHook to support OAuth (#37922)](https://github.com/apache/airflow/pull/37922): @andyguwc
   - [ ] [Remove reference to execution_info in snowflake hook docstring (#37804)](https://github.com/apache/airflow/pull/37804): @remisalmon
## Provider [weaviate: 1.3.4rc1](https://pypi.org/project/apache-airflow-providers-weaviate/1.3.4rc1)
   - [ ] [Fix `WeaviateIngestOperator`/`WeaviateDocumentIngestOperator` arguments in `MappedOperator` (#38402)](https://github.com/apache/airflow/pull/38402): @Taragolis
## Provider [yandex: 3.9.1rc1](https://pypi.org/project/apache-airflow-providers-yandex/3.9.1rc1)
   - [ ] [[yandexcloud/yq] support iam token from metadata, simplify code (#38411)](https://github.com/apache/airflow/pull/38411): @uzhastik
   - [ ] [Avoid use of `assert` outside of the tests (#37718)](https://github.com/apache/airflow/pull/37718): @Taragolis

All users involved in the PRs:
@ferruzzi @dondaum @potiuk @sudiptob2 @eladkal @korolkevich @bolkedebruin @dolfinus @stiak @Lee-W @AlexisBRENON @molcay @dabla @dybolo @shahar1 @e-galan @CYarros10 @chrishronek @amoghrajesh @romsharon98

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by pdebelak** [comment]
I can confirm that my change to cncf.kubernetes is working as expected.

**Comment by Taragolis** [comment]
Just figure out that we accidentally exclude https://github.com/apache/airflow/pull/37458 from the changelog. We could add it after the release, because changes itself presented into the released package.

**Comment by gschuurman** [comment]
#38872 login is working as expected again with both email set and unset

**Comment by ellisms** [comment]
#37886 is good.

**Comment by jliu0812** [comment]
[#38022](https://github.com/apache/airflow/pull/38022) is good. ✅

**Comment by stiak** [comment]
#37736 is good.
![Notification_Center](https://github.com/apache/airflow/assets/345934/9da55450-9541-4beb-a813-c6c70b983830)

**Comment by sudohainguyen** [comment]
#38223 and #38106 are good ✅

**Comment by SubhamSinghal** [comment]
Added a fix for #38741 in #38918. There was an extra slash in api.

**Comment by dondaum** [comment]
#38786  and #38496 are good ✅

**Comment by potiuk** [comment]
Checcked all my changes : all good !

**Comment by moiseenkov** [comment]
#38251, #38458, #38454, #37998, #38404, #37818, #38404, #37938 work as expected

**Comment by pankajkoti** [comment]
Checked SFTP provider for https://github.com/apache/airflow/pull/38881 and is good!

**Comment by eladkal** [comment]
> Added a fix for https://github.com/apache/airflow/pull/38741 in https://github.com/apache/airflow/pull/38918. There was an extra slash in api.

Databricks provider will be excluded from RC1

**Comment by kacpermuda** [comment]
I checked the whole OpenLineage provider + my PR for dbt.cloud #38033 - all is good.

**Comment by e-galan** [comment]
#37969 is good.

**Comment by dabla** [comment]
Just tested [#38528](https://github.com/apache/airflow/pull/38528) and I confirm it is working with ODBC as well as JDBC.

**Comment by amoghrajesh** [comment]
Installed and RC with breeze and tested my changes:
- Setting use_beeline by default for hive cli connection (#38763)
- Removing deprecated code in hive provider (#38859)
- Adding support to hive hook for high availability Hive installations (#38651)
- Fix TRY002 for apache hive provider (#38781)
- Add ssl context for verification of certs in FTPS hook (#38266)


All these changes are working as expected.

**Comment by Lee-W** [comment]
Verified #38390, https://github.com/apache/airflow/pull/38396/, https://github.com/apache/airflow/pull/38397/, https://github.com/apache/airflow/pull/38394/, https://github.com/apache/airflow/pull/38392/, https://github.com/apache/airflow/pull/38393/, https://github.com/apache/airflow/pull/38391/

**Comment by eladkal** [comment]
Thank you everyone. Providers are released.
yandex and databricks providers are excluded and will followup with rc2

I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).

**Comment by molcay** [comment]
The changes in #37787 works as expected
