### ISSUE TITLE
Status of testing Providers that were prepared on April 13, 2024

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#38997]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [databricks: 6.3.0rc2](https://pypi.org/project/apache-airflow-providers-databricks/6.3.0rc2)
   - [x] [Add cancel_previous_run to DatabricksRunNowOperator (#38702)](https://github.com/apache/airflow/pull/38702): @SubhamSinghal
   - [ ] [add repair_run support to DatabricksRunNowOperator in deferrable mode (#38619)](https://github.com/apache/airflow/pull/38619): @Lee-W
     Linked issues:
       - [ ] [Linked Issue #38619](https://github.com/apache/airflow/pull/38619): @Lee-W
   - [x] [Update ACL during job reset (#38741)](https://github.com/apache/airflow/pull/38741): @SubhamSinghal
   - [x] [Remove extra slash from update permission endpoint (#38918)](https://github.com/apache/airflow/pull/38918): @SubhamSinghal
   - [ ] [remove redundant else block in DatabricksExecutionTrigger (#38397)](https://github.com/apache/airflow/pull/38397): @Lee-W
   - [ ] [Rename `DatabricksSqlOperator`'s fields' names to comply with templated fields validation (#38052)](https://github.com/apache/airflow/pull/38052): @shahar1
     Linked issues:
       - [ ] [Linked Issue #36484](https://github.com/apache/airflow/issues/36484): @shahar1
## Provider [yandex: 3.10.0rc2](https://pypi.org/project/apache-airflow-providers-yandex/3.10.0rc2)
   - [ ] [Add Yandex Query support from Yandex.Cloud (#37458)](https://github.com/apache/airflow/pull/37458): @uzhastik
   - [ ] [[yandexcloud/yq] support iam token from metadata, simplify code (#38411)](https://github.com/apache/airflow/pull/38411): @uzhastik
   - [ ] [Avoid use of `assert` outside of the tests (#37718)](https://github.com/apache/airflow/pull/37718): @Taragolis

All users involved in the PRs:
@Lee-W @SubhamSinghal @uzhastik @shahar1 @Taragolis

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by pankajkoti** [comment]
For the databricks provider, for PRs #38741 and #38918 to work well, we would need PR #38692 to be included as well

cc: @SubhamSinghal @Lee-W

**Comment by eladkal** [comment]
> For the databricks provider, for PRs #38741 and #38918 to work well, we would need PR #38962 to be included as well 😐
> 
> cc: @SubhamSinghal @Lee-W

Why? It looks like a feature not a fix to regression from rc1

**Comment by pankajkoti** [comment]
> Why? It looks like a feature not a fix to regression from rc1

It's that the work done in PR #38741 contained a couple of issues of which one was fixed in #38918 , however the work that has been done in #38741 will not work as expected due to another issue which is getting fixed in #38962 . Essentially, the permissions endpoint call introduced in #38741 expects a job ID which was missing in it, and PR #38962 fixes that. So it will be like if we do not include #38962 , we're releasing #38741 which we know has an issue/bug.

**Comment by eladkal** [comment]
Thanks for the explnation. I will exclude databricks and prepare RC3.
Can you handle the review/merge of the needed PR?

**Comment by Lee-W** [comment]
@eladkal Just reviewed and merged https://github.com/apache/airflow/pull/38962

**Comment by SubhamSinghal** [comment]
Testes #38702, working as expected.

**Comment by eladkal** [comment]
Thank you everyone. Providers are released.
databricks provider is excluded and will have RC3

I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
