### ISSUE TITLE
Status of testing Providers that were prepared on April 16, 2024

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#39063]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [cncf.kubernetes: 8.1.1rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/8.1.1rc1)
   - [x] [Avoid logging empty line KPO (#38247)](https://github.com/apache/airflow/pull/38247): @pankajastro
## Provider [databricks: 6.3.0rc3](https://pypi.org/project/apache-airflow-providers-databricks/6.3.0rc3)
PRs that were tested in RC2 are automatically marked as tested yet feel free to retest
   - [x] [Add cancel_previous_run to DatabricksRunNowOperator (#38702)](https://github.com/apache/airflow/pull/38702): @SubhamSinghal
   - [x] [add repair_run support to DatabricksRunNowOperator in deferrable mode (#38619)](https://github.com/apache/airflow/pull/38619): @Lee-W
     Linked issues:
       - [x] [Linked Issue #38619](https://github.com/apache/airflow/pull/38619): @Lee-W
   - [x] [Adds job_id as path param in update permission (#38962)](https://github.com/apache/airflow/pull/38962): @SubhamSinghal
   - [x] [Fix remaining D401 checks (#37434)](https://github.com/apache/airflow/pull/37434): @rawwar
     Linked issues:
       - [x] [Linked Issue #37256](https://github.com/apache/airflow/issues/37256): @Taragolis
   - [x] [Update ACL during job reset (#38741)](https://github.com/apache/airflow/pull/38741): @SubhamSinghal
   - [x] [Remove extra slash from update permission endpoint (#38918)](https://github.com/apache/airflow/pull/38918): @SubhamSinghal
   - [ ] [[FIX] typo in parameter (#39050)](https://github.com/apache/airflow/pull/39050): @gaurav7261
   - [x] [remove redundant else block in DatabricksExecutionTrigger (#38397)](https://github.com/apache/airflow/pull/38397): @Lee-W
   - [x] [Rename `DatabricksSqlOperator`'s fields' names to comply with templated fields validation (#38052)](https://github.com/apache/airflow/pull/38052): @shahar1
     Linked issues:
       - [x] [Linked Issue #36484](https://github.com/apache/airflow/issues/36484): @shahar1
## Provider [fab: 1.0.4rc1](https://pypi.org/project/apache-airflow-providers-fab/1.0.4rc1)
   - [x] [Remove button for reset my password when we have reset password (#38957)](https://github.com/apache/airflow/pull/38957): @amoghrajesh
     Linked issues:
       - [x] [Linked Issue #38922](https://github.com/apache/airflow/issues/38922): @amoghrajesh

All users involved in the PRs:
@shahar1 @amoghrajesh @SubhamSinghal @pankajastro @rawwar @Lee-W @gaurav7261

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by SubhamSinghal** [comment]
#38962 is working as expected

**Comment by rawwar** [comment]
#37434  is just lint fixes. Nothing to be tested

**Comment by Lee-W** [comment]
Tested and verified #38619, 38397

**Comment by amoghrajesh** [comment]
@eladkal https://github.com/apache/airflow/pull/38957 works as expected. I can see only one button for reset password as expected.
![image](https://github.com/apache/airflow/assets/35884252/220b62c2-7769-40c2-91d5-7e495137b361)

**Comment by pankajastro** [comment]
https://github.com/apache/airflow/pull/38247 looks good

**Comment by eladkal** [comment]
Thank you everyone. Providers are released.

I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
