### ISSUE TITLE
Status of testing of Apache Airflow 2.9.1rc2

### ISSUE THREAD

**Issue by ephraimbuddy** [apache/airflow#39326]
### Body

We are kindly requesting that contributors to [Apache Airflow RC 2.9.1rc2](https://pypi.org/project/apache-airflow/2.9.1rc1/) help test the RC.

Please let us know by commenting if the issue is addressed in the latest RC.

- [x] [Use `methodtools.lru_cache` instead of `functools.lru_cache` in class methods (#37757)](https://github.com/apache/airflow/pull/37757): @Taragolis
- [ ] [fix(google,log): Avoid log name overriding (#38071)](https://github.com/apache/airflow/pull/38071): @AlexisBRENON
- [ ] [Hide internals of some groupped workflows (#38604)](https://github.com/apache/airflow/pull/38604): @potiuk
- [x] [Avoid to use `functools.lru_cache` in class methods in `google` provider (#38652)](https://github.com/apache/airflow/pull/38652): @Taragolis
- [x] [Raise deprecated warning in `airflow dags backfill` only if `-I`/`--ignore-first-depends-on-past` provided (#38676)](https://github.com/apache/airflow/pull/38676): @Taragolis
     Linked issues:
     - [Follow zero internal warning in unit tests (#38642)](https://github.com/apache/airflow/issues/38642)
- [ ] [Fix kubeconform pre-commit to not leave around containers (#38688)](https://github.com/apache/airflow/pull/38688): @jedcunningham
- [ ] [Use async db calls in WorkflowTrigger (#38689)](https://github.com/apache/airflow/pull/38689): @Taragolis @stevenschaerer
     Linked issues:
     - [Avoid to use sync (with blocking io) functions into the `WorkflowTrigger` (#38672)](https://github.com/apache/airflow/issues/38672)
- [ ] [Improve audit log events filter (#38719)](https://github.com/apache/airflow/pull/38719): @bbovenzi
- [ ] [bump uv to 0.1.29 (#38758)](https://github.com/apache/airflow/pull/38758): @hussein-awala
- [ ] [update edge label image in documentation example with the new graph view (#38802)](https://github.com/apache/airflow/pull/38802): @idantepper
- [ ] [Add FAB provider to Airflow extras in the image (#38824)](https://github.com/apache/airflow/pull/38824): @ephraimbuddy
- [ ] [Workaround occasional failures of docker system prune in public runners (#38825)](https://github.com/apache/airflow/pull/38825): @potiuk
- [ ] [Fix typo in templates-ref.rst (#38865)](https://github.com/apache/airflow/pull/38865): @alxkolm
- [ ] [Fix dag run link params (#38873)](https://github.com/apache/airflow/pull/38873): @bbovenzi
- [ ] [bump uv to 0.1.32 (#38874)](https://github.com/apache/airflow/pull/38874): @hussein-awala
- [x] [Fix problem that links in legacy log view can not be clicked (#38882)](https://github.com/apache/airflow/pull/38882): @jscheffl
- [x] [Bugfix: Move rendering of `map_index_template` so it renders for failed tasks as long as it was defined before the point of failure (#38902)](https://github.com/apache/airflow/pull/38902): @TJaniF
- [x] [Fix built query with implicit cartessian product in `AirflowSecurityManagerV2` (#38913)](https://github.com/apache/airflow/pull/38913): @Taragolis
- [ ] [Don't wait for lock on DagRun in mini scheduler (#38914)](https://github.com/apache/airflow/pull/38914): @dstandish
- [x] [Fix `SAWarning` 'Coercing Subquery object into a select() for use in IN()' (#38926)](https://github.com/apache/airflow/pull/38926): @Taragolis
- [ ] [Update build dependencies to their latest versions (#38930)](https://github.com/apache/airflow/pull/38930): @potiuk
- [ ] [Graph view improvements (#38940)](https://github.com/apache/airflow/pull/38940): @bbovenzi
- [ ] [Fix dag run selection (#38941)](https://github.com/apache/airflow/pull/38941): @bbovenzi
- [ ] [Fix calendar view with no DAG Run. (#38964)](https://github.com/apache/airflow/pull/38964): @tirkarthi
     Linked issues:
     - [Calendar view is broken for dags with no dagrun (#38875)](https://github.com/apache/airflow/issues/38875)
- [ ] [Changed color of extra tasks to a readable color (#38969)](https://github.com/apache/airflow/pull/38969): @idantepper @Timelessprod
     Linked issues:
     - [Change the UI color for ExternalSensor tasks (#38845)](https://github.com/apache/airflow/issues/38845)
- [ ] [Use debug level for minischeduler skip (#38976)](https://github.com/apache/airflow/pull/38976): @dstandish
- [x] [Mark `extending/add-build-essential-extend/Dockerfile` docker example test as XFAIL (#38978)](https://github.com/apache/airflow/pull/38978): @dirkgently007 @Taragolis
     Linked issues:
     - [Flaky docker example test around `mpi4py` builds (#38988)](https://github.com/apache/airflow/issues/38988)
     - [Can you have a DAG dependent on another DAG? (#6)](https://github.com/apache/airflow/issues/6)
- [x] [Add `inherit_cache` attribute for `CreateTableAs` custom SA Clause (#38985)](https://github.com/apache/airflow/pull/38985): @Taragolis
- [x] [Undeprecate `BaseXCom.get_one` method (#38991)](https://github.com/apache/airflow/pull/38991): @Taragolis
- [ ] [Add in Trove classifiers Python 3.12 support (#39004)](https://github.com/apache/airflow/pull/39004): @Lee-W
- [ ] [ check whether AUTH_ROLE_PUBLIC is set in check_authentication (#39012)](https://github.com/apache/airflow/pull/39012): @Lee-W @dstandish
     Linked issues:
     - [401 UNAUTHORIZED when using AUTH_ROLE_PUBLIC = "Admin" (#38900)](https://github.com/apache/airflow/issues/38900)
- [ ] [Fix PROD image package installation in CI (#39035)](https://github.com/apache/airflow/pull/39035): @potiuk
- [x] [Hostname was "redacted", not "redact"; remove it when there is no context (#39037)](https://github.com/apache/airflow/pull/39037): @jedcunningham
- [ ] [Do not add local airflow sources in CI when building k8s image (#39043)](https://github.com/apache/airflow/pull/39043): @potiuk
     Linked issues:
     - [Fix PROD image package installation in CI (#39035)](https://github.com/apache/airflow/pull/39035)
- [ ] [Upgrade to latest hatchling as build dependency (#39044)](https://github.com/apache/airflow/pull/39044): @potiuk
- [ ] [update simple-salesforce type hints to support 1.12.6 (#39047)](https://github.com/apache/airflow/pull/39047): @hussein-awala
- [ ] [Add changelog for airflow python client 2.9.0 (#39060)](https://github.com/apache/airflow/pull/39060): @ephraimbuddy
- [ ] [Check that the dataset<>task exists before trying to render graph (#39069)](https://github.com/apache/airflow/pull/39069): @bbovenzi
- [ ] [Update hatchling to version 1.24.0(latest) (#39072)](https://github.com/apache/airflow/pull/39072): @ephraimbuddy
- [ ] [Fix main failing because of the new xmlsec 1.3.14 compatibility (#39104)](https://github.com/apache/airflow/pull/39104): @potiuk
- [ ] [Improve task filtering UX (#39119)](https://github.com/apache/airflow/pull/39119): @bbovenzi
- [ ] [Improve rendered_template ux in react dag page (#39122)](https://github.com/apache/airflow/pull/39122): @bbovenzi
- [ ] [Upgrade to latest build/install dependencies (#39160)](https://github.com/apache/airflow/pull/39160): @potiuk
- [ ] [Update `is_authorized_custom_view` from auth manager to handle custom actions (#39167)](https://github.com/apache/airflow/pull/39167): @jedcunningham @vincbeck
     Linked issues:
     - [Custom FAB actions no longer work (#39144)](https://github.com/apache/airflow/issues/39144)
- [ ] [Fetch served logs when no remote/executor logs available for non-running task try (#39177)](https://github.com/apache/airflow/pull/39177): @Khrol @kahlstrm
     Linked issues:
     - [Skip served logs for non-running task try (#32561)](https://github.com/apache/airflow/pull/32561)
- [ ] [Use grid view for Task Instance's `log_url` (#39183)](https://github.com/apache/airflow/pull/39183): @AetherUnbound @csp33
     Linked issues:
     - [`TaskInstance::log_url`'s webpage does not provide a link or mechanism to view the DAG run (#39179)](https://github.com/apache/airflow/issues/39179)
     - [No way of going back to the DAG page once entering task details (#39023)](https://github.com/apache/airflow/issues/39023)
- [x] [Add warning about run/import Airflow under the Windows (#39196)](https://github.com/apache/airflow/pull/39196): @Taragolis @shachibista
     Linked issues:
     - [Windows support for Airflow (#10388)](https://github.com/apache/airflow/issues/10388)
- [x] [Force to use Airflow Deprecation warnings categories on `@deprecated` decorator (#39205)](https://github.com/apache/airflow/pull/39205): @Taragolis
- [ ] [Add Grid button to Task Instance view (#39223)](https://github.com/apache/airflow/pull/39223): @csp33
     Linked issues:
     - [No way of going back to the DAG page once entering task details (#39023)](https://github.com/apache/airflow/issues/39023)
- [ ] [Fixed side effect of menu filtering causing disappearing menus (#39229)](https://github.com/apache/airflow/pull/39229): @raphaelauv @potiuk @csp33
     Linked issues:
     - [Pools have disappeared from the Admin menu (#39204)](https://github.com/apache/airflow/issues/39204)
     - [front - admin menu - drop-down non deterministic (#39135)](https://github.com/apache/airflow/issues/39135)
- [x] [Fix trigger kwarg encryption migration (#39246)](https://github.com/apache/airflow/pull/39246): @jedcunningham @romanzdk @hussein-awala
     Linked issues:
     - [Fix trigger_kwargs encryption/decryption on db migration (#38876)](https://github.com/apache/airflow/pull/38876)
     - [DB migrate throws na error on encrypt_trigger_kwargs (#38836)](https://github.com/apache/airflow/issues/38836)
- [ ] [Add workaround for datetime-local input in firefox+safari (#39261)](https://github.com/apache/airflow/pull/39261): @bbovenzi
- [ ] [Make task log messages include run_id (#39280)](https://github.com/apache/airflow/pull/39280): @RyuSA
     Linked issues:
     - [ Include `run_id` in TaskInstance Logging for Enhanced Traceability and Debugging (#39272)](https://github.com/apache/airflow/issues/39272)
- [ ] [Copy menu_item href for nav bar (#39282)](https://github.com/apache/airflow/pull/39282): @bbovenzi
- [ ] [added logical_date parameter (#39285)](https://github.com/apache/airflow/pull/39285): @flolas

Thanks to all who contributed to the release (probably not a complete list!):
@bbovenzi @AetherUnbound @Taragolis @dstandish @hussein-awala @flolas @alxkolm @kahlstrm @TJaniF @ephraimbuddy @shachibista @potiuk @romanzdk @jscheffl @stevenschaerer @csp33 @Timelessprod @Khrol @dirkgently007 @AlexisBRENON @raphaelauv @idantepper @vincbeck @Lee-W @jedcunningham @tirkarthi @RyuSA

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by jscheffl** [comment]
Checked and my patch is in.

**Comment by RyuSA** [comment]
![image](https://github.com/apache/airflow/assets/12961775/4d59e26e-7c3c-4667-a6ba-8e380806e9fa)
I confirmed my patch is in the rc1. 👍 (https://github.com/apache/airflow/pull/39280)

**Comment by hterik** [comment]
I haven't checked any of the listed tickets in particular but have run rc1 quite extensively since yesterday and have not noticed any immediately apparent instabilities or problems.   👍

**Comment by Timelessprod** [comment]
https://github.com/apache/airflow/pull/38969 Is patched from my point of view. Thanks Idan Tepper!

**Comment by jedcunningham** [comment]
#38882 and #39246 look good.

#39167, I'm not sure if I made a mistake when cherry-picking it, but that doesn't work with the latest FAB rc 😞. I'll investigate a bit more in a bit.

**Comment by Taragolis** [comment]
Checked my changes, all looking good

**Comment by ephraimbuddy** [comment]
> #38882 and #39246 look good.
> 
> #39167, I'm not sure if I made a mistake when cherry-picking it, but that doesn't work with the latest FAB rc 😞. I'll investigate a bit more in a bit.

Cc @vincbeck

**Comment by TJaniF** [comment]
#38902 Looks good :) 

![image](https://github.com/apache/airflow/assets/90063506/647f458d-c962-40f1-b484-b2d73c59d392)

**Comment by jedcunningham** [comment]
Got to the bottom of #39167. Turns out that was an incomplete fix and I just opened #39421 to get the other spot. #39167 itself is fine, but custom actions (#39144) won't work until both are in. However, it isn't a regression in this release.

**Comment by csp33** [comment]
All good with #39223

**Comment by ephraimbuddy** [comment]
Airflow 2.9.1 has been released. Thank you all for testing this release
