### ISSUE TITLE
Status of testing Providers that were prepared on June 07, 2024

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#40115]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 8.24.0rc2](https://pypi.org/project/apache-airflow-providers-amazon/8.24.0rc2)
   - [x] [ECS Overrides for AWS Batch submit_job (#39903)](https://github.com/apache/airflow/pull/39903): @yehoshuadimarsky
   - [x] [feat: implement amazon s3 to dynamodb transfer operator (#39654)](https://github.com/apache/airflow/pull/39654): @dondaum
     Linked issues:
       - [x] [Linked Issue #39377](https://github.com/apache/airflow/issues/39377): @eladkal
   - [x] [Adding Glue Data Quality Rule Recommendation Run  (#40014)](https://github.com/apache/airflow/pull/40014): @gopidesupavan
   - [ ] [Allow user-specified object attributes to be used in check_fn for S3KeySensor (#39950)](https://github.com/apache/airflow/pull/39950): @ellisms
     Linked issues:
       - [ ] [Linked Issue #39898](https://github.com/apache/airflow/issues/39898): @eladkal
   - [x] [Adding Amazon Glue Data Quality Service (#39923)](https://github.com/apache/airflow/pull/39923): @gopidesupavan
   - [ ] [Deduplicate model name in SageMakerTransformOperator (#39956)](https://github.com/apache/airflow/pull/39956): @mateuslatrova
     Linked issues:
       - [ ] [Linked Issue #39502](https://github.com/apache/airflow/issues/39502): @mxuan0
   - [ ] [fix: DynamoDBToS3Operator - remove process_func from templated_fields (#39948)](https://github.com/apache/airflow/pull/39948): @raphaelauv
   - [x] [Fix aws assume role session creation when deferrable (#40051)](https://github.com/apache/airflow/pull/40051): @gopidesupavan
     Linked issues:
       - [x] [Linked Issue #39970](https://github.com/apache/airflow/issues/39970): @arollet-decathlon
   - [x] [Resolving ECS fargate deprecated warnings (#39834)](https://github.com/apache/airflow/pull/39834): @dirrao
   - [x] [Resolving EMR notebook deprecated warnings (#39829)](https://github.com/apache/airflow/pull/39829): @dirrao
   - [ ] [Bump boto min versions (#40052)](https://github.com/apache/airflow/pull/40052): @ferruzzi
   - [x] [Implement per-provider tests with lowest-direct dependency resolution (#39946)](https://github.com/apache/airflow/pull/39946): @potiuk
   - [x] [Resolve aws emr deprecations in tests (#40020)](https://github.com/apache/airflow/pull/40020): @dirrao
## Provider [celery: 3.7.2rc1](https://pypi.org/project/apache-airflow-providers-celery/3.7.2rc1)
   - [x] [Fixing exception types to include TypeError, which is what is raised in (#40012)](https://github.com/apache/airflow/pull/40012): @leakec
     Linked issues:
       - [x] [Linked Issue #40011](https://github.com/apache/airflow/issues/40011): @leakec
   - [ ] [catch sentry flush if exception happens in _execute_in_fork finally block (#40060)](https://github.com/apache/airflow/pull/40060): @Lee-W
   - [ ] [add PID and return code to _execute_in_fork logging (#40058)](https://github.com/apache/airflow/pull/40058): @Lee-W
## Provider [cncf.kubernetes: 8.3.1rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/8.3.1rc1)
   - [x] [Fixes K8s trigger failing running pods with timeout (#40019)](https://github.com/apache/airflow/pull/40019): @Usiel
   - [ ] [Refresh properties on KubernetesPodOperator on token expiration also when logging (#39789)](https://github.com/apache/airflow/pull/39789): @paolo-moriello
   - [ ] [Fix Pod Number Exception in the sync mode if reattach_on_restart parameter is False (#39329)](https://github.com/apache/airflow/pull/39329): @e-galan
   - [x] [Avoid resetting adopted task instances when retrying for kubernetes executor (#39406)](https://github.com/apache/airflow/pull/39406): @tanvn
   - [ ] [Include fatal reason for pod pending events (#39924)](https://github.com/apache/airflow/pull/39924): @wolfier

All users involved in the PRs:
@potiuk @mateuslatrova @ferruzzi @gopidesupavan @dirrao @leakec @tanvn @paolo-moriello @wolfier @raphaelauv @ellisms @Usiel @yehoshuadimarsky @e-galan @dondaum @Lee-W

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
My changes were just in tests but I tested that indeed the new celery provider fixes the problem with celery executor reported in #40011 (Impacting also previous versions of airflow). WDYT @eladkal, maybe we should yank the 5.4.0 of celery provider already - to avoid people to install it accidentally ? It's pretty bad when you install 5.4.0 for all previous Airlfow version that use celery provider.

![image](https://github.com/apache/airflow/assets/595491/dc60e160-5625-4bda-8e7c-8124f2693177)

**Comment by eladkal** [comment]
> WDYT @eladkal, maybe we should yank the 3.7.1 of celery provider already - to avoid people to install it accidentally ?

Agreed

**Comment by potiuk** [comment]
Yenked 3.7.1

**Comment by dondaum** [comment]
Tested #39654, works as expected.

**Comment by fdemiane** [comment]
No issues from my side

**Comment by tanvn** [comment]
Tested https://github.com/apache/airflow/pull/39406 by installing [cncf.kubernetes: 8.3.1rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/8.3.1rc1) upon my Airflow 2.8.4, confirmed it is working as expected.

**Comment by arollet-decathlon** [comment]
Tested #40051 it fixed #39970  ! Huge thanks @gopidesupavan

**Comment by yehoshuadimarsky** [comment]
Tested Amazon provider, works for me

**Comment by leakec** [comment]
Tested `celery: 3.7.2rc1` and verified it implements #40012 and that it fixes #40011.

**Comment by gopidesupavan** [comment]
Tested both #40014 and #39923 working fine.

**Comment by gopidesupavan** [comment]
Thanks @arollet-decathlon for testing #40051

**Comment by dirrao** [comment]
Tested #39834, #39829 and #40020. They looks good to me.

**Comment by Usiel** [comment]
Tested #40019 with Airflow 2.9.1, all good 👍

**Comment by eladkal** [comment]
Thank you everyone. Providers are released.

I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
