### ISSUE TITLE
Status of testing of Apache Airflow Helm Chart 1.14.0rc1

### ISSUE THREAD

**Issue by jedcunningham** [apache/airflow#40248]
We are kindly requesting that contributors to [Apache Airflow Helm Chart 1.14.0rc1](https://dist.apache.org/repos/dist/dev/airflow/helm-chart/1.14.0rc1) help test the RC.

Please let us know by commenting if the issue is addressed in the latest RC.

- [ ] [feat: enable mysql keda support for triggerer (#37365)](https://github.com/apache/airflow/pull/37365): @claneys
     Linked issues:
     - [feat: support mysql backend as keda trigger (#36167)](https://github.com/apache/airflow/pull/36167)
- [ ] [remove K8S 1.25 support (#38367)](https://github.com/apache/airflow/pull/38367): @raphaelauv
- [x] [Upgrade to latest chart dependencies detected by canary run (#38416)](https://github.com/apache/airflow/pull/38416): @potiuk
- [ ] [Chart: Enable templating in extraContainers and extraInitContainers (#38507)](https://github.com/apache/airflow/pull/38507): @mewa
- [x] [Chart: Allow AWS ECS Executor (#38524)](https://github.com/apache/airflow/pull/38524): @LipuFei
- [ ] [Add rpc server to helm chart (#38549)](https://github.com/apache/airflow/pull/38549): @dstandish
- [x] [Limit redis image to 7.2 in our chart (#38928)](https://github.com/apache/airflow/pull/38928): @potiuk
- [ ] [doc: fix hpa documentation in the helm chart (#39307)](https://github.com/apache/airflow/pull/39307): @raphaelauv
- [ ] [Document `extraContainers` and `extraInitContainers` that are templated (#40033)](https://github.com/apache/airflow/pull/40033): @jedcunningham
- [ ] [feat(chart): allow valueFrom in env config of components (#40095) (#40135)](https://github.com/apache/airflow/pull/40135): @dada-engineer
     Linked issues:
     - [Chart: Allow to extend cleanup cronjob env with custom envs from secrets or config maps (#40095)](https://github.com/apache/airflow/issues/40095)
- [ ] [Chart: Default airflow version to 2.9.2 (#40160)](https://github.com/apache/airflow/pull/40160): @utkarsharma2
- [ ] [Chart: set `workers.safeToEvict` default to False (#40229)](https://github.com/apache/airflow/pull/40229): @jedcunningham
- [ ] [Chart: Release notes for 1.14.0 (#40246)](https://github.com/apache/airflow/pull/40246): @jedcunningham

Thanks to all who contributed to the release (probably not a complete list!):
@potiuk @raphaelauv @dada-engineer @ephraimbuddy @jedcunningham @LipuFei @dstandish @mewa @claneys @utkarsharma2

**Comment by potiuk** [comment]
Confirmed that proper dependency versions are installed when chart is installed (my changes)

**Comment by LipuFei** [comment]
Hi @potiuk , https://github.com/apache/airflow/pull/38524 works for me.

**Comment by jedcunningham** [comment]
Thanks for testing @potiuk and @LipuFei! The release is underway.

**Comment by claneys** [comment]
Wasn't present sorry :/ 
Tested and I found a bug on kedaConnection value compute when using mysql database backend. The helm template function urlJoin needs a scheme and without it the string ends with "//" at the beginning of the string. I'm working on a fix + test
