### ISSUE TITLE
Status of testing Providers that were prepared on June 22, 2024

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#40382]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 8.25.0rc1](https://pypi.org/project/apache-airflow-providers-amazon/8.25.0rc1)
   - [x] [Add Amazon Comprehend Document Classifier (#40287)](https://github.com/apache/airflow/pull/40287): @gopidesupavan
   - [x] [Fix `importlib_metadata` import in aws utils (#40134)](https://github.com/apache/airflow/pull/40134): @eladkal
   - [ ] [openlineage, redshift: do not call DB for schemas below Airflow 2.10 (#40197)](https://github.com/apache/airflow/pull/40197): @mobuchowski
   - [x] [Lazy match escaped quotes in `RedshiftToS3Operator` (#40206)](https://github.com/apache/airflow/pull/40206): @jasonspeck
   - [x] [Use stdlib `importlib.metadata` for retrieve `botocore` package version (#40137)](https://github.com/apache/airflow/pull/40137): @Taragolis
     Linked issues:
       - [x] [Linked Issue #40134](https://github.com/apache/airflow/pull/40134): @eladkal
## Provider [apache.drill: 2.7.2rc1](https://pypi.org/project/apache-airflow-providers-apache-drill/2.7.2rc1)
   - [ ] [remove deprecation drill (#39732)](https://github.com/apache/airflow/pull/39732): @Bowrna
     Linked issues:
       - [ ] [Linked Issue #39485](https://github.com/apache/airflow/issues/39485): @Taragolis
## Provider [apache.kafka: 1.5.0rc1](https://pypi.org/project/apache-airflow-providers-apache-kafka/1.5.0rc1)
   - [x] [Add `delete_topic` to `KafkaAdminClientHook` and teardown logic to Kafka integration tests (#40142)](https://github.com/apache/airflow/pull/40142): @shahar1
     Linked issues:
       - [x] [Linked Issue #40140](https://github.com/apache/airflow/pull/40140): @shahar1
   - [ ] [Default client in KafkaBaseHook (#40284)](https://github.com/apache/airflow/pull/40284): @riccardoforzan
## Provider [cncf.kubernetes: 8.3.2rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/8.3.2rc1)
   - [ ] [Fix Scheduler restarting due to too many completed pods in cluster (#40183)](https://github.com/apache/airflow/pull/40183): @ephraimbuddy
     Linked issues:
       - [ ] [Linked Issue #22612](https://github.com/apache/airflow/issues/22612): @dviru
   - [x] [k8s version bump (#40253)](https://github.com/apache/airflow/pull/40253): @dirrao
## Provider [common.compat: 1.0.0rc1](https://pypi.org/project/apache-airflow-providers-common-compat/1.0.0rc1)
   - [x] [Add common.compat provider (#40374)](https://github.com/apache/airflow/pull/40374): @potiuk
## Provider [common.sql: 1.14.1rc1](https://pypi.org/project/apache-airflow-providers-common-sql/1.14.1rc1)
   - [ ] [standardizes template fields for `BaseSQLOperator` and adds `database` as a templated field (#39826)](https://github.com/apache/airflow/pull/39826): @nyoungstudios
## Provider [databricks: 6.6.0rc1](https://pypi.org/project/apache-airflow-providers-databricks/6.6.0rc1)
   - [x] [Add DatabricksTaskOperator (#40013)](https://github.com/apache/airflow/pull/40013): @pankajkoti
   - [x] [Add DatabricksWorkflowTaskGroup (#39771)](https://github.com/apache/airflow/pull/39771): @pankajkoti
   - [ ] [Databricks: stop including user names in `list_jobs` (#40178)](https://github.com/apache/airflow/pull/40178): @stephenpurcell-db
   - [x] [Lower log levels from INFO to DEBUG to reduce log verbosity - Databricks provider auth (#39941)](https://github.com/apache/airflow/pull/39941): @pankajkoti
## Provider [dbt.cloud: 3.9.0rc1](https://pypi.org/project/apache-airflow-providers-dbt-cloud/3.9.0rc1)
   - [x] [Add `retry_from_failure` parameter to DbtCloudRunJobOperator (#38868)](https://github.com/apache/airflow/pull/38868): @boraberke
     Linked issues:
       - [x] [Linked Issue #35772](https://github.com/apache/airflow/issues/35772): @sdurry
   - [x] [Fix `DbtCloudRunJobOperator` to Use Correct Status Parameters for `reuse_existing_run` (#40048)](https://github.com/apache/airflow/pull/40048): @boraberke
## Provider [docker: 3.12.1rc1](https://pypi.org/project/apache-airflow-providers-docker/3.12.1rc1)
   - [x] [Bump docker version to 7.1.0 (#39839)](https://github.com/apache/airflow/pull/39839): @eladkal
## Provider [fab: 1.2.0rc1](https://pypi.org/project/apache-airflow-providers-fab/1.2.0rc1)
   - [x] [Add CSRF protection to "/logout" (#40145)](https://github.com/apache/airflow/pull/40145): @shahar1
     Linked issues:
       - [x] [Linked Issue #33030](https://github.com/apache/airflow/issues/33030): @potiuk
   - [x] [Upgrade to FAB 4.5.0 (#39851)](https://github.com/apache/airflow/pull/39851): @potiuk
   - [x] [fix: sqa deprecations for airflow providers (#39293)](https://github.com/apache/airflow/pull/39293): @dondaum
     Linked issues:
       - [x] [Linked Issue #28723](https://github.com/apache/airflow/issues/28723): @potiuk
   - [ ] [Add `[webserver]update_fab_perms` to deprecated configs (#40317)](https://github.com/apache/airflow/pull/40317): @ephraimbuddy
## Provider [ftp: 3.10.0rc1](https://pypi.org/project/apache-airflow-providers-ftp/3.10.0rc1)
   - [ ] [Allow FTPHook to change port number (#39465)](https://github.com/apache/airflow/pull/39465): @VelmiraPetkova
     Linked issues:
       - [ ] [Linked Issue #39308](https://github.com/apache/airflow/issues/39308): @arollet-decathlon
## Provider [google: 10.20.0rc1](https://pypi.org/project/apache-airflow-providers-google/10.20.0rc1)
   - [ ] [Add GenerationConfig and SafetySettings parameters to Google Cloud Multimodal Model Operators (#40126)](https://github.com/apache/airflow/pull/40126): @CYarros10
   - [x] [Add missing location param to `BigQueryUpdateTableSchemaOperator` (#40237)](https://github.com/apache/airflow/pull/40237): @shahar1
     Linked issues:
       - [x] [Linked Issue #40235](https://github.com/apache/airflow/issues/40235): @mariayanovskaya
   - [ ] [Add support for external IdP OIDC token retrieval for Google Cloud Operators. (#39873)](https://github.com/apache/airflow/pull/39873): @dybolo
     Linked issues:
       - [ ] [Linked Issue #35899](https://github.com/apache/airflow/issues/35899): @ChloeSheasby
   - [ ] [Add encryption_configuration parameter to BigQuery operators (#40063)](https://github.com/apache/airflow/pull/40063): @VladaZakharova
   - [x] [add default gcp_conn_id to GoogleBaseAsyncHook (#40080)](https://github.com/apache/airflow/pull/40080): @Lee-W
   - [x] [Added ordering key option for PubSubPublishMessageOperator GCP Operator (#39955)](https://github.com/apache/airflow/pull/39955): @mehdigati
     Linked issues:
       - [ ] [Linked Issue #39940](https://github.com/apache/airflow/issues/39940): @mehdigati
   - [ ] [Add method to get metadata from GCS blob in GCSHook (#38398)](https://github.com/apache/airflow/pull/38398): @jalengg
   - [ ] [Adding params. to create_auto_ml_forecasting_training_job in AutoMl hook (#39767)](https://github.com/apache/airflow/pull/39767): @vinay2242g
   - [ ] [Implement CloudComposerDAGRunSensor (#40088)](https://github.com/apache/airflow/pull/40088): @MaksYermak
   - [x] [Implement `CloudDataTransferServiceRunJobOperator` (#39154)](https://github.com/apache/airflow/pull/39154): @boraberke
   - [x] [Fetch intermediate log async GKEStartPod   (#39348)](https://github.com/apache/airflow/pull/39348): @pankajastro
   - [x] [feat: added OL support for AzureBlobStorageToGCSOperator in google provider package (#40290)](https://github.com/apache/airflow/pull/40290): @rahul-madaan
   - [x] [Fix hive_partition_sensor system test (#40023)](https://github.com/apache/airflow/pull/40023): @e-galan
   - [x] [Fix openai 1.32 breaking openai tests (#40110)](https://github.com/apache/airflow/pull/40110): @potiuk
   - [x] [Fix credentials intialization revealed by mypy version of google auth (#40108)](https://github.com/apache/airflow/pull/40108): @potiuk
   - [x] [Change regular expression to exclude double quote and newline (#39991)](https://github.com/apache/airflow/pull/39991): @kylase
   - [x] [Fix replace parameter for BigQueryToPostgresOperator (#40278)](https://github.com/apache/airflow/pull/40278): @e-galan
   - [x] [Fix `GCSToGCSOperator` behavior difference for moving single object (#40162)](https://github.com/apache/airflow/pull/40162): @boraberke
     Linked issues:
       - [x] [Linked Issue #37576](https://github.com/apache/airflow/issues/37576): @nyoungstudios
   - [ ] [Refactor Datapipeline operators and fix system tests (#39716)](https://github.com/apache/airflow/pull/39716): @VladaZakharova
   - [ ] [openlineage: isolate metadata extraction by executing OL methods in separate, forked process (#40078)](https://github.com/apache/airflow/pull/40078): @mobuchowski
   - [x] [Bump minimum version of google auth (#40190)](https://github.com/apache/airflow/pull/40190): @potiuk
     Linked issues:
       - [ ] [Linked Issue #39873](https://github.com/apache/airflow/pull/39873): @dybolo
   - [ ] [Bump google-ads version to use v17 by default (#40158)](https://github.com/apache/airflow/pull/40158): @molcay
   - [x] [google: move bigquery openlineage imports inside methods (#40062)](https://github.com/apache/airflow/pull/40062): @ahidalgob
     Linked issues:
       - [x] [Linked Issue #40043](https://github.com/apache/airflow/issues/40043): @ahidalgob
   - [x] [Add template_field to DataplexGetDataQualityScanResultOperator (#40041)](https://github.com/apache/airflow/pull/40041): @amirmor1
## Provider [http: 4.12.0rc1](https://pypi.org/project/apache-airflow-providers-http/4.12.0rc1)
   - [x] [Add `retry_args` parameter to `HttpOperator` (#40086)](https://github.com/apache/airflow/pull/40086): @boraberke
     Linked issues:
       - [x] [Linked Issue #39247](https://github.com/apache/airflow/issues/39247): @lopezvit
## Provider [microsoft.azure: 10.1.2rc1](https://pypi.org/project/apache-airflow-providers-microsoft-azure/10.1.2rc1)
   - [x] [Switch AzureDataLakeStorageV2Hook to use ManagedIdentityCredential for managed identity/workload auth (#38497)](https://github.com/apache/airflow/pull/38497): @TJaniF
   - [x] [BUGFIX: Make sure XComs work correctly in MSGraphAsyncOperator with paged results and dynamic task mapping (#40301)](https://github.com/apache/airflow/pull/40301): @dabla
   - [x] [Revert "refactor: Make sure xcoms work correctly in MSGraphAsyncOperator with concurrent workers" (#40300)](https://github.com/apache/airflow/pull/40300): @dabla
   - [x] [refactor: Make sure xcoms work correctly in MSGraphAsyncOperator with concurrent workers (#40297)](https://github.com/apache/airflow/pull/40297): @dabla
## Provider [microsoft.mssql: 3.7.2rc1](https://pypi.org/project/apache-airflow-providers-microsoft-mssql/3.7.2rc1)
   - [x] [Add `mssql` integration tests and relocate existing unit tests (#39831)](https://github.com/apache/airflow/pull/39831): @shahar1
     Linked issues:
       - [x] [Linked Issue #39768](https://github.com/apache/airflow/pull/39768): @shahar1
       - [x] [Linked Issue #38577](https://github.com/apache/airflow/issues/38577): @Taragolis
## Provider [openai: 1.2.2rc1](https://pypi.org/project/apache-airflow-providers-openai/1.2.2rc1)
   - [x] [Fix openai 1.32 breaking openai tests (#40110)](https://github.com/apache/airflow/pull/40110): @potiuk
## Provider [openlineage: 1.9.0rc1](https://pypi.org/project/apache-airflow-providers-openlineage/1.9.0rc1)
   - [ ] [local task job: add overtime mechanism, to not kill task prematurely when auxiliary processes are running (#39890)](https://github.com/apache/airflow/pull/39890): @mobuchowski
   - [ ] [openlineage: add some debug logging around sql parser call sites (#40200)](https://github.com/apache/airflow/pull/40200): @mobuchowski
   - [ ] [openlineage: Add task SLA and queued datetime to AirflowRunFacet (#40091)](https://github.com/apache/airflow/pull/40091): @kacpermuda
   - [ ] [[openlineage] Add error stacktrace to task fail event (#39813)](https://github.com/apache/airflow/pull/39813): @kacpermuda
     Linked issues:
       - [ ] [Linked Issue #38155](https://github.com/apache/airflow/pull/38155): @vandonr
   - [ ] [[OPENLINEAGE] Introduce AirflowJobFacet and AirflowStateRunFacet (#39520)](https://github.com/apache/airflow/pull/39520): @kacpermuda
     Linked issues:
       - [ ] [Linked Issue #39467](https://github.com/apache/airflow/issues/39467): @kacpermuda
   - [x] [Use UUIDv7 for OpenLineage runIds (#39889)](https://github.com/apache/airflow/pull/39889): @dolfinus
   - [ ] [openlineage: isolate metadata extraction by executing OL methods in separate, forked process (#40078)](https://github.com/apache/airflow/pull/40078): @mobuchowski
   - [ ] [openlineage, redshift: do not call DB for schemas below Airflow 2.10 (#40197)](https://github.com/apache/airflow/pull/40197): @mobuchowski
   - [ ] [Fix scheduler crashing with OpenLineage provider==1.8.0 on airflow standalone (#40353)](https://github.com/apache/airflow/pull/40353): @kacpermuda
     Linked issues:
       - [ ] [Linked Issue #40309](https://github.com/apache/airflow/issues/40309): @merobi-hub
   - [x] [fix: sqa deprecations for airflow providers (#39293)](https://github.com/apache/airflow/pull/39293): @dondaum
     Linked issues:
       - [x] [Linked Issue #28723](https://github.com/apache/airflow/issues/28723): @potiuk
## Provider [opensearch: 1.3.0rc1](https://pypi.org/project/apache-airflow-providers-opensearch/1.3.0rc1)
   - [ ] [Opensearch operator set connection type (#39788)](https://github.com/apache/airflow/pull/39788): @Lukas1v
## Provider [sftp: 4.10.2rc1](https://pypi.org/project/apache-airflow-providers-sftp/4.10.2rc1)
   - [ ] [sftp_sensor: fixing resource management with sensor (#40022)](https://github.com/apache/airflow/pull/40022): @pateash
## Provider [snowflake: 5.5.2rc1](https://pypi.org/project/apache-airflow-providers-snowflake/5.5.2rc1)
   - [ ] [openlineage: add some debug logging around sql parser call sites (#40200)](https://github.com/apache/airflow/pull/40200): @mobuchowski
   - [ ] [Bump Snowflake client driver versions per support policy (#39886)](https://github.com/apache/airflow/pull/39886): @josh-fell
## Provider [telegram: 4.5.2rc1](https://pypi.org/project/apache-airflow-providers-telegram/4.5.2rc1)
   - [x] [Working fix for typing in telegram provider (#40258)](https://github.com/apache/airflow/pull/40258): @potiuk
     Linked issues:
       - [x] [Linked Issue #40255](https://github.com/apache/airflow/pull/40255): @potiuk
   - [x] [Fix typing in telegram provider (#40255)](https://github.com/apache/airflow/pull/40255): @potiuk
## Provider [teradata: 2.3.0rc1](https://pypi.org/project/apache-airflow-providers-teradata/2.3.0rc1)
   - [x] [Enhancements to S3 and Azure to Teradata Cloud Transfer Operators (#40378)](https://github.com/apache/airflow/pull/40378): @satish-chinthanippu
## Provider [ydb: 1.0.0rc1](https://pypi.org/project/apache-airflow-providers-ydb/1.0.0rc1)
   - [ ] [add new YDB provider (#39996)](https://github.com/apache/airflow/pull/39996): @uzhastik

All users involved in the PRs:
@rahul-madaan @eladkal @Taragolis @nyoungstudios @uzhastik @jalengg @mobuchowski @e-galan @VladaZakharova @riccardoforzan @josh-fell @pankajastro @kacpermuda @ephraimbuddy @satish-chinthanippu @boraberk

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by uzhastik** [comment]
Hello. Could you please exclude from this release ydb provider? It’s too young for that ;) it has known bug related to auth and I’d like to add new feature there later. Thank you in advance.

**Comment by eladkal** [comment]
> Hello. Could you please exclude from this release ydb provider? It’s too young for that ;) it has known bug related to auth and I’d like to add new feature there later. Thank you in advance.

In your PR you marked it as ready to be released
https://github.com/apache/airflow/blob/6e5ae26382b328e88907e8301d4b2352ef8524c5/airflow/providers/ydb/provider.yaml#L24

What is the issue with the provider?

**Comment by uzhastik** [comment]
> > Hello. Could you please exclude from this release ydb provider? It’s too young for that ;) it has known bug related to auth and I’d like to add new feature there later. Thank you in advance.
> 
> In your PR you marked it as ready to be released
> 
> https://github.com/apache/airflow/blob/6e5ae26382b328e88907e8301d4b2352ef8524c5/airflow/providers/ydb/provider.yaml#L24
> 
> Missing features are not a blocker for release. We can always add new features later on.

To be honest yaml was just copied and bug was found two days ago;) auth info from file does not work, but there is workaround to provide auth info inplace.

**Comment by potiuk** [comment]
Checked that all changes are there. The `common.compat` does not have any code yet, so we could skip releasing it, but there is no harm in doing so - having a 1.0.0 version released in PyPI is generally a good idea.

**Comment by gopidesupavan** [comment]
Tested #40287, working fine. Thanks

**Comment by rahul-madaan** [comment]
tested #40290, working fine 👍🏻

**Comment by mehdigati** [comment]
tested #39955, working fine, thanks !

**Comment by shahar1** [comment]
#40142, #40237, #39831 are ok

**Comment by jasonspeck** [comment]
Confirmed https://github.com/apache/airflow/pull/40206 works as expected

**Comment by kylase** [comment]
I have tested #39991 and it works as expected.

```
[2024-06-23, 04:47:48 UTC] {beam.py:119} WARNING - {"message":"org.apache.beam.runners.dataflow.DataflowRunner - Dataflow SDK version: 2.56.0","severity":"INFO"}
[2024-06-23, 04:47:49 UTC] {beam.py:119} WARNING - {"message":"org.apache.beam.runners.dataflow.DataflowRunner - To access the Dataflow monitoring console, please navigate to https://console.cloud.google.com/dataflow/jobs/<redacted>","severity":"INFO"}
[2024-06-23, 04:47:49 UTC] {beam.py:119} WARNING - {"message":"org.apache.beam.runners.dataflow.DataflowRunner - Submitted job: <redacted>","severity":"INFO"}
[2024-06-23, 04:47:49 UTC] {beam.py:119} WARNING - {"message":"org.apache.beam.runners.dataflow.DataflowRunner - To cancel the job using the \u0027gcloud\u0027 tool, run:\n\u003e gcloud dataflow jobs --project\u003d<redacted> cancel --region\u003<redacted> <redacted>","severity":"INFO"}
[2024-06-23, 04:47:49 UTC] {beam.py:172} INFO - Process exited with return code: 0
[2024-06-23, 04:47:49 UTC] {dataflow.py:461} INFO - Start waiting for done.
[2024-06-23, 04:47:49 UTC] {dataflow.py:403} INFO - Google Cloud DataFlow job <redacted> is state: JOB_STATE_PENDING
[2024-06-23, 04:47:49 UTC] {dataflow.py:464} INFO - Waiting for done. Sleep 10 s
[2024-06-23, 04:47:59 UTC] {dataflow.py:403} INFO - Google Cloud DataFlow job <redacted> is state: JOB_STATE_PENDING
[2024-06-23, 04:47:59 UTC] {dataflow.py:464} INFO - Waiting for done. Sleep 10 s
[2024-06-23, 04:48:09 UTC] {dataflow.py:403} INFO - Google Cloud DataFlow job <redacted> is state: JOB_STATE_RUNNING
[2024-06-23, 04:48:09 UTC] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=<redacted>, task_id=start_streaming, map_index=0, execution_date=20240623T044637, start_date=20240623T044717, end_date=20240623T044809
[2024-06-23, 04:48:09 UTC] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-06-23, 04:48:09 UTC] {taskinstance.py:2781} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

**Comment by dirrao** [comment]
Changes https://github.com/apache/airflow/pull/40253 works as expected.

**Comment by amirmor1** [comment]
Tested #40041 and it works as expected.

**Comment by TJaniF** [comment]
Tested #38497, works as expected.

**Comment by kacpermuda** [comment]
#39520 stopped working correctly (something changed between now and when i wrote it) and I'm trying to debug what exactly is causing it.

**Comment by satish-chinthanippu** [comment]
Can you please remove teradata [https://github.com/apache/airflow/pull/40378](https://github.com/apache/airflow/pull/40378) PR from this 2.3.0 release as we wanted to release compute cluster functionality along with this. We are in process of creating new PR for compute cluster and we would like to release 2.3.0 with these two features as per our roadmap.

**Comment by dolfinus** [comment]
#39889 is working as expected

**Comment by uzhastik** [comment]
Hello, @potiuk . Thank you for clarification. I'd like to ask how we can improve quality if this release or it is not our goal? Usually release means something good and stable for use. But you tell that improving is big overhead. That means that release is something dirty in some situations, it is easy to release. I suggest to make it clear to users who installs such “release”. It could be just a comment that particular providers have some known problems or give authors some release branch to merge fixes there. Or even exclude provider from release.

**Comment by potiuk** [comment]
> Or even exclude provider from release.

Yes.  This is how it works. Unit tests are the first line of defense and we assume that when we have passing unit test in main - the provider is ready to have release candidate out. And then this conversation here is foreseen to see if there are any bugs that should block certain providers and remove them from release. But this is NOT to block certain features from being released, it is only to see if there are no blocker bugs. What gets merged into main is assumed to be "ready for next release candidate". If you do not want a PR to be merged yet, you should keep on rebasing it and mark it as Draft until you feel it is ready to be released in the next release candidate (whenever it happens).

If there is a blocker bug /regression we exclude provider from release. But it's a 0/1 decision based on release manager's assesment whether it's ok to release particular provider or not, based on description of those who test the RC here. If a bug is found during RC, those who find it shoudl describe the scope and impact of the bug and release manager assesses and decides what to do. This is at sole discretion of the release manager  (see https://www.apache.org/legal/release-policy.html#approving-a-release and releated documentation on the release process requirements by the Apache Software Foundation). 

In our case we are ok to release new features even with minor non-blocking bugs, the "strong" reason for excluding the provider is when there is a major regression in already released features. Sometimes we even decide to release providers even if new features are not complete, if some partial implementation "work" but new work is planned (then it will be released in the next wave). 

We do not "hold" releases, we release everything that has been merged to main. Full stop.  This has been working like that for ~ 4 years for 90+ providers of ours.

**Comment by potiuk** [comment]
BTW. And just to clarify - as per definition of the ASF release manager's job is purely mechanical (+ single-handedly make decision to exclude certain provides based on the assessment of bug description provided by those who test it).

See also here: https://infra.apache.org/release-publishing.html#releasemanager

The release manager releases whatever the community decided to merge as "ready to be released". In case of providers "main" is the "ready for release sign" so when you are marking your PR as "ready to be merged" and it passes all tests as an author you are saying "it's ready to be release". That's why also in those "Status of the providers" issue we mark the authors, so that they can verify **just before the release** if there are no blocking bugs. See https://github.com/apache/airflow/issues/40382#issuecomment-2185793983 where @kacpermuda is still evaluating the impact for openlineage provider.  But again - this is for bugs only. What goes into the next release is decided at merge time. See also https://github.com/apache/airflow/blob/main/PROVIDERS.rst#community-providers-release-process- where the release process and various aspects of it are explained.

**Comment by Lee-W** [comment]
Verified https://github.com/apache/airflow/pull/40080

**Comment by potiuk** [comment]
So just to summarize it in short - release manager is NOT responsible for quality of the merged changes nor for the set of changes that are being prepared as release candidates. In both cases the authors are responsible - both for what goes in but also about the quality of what goes in. Release manager is a purely mechanical role to make the release happen, but the authors (with approval of committers who merge the changes) are driving both the scope and quality of the release. No-one else.. And the authors have a chance to verify their changes once the RC is out and have a chance to say "hey there is a blocker bug, I will fix it but for now let's remove it from the release".

I think this is a very, very clear split of responsibilities here and I am explaining it here, so that it's crystal clear as different people might have different assumptions on what is the release manager's and author's role in the process, and when tests are done.

**Comment by e-galan** [comment]
#40023 works as expected

**Comment by uzhastik** [comment]
> Hello. Could you please exclude from this release ydb provider? It’s too young for that ;) it has known bug related to auth and I’d like to add new feature there later. Thank you in advance.

Let’s release ydb provider. Known issues are minors.

**Comment by pankajastro** [comment]
https://github.com/apache/airflow/pull/39348 looks good. thank you!

**Comment by kacpermuda** [comment]
@eladkal please exclude openlineage provider from this wave, and if possible, let's go for rc2.

#40353 is causing the scheduler crash, I prepared a revert commit in #40402 that should be included in rc2. I also described the bug and provided some logs in #40403, but i guess for now just reverting this will allow us to move forward with the release.

**Comment by satish-chinthanippu** [comment]
> > Can you please remove teradata #40378 PR from this 2.3.0 release as we wanted to release compute cluster functionality along with this. We are in process of creating new PR for compute cluster and we would like to release 2.3.0 with these two features as per our roadmap.
> 
> It's of course @eladkal (Release Manager's) decision - but no @satish-chinthanippu , this is not how our provider's release process work. We release every changed provider from main, and we only exclude a provider (not individual PRs) from release if a serious bug has been found. Manipulating and manually modifying stuff during the release is not easy, takes time and effort, might break various parts of the process (like documentation generation, or package preparation, publishing, signing and verification) and introduces serious overhead for ther release process that we don't want.
> 
> We have more than 90 providers and we cannot afford individual treatment and such "custom" approach.
> 
> If there is a bug / regression in the existing functionality that is a blocker - we might remove whole provider from the set of the providers being voted - but that's about all flexibility, and unless there is a bug in Teradata provider, it will be released as-is.
> 
> We do not look at other's roadmaps - this is a bit of price to pay for making the provider a "community managed" one and we've been very clear about the process when we accepted Teradata - one of the reasons why Teradata could choose to release their own provider, was that this could help them to manage their own release roadmap and schedule. Once this is a community provider, we do expect Teradata to keep it updated, with dashboard and fix bugs (in their own interest) but this also means that anyone can contribute changes (and Airflow committers make decisions what goes in and out) but also that we release it together with other providers with the same cadence.
> 
> I hope that explains how it works :). This is not a complaint or being nasty (we appreciate all the work done, system test dashboards, and all the new features you guys, add). It's just the way how we have to manage 90+ providers in release has to have some limitations and structure, and also the governance requirements of the ASF is very clear that once the code is submitted to our repo it has to follow the rules of ASF where only Airflow committers can decide on the code modifications. So I wanted to make it clear.

Thank you @potiuk  for your detailed information. Understood the process and considerations regarding the release. Actually, @eladkal  suggested to raise individual PRs for each related functionality implemented in Airflow Teradata Provider to make the review process simpler. So, in line with this suggestion, we thought of raising individual PRs for the two features we have planned for this release.
We're committed to aligning with the community standards and appreciate the governance framework outlined by ASF.
Given this understanding, we'll proceed with the new PR for the compute cluster functionality alongside Teradata's provider updates as per the standard release cadence. We'll ensure that our contributions meet the necessary criteria and are compatible with the overall release process.
Please let us know if there are any specific guidelines or additional steps we should follow as we prepare these updates with multiple PRs for a single release.

**Comment by satish-chinthanippu** [comment]
https://github.com/apache/airflow/pull/40378 working as expected.

**Comment by pankajkoti** [comment]
Tested #40013, #39771 and #39941. All works fine. Thank you for the release efforts!

**Comment by ahidalgob** [comment]
#40062 working as expected

**Comment by boraberke** [comment]
Tested all of my work (#38868, #39154, #40048, #40086, #40162) and they all work as expected!

Thanks! 🥂

**Comment by potiuk** [comment]
> Which we stand for.
> I do not understand the concern you raised. Merged PR = ready to release.
> What is the problem with releasing it as is?

Yep. This is all good and I stand for it too. Raising PR <> merging PR. If you wish PR to wait because there is a need release it together with another - related PR, the PR can be kept in draft or with an unresolved conversation explaining that it  shoud not yet been merged, and other PRs might be added on top (based on the first PR) and both could be rebased until both are ready to be released. I believe there was a lack of understanding that "merged" = "ready to release" for providers, so I hope it's now clear.

**Comment by satish-chinthanippu** [comment]
@potiuk and @eladkal understood. These steps clarifies on the process to follow to release related features with multiple PRs in a single release. Thank you for providing detailed infomration.

**Comment by satish-chinthanippu** [comment]
> > Actually, @eladkal suggested to raise individual PRs for each related functionality implemented in Airflow Teradata Provider to make the review process simpler.
> 
> Which we stand for. I do not understand the concern you raised. Merged PR = ready to release. What is the problem with releasing it as is?

Please release it. https://github.com/apache/airflow/pull/40378 Tested and working as expected.

**Comment by dabla** [comment]
[40301
](https://github.com/apache/airflow/pull/40301)
[40300
]( https://github.com/apache/airflow/pull/40300)
 [40297](https://github.com/apache/airflow/pull/40297) are all working as expected
