### ISSUE TITLE
Status of testing Providers that were prepared on July 02, 2024

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#40555]
I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [openlineage: 1.9.0rc2](https://pypi.org/project/apache-airflow-providers-openlineage/1.9.0rc2)
   - [x] [local task job: add overtime mechanism, to not kill task prematurely when auxiliary processes are running (#39890)](https://github.com/apache/airflow/pull/39890): @mobuchowski
   - [x] [openlineage: add some debug logging around sql parser call sites (#40200)](https://github.com/apache/airflow/pull/40200): @mobuchowski
   - [x] [openlineage: Add task SLA and queued datetime to AirflowRunFacet (#40091)](https://github.com/apache/airflow/pull/40091): @kacpermuda
   - [x] [[openlineage] Add error stacktrace to task fail event (#39813)](https://github.com/apache/airflow/pull/39813): @kacpermuda
     Linked issues:
       - [x] [Linked Issue #38155](https://github.com/apache/airflow/pull/38155): @vandonr
   - [x] [[OPENLINEAGE] Introduce AirflowJobFacet and AirflowStateRunFacet (#39520)](https://github.com/apache/airflow/pull/39520): @kacpermuda
     Linked issues:
       - [x] [Linked Issue #39467](https://github.com/apache/airflow/issues/39467): @kacpermuda
   - [x] [Use UUIDv7 for OpenLineage runIds (#39889)](https://github.com/apache/airflow/pull/39889): @dolfinus
   - [x] [openlineage: isolate metadata extraction by executing OL methods in separate, forked process (#40078)](https://github.com/apache/airflow/pull/40078): @mobuchowski
   - [x] [openlineage: readd few removed Task properties in AirflowRunFacet (#40371)](https://github.com/apache/airflow/pull/40371): @mobuchowski
   - [x] [openlineage, redshift: do not call DB for schemas below Airflow 2.10 (#40197)](https://github.com/apache/airflow/pull/40197): @mobuchowski
   - [x] [openlineage: fix scheduler crashing on airflow standalone (#40459)](https://github.com/apache/airflow/pull/40459): @kacpermuda
     Linked issues:
       - [x] [Linked Issue #40403](https://github.com/apache/airflow/issues/40403): @kacpermuda
   - [x] [openlineage: nit: fix logging level (#40461)](https://github.com/apache/airflow/pull/40461): @kacpermuda
     Linked issues:
       - [x] [Linked Issue #40078](https://github.com/apache/airflow/pull/40078): @mobuchowski
   - [x] [openlineage: provide stack trace under proper key in error facet (#40372)](https://github.com/apache/airflow/pull/40372): @kacpermuda
     Linked issues:
       - [x] [Linked Issue #39813](https://github.com/apache/airflow/pull/39813): @kacpermuda
   - [x] [fix: sqa deprecations for airflow providers (#39293)](https://github.com/apache/airflow/pull/39293): @dondaum
     Linked issues:
       - [x] [Linked Issue #28723](https://github.com/apache/airflow/issues/28723): @potiuk
   - [x] [Enable enforcing pydocstyle rule D213 in ruff. (#40448)](https://github.com/apache/airflow/pull/40448): @ferruzzi

All users involved in the PRs:
@dondaum @dolfinus @kacpermuda @mobuchowski @ferruzzi

**Comment by kacpermuda** [comment]
Thanks for the rc2, I'll look into it tomorrow and confirm all the PR's included.

**Comment by kacpermuda** [comment]
I've run a couple of different DAGs on different environments (standalone, breeze, Astro) and it looks like all the changes work as expected.

**Comment by dondaum** [comment]
#39293 is good.

**Comment by kacpermuda** [comment]
OpenLineage [1.9.0](https://pypi.org/project/apache-airflow-providers-openlineage/1.9.0/) has been released 🎉

**Comment by potiuk** [comment]
Indeed!

Thank you everyone. Providers are released.

I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
