### ISSUE TITLE
Status of testing Providers that were prepared on July 09, 2024

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#40661]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 8.26.0rc1](https://pypi.org/project/apache-airflow-providers-amazon/8.26.0rc1)
   - [ ] [Do not dynamically determine op links for emr serverless start job operator (#40627)](https://github.com/apache/airflow/pull/40627): @o-nikolas
     Linked issues:
       - [ ] [Linked Issue #40103](https://github.com/apache/airflow/issues/40103): @fjmacagno
   - [x] [Be able to remove ACL in S3 hook's copy_object (#40518)](https://github.com/apache/airflow/pull/40518): @anteverse
   - [x] [Fix OpenLineage extraction for deferrable AthenaOperator (#40545)](https://github.com/apache/airflow/pull/40545): @kacpermuda
   - [ ] [Reduce memory footprint of s3 key trigger (#40473)](https://github.com/apache/airflow/pull/40473): @dstandish
   - [ ] [Adding cluster to ecs trigger event to avoid defer error (#40482)](https://github.com/apache/airflow/pull/40482): @ellisms
     Linked issues:
       - [ ] [Linked Issue #40207](https://github.com/apache/airflow/issues/40207): @frantoja
   - [x] [Use base aws classes in AWS Glue Data Catalog Sensors (#40492)](https://github.com/apache/airflow/pull/40492): @gopidesupavan
     Linked issues:
       - [x] [Linked Issue #35278](https://github.com/apache/airflow/issues/35278): @Taragolis
   - [x] [Use base aws classes in AWS Glue Crawlers Operators/Sensors/Triggers (#40504)](https://github.com/apache/airflow/pull/40504): @gopidesupavan
     Linked issues:
       - [x] [Linked Issue #35278](https://github.com/apache/airflow/issues/35278): @Taragolis
   - [ ] [Share data loader to across asyncio boto sessions (#40658)](https://github.com/apache/airflow/pull/40658): @dstandish
## Provider [cncf.kubernetes: 8.3.3rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/8.3.3rc1)
   - [x] [Solve failing KPO task with task decorator and imported typing elements (#40642)](https://github.com/apache/airflow/pull/40642): @BenediktRamsauer
     Linked issues:
       - [x] [Linked Issue #40585](https://github.com/apache/airflow/issues/40585): @BenediktRamsauer
## Provider [common.sql: 1.14.2rc1](https://pypi.org/project/apache-airflow-providers-common-sql/1.14.2rc1)
   - [ ] [FIX: DbApiHook.insert_rows unnecessarily restarting connections (#40615)](https://github.com/apache/airflow/pull/40615): @dabla
## Provider [databricks: 6.7.0rc1](https://pypi.org/project/apache-airflow-providers-databricks/6.7.0rc1)
   - [ ] [Make Databricks operators' json parameter compatible with XComs, Jinja expression values (#40471)](https://github.com/apache/airflow/pull/40471): @boraberke
     Linked issues:
       - [ ] [Linked Issue #35433](https://github.com/apache/airflow/issues/35433): @josh-fell
   - [x] [Bug/fix support azure managed identities in Databricks operator (#40332)](https://github.com/apache/airflow/pull/40332): @marcel-martinelli
     Linked issues:
       - [x] [Linked Issue #38762](https://github.com/apache/airflow/issues/38762): @jtv8
## Provider [docker: 3.12.2rc1](https://pypi.org/project/apache-airflow-providers-docker/3.12.2rc1)
   - [x] [DockerOperator TaskFlow - correct arguments in python command (#39620)](https://github.com/apache/airflow/pull/39620): @antoinetavant
     Linked issues:
       - [x] [Linked Issue #39319](https://github.com/apache/airflow/issues/39319): @antoinetavant
   - [x] [Improve logging behavior of DockerOperator (#40489)](https://github.com/apache/airflow/pull/40489): @jscheffl
## Provider [fab: 1.2.1rc1](https://pypi.org/project/apache-airflow-providers-fab/1.2.1rc1)
   - [x] [Add backward compatibility to CSRF protection of `/logout` method (#40479)](https://github.com/apache/airflow/pull/40479): @shahar1
     Linked issues:
       - [x] [Linked Issue #40470](https://github.com/apache/airflow/issues/40470): @Al2a2d2m
## Provider [google: 10.21.0rc1](https://pypi.org/project/apache-airflow-providers-google/10.21.0rc1)
   - [ ] [Update Google Cloud Generative Model Hooks/Operators to bring parity with Vertex AI API (#40484)](https://github.com/apache/airflow/pull/40484): @CYarros10
   - [ ] [DataflowStartFlexTemplateOperator. Check for Dataflow job type each check cycle. (#40584)](https://github.com/apache/airflow/pull/40584): @theopus
   - [ ] [Added chunk_size parameter to LocalFilesystemToGCSOperator  (#40379)](https://github.com/apache/airflow/pull/40379): @jsjasonseba
   - [ ] [Add support for query parameters to BigQueryCheckOperator (#40556) (#40558)](https://github.com/apache/airflow/pull/40558): @aldenstpage
   - [ ] [DataprocCreateBatchOperator - Link for asynchronous mode  (#40643)](https://github.com/apache/airflow/pull/40643): @kandharvishnu
   - [x] [Revert "Fix `GCSToGCSOperator` behavior difference for moving single object (#40162)" (#40577)](https://github.com/apache/airflow/pull/40577): @MaksYermak
   - [x] [fix BigQueryInsertJobOperator's return value and openlineage extraction in deferrable mode (#40457)](https://github.com/apache/airflow/pull/40457): @kacpermuda
   - [x] [fix OpenLineage extraction for GCP deferrable operators (#40521)](https://github.com/apache/airflow/pull/40521): @kacpermuda
     Linked issues:
       - [x] [Linked Issue #40457](https://github.com/apache/airflow/pull/40457): @kacpermuda
   - [x] [40559: fix add project_id to submit_batch_job hook (#40560)](https://github.com/apache/airflow/pull/40560): @guillaumeblaquiere
     Linked issues:
       - [x] [Linked Issue #40559](https://github.com/apache/airflow/issues/40559): @guillaumeblaquiere
   - [x] [Resolve google deprecations in tests (#40629)](https://github.com/apache/airflow/pull/40629): @dirrao
   - [x] [Resolve google vertex ai deprecations in tests (#40506)](https://github.com/apache/airflow/pull/40506): @dirrao
   - [x] [Add notes about reverting the change in GCSToGCSOperator (#40579)](https://github.com/apache/airflow/pull/40579): @potiuk
## Provider [influxdb: 2.6.0rc1](https://pypi.org/project/apache-airflow-providers-influxdb/2.6.0rc1)
   - [ ] [add timeout to influx db (#40439)](https://github.com/apache/airflow/pull/40439): @romsharon98
   - [x] [Fix failure of "Add connection" introduced by influxdb change (#40469)](https://github.com/apache/airflow/pull/40469): @potiuk
     Linked issues:
       - [x] [Linked Issue #40439](https://github.com/apache/airflow/pull/40439): @romsharon98
## Provider [microsoft.azure: 10.2.0rc1](https://pypi.org/project/apache-airflow-providers-microsoft-azure/10.2.0rc1)
   - [ ] [S3 to wasb (#40511)](https://github.com/apache/airflow/pull/40511): @jroachgolf84
## Provider [openlineage: 1.9.1rc1](https://pypi.org/project/apache-airflow-providers-openlineage/1.9.1rc1)
   - [x] [openlineage: fix parsing dag tree with MappedOperator (#40621)](https://github.com/apache/airflow/pull/40621): @kacpermuda
## Provider [oracle: 3.10.3rc1](https://pypi.org/project/apache-airflow-providers-oracle/3.10.3rc1)
   - [ ] [Warn user about unused replace parameter in insert_rows (OracleHook) (#39408)](https://github.com/apache/airflow/pull/39408): @RichieSK
## Provider [snowflake: 5.6.0rc1](https://pypi.org/project/apache-airflow-providers-snowflake/5.6.0rc1)
   - [x] [chore: Add param support for client_request_mfa_token (#40394)](https://github.com/apache/airflow/pull/40394): @vanducng
## Provider [teradata: 2.4.0rc1](https://pypi.org/project/apache-airflow-providers-teradata/2.4.0rc1)
   - [x] [Added support of Teradata Compute Cluster Provision, Decommission, Suspend and Resume operations (#40509)](https://github.com/apache/airflow/pull/40509): @sc250072
## Provider [weaviate: 2.0.0rc1](https://pypi.org/project/apache-airflow-providers-weaviate/2.0.0rc1)
   - [ ] [Upgrade to weaviate-client to v4 (#40194)](https://github.com/apache/airflow/pull/40194): @Lee-W
   - [x] [Fix mypy problems in new waeviate client (#40330)](https://github.com/apache/airflow/pull/40330): @potiuk
   - [x] [Update pandas minimum requirement for Python 3.12 (#40272)](https://github.com/apache/airflow/pull/40272): @potiuk
   - [x] [Add dependency to httpx >= 0.25.0 everywhere (#40256)](https://github.com/apache/airflow/pull/40256): @potiuk
## Provider [ydb: 1.1.0rc1](https://pypi.org/project/apache-airflow-providers-ydb/1.1.0rc1)
   - [x] [support auth key from content and from file (#40390)](https://github.com/apache/airflow/pull/40390): @uzhastik

All users involved in the PRs:
@BenediktRamsauer @marcel-martinelli @kacpermuda @uzhastik @jsjasonseba @antoinetavant @theopus @CYarros10 @sc250072 @MaksYermak @boraberke @guillaumeblaquiere @o-nikolas @Lee-W @shahar1 @potiuk @ellism

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
I checked all my changes they look good. One SMALL thing.. I noticed that weaviate changelog is wrong - the 2.0.0 changelog contains also 1.4.2 changes and 1.4.2 is missing from changelog. This is caused by #40194 - where `2.0.0` description replaced 1.4.2 one rather than added it. This should not change the release status of 2.0.0 because changelog is not part of the package and we can fix it by cherry-picking #40663 that fixes it and reganerating the documentation (cc: @eladkal )

**Comment by kacpermuda** [comment]
I checked all my changes they look good. Thanks !

**Comment by sc250072** [comment]
I checked Teradata airflow provider and new feature(s) are working as expected.  Thank you!.

**Comment by MaksYermak** [comment]
I have checked all my changes they work as expected.

**Comment by vanducng** [comment]
I checked my change for the snowflake provider, it works as expected.

**Comment by marcel-martinelli** [comment]
I checked all my changes on the Databricks operator; it works fine!

**Comment by gopidesupavan** [comment]
Verified #40492 and #40504 are working fine. Thank you for the release efforts.

**Comment by dirrao** [comment]
I have verified [#40629)](https://github.com/apache/airflow/pull/40629) and [#40506)](https://github.com/apache/airflow/pull/40506). They are working as expected.

**Comment by antoinetavant** [comment]
I have verified the Docker operator, both #39620  and #40489 works as expected on airflow:2.8.3-python3.11 as well as airflow:2.9.2-python3.11

**Comment by BenediktRamsauer** [comment]
I have tested [#40642](https://github.com/apache/airflow/pull/40642) and it is working.

**Comment by guillaumeblaquiere** [comment]
Ok for #40560

**Comment by potiuk** [comment]
I am not sure if that qualifies for RC2, but currently in main AWS auth manager fails compatibility test for 2.8 - i described it in https://github.com/apache/airflow/issues/40684 - cc: @vincbeck, @eladkal

**Comment by potiuk** [comment]
So I guess with https://github.com/apache/airflow/pull/40690 it means RC2 for Amazon ?

**Comment by vincbeck** [comment]
Yes!

**Comment by eladkal** [comment]
I will exclude fab from rc1

**Comment by anteverse** [comment]
#40518 

Checked and working as expected.

**Comment by shahar1** [comment]
#40479 is ok

**Comment by jscheffl** [comment]
I just found a serious problem in databricks provider. PR coming in a moment.
If PR 40153 is contained in the release then for sure we need to stop and a -1 from my side.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jscheffl** [comment]
Dont see my previous email, -1 for databricks, raised a fix PR #40708 but would rather recomment to roll back #40153

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jscheffl** [comment]
Ah, emails are getting to ticket and not to devlist :-D

As far as I see the PR #40153 is not in the providers-cut? Then it is OK...

**Comment by pankajkoti** [comment]
yes, #40153 is not in this providers wave

**Comment by dabla** [comment]
I have the impression the issue for [40615](https://github.com/apache/airflow/pull/40615) is still there

**Comment by potiuk** [comment]
> PR [40615](https://github.com/apache/airflow/pull/40615) partially fixes the issue, it doesn't fix it for the JdbcHook as there the driver_path and driver_class property causes the same issue as placeholder did. Also mentioned this in original [issue](https://github.com/apache/airflow/issues/40609).

Yeah. Good catch @dabla  -> I think it's not a blocker for this release, it's not a regression comparing to already released common.sql and we can always fix it in the next round (and it has rather small-ish impact).

**Comment by eladkal** [comment]
@dabla can you raise PR with a fix for it?

**Comment by dabla** [comment]
> @dabla can you raise PR with a fix for it?

Hey Elad, yes I already have a fix for it, but would like to see PR [#40665](https://github.com/apache/airflow/pull/40665/) merged first as this will allow me to have a cleaner solution.  Unless you want this fix first then I will have to refactor the fix in [#40665](https://github.com/apache/airflow/pull/40665/) afterwards, that's also possible.  It's up to you

**Comment by potiuk** [comment]
I think it's not a regression and can be easily fixed in the next round if you ask me :) - there are few other things that @dabla is contributing in this area https://github.com/apache/airflow/pull/40665 and likely they could be done in next release ?

**Comment by eladkal** [comment]
Thank you everyone. Providers are released (excluding amazon and weaviate)

I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).

**Comment by dabla** [comment]
> @dabla can you raise PR with a fix for it?

https://github.com/apache/airflow/pull/40751
