### ISSUE TITLE
Status of testing of Apache Airflow 2.9.3rc1

### ISSUE THREAD

**Issue by utkarsharma2** [apache/airflow#40756]
### Body

We are kindly requesting that contributors to [Apache Airflow RC 2.9.3rc1](https://pypi.org/project/apache-airflow/2.9.3rc1/) help test the RC.

Please let us know by commenting if the issue is addressed in the latest RC.

- [x] [Fix dag task scheduled and queued duration metrics (#37936)](https://github.com/apache/airflow/pull/37936): @htpawel
- [ ] [Rename "try_number" increments that are unrelated to the airflow concept (#39317)](https://github.com/apache/airflow/pull/39317): @dstandish
- [x] [Change `httpx` to `requests` in `file_task_handler` (#39799)](https://github.com/apache/airflow/pull/39799): @softyoungha
     Linked issues:
     - [HTTP_PROXY settings do not recognize Worker Pods within NO_PROXY CIDR range (#39794)](https://github.com/apache/airflow/issues/39794)
- [ ] [uv version bump to 0.2.3 (#39848)](https://github.com/apache/airflow/pull/39848): @dirrao
- [x] [Improve trigger UI for string array format validation (#39993)](https://github.com/apache/airflow/pull/39993): @techolga
     Linked issues:
     - [Param schema `array` type does does not work with `items` element (#39972)](https://github.com/apache/airflow/issues/39972)
- [ ] [Use a join for TI notes in TI batch API endpoint (#40028)](https://github.com/apache/airflow/pull/40028): @jedcunningham
- [x] [Upgrade to latest installers (#40107)](https://github.com/apache/airflow/pull/40107): @potiuk
- [x] [Ensures DAG params order regardless of backend (#40156)](https://github.com/apache/airflow/pull/40156): @Usiel
- [ ] [Upgrade build installers and dependencies (#40177)](https://github.com/apache/airflow/pull/40177): @potiuk
- [x] [Fix import future annotations in venv jinja template (#40208)](https://github.com/apache/airflow/pull/40208): @phi-friday
- [ ] [Swap dag run link from legacy graph to grid with graph tab (#40241)](https://github.com/apache/airflow/pull/40241): @bbovenzi
- [x] [Update to uv 0.2.11 (#40244)](https://github.com/apache/airflow/pull/40244): @potiuk
- [ ] [Remove "experimental" banner for OTel Metrics (#40286)](https://github.com/apache/airflow/pull/40286): @ferruzzi
- [ ] [Fix compatibility with old MySQL 8.0 (#40314)](https://github.com/apache/airflow/pull/40314): @jedcunningham
- [ ] [Add `[webserver]update_fab_perms` to deprecated configs (#40317)](https://github.com/apache/airflow/pull/40317): @ephraimbuddy
- [ ] [Fix TriggeredDagRunOperator triggered link (#40336)](https://github.com/apache/airflow/pull/40336): @fredthomsen @ljades
     Linked issues:
     - [TriggerDagRunOperator External Link doesn't link with execution date to match to triggered DAG (#19264)](https://github.com/apache/airflow/issues/19264)
- [ ] [Fix dag (un)pausing won't work on environment where dag files are missing (#40345)](https://github.com/apache/airflow/pull/40345): @boushphong @raphaelauv
     Linked issues:
     - [cli | airflow dags unpause - fail cause not founding dags (#38834)](https://github.com/apache/airflow/issues/38834)
- [x] [Upgrade `pip` to just-released 24.1 (#40367)](https://github.com/apache/airflow/pull/40367): @potiuk
     Linked issues:
     - [Test `pip 24.1b2` (#40184)](https://github.com/apache/airflow/pull/40184)
- [x] [Upgrade to latest version of hatchling as build dependency (#40387)](https://github.com/apache/airflow/pull/40387): @potiuk
- [x] [extra being passed to SQLalchemy (#40391)](https://github.com/apache/airflow/pull/40391): @aritra24 @MialLewis
     Linked issues:
     - [`__extra__` being passed to SQLalchemy engine url erroneously (#40056)](https://github.com/apache/airflow/issues/40056)
- [ ] [fix(statsd): handle unsupport operand int + str when value of tag is not str (#40407)](https://github.com/apache/airflow/pull/40407): @DLT1412
- [x] [Update uv to 0.2.15 (#40411)](https://github.com/apache/airflow/pull/40411): @potiuk
- [x] [Remove logging for "blocked" events (#40446)](https://github.com/apache/airflow/pull/40446): @ayushjain2809 @bbovenzi
     Linked issues:
     - [Clean up webserver endpoints adding to audit log (#37580)](https://github.com/apache/airflow/pull/37580)
- [ ] [Fix calendar view scroll (#40458)](https://github.com/apache/airflow/pull/40458): @bbovenzi
- [x] [Upgrade to latest `pip` and `uv` version (#40463)](https://github.com/apache/airflow/pull/40463): @potiuk
- [x] [Validating provider description for urls in provider list view (#40475)](https://github.com/apache/airflow/pull/40475): @amoghrajesh
- [x] [uv version bump 0.2.18 (#40501)](https://github.com/apache/airflow/pull/40501): @dirrao
- [ ] [Fix latest botocore tests to not conflict with apache-beam provider (#40502)](https://github.com/apache/airflow/pull/40502): @potiuk
- [ ] [Recognize quotes when parsing urls in logs (#40508)](https://github.com/apache/airflow/pull/40508): @smlee729
- [ ] [Disable rendering for doc_md (#40522)](https://github.com/apache/airflow/pull/40522): @Lee-W
- [x] [Update trove classifiers to the latest version as build dependency (#40542)](https://github.com/apache/airflow/pull/40542): @potiuk
- [ ] [Fix bug in `SchedulerJobRunner._process_executor_events` (#40563)](https://github.com/apache/airflow/pull/40563): @vincbeck
- [x] [Upgrade to another version of trove-classifier (new CUDA classifiers) (#40564)](https://github.com/apache/airflow/pull/40564): @potiuk
- [x] [Skip checking subdagslist if taskinstance state is skipped (#40578)](https://github.com/apache/airflow/pull/40578): @abhishekbhakat
     Linked issues:
     - [Airflow API for Updating TaskInstance State to skipped is broken (#40575)](https://github.com/apache/airflow/issues/40575)

Thanks to all who contributed to the release (probably not a complete list!):
@fredthomsen @bbovenzi @vincbeck @Usiel @ayushjain2809 @Lee-W @aritra24 @ephraimbuddy @raphaelauv @softyoungha @amoghrajesh @smlee729 @ljades @MialLewis @ferruzzi @boushphong @techolga @DLT1412 @htpawel @abhishekbhakat @phi-friday @jedcunningham @potiuk @dirrao @dstandish

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by phi-friday** [comment]
#40208
it works fine (test operators: `_PythonVirtualenvDecoratedOperator`, `_DockerDecoratedOperator`)

**Comment by Usiel** [comment]
https://github.com/apache/airflow/pull/40156 works as expected on our dev cluster

**Comment by amoghrajesh** [comment]
Checked all my changes (https://github.com/apache/airflow/pull/40475) and ran a few sample dags too, works as expected

**Comment by abhishekbhakat** [comment]
Verified #40578, working as expected.

**Comment by aritra24** [comment]
Checked my changes #40391 and they work as expected

**Comment by softyoungha** [comment]
Checked #39799, works as expected

**Comment by htpawel** [comment]
#37936 works fine

**Comment by techolga** [comment]
Tried #39993, works as expected

**Comment by fredthomsen** [comment]
#40336 works as expected.

**Comment by utkarsharma2** [comment]
Airflow 2.9.3 has been released. Thank you all for testing this release
