### ISSUE TITLE
Status of testing Providers that were prepared on July 12, 2024

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#40752]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

**Issues tested with rc1 are marked as tested by default on rc2 yet we encourage you to retest rc2 as well.**

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 8.26.0rc2](https://pypi.org/project/apache-airflow-providers-amazon/8.26.0rc2)
   - [ ] [Do not dynamically determine op links for emr serverless start job operator (#40627)](https://github.com/apache/airflow/pull/40627): @o-nikolas
     Linked issues:
       - [ ] [Linked Issue #40103](https://github.com/apache/airflow/issues/40103): @fjmacagno
   - [x] [Be able to remove ACL in S3 hook's copy_object (#40518)](https://github.com/apache/airflow/pull/40518): @anteverse
   - [ ] [feat(aws): provide the context to check_fn in S3 sensor (#40686)](https://github.com/apache/airflow/pull/40686): @hussein-awala
   - [x] [Fix OpenLineage extraction for deferrable AthenaOperator (#40545)](https://github.com/apache/airflow/pull/40545): @kacpermuda
   - [ ] [Reduce memory footprint of s3 key trigger (#40473)](https://github.com/apache/airflow/pull/40473): @dstandish
   - [ ] [Adding cluster to ecs trigger event to avoid defer error (#40482)](https://github.com/apache/airflow/pull/40482): @ellisms
     Linked issues:
       - [ ] [Linked Issue #40207](https://github.com/apache/airflow/issues/40207): @frantoja
   - [ ] [Fix deferrable AWS SageMaker operators (#40706)](https://github.com/apache/airflow/pull/40706): @vincbeck
   - [x] [Make `AwsAuthManager` compatible with only Airflow >= 2.9 (#40690)](https://github.com/apache/airflow/pull/40690): @vincbeck
     Linked issues:
       - [x] [Linked Issue #40684](https://github.com/apache/airflow/issues/40684): @potiuk
   - [x] [Add serialization opt to s3 operator (#40659)](https://github.com/apache/airflow/pull/40659): @eldar-elne
     Linked issues:
       - [x] [Linked Issue #40637](https://github.com/apache/airflow/issues/40637): @eldar-elne
   - [x] [Use base aws classes in AWS Glue Data Catalog Sensors (#40492)](https://github.com/apache/airflow/pull/40492): @gopidesupavan
     Linked issues:
       - [x] [Linked Issue #35278](https://github.com/apache/airflow/issues/35278): @Taragolis
   - [x] [Use base aws classes in AWS Glue Crawlers Operators/Sensors/Triggers (#40504)](https://github.com/apache/airflow/pull/40504): @gopidesupavan
     Linked issues:
       - [x] [Linked Issue #35278](https://github.com/apache/airflow/issues/35278): @Taragolis
   - [ ] [Share data loader to across asyncio boto sessions (#40658)](https://github.com/apache/airflow/pull/40658): @dstandish
   - [ ] [Send important executor logs to task logs (#40468)](https://github.com/apache/airflow/pull/40468): @vincbeck
     Linked issues:
       - [ ] [Linked Issue #32646](https://github.com/apache/airflow/pull/32646): @pankajkoti
   - [ ] [Send important executor logs to task logs in `AwsBatchExecutor` (#40698)](https://github.com/apache/airflow/pull/40698): @vincbeck
     Linked issues:
       - [ ] [Linked Issue #40468](https://github.com/apache/airflow/pull/40468): @vincbeck
## Provider [weaviate: 2.0.0rc2](https://pypi.org/project/apache-airflow-providers-weaviate/2.0.0rc2)
   - [ ] [Upgrade to weaviate-client to v4 (#40194)](https://github.com/apache/airflow/pull/40194): @Lee-W
   - [x] [Fix mypy problems in new waeviate client (#40330)](https://github.com/apache/airflow/pull/40330): @potiuk
   - [ ] [Tiny PR: Fix two typos in Weaviate provider code (#40670)](https://github.com/apache/airflow/pull/40670): @TJaniF
     Linked issues:
       - [ ] [Linked Issue #40194](https://github.com/apache/airflow/pull/40194): @Lee-W

All users involved in the PRs:
@dstandish @ellisms @TJaniF @Lee-W @eldar-elne @hussein-awala @potiuk @gopidesupavan @anteverse @kacpermuda @vincbeck @o-nikolas

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by eldar-elne** [comment]
@eladkal From my side (#40659 + #40637 )- everything works as expected with RC2, LMK if u need anything else.

**Comment by eladkal** [comment]
Thank you everyone. Providers are released.

I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
