### ISSUE TITLE
Status of testing of Apache Airflow Helm Chart 1.15.0rc1

### ISSUE THREAD

**Issue by jedcunningham** [apache/airflow#40907]
We are kindly requesting that contributors to [Apache Airflow Helm Chart 1.15.0rc1](https://dist.apache.org/repos/dist/dev/airflow/helm-chart/1.15.0rc1) help test the RC.

Please let us know by commenting if the issue is addressed in the latest RC.

- [x] [gitSync: add extraEnvFrom to git-sync containers to support proxy settings from k8s secret (#39031)](https://github.com/apache/airflow/pull/39031): @rasulkarimov
- [ ] [fix a vulnerability in protobuf for pgbouncer_exporter (#40303)](https://github.com/apache/airflow/pull/40303): @andrew-stein-sp
- [x] [Switch to newer pgbouncer-exporter image as default for Helm Chart (#40318)](https://github.com/apache/airflow/pull/40318): @potiuk @andrew-stein-sp
     Linked issues:
     - [fix a vulnerability in protobuf for pgbouncer_exporter (#40303)](https://github.com/apache/airflow/pull/40303)
- [ ] [Fix/ unnecessary `or` in git ssh key (#40393)](https://github.com/apache/airflow/pull/40393): @romsharon98
- [ ] [Fix startupProbe timing comment (#40412)](https://github.com/apache/airflow/pull/40412): @jedcunningham
- [ ] [Enhance User Experience by Opening external UI Links in new Tab on browser. (#40635)](https://github.com/apache/airflow/pull/40635): @VICIWUOHA
- [x] [Clarify PMC members vs PMCs (#40777)](https://github.com/apache/airflow/pull/40777): @potiuk
- [ ] [Chart: Default airflow version to 2.9.3 (#40816)](https://github.com/apache/airflow/pull/40816): @utkarsharma2

Thanks to all who contributed to the release (probably not a complete list!):
@potiuk @romsharon98 @utkarsharma2 @jedcunningham @VICIWUOHA @rasulkarimov @andrew-stein-sp

**Comment by VICIWUOHA** [comment]
Hi @jedcunningham , what are the steps in testing this ? any docs link

**Comment by VICIWUOHA** [comment]
> Hi @jedcunningham , what are the steps in testing this ? any docs link

hello @eladkal , @jedcunningham , @potiuk ...
just following up here.

**Comment by potiuk** [comment]
https://github.com/apache/airflow/blob/main/dev/README_RELEASE_HELM_CHART.md#verify-release-candidates-by-contributors

**Comment by potiuk** [comment]
All my changes are in ! Tested the chart looks good!

**Comment by rasulkarimov** [comment]
Tested. envFrom works for gitSync init/sidecar containers.

**Comment by jedcunningham** [comment]
Thanks for testing the RC @potiuk and @rasulkarimov. The release is underway!
