### ISSUE TITLE
 Status of testing Providers that were prepared on July 21, 2024

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#40910]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [apache.beam: 5.7.2rc1](https://pypi.org/project/apache-airflow-providers-apache-beam/5.7.2rc1)
   - [ ] [Update default value for job_name in DataflowConfiguration (#40645)](https://github.com/apache/airflow/pull/40645): @e-galan
     Linked issues:
       - [ ] [Linked Issue #40515](https://github.com/apache/airflow/issues/40515): @turb
## Provider [apache.spark: 4.9.0rc1](https://pypi.org/project/apache-airflow-providers-apache-spark/4.9.0rc1)
   - [x] [Add `kubernetes_application_id` to `SparkSubmitHook` (#40753)](https://github.com/apache/airflow/pull/40753): @nevcohen
   - [x] [Fix/spark submit pod name has driver (#40732)](https://github.com/apache/airflow/pull/40732): @romsharon98

All users involved in the PRs:
@romsharon98 @nevcohen @e-galan

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by e-galan** [comment]
Hi @eladkal . #40645 contains small changes for two provider packages:
- `airflow/providers/google/cloud/operators/dataflow.py` which is part of _apache-airflow-providers-google_ 
- `airflow/providers/apache/beam/operators/beam.py` which is part of _apache-airflow-providers-apache-beam`_

The beam operator is using an object from the `dataflow.py` module. It won't work if only  _apache-airflow-providers-apache-beam`_ is released and will cause bugs.

**Comment by eladkal** [comment]
> Hi @eladkal . #40645 contains small changes for two provider packages:
> 
> * `airflow/providers/google/cloud/operators/dataflow.py` which is part of _apache-airflow-providers-google_
> * `airflow/providers/apache/beam/operators/beam.py` which is part of _apache-airflow-providers-apache-beam`_
> 
> The beam operator is using an object from the `dataflow.py` module. It won't work if only _apache-airflow-providers-apache-beam`_ is released and will cause bugs.

Then this is a bug in beam provider.
If the code needs specific version of google provider it needs to have version check for it. Nothing prevents users from bumping beam provider without bumping google provider

**Comment by romsharon98** [comment]
Checked my changes, working as expected 😃

**Comment by e-galan** [comment]
> > Hi @eladkal . #40645 contains small changes for two provider packages:
> > 
> > * `airflow/providers/google/cloud/operators/dataflow.py` which is part of _apache-airflow-providers-google_
> > * `airflow/providers/apache/beam/operators/beam.py` which is part of _apache-airflow-providers-apache-beam`_
> > 
> > The beam operator is using an object from the `dataflow.py` module. It won't work if only _apache-airflow-providers-apache-beam`_ is released and will cause bugs.
> 
> Then this is a bug in beam provider. If the code needs specific version of google provider it needs to have version check for it. Nothing prevents users from bumping beam provider without bumping google provider

That's the problem. #40645 has not been included into any provider packages yet, so I don't know the version of 
 the Google provider package that I can use for the version check.  
 
On the other hand the PR fixes an already existing bug, which has been present since _providers-apache-beam/5.6.3_,  so upgrading only the Apache Beam package will not make anything worse.

**Comment by nevcohen** [comment]
Also, checked my changes, and working as expected

**Comment by eladkal** [comment]
> That's the problem. https://github.com/apache/airflow/pull/40645 has not been included into any provider packages yet, so I don't know the version of
> the Google provider package that I can use for the version check.


You can add check for `apache-airflow-providers-google >=10.22.0`  which is the next feature release

**Comment by eladkal** [comment]
Thank you everyone. Providers are released.
apache beam is excluded from this wave.

I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
