### ISSUE TITLE
Temporary disabling featuers in "canary" run due to problems with self-hosted runners

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#40925]
### Body

Our self hosted runners are old (not updated since Sep 2023 - because the workflows in https://github.com/ashb/runner to update them have not been running. We temporarily switched the canary runs to run using public runners in:

* https://github.com/apache/airflow/pull/40913 followed up by 
* https://github.com/apache/airflow/pull/40921

This has some limitations:

* [ ] the canary runs are running full tests and they take more than 1h 20 minutes to run (self-hosted were ~3/4 times faster
* [ ] they do not build and refresh cache for ARM images (work in progress in #41049 )
* [x] they run 2x a day currently as scheduled runs and can be manually triggered from  https://github.com/apache/airflow/actions/workflows/ci.yml as needed  (work in progress to increased to 4xDay by #41056 and it should be enough).
* [ ] they do not publish documentation because there is not enough disk space on public runners - PR https://github.com/apache/airflow/pull/41057 
* [ ] we cannot release the multi-platform images via Github workflow (it requires public runner + ARM instance started by it)

This could be fixed in a varioous ways:

* when @ashb is back from holidays we can restore the old runners approach
* we can continue and complete work that @hussein-awala has done on using GitHub Kubernetes Controller to run ephemeral runner on our infrastructure
* some of the above (ARM) can be fixed by employing self-hosted ASF runners likely https://cwiki.apache.org/confluence/display/INFRA/ASF+Infra+provided+self-hosted+runners

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.
