### ISSUE TITLE
Status of testing Providers that were prepared on July 28, 2024

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#41080]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 8.27.0rc1](https://pypi.org/project/apache-airflow-providers-amazon/8.27.0rc1)
   - [ ] [Add RedriveExecution support to StepFunctionStartExecutionOperator (#40976)](https://github.com/apache/airflow/pull/40976): @gopidesupavan
   - [ ] [AIP-62: add hook lineage collection support for S3Hook  (#40819)](https://github.com/apache/airflow/pull/40819): @mobuchowski
   - [ ] [Introduce Amazon Kinesis Analytics V2 (Managed Service for Apache Flink application)  (#40765)](https://github.com/apache/airflow/pull/40765): @gopidesupavan
   - [ ] [Make EMR Container Trigger max attempts retries match the Operator (#41008)](https://github.com/apache/airflow/pull/41008): @o-nikolas
     Linked issues:
       - [ ] [Linked Issue #40483](https://github.com/apache/airflow/issues/40483): @akomisarek
   - [ ] [Fix `RdsStopDbOperator` operator in deferrable mode (#41059)](https://github.com/apache/airflow/pull/41059): @vincbeck
   - [ ] [Fix `RedshiftCreateClusterOperator` to always specify `PubliclyAccessible` (#40872)](https://github.com/apache/airflow/pull/40872): @vincbeck
   - [ ] [Update `example_redshift` and `example_redshift_s3_transfers` to use `RedshiftDataHook` instead of `RedshiftSQLHook` (#40970)](https://github.com/apache/airflow/pull/40970): @vincbeck
   - [ ] [openlineage: migrate OpenLineage provider to V2 facets. (#39530)](https://github.com/apache/airflow/pull/39530): @JDarDagran
   - [ ] [[AIP-62] Translate AIP-60 URI to OpenLineage (#40173)](https://github.com/apache/airflow/pull/40173): @kacpermuda
     Linked issues:
       - [ ] [Linked Issue #40335](https://github.com/apache/airflow/pull/40335): @JDarDagran
       - [ ] [Linked Issue #38767](https://github.com/apache/airflow/issues/38767): @mobuchowski
   - [ ] [Move AWS Managed Service for Apache Flink sensor states to Hook (#40896)](https://github.com/apache/airflow/pull/40896): @gopidesupavan
   - [ ] [Replace usages of task context logger with the log table (#40867)](https://github.com/apache/airflow/pull/40867): @dstandish
## Provider [fab: 1.2.2rc1](https://pypi.org/project/apache-airflow-providers-fab/1.2.2rc1)
   - [x] [Bug fix: sync perm command not able to use custom security manager (#41020)](https://github.com/apache/airflow/pull/41020): @dirrao
   - [x] [Bump version checked by FAB provider on logout CSRF protection to 2.10.0 (#40784)](https://github.com/apache/airflow/pull/40784): @potiuk
     Linked issues:
       - [x] [Linked Issue #40470](https://github.com/apache/airflow/issues/40470): @Al2a2d2m
       - [x] [Linked Issue #40479](https://github.com/apache/airflow/pull/40479): @shahar1
   - [x] [AIP-44 make database isolation mode work in Breeze (#40894)](https://github.com/apache/airflow/pull/40894): @potiuk
## Provider [google: 10.21.1rc1](https://pypi.org/project/apache-airflow-providers-google/10.21.1rc1)
   - [ ] [Dynamic import MySqlHook/PostgresHook in CloudSQLDatabaseHook (#41009)](https://github.com/apache/airflow/pull/41009): @jhongy1994
     Linked issues:
       - [ ] [Linked Issue #40175](https://github.com/apache/airflow/issues/40175): @bourliam
   - [ ] [Make google_analytics_admin system tests self sufficient (#40951)](https://github.com/apache/airflow/pull/40951): @moiseenkov
   - [ ] [Fix Custom Training Job operators to accept results without a model in def mode (#40685)](https://github.com/apache/airflow/pull/40685): @e-galan
     Linked issues:
       - [ ] [Linked Issue #40476](https://github.com/apache/airflow/issues/40476): @vignesh-sc
   - [ ] [Fix behavior for reattach_state parameter in BigQueryInsertJobOperator (#40664)](https://github.com/apache/airflow/pull/40664): @VladaZakharova
   - [ ] [Refactor dataproc system tests (#40720)](https://github.com/apache/airflow/pull/40720): @VladaZakharova
   - [ ] [openlineage: migrate OpenLineage provider to V2 facets. (#39530)](https://github.com/apache/airflow/pull/39530): @JDarDagran
   - [ ] [Resolve google cloud sql deprecation in tests (#40834)](https://github.com/apache/airflow/pull/40834): @dirrao
   - [ ] [Update default value for job_name in DataflowConfiguration (#40645)](https://github.com/apache/airflow/pull/40645): @e-galan
     Linked issues:
       - [ ] [Linked Issue #40515](https://github.com/apache/airflow/issues/40515): @turb

All users involved in the PRs:
@moiseenkov @dstandish @dirrao @potiuk @JDarDagran @gopidesupavan @mobuchowski @VladaZakharova @o-nikolas @e-galan @kacpermuda @vincbeck @jhongy1994

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
I checked all my changes. Also verfied that FAB 1.2.2 fixes the logout issue for 2.9.2. Looks good.

**Comment by moiseenkov** [comment]
Hi, #40951 works as expected

**Comment by JDarDagran** [comment]
https://github.com/apache/airflow/pull/39530 adds `apache-airflow-providers-common-compat>=1.1.0` dependency to amazon and google providers. You can't install new packages without `apache-airflow-providers-common-compat==1.1.0rc0` release (which may be missed when following instructions from the docs to test RCs with flag `--no-deps`)

**Comment by potiuk** [comment]
> https://github.com/apache/airflow/pull/39530 adds apache-airflow-providers-common-compat>=1.1.0 dependency to amazon and google providers. You can't install new packages without apache-airflow-providers-common-compat==1.1.0rc0 release (which may be missed when following instructions from the docs to test RCs with flag --no-deps)

Ah right - so common-compat should be released as well here .. cc: @eladkal

**Comment by gopidesupavan** [comment]
Yes it is failing to install package.
<img width="1755" alt="image" src="https://github.com/user-attachments/assets/d71fd653-127e-4d9d-b754-51fc489f9b75">

Once it updated i will test these #40976 , #40765 and #40896.

**Comment by dirrao** [comment]
[#41020)](https://github.com/apache/airflow/pull/41020): [@dirrao](https://github.com/dirrao) working as expected.

**Comment by e-galan** [comment]
#40645 works as expected

**Comment by akomisarek** [comment]
I think I will wait for rc2 cut, as I am not able to test it easily in my environment (we start via Docker): 

Without using --no-deps as reported above the Depencencies are not installing.

Adding --no-deps allows the dependencies to install, but I think I have got further version clashes:
airflow-1   |   File "/home/airflow/.local/lib/python3.10/site-packages/pydantic_core/__init__.py", line 29, in <module>
airflow-1   |     from .core_schema import CoreConfig, CoreSchema, CoreSchemaType, ErrorType
airflow-1   |   File "/home/airflow/.local/lib/python3.10/site-packages/pydantic_core/core_schema.py", line 15, in <module>
airflow-1   |     from typing_extensions import deprecated
airflow-1   | ImportError: cannot import name 'deprecated' from 'typing_extensions' (/home/airflow/.local/lib/python3.10/site-packages/typing_extensions.py)

We might have some dependencies causing those issues, but that's why I don't want to omit them! 

Thanks, I will keep an eye on the thread and confirm/retest when the new RC is in place. Thanks for the support 🙏

**Comment by e-galan** [comment]
#40685 works as expected

**Comment by eladkal** [comment]
Thank you everyone. Providers are released.
Providers amazon and google are excluded - I will cut followup release shortly

I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
