### ISSUE TITLE
Status of testing Providers that were prepared on August 25, 2024

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#41722]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [celery: 3.8.1rc1](https://pypi.org/project/apache-airflow-providers-celery/3.8.1rc1)
   - [ ] [Add slots_occupied to old hybrid executors (#41602)](https://github.com/apache/airflow/pull/41602): @o-nikolas
     Linked issues:
       - [ ] [Linked Issue #41525](https://github.com/apache/airflow/issues/41525): @LipuFei
## Provider [cncf.kubernetes: 8.4.1rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/8.4.1rc1)
   - [ ] [K8s Executor: failing the task in case the watcher receives an event with the reason ProviderFailed (#41186)](https://github.com/apache/airflow/pull/41186): @dirrao
   - [ ] [Fix 'do_xcom_push' and 'get_logs' functionality for KubernetesJobOperator (#40814)](https://github.com/apache/airflow/pull/40814): @MaksYermak
   - [ ] [Add missing field to KubernetesHook (#41464)](https://github.com/apache/airflow/pull/41464): @VladaZakharova
   - [ ] [Add slots_occupied to old hybrid executors (#41602)](https://github.com/apache/airflow/pull/41602): @o-nikolas
     Linked issues:
       - [ ] [Linked Issue #41525](https://github.com/apache/airflow/issues/41525): @LipuFei
## Provider [openlineage: 1.11.0rc2](https://pypi.org/project/apache-airflow-providers-openlineage/1.11.0rc2)
   - [x] [feat: [openlineage] add debug facet to all events (#41217)](https://github.com/apache/airflow/pull/41217): @kacpermuda
   - [x] [feat: add fileloc to DAG info in AirflowRunFacet (#41311)](https://github.com/apache/airflow/pull/41311): @kacpermuda
   - [x] [chore: remove openlineage client deprecated from_environment() method (#41310)](https://github.com/apache/airflow/pull/41310): @kacpermuda
   - [x] [feat: openlineage listener captures hook-level lineage (#41482)](https://github.com/apache/airflow/pull/41482): @mobuchowski
   - [x] [fix: get task dependencies without serializing task tree to string (#41494)](https://github.com/apache/airflow/pull/41494): @mobuchowski
   - [x] [fix: return empty data instead of None when OpenLineage on_start method is missing (#41268)](https://github.com/apache/airflow/pull/41268): @kacpermuda
   - [x] [fix: openlineage replace dagTree with downstream_task_ids (#41587)](https://github.com/apache/airflow/pull/41587): @kacpermuda
     Linked issues:
       - [x] [Linked Issue #41505](https://github.com/apache/airflow/issues/41505): @mobuchowski
       - [x] [Linked Issue #41494](https://github.com/apache/airflow/pull/41494): @mobuchowski
## Provider [ssh: 3.13.1rc1](https://pypi.org/project/apache-airflow-providers-ssh/3.13.1rc1)
   - [x] [SSHHook: check if existing connection is still alive (#41061)](https://github.com/apache/airflow/pull/41061): @dolfinus
     Linked issues:
       - [x] [Linked Issue #40377](https://github.com/apache/airflow/pull/40377): @MRLab12
## Provider [tabular: 1.6.1rc1](https://pypi.org/project/apache-airflow-providers-tabular/1.6.1rc1)
   - [x] [Mark tabular provider as removed (#41629)](https://github.com/apache/airflow/pull/41629): @eladkal

All users involved in the PRs:
@dolfinus @mobuchowski @VladaZakharova @dirrao @o-nikolas @eladkal @kacpermuda @MaksYermak

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by mobuchowski** [comment]
I've checked OpenLineage provider changes on a few example DAGs and they work as expected.

**Comment by kacpermuda** [comment]
I've also checked OpenLineage provider on a few example DAGs running on Astro and they work as expected 👍

**Comment by dolfinus** [comment]
I'm using a fork of ssh provider with changes from #41061 for almost a month.

**Comment by eladkal** [comment]
Thank you everyone. Providers are released.

I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
