### ISSUE TITLE
Status of testing of Apache Airflow 2.10.1rc1

### ISSUE THREAD

**Issue by utkarsharma2** [apache/airflow#41956]
### Body

We are kindly requesting that contributors to [Apache Airflow RC 2.10.1rc1](https://pypi.org/project/apache-airflow/2.10.1rc1/) help test the RC.

Please let us know by commenting if the issue is addressed in the latest RC.

- [ ] [Fix try selector refresh (#41483) (#41503)](https://github.com/apache/airflow/pull/41503): @bbovenzi
     Linked issues:
     - [Fix try selector refresh (#41483)](https://github.com/apache/airflow/pull/41483)
- [ ] [Field Deletion Warning when editing Connections (#41144) (#41504)](https://github.com/apache/airflow/pull/41504): @bbovenzi @lh5844
     Linked issues:
     - [Field Deletion Warning when editing Connections (#41144)](https://github.com/apache/airflow/pull/41144)
- [x] [Fix UI rendering when XCom is INT, FLOAT, BOOL or NULL (#41516) (#41605)](https://github.com/apache/airflow/pull/41605): @jscheffl
- [ ] [[Backport] Fix InletEventsAccessors type stub (#41572) (#41607)](https://github.com/apache/airflow/pull/41607): @uranusjr
- [x] [Apply GitHub workflow changes to stable branch (#41623)](https://github.com/apache/airflow/pull/41623): @potiuk
- [x] [Adding url sanitisation for extra links (#41665) (#41680)](https://github.com/apache/airflow/pull/41680): @amoghrajesh
- [x] [[Backport] Splitting syspath preparation into stages (#41694)](https://github.com/apache/airflow/pull/41694): @amoghrajesh @uranusjr
     Linked issues:
     - [Splitting syspath preparation into stages (#41672)](https://github.com/apache/airflow/pull/41672)
- [x] [fix log for notifier(instance) without __name__ (#41591) (#41699)](https://github.com/apache/airflow/pull/41699): @obarisk
- [x] [Adding rel property to hyperlinks in logs (#41696) (#41783)](https://github.com/apache/airflow/pull/41783): @amoghrajesh
- [x] [Remove deprecation warning for cgitb in Plugins Manager (#41732) (#41793)](https://github.com/apache/airflow/pull/41793): @potiuk
- [x] [Keep FAB compatibility for versions before 1.3.0 in 2.10 (#41549) (#41809)](https://github.com/apache/airflow/pull/41809): @joaopamaral
- [ ] [Don't Fail LocalTaskJob on heartbeat (#41704) (#41810)](https://github.com/apache/airflow/pull/41810): @collinmcnulty @jedcunningham
     Linked issues:
     - [Don't Fail LocalTaskJob on heartbeat (#41704)](https://github.com/apache/airflow/pull/41704)
- [ ] [Fix: DAGs are not marked as stale if the dags folder change (#41433) (#41829)](https://github.com/apache/airflow/pull/41829): @utkarsharma2
- [x] [Set end_date and duration for triggers completed with end_from_trigger as True (#41834)](https://github.com/apache/airflow/pull/41834): @Lee-W
- [x] [[Backport] logout link in no roles error page fix (#41813) (#41845)](https://github.com/apache/airflow/pull/41845): @gagan-bhullar-tech @shahar1
     Linked issues:
     - [logout link in no roles error page fix (#41813)](https://github.com/apache/airflow/pull/41813)
- [ ] [Handle Example dags case when checking for missing files (#41856) (#41874)](https://github.com/apache/airflow/pull/41874): @utkarsharma2
     Linked issues:
     - [DAGs are not marked as stale if the AIRFLOW__CORE__DAGS_FOLDER changes (#41432)](https://github.com/apache/airflow/issues/41432)
- [x] [Bump webpack from 5.76.0 to 5.94.0 in /airflow/www (#41864) (#41879)](https://github.com/apache/airflow/pull/41879): @potiuk
- [x] [Adding tojson filter to example_inlet_event_extra example dag (#41873) (#41890)](https://github.com/apache/airflow/pull/41890): @potiuk
- [x] [Make Scarf usage reporting in major+minor versions and counters in buckets (#41898) (#41900)](https://github.com/apache/airflow/pull/41900): @jscheffl
- [x] [Add backcompat check for executors that don't inherit BaseExecutor (#… (#41927)](https://github.com/apache/airflow/pull/41927): @potiuk
- [x] [Protect against None components of universal pathlib xcom backend (#4… (#41938)](https://github.com/apache/airflow/pull/41938): @potiuk
     Linked issues:
     - [Universal-pathlib 0.2.3 seems to break compatibility with 0.2.2 (at least breaks mypy checks). (#41723)](https://github.com/apache/airflow/issues/41723)
- [x] [Lower down universal-pathlib minimum to 0.2.2 (#41939) (#41943)](https://github.com/apache/airflow/pull/41943): @potiuk

Thanks to all who contributed to the release (probably not a complete list!):
@gagan-bhullar-tech @obarisk @uranusjr @utkarsharma2 @bbovenzi @lh5844 @jedcunningham @amoghrajesh @jscheffl @shahar1 @potiuk @joaopamaral @collinmcnulty @Lee-W

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by obarisk** [comment]
#41591 works as expected

tested with
`airflow.providers.slack.notifications.slack_webhook.send_slack_webhook_notification`
and
`airflow.providers.discord.notifications.discord.DiscordNotifier`

**Comment by amoghrajesh** [comment]
Tested my changes: https://github.com/apache/airflow/pull/41783, https://github.com/apache/airflow/pull/41680, https://github.com/apache/airflow/pull/41694 with breeze and all of them work as expected.

**Comment by amoghrajesh** [comment]
Also tested https://github.com/apache/airflow/pull/41890, for which I am the original contributor. I think we should cherry pick to retain the original author because the committer who cherry picks might not be fully aware of the scope of the change and shouldn't be responsible for testing it.

**Comment by potiuk** [comment]
> * Adding tojson filter to example_inlet_event_extra example dag (#41873) (#41890)

I think that needs some tooling improvement when generating the issue. The commit itself retains the original author:

<img width="680" alt="Screenshot 2024-09-03 at 06 39 03" src="https://github.com/user-attachments/assets/2047823c-d519-470d-814e-ee01ccc850e9">

But cherry-picked PR does not (and it cannot, because you cannot make another person author of your PR). So when we generate the issue, we should read commit information and simply add all 'comit authors` to the issue.

Created https://github.com/apache/airflow/issues/41969

**Comment by potiuk** [comment]
All good for my changes !

**Comment by potiuk** [comment]
One thing: @hadarsharon  -> can you please check if your https://github.com/apache/airflow/issues/41891  is solved in RC1 ?

**Comment by hadarsharon** [comment]
Yes @potiuk I just checked and can confirm that #41891 is resolved in [v2.10.1.rc1](https://pypi.python.org/pypi/apache-airflow/2.10.1.rc1)

Cheers

**Comment by vatsrahul1001** [comment]
Noticed [issue](https://github.com/apache/airflow/issues/41977) while using TriggerDagRunOperator

**Comment by jscheffl** [comment]
Can confirm the fixes/changes I contributed are in:

- Reporting of Scarf in buckets (#41898/#41898)
- Deprecation of warnings in Plugins Manager (#4173/#41793)
- Bump of Micromatch version (#41726/#41755)
- Universal Pathlib Fixes (Various PRs, is now 0.2.3)
- XCom UI Rendering Issues for INT, BOOL, FLOAT, NULL (#41516/#41605)

**Comment by Lee-W** [comment]
#41834 was not actually my work. but tested it and works fine

**Comment by tirkarthi** [comment]
Thanks @Lee-W for the backport, it's working fine as expected.

**Comment by jrderuiter** [comment]
Confirmed that #42032 is working fine in the rc.

**Comment by utkarsharma2** [comment]
Airflow 2.10.1 has been released. Thank you all for testing this release
