### ISSUE TITLE
AIP-84 Authentications and Permissions

### ISSUE THREAD

**Issue by pierrejeambrun** [apache/airflow#42360]
Meta issue for Authentications and Permissions for the API.

### Public API
- [x] assets @rawwar https://github.com/apache/airflow/pull/47136
- [x] asset aliases @rawwar https://github.com/apache/airflow/pull/47241
    - [x] associated assets @rawwar https://github.com/apache/airflow/issues/47561
- [x] backfills @vatsrahul1001 https://github.com/apache/airflow/pull/47482
- [x] config @jason810496 https://github.com/apache/airflow/pull/47208
- [x] connections  @rawwar https://github.com/apache/airflow/pull/47194
- [x] dag_parsing @rawwar https://github.com/apache/airflow/pull/47532
- [x] dag_report @Lee-W  
- [x] dag_run @rawwar https://github.com/apache/airflow/pull/47532
- [x] dag_sources @rawwar https://github.com/apache/airflow/pull/47532
- [x] dag_stats @rawwar https://github.com/apache/airflow/pull/47532
- [x] dag_tags @vatsrahul1001 https://github.com/apache/airflow/pull/47690
- [x] dag_versions @vatsrahul1001 https://github.com/apache/airflow/pull/47553
- [x] dag_warning @rawwar https://github.com/apache/airflow/pull/47532
- [x] dags @jason810496 ~~https://github.com/apache/airflow/pull/47062~~, https://github.com/apache/airflow/pull/47433
- [x] event_logs @jason810496 https://github.com/apache/airflow/pull/47246
- [x] extra_links @jason810496 https://github.com/apache/airflow/pull/47251
- [x] import_error @jason810496 https://github.com/apache/airflow/pull/47270
- [x] job @jason810496 https://github.com/apache/airflow/pull/47271
- [x] log @jason810496 https://github.com/apache/airflow/pull/47302
- [x] login (is already not an authenticated endpoint and need to remain like this)
- [x] monitor (is already not an authenticated endpoint and need to remain like this)
- [x] plugins @pierrejeambrun https://github.com/apache/airflow/pull/47504
- [x] pools @rawwar https://github.com/apache/airflow/pull/47192
- [x] providers @pierrejeambrun https://github.com/apache/airflow/pull/47505
- [x] task_instances @rawwar https://github.com/apache/airflow/pull/47532
- [x] tasks @vatsrahul1001  https://github.com/apache/airflow/pull/47684
- [x] variables @@jason810496 https://github.com/apache/airflow/pull/47211
- [x] version (is already not an authenticated endpoint and need to remain like this)
- [x] xcom @rawwar https://github.com/apache/airflow/pull/47532
- [x] @jason810496 https://github.com/apache/airflow/issues/47457 (backend change done)

### Private / UI API  (<=> views.py) @Lee-W
- [x] assets @Lee-W https://github.com/apache/airflow/pull/47485
- [x] backfills (depends on: backfills) @Lee-W https://github.com/apache/airflow/pull/47657
- [x] config @Lee-W https://github.com/apache/airflow/pull/47487
- [x] dags @Lee-W https://github.com/apache/airflow/pull/47623
- [x] dependencies @Lee-W https://github.com/apache/airflow/pull/47625
- [x] structure @Lee-W https://github.com/apache/airflow/pull/47631
- [x] dashboard @Lee-W  https://github.com/apache/airflow/pull/47650
- [x] grid @Lee-W https://github.com/apache/airflow/pull/47651

### ~~Execution API~~
- [ ] ~~assets @Lee-W https://github.com/apache/airflow/pull/47658~~
- [ ] ~~connections @Lee-W https://github.com/apache/airflow/pull/47661~~
- [x] health @Lee-W  (probably don't need it?)
- [ ] ~~task_instances @Lee-W https://github.com/apache/airflow/pull/47664~~
- [ ] ~~variables~~
- [ ] ~~xcoms~~

### misc
- https://github.com/apache/airflow/pull/47388

## II Additional Tasks
- [x] https://github.com/apache/airflow/issues/47055 @vincbeck
> Default to SimpleAuthManager for development time of airflow 3 as long as FABAuthManager does not support JWT auth, this is the only way we can progress on this while https://github.com/apache/airflow/issues/44849 is not completed

### Committer
- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by jason810496** [comment]
Hi @pierrejeambrun, could you please assign this ticket to me? Thanks!

**Comment by pierrejeambrun** [comment]
Hello @jason810496,

There has been some update on this one, it is not well scoped and depends on the work that Vincent is doing on the FABAuthManager and JWT backend. I do not recommend to take this one at this point. Removing the `good first issue tag`

**Comment by jason810496** [comment]
Gotcha, I will take other tickets. Thanks !

**Comment by pierrejeambrun** [comment]
Related PR https://github.com/apache/airflow/pull/42634

**Comment by pierrejeambrun** [comment]
cc: @vincbeck

**Comment by pierrejeambrun** [comment]
This is now unblocked since https://github.com/apache/airflow/issues/44884 has been implemented. We can start implementing the permissions for different endpoints.

**Comment by pierrejeambrun** [comment]
@jason810496 if you still have some interest for this let me know so I can assign you :)

**Comment by jason810496** [comment]
> @jason810496 if you still have some interest for this let me know so I can assign you :) 

Sure! I can work on this issue, I will look into the context tomorrow then ask if I not sure about the details.

**Comment by pierrejeambrun** [comment]
Great. Don't hesitate to do 1 PR per 'resource'. (for instance for DagRun endpoints, for taskinstance endpoints, connection enpoints etc...).

I think @rawwar will provide some help too so you can split the work easily. :)

**Comment by jason810496** [comment]
I will start with the Config endpoint first and provide an update here before working on the other endpoints. I’ll also list all the necessary endpoints later.  

Before proceeding further, I’d like to double-check something. After reviewing #44884, it seems that we might need a general middleware or a `Depends` function (in FastAPI) as an authentication layer to read the Bearer token from authorization request headers. This authentication layer should leverage the `AuthManager` initialized in the FastAPI app (accessible via `request.app.state.auth_manager`).

**Comment by jason810496** [comment]
> I’ll also list all the necessary endpoints later.

Endpoints:
- [ ] configuration
- [ ] connection
- [ ] dag
- [ ] asset
- [ ] pool
- [ ] variable
- [ ] view
- [ ] custom_view

**Comment by pierrejeambrun** [comment]
Thanks @jason810496 meta issue updated

**Comment by rawwar** [comment]
@jason810496 , I'll pick asset, pool and variable. I'll work on them this week.

**Comment by jason810496** [comment]
> [@jason810496](https://github.com/jason810496) , I'll pick asset, pool and variable. I'll work on them this week.

Then I'll take configuration and connection also, if I am fast enough I can take the rest also ! ( Not sure I have enough time currently )

**Comment by pierrejeambrun** [comment]
@Lee-W do you want to take the private `/ui` endpoints ?

**Comment by jason810496** [comment]
The previous endpoints were listed from `AuthManager`, but we should instead list them from the **Legacy API**, as some entities have not been implemented in `AuthManager`.


```bash
grep -rl "requires_access_" airflow/api_connexion/endpoints/ | sed -E 's|airflow/api_connexion/endpoints//||; s/_endpoint\.py$//; s|^|- [ ] |' | sort
```

### Public
- [ ] asset
- [ ] config
- [ ] connection
- [ ] dag
- [ ] dag_parsing.py
- [ ] dag_run
- [ ] dag_source
- [ ] dag_stats
- [ ] dag_warning
- [ ] event_log
- [ ] extra_link
- [ ] import_error
- [ ] log
- [ ] plugin
- [ ] pool
- [ ] provider
- [ ] task
- [ ] task_instance
- [ ] variable
- [ ] xcom
### UI
- [ ] view
- [ ] custom_view

**Comment by pierrejeambrun** [comment]
Can you instead list them on `api_fastapi` ? Some legacy endpoints were migrated to different resource. custom_view does not exist anymore, we potentially have the `execution_api` to secure behind auth, etc.

**Comment by jason810496** [comment]
> Can you instead list them on `api_fastapi` ? Some legacy endpoints were migrated to different resource. custom_view does not exist anymore, we potentially have the `execution_api` to secure behind auth, etc.

Just updated the above list:
- `airflow/api_fastapi/core_api/routes/public/` : 28 endpoints
- `airflow/api_fastapi/core_api/routes/ui/` : 8 endpoints
- `airflow/api_fastapi/execution_api/routes/` : 6 endpoints

total: 42 endpoints

I think some `requires_access_<entity>` might be reused for different endpoints across `public`, `ui` and `execution_api` routes.

**Comment by pierrejeambrun** [comment]
Thanks jason, the issue description has been updated accordingly.

**Comment by rawwar** [comment]
@pierrejeambrun , I'll pick these dag_parsing, dag_report, dag_run, dag_sources, dag_stats, dag_tags, dag_versions, dag_warning, task_instances, xcom

**Comment by jason810496** [comment]
I'll pick:
- [ ] event_logs
- [ ] extra_links
- [ ] import_error
- [ ] job
- [ ] log

**Comment by phanikumv** [comment]
@jason810496 @rawwar can you please mark which of the APIs are Done, which are WIP and which are yet to be picked up.

**Comment by jason810496** [comment]
> [@jason810496](https://github.com/jason810496) [@rawwar](https://github.com/rawwar) can you please update the description and indicate which of the APIs are Done, which are WIP and which are yet to be picked up.

Hi @phanikumv, I don't have permission to update the meta issue description, but I've added the PR links in my comment above. The links will reflect the current state of the PRs.

**Comment by Lee-W** [comment]
just updated the description with @jason810496 's help

**Comment by Lee-W** [comment]
I just updated the current status in the descpriont

**Comment by Lee-W** [comment]
@jason810496 @rawwar @vatsrahul1001 , are there any other known dependencies in public auths? It would be nice if we could list them so that we know what to do first 🙂 I'll take a look at the non-assigned ones later. as for the format, you can take a look at the UI part.

**Comment by rawwar** [comment]
> [@jason810496](https://github.com/jason810496) [@rawwar](https://github.com/rawwar) [@vatsrahul1001](https://github.com/vatsrahul1001) , are there any other known dependencies in public auths? It would be nice if we could list them so that we know what to do first 🙂 I'll take a look at the non-assigned ones later. as for the format, you can take a look at the UI part.

except asset_alias, my rest of the PR's depend on dags

**Comment by jason810496** [comment]
> [@jason810496](https://github.com/jason810496) [@rawwar](https://github.com/rawwar) [@vatsrahul1001](https://github.com/vatsrahul1001) , are there any other known dependencies in public auths? It would be nice if we could list them so that we know what to do first 🙂 I'll take a look at the non-assigned ones later. as for the format, you can take a look at the UI part.

Still working on fixing the Kubernetes tests. If not resolved today, I’ll continue over the weekend. I have a rough idea of how to fix it but need to test it locally.

**Comment by rawwar** [comment]
@pierrejeambrun, dag report is a new endpoint in AF3. What permissions should a user need to access it?

Should this be a separate permission or should it be a sub-entity of dags?

**Comment by vatsrahul1001** [comment]
@pierrejeambrun, I see that the dag_tags and tasks endpoints are unassigned. I can pick them up.

**Comment by Lee-W** [comment]
@vatsrahul1001 just assigned. Thanks!

**Comment by jason810496** [comment]
The DAG-related blocker https://github.com/apache/airflow/pull/47433 has just been resolved!  
Entities that depend on DAGs can now rebase to the latest `main` branch and leverage `ReadableDagsFilterDep` and `EditableDagsFilterDep` from the `airflow.api_fastapi.core_api.security` module to obtain the `get_permitted_dag_ids` filter.

**Comment by Lee-W** [comment]
@pierrejeambrun do we need auth for `execution/health`?

**Comment by rawwar** [comment]
> [@pierrejeambrun](https://github.com/pierrejeambrun) do we need auth for `execution/health`?

I don't think we should have auth for health endpoints, as monitoring tools can use them.

**Comment by Lee-W** [comment]
Yep, I don't think we should have auth either. as for whether to call it `/monitor`, I think `/health` is quite commonly used and probably shouldn't be changed?

**Comment by Lee-W** [comment]
for execution API, see https://github.com/apache/airflow/pull/47658#issuecomment-2717720206

**Comment by Lee-W** [comment]
only `dag_report, import_error` remains. I think we don't need to wait for https://github.com/apache/airflow/issues/47561.

**Comment by Lee-W** [comment]
almost there!

**Comment by Lee-W** [comment]
@prabhusneha will you be able to create the pr for dag report today? if not I can just work on it. Thanks!

**Comment by phanikumv** [comment]
> [@prabhusneha](https://github.com/prabhusneha) will you be able to create the pr for dag report today? if not I can just work on it. Thanks!

@Lee-W please work on the dag report as well, as @prabhusneha is on leave today

**Comment by rawwar** [comment]
> > [@prabhusneha](https://github.com/prabhusneha) will you be able to create the pr for dag report today? if not I can just work on it. Thanks!
> 
> @Lee-W please work on the dag report as well, as @prabhusneha is on leave today

I will raise a PR.

**Comment by Lee-W** [comment]
Hey @pierrejeambrun , with the help from @jason810496 and @rawwar , i just got https://github.com/apache/airflow/pull/47842 and https://github.com/apache/airflow/pull/47270#pullrequestreview-2690232834 ready to merge. I think these 2 are the last ones for this ticket

**Comment by Lee-W** [comment]
I'm planning on merging those two and closing the issue in an hour if no objection is received. Thanks!

**Comment by pierrejeambrun** [comment]
Thanks @Lee-W, I just approved and merged both, I think the issue is ready to be closed 🎉 🎉 

Thanks a lot to everyone for your contributions.

**Comment by Lee-W** [comment]
@pierrejeambrun Thanks so much for helping with the review, and thanks to all for helping out!

**Comment by bugraoz93** [comment]
Amazing effort/work! Kudos all! 👏 👏

**Comment by vincbeck** [comment]
Indeed! Amazing work!!
