### ISSUE TITLE
AIP-84 List DAGs endpoint new features (2/2) Advanced

### ISSUE THREAD

**Issue by pierrejeambrun** [apache/airflow#42467]
### Description
Related to: https://github.com/apache/airflow/issues/42370

Advanced:
- later on, we will want more advanced search features like any/all combinations of tags
- we will also want to search more by dag run: "show dags with a dag run within this date range", "show dags with a running dagrun", 
<img width="851" alt="Screenshot 2024-09-11 at 8 51 43 AM" src="https://github.com/user-attachments/assets/36138f06-929d-4ce4-b9f5-3bc4d1caa8e2">

We're looking to include the last X runs of a DAG, but that can be a separate endpoint to add later:
<img width="566" alt="Screenshot 2024-09-11 at 9 00 03 AM" src="https://github.com/user-attachments/assets/fd1ada28-e6b7-485a-88f7-dc015e76e8bd">

### Use case/motivation

Our current REST API dags list endpoint is not sufficient. It doesn't include any run history and sorting only works for a few fields
The legacy UI uses a custom FAB view which also needs to be replaced.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by prabhusneha** [comment]
I can work on this one

**Comment by pierrejeambrun** [comment]
Great @prabhusneha, assigned, thank you!

**Comment by prabhusneha** [comment]
PR: https://github.com/apache/airflow/pull/45420
