### ISSUE TITLE
Status of testing Providers that were prepared on September 27, 2024

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#42538]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [common.sql: 1.17.1rc1](https://pypi.org/project/apache-airflow-providers-common-sql/1.17.1rc1)
   - [x] [fix(providers/common/sql): add dummy connection setter for backward compatibility (#42490)](https://github.com/apache/airflow/pull/42490): @Lee-W
     Linked issues:
       - [x] [Linked Issue #42452](https://github.com/apache/airflow/issues/42452): @agreenburg
   - [ ] [Changed type hinting for handler function (#42275)](https://github.com/apache/airflow/pull/42275): @Ariel2400
## Provider [openlineage: 1.12.1rc1](https://pypi.org/project/apache-airflow-providers-openlineage/1.12.1rc1)
   - [x] [fix: OL dag start event not being emitted (#42448)](https://github.com/apache/airflow/pull/42448): @kacpermuda
     Linked issues:
       - [x] [Linked Issue #41690](https://github.com/apache/airflow/pull/41690): @mobuchowski
   - [x] [Fix typo in error stack trace formatting for clearer output (#42017)](https://github.com/apache/airflow/pull/42017): @aboitreaud

All users involved in the PRs:
@kacpermuda @Lee-W @Ariel2400 @aboitreaud

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by kacpermuda** [comment]
All OL changes are good, thanks for the quick response !

**Comment by Lee-W** [comment]
Tested #42490 . Works as expected. Thanks @eladkal !

**Comment by eladkal** [comment]
Thank you everyone. Providers are released.

I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
