### ISSUE TITLE
AIP-84 Migrate Dag Run related public endpoint to FastAPI 

### ISSUE THREAD

**Issue by rawwar** [apache/airflow#42701]
### Description

Migrate following endpoint 

- [x] List DAG runs - #43506
- [x] Trigger a new DAG run - #43875
- [x] List DAG runs(batch) - #44170
- [x] Get a DAG run - #42725 
- [x] Delete a DAG run - #42910
- [x] Modify a DAG run - #42973
- [x] Clear a DAG run - #42975
- [x] Get ~~dataset~~ asset events for a DAG run - ~~#43876~~ #43874
- [x] ~~Update the DAGRun note - #42974~~ 
- [x] update dag run note in PATCH dag_run endpoint - #43508

### Use case/motivation

[AIP-84](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-84+UI+REST+API)

### Related issues

Relates to: https://github.com/apache/airflow/issues/42370

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
Important to note. For triggering a dagrun, the api_connexion endpoint is missing a lot of the form fields that @jscheffl added to [views.py](https://github.com/apache/airflow/blob/main/airflow/www/views.py#L2005). I think if its best if we consolidate to a single public trigger dag run endpoint in FastAPI.

**Comment by jscheffl** [comment]
> Important to note. For triggering a dagrun, the api_connexion endpoint is missing a lot of the form fields that @jscheffl added to [views.py](https://github.com/apache/airflow/blob/main/airflow/www/views.py#L2005). I think if its best if we consolidate to a single public trigger dag run endpoint in FastAPI.

I was always looking at `/api/v1/ui/#/DAG/get_dag_details` (airflow/api_connexion/endpoints/dag_endpoint.py:get_dag_details()` which contains a dict of all params definitions. I _think_ this should contain all needed information to generate the form views.

Have not checked all default but looking at the fast API I feel like this is the same, have not checked for alle details of complete-ness. But this could be added-in there... I _think_ --> http://localhost:29091/docs#/DAG/get_dag_details (Try it with `example_params_ui_tutorial` and take a look to `params` in the response.

FYI @shubhamraj-git

**Comment by rawwar** [comment]
Thank you so much for your help @pierrejeambrun , @bugraoz93 , @omkar-foss . I learned a lot while contributing to this endpoint.

**Comment by pierrejeambrun** [comment]
Thanks @rawwar for you contributions :)
