### ISSUE TITLE
Status of testing Providers that were prepared on October 31, 2024

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#43545]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 9.1.0rc2](https://pypi.org/project/apache-airflow-providers-amazon/9.1.0rc2)
   - [ ] [feat: add OpenLineage support for RedshiftToS3Operator (#41632)](https://github.com/apache/airflow/pull/41632): @kacpermuda
     Linked issues:
       - [ ] [Linked Issue #41575](https://github.com/apache/airflow/pull/41575): @Artuz37
   - [ ] [Add SageMakerProcessingSensor (#43144)](https://github.com/apache/airflow/pull/43144): @vVv-AA
   - [ ] [Make `RedshiftDataOperator`  handle multiple queries (#42900)](https://github.com/apache/airflow/pull/42900): @jroachgolf84
   - [ ] [fix(providers/amazon): alias is_authorized_dataset to is_authorized_asset (#43470)](https://github.com/apache/airflow/pull/43470): @Lee-W
   - [ ] [Remove returns in final clause of athena hooks (#43426)](https://github.com/apache/airflow/pull/43426): @yangyulely
     Linked issues:
       - [ ] [Linked Issue #43274](https://github.com/apache/airflow/issues/43274): @iritkatriel
   - [ ] [Remove sqlalchemy-redshift dependency (#43271)](https://github.com/apache/airflow/pull/43271): @mobuchowski
   - [ ] [feat(providers/amazon): Use asset in common provider (#43110)](https://github.com/apache/airflow/pull/43110): @Lee-W
   - [ ] [Restrict looker-sdk version 24.18.0 and microsoft-kiota-http 1.3.4 (#42954)](https://github.com/apache/airflow/pull/42954): @gopidesupavan
   - [x] [Limit mypy-boto3-appflow (#43436)](https://github.com/apache/airflow/pull/43436): @eladkal
## Provider [fab: 1.5.0rc2](https://pypi.org/project/apache-airflow-providers-fab/1.5.0rc2)
   - [ ] [feat(providers/fab): Use asset in common provider (#43112)](https://github.com/apache/airflow/pull/43112): @Lee-W
   - [ ] [Fix revoke Dag stale permission on airflow < 2.10 (#42844)](https://github.com/apache/airflow/pull/42844): @joaopamaral
     Linked issues:
       - [ ] [Linked Issue #42743](https://github.com/apache/airflow/issues/42743): @RostD
   - [ ] [fix(providers/fab): alias is_authorized_dataset to is_authorized_asset (#43469)](https://github.com/apache/airflow/pull/43469): @Lee-W
   - [ ] [Bump Flask-AppBuilder to ``4.5.2`` (#43309)](https://github.com/apache/airflow/pull/43309): @kaxil
   - [ ] [Upgrade FAB to 4.5.1 (#43251)](https://github.com/apache/airflow/pull/43251): @potiuk
   - [ ] [Move user and roles schemas to fab provider (#42869)](https://github.com/apache/airflow/pull/42869): @vincbeck
   - [ ] [Move the session auth backend to FAB auth manager (#42878)](https://github.com/apache/airflow/pull/42878): @vincbeck
     Linked issues:
       - [ ] [Linked Issue #42634](https://github.com/apache/airflow/pull/42634): @vincbeck

All users involved in the PRs:
@yangyulely @kacpermuda @mobuchowski @kaxil @vVv-AA @Lee-W @jroachgolf84 @joaopamaral @vincbeck @gopidesupavan @potiuk @eladkal

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by eladkal** [comment]
Closing as vote is cancelled
