### ISSUE TITLE
Status of testing of Apache Airflow 2.10.3rc2

### ISSUE THREAD

**Issue by utkarsharma2** [apache/airflow#43585]
### Body

We are kindly requesting that contributors to [Apache Airflow RC 2.10.3rc2](https://pypi.org/project/apache-airflow/2.10.3rc2/) help test the RC.

Please let us know by commenting if the issue is addressed in the latest RC.

- [ ] [Bump dompurify from 2.2.9 to 2.5.6 in /airflow/www (#42263) (#42270)](https://github.com/apache/airflow/pull/42270): @pierrejeambrun
- [ ] [fix: Correct docstring format in _get_template_context (#42244) (#42272)](https://github.com/apache/airflow/pull/42272): @romsharon98
- [ ] [ Update StatsD Image Tag from failed dependencies check (#42264) (#42281)](https://github.com/apache/airflow/pull/42281): @jscheffl
     Linked issues:
     - [Update StatsD Image Tag from failed dependencies check (#42264)](https://github.com/apache/airflow/pull/42264)
- [ ] [Use `selectinload` in trigger (#42351)](https://github.com/apache/airflow/pull/42351): @vincbeck @josephangbc
     Linked issues:
     - [Use `selectinload` in trigger (#40487)](https://github.com/apache/airflow/pull/40487)
- [ ] [apply otel_service on metrics (#42242) (#42441)](https://github.com/apache/airflow/pull/42441): @romsharon98
- [ ] [ Bugfix task execution from runner in Windows (#42426) (#42478)](https://github.com/apache/airflow/pull/42478): @jscheffl
- [ ] [[BACKPORT] Fix the span link of task instance to point to the correct span in the scheduler_job_loop (#42430) (#42480)](https://github.com/apache/airflow/pull/42480): @howardyoo @shahar1
     Linked issues:
     - [Fix the span link of task instance to point to the correct span in the scheduler_job_loop (issue #42429) (#42430)](https://github.com/apache/airflow/pull/42430)
- [ ] [ Do not attempt to provide not stringified objects to UI via xcom if pickling is active (#42388) (#42486)](https://github.com/apache/airflow/pull/42486): @jscheffl
- [ ] [fix: ensure DAG trigger form submits with updated parameters upon key… (#42499)](https://github.com/apache/airflow/pull/42499): @pierrejeambrun
- [ ] [Handle ENTER key correctly in trigger form and allow manual JSON (#42… (#42535)](https://github.com/apache/airflow/pull/42535): @pierrejeambrun
- [ ] [Reduce eyestrain in dark mode with reduced contrast and saturation (#… (#42583)](https://github.com/apache/airflow/pull/42583): @pierrejeambrun
- [ ] [Support of host.name in OTEL metrics and usage of OTEL_RESOURCE_ATTRI… (#42604)](https://github.com/apache/airflow/pull/42604): @potiuk
- [ ] [Prevent redirect loop on /home with tags/lastrun filters (#42607) (#42609) (#42628)](https://github.com/apache/airflow/pull/42628): @jmaicher @jscheffl
     Linked issues:
     - [Prevent redirect loop on /home with tags/lastrun filters (#42607) (#42609)](https://github.com/apache/airflow/pull/42609)
- [ ] [Limit branches for pull request target workflow (#42635)](https://github.com/apache/airflow/pull/42635): @potiuk
- [ ] [[BACKPORT] Add retry logic in the scheduler for updating trigger timeouts in case of deadlocks. (#41429) (#42651)](https://github.com/apache/airflow/pull/42651): @shahar1 @TakawaAkirayo
     Linked issues:
     - [Add retry logic in the scheduler for updating trigger timeouts in case of deadlocks. (#41429)](https://github.com/apache/airflow/pull/41429)
- [ ] [Correctly select task in DAG Graph View when clicking on its name (#42697)](https://github.com/apache/airflow/pull/42697): @bbovenzi @jonhspyro
     Linked issues:
     - [Correctly select task in DAG Graph View when clicking on its name (#38782)](https://github.com/apache/airflow/pull/38782)
- [ ] [ fix(datasets/managers): fix error handling file loc when dataset alias resolved into new datasets (#42733)](https://github.com/apache/airflow/pull/42733): @uranusjr @Lee-W
     Linked issues:
     - [DAG priority parsing request is not inserted correctly on Postgres (#42704)](https://github.com/apache/airflow/issues/42704)
- [ ] [Fix dag warning documentation (#42858) (#42888)](https://github.com/apache/airflow/pull/42888): @pierrejeambrun
- [ ] [Deprecate session auth backend (backport) (#42911)](https://github.com/apache/airflow/pull/42911): @vincbeck
     Linked issues:
     - [Deprecate session auth backend (#42909)](https://github.com/apache/airflow/pull/42909)
- [ ] [Improving validation of task retries to handle None values (#42532) (#42915)](https://github.com/apache/airflow/pull/42915): @brightview4578 @jscheffl
     Linked issues:
     - [Improving validation of task retries to handle None values (#42532)](https://github.com/apache/airflow/pull/42532)
- [ ] [Remove the referrer from Webserver to Scarf (#42901) (#42942)](https://github.com/apache/airflow/pull/42942): @kaxil
- [ ] [Removed unicodecsv dependency for providers with Airflow version 2.8.… (#42970)](https://github.com/apache/airflow/pull/42970): @potiuk
- [ ] [Restrict looker-sdk version 24.18.0 and microsoft-kiota-http 1.3.4 (#… (#42977)](https://github.com/apache/airflow/pull/42977): @potiuk
- [ ] [Fix canary build test test_cli_internal_api_background process termination #42781 (#42983)](https://github.com/apache/airflow/pull/42983): @gopidesupavan
- [ ] [Fix PythonOperator when DAG has hyphen in name (#42993)](https://github.com/apache/airflow/pull/42993): @k-slash @jason810496
     Linked issues:
     - [PythonVirtualenvOperator - SyntaxError: cannot assign to operator (#42796)](https://github.com/apache/airflow/issues/42796)
- [ ] [Update json schema pre-commit to have draft7 schema in file (#43005) (#43007)](https://github.com/apache/airflow/pull/43007): @pierrejeambrun
- [ ] [Flush the session between writing and deletion of RTIF (#42928) (#43012)](https://github.com/apache/airflow/pull/43012): @ephraimbuddy
- [ ] [Disable flaky mssql based integration tests (#42811) (#43016)](https://github.com/apache/airflow/pull/43016): @gopidesupavan
- [ ] [Improve startup of K8S tests (#42721) (#43025)](https://github.com/apache/airflow/pull/43025): @gopidesupavan
- [ ] [update k8s tests urllib3 retry config status_forcelist and allowed_me… (#43026)](https://github.com/apache/airflow/pull/43026): @gopidesupavan
- [ ] [increase backoff_factor and add try/catch in k8s tests (#42940) (#43030)](https://github.com/apache/airflow/pull/43030): @gopidesupavan
- [ ] [Add retry on error 502 and 504 (#42994) (#43044)](https://github.com/apache/airflow/pull/43044): @majorosdonat @jscheffl
     Linked issues:
     - [Add retry on error 502 and 504 (#42994)](https://github.com/apache/airflow/pull/42994)
- [ ] [[Backport] Remove zombie from executor (#43065)](https://github.com/apache/airflow/pull/43065): @uranusjr
- [ ] [Added task_instance_mutation_hook for mapped operator index 0 (#42661) (#43089)](https://github.com/apache/airflow/pull/43089): @jscheffl @AutomationDev85
     Linked issues:
     - [Added task_instance_mutation_hook for mapped operator index 0 (#42661)](https://github.com/apache/airflow/pull/42661)
- [ ] [ AIP-69: Breeze adjustments for introduction of Edge Executor (#41731) (#43139)](https://github.com/apache/airflow/pull/43139): @jscheffl
     Linked issues:
     - [AIP-69: Breeze adjustments for introduction of Edge Executor (#41731)](https://github.com/apache/airflow/pull/41731)
- [ ] [[Backport] BashOperator: Execute templated bash script as file (#43191)](https://github.com/apache/airflow/pull/43191): @Joffreybvn
     Linked issues:
     - [BashOperator: Execute templated bash script as file (#42783)](https://github.com/apache/airflow/pull/42783)
- [ ] [Do not fail the build if only trove-classifiers change (#43236) (#43237)](https://github.com/apache/airflow/pull/43237): @potiuk
- [ ] [Mark sometimes failing heartbeat test and view test as flaky (#43250) (#43257)](https://github.com/apache/airflow/pull/43257): @potiuk
- [ ] [Skip example importability tests for providers in non-main branches (… (#43263)](https://github.com/apache/airflow/pull/43263): @potiuk
- [ ] [Better handling masking of values of set variable  (#43123) (#43278)](https://github.com/apache/airflow/pull/43278): @potiuk
- [ ] [Fix edge-case when conflicting constraints prevent k8s env creation (… (#43298)](https://github.com/apache/airflow/pull/43298): @potiuk
     Linked issues:
     - [Make Helm artifacts reproducible (#36930)](https://github.com/apache/airflow/pull/36930)
- [ ] [fix schedule_downstream_tasks bug (#42582) (#43299)](https://github.com/apache/airflow/pull/43299): @potiuk
- [ ] [Fixes behaviour of example dag tests for main/other branches (#43273) (#43307)](https://github.com/apache/airflow/pull/43307): @potiuk @ashb
     Linked issues:
     - [Split providers out of the main "airflow/" tree into a UV workspace project (#42505)](https://github.com/apache/airflow/pull/42505)
     - [Skip example importability tests for providers in non-main branches (#43260)](https://github.com/apache/airflow/pull/43260)
- [ ] [Check python version that was used to install pre-commit venvs (#43282) (#43310)](https://github.com/apache/airflow/pull/43310): @potiuk
- [ ] [Add isolation mode exclusion for mapped operator test (#43297) (#43311)](https://github.com/apache/airflow/pull/43311): @potiuk
- [ ] [Backport: Bump Flask-AppBuilder to ``4.5.2`` (#43309) (#43318)](https://github.com/apache/airflow/pull/43318): @kaxil
- [ ] [Masking configuration values irrelevant to DAG author (#43040) (#43336)](https://github.com/apache/airflow/pull/43336): @potiuk
- [ ] [Suppress warnings when masking sensitive confs (#43335) (#43337)](https://github.com/apache/airflow/pull/43337): @potiuk
- [ ] [Backport: Remove Scarf analytics from Airflow Webserver (#43346) (#43348)](https://github.com/apache/airflow/pull/43348): @kaxil
- [ ] [ Resolve warning in Dataset Alias migration (#43425)](https://github.com/apache/airflow/pull/43425): @Lee-W @kaxil
     Linked issues:
     - [Resolve warning in Dataset Alias migration (#43421)](https://github.com/apache/airflow/pull/43421)
- [ ] [Ensure total_entries in /api/v1/dags (#43377) (#43429)](https://github.com/apache/airflow/pull/43429): @pierrejeambrun
- [ ] [include limit and offset in request body schema for List task instances (batch) endpoint (#43479)](https://github.com/apache/airflow/pull/43479): @rawwar
- [ ] [Fix broken stat scheduler_loop_duration (#42886) (#43544)](https://github.com/apache/airflow/pull/43544): @potiuk
- [ ] [Fix TrySelector for Mapped Tasks in Logs and Details Grid Panel (#43565) Backport (#43566)](https://github.com/apache/airflow/pull/43566): @jscheffl
- [ ] [Conditionally add OTEL events when processing executor events (#43558) (#43567)](https://github.com/apache/airflow/pull/43567): @jedcunningham
     Linked issues:
     - [Conditionally add OTEL events when processing executor events (#43558)](https://github.com/apache/airflow/pull/43558)
- [ ] [Mark all tasks as skipped when failing a dag_run manually including t… (#43572)](https://github.com/apache/airflow/pull/43572): @utkarsharma2
- [ ] [ FIX: Don't raise a warning in ExecutorSafeguard when execute is called from an extended operator (#42849) Backport (#43577)](https://github.com/apache/airflow/pull/43577): @dabla @jscheffl
     Linked issues:
     - [FIX: Don't raise a warning in ExecutorSafeguard when execute is called from an extended operator (#42849)](https://github.com/apache/airflow/pull/42849)

Thanks to all who contributed to the release (probably not a complete list!):
@uranusjr @howardyoo @majorosdonat @ashb @rawwar @jonhspyro @kaxil @potiuk @pierrejeambrun @Lee-W @bbovenzi @ephraimbuddy @AutomationDev85 @vincbeck @jscheffl @k-slash @jason810496 @shahar1 @jedcunningham @romsharon98 @dabla @jmaicher @gopidesupavan @utkarsharma2 @TakawaAkirayo @josephangbc @brightview4578 @Joffreybvn

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by utkarsharma2** [comment]
Updated the [old issue](https://github.com/apache/airflow/issues/43441) to retain the already-tested PR and comments.
