### ISSUE TITLE
Status of testing Providers that were prepared on November 03, 2024

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#43615]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 9.1.0rc3](https://pypi.org/project/apache-airflow-providers-amazon/9.1.0rc3)
   - [ ] [feat: add OpenLineage support for RedshiftToS3Operator (#41632)](https://github.com/apache/airflow/pull/41632): @kacpermuda
     Linked issues:
       - [ ] [Linked Issue #41575](https://github.com/apache/airflow/pull/41575): @Artuz37
   - [ ] [Add SageMakerProcessingSensor (#43144)](https://github.com/apache/airflow/pull/43144): @vVv-AA
   - [ ] [Make `RedshiftDataOperator`  handle multiple queries (#42900)](https://github.com/apache/airflow/pull/42900): @jroachgolf84
   - [x] [fix(providers/amazon): alias is_authorized_dataset to is_authorized_asset (#43470)](https://github.com/apache/airflow/pull/43470): @Lee-W
   - [ ] [Remove returns in final clause of athena hooks (#43426)](https://github.com/apache/airflow/pull/43426): @yangyulely
     Linked issues:
       - [ ] [Linked Issue #43274](https://github.com/apache/airflow/issues/43274): @iritkatriel
   - [x] [Remove sqlalchemy-redshift dependency (#43271)](https://github.com/apache/airflow/pull/43271): @mobuchowski
   - [x] [feat(providers/amazon): Use asset in common provider (#43110)](https://github.com/apache/airflow/pull/43110): @Lee-W
   - [ ] [Restrict looker-sdk version 24.18.0 and microsoft-kiota-http 1.3.4 (#42954)](https://github.com/apache/airflow/pull/42954): @gopidesupavan
   - [x] [Limit mypy-boto3-appflow (#43436)](https://github.com/apache/airflow/pull/43436): @eladkal
   - [ ] [Standard provider python operator (#42081)](https://github.com/apache/airflow/pull/42081): @gopidesupavan
## Provider [fab: 1.5.0rc3](https://pypi.org/project/apache-airflow-providers-fab/1.5.0rc3)
   - [x] [feat(providers/fab): Use asset in common provider (#43112)](https://github.com/apache/airflow/pull/43112): @Lee-W
   - [x] [Fix revoke Dag stale permission on airflow < 2.10 (#42844)](https://github.com/apache/airflow/pull/42844): @joaopamaral
     Linked issues:
       - [x] [Linked Issue #42743](https://github.com/apache/airflow/issues/42743): @RostD
   - [x] [fix(providers/fab): alias is_authorized_dataset to is_authorized_asset (#43469)](https://github.com/apache/airflow/pull/43469): @Lee-W
   - [ ] [Docs: Change CustomSecurityManager method name (#43034)](https://github.com/apache/airflow/pull/43034): @kgw7401
   - [ ] [Bump Flask-AppBuilder to ``4.5.2`` (#43309)](https://github.com/apache/airflow/pull/43309): @kaxil
   - [ ] [Upgrade FAB to 4.5.1 (#43251)](https://github.com/apache/airflow/pull/43251): @potiuk
   - [ ] [Move user and roles schemas to fab provider (#42869)](https://github.com/apache/airflow/pull/42869): @vincbeck
   - [ ] [Move the session auth backend to FAB auth manager (#42878)](https://github.com/apache/airflow/pull/42878): @vincbeck
     Linked issues:
       - [ ] [Linked Issue #42634](https://github.com/apache/airflow/pull/42634): @vincbeck
   - [ ] [Add logging to the migration commands (#43516)](https://github.com/apache/airflow/pull/43516): @ephraimbuddy
   - [x] [Rename dataset as asset in UI (#43073)](https://github.com/apache/airflow/pull/43073): @Lee-W

All users involved in the PRs:
@mobuchowski @kgw7401 @kacpermuda @kaxil @Lee-W @eladkal @yangyulely @vincbeck @potiuk @vVv-AA @joaopamaral @gopidesupavan @jroachgolf84 @ephraimbuddy

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by gopidesupavan** [comment]
Oh @eladkal common compat is required for aws provider, it has changes to appflow which references to standard provider.

https://github.com/apache/airflow/pull/42081/files#diff-8721ac5046348753733a590d30f9d7fead6ae61bf4f2e05a3167bdcde2cafc18R28

**Comment by gopidesupavan** [comment]
Last release was oct 14th for compat provider, so along with aws provider now common compat also required i believe WDYT?

**Comment by potiuk** [comment]
> Last release was oct 14th for compat provider, so along with aws provider now common compat also required i believe WDYT?

Agreed. Good call. And we might (in the next version of AWS provider) already start using "standard" provider as dependnecy as long as we release it and it works for 2.8 an 2.9 (https://github.com/apache/airflow/pull/43556)

**Comment by Lee-W** [comment]
Verify https://github.com/apache/airflow/pull/43469, https://github.com/apache/airflow/pull/43112, https://github.com/apache/airflow/pull/43470 and https://github.com/apache/airflow/pull/43110

**Comment by joaopamaral** [comment]
Tested https://github.com/apache/airflow/pull/42844 with success.

**Comment by eladkal** [comment]
Thank you everyone. Providers are released.
Amazon provider is excluded and will have rc4

I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
