### ISSUE TITLE
Move core operators/sensors/triggers to standard provider

### ISSUE THREAD

**Issue by gopidesupavan** [apache/airflow#43641]
### Body

Move all the core area operators to standard provider.

- [x] Move Data time operators/sensors to standard provider #41564
- [x] Move Hooks to standard provider #42794 
- [x] Move bash operator to standard provider #42252 
- [x] Move python operator to standard provider #42081
- [x] Move triggers to standard provider  https://github.com/apache/airflow/pull/43608
- [ ] Move decorators to standard provider #44027
- [X] Move external external task sensor to standard provider https://github.com/apache/airflow/pull/44288
- [X] Move filesystem sensor to standard provider https://github.com/apache/airflow/pull/43890
- [x] #48936
- [x] Move latest only operator to standard provider https://github.com/apache/airflow/pull/44309
- [X] Move trigger dag run operator to standard provider https://github.com/apache/airflow/pull/44053

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
Nice!

**Comment by gopidesupavan** [comment]
cc: @romsharon98

**Comment by kunaljubce** [comment]
@gopidesupavan Can we link #43890 to `Move filesystem sensor to standard provider` in the description above? I'll take up one of the other open items from the remaining.

**Comment by hardeybisey** [comment]
@gopidesupavan can we also link #44053 for Move TriggerDagRunOperator.

**Comment by jason810496** [comment]
Hi @gopidesupavan, I can take `Move external external task sensor to standard provider`, thanks !

( I will provide to PR to link to this meta issue later )

**Comment by kunaljubce** [comment]
@jason810496 I am already working on that and the PR is up, pending some fixes. Please pick up some other open issues, thanks :)

**Comment by kunaljubce** [comment]
@gopidesupavan Can you please review #44288 and link it to `Move external external task sensor to standard provider`?

This would leave only `Move core operator docs to standard provider documentation`. Do we start working on this now since I see that #44027 is still a WIP?

**Comment by gopidesupavan** [comment]
> @gopidesupavan Now that #44288 is merged, maybe you can link it to `Move external external task sensor to standard provider`?
> 
> This would leave only `Move core operator docs to standard provider documentation`. Do we start working on this now since I see that #44027 is still a WIP?

Yes, it needs some verification from core area to standard provider, moving if there are any missing documentation.

**Comment by hardeybisey** [comment]
@gopidesupavan We can now link #44309 for `Move LatestOnlyOperator` to standard provider. Thanks.

**Comment by potiuk** [comment]
Linked
