### ISSUE TITLE
AIP-38 | Migrate to new UI

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#43712]
Meta epic to track all legacy UI pages we need to migrate over to the new UI

See here for designs: https://github.com/apache/airflow/issues/42371

## Feature complete with Legacy UI
 General
- Dags List
    - [x] Dag Card to show last and next runs and a chart of recent runs
    - [x] Pause/unpause Dag
    - [x] Trigger dag run #44857
    - [x] Filter dags by last dag run state, paused, and tags
    - [x] Sort dag list by display name, latest run, next run,
    - [x] Search for a dag by dag_id or dag_display_name
    - [x] Dag import errors
- Dag Details
    - [x] Click on a row in the Dags list to open up Dag Details
    - [x] Show header that has the same information as the Dag Card and includes actions to:
        - [x] Trigger basic Dag #44857
        - [x] Use dag params to generate forms for triggering a dag #44858
    - [x] List all dag runs and link to a specific Dag Run
    - [x] Dag Code
    - [x] Audit Log events filtered by DagId
    - [x] Reparse Dag
    - [ ] Delete Dag
    - [x] Dag Run duration bar chart
    - [ ] Show Asset conditions and which events have been met for next triggered run
    - [ ] Details tab to list all details not in the header card
- [ ] Dag Visualizations
    - [x] Graph
        - [x] Show the nodes and edges of a graph
        - [ ] Filter by upstream/downstream of a task id 
        - [x] Toggle Dag Dependencies (sensors, triggers, data assets with conditions)
        - [x] Show a specific dag run in the graph with each node filled with task instance or asset event info
        - [x] Click on a task to select it as a task or task instance
    - [x] Grid
        - [ ] Filter by run type, or state
        - [ ] Explore use of icons for each state to be more accessible. And how to balance that with run_type, try_number and has a note functionality
    - [ ] Gantt chart
    - [x] Dropdown selector on each viz to change between dag runs
    - [x] Side drawer on the full page modal to show a condensed Task Instance details view with all TI actions
    - [ ] Calendar view (do we keep it?)
- [x] Auto refresh #46129
- [x] Task Details
    - [x] List task instances
    - [x] Task instance duration chart
    - [x] Audit Log events filtered by TaskId
- [x] Dag Run Details
    - [x] List task instances
    - [x] Manually mark dag run as failed or success
    - [x] Clear a dag run
    - [x] Audit Log events filtered by dag run id
- [ ] Task Instance Details
    - [x] Manually mark a task failed or success
    - [x] Clear a task instance #44860
    - [x] See task instance logs across tries #44663
    - [x] See task instance details across tries
    - [x] Audit Log events filtered by TI
    - [x] Mapped Task Summary page with list of all mapped instances #45990
    - [x] Allow selecting a single mapped instance with all task instance functionality
    - [x] Xcoms #44667
    - [x] Rendered templates  
    - [ ] Logs
        - [x] Filter & parse by level
        - [ ] Filter & parse by source
        - [ ] Auto scroll to bottom of logs
- Dag Runs list
	- [x] List runs across all dags
	- [ ] Search, filter and sort
	- [x] Clear and mark state
- Task Instances list
	- [x] List task instances across all dags
	- [ ] Search, filter and sort
	- [x] Clear and mark state
- Dashboard (formerly known as Cluster Activity)
    - [x] Import Errors https://github.com/apache/airflow/issues/43711 
    - [ ] Pool Summary #43328
    - [x] Show historic metrics for dag run and task instances states
    - [x] Component health badges with heartbeat timestamps
 - Assets (formerly known as Datasets)
   - [x] List assets
   - [ ] List all asset events
   - [x] Manually create asset event
   - [x] Asset Details
     - [x] Show dependency graph of assets
     - [x] List events
 - User Profile
	 - [x] Toggle dark/light mode
	 - [x] Change default timezone
- Docs
	- [x] Link to API, docs, and github
- Admin
  - [x] List Plugins
  - Connections
    - [x] List Connections  #43703 
    - [x] Edit Connection
    - [ ] Delete Connection
    - [ ] Test Connection
   - [ ] Show config
   - [x] List Providers
  - Variables 
    - [x] List Variables #43709
    - [x] Import variables
    - [x] Add Variable
    - [x] Edit Variable
    - [x] Delete Variable
  - Pools
    - [x] List all pools
    - [ ] Edit Pool
    - [ ] Delete Pool
    - [ ] Create Pool 
  - Browse
   - Events
     - [x] List all Audit Log Events
     - [x] Sort list
     - [ ] Filter list
     - [ ] Search list
  - XComs
    - [x] List all xcoms
- Plugins
  - [ ] Show legacy plugins in an iFrame
- Authentication & Permissions
  - [ ] Show user management and security in a plugin or natively
  - [ ] Show or hide UI elements based on user permissions
 - UI Customizations
  - [ ] [#46874](https://github.com/apache/airflow/issues/46874)

## New Features
 - General
   - [x] Improve color blind accessibility by not relying just on colors for state #43054
  - Dashboard
    - [ ] Scope out other helpful summaries
 - Dags List
	 - [ ] Advanced search 
 - Dag Details
    -  Overview
       -  [x] Quick stats on recent failed runs and task instances
       - [ ] Total dag run summary chart
       - [ ] Dag run success rate chart
       - [ ] Add graph minimap quick link
       - [ ] Links to most recent failed task logs
       - [ ] Figure out if we can do failed task log previews
       - [ ] Scope out other helpful summaries
     - [x] List all tasks
        - [ ] Nest list rows based on task groups that expand and collapse like the grid view
    - Task Details
        - [ ] Quick stats on failed and retried task instances
	    - [ ] Total task instance summary chart
	    - [ ] TI success rate chart
	    - [ ] Scope out other helpful summaries
- Assets
  - [ ] Show summaries of asset events with their upstream/downstreams
  - Dependency graph
    - [x] Select an asset event and see all other related events on the graph
  - [ ] Auto refresh Asset pages
  - [ ] Show Asset Queue
  - [x] Materialize asset event
- Backfills
    - [x] Create backfill for a dag with a dry run 
    - [ ] Active backfills banner #43968
    - [x] List backfills #43967
    - [ ] Pause/cancel backfill
- Versioning
    - [x] Show version on dag/dagrun/task/task instance
    - [x] When viewing an older dag run, fetch the dag code for that version 
    - [ ] Fetch the dag structure for an older version or give an alert that the structure has changed 
- Plugins
  - [ ] React-based to replace menu items
  - [ ] React-based for specific sub views (inside dashboard, dag overview, etc)
  - [ ] Dev Tools to aid plugin development
     - [ ] Give an iframe template
     - [ ] CLI to generate boilerplate plugin

**Comment by hterik** [comment]
> Filter by tags https://github.com/apache/airflow/pull/43715

This appears to link to something else.

**Comment by bbovenzi** [comment]
> > Filter by tags #43715
> 
> This appears to link to something else.

Good catch. Fixed.

**Comment by bbovenzi** [comment]
I'll probably update the main issue description. But here's the priority for the month:

## December user stories

- Dags List
    - [x] Dag Card to show last and next runs and a chart of recent runs
    - [x] Can pause/unpause a Dag from the list
    - [x] Filter dags by last dag run state, paused, and tags
    - [x] Sort dag list by display name, latest run, next run,
    - [x] Search for a dag by dag_id or dag_display_name
- Dashboard
    - [x] See an alert for Dag Import Errors
    - [x] Quick links to filter dags list by last run state
    - [x] See health status of Airflow components (scheduler, triggerrer etc)
    - [x] See basic info on the states dag runs and task instances that have happened over a given length of time
- [ ] Dag Details
    - [x] Click on a row in the Dags list to open up Dag Details
    - [x] Show header that has the same information as the Dag Card and includes actions to:
        - [ ] Trigger Dag
        - [x] Reparse Dag
        - [ ] Delete Dag
    - [x] List all dag runs and link to a specific Dag Run
    - [x] List all tasks
        - [ ] Include task group information
    - [x] Render Dag Code
    - [x] Show Audit Log Events related to the Dag
- [ ] Dag Visualizations
    - [x] Graph
        - [x] Show the nodes and edges of a graph
        - [ ] Toggle showing the external dependencies of a graph (sensors, triggers, data assets with conditions)
        - [ ] Show a specific dag run in the graph with each node filled with task instance or asset event info
        - [ ] Click on a task to select it as a task or task instance
    - [ ] Grid
        - [ ] Explore use of icons for each state to be more accessible. And how to balance that with run_type, try_number and has a note functionality
    - [ ] Gantt
    - [ ] Dropdown selector on each viz to change between dag runs
    - [ ] Side drawer on each viz to see details about a task instance or dag run and the ability to quickly clear or mark as a failure
    - [ ] Auto refresh grid data to see dags running
    - [ ] Filter visualizations based on upstream/downstream of a task or dag run type or dag run state
    - [ ] Have a state legend where clicking on a state can highlight all task instances with that state
- [ ] Task Details
    - [ ] List all task instances
    - [ ] Show all audit log events related to that task id
- [x] Dag Run Details
    - [x] List all task instances
    - [ ] Change dag run note
    - [ ] Manually mark dag run as failed or success
    - [ ] Clear a dag run
    - [ ] Show all audit log events related to that dag run id
- [ ] Task Instance Details
    - [ ] Manually mark a task failed or success
    - [ ] Change the task instance note
    - [ ] Clear a task instance
    - [ ] See task instance logs across tries
    - [ ] See task instance details across tries
    - [ ] List all mapped task instances
        - [ ] Allow selecting a single mapped instance with all task instance functionality
    - [ ] See task instance xcoms
    - [ ] Show all audit log events related to that task instance

**Comment by pierrejeambrun** [comment]
I feel like we have everything from the backend perspective. (or planned such as asset dependencies).

The only points I'm not so sure are:
- Include task group information (I'm not sure we have this)
- Show dag import errors on dag list level (I am not sure how we want to display them, as in the legacy we can put them at the top of the dag list, but I don't think we can group them by `dag_id` there's not really a relation there in the db model)

**Comment by bbovenzi** [comment]
> I feel like we have everything from the backend perspective. (or planned such as asset dependencies).
> 
> The only points I'm not so sure are:
> 
> * Include task group information (I'm not sure we have this)
> * Show dag import errors on dag list level (I am not sure how we want to display them, as in the legacy we can put them at the top of the dag list, but I don't think we can group them by `dag_id` there's not really a relation there in the db model)

- I think almost all Task Group information is handled by grid_data and structure endpoints 
- We literally just need to copy the component from the home page and also show it at the top of the page on the dags list

**Comment by pierrejeambrun** [comment]
I'll work on the `mark as....` (failed/success) etc. For dagruns and tasks.

**Comment by aryavj1** [comment]
@bbovenzi Not sure if this is already planned, but could we add a **conf** column to the DAGs run UI page like in Airflow 2?

**Comment by bbovenzi** [comment]
Airflow 3 it out. Closing this meta issue, anything else should be its own feature request.

**Comment by aryavj1** [comment]
@bbovenzi I have opened an issue here https://github.com/apache/airflow/issues/50912
