### ISSUE TITLE
Status of testing Providers that were prepared on November 14, 2024

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#44041]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [amazon: 9.1.0rc4](https://pypi.org/project/apache-airflow-providers-amazon/9.1.0rc4)
   - [ ] [feat: add OpenLineage support for RedshiftToS3Operator (#41632)](https://github.com/apache/airflow/pull/41632): @kacpermuda
     Linked issues:
       - [ ] [Linked Issue #41575](https://github.com/apache/airflow/pull/41575): @Artuz37
   - [ ] [Add SageMakerProcessingSensor (#43144)](https://github.com/apache/airflow/pull/43144): @vVv-AA
   - [ ] [Make `RedshiftDataOperator`  handle multiple queries (#42900)](https://github.com/apache/airflow/pull/42900): @jroachgolf84
   - [ ] [fix(providers/amazon): alias is_authorized_dataset to is_authorized_asset (#43470)](https://github.com/apache/airflow/pull/43470): @Lee-W
   - [ ] [Remove returns in final clause of athena hooks (#43426)](https://github.com/apache/airflow/pull/43426): @yangyulely
     Linked issues:
       - [ ] [Linked Issue #43274](https://github.com/apache/airflow/issues/43274): @iritkatriel
   - [ ] [fix: replace \s with space (#43849)](https://github.com/apache/airflow/pull/43849): @LyndonFan
     Linked issues:
       - [ ] [Linked Issue #38864](https://github.com/apache/airflow/pull/38864): @vincbeck
       - [ ] [Linked Issue #39252](https://github.com/apache/airflow/issues/39252): @Taragolis
       - [ ] [Linked Issue #39428](https://github.com/apache/airflow/pull/39428): @romsharon98
       - [ ] [Linked Issue #38734](https://github.com/apache/airflow/pull/38734): @dabla
   - [x] [Fix `HttpToS3Operator` throws exception if s3_bucket parameter is not passed (#43828)](https://github.com/apache/airflow/pull/43828): @kunaljubce
     Linked issues:
       - [x] [Linked Issue #43379](https://github.com/apache/airflow/issues/43379): @kostiantyn-lab
   - [ ] [Fix awslogs_stream_prefix pattern (#43138)](https://github.com/apache/airflow/pull/43138): @pyrr
     Linked issues:
       - [ ] [Linked Issue #43130](https://github.com/apache/airflow/issues/43130): @pyrr
   - [ ] [Check if awslogs_stream_prefix already ends with container_name (#43724)](https://github.com/apache/airflow/pull/43724): @pyrr
     Linked issues:
       - [ ] [Linked Issue #43138](https://github.com/apache/airflow/pull/43138): @pyrr
   - [ ] [bugfix description should be optional for openlineage integration with `AthenaOperator` (#43576)](https://github.com/apache/airflow/pull/43576): @Udbv
   - [ ] [Decouple volume_configurations from capacity_provider_strategy (#43047)](https://github.com/apache/airflow/pull/43047): @pyrr
     Linked issues:
       - [ ] [Linked Issue #43046](https://github.com/apache/airflow/issues/43046): @pyrr
   - [x] [GlueJobOperator: add option to wait for cleanup before returning job status (#43688)](https://github.com/apache/airflow/pull/43688): @eladkal
   - [x] [Resolve GlueJobTrigger serialization bug causing verbose to always be True (#43622)](https://github.com/apache/airflow/pull/43622): @jimwbaldwin
   - [ ] [Remove returns in final clause of S3ToDynamoDBOperator (#43456)](https://github.com/apache/airflow/pull/43456): @yangyulely
     Linked issues:
       - [ ] [Linked Issue #43274](https://github.com/apache/airflow/issues/43274): @iritkatriel
   - [ ] [Remove sqlalchemy-redshift dependency (#43271)](https://github.com/apache/airflow/pull/43271): @mobuchowski
   - [ ] [feat(providers/amazon): Use asset in common provider (#43110)](https://github.com/apache/airflow/pull/43110): @Lee-W
   - [x] [Restrict looker-sdk version 24.18.0 and microsoft-kiota-http 1.3.4 (#42954)](https://github.com/apache/airflow/pull/42954): @gopidesupavan
   - [x] [Limit mypy-boto3-appflow (#43436)](https://github.com/apache/airflow/pull/43436): @eladkal
   - [x] [Standard provider python operator (#42081)](https://github.com/apache/airflow/pull/42081): @gopidesupavan
   - [ ] [Add support for semicolon stripping to DbApiHook, PrestoHook, and TrinoHook (#41916)](https://github.com/apache/airflow/pull/41916): @Illumaria
     Linked issues:
       - [ ] [Linked Issue #34828](https://github.com/apache/airflow/issues/34828): @MikeWallis42
   - [ ] [remove all deprecations cncf.kubernetes (#43689)](https://github.com/apache/airflow/pull/43689): @romsharon98
   - [x] [Fix docstring for AthenaTrigger (#43616)](https://github.com/apache/airflow/pull/43616): @eladkal
## Provider [apache.beam: 5.9.1rc1](https://pypi.org/project/apache-airflow-providers-apache-beam/5.9.1rc1)
   - [x] [Standard provider python operator (#42081)](https://github.com/apache/airflow/pull/42081): @gopidesupavan
## Provider [apache.drill: 2.8.1rc1](https://pypi.org/project/apache-airflow-providers-apache-drill/2.8.1rc1)
   - [ ] [Add support for semicolon stripping to DbApiHook, PrestoHook, and TrinoHook (#41916)](https://github.com/apache/airflow/pull/41916): @Illumaria
     Linked issues:
       - [ ] [Linked Issue #34828](https://github.com/apache/airflow/issues/34828): @MikeWallis42
## Provider [apache.druid: 3.12.1rc1](https://pypi.org/project/apache-airflow-providers-apache-druid/3.12.1rc1)
   - [ ] [Add support for semicolon stripping to DbApiHook, PrestoHook, and TrinoHook (#41916)](https://github.com/apache/airflow/pull/41916): @Illumaria
     Linked issues:
       - [ ] [Linked Issue #34828](https://github.com/apache/airflow/issues/34828): @MikeWallis42
## Provider [apache.hive: 8.2.1rc1](https://pypi.org/project/apache-airflow-providers-apache-hive/8.2.1rc1)
   - [ ] [Add support for semicolon stripping to DbApiHook, PrestoHook, and TrinoHook (#41916)](https://github.com/apache/airflow/pull/41916): @Illumaria
     Linked issues:
       - [ ] [Linked Issue #34828](https://github.com/apache/airflow/issues/34828): @MikeWallis42
   - [x] [Explain how to use uv with airflow virtualenv and make it works (#43604)](https://github.com/apache/airflow/pull/43604): @potiuk
     Linked issues:
       - [x] [Linked Issue #43200](https://github.com/apache/airflow/issues/43200): @potiuk
   - [ ] [Move `uncompress_file` function from `airflow.utils` to Hive provider (#43526)](https://github.com/apache/airflow/pull/43526): @kaxil
## Provider [apache.impala: 1.5.2rc1](https://pypi.org/project/apache-airflow-providers-apache-impala/1.5.2rc1)
   - [ ] [Add support for semicolon stripping to DbApiHook, PrestoHook, and TrinoHook (#41916)](https://github.com/apache/airflow/pull/41916): @Illumaria
     Linked issues:
       - [ ] [Linked Issue #34828](https://github.com/apache/airflow/issues/34828): @MikeWallis42
## Provider [apache.pinot: 4.5.1rc1](https://pypi.org/project/apache-airflow-providers-apache-pinot/4.5.1rc1)
   - [ ] [Add support for semicolon stripping to DbApiHook, PrestoHook, and TrinoHook (#41916)](https://github.com/apache/airflow/pull/41916): @Illumaria
     Linked issues:
       - [ ] [Linked Issue #34828](https://github.com/apache/airflow/issues/34828): @MikeWallis42
## Provider [apache.spark: 4.11.3rc1](https://pypi.org/project/apache-airflow-providers-apache-spark/4.11.3rc1)
   - [x] [Standard provider python operator (#42081)](https://github.com/apache/airflow/pull/42081): @gopidesupavan
## Provider [apprise: 1.4.1rc1](https://pypi.org/project/apache-airflow-providers-apprise/1.4.1rc1)
   - [x] [Standard provider bash operator (#42252)](https://github.com/apache/airflow/pull/42252): @gopidesupavan
   - [ ] [Unify DAG schedule args and change default to None (#41453)](https://github.com/apache/airflow/pull/41453): @uranusjr
## Provider [atlassian.jira: 2.7.1rc1](https://pypi.org/project/apache-airflow-providers-atlassian-jira/2.7.1rc1)
   - [x] [Standard provider bash operator (#42252)](https://github.com/apache/airflow/pull/42252): @gopidesupavan
## Provider [celery: 3.8.4rc1](https://pypi.org/project/apache-airflow-providers-celery/3.8.4rc1)
   - [ ] [AIP-72: Remove DAG pickling (#43667)](https://github.com/apache/airflow/pull/43667): @kaxil
   - [x] [Standard provider python operator (#42081)](https://github.com/apache/airflow/pull/42081): @gopidesupavan
## Provider [cloudant: 4.0.3rc1](https://pypi.org/project/apache-airflow-providers-cloudant/4.0.3rc1)
   - [ ] [Bump `uv` to `0.4.28` (#43451)](https://github.com/apache/airflow/pull/43451): @kaxil
## Provider [cncf.kubernetes: 10.0.0rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/10.0.0rc1)
   - [ ] [remove all deprecations cncf.kubernetes (#43689)](https://github.com/apache/airflow/pull/43689): @romsharon98
   - [ ] [Change default value of `namespace` in `task.kubernetes` to be None (#43402)](https://github.com/apache/airflow/pull/43402): @romsharon98
   - [ ] [Add random_name_suffix to SparkKubernetesOperator (#43800) (#43847)](https://github.com/apache/airflow/pull/43847): @mrk-andreev
     Linked issues:
       - [ ] [Linked Issue #43800](https://github.com/apache/airflow/issues/43800): @Flametaa
   - [ ] [terminate kubernetes watch in case of unknown error while flushing queue (#43645)](https://github.com/apache/airflow/pull/43645): @pavansharma36
     Linked issues:
       - [ ] [Linked Issue #43440](https://github.com/apache/airflow/issues/43440): @iw-pavan
   - [ ] [Update 'namespace' priority for 'find_pod' function (#43762)](https://github.com/apache/airflow/pull/43762): @MaksYermak
   - [ ] [AIP-72: Remove DAG pickling (#43667)](https://github.com/apache/airflow/pull/43667): @kaxil
## Provider [common.compat: 1.2.2rc1](https://pypi.org/project/apache-airflow-providers-common-compat/1.2.2rc1)
   - [ ] [serialize asset/dataset timetable conditions in OpenLineage info also for older supported Airflow 2 versions (#43434)](https://github.com/apache/airflow/pull/43434): @mobuchowski
   - [x] [Standard provider python operator (#42081)](https://github.com/apache/airflow/pull/42081): @gopidesupavan
## Provider [common.sql: 1.20.0rc1](https://pypi.org/project/apache-airflow-providers-common-sql/1.20.0rc1)
   - [ ] [Add support for semicolon stripping to DbApiHook, PrestoHook, and TrinoHook (#41916)](https://github.com/apache/airflow/pull/41916): @Illumaria
     Linked issues:
       - [ ] [Linked Issue #34828](https://github.com/apache/airflow/issues/34828): @MikeWallis42
## Provider [databricks: 6.13.0rc1](https://pypi.org/project/apache-airflow-providers-databricks/6.13.0rc1)
   - [ ] [Add on_kill  equivalent to Databricks SQL Hook to cancel timed out queries (#42668)](https://github.com/apache/airflow/pull/42668): @R7L208
     Linked issues:
       - [ ] [Linked Issue #42115](https://github.com/apache/airflow/pull/42115): @R7L208
   - [ ] [Added support for job_parameters and dbt_commands in DatabricksRunNow Operator (#43895)](https://github.com/apache/airflow/pull/43895): @pranshupand-db
   - [ ] [Enable workload identity authentication for the Databricks provider (#41639)](https://github.com/apache/airflow/pull/41639): @basvandriel
     Linked issues:
       - [ ] [Linked Issue #41586](https://github.com/apache/airflow/issues/41586): @basvandriel
   - [ ] [Add support for semicolon stripping to DbApiHook, PrestoHook, and TrinoHook (#41916)](https://github.com/apache/airflow/pull/41916): @Illumaria
     Linked issues:
       - [ ] [Linked Issue #34828](https://github.com/apache/airflow/issues/34828): @MikeWallis42
## Provider [dbt.cloud: 3.11.2rc1](https://pypi.org/project/apache-airflow-providers-dbt-cloud/3.11.2rc1)
   - [ ] [Added condition to check if it is a scheduled save or rerun (#43453)](https://github.com/apache/airflow/pull/43453): @krzysztof-kubis
     Linked issues:
       - [ ] [Linked Issue #43347](https://github.com/apache/airflow/issues/43347): @krzysztof-kubis
## Provider [docker: 3.14.1rc1](https://pypi.org/project/apache-airflow-providers-docker/3.14.1rc1)
   - [x] [Fix logs with leading spaces in the Docker operator (#33692) (#43840)](https://github.com/apache/airflow/pull/43840): @mrk-andreev
   - [x] [Standard provider python operator (#42081)](https://github.com/apache/airflow/pull/42081): @gopidesupavan
## Provider [elasticsearch: 5.5.3rc1](https://pypi.org/project/apache-airflow-providers-elasticsearch/5.5.3rc1)
   - [ ] [Add support for semicolon stripping to DbApiHook, PrestoHook, and TrinoHook (#41916)](https://github.com/apache/airflow/pull/41916): @Illumaria
     Linked issues:
       - [ ] [Linked Issue #34828](https://github.com/apache/airflow/issues/34828): @MikeWallis42
## Provider [exasol: 4.6.1rc1](https://pypi.org/project/apache-airflow-providers-exasol/4.6.1rc1)
   - [ ] [Add support for semicolon stripping to DbApiHook, PrestoHook, and TrinoHook (#41916)](https://github.com/apache/airflow/pull/41916): @Illumaria
     Linked issues:
       - [ ] [Linked Issue #34828](https://github.com/apache/airflow/issues/34828): @MikeWallis42
## Provider [fab: 1.5.1rc1](https://pypi.org/project/apache-airflow-providers-fab/1.5.1rc1)
   - [x] [fab_auth_manager: allow get_user method to return the user authenticated via Kerberos (#43662)](https://github.com/apache/airflow/pull/43662): @brouberol
## Provider [google: 10.26.0rc1](https://pypi.org/project/apache-airflow-providers-google/10.26.0rc1)
   - [ ] [Add support for IAM database authentication for CloudSQL connection (#43631)](https://github.com/apache/airflow/pull/43631): @MaksYermak
   - [ ] [Provide option to `force_delete` for `GCSToBigQueryOperator` (#43785)](https://github.com/apache/airflow/pull/43785): @nathadfield
   - [x] [Unify reattach_states parameter logic across BigQuery operators (#43259)](https://github.com/apache/airflow/pull/43259): @moiseenkov
     Linked issues:
       - [x] [Linked Issue #40664](https://github.com/apache/airflow/pull/40664): @VladaZakharova
   - [x] [Remove non-existing field  from the ListCustomTrainingJobOperator's template_fields (#43924)](https://github.com/apache/airflow/pull/43924): @moiseenkov
   - [x] [Fix validating `parent_model` parameter in `UploadModelOperator` (#43473)](https://github.com/apache/airflow/pull/43473): @VladaZakharova
   - [ ] [Add support for semicolon stripping to DbApiHook, PrestoHook, and TrinoHook (#41916)](https://github.com/apache/airflow/pull/41916): @Illumaria
     Linked issues:
       - [ ] [Linked Issue #34828](https://github.com/apache/airflow/issues/34828): @MikeWallis42
   - [ ] [Remove Airflow 2.1 compat code in Google provider (#43952)](https://github.com/apache/airflow/pull/43952): @uranusjr
   - [x] [Explain how to use uv with airflow virtualenv and make it works (#43604)](https://github.com/apache/airflow/pull/43604): @potiuk
     Linked issues:
       - [x] [Linked Issue #43200](https://github.com/apache/airflow/issues/43200): @potiuk
   - [x] [Standard provider python operator (#42081)](https://github.com/apache/airflow/pull/42081): @gopidesupavan
   - [x] [Bump google-ads version to use v18 by default (#43474)](https://github.com/apache/airflow/pull/43474): @VladaZakharova
## Provider [http: 4.13.3rc1](https://pypi.org/project/apache-airflow-providers-http/4.13.3rc1)
   - [ ] [Fix(http) bug, pass request_kwargs to HttpHooK.run (#43459)](https://github.com/apache/airflow/pull/43459): @childe
   - [x] [Limit temporarily aiohttp to < 3.11.0 (#44006)](https://github.com/apache/airflow/pull/44006): @potiuk
## Provider [jdbc: 4.5.3rc1](https://pypi.org/project/apache-airflow-providers-jdbc/4.5.3rc1)
   - [ ] [Add support for semicolon stripping to DbApiHook, PrestoHook, and TrinoHook (#41916)](https://github.com/apache/airflow/pull/41916): @Illumaria
     Linked issues:
       - [ ] [Linked Issue #34828](https://github.com/apache/airflow/issues/34828): @MikeWallis42
## Provider [microsoft.azure: 11.1.0rc1](https://pypi.org/project/apache-airflow-providers-microsoft-azure/11.1.0rc1)
   - [x] [Add copy_object functionality for wasbhook (#43037)](https://github.com/apache/airflow/pull/43037): @kunaljubce
     Linked issues:
       - [x] [Linked Issue #42497](https://github.com/apache/airflow/issues/42497): @kunaljubce
   - [x] [Fix Power BI trigger testcase (#43494)](https://github.com/apache/airflow/pull/43494): @ambika-garg
   - [ ] [Add min version to ipykernel,scrapbook, pywinrm (#43603)](https://github.com/apache/airflow/pull/43603): @rawwar
## Provider [microsoft.mssql: 3.9.2rc1](https://pypi.org/project/apache-airflow-providers-microsoft-mssql/3.9.2rc1)
   - [ ] [Add support for semicolon stripping to DbApiHook, PrestoHook, and TrinoHook (#41916)](https://github.com/apache/airflow/pull/41916): @Illumaria
     Linked issues:
       - [ ] [Linked Issue #34828](https://github.com/apache/airflow/issues/34828): @MikeWallis42
## Provider [microsoft.winrm: 3.6.1rc1](https://pypi.org/project/apache-airflow-providers-microsoft-winrm/3.6.1rc1)
   - [x] [Move responsibility to run a command from WinRMOperator to WinRMHook (#43646)](https://github.com/apache/airflow/pull/43646): @dabla
## Provider [mysql: 5.7.4rc1](https://pypi.org/project/apache-airflow-providers-mysql/5.7.4rc1)
   - [ ] [Add support for semicolon stripping to DbApiHook, PrestoHook, and TrinoHook (#41916)](https://github.com/apache/airflow/pull/41916): @Illumaria
     Linked issues:
       - [ ] [Linked Issue #34828](https://github.com/apache/airflow/issues/34828): @MikeWallis42
   - [x] [Explain how to use uv with airflow virtualenv and make it works (#43604)](https://github.com/apache/airflow/pull/43604): @potiuk
     Linked issues:
       - [x] [Linked Issue #43200](https://github.com/apache/airflow/issues/43200): @potiuk
## Provider [odbc: 4.8.1rc1](https://pypi.org/project/apache-airflow-providers-odbc/4.8.1rc1)
   - [ ] [Add support for semicolon stripping to DbApiHook, PrestoHook, and TrinoHook (#41916)](https://github.com/apache/airflow/pull/41916): @Illumaria
     Linked issues:
       - [ ] [Linked Issue #34828](https://github.com/apache/airflow/issues/34828): @MikeWallis42
## Provider [openlineage: 1.14.0rc1](https://pypi.org/project/apache-airflow-providers-openlineage/1.14.0rc1)
   - [ ] [Add support for semicolon stripping to DbApiHook, PrestoHook, and TrinoHook (#41916)](https://github.com/apache/airflow/pull/41916): @Illumaria
     Linked issues:
       - [ ] [Linked Issue #34828](https://github.com/apache/airflow/issues/34828): @MikeWallis42
   - [ ] [add ProcessingEngineRunFacet to OL DAG Start event (#43213)](https://github.com/apache/airflow/pull/43213): @mobuchowski
   - [ ] [serialize asset/dataset timetable conditions in OpenLineage info also for older supported Airflow 2 versions (#43434)](https://github.com/apache/airflow/pull/43434): @mobuchowski
   - [x] [openlineage: accept whole config when instantiating OpenLineageClient (#43740)](https://github.com/apache/airflow/pull/43740): @JDarDagran
   - [x] [Temporarily limit openlineage to <1.24.0 (#43732)](https://github.com/apache/airflow/pull/43732): @potiuk
   - [x] [Standard provider python operator (#42081)](https://github.com/apache/airflow/pull/42081): @gopidesupavan
## Provider [oracle: 3.12.1rc1](https://pypi.org/project/apache-airflow-providers-oracle/3.12.1rc1)
   - [ ] [Fix oracle bulk insert issue when leftover chunk is empty (#43467)](https://github.com/apache/airflow/pull/43467): @romsharon98
   - [ ] [Add support for semicolon stripping to DbApiHook, PrestoHook, and TrinoHook (#41916)](https://github.com/apache/airflow/pull/41916): @Illumaria
     Linked issues:
       - [ ] [Linked Issue #34828](https://github.com/apache/airflow/issues/34828): @MikeWallis42
## Provider [pagerduty: 3.8.1rc1](https://pypi.org/project/apache-airflow-providers-pagerduty/3.8.1rc1)
   - [x] [Standard provider bash operator (#42252)](https://github.com/apache/airflow/pull/42252): @gopidesupavan
   - [ ] [Purge existing SLA implementation (#42285)](https://github.com/apache/airflow/pull/42285): @ferruzzi
## Provider [papermill: 3.8.2rc1](https://pypi.org/project/apache-airflow-providers-papermill/3.8.2rc1)
   - [ ] [Add min version to ipykernel,scrapbook, pywinrm (#43603)](https://github.com/apache/airflow/pull/43603): @rawwar
## Provider [pinecone: 2.1.1rc1](https://pypi.org/project/apache-airflow-providers-pinecone/2.1.1rc1)
   - [ ] [Add source_tag to PineconeHook (#43960)](https://github.com/apache/airflow/pull/43960): @TJaniF
## Provider [postgres: 5.14.0rc1](https://pypi.org/project/apache-airflow-providers-postgres/5.14.0rc1)
   - [ ] [Add AWS Redshift Serverless support to PostgresHook (#43669)](https://github.com/apache/airflow/pull/43669): @topherinternational
   - [ ] [Fix PostgresHook bug when getting AWS Redshift Serverless credentials (#43807)](https://github.com/apache/airflow/pull/43807): @topherinternational
     Linked issues:
       - [ ] [Linked Issue #43669](https://github.com/apache/airflow/pull/43669): @topherinternational
   - [ ] [Add support for semicolon stripping to DbApiHook, PrestoHook, and TrinoHook (#41916)](https://github.com/apache/airflow/pull/41916): @Illumaria
     Linked issues:
       - [ ] [Linked Issue #34828](https://github.com/apache/airflow/issues/34828): @MikeWallis42
## Provider [presto: 5.7.0rc1](https://pypi.org/project/apache-airflow-providers-presto/5.7.0rc1)
   - [ ] [Add support for semicolon stripping to DbApiHook, PrestoHook, and TrinoHook (#41916)](https://github.com/apache/airflow/pull/41916): @Illumaria
     Linked issues:
       - [ ] [Linked Issue #34828](https://github.com/apache/airflow/issues/34828): @MikeWallis42
## Provider [slack: 8.9.2rc1](https://pypi.org/project/apache-airflow-providers-slack/8.9.2rc1)
   - [ ] [Add support for semicolon stripping to DbApiHook, PrestoHook, and TrinoHook (#41916)](https://github.com/apache/airflow/pull/41916): @Illumaria
     Linked issues:
       - [ ] [Linked Issue #34828](https://github.com/apache/airflow/issues/34828): @MikeWallis42
## Provider [smtp: 1.8.1rc1](https://pypi.org/project/apache-airflow-providers-smtp/1.8.1rc1)
   - [x] [Standard provider bash operator (#42252)](https://github.com/apache/airflow/pull/42252): @gopidesupavan
   - [ ] [Purge existing SLA implementation (#42285)](https://github.com/apache/airflow/pull/42285): @ferruzzi
   - [ ] [Unify DAG schedule args and change default to None (#41453)](https://github.com/apache/airflow/pull/41453): @uranusjr
## Provider [snowflake: 5.8.1rc1](https://pypi.org/project/apache-airflow-providers-snowflake/5.8.1rc1)
   - [ ] [Add support for semicolon stripping to DbApiHook, PrestoHook, and TrinoHook (#41916)](https://github.com/apache/airflow/pull/41916): @Illumaria
     Linked issues:
       - [ ] [Linked Issue #34828](https://github.com/apache/airflow/issues/34828): @MikeWallis42
   - [x] [Standard provider python operator (#42081)](https://github.com/apache/airflow/pull/42081): @gopidesupavan
## Provider [sqlite: 3.9.1rc1](https://pypi.org/project/apache-airflow-providers-sqlite/3.9.1rc1)
   - [ ] [Add support for semicolon stripping to DbApiHook, PrestoHook, and TrinoHook (#41916)](https://github.com/apache/airflow/pull/41916): @Illumaria
     Linked issues:
       - [ ] [Linked Issue #34828](https://github.com/apache/airflow/issues/34828): @MikeWallis42
## Provider [standard: 0.0.1rc1](https://pypi.org/project/apache-airflow-providers-standard/0.0.1rc1)
   - [ ] [Airflow Standard Provider (#41564)](https://github.com/apache/airflow/pull/41564): @romsharon98
## Provider [teradata: 2.6.1rc1](https://pypi.org/project/apache-airflow-providers-teradata/2.6.1rc1)
   - [ ] [Add support for semicolon stripping to DbApiHook, PrestoHook, and TrinoHook (#41916)](https://github.com/apache/airflow/pull/41916): @Illumaria
     Linked issues:
       - [ ] [Linked Issue #34828](https://github.com/apache/airflow/issues/34828): @MikeWallis42
## Provider [trino: 5.9.0rc1](https://pypi.org/project/apache-airflow-providers-trino/5.9.0rc1)
   - [ ] [Add support for semicolon stripping to DbApiHook, PrestoHook, and TrinoHook (#41916)](https://github.com/apache/airflow/pull/41916): @Illumaria
     Linked issues:
       - [ ] [Linked Issue #34828](https://github.com/apache/airflow/issues/34828): @MikeWallis42
## Provider [vertica: 3.9.1rc1](https://pypi.org/project/apache-airflow-providers-vertica/3.9.1rc1)
   - [ ] [Add support for semicolon stripping to DbApiHook, PrestoHook, and TrinoHook (#41916)](https://github.com/apache/airflow/pull/41916): @Illumaria
     Linked issues:
       - [ ] [Linked Issue #34828](https://github.com/apache/airflow/issues/34828): @MikeWallis42
## Provider [ydb: 2.0.0rc1](https://pypi.org/project/apache-airflow-providers-ydb/2.0.0rc1)
   - [ ] [Migrate YDB Operator to new DBAPI (#43784)](https://github.com/apache/airflow/pull/43784): @vgvoleg
   - [ ] [Add support for semicolon stripping to DbApiHook, PrestoHook, and TrinoHook (#41916)](https://github.com/apache/airflow/pull/41916): @Illumaria
     Linked issues:
       - [ ] [Linked Issue #34828](https://github.com/apache/airflow/issues/34828): @MikeWallis42

All users involved in the PRs:
@basvandriel @TJaniF @vgvoleg @kacpermuda @pyrr @Illumaria @MaksYermak @pranshupand-db @kunaljubce @romsharon98 @nathadfield @kaxil @Udbv @childe @krzysztof-kubis @LyndonFan @mobuchowski @ferruzzi @brou

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
I checked all my changes - most of them were docs and dependencies. Dependencies look good (openlineage change of mine was overwritten later by @JDarDagran - so all good there as well. 

So everything looks good from my side. 👍

**Comment by JDarDagran** [comment]
> I checked all my changes - most of them were docs and dependencies. Dependencies look good (openlineage change of mine was overwritten later by @JDarDagran - so all good there as well.

Yup, confirming my changes from from #43740 work as expected.

**Comment by jimwbaldwin** [comment]
> https://github.com/apache/airflow/pull/43622: @jimwbaldwin

Heya, confirming that #43622 is working correctly after installing [9.1.0rc4](https://pypi.org/project/apache-airflow-providers-amazon/9.1.0rc4)

**Comment by gopidesupavan** [comment]
I verified all my changes and tested a few DAG examples. The Spark, Beam, and Docker operators are working as expected.

For Snowflake, I couldn't test in a real environment but confirmed that the imports appear correct.

As for the following providers—Apprise, Atlassian, PagerDuty, OpenLineage, and SMTP—they only have documentation updates, which also look fine.

**Comment by gopidesupavan** [comment]
> I verified all my changes and tested a few DAG examples. The Spark, Beam, and Docker operators are working as expected.
> 
> For Snowflake, I couldn't test in a real environment but confirmed that the imports appear correct.
> 
> As for the following providers—Apprise, Atlassian, PagerDuty, OpenLineage, and SMTP—they only have documentation updates, which also look fine.

google, celery providers also fine.

One thing i observed the in the docker provider connection documentation. the auth reference url broken. raised fix here https://github.com/apache/airflow/pull/44112

**Comment by kunaljubce** [comment]
Verified that my changes on azure provider works as expected!

**Comment by brouberol** [comment]
I checked that my changes related to using Kerberos authentication for the stable API work with `apache-airflow-providers-fab==1.5.1rc1`.

**Comment by ambika-garg** [comment]
Verified my changes in azure provided. Working as expected.

**Comment by moiseenkov** [comment]
Hi,
#43259 and #43924 work as expected

**Comment by eladkal** [comment]
> One thing i observed the in the docker provider connection documentation. the auth reference url broken. raised fix here https://github.com/apache/airflow/pull/44112

Thanks. This will be added in the next wave

**Comment by dabla** [comment]
[43646](https://github.com/apache/airflow/pull/43646) works as expected

**Comment by VladaZakharova** [comment]
Hi there! Changes https://github.com/apache/airflow/pull/43474 and https://github.com/apache/airflow/pull/43474 work fine

**Comment by eladkal** [comment]
Thank you everyone. Providers are released.

I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).

**Comment by Udbv** [comment]
Hi #43576  works as expected.
