### ISSUE TITLE
Status of testing Providers that were prepared on November 24, 2024

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#44324]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [celery: 3.8.5rc1](https://pypi.org/project/apache-airflow-providers-celery/3.8.5rc1)
   - [ ] [Allow for retry when tasks are stuck in queued (#43520)](https://github.com/apache/airflow/pull/43520): @dimberman
## Provider [cncf.kubernetes: 10.0.1rc1](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/10.0.1rc1)
   - [x] [Bugfix KubernetesJobOperator.on_kill() (#44131)](https://github.com/apache/airflow/pull/44131): @moiseenkov
   - [ ] [Allow for retry when tasks are stuck in queued (#43520)](https://github.com/apache/airflow/pull/43520): @dimberman
   - [ ] [Rename execution_date to logical_date across codebase (#43902)](https://github.com/apache/airflow/pull/43902): @sunank200
## Provider [google: 11.0.0rc1](https://pypi.org/project/apache-airflow-providers-google/11.0.0rc1)
   - [x] [Remove deprecated functionality from Google provider (#43953)](https://github.com/apache/airflow/pull/43953): @moiseenkov
   - [x] [feat: add OpenLineage support for BigQueryToBigQueryOperator (#44214)](https://github.com/apache/airflow/pull/44214): @kacpermuda
   - [ ] [Introduce gcp advance (V3) API translate native datasets operators (#44271)](https://github.com/apache/airflow/pull/44271): @olegkachur-e
   - [ ] [Introduce new gcp TranslateText and TranslateTextBatch operators (#43860)](https://github.com/apache/airflow/pull/43860): @olegkachur-e
   - [ ] [Add gcloud command to DataprocCreateClusterOperator to be able to create dataproc on GKE cluster (#44185)](https://github.com/apache/airflow/pull/44185): @MaksYermak
   - [x] [Fix incorrect query in `BigQueryAsyncHook.create_job_for_partition_get` (#44225)](https://github.com/apache/airflow/pull/44225): @sean-rose
     Linked issues:
       - [x] [Linked Issue #37655](https://github.com/apache/airflow/pull/37655): @Silviu-Surcica
   - [x] [Fix Dataplex Data Quality partial update (#44262)](https://github.com/apache/airflow/pull/44262): @amirmor1
   - [ ] [Bump `google-cloud-translate` to `3.16` (#44297)](https://github.com/apache/airflow/pull/44297): @kaxil
   - [ ] [fix google datacatalog operator tests (#44281)](https://github.com/apache/airflow/pull/44281): @gopidesupavan
   - [ ] [Rename execution_date to logical_date across codebase (#43902)](https://github.com/apache/airflow/pull/43902): @sunank200
## Provider [standard: 0.0.2rc1](https://pypi.org/project/apache-airflow-providers-standard/0.0.2rc1)
   - [x] [Fix TriggerDagRunOperator extra_link when trigger_dag_id is templated (#42810)](https://github.com/apache/airflow/pull/42810): @fredthomsen
   - [x] [Move `TriggerDagRunOperator` to standard provider (#44053)](https://github.com/apache/airflow/pull/44053): @hardeybisey
     Linked issues:
       - [x] [Linked Issue #43641](https://github.com/apache/airflow/issues/43641): @gopidesupavan
   - [x] [Move filesystem sensor to standard provider (#43890)](https://github.com/apache/airflow/pull/43890): @kunaljubce
     Linked issues:
       - [x] [Linked Issue #43641](https://github.com/apache/airflow/issues/43641): @gopidesupavan
   - [ ] [Rename execution_date to logical_date across codebase (#43902)](https://github.com/apache/airflow/pull/43902): @sunank200

All users involved in the PRs:
@amirmor1 @dimberman @hardeybisey @fredthomsen @MaksYermak @sunank200 @kunaljubce @kacpermuda @sean-rose @kaxil @olegkachur-e @moiseenkov @gopidesupavan

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by moiseenkov** [comment]
Hi, 
#44131 and #43953 look good

**Comment by hardeybisey** [comment]
Hi, [#44053](https://github.com/apache/airflow/pull/44053) works as expected.

**Comment by fredthomsen** [comment]
#42810 is good.

**Comment by kacpermuda** [comment]
#44214 is good

**Comment by amirmor1** [comment]
#44262 works as expected

**Comment by sean-rose** [comment]
I verified that #44225 works.

**Comment by kunaljubce** [comment]
@eladkal So I verified that #43890 works with `apache-airflow>=2.10.0`. 

<img width="746" alt="image" src="https://github.com/user-attachments/assets/e6fe96ac-45d5-4b56-9778-d6441f4a6265">

However, there's an error when I do the same with `apache-airflow==2.9.3` - 
<img width="743" alt="image" src="https://github.com/user-attachments/assets/025af1ed-0aa9-410a-9a72-5534765db73c">

Unless I am doing something wrong, in which case please let me know, it seems that this is happening because of #41021 which seems to be linked to the airflow 2.10.0 milestone. If that's the case, maybe we should update the documentation for it on PyPi?

<img width="795" alt="image" src="https://github.com/user-attachments/assets/77548938-973d-4a03-8cc0-90d8d556ec70">

**Comment by potiuk** [comment]
> However, there's an error when I do the same with apache-airflow==2.9.3 

Good catch. Apparently we miss compatibility class for that in "common.compat" and the sensor has no corresponding tests that would detect it in "providers/tests/standard/sensors"  - the test for filesystem sensor is still in "tests/sensors" that's why our test suite did not catch it.

> If that's the case, maybe we should update the documentation for it on PyPi?

Nope. We want to keep 2.8+ compatibility.  We should add compatibilty `StartTriggerArgs` class in "common.compat" similarly to other "after 2.8" features, and import the class from there in the sensor.

I guess @eladkal  - since it's not a regression and standard provider is still 0.* it's not a blocker for the release and can be fixed as a follow-up.

**Comment by eladkal** [comment]
@kunaljubce if you can raise a PR with a fix that would be much appreciated
