### ISSUE TITLE
AIP-72: Handling task instance state exceptions from task sdk and execution API

### ISSUE THREAD

**Issue by amoghrajesh** [apache/airflow#44414]
### Body

Similar to https://github.com/apache/airflow/issues/44137, there are various state exceptions raised while running `ti.task.execute`. This issue tracks handling them gracefully.

- [x] Deferral Exception: `TaskDeferred` (PR: https://github.com/apache/airflow/pull/44241 @amoghrajesh)
- [x] Skip Exception: `AirflowSkipException` (PR https://github.com/apache/airflow/pull/44786 @amoghrajesh)
- [x] Reschedule exception: `AirflowRescheduleException` (PR https://github.com/apache/airflow/pull/44907 @amoghrajesh) 
- [x] Fail Exception: `AirflowFailException` (PR https://github.com/apache/airflow/pull/44954 @amoghrajesh)
- [x] Sensor timeout exception: `AirflowSensorTimeout` (PR https://github.com/apache/airflow/pull/44954 @amoghrajesh)
- [x] Task terminated exception: `AirflowTaskTerminated` (PR https://github.com/apache/airflow/pull/44977 @amoghrajesh)
- [x] Task timeout (up_for_retry state) `AirflowTaskTimeout` (PR https://github.com/apache/airflow/pull/45310 @amoghrajesh)
- [x] Airflow Exception (up_for_retry state) (PR https://github.com/apache/airflow/pull/45308 @amoghrajesh)
- [x] System Exit: `SystemExit`(PR: https://github.com/apache/airflow/pull/45282 @amoghrajesh)
- [x] Base Exception: `BaseException` (PR https://github.com/apache/airflow/pull/45106 @amoghrajesh)

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by amoghrajesh** [comment]
I do not think we do it:
```
    except SystemExit:
        ...
    except BaseException:
        # TODO: Handle TI handle failure
        raise
```

**Comment by amoghrajesh** [comment]
All the TI states have been handled in various PRs as linked in the description. Closing this issue as complete.

**Comment by amoghrajesh** [comment]
All the TI states have been handled in various PRs as linked in the description. Closing this issue as complete.
