### ISSUE TITLE
Removal of AIP-44 code

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#44436]
### Body

We eventually decided to drop AIP-44. We are about to remove it and here is the list of things that should be removed:

-  [x] removal of "enble-aip-44" controlled parts of CI workflows and breeze 
-  [x] removal of `--database-isolation` Breeze flag (and corresponding scripts/test shennigans
-  [x] removal of `AIRFLOW_ENABLE_AIP_44` occurrences (ci/code) and `_ENABLE_AIP_44` , `InternalApiConfig`, `database_access_isolation`
- [x] https://github.com/apache/airflow/pull/44463
-  [x] removal of "internal_api_v1.yaml" and "internal-api" CLI
-  [x] removal of @internal_api_call decorators (82 methods)  - re-join back methods that were separated out from the main code - when methods start with `_`:
   - [x] ./task_sdk/src/airflow/sdk/definitions/asset/__init__.py: expand_alias_to_assets
   - [x] ./airflow/secrets/metastore.py:     _fetch_connection
   - [x] ./airflow/secrets/metastore.py:     _fetch_variable
   - [x] ./airflow/jobs/job.py:     _kill
   - [x] ./airflow/jobs/job.py:     _fetch_from_db
   - [x] ./airflow/jobs/job.py:     _add_to_db
   - [x] ./airflow/jobs/job.py:     _update_in_db
   - [x] ./airflow/jobs/job.py:     _update_heartbeat
   - [x] ./airflow/jobs/job.py: most_recent_job
   - [x] ./airflow/api/common/trigger_dag.py: trigger_dag
   - [x] ./airflow/assets/manager.py:     register_asset_change
   - [x] ./airflow/dag_processing/processor.py:     update_import_errors
   - [x] ./airflow/dag_processing/processor.py:     _validate_task_pools_and_update_dag_warnings
   - [x] ./airflow/dag_processing/processor.py:     execute_callbacks
   - [x] ./airflow/dag_processing/processor.py:     execute_callbacks_without_dag
   - [x] ./airflow/dag_processing/processor.py:     _execute_task_callbacks
   - [x] ./airflow/dag_processing/processor.py:     save_dag_to_db
   - [x] ./airflow/dag_processing/manager.py:     deactivate_stale_dags
   - [x] ./airflow/dag_processing/manager.py:     _fetch_callbacks
   - [x] ./airflow/dag_processing/manager.py:     _get_priority_filelocs
   - [x] ./airflow/dag_processing/manager.py:     clear_nonexistent_import_errors
   - [x] ./airflow/models/dagrun.py:     fetch_task_instances
   - [x] ./airflow/models/dagrun.py:     _check_last_n_dagruns_failed
   - [x] ./airflow/models/dagrun.py:     fetch_task_instance
   - [x] ./airflow/models/dagrun.py:     get_previous_dagrun
   - [x] ./airflow/models/dagrun.py:     get_previous_scheduled_dagrun
   - [x] ./airflow/models/dagrun.py:     _get_log_template
   - [x] ./airflow/models/trigger.py:     from_object
   - [x] ./airflow/models/trigger.py:     bulk_fetch
   - [x] ./airflow/models/trigger.py:     clean_unused
   - [x] ./airflow/models/trigger.py:     submit_event
   - [x] ./airflow/models/trigger.py:     submit_failure
   - [x] ./airflow/models/trigger.py:     ids_for_triggerer
   - [x] ./airflow/models/trigger.py:     assign_unassigned
   - [x] ./airflow/models/xcom_arg.py: _get_task_map_length
   - [x] ./airflow/models/renderedtifields.py:     _update_runtime_evaluated_template_fields
   - [x] ./airflow/models/serialized_dag.py:     get_serialized_dag
   - [x] ./airflow/models/dag.py:     fetch_callback
   - [x] ./airflow/models/dag.py:     fetch_dagrun
   - [x] ./airflow/models/dag.py:     get_current
   - [x] ./airflow/models/dag.py:     get_paused_dag_ids
   - [x] ./airflow/models/dag.py:     deactivate_deleted_dags
   - [x] ./airflow/models/skipmixin.py:     _skip
   - [x] ./airflow/models/skipmixin.py:     _skip_all_except
   - [x] ./airflow/models/xcom.py:     set
   - [x] ./airflow/models/xcom.py:     get_value
   - [x] ./airflow/models/xcom.py:     get_one
   - [x] ./airflow/models/xcom.py:     clear
   - [x] ./airflow/models/taskinstance.py: _merge_ti
   - [x] ./airflow/models/taskinstance.py: _add_log
   - [x] ./airflow/models/taskinstance.py: _update_ti_heartbeat
   - [x] ./airflow/models/taskinstance.py: _xcom_pull
   - [x] ./airflow/models/taskinstance.py: _get_template_context
   - [x] ./airflow/models/taskinstance.py: _handle_failure
   - [x] ./airflow/models/taskinstance.py: _record_task_map_for_downstreams
   - [x] ./airflow/models/taskinstance.py: _update_rtif
   - [x] ./airflow/models/taskinstance.py: _defer_task
   - [x] ./airflow/models/taskinstance.py: _handle_reschedule
   - [x] ./airflow/models/taskinstance.py:     get_task_instance
   - [x] ./airflow/models/taskinstance.py:     _clear_xcom_data
   - [x] ./airflow/models/taskinstance.py:     _set_state
   - [x] ./airflow/models/taskinstance.py:     _get_dagrun
   - [x] ./airflow/models/taskinstance.py:     _check_and_change_state_before_execution
   - [x] ./airflow/models/taskinstance.py:     _register_asset_changes_int
   - [x] ./airflow/models/taskinstance.py:     save_to_db
   - [x] ./airflow/models/dagwarning.py:     purge_inactive_dag_warnings
   - [x] ./airflow/models/variable.py:     _set
   - [x] ./airflow/models/variable.py:     _update
   - [x] ./airflow/models/variable.py:     _delete
   - [x] ./airflow/cli/commands/task_command.py: _get_ti_db_access
   - [x] ./airflow/utils/log/file_task_handler.py:     _render_filename_db_access
   - [x] ./airflow/utils/cli_action_loggers.py: _default_action_log_internal
   - [x] ./airflow/sensors/base.py: _orig_start_date
   - [x] ./providers/src/airflow/providers/edge/models/edge_logs.py:     push_logs
   - [x] ./providers/src/airflow/providers/edge/models/edge_job.py:     reserve_task
   - [x] ./providers/src/airflow/providers/edge/models/edge_job.py:     set_state
   - [x] ./providers/src/airflow/providers/edge/models/edge_worker.py:     register_worker
   - [x] ./providers/src/airflow/providers/edge/models/edge_worker.py:     set_state
   - [x] ./tests/api_internal/test_internal_api_call.py:     fake_method
   - [x] ./tests/api_internal/test_internal_api_call.py:     fake_method_with_params
   - [x] ./tests/api_internal/test_internal_api_call.py:     fake_class_method_with_params
   - [x] ./tests/api_internal/test_internal_api_call.py:     fake_class_method_with_serialized_params
- [ ] removal of `*Pydantic` models 

BTW. Command to generate list of methods:

```bash
find . -name '*.py' | xargs grep -A 4 '@internal_api_call' | grep -v "@internal_api_call" | grep "def " | sed 's/(.*//' | sed "s/-/: /" | sed "s/^/   - [ ] /" | sed "s/def //"
```

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
cc: @jscheffl @rawwar @kaxil

**Comment by ashb** [comment]
I'm currently re-working all the dag processing stuff to use TaskSDK code etc (but don't know when I'll have a PR for that -- likely Monday or Tuesday) so it _might_ be worth skipping over those. But on the other hand the changes are quite simple to do so it maybe makes sense to do it anyway.

**Comment by potiuk** [comment]
I think we can progress on those regardless. One-by-one.

**Comment by jscheffl** [comment]
I'd support - but probably I'm only having time on the weekend. As I was also preparing to move Edge-Worker off the internal API, I have 4 PR's (4 slices instead of one elephant) and asked @kaxil already for review. If somebody else has time... these 4 PRs implicitly also remove parts (5 hits) listed from the work and lift them to FastAPI.

https://github.com/apache/airflow/pulls?q=is%3Aopen+is%3Apr+author%3Ajscheffl+label%3Aprovider%3Aedge

**Comment by potiuk** [comment]
I take "airflow/secrets/" to get the founding removal PR :).

**Comment by potiuk** [comment]
First small, exemplary PR: https://github.com/apache/airflow/pull/44489

**Comment by potiuk** [comment]
Looking at jobs.

**Comment by rawwar** [comment]
I'll work on `airflow/models`

**Comment by jason810496** [comment]
working on
- `airflow/models/trigger`

**Comment by potiuk** [comment]
One more thing: 

Whenever we see `| ....Pydantic` we should also remove it. We can remove it also later if we forget it (there is the last point about removing all `...Pydantic` classes, but if we are modifying a file already for AIP-44 removal, we can as well remove those condidtional Pydantic type hints.

**Comment by potiuk** [comment]
> I'm currently re-working all the dag processing stuff to use TaskSDK code etc (but don't know when I'll have a PR for that -- likely Monday or Tuesday) so it _might_ be worth skipping over those. But on the other hand the changes are quite simple to do so it maybe makes sense to do it anyway.

Yeah. Let's use the momentum and fix all of them :)

**Comment by jscheffl** [comment]
All the providers/edge dependencies should be gone with #44434

**Comment by jscheffl** [comment]
I'm going for  ./airflow/sensors/base.py: _orig_start_date

**Comment by potiuk** [comment]
I am getting taskinstance 😱 😱 😱 😱 😱 😱

**Comment by jscheffl** [comment]
> I am getting taskinstance 😱 😱 😱 😱 😱 😱

I thought this is with @rawwar ?

**Comment by rawwar** [comment]
> I am getting taskinstance 😱 😱 😱 😱 😱 😱 

Please take it. I am stuck at airport and can't get to it until tomorrow

**Comment by potiuk** [comment]
> > I am getting taskinstance 😱 😱 😱 😱 😱 😱
> 
> Please take it. I am stuck at airport and can't get to it until tomorrow

AAAAH.... MISSED IT ....

**Comment by potiuk** [comment]
CLOSED !!!!

**Comment by kaxil** [comment]
Nice work 👏
