### ISSUE TITLE
Remove deprecated code from providers before Airflow 2.11.0 release

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#44559]
### Body

Following [[LAZY CONSENSUS] Remove deprecations from providers prior to Airflow 2.11 release](https://lists.apache.org/thread/lhy7zhz8yxo3jjpln0ds8ogszgb9b469) this issue will track the progress of the removal status.

**How to remove?**
1. PRs should be easy to review, You can handle more than 1 provider in the same PR but please use judgment about how many files the PR changes. Please use meaningful commit message.
2. Find all deprecated code in a provider and accommodate for the needed change (normally the code has deprecation warning that indicates what needs to be removed). Make sure you are not removing code that was just deprecated in recent PR and was never released in stable version. Do not bulk remove!
3. Add entry to CHANGELOG.rst with information about what was removed and how to mitigate (normally it's copy/paste with minor adjustments to the deprecation warning). Use the following blockright after the `Changelog` line:

```
main
....

.. warning::
  All deprecated classes, parameters and features have been removed from the {provider_name} provider package.
  The following breaking changes were introduced:

  * what was removed and how to mitigate

```

4. If provider was already handled and introduce new deprecation do not remove again (at least not for now).

List of providers:

- [x] airbyte https://github.com/apache/airflow/pull/44577
- [x] alibaba https://github.com/apache/airflow/pull/44576
- [x] amazon https://github.com/apache/airflow/pull/42450
- [x] apache.beam #44700
- [x] apache.cassandra no deprecations
- [x] apache.drill https://github.com/apache/airflow/pull/44575
- [x] apache.druid https://github.com/apache/airflow/pull/44765
- [x] apache.flink. no deprecations
- [x] apache.hdfs no deprecations
- [x] apache.hive #44715
- [x] apache.iceberg no deprecations
- [x] apache.impala no deprecations
- [x] apache.kafka no deprecations
- [x] apache.kylin no deprecations
- [x] apache.livy #44631
- [x] apache.pig no deprecations
- [x] apache.pinot no deprecations
- [x] apache.spark #44567
- [x] apprise #44764
- [x] arangodb *No deprecations*
- [x] asana *No deprecations*
- [x] atlassian.jira #44644
- [x] celery *Assume deprecations do not affect user and will stay*
- [x] cloudant *No deprecations*
- [x] cncf.kubernetes https://github.com/apache/airflow/pull/43689
- [x] cohere *No deprecations*
- [x] common.compat *No deprecations*
- [x] common.io *No deprecations*
- [x] common.sql #44645
- [x] databricks https://github.com/apache/airflow/pull/44566
- [x] datadog *No deprecations*
- [x] dbt #44638
- [x] dingding *No deprecations*
- [x] discord *No deprecations*
- [x] docker #44583
- [x] edge *New provider, this is sooo fresh and cool it does not have deprecations (yet!)*
- [x] elasticsearch https://github.com/apache/airflow/pull/44629
- [x] exasol *No deprecations*
- [x] fab https://github.com/apache/airflow/pull/44198
- [x] facebook *No deprecations*
- [x] ftp *No deprecations*
- [x] github *No deprecations*
- [x] google **excluded from policy**
- [x] grpc *No deprecations*
- [x] hashicorp https://github.com/apache/airflow/pull/44598
- [x] http #44542
- [x] imap *No deprecations*
- [x] influxdb *No deprecations*
- [x] jdbc #44662
- [x] jenkins *No deprecations*
- [x] microsoft.azure https://github.com/apache/airflow/pull/44763
- [x] microsoft.mssql #44762
- [x] microsoft.psrp #44761
- [x] microsoft.winrm *No deprecations*
- [x] mongo *No deprecations*
- [x] mysql #44665
- [x] neo4j *No deprecations*
- [x] odbc *No deprecations*
- [x] openai *No deprecations*
- [x] openfaas *No deprecations*
- [x] openlineage #44636
- [x] opensearch *No deprecations*
- [x] opsgenie *No deprecations*
- [x] oracle #44704
- [x] pagerduty https://github.com/apache/airflow/pull/44653
- [x] papermill *No deprecations*
- [x] pgvector *No deprecations*
- [x] pinecone *No deprecations*
- [x] postgres #44705
- [x] presto *No deprecations*
- [x] qdrant *No deprecations*
- [x] redis  #44633
- [x] salesforce *No deprecations*
- [x] samba *No deprecations*
- [x] segment *No deprecations*
- [x] sendgrid #44637
- [x] sftp https://github.com/apache/airflow/pull/44740
- [x] singularity *No deprecations*
- [x] slack #44693
- [x] smtp *No deprecations* 
- [x] snowflake  #44756
- [x] sqlite #44707
- [x] ssh #44544
- [x] standard https://github.com/apache/airflow/pull/44541
- [x] tableau https://github.com/apache/airflow/pull/44757
- [x] telegram *No deprecations*
- [x] teradata https://github.com/apache/airflow/pull/44746
- [x] trino https://github.com/apache/airflow/pull/44717
- [x] vertica #44748
- [x] weaviate https://github.com/apache/airflow/pull/44745
- [x] yandex https://github.com/apache/airflow/pull/44754
- [x] ydb *No deprecations*
- [x] zendesk *No deprecations*

**Maintainers please update the list with the relevant PRs/status**

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by Prab-27** [comment]
Hello @potiuk 
I'm a newbie I would like to confirm whether I should use the `v2-10-test` branch for this issue since it is related to version 2

**Comment by kunaljubce** [comment]
@Prab-27 If you're talking about which branch to raise the PR on, that should be `main`. Refer to the tagged PRs for inspiration.

**Comment by kunaljubce** [comment]
@eladkal So in the context of this change, are we good to deprecate the Apache Drill provider completely - https://github.com/apache/airflow/blob/3747c91afdcd0470ca29e911c589b334b357b778/providers/src/airflow/providers/apache/drill/operators/drill.py#L33?

**Comment by Prab-27** [comment]
@eladkal I’m working on the hashicorp provider and will soon raise a PR.

**Comment by jscheffl** [comment]
@eladkal I just checked for the noted deprecations in Celery - these are purely for executor interface, not DAG author specific - and the change was just added and require Airflow 2.10.4 as minimum. If we add a breaking change, Celery can not be upgraded for Airflow 2.10.3 and below.
Therefore I'd recommend to keep the Celery deprecations for a moment. No harm for the intend to help users to migrate.

**Comment by Prab-27** [comment]
@jscheffl - How can I determine the version number like 3.8.0 in CHANGELOG.rst? 

I believe the version number in CHANGELOG.rst is derived from the next versions mentioned in provider.yaml .

**Comment by eladkal** [comment]
> @jscheffl - How can I determine the version number like 5.0.0 in CHANGELOG.rst?
> 
> I believe the version number in CHANGELOG.rst is derived from the next versions mentioned in provider.yaml .

You don't see the instructions in step 3. You set `main` not version. The version number is chosen by release manager during release time.

**Comment by kunaljubce** [comment]
> @eladkal So in the context of this change, are we good to deprecate the Apache Drill provider completely?
> 
> https://github.com/apache/airflow/blob/3747c91afdcd0470ca29e911c589b334b357b778/providers/src/airflow/providers/apache/drill/operators/drill.py#L33

@eladkal In case you missed this message ^^^

**Comment by jason810496** [comment]
Working on 
- elasticsearch

**Comment by kunaljubce** [comment]
@eladkal @jscheffl `apache.hdfs` has no deprecations. Please update the description.

**Comment by potiuk** [comment]
Updatiing

**Comment by jscheffl** [comment]
> Updatiing

Updating descriptions in Github is a pain. I did it already ~10 times and it seems if others update as well then sometimes (at least 10 times already) my changes are lost. Also notes down a few multiple times which have no deprecations. Tracking a set of PRs on a bug ticket is something Github is not made for :-(

**Comment by kunaljubce** [comment]
FYI - Working on Apache Drill and Apache Druid deprecations.

**Comment by potiuk** [comment]
> Updating descriptions in Github is a pain. I did it already ~10 times and it seems if others update as well then sometimes (at least 10 times already) my changes are lost. Also notes down a few multiple times which have no deprecations. Tracking a set of PRs on a bug ticket is something Github is not made for :-(

What I did it in the past is re-generating those issues automatically from time to time ...  Another thing-> I did not link/update the PRs in the list just "clicked" the checkmark - it was good enough usually.

**Comment by kunaljubce** [comment]
@potiuk @jscheffl While we're at it, below also don't have any deprecations - 

* apache.pig
* apache.pinot
* apache.cassandra

With the `apache.druid` PR up, looks like we're done with the Apache series of deprecations :)

**Comment by potiuk** [comment]
<img width="267" alt="Screenshot 2024-12-07 at 21 51 20" src="https://github.com/user-attachments/assets/3d32bfa9-51a3-4270-82bc-609b86210045">

🚀

**Comment by potiuk** [comment]
Is it done ?????!   ??? 🚀

**Comment by potiuk** [comment]
Shall you do the honors @eladkal and close it ?

**Comment by eladkal** [comment]
Created a small followup https://github.com/apache/airflow/issues/44807 to make docs better :)
