### ISSUE TITLE
Improve example docs around `SQLExecuteQueryOperator` in all SQLrelated providers 

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#44807]
### Body

Context: https://github.com/apache/airflow/pull/44707#discussion_r1872961329

In Sqlite provider we have `operators.rst` which explains how to leverage `SQLExecuteQueryOperator` from `common.sql `provider to be used with Sqlite. We should have similar doc and examples for all SQL related operators  that were removed as part of https://github.com/apache/airflow/issues/44559

**The Task:**
verify that we have `operators.rst` in each of the above providers that explain how to use `SQLExecuteQueryOperator` with the specific provider **See sqlite provider [operators.rst](https://github.com/apache/airflow/blob/c73becd1a7b5b38a5b0dfe0cb9d02b076bfe6f32/docs/apache-airflow-providers-sqlite/operators.rst#L25) for example template**:

```
.. _howto/operator:SqliteOperator:

SQLExecuteQueryOperator to connect to Sqlite
============================================

Use the :class:`SQLExecuteQueryOperator<airflow.providers.common.sql.operators.sql>` to execute
Sqlite commands in a `Sqlite <https://sqlite.org/lang.html>`__ database.

.. note::
    Previously, ``SqliteOperator`` was used to perform this kind of operation. After deprecation this has been removed. Please use ``SQLExecuteQueryOperator`` instead.

Using the Operator
^^^^^^^^^^^^^^^^^^

Use the ``conn_id`` argument to connect to your Sqlite instance where
the connection metadata is structured as follows:

.. list-table:: Sqlite Airflow Connection Metadata
   :widths: 25 25
   :header-rows: 1

   * - Parameter
     - Input
   * - Host: string
     - Sqlite database file

An example usage of the SQLExecuteQueryOperator to connect to Sqlite is as follows:

.. exampleinclude:: /../../providers/tests/system/sqlite/example_sqlite.py
    :language: python
    :start-after: [START howto_operator_sqlite]
    :end-before: [END howto_operator_sqlite]

Furthermore, you can use an external file to execute the SQL commands. Script folder must be at the same level as DAG.py file.

.. exampleinclude:: /../../providers/tests/system/sqlite/example_sqlite.py
    :language: python
    :start-after: [START howto_operator_sqlite_external_file]
    :end-before: [END howto_operator_sqlite_external_file]

```

If possible accommodate for the specific parameters that can be passed from the provider to the hook.
For example in Postgres we can pass `hook_params` for enabling logging so we explain about this explicitly with [example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html#enable-logging-of-database-messages-sent-to-the-client)

![Screenshot 2024-12-10 at 10 42 52](https://github.com/user-attachments/assets/6cfb53df-6eab-4522-974d-67bb82aa1606)

The items:

- [ ] Exasol (Previously had `ExasolOperator`)
- [ ] apache.drill (Previously had `DrillOperator`)
- [ ] jdbc (Previously had `JdbcOperator`)
- [ ] microsoft.mssql (Previously had `MsSqlOperator`)
- [ ] mysql (Previously had `MySQLOperator`)
- [x] oracle (Previously had `OracleOperator`)
- [x] presto Previously had `PrestoOperator`)
- [ ] snowflake (Previously had `SnowflakeOperator`)
- [ ] trino (Previously had `TrinoOperator`)
- [x] vertica (Previously had `VerticaOperator`)
- [x] postgres (Previously had `PostgresOperator`)  Docs already [exists](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html) but requires tweaks to align the style

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by geraj1010** [comment]
To confirm, this is for all operators that were deprecated (and merged) in [#44559](https://github.com/apache/airflow/issues/44559)? Are you looking for additional `HOW-TO` guides for the `The Items`?

**Comment by eladkal** [comment]
> To confirm, this is for all operators that were deprecated (and merged) in [#44559](https://github.com/apache/airflow/issues/44559)? Are you looking for additional `HOW-TO` guides for the `The Items`?

Yes, get what we have for sqlite to the other providers. I assume it's mostly the same with difference of `conn_id`

**Comment by geraj1010** [comment]
For Amazon, I did find mention of `SQLExecuteQueryOperator` for Redshift and Athena, but not RDS.

Redshift: https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/operators/redshift/redshift_sql.html
Athena: https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/operators/athena/athena_sql.html

Should I replace the existing files with `operators.rst` and create a new one for RDS (if needed)?

**Comment by eladkal** [comment]
Amazon is not on the list because the docs there are OK. No need for changes on this provider

**Comment by nailo2c** [comment]
Hi @eladkal could you assign this issue to me? I'd like to give it a try.

**Comment by eladkal** [comment]
@nailo2c are you working on the remaining items?

**Comment by nailo2c** [comment]
@eladkal yes, I'm still working on the remaining items.

**Comment by nailo2c** [comment]
The items:
- [x] Exasol (Previously had ExasolOperator)
- [x] apache.drill (Previously had DrillOperator)
- [x] jdbc (Previously had JdbcOperator)
- [x] microsoft.mssql (Previously had MsSqlOperator)
- [x] mysql (Previously had MySQLOperator)
- [x] oracle (Previously had OracleOperator)
- [x] presto Previously had PrestoOperator)
- [x] snowflake (Previously had SnowflakeOperator)
- [x] trino (Previously had TrinoOperator)
- [x] vertica (Previously had VerticaOperator)
- [x] postgres (Previously had PostgresOperator)

Once #49679 is merged, all items will use SQLExecuteQueryOperator, so I believe this issue can be closed.

**Comment by nailo2c** [comment]
Hi @eladkal, #49679 is merged, so I believe this issue can be closed.
