### ISSUE TITLE
Status of testing of Apache Airflow 2.10.4rc1

### ISSUE THREAD

**Issue by utkarsharma2** [apache/airflow#44811]
### Body

We are kindly requesting that contributors to [Apache Airflow RC 2.10.4rc1](https://pypi.org/project/apache-airflow/2.10.4rc1/) help test the RC.

Please let us know by commenting if the issue is addressed in the latest RC.

- [ ] [Check pool_slots on partial task import instead of execution (#39724) (#42693)](https://github.com/apache/airflow/pull/42693): @karenbraganz
- [ ] [Double-check TaskInstance state if it differs from the Executor state. (#43063)](https://github.com/apache/airflow/pull/43063): @antonysouthworth-halter
- [x] [Allow Utkarsh to run dockerhub image release job (#43588) (#43589)](https://github.com/apache/airflow/pull/43589): @utkarsharma2
- [x] [ Fix Try Selector in Mapped Tasks also on Index 0 (#43590) Backport (#43591)](https://github.com/apache/airflow/pull/43591): @jscheffl
     Linked issues:
     - [Fix Try Selector in Mapped Tasks also on Index 0 (#43590)](https://github.com/apache/airflow/pull/43590)
- [x] [[BACKPORT] Complete automation of version replacement pre-commit for pip and uv … (#43623)](https://github.com/apache/airflow/pull/43623): @potiuk @kaxil
     Linked issues:
     - [Bump ``pip`` to ``24.2`` (#43197)](https://github.com/apache/airflow/pull/43197)
     - [Bump ``uv`` to ``0.4.24`` (#43135)](https://github.com/apache/airflow/pull/43135)
- [x] [[BACKPORT] Allow to switch breeze to use uv internally to create virtualenvs (#43587) (#43624)](https://github.com/apache/airflow/pull/43624): @potiuk
- [x] [[BACKPORT] Remove root warning in image used to build packages in CI (#43597)  (#43625)](https://github.com/apache/airflow/pull/43625): @potiuk
- [x] [ Fix venv numpy example which needs to be 1.26 at least to be working in Python 3.12 (#43653) (#43659)](https://github.com/apache/airflow/pull/43659): @jscheffl
     Linked issues:
     - [Fix venv numpy example which needs to be 1.26 at least to be working in Python 3.12 (#43653)](https://github.com/apache/airflow/pull/43653)
- [x] [[BACKPORT] Fix reproducibility of prepared provider packages (fix flit frontend)… (#43687)](https://github.com/apache/airflow/pull/43687): @potiuk
- [x] [[BACKPORT] Detect situation where Breeze is installed with both pipx and uv (#43… (#43695)](https://github.com/apache/airflow/pull/43695): @potiuk
- [ ] [Disable XCom list ordering by execution_date (#43680) (#43696)](https://github.com/apache/airflow/pull/43696): @pierrejeambrun
- [x] [[BACKPORT] Handle FileNotFound Error returned by missing uv or pipx (#43714) (#43715)](https://github.com/apache/airflow/pull/43715): @potiuk
- [x] [Remove note about MySQL 5 (#43729)](https://github.com/apache/airflow/pull/43729): @eladkal
- [x] [[BACKPORT (Modified)] Prevent using trigger_rule="always" in a dynamic mapped task (#43368) (#43810)](https://github.com/apache/airflow/pull/43810): @shahar1
     Linked issues:
     - [Prevent using `trigger_rule=TriggerRule.ALWAYS` in a task-generated mapping within mapped task groups (#43368)](https://github.com/apache/airflow/pull/43368)
- [x] [#43252 Disable extra links button if link is null or empty (#43844) (#43851)](https://github.com/apache/airflow/pull/43851): @jscheffl @enisnazif
     Linked issues:
     - [#43252 Disable extra links button if link is null or empty (#43844)](https://github.com/apache/airflow/pull/43844)
- [x] [ Correct mime-type in OpenAPI spec (#43879) (#43901)](https://github.com/apache/airflow/pull/43901): @jscheffl @xitep
     Linked issues:
     - [Correct mime-type in OpenAPI spec (#43879)](https://github.com/apache/airflow/pull/43879)
- [ ] [Fix duplication of Task tries in the UI (#43891) (#43950)](https://github.com/apache/airflow/pull/43950): @ephraimbuddy @tirkarthi
     Linked issues:
     - [Duplicate entries in API response when TaskInstanceHistory and TaskInstance have same maximum try number (#41765)](https://github.com/apache/airflow/issues/41765)
- [x] [ Ensure priority weight is capped at 32-bit integer to prevent roll-over (#43611) (#44045)](https://github.com/apache/airflow/pull/44045): @jscheffl
- [x] [ Log message source details are grouped (#43681) (#44070)](https://github.com/apache/airflow/pull/44070): @jscheffl
- [x] [[v2-10-test] Add .dockerignore to target workflow override (#43885) (#44103)](https://github.com/apache/airflow/pull/44103): @potiuk
- [ ] [get_task_instance_try_details API returns TaskInstanceHistory schema … (#44133)](https://github.com/apache/airflow/pull/44133): @pierrejeambrun
- [x] [[v2-10-test] Re-queue tassk when they are stuck in queued (#43520) (#44158)](https://github.com/apache/airflow/pull/44158): @jscheffl @dimberman
     Linked issues:
     - [Allow for retry when tasks are stuck in queued (#43520)](https://github.com/apache/airflow/pull/43520)
- [ ] [[v2-10-test] suppress the warnings where we check for sensitive values (#44148) (#44167)](https://github.com/apache/airflow/pull/44167): @zachliu
- [x] [[v2-10-test] Avoid grouping task instance stats by try_number for dynamic mapped tasks (#44300) (#44319)](https://github.com/apache/airflow/pull/44319): @shahar1
- [ ] [[v2-10-test] Fix problem with inability to remove fields from Connection form (#40421) (#44442)](https://github.com/apache/airflow/pull/44442): @MaksYermak
- [ ] [Fix wrong display of multiline messages in the log after filtering (#44457)](https://github.com/apache/airflow/pull/44457): @jason810496 @Pad71
     Linked issues:
     - [wrong display of multiline messages in the log after filtering by message level (#41265)](https://github.com/apache/airflow/issues/41265)
- [x] [[v2-10-test] Allow "/" in metrics validator (#42934) (#44515)](https://github.com/apache/airflow/pull/44515): @potiuk
- [ ] [[v2-10-test] fix gantt flickering #42215 (#44488) (#44517)](https://github.com/apache/airflow/pull/44517): @darkag
- [x] [[v2-10-test] Fix tests badge in README.md (#44505) (#44587)](https://github.com/apache/airflow/pull/44587): @shahar1
- [ ] [Fix test_deprecated_options_with_new_section (#44647)](https://github.com/apache/airflow/pull/44647): @utkarsharma2
- [x] [[BACKPORT (modified)] Prevent using `trigger_rule=TriggerRule.ALWAYS` in a task-generated mapping within bare tasks (#44751) (#44769)](https://github.com/apache/airflow/pull/44769): @shahar1
     Linked issues:
     - [Prevent using `trigger_rule=TriggerRule.ALWAYS` in a task-generated mapping within bare tasks (#44751)](https://github.com/apache/airflow/pull/44751)
- [ ] [[Backport] Fixing cli test failure in CI (#44679) (#44806)](https://github.com/apache/airflow/pull/44806): @utkarsharma2

Thanks to all who contributed to the release (probably not a complete list!):
@antonysouthworth-halter @Pad71 @karenbraganz @pierrejeambrun @kaxil @potiuk @shahar1 @utkarsharma2 @enisnazif @eladkal @xitep @ephraimbuddy @tirkarthi @jscheffl @jason810496 @dimberman

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by kaxil** [comment]
@utkarsharma2 Was https://github.com/apache/airflow/pull/44155 not included in 2.10.4?

**Comment by potiuk** [comment]
All my changes checked !

**Comment by darkag** [comment]
hello
#44517 works as expected

**Comment by jscheffl** [comment]
Tested or checked code for #43591, #43659, #43851, #43901, #44045, #44158, #44070 and all looks good.

Had a bit of challenges running with breeze (either from TAG 2.10.4rc1 or from main with --use-airflow-version)... but this is not blocking release in my view.

**Comment by potiuk** [comment]
> Had a bit of challenges running with breeze (either from TAG 2.10.4rc1 or from main with --use-airflow-version)... but this is not blocking release in my view.

What challenges :) ?

**Comment by jscheffl** [comment]
> > Had a bit of challenges running with breeze (either from TAG 2.10.4rc1 or from main with --use-airflow-version)... but this is not blocking release in my view.
> 
> What challenges :) ?

(1) using tag 2.10.4rc1 and starting with breeze matching from the tag as well failed in DAG parsing for some examples as the tag / branch does not contani standard provider (providers noch back-ported). As providers are not updated on tag/v2-10-test branch did not further attempted to patch around.

(2) using current main and `breeze down && breeze release-management prepare-provider-packages --include-not-ready-providers --skip-tag-check && rm -v dist/*fab* && breeze start-airflow --python 3.12 --load-example-dags --backend postgres --executor CeleryExecutor --answer y --use-airflow-version 2.10.4rc1 --use-packages-from-dist` failed to start Celery Worker. Needed to use LocalExecutor

Maybe best would have been using the docker images directly :-D

**Comment by shahar1** [comment]
All of my changes were tested :)

**Comment by jason810496** [comment]
Hi, https://github.com/apache/airflow/pull/44457 ( Fix wrong display of multiline messages in the log after filtering ) works as expected, Thanks !
![Fix wrong display of multiline messages in the log after filtering](https://github.com/user-attachments/assets/f2059af9-ebd7-4c0c-bedd-a199f8407cbd)
