### ISSUE TITLE
Airflow 2 to 3 auto migration rules - ruff (44080 ~ 45017)

### ISSUE THREAD

**Issue by Lee-W** [apache/airflow#45212]
### Description
Parent issue: https://github.com/apache/airflow/issues/41641

#### name
* [x] `TriggerRule.NONE_FAILED_OR_SKIPPED` (from #44475)
* [x] argument `appbuilder` in BaseAuthManager and its subclasses (from #45009)

#### context key
* [ ] `conf` (from #44820)

### AIR303
* [x] `airflow.config_templates.default_celery.DEFAULT_CELERY_CONFIG` → `airflow.providers.celery.executors.default_celery.DEFAULT_CELERY_CONFIG` (from #45017) (3.3.0)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Lee-W** [comment]
the appbuilder rule has been added to https://github.com/astral-sh/ruff/pull/15083

**Comment by Lee-W** [comment]
https://github.com/astral-sh/ruff/pull/15145 created for the 303 one

**Comment by Lee-W** [comment]
the remaining rule has been addressed by https://github.com/astral-sh/ruff/pull/15144

**Comment by Lee-W** [comment]
as we already have `uv run  scripts/ci/pre_commit/significant_newsfragments_checker.py --list-todo`, we don't need to track it this way. Close this issue and use the parent issue to track
