### ISSUE TITLE
Status of testing Providers that were prepared on December 30, 2024

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#45298]
### Body

I have a kind request for all the contributors to the latest provider packages release.
Could you please help us to test the RC versions of the providers?

The guidelines on how to test providers can be found in

[Verify providers by contributors](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-the-release-candidate-by-contributors)

Let us know in the comment, whether the issue is addressed.

Those are providers that require testing as there were some substantial changes introduced:

## Provider [fab: 1.5.2rc1](https://pypi.org/project/apache-airflow-providers-fab/1.5.2rc1)
   - [x] [Correctly import isabs from os.path (#45178)](https://github.com/apache/airflow/pull/45178): @potiuk
     Linked issues:
       - [x] [Linked Issue #45139](https://github.com/apache/airflow/pull/45139): @shubhamraj-git
   - [x] [Invalidate user session on password reset (#45139)](https://github.com/apache/airflow/pull/45139): @shubhamraj-git

All users involved in the PRs:
@potiuk @shubhamraj-git

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
Installed the new FAB provider with airflow 2.10.4. All works fine, including the scenario of CLI password reset.

**Comment by amoghrajesh** [comment]
Tested out the scenario of password reset from the CLI and it successfully invalidates the session, after installing the new FAB provider with Airflow 2.10.4 version using breeze. Looks good!

**Comment by shubhamraj-git** [comment]
Installed the airflow 2.10.4, and installed the fab provider 1.5.2rc1
Tested out the CLI password reset scenario, it successfully invalidates.
It works fine.

Thanks.

**Comment by eladkal** [comment]
Thank you everyone. Providers are released.

I invite everyone to help improve providers for the next release, a list of open issues can be found [here](https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Aproviders).
