### ISSUE TITLE
Move out all unnecessary binaries installed in CI image

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#8785]
**Description**

We have a lot of unnecessary binaries/libraries baked into the CI image. And we can move it out in the form of integration images downloaded separately by docker-compose. 

Those are:

- [x] Kind - not needed as long as we move it out of the container #8782
- [x] KubeCTL - not needed as long as we move kind out of the container #8782 
- [x] Hadoop Distro - could be a separate docker -run Hadoop most likely #8783
- [x] Minicluster - could be a separate docker run minicluster mostl likely #8784
- [x] Singularity - seems we did not need that in the first place #8774
- [x] Gcloud - separate docker image pulled from google/cloud-sdk:latest #8946
- [x] Aws-cli - separate docker image pulled from amazon/aws-cli #8947 
- [x] docker-ce (likely)  -  docker is not needed after moving kubernetes to host #9126 

**Use case / motivation**

Make the image download faster and only download images when they are used

**Related Issues**

 #8782, #8782,, #8783, #8784, #8774, #8946, #8947

**Comment by ashb** [comment]
@potiuk Do our _CI_ tests need `gcloud` or `aws` CLI tools? Between them the add something like 500Mb to the image.

(It would be _really_ nice if docker let you easily compose layers from different images, without having to rebuild it)

**Comment by mik-laj** [comment]
@ashb we use `gcloud` and `aws-cli` in system tests. We don't always have an operator. gcloud is even used by the Airflow operators. 
https://github.com/apache/airflow/blob/master/airflow/providers/google/cloud/operators/kubernetes_engine.py#L267

**Comment by ashb** [comment]
@mik-laj That's why I asked about CI, not system tests.

A large part of the slow down for our tests was pulling images, so if we can reduce the size of that image we can speed our builds up.

Trade off is to decide if maintaining a second image is worth it or not.

**Comment by mik-laj** [comment]
@ashb On CI, we don't use it yet.

**Comment by ashb** [comment]
Might be worth investigating, at least once we've gotten rid of all the items on this list which are far bigger.

https://github.com/wagoodman/dive is a useful too for exploring docker images

**Comment by potiuk** [comment]
We can get those also used from docker images. 

We have now the docker socket mapped inside the docker image so we can do `docker pull google/cloud-sdk:latest` - we can even write simple scripts that can do it seamlessly the first time you run 'gcloud' command .

**Comment by potiuk** [comment]
That's basicallly what I planned to do with all the binaries -> but it requires a bit of work. If anyone can pick this up - I am more than happy to review :)

**Comment by potiuk** [comment]
@ashb @mik-laj -> issues added for gcloud and awscli. Feel free to implement  if you have time

**Comment by ashb** [comment]
Next chunkiest layers (in order they appear in the Dockerfile):

- 413MB - Installing node and yarn
- 385MB - docker-ce
- 43MB kubectl
- 438MB - gcloud-sdk (aws CLI is only 72MB)
- 1.4GB - all of the python deps (`pip install -e .[$AIRFLOW_EXTRAS]` - not much we can do about that I don't think)
- 219MB - node deps (`yarn --cwd airflow/www install --frozen-lockfile --no-cache`)

(Not saying we can/should get rid of all of those, just listing large layers)

**Comment by potiuk** [comment]
Kubectl gone already after merging #8265

**Comment by potiuk** [comment]
I think docker can be removed as well. Let me see.
