### ISSUE TITLE
Officially support HA for scheduler component (AIP-15)

### ISSUE THREAD

**Issue by ashb** [apache/airflow#9630]
https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=103092651

- [x] #10729 Detect orphaned task instances by SchedulerJob id and heartbeat
- [x] #10881 Mark task as failed when it fails sending in Celery
- [x] #10949 Allow CeleryExecutor to "adopt" an orphaned queued or running task 
- [x] #10996 Allow Kubernetes executor to adopt tasks 
- [x] #11244 Add adoption support in to the new CeleryKubernetesExecutor (added in #10901)
- [x] The big one - scheduler HA pr #10956
- [x] #11498 Add "fast follow" to end of task run (this is a mini "scheduler" run at the end of task execution.)
- [x] Performance optimisation PRs
- [x] Decide if we need https://github.com/apache/airflow/pull/10933 or not
- [x] Ensure smart sensor DAG is loaded by scheduler even when DAG serialization is enabled.

**Comment by mik-laj** [comment]
@ashb @kaxil Could you please share some more details about the change?

In particular, I would like to answer the following questions:
* Is there a plan to implement this AIP? If so, can I have any preview? This is essential for us to successfully release Airflow 2.0
* Do you need help with this task? If you plan to do it yourself, it's okay, but if you would like other people to contribute, I would like to know how to do it.  
* How can I get more information on this subject? Slack channel, DM, Jira, Email? Each contributor has a different preference for communication.

With these questions, I would like to remove barriers for new contributors who do not follow the activity of the entire community.  Hope this helps speed up your work on key features for the new Airflow 2.0.

**Comment by ashb** [comment]
Yes, I have started work on this, and got reasonably far with it (far enough to start running performance tests, but there are a few things I still have as to-do's such as SLAs or per task concurrency limits) but unfortunately I want able to get the code in a situation where I could pr it before going off on paternity leave - as soon as I'm back (September) getting this landed is my top priority.

**Comment by mik-laj** [comment]
Link: https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=103092651

**Comment by ryw** [comment]
@ashb since you're done w/ work for 2.0 on this ticket, maybe close this out and create any new tickets for things you want to do post-2.0?
